kubernetes-sigs/kueue

README.md

Add more details and links related to the project

---

config/crd/kustomization.yaml
config/crd/patches/cainjection_in_capacities.yaml
config/crd/patches/cainjection_in_queuedworkloads.yaml
config/crd/patches/cainjection_in_queues.yaml
config/crd/patches/webhook_in_capacities.yaml
config/crd/patches/webhook_in_queuedworkloads.yaml
config/crd/patches/webhook_in_queues.yaml
config/manager/controller_manager_config.yaml
config/rbac/capacity_editor_role.yaml
config/rbac/capacity_viewer_role.yaml
config/rbac/queue_editor_role.yaml
config/rbac/queue_viewer_role.yaml
config/rbac/queuedworkload_editor_role.yaml
config/rbac/queuedworkload_viewer_role.yaml
config/rbac/role.yaml
controllers/capacity_controller.go
controllers/job_controller.go
controllers/queue_controller.go
controllers/queuedworkload_controller.go
main.go

group transfer to x-k8s.io

---

pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/workload/workload.go
pkg/workload/workload_test.go

Make TotalRequests in workload.Info a list instead of map

---

Makefile

/kind cleanup
Ci-Verify is always welcomed :)

Add verify checks for go code

---

config/samples/sample-job.yaml

update annotation in sample

---

Makefile

Add the missing license header for source file

---

Makefile

/kind cleanup
Ensure we don't forget to update manifests or generate code.
Part of #20

Verify manifests and code generation

---

pkg/util/testing/wrappers.go
test/integration/controller/job/job_controller_test.go
test/integration/scheduler/scheduler_test.go
test/integration/scheduler/suite_test.go

/kind test
Adds integration test that covers end-to-end scheduling of jobs.
Fixes  #30

Added scheduler integration tests

---

pkg/controller/workload/job/job_controller.go

/kind cleanup
Refactor job-controller so that stopping a job due to non-matching workloads is done in one place
Fixes #

refactor job suspension due to multiple or non-matching workloads in job-controller

---

pkg/capacity/capacity.go
pkg/capacity/capacity_test.go
pkg/capacity/snapshot.go
pkg/capacity/snapshot_test.go
pkg/controller/core/capacity_controller.go
pkg/controller/workload/job/job_controller.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind cleanup
Refactor some variables collide with buildin func, we should refactor it to avoid some troubles.
e.g. cap new copy and so on.
Fixes #41

Refactor some variables collide with buildin func

---

OWNERS

I hope you would agree to this as a first step towards becoming maintainers in the future.
Thanks for contributing from the get go and for being part of the core Kueue team, I hope we continue this collaboration and together make this a successful project.
/assign @alculquicondor @ArangoGutierrez @denkensk

add ArangoGutierrez and denkensk as reviewers

---

Makefile

/kind bug
My apologies, forgot to edit this on https://github.com/kubernetes/test-infra/pull/25375

Fix deploy command in Makefile

---

main.go
pkg/constants/constants.go
pkg/controller/workload/job/job_controller.go
pkg/util/testing/core.go
test/integration/controller/job/job_controller_test.go
test/integration/scheduler/suite_test.go

/kind feature
Fixes #9
```bash
Name:           sample-job-4q87f
Namespace:      default
Selector:       controller-uid=6576a66d-dd4a-48e9-ba92-97d7db1ea9cd
Labels:         controller-uid=6576a66d-dd4a-48e9-ba92-97d7db1ea9cd
job-name=sample-job-4q87f
Annotations:    kueue.x-k8s.io/queue-name: main
Parallelism:    3
Completions:    3
Start Time:     Sat, 19 Feb 2022 11:23:46 +0800
Completed At:   Sat, 19 Feb 2022 11:23:57 +0800
Duration:       11s
Pods Statuses:  0 Running / 3 Succeeded / 0 Failed
Pod Template:
Labels:  controller-uid=6576a66d-dd4a-48e9-ba92-97d7db1ea9cd
job-name=sample-job-4q87f
Containers:
pi:
Image:      perl
Port:       <none>
Host Port:  <none>
Command:
perl
-Mbignum=bpi
-wle
print bpi(2000)
Limits:
cpu:     1
memory:  200Mi
Requests:
cpu:        1
memory:     200Mi …
```

Add queuedWorkload created event to batch/job

---

pkg/capacity/capacity.go
pkg/capacity/capacity_test.go
pkg/capacity/snapshot.go
pkg/capacity/snapshot_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/workload/workload.go

/kind cleanup
Will simplify calculation of used/borrowed resources.
Part of #7

Keep parsed resource quantities in capacity cache

---

.gitignore
Makefile
go.mod
go.sum

/kind cleanup
- Sync the go.mod & go.sum by running `go mod vendor`
- Add `vendor` to .gitignore
- Add a Makefile entry "gomod-verify" to error out unsynced go.mod & go.sum
Fixes #

Add go.mod verify checks

---

Makefile
pkg/queue/manager_test.go
pkg/scheduler/scheduler.go

/kind cleanup
First part of the work for https://github.com/kubernetes-sigs/kueue/issues/67
Second part: https://github.com/kubernetes/test-infra/pull/25443
Fixes https://github.com/kubernetes-sigs/kueue/issues/67
None

cleanup: fix race condition

---

api/v1alpha1/queue_types.go
config/crd/bases/kueue.x-k8s.io_queues.yaml
main.go
pkg/controller/core/queue_controller.go
pkg/queue/manager.go
pkg/queue/manager_test.go
pkg/queue/queue.go
test/integration/scheduler/suite_test.go

/kind feature
initial implementation for  #5

Add status report for kueue.Queue

---

Makefile

/kind cleanup
Fixes #
TODO: migrate to Ginko v2
- https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

Add ACK_GINKGO_DEPRECATIONS ack to clean test logs

---

api/v1alpha1/queue_types.go
config/crd/bases/kueue.x-k8s.io_queues.yaml
pkg/util/testing/wrappers.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/queue_controller_test.go
test/integration/framework/framework.go

Add integration tests for Queue controller

---

api/v1alpha1/queuedworkload_types.go
config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml

/kind feature
first part of #92

fix typo in api

---

pkg/cache/cache.go
pkg/cache/snapshot.go
pkg/cache/snapshot_test.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/queuedworkload_controller.go
pkg/controller/workload/job/job_controller.go
pkg/queue/manager.go
pkg/queue/manager_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/job/job_controller_test.go
test/integration/scheduler/scheduler_test.go

Followup on #95
/kind cleanup
Fixes #
This is a variable rename patch. This patch doesn't introduces any changes
FollowUp on #95

Follow up on Capacity -> ClusterQueue

---

.github/BUG_REPORT.md
.github/ENHANCEMENT.md
.github/NEW_RELEASE.md
.github/SUPPORT.md
RELEASE.md

Add github templates for diff purposes

---

Makefile
go.mod
go.sum
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/queue_controller_test.go
test/integration/controller/core/suite_test.go
test/integration/controller/job/job_controller_test.go
test/integration/controller/job/suite_test.go
test/integration/framework/framework.go
test/integration/scheduler/scheduler_test.go
test/integration/scheduler/suite_test.go

Migrate to GINKO/v2

---

api/v1alpha1/clusterqueue_types.go
config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
pkg/controller/core/clusterqueue_controller.go
test/integration/controller/core/clusterqueue_controller_test.go

/kind cleanup
Part of #7
Part 1 of https://github.com/kubernetes-sigs/kueue/issues/7#issuecomment-1062817277

Rename AssignedWorkloads to AdmittedWorkloads

---

api/v1alpha1/queue_types.go
config/crd/bases/kueue.x-k8s.io_queues.yaml
pkg/controller/core/queue_controller.go
pkg/queue/manager.go
pkg/queue/manager_test.go
test/integration/controller/core/queue_controller_test.go

Enhance Kueue.Queue.Status test suite

---

api/v1alpha1/clusterqueue_types.go
config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
pkg/controller/core/clusterqueue_controller.go
pkg/queue/manager.go
test/integration/controller/core/clusterqueue_controller_test.go

/kind feature
Remaining implementation for #7
Add pendingWrkloads to Kueue.ClusterQueue.Status

Kueue.ClusterQueue.Status Add pendingWorkloads

---

Makefile
cloudbuild.yaml

Fix image tag for postsubmit job

---

config/rbac/role.yaml
pkg/controller/core/clusterqueue_controller.go

Fixing RBAC roles

---

api/v1alpha1/clusterqueue_types.go
config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml

Fix json tags

---

pkg/constants/constants.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/queue_controller.go

Temporal solution for #101

---

pkg/queue/manager.go
pkg/queue/queue.go
pkg/queue/queue_test.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/wrappers.go

/kind feature
Use QueueStrategy in ClusterQueue construct.
1/n of #8

Use QueueStrategy in ClusterQueue construct

---

config/rbac/role.yaml
main.go
pkg/controller/workload/job/job_controller.go

/kind bug
/kind cleanup
Fixes #
Missed during https://github.com/kubernetes-sigs/kueue/pull/127

Fix RBAC after adding Priority support 

---

config/manager/manager.yaml
config/samples/minimal.yaml

Fixes #
set `imagePullPolicy` to Always on main/devel branch, this should be changed to `ifNotePresent` when cutting a release, and left `Always` on main branch, for development purposes.
Also add `namespaceSelector: {}` to sample ClusterQueue, this is causing not wanted behavior while local devel testing

Add imagePullPolicy to manager deployment

---

README.md

Update README quick start section

---

config/rbac/role.yaml
pkg/controller/workload/job/job_controller.go

/kind bug
Fixes #131  
pr miss `watch` in this pr #128

update RBAC for PriorityClass

---

Makefile

/kind cleanup
Fixes #
Since go1.16 `go get` for installing pkg binaries has been deprecated, the right way is now `go install`, which allow us to remove the `go-get-tool`  on the Makefile.
THis patch also requires kustomize to be bumped to v4

Remove go-get-tool helper

---

Makefile

/kind bug
#136 forgot to set the version for kustomize.
Fixes #

Fix kustomize installation

---

README.md
config/samples/kueue_v1alpha1_resourceflavor.yaml

/kind cleanup
remove unused contents in readme and sample. make it clean for users.
Fixes #

update readme and sample

---

README.md
docs/concepts/README.md
docs/concepts/cluster_queue.md
docs/concepts/queue.md
docs/concepts/queued_workload.md

Add a concept page for each API resource and a glossary for commonly used terms.
Part of #64

Add a concept page for each API resource

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
docs/concepts/cluster_queue.md
pkg/queue/manager_test.go
pkg/queue/queue_test.go
pkg/scheduler/scheduler_test.go

Fix a couple typos

---

main.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/queuedworkload_controller.go
pkg/queue/manager.go
pkg/scheduler/scheduler.go
pkg/workload/workload.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/queue_controller_test.go
test/integration/controller/core/queuedworkload_controller_test.go
test/integration/controller/core/suite_test.go
test/integration/scheduler/suite_test.go

Co-authored-by: Aldo Culquicondor <1299064+alculquicondor@users.noreply.github.com>
Fixes #
re-do of https://github.com/kubernetes-sigs/kueue/pull/125 thanks to GitHub

Add pending condition to queuedworkloads

---

api/v1alpha1/clusterqueue_types.go
config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml

Fix typo in json field name

---

README.md
config/samples/single-clusterqueue-setup.yaml
docs/README.md
docs/concepts/README.md
docs/tasks/README.md
docs/tasks/administer_cluster_resources.md

Explains the setup for a single cluster queue.
Part of #64

Add task for single cluster queue setup

---

pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/queuedworkload_controller.go
pkg/queue/manager.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/queuedworkload_controller_test.go
test/integration/framework/framework.go

/kind bug
To keep a correct track of number of pending workloads in a ClusterQueue
Fixes #148

Fix clusterqueue controller to update pending workloads

---

config/samples/sample-job.yaml
docs/tasks/README.md
docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md

Shows how to run jobs and monitor them
Part of #64

Add task for run jobs

---

go.mod
main.go
pkg/scheduler/scheduler.go
test/integration/framework/framework.go
test/integration/scheduler/scheduler_test.go

/kind cleanup
Hopefully will help us spot the flaky failure #158 
Fixes #

Increase logging during integration tests

---

README.md
docs/concepts/cluster_queue.md
docs/concepts/queued_workload.md
docs/tasks/README.md
docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md

Implements the editorial review from #157 
Part of #64

Editorial review on user docs

---

pkg/scheduler/scheduler.go

Add event when failing to schedule a QW

---

pkg/scheduler/scheduler.go

Add the reason for failing to admit a workload in the event and condition message. We can still do more by plumbing reason related to failed to match affinity or taints. 
/kind cleanup

Add more details to the failure to admit event and condition message

---

docs/concepts/README.md

fix: incorrect anchor point for resource-flavor

---

docs/concepts/cluster_queue.md
docs/tasks/administer_cluster_quotas.md

Add details for managing cohorts

---

docs/concepts/cluster_queue.md
docs/concepts/queued_workload.md

Add concept for priority and queueing strategy

---

pkg/scheduler/scheduler.go

/kind cleanup
variables renaming for consistency
Fixes #

Cleanup: variables renaming

---

docs/README.md
docs/setup/README.md
docs/setup/install.md
docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md
docs/tasks/setup_rbac.md

Docs: Add install doc pages

---

pkg/cache/cache.go

/kind cleanup
remove redup error message
Fixes #

remove duplicate error message

---

docs/tasks/README.md

fix: error jump link for setup_rbac.md

---

Makefile
README.md
config/manager/kustomization.yaml
docs/setup/install.md

Fixes #
We use `devel` as the image tag for the `main` branch.

Add instructions for one-line installation

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
.gitignore
Makefile
RELEASE.md

Documents the release process
Also adds a make rule to build the artifacts
Fixes #
/hold
Depends on #195

Add release process

---

pkg/queue/cluster_queue_best_effort_fifo.go
pkg/queue/cluster_queue_best_effort_fifo_test.go
pkg/queue/cluster_queue_impl.go
pkg/queue/cluster_queue_interface.go
pkg/queue/manager.go
pkg/queue/manager_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
test/integration/scheduler/scheduler_test.go

/kind bug
https://github.com/kubernetes-sigs/kueue/pull/135#discussion_r840729523
We have a case where we requeue because the workload didn't fit. But we also have a case where we requeue because we admitted workloads in another CQ that had higher priority, even though they might still fit in the next scheduling cycle. I don't think we should punish those workloads. They should skip the inadmissible stage.

Distinguish workload type before requeue

---

Makefile
config/manager/kustomization.yaml

/kind feature
To facilitate the installation of the latest image of the release.
Part of #197

Match release-0.1 tags in manifests

---

docs/setup/install.md

Part of #197 
Sorry @ArangoGutierrez that I didn't understand your comment earlier.

Fix install instructions for release

---

README.md
docs/setup/install.md

Add installation instructions for a released version

---

test/integration/controller/core/suite_test.go
test/integration/controller/job/suite_test.go
test/integration/framework/framework.go
test/integration/scheduler/scheduler_test.go
test/integration/scheduler/suite_test.go

/kind cleanup
Cleans up the scheduler integration test to use the patterns we settled on as of late.
Fixes #

Cleanup scheduler integration tests

---

pkg/controller/core/workload_controller.go
pkg/workload/workload.go
test/integration/controller/core/workload_controller_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/201

feat: sync workload condition when admitted

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

Add examples from the latest release
Fixes #

Add learnings and examples from the last release

---

pkg/queue/cluster_queue_best_effort_fifo.go
pkg/queue/cluster_queue_impl.go
pkg/queue/cluster_queue_strict_fifo.go
pkg/queue/queue.go
pkg/util/heap/heap.go
pkg/util/heap/heap_test.go
test/integration/scheduler/scheduler_test.go

introduce Heap package

---

pkg/cache/cache_test.go

/kind cleanup
Simple change but more readable and descriptive. 
Fixes #

use struct `Resources` for `UsedResources` in tests

---

pkg/queue/cluster_queue_impl_test.go

test: add testcases to cover ClusterQueueImpl methods

---

config/rbac/role.yaml
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/workload_controller.go
pkg/util/testing/wrappers.go
pkg/workload/workload.go
pkg/workload/workload_test.go
test/integration/controller/core/workload_controller_test.go
test/integration/framework/framework.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/119

feat: handle pod overhead

---

pkg/scheduler/scheduler.go

/kind cleanup
To satisfy #229 
Fixes #

Fix import block in scheduler

---

.github/ISSUE_TEMPLATE/ENHANCEMENT.md

Lists possible artifacts that an enhancement entails
Fixes #

Add task list to enhancements template

---

pkg/controller/core/workload_controller.go

/kind cleanup
Fixes #
This is how it displays: 
```
13519 workload_controller.go:274] RuntimeClass.node.k8s.io "kata" not foundCould not get RuntimeClass
```
And this is how I looks like after cleanup:
```
workload_controller.go:274] Could not get RuntimeClass: RuntimeClass.node.k8s.io "kata" not found
```

Fix format of error logging

---

docs/setup/install.md

Documents how to change the default configuration of a released version
Part of https://github.com/kubernetes-sigs/kueue/issues/169

Add docs on how to change the configuration

---

pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/189
Errors like: `Workload didn't fit: request cpu resource error: [flavor one doesn't match with node affinity, flavor two still lack 100 after borrowing, flavor three borrowing limit is exceeded]`

feat: add detailed errors to assignFlavors

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/snapshot.go
pkg/cache/snapshot_test.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/core.go
pkg/controller/core/resourceflavor_controller.go
pkg/controller/core/workload_controller.go
pkg/queue/manager.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
test/integration/controller/core/workload_controller_test.go
test/integration/framework/framework.go
test/integration/scheduler/scheduler_test.go

/kind feature
Part of https://github.com/kubernetes-sigs/kueue/issues/134

feat: clusterQueue add status field

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
Makefile

/kind cleanup
Fixes #226
```release-note
NONE
```

Rename image to registry.k8s.io/kueue/kueue

---

main.go
pkg/controller/core/resourceflavor_controller.go
pkg/queue/manager.go
pkg/queue/manager_test.go
pkg/queue/status_checker.go
pkg/scheduler/scheduler_test.go
test/integration/controller/core/suite_test.go
test/integration/scheduler/suite_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/251

feat: filter inactive clusterQueues in scheduling

---

OWNERS

@denkensk has been an important contributor to the project since it was first published. Over time, he has demonstrated good technical judgement, thoroughness in designs, coding and reviews. 
Fixes #

Promoting denkensk to approver

---

pkg/queue/cluster_queue_best_effort_fifo.go
pkg/queue/cluster_queue_best_effort_fifo_test.go
pkg/queue/cluster_queue_impl.go
pkg/queue/cluster_queue_impl_test.go
pkg/queue/cluster_queue_interface.go
pkg/queue/cluster_queue_strict_fifo_test.go
pkg/queue/manager.go
pkg/queue/queue.go
pkg/workload/workload.go

/kind cleanup
call `NewInfo` in `manager.go` to improve the performance.
ref: https://github.com/kubernetes-sigs/kueue/issues/162

do workload.NewInfo when inserting and updating

---

pkg/cache/cache_test.go

/kind cleanup
Refactored TestCacheWorkloadOperations so that each test case is independent of the others. I also added some missing test cases as well. Thanks for your review! 
Fixes https://github.com/kubernetes-sigs/kueue/issues/72

Refactor TestCacheWorkloadOperations

---

CHANGELOG/CHANGELOG-0.1.md
pkg/queue/cluster_queue_best_effort_fifo.go
pkg/queue/cluster_queue_best_effort_fifo_test.go

cherry-pick: Fix number of pending workloads in a BestEffortFIFO ClusterQueue

---

hack/cherry_pick_pull.sh

Feat: add cherry-pick script

---

README.md
docs/setup/install.md

https://pkg.go.dev/sigs.k8s.io/kueue@v0.1.1/apis/config/v1alpha1
Fixes #

Update Readme and Docs to v0.1.1

---

test/integration/scheduler/scheduler_test.go

/kind cleanup
Part commit of https://github.com/kubernetes-sigs/kueue/pull/284, just including the refactor works of scheduler tests.

Refactor tests in scheduler

---

test/integration/controller/core/clusterqueue_controller_test.go

/kind cleanup
Part commit of https://github.com/kubernetes-sigs/kueue/pull/284, just including the refactor works of clusterqueue controller tests.

Refactor tests in clusterqueue controller

---

config/rbac/role.yaml
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/core.go
pkg/controller/core/queue_controller.go
pkg/controller/core/resourceflavor_controller.go
pkg/util/testing/not_found_error_cmp.go
test/integration/controller/core/resourceflavor_controller_test.go
test/integration/scheduler/scheduler_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/249

manage a finalizer for resourceFlavor based on usage by cluster queues

---

test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/job/job_controller_test.go

Cleanup: use BeNotFoundError for error validation

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/controller/core/clusterqueue_controller.go
test/integration/scheduler/scheduler_test.go

Trigger re-queueing of workloads on namespace label update

---

apis/kueue/v1alpha1/clusterqueue_webhook.go
config/webhook/manifests.yaml
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/core.go
test/integration/webhook/v1alpha1/clusterqueue_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/285
None

Add webhook defaulter to clusterQueue

---

apis/kueue/v1alpha1/workload_webhook.go
apis/kueue/v1alpha1/workload_webhook_test.go
test/integration/webhook/v1alpha1/workload_test.go

/kind feature
Part of https://github.com/kubernetes-sigs/kueue/issues/171

Add validations to workload

---

test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/resourceflavor_controller_test.go

/kind cleanup
Fixes #
Forget to address the ToDo.

Cleanup: simplify tests in validating finalizer creating

---

apis/kueue/v1alpha1/workload_webhook.go
apis/kueue/v1alpha1/workload_webhook_test.go
test/integration/scheduler/scheduler_test.go
test/integration/webhook/v1alpha1/workload_test.go

/kind feature
When priorityClassName is set, priority should not be nil.
Refer to https://github.com/kubernetes-sigs/kueue/pull/304#issuecomment-1204921639

add validation to workload priority

---

pkg/util/testing/wrappers.go
test/integration/controller/job/job_controller_test.go
test/integration/controller/job/suite_test.go
test/integration/framework/framework.go
test/integration/scheduler/scheduler_test.go
test/integration/scheduler/suite_test.go

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it:**
Made scheduler integration tests independent of job controller
**Which issue(s) this PR fixes:**
Fixes #155 
**Special notes for your reviewer:**

Cleanup: scheduler tests independent of job controller

---

OWNERS

/kind document
Fixes #
Help reviewing PRs

nominate kerthcet as kueue reviewer

---

pkg/controller/core/workload_controller.go

Replace if-else with switch for readability

---

apis/kueue/v1alpha1/clusterqueue_types.go
apis/kueue/v1alpha1/resourceflavor_types.go
apis/kueue/v1alpha1/workload_types.go
config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/crd/bases/kueue.x-k8s.io_workloads.yaml

Update API docs to reflect changes in webhooks.
Fixes #

Update API docs with defaulting and validation

---

apis/kueue/webhooks/workload_webhook.go
apis/kueue/webhooks/workload_webhook_test.go
pkg/util/testing/wrappers.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/328
Ignore the validation of `Each resourceName should be listed in the pod spec, although it might be too cumbersome to validate, so we could ignore it.`

Validate Workload admission

---

CHANGELOG/CHANGELOG-0.2.md
docs/concepts/README.md
docs/reference/README.m
docs/reference/metrics.md
docs/setup/README.md
docs/setup/install.md
pkg/metrics/metrics.go

Explain how to install metrics scraping.
Show which metrics are available.
Fixes #

Add docs to install and use metrics

---

CHANGELOG/CHANGELOG-0.2.md
README.md
docs/concepts/cluster_queue.md
docs/concepts/local_queue.md
docs/setup/install.md

I accidentally deleted some commits from #351 instead of squashing.
Fixes #

Recover updates to docs and release notes

---

README.md
docs/setup/install.md

Part of #352
This will mark the start of release-0.3

Update latest version

---

docs/concepts/cluster_queue.md
docs/concepts/workload.md
docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md

Change references of v1alpha1 to v1alpha2 in docs

---

docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md
docs/tasks/setup_rbac.md

I fixed the broken links in the documents.
Fixes #

Fix the broken links in the documents

---

docs/concepts/cluster_queue.md

Fixes a link issue in cluster_queue readme
Fixes #367

doc fix for admitted

---

docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md
docs/tasks/setup_rbac.md

Cherry pick of #368 on release-0.2.
#368: Fix broken links in the documents
```release-note
```

Automated cherry pick of #368: Fix broken links in the documents

---

docs/concepts/cluster_queue.md

Cherry pick of PR #370 
Add a documentation fix into the release 0.2.
Fixes #

Cherry Pick Into Release 0.2: doc fix for admitted section

---

cloudbuild.yaml

/kind feature
As described in [this](https://github.com/kubernetes-sigs/kueue/pull/375#issuecomment-1239521085), I updated the builder image.
Fixes #

Update the builder image

---

Makefile
cloudbuild.yaml
docs/setup/install.md

/kind bug
As discussed in [this](https://github.com/kubernetes-sigs/kueue/pull/378#issuecomment-1239792325), I fixed the command for cloud build.
Fixes #

Fix the command for cloud build

---

Makefile

/kind cleanup
I fixed make target for unit tests.
Part-of #362

Fix make target for unit tests

---

docs/concepts/cluster_queue.md
docs/concepts/workload.md

I fixed the broken links for admission.
Fixes #

Fix the broken links for admission

---

pkg/controller/workload/job/job_controller.go

/kind cleanup
I fixed some typo comments for the pkg `controller/workload/job`.
Fixes #

Fix some typo comments for the pkg controller/workload/job

---

test/integration/scheduler/scheduler_test.go

/kind cleanup
Regroup test to reduce setup code.
Fixes #

Regroup scheduler integration tests

---

pkg/controller/core/core.go
pkg/queue/cluster_queue_interface.go

/kind cleanup
I fixed some wrong comments and messages.
Fixes #

Fix some wrong comments and messages

---

test/integration/scheduler/scheduler_test.go

/kind cleanup
Test that, in a cohort, workloads in cluster queues that don't need to borrow are admitted before workloads in cluster queues that need to borrow, even if they were created later.
Fixes #

Add test for returning borrowed capacity

---

README.md

To give a clear signal to users about the status of the project.
Fixes #

Add status of production readiness

---

main.go
main_test.go

/kind feature
/kind cleanup
Fixes #

leaderElectionID should be empty when leaderElection is disabled

---

apis/config/v1alpha2/defaults.go
apis/config/v1alpha2/defaults_test.go
main.go
main_test.go

/kind cleanup
As discussed in [this](https://github.com/kubernetes-sigs/kueue/pull/362#issuecomment-1232041979), I implemented the defaulting webhooks to set the default values for `ControllerManagerConfigurationSpec`.
Fixes #

Consolidate defaulting for ControllerManagerConfigurationSpec

---

apis/kueue/v1alpha2/clusterqueue_types.go
apis/kueue/v1alpha2/resourceflavor_types.go
apis/kueue/v1alpha2/workload_types.go
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml

Add shortnames to kueue APIs

---

pkg/scheduler/scheduler.go

Add requeue reason to log

---

apis/kueue/webhooks/clusterqueue_webhook.go
apis/kueue/webhooks/localqueue_webhook.go
apis/kueue/webhooks/resourceflavor_webhook.go
apis/kueue/webhooks/workload_webhook.go
config/components/webhook/manifests.yaml
main.go
pkg/controller/workload/job/job_webhook.go
pkg/controller/workload/job/job_webhook_test.go
test/integration/controller/job/job_controller_test.go
test/integration/controller/job/job_webhook_test.go
test/integration/controller/job/suite_test.go

/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/412

Add webhook to Job controller

---

.github/dependabot.yml

/kind feature
We are adding the dependabot github bot to this repo.
This will look over the packages in your go.mod and create a PR for updates.  
The PR has a series of instructions to manage the PR (rebase, ignore, close, ignore dependency, etc).  
Fixes #435

dependabot addition to repo

---

.github/dependabot.yml

Dependabot doesn't allow you to set ignore-minor-and-major for all dependencies.  
/kind bug
We will just apply this ignore rule to all k8s.io/* packages.

add dependency-name to dependabot for go

---

apis/kueue/v1alpha2/resourceflavor_types.go
apis/kueue/v1alpha2/zz_generated.deepcopy.go
apis/kueue/webhooks/resourceflavor_webhook.go
apis/kueue/webhooks/resourceflavor_webhook_test.go
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
docs/concepts/cluster_queue.md
docs/tasks/administer_cluster_quotas.md
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/snapshot_test.go
pkg/controller/workload/job/job_controller.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/wrappers.go

This is because some components like helm or argocd will add its own labels to owned objects
for management, in this situation, when we use them to deploy resourceFlavor, unexpected labels
will be added to resourceFlavor which will lead to pods pending for corresponding jobs will be added
these labels to their node selector automatically
/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/425

Add a new field nodeSelector to resourceFlavor to replace original metadata.labels

---

pkg/scheduler/flavorassigner/flavorassigner.go
pkg/scheduler/flavorassigner/flavorassigner_test.go

/kind cleanup
Extracts the logic of accumulating usage and borrowing for a podset into its own method.
This improves readability.
Fixes #

Refactor flavorassigner for readability

---

apis/kueue/v1alpha2/workload_types.go
apis/kueue/webhooks/workload_webhook.go
apis/kueue/webhooks/workload_webhook_test.go
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml

Before we will have a default name  for unset podSet name, it's auto generated via kubebuilder. But when we have two name unset podSets, they will both have the  name, it violates the API validation of non-repeated names. So remove the annotation in the API but add the default name via webhook muatation only when we have one podSet and its name is empty
/kind bug
Fixes #

Add default podSet name via webhook mutation

---

apis/kueue/webhooks/clusterqueue_webhook.go
apis/kueue/webhooks/clusterqueue_webhook_test.go

Signed-off-by:  cmssczy <smartczy@outlook.com>
/kind feature
Fixes # https://github.com/kubernetes-sigs/kueue/issues/434

Make ClusterQueue.spec.queuingStrategy immutable

---

test/integration/scheduler/scheduler_test.go

/kind cleanup
All CQs in the tests belong to the same cohort, so having it in the name just makes the tests harder to read/understand.
Fixes #

Shorten name of objects in cohort in integration tests

---

pkg/controller/core/workload_controller.go
pkg/controller/workload/job/job_controller.go
pkg/workload/workload.go
test/e2e/e2e_test.go
test/integration/controller/core/workload_controller_test.go

/kind cleanup
The function has an one-liner replacement in the core API.
Fixes #
Follow up to review: https://github.com/kubernetes-sigs/kueue/pull/460#discussion_r1047410714

Remove unnecessary function in kueue

---

apis/kueue/v1alpha2/clusterqueue_types.go
apis/kueue/v1alpha2/resourceflavor_types.go
apis/kueue/v1alpha2/workload_types.go
apis/kueue/webhooks/clusterqueue_webhook.go
apis/kueue/webhooks/clusterqueue_webhook_test.go
apis/kueue/webhooks/resourceflavor_webhook.go
apis/kueue/webhooks/resourceflavor_webhook_test.go
apis/kueue/webhooks/workload_webhook.go
apis/kueue/webhooks/workload_webhook_test.go
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
test/integration/webhook/v1alpha2/clusterqueue_test.go
test/integration/webhook/v1alpha2/resourceflavor_test.go
test/integration/webhook/v1alpha2/workload_test.go

/kind cleanup
Validate using open API where possible
Fixes # https://github.com/kubernetes-sigs/kueue/issues/465

Validate using open API where possible

---

main.go
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/scheduler/scheduler.go
pkg/util/testing/wrappers.go
test/integration/framework/framework.go
test/integration/scheduler/podsready/scheduler_test.go
test/integration/scheduler/podsready/suite_test.go

/kind feature
Introduces sequencing of job startups to prevent deadlocks in case of resource provisioning issues.
Part of: https://github.com/kubernetes-sigs/kueue/issues/349
- built on top of the current version of https://github.com/kubernetes-sigs/kueue/pull/460, will rebase once the first PR is merged

Block admission until PodsReady for all admitted workloads if WaitForPodsReady is enabled

---

docs/tasks/administer_cluster_quotas.md

Within line 203, I noticed a missing period during a user study on Dec 20th. Thought it was worth fixing.
Fixes #

Fix missing period in documentation

---

test/integration/scheduler/podsready/scheduler_test.go

/kind flake
/kind bug
There are two newly added tests in scheduler_test.go which are failing occasionally due to different reasons: 
- fails due to a conflict when adding `PodsReady` condition to a newly admitted workload when another `WorkloadAdmitted` condition is added later by workload_reconclier.  Fixed by retrying of adding the condition.
- fails due to a random order at which workloads are admitted in the same scheduling cycle. Solved by adding a second before creating the second workload to ensure the order of admission.
Fixes #488 
The proposed solutions are quick to do, but it seems both issues could be solved better.
First if we used SSA there should be no conflict between PodsReady and WorkloadAdmitted if used different field managers. 
Second we could …

Fix flaky integration tests for scheduling when WaitForPodsReady is enabled

---

test/e2e/suite_test.go

/kind bug
/kind flake
Increase timeout to create the first ResourceFlavor
If there are too many contentions in the test job, it could take some time for Kueue to start up.
Fixes #495

Increase timeout for Kueue to be ready

---

pkg/util/testing/not_found_error_cmp.go
test/integration/webhook/v1alpha2/clusterqueue_test.go
test/integration/webhook/v1alpha2/suite_test.go
test/integration/webhook/v1alpha2/workload_test.go

/kind cleanup
Enable `core.SetupControllers` to replace deleting finalizers manually.
Fixes # https://github.com/kubernetes-sigs/kueue/pull/466#discussion_r1049860993

Clean up webhook integration test

---

Makefile
config/dev/kustomization.yaml
config/dev/manager_config_patch.yaml

/kind cleanup
The current json-like logging format is nice for machines but hard for humans to read and use for debugging/troubleshooting. As Kueue with its current maturity is often used for trying out/experiments
the default config should favour smooth human experience. 
Before: 
```
{"level":"Level(-2)","ts":"2023-01-04T13:29:43.188609043Z","caller":"job/job_controller.go:140","msg":"Reconciling Job","controller":"job","controllerGroup":"batch","controllerKind":"Job","job":{"name":"sample-job-rb572","namespace":"default"},"namespace":"default","name":"sample-job-rb572","reconcileID":"d6f549db-9778-4353-98d8-de29f209806a","job":{"name":"sample-job-rb572","namespace":"default"}}
{"level":"Level(-2)","ts":"2023-01-04T13:29:43.18878194Z","caller":"job/job_controller.go:362","msg":"job with …
```

Use human-readable logging format in manifest.yaml.

---

docs/setup/install.md

fix broken link

---

apis/kueue/webhooks/workload_webhook_test.go
pkg/util/priority/priority_test.go
pkg/util/testing/wrappers.go
test/integration/scheduler/scheduler_test.go

/kind cleanup
This reduces bloat when writing tests.
Fixes #

Define priority by value in testing wrappers

---

pkg/controller/core/workload_controller.go
pkg/queue/manager.go
test/integration/scheduler/scheduler_test.go

/kind bug
Ensures atomicity when releasing quota and requeuing inadmissible workloads. If not, it's possible that a workload being requeued slips in between the time a workload is deleted from the cache and we requeue inadmissible workloads, violating priority.
Fixes #
This is adding a dependency from the queue manager lock into the cache lock. We already had an instance like this via the StatusChecker interface in the manager.
In the future, we need to be careful not to add a lock dependency the other way around.
Based on top of #506

Atomically release quota and queue inadmissible workloads

---

docs/setup/install.md
docs/tasks/README.md
docs/tasks/setup_sequential_admission.md

/kind feature
The new docs describe how to update Kueue configuration to use waitForPodsReady configuration which provides a simple implementation of the all-or-nothing scheduling in Kueue.
Part of: https://github.com/kubernetes-sigs/kueue/issues/349

Docs on enabling simple all-or-nothing scheduling in Kueue

---

pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/util/testing/core.go

/kind cleanup
Add a test case for preemption in combination with node affinity and taints, to make sure that both things are respected together.
One test case has two pod sets, each assigned to a different flavor.
Fixes #

Test cases for preemption mode with affinity and taints

---

OWNERS

Add @tenzen-y to reviewers, given his history of contributions and active involvement in issues.
- [18 merged PRs](https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+author%3Atenzen-y+is%3Aclosed+merged%3A%3C%3D2023-01-30)
Fixes #

Add tenzen-y to reviewers

---

pkg/controller/core/workload_controller.go
test/integration/controller/core/workload_controller_test.go

/kind cleanup
Clarify the queue type that the Workload is Inadmissible to (LocalQueue)
Fixes #

Updated workload Inadmissible message when LocalQueue does not exist

---

pkg/queue/manager_test.go
pkg/util/routine/error_channel_test.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
/kind cleanup
comparing with != will fail on wrapped errors. Use errors.Is to check for a specific error
Fixes #

Use errors.Is to check for a specific error

---

apis/kueue/webhooks/workload_webhook.go
pkg/cache/cache.go
pkg/controller/core/workload_controller.go
pkg/controller/workload/job/job_controller.go
pkg/queue/cluster_queue_best_effort_fifo_test.go
pkg/queue/cluster_queue_strict_fifo_test.go
pkg/queue/manager.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
/kind cleanup
Clean up unnecessary whitespace and convert
Fixes #

Clean up unnecessary whitespace and convert

---

Makefile

Set go.mod go version as single source of truth for golang version.
/kind cleanup

Makefile: set GO-VERSION as image version tag

---

netlify.toml

Fixes the publish directory in netlify.toml. Currently set manually in netlify.

update netlify publish directory

---

test/integration/controller/job/job_controller_test.go

Signed-off-by: Kante Yin <kerthcet@gmail.com>
/kind cleanup
~The e2e test flow:~
~1. Create a job with no matched localQueue, job is suspend.~
~2. Create a localQueue but located in another namespace with job, job is suspend.~
~3. Unsuspend the job manually, back to suspend status.~
~4. Create a localQueue located in the same namespace. job is unsuspend.~
~5. Delete the job, workload is also deleted.~
Fixes https://github.com/kubernetes-sigs/kueue/issues/546

Add integration tests for job controller

---

config/samples/sample-job.yaml
config/samples/single-clusterqueue-setup.yaml
docs/concepts/README.md
docs/concepts/cluster_queue.md
docs/concepts/local_queue.md
docs/concepts/resource_flavor.md
docs/concepts/workload.md
docs/tasks/README.md
docs/tasks/administer_cluster_quotas.md
docs/tasks/run_jobs.md
docs/tasks/setup_rbac.md
docs/tasks/setup_sequential_admission.md

Documentation changes to address the insights from UX study sessions: 
https://docs.google.com/document/d/1xbN46OLuhsXXHeqZrKrl9I57kpFQ2yqiYdOx0sHZC4Q/edit
- Changed order in 'Concepts' main page: ResourceFlavor first, to follow logical order of creation
- Separated ResourceFlavor section into it's own page, so it's more clean
- Added yaml example to LocalQueue page
- Used more descriptive names for Kueue objects in yaml and made them uniform between examples / pages

First pass - Documentation improvement

---

config/components/manager/manager.yaml

Increasing the requests and limits for controller-manager to 500m CPU and 512Mi memory respectively, matching to provide a Guaranteed QOS.
/bug
This PR aims to provide a Guaranteed QOS for Kueue Controller Manager by matching the requests and limits specified in the Deployment; setting the CPU to 500m and the memory to 512m.
With this memory footprint the manager can support around 7000 Jobs.
Fixes #

Increase and match requests and limits for manager

---

site/assets/scss/_styles_project.scss

/kind bug
the previous pr of doc landing site added a change that restricted max width for the entire landing page rows. Which does not look right for the social links section.

fix max width for only text content

---

pkg/controller/workload/job/job_webhook.go
pkg/controller/workload/job/job_webhook_test.go

Validate queue-name annotation is a valid crd name

---

site/config.toml
site/content/en/docs/_index.md
site/content/en/docs/concepts/_index.md
site/content/en/docs/tasks/_index.md

link to run a job from tasks/
update doc title to kueue
update root page title to Documentation

remove list from concepts and tasks root page

---

keps/369-job-interface/README.md
keps/369-job-interface/kep.yaml

Signed-off-by: Kante Yin <kerthcet@gmail.com>
/kind feature
Part of https://github.com/kubernetes-sigs/kueue/issues/369

[KEP]Add job interface for integration

---

CHANGELOG/CHANGELOG-0.2.md
README.md

I updated the documentation links with `https://kueue.sigs.k8s.io`.
Fixes #

Update documentation links

---

site/content/en/docs/installation/_index.md

I fixed a typo on the website. Our project name is `Kueue`, not `Queue` :)
Fixes #

Fix a typo on the website

---

pkg/controller/core/workload_controller.go
pkg/controller/workload/job/job_controller.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/scheduler.go
pkg/workload/workload.go
pkg/workload/workload_test.go

/kind feature
Make use of SSA while updating a workload status condition.
Each condition is changed with it's own manager name allowing concurrent changes to different conditions.
Fixes #493
cc: @mwielgus @alculquicondor

[pkg/workload] Use SSA patch to update status conditions.

---

pkg/controller/workload/job/job_controller.go
pkg/controller/workload/jobframework/helpers.go
pkg/controller/workload/jobframework/interface.go
pkg/controller/workload/mpijob/mpijob_controller.go
pkg/controller/workload/mpijob/mpijob_controller_test.go
pkg/controller/workload/mpijob/mpijob_webhook.go
test/integration/controller/mpijob/mpijob_controller_test.go

/kind feature
This aligns the implementation of the MPIJob controller with Job controller. It also already drops some code that was duplicated.
Part of #369
There will be follow ups:
- commonize the `Reconcile` functions
- commonize indexing
- commonize webhooks

Use the GenericJob interface by MPIJob

---

pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_test.go

/kind bug
/kind feature
Allows borrowing when preempting workloads from the same queue, but prefers no borrowing and preempting workloads that have already borrowed from the queue. Preemption of borrowers will not happen if borrowing would be needed anyway. 
Fixes #533

Allow borrowing while preemption is applied to assigned cluster queue

---

Makefile

/kind cleanup
I upgrade the K8s versions for tests in Makefile.
Fixes #

Upgrade the default K8s versions for local tests

---

config/samples/sample-job.yaml
config/samples/single-clusterqueue-setup.yaml
site/content/en/docs/concepts/cluster_queue.md
site/content/en/docs/concepts/local_queue.md
site/content/en/docs/concepts/resource_flavor.md
site/content/en/docs/tasks/administer_cluster_quotas.md
site/content/en/docs/tasks/setup_sequential_admission.md

Documentation update necessary for v1beta1 api graduation.

Documentation update for v1beta1 api

---

README.md
site/content/en/docs/concepts/resource_flavor.md
site/content/en/docs/concepts/workload.md
site/content/en/docs/installation/_index.md
site/content/en/docs/tasks/run_jobs.md

I updated documentation for `config.kueue.x-k8s.io` and `kueue.x-k8s.io` v1beta1.
Fixes #

Update documentation for config.kueue.x-k8s.io v1beta1 

---

test/integration/webhook/localqueue_test.go

/kind cleanup
I removed an unneeded integration test case.
Fixes #511

Fix flaky integration test

---

CHANGELOG/CHANGELOG-0.3.md
site/content/en/docs/tasks/run_jobs.md
site/content/en/docs/tasks/setup_sequential_admission.md

Updates release notes from the PRs tagged as `kind/feature` or `kind/bug` that are user-facing.
Fixes #
Let me know if I missed a PR.
In the future we should be more diligent adding release notes (I'm guilty too). And we should probably add milestones too.

Update release notes for 0.3

---

site/content/en/docs/installation/_index.md

Add quotes on the docs so it does not fail installation for zsh terminals.
Fixes #671

add quotes for zsh terminal

---

test/integration/scheduler/scheduler_test.go

/kind bug
Flaky test: Scheduler when Handling clusterQueue events Should re-enqueue by the update event of ClusterQueue 
Fixes #674

fixed flaky test

---

README.md
test/performance/README.md

Signed-off-by: Kante Yin <kerthcet@gmail.com>
/kind cleanup
The first step of scalability tests is added in https://github.com/kubernetes-sigs/kueue/pull/462
Fixes #

Update production readiness items

---

pkg/controller/jobs/mpijob/mpijob_controller.go

/kind cleanup
I fixed typos for the MPIJob.
Fixes #

Fix typos for the MPIJob

---

README.md
site/content/en/docs/installation/_index.md

Update docs to v0.3.0 in main branch

---

pkg/workload/workload.go

/kind cleanup
I removed an unused function, `UpdateStatusIfChanged`, in the workload package.
Fixes #

Remove an unused function

---

pkg/workload/workload.go
test/integration/scheduler/scheduler_test.go
test/util/util.go

/kind cleanup
I replaced our `workload.FindConditionIndex` with the `apimeta.FindStatusCondition` to avoid reinventing the wheel.
Fixes #

Use FindStatusCondition in apimeta instead of workload.FindConditionIndex

---

CHANGELOG/CHANGELOG-0.4.md

/kind flake
Adds a changelog entry for #612 / #613

[CHANGELOG] Add LimitRange based validation before admission

---

apis/kueue/webhooks/workload_webhook.go
pkg/cache/cache.go
pkg/cache/snapshot_test.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/workload_controller.go
pkg/controller/core/workload_controller_test.go
pkg/controller/jobframework/reconciler.go
pkg/queue/manager.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/wrappers.go
pkg/workload/workload.go
test/e2e/e2e_test.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/localqueue_controller_test.go
test/integration/controller/job/job_controller_test.go
test/integration/controller/mpijob/mpijob_controller_test.go
test/integration/scheduler/podsready/scheduler_test.go
test/integration/scheduler/scheduler_test.go
test/integration/scheduler/workload_controller_test.go
test/integration/webhook/workload_test.go
test/util/util.go

/kind cleanup
Now are used 2 different ways to check if workload is admitted:
wl.Status.Admission == nil
and
apimeta.IsStatusConditionTrue(wl.Status.Conditions, kueue.WorkloadAdmitted)
Fixes #694

Admission checking refactorization

---

CHANGELOG/CHANGELOG-0.3.md

I updated the CHANGELOG for #711.
Follow up on https://github.com/kubernetes-sigs/kueue/pull/726#issuecomment-1523917870.
Fixes #

Update the changelog for #711

---

main.go
main_test.go
pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/integrationmanager_test.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/jobs.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/mpijob/mpijob_webhook.go

/kind feature
Change the way job's frameworks are integrated into the controller manager.
Fixes #691

[jobframework] Integration Manager

---

.github/PULL_REQUEST_TEMPLATE.md

Pull-Request-Template: Add release-note block

---

test/integration/controller/core/localqueue_controller_test.go

/kind cleanup
In the real world, we can assign only resourceFlavors that clusterQueue has to workloads. 
However, in `Should update status when workloads are created` case, we assign a resourceFlavor, `onDemand`, that clusterQueue doesn't have to workloads.
https://github.com/kubernetes-sigs/kueue/blob/726b1d59c19bcfb7081816ec72eee6e97523986e/test/integration/controller/core/localqueue_controller_test.go#L58-L62
https://github.com/kubernetes-sigs/kueue/blob/726b1d59c19bcfb7081816ec72eee6e97523986e/test/integration/controller/core/localqueue_controller_test.go#L190-L198
Fixes #

Fix an integration test for the local-queue-controller

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #
```release-note
NONE
```
Edit GitHub PR template to be in line with k/k template

Edit github PR template

---

test/integration/controller/core/resourceflavor_controller_test.go

/kind bug
/kind flake
Flaky test
Fixes #704

fixed resource flavor flaky test

---

site/content/en/docs/tasks/run_flux_minicluster.md

Documents flux MiniCluster usage with Kueue. 
Fixes #716

[doc] Run A Flux Minicluster

---

site/content/en/docs/tasks/_index.md

/kind flake
Mention Flux in the Tasks index.
Related to  #716
```release-note
NONE
```

[site] Mention Flux in the Tasks index.

---

pkg/controller/jobs/job/job_webhook_test.go
pkg/controller/jobs/mpijob/mpijob_webhook_test.go
pkg/util/testingjobs/job/wrappers.go

/kind cleanup
I added the unit tests for the jobframework Defaulter.
Ref #758
```release-note
None
```

Add the unit test for the jobframework Defaulter

---

CHANGELOG/CHANGELOG-0.3.md
README.md
site/content/en/docs/installation/_index.md

Fixes #766 
```release-note
NONE
```

Update documentation to v0.3.1

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

- Clarify which steps can be skipped in patch releases.
- Add note on how to use the release-note script.
Fixes #
```release-note
NONE
```

Update steps of release process

---

README.md

Fixes #
It will look like:
```release-note
NONE
```

Add logo & badges to README.md

---

pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go

/kind cleanup
I added interface compliance checks to framework jobs.
Fixes #
```release-note
None
```

Add interface compliance checks to framework jobs

---

Makefile

/kind cleanup
We currently use different versions between the ginkgo binary and the ginkgo library.
So, I modified Makefile to use the same version for the ginkgo across the whole of this repo.
Fixes #
```release-note
None
```

Use go.mod go version as a single source of truth of Ginkgo version

---

keps/420-partial-admission/README.md
keps/420-partial-admission/kep.yaml

KEP-420 Allow partial admission 
Fixes #420
```release-note
NONE
```

KEP-420 Allow partial admission

---

config/samples/sample-mpijob.yaml
site/content/en/docs/tasks/run_mpi_jobs.md

Add MPI Task to Documentation
Fixes #764 
```release-note
Add a task for running MPIJobs with Kueue
```

add MPI example

---

charts/kueue/README.md

Update helm-chart's README.md
Because we don't use helm-chart-releaser, README.md is not correct.
I've updated README.md.
Fixes #753 
Thanks for reviewing this PR.
```release-note
NONE
```

update how to install helm-chart

---

OWNERS

@trasc has made multiple meaningful contributions to Kueue for the v0.3 release and even more during the ongoing v0.4 release.
He has quickly accumulated deep knowledge of the codebase and is applying our best practices. I'm confident he'll be a valuable member of our reviewers team.
Fixes #
```release-note
NONE
```

Add trasc as reviewer

---

examples/ray-job-sample.yaml
site/content/en/docs/tasks/run_rayjobs.md

- Add the required ConfigMap to the tutorial
- Use more specific links to tutorial
- Add example file
Fixes #
```release-note
NONE
```

Add ConfigMap to RayJob tutorial

---

pkg/cache/cache.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
test/integration/scheduler/preemption_test.go

/kind bug
Backport of #805 to v0.3.x
Backport of #804 
```release-note
Fix: Potential over-admission within cohort when borrowing.
```

Fix concurrent admission in cohort when borrowing (#805)

---

test/integration/controller/job/job_controller_test.go
test/integration/controller/job/job_webhook_test.go
test/integration/controller/mpijob/mpijob_controller_test.go
test/integration/controller/rayjob/rayjob_controller_test.go

/kind cleanup
Reuse envtest in the integration tests for batch,mpi, and ray jobs.
Doing so we speed up the overall integration tests with @35%.
Fixes #767
```release-note
NONE
```

[test/integration] Reuse envtest

---

Makefile

/kind cleanup
In the bots, linter runs with 2 cores, which can go over the timelimit
Fixes #
```release-note
NONE
```

Increase timeout for lint

---

config/components/rbac/rayjob_editor_role.yaml
config/components/rbac/rayjob_viewer_role.yaml

/kind bug
[config/rbac] Add RayJob roles.
Fixes #825 
```release-note
NONE
```

[config/rbac] Add RayJob roles.

---

pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go
pkg/util/maps/maps.go

/kind cleanup
Add a common way to merge and clone node selectors
Relates to #782
```release-note
NONE
```

[jobs] Add a common way to merge and clone node selectors

---

pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_test.go

/kind bug
Fixes #840
```release-note
Fixed preemption to prefer preempting workloads that were more recently admitted.
```

Resolve conflicts after merging order of preempting workloads

---

Makefile

/kind cleanup
I modified Makefile to use 'GO_CMD' instead of 'go'.
Fixes #
```release-note
NONE
```

Makefile: Use 'GO_CMD' instead of 'go'

---

pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobs/job/job_webhook.go

/kind cleanup
`Manageble` is a typo and `IsOwnerManagebleByKueue` isn't appropriate function name.
So I replaced `IsOwnerManagebleByKueue` with `IsOwnerManagedByKueue`.
Fixes #
```release-note
NONE
```

Replace 'IsOwnerManagebleByKueue' with 'IsOwnerManagedByKueue'

---

site/content/en/docs/tasks/_index.md

I added a link related to MPIJob to the tasks page, similar to other frameworks.
Fixes #
```release-note
NONE
```

Add a link related to MPIJob to the tasks page

---

site/content/en/docs/concepts/workload.md

Fix typo in workload.md
Thank you so much for your review.
```release-note
NONE
```

fix typo in workload.md

---

test/integration/controller/job/job_controller_test.go

/kind cleanup
I added a test case to ensure that startTime is reset when jobs are stopped, as discussed in https://github.com/kubernetes-sigs/kueue/pull/797#issuecomment-1560048273 with @alculquicondor.
Fixes #
```release-note
NONE
```

[Integration Test] Ensure that startTime is reset when jobs are stopped

---

site/OWNERS

Add @moficodes as approver for the site folder, as original author and main maintainer.
Fixes #
```release-note
NONE
```

Add moficodes as approver for site

---

test/integration/controller/job/job_controller_test.go

/kind cleanup
Add an "almost-e2e" integration test for job preemption with fungibility.
Fixes #
I plan to add a similar test for E2E, as there is no k8s job controller running in integration tests.
```release-note
NONE
```

Add integration test for job preemption and fungibility

---

Makefile
go.mod
go.sum
hack/internal/tools/pinversion.go
hack/update-codegen.sh

/kind cleanup
Make client-go generate work from outside GOPATH and a reference to k8s.io/code-generator in go.mod
Fixes #
```release-note
NONE
```

[client-go] Generate from outside GOPATH

---

Makefile
hack/e2e-test.sh
hack/kind-cluster.yaml

/kind cleanup
Gather logs from scheduler, kcm and kueue controllers for debugging.
Fixes #
```release-note
NONE
```

Store logs from controllers in E2E tests

---

config/components/rbac/role.yaml
main.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/job/job_controller.go

/kind bug
This fix ignores jobs if the integration of these jobs is disabled, but there is ```kueue.x-k8s.io/queue-name``` label in the metadata of jobs
Fixes #877
```release-note
Ignoring integrations if crd wasn't installed otherwise all integrations are enabled by default
```

Ignore jobs if integration is disabled

---

hack/kind-cluster.yaml
pkg/scheduler/scheduler.go
pkg/util/testingjobs/job/wrappers.go
test/e2e/e2e_test.go

/kind cleanup
Ensure basic fungibility works E2E
Fixes #
Builds on top of #894 (first commit)
```release-note
NONE
```

Add E2E test for nodeSelector based on ResourceFlavor

---

test/integration/controller/job/job_controller_test.go

/kind cleanup
Fixes #
```release-note
NONE
```

Cleanup created priority classes

---

test/integration/controller/job/job_controller_test.go
test/integration/scheduler/scheduler_test.go

/kind cleanup
Adds integration tests to check the node selector management for admission based on pods count only.
Fixes #891
```release-note
NONE
```

[tests] NodeSelector assignment when using quota only for pod count

---

Makefile
hack/e2e-test.sh
hack/kind-cluster.yaml
test/e2e/suite_test.go

/kind cleanup
Cherry-pick e2e run changers on release 0.3. 
#894
#879
Fixes #
```release-note
NONE
```

Cherry-pick e2e run changers on release 0.3

---

hack/e2e-test.sh

/kind cleanup
/kind flake
I improved logging for E2E and added a flag `--wait 1m` to `kind create cluster`.
https://github.com/kubernetes-sigs/kueue/pull/908
Fixes #
```release-note
NONE
```

[E2E] Improve logging 

---

pkg/controller/jobframework/reconciler.go
test/integration/controller/job/job_controller_test.go

/kind cleanup
Limit the involvement of the jobframework in non-standalone job reconciliation.
Relates to  #762 
```release-note
NONE
```

[jobframework] Limit the involvement in non-standalone job reconciliation

---

hack/e2e-test.sh

/kind cleanup
[hack/e2e] Restore the image tag to `release-0.3`
Fixes #
```release-note
NONE
```

[hack/e2e] Restore the image tag to `release-0.3`

---

test/e2e/e2e_test.go
test/util/util.go

/kind cleanup
E2E version of #885
This tests that a job can run in a different flavor after being preempted.
Fixes #
```release-note
NONE
```

E2E test for preemption and fungibility

---

Makefile

/kind cleanup
Use $(PROJECT_DIR) instead of $(shell pwd) in the Makefile where ever it's possible.
Fixes #920
```release-note
NONE
```

[Makefile] Use $(PROJECT_DIR) instead of $(shell pwd) 

---

hack/e2e-test.sh

/kind cleanup
[e2e] Make kind verbose
Fixes #
```release-note
NONE
```

[e2e] Make kind verbose

---

site/content/en/docs/concepts/workload.md

Fixes #929
```release-note
NONE
```

Update workload manifest in doc

---

charts/kueue/templates/manager/manager.yaml

/kind cleanup
Kueue does not use environment variables for controller configuration, instead it has its own [configuration type](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/manager/controller_manager_config.yaml), so we delete them
Fixes #892
```release-note
NONE
```

Deleted env field in the helm chart as unused

---

pkg/controller/jobframework/reconciler.go

/kind bug
Don't set podSet's  minCount in job controller when the PartialAdmission feature gate is disabled.
Fixes #917
```release-note
NONE
```

[controlles/job] Don't set minCount when PartialAdmission is disabled

---

charts/kueue/templates/manager/manager.yaml
charts/kueue/values.yaml

/kind feature
Allows the kueue manager to run in more restriced namespaces.
Fixes #874
```release-note
Allow specifying the manager pod and container security context instead of hardcoded values
```

Allow specifiying pod and container security context

---

go.mod
go.sum

/kind cleanup
[dep] Use kuberay v0.5.2
Fixes #781
Because `github.com/ray-project/kuberay` is not providing sub-module tags `ray-operator/v0.5.2` the go.mod reference is `v0.0.0-20230613204710-aeed3cdcbdcc`.
```release-note
NONE
```

[dep] Use kuberay v0.5.2

---

test/integration/framework/framework.go

/kind cleanup
I replaced deprecated manager Options with new ones in integrations test.
Fixes #
```release-note
NONE
```

[Integration test] Replace deprecated manager Options with new ones

---

site/content/en/docs/adopters/index.md

I added the adopters page to the doc site. Also, I added my company as a first adopter.
Fixes #
```release-note
NONE
```

Add adopters to the site

---

Makefile

/kind cleanup
> KIND v0.18.0 Comes with a big shoutout to [Docker, Inc.](https://www.docker.com/company/) for accepting us into the updated [Docker Sponsored OSS Program](https://www.docker.com/community/open-source/application/). Thanks Docker! 🎉
Images should no longer have pull rate limits as a result.
The project will still consider mirroring on or switching primarily to [registry.k8s.io](https://registry.k8s.io/) in the future, after determining an updated immutable tagging scheme to comply with requirements there.
Fixes #933 
```release-note
NONE
```

[e2e] Use kind 0.18

---

main.go
pkg/controller/core/clusterqueue_controller_test.go
pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/integrationmanager_test.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobframework/reconciler_test.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/context.go
pkg/util/testingjobs/job/wrappers.go
test/e2e/e2e_test.go
test/integration/controller/job/suite_test.go
test/integration/controller/jobset/suite_test.go
test/integration/controller/mpijob/suite_test.go
test/integration/controller/rayjob/suite_test.go

/kind cleanup
- Only set image name in job wrapper
- Obtain scheme from client when building a reconciler
- Testing util to build a context with verbose logging
Fixes #
```release-note
NONE
```

Simplify tests setup

---

examples/sample-job-partial-admission.yaml
site/content/en/docs/installation/_index.md
site/content/en/docs/tasks/run_jobs.md

Document partial admission and feature gate usage.
Fixes #935
```release-note
NONE
```

[site] Document partial admission and feature gate usage.

---

Makefile
charts/kueue/values.yaml
config/components/manager/kustomization.yaml

/kind feature
Generate the helm package along with the manifests.
Fixes #745 
```release-note
NONE
```

[artifacts] Add helm package

---

Makefile
README.md
config/components/manager/kustomization.yaml
hack/e2e-test.sh

/kind cleanup
Change `main` references to `release-0.4`
Relates to #955
```release-note
NONE
```

Change `main` references to `release-0.4`

---

README.md
site/config.toml
site/content/en/docs/installation/_index.md

Update docs to v0.4.0 in main branch
Relates to #955 
```release-note
NONE
```

Update docs to v0.4.0 in main branch

---

Makefile
hack/update-helm.sh

/kind cleanup
Use a locally installed `yq` and `helm` while building the artifacts.
Fixes #
```release-note
NONE
```

[makefile] Use local yq and helm

---

charts/kueue/README.md
charts/kueue/templates/manager/manager.yaml
charts/kueue/values.yaml

Fixes #
```release-note
Expose probe configurations to helm chart
```

feat: expose probe

---

charts/kueue/templates/rbac/jobset_editor_role.yaml
charts/kueue/templates/rbac/jobset_viewer_role.yaml
config/components/rbac/jobset_editor_role.yaml
config/components/rbac/jobset_viewer_role.yaml
config/components/rbac/kustomization.yaml

/kind cleanup
Add jobset RBAC roles
Fixes #
```release-note
NONE
```

[rbac] Add jobset roles

---

site/content/en/docs/adopters/index.md

added WattIQ to adopters list

---

site/content/en/docs/installation/_index.md
site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/enabling_pprof_endpoints.md

[site] Added pprof doc
Fixes #983
```release-note
NONE
```

[site] Added pprof doc

---

site/content/en/docs/installation/_index.md

Added kueue installation guide using helm in website. 
Fixes #753
```release-note
None
```

Add helm installation instructions to website

---

site/content/en/docs/installation/_index.md

The index `Install via Helm` is not working in Installation page of website. This is because the title contains the link. So, I put the link into the text "Helm" below the title.
Fixes #
```release-note
NONE
```

Changed helm installation link

---

.gitignore

/kind cleanup
Ignore [nix](https://nixos.org/) files that contain development environments.
Fixes #
```release-note
NONE
```

Ignore .nix files from git

---

config/components/webhook/manifests.yaml
main.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/job/job_webhook_test.go
pkg/util/kubeversion/kubeversion.go
pkg/util/kubeversion/kubeversion_test.go

/kind feature
Check k8s version and change condition for batch/job.completions with parallelism in case of partial admission
Fixes #970
This is the second step fixing #970.
```release-note
NONE
```

check k8s version for synchronization of completions and parallelism

---

test/integration/controller/core/suite_test.go
test/integration/controller/job/job_controller_test.go
test/integration/controller/job/job_webhook_test.go
test/integration/controller/job/suite_test.go
test/integration/controller/jobset/jobset_controller_test.go
test/integration/controller/jobset/jobset_webhook_test.go
test/integration/controller/mpijob/mpijob_controller_test.go
test/integration/controller/mpijob/mpijob_webhook_test.go
test/integration/controller/rayjob/rayjob_controller_test.go
test/integration/controller/rayjob/rayjob_webhook_test.go
test/integration/framework/framework.go
test/integration/scheduler/podsready/scheduler_test.go
test/integration/scheduler/suite_test.go
test/integration/webhook/suite_test.go

/kind cleanup
Ref: https://github.com/kubernetes-sigs/kueue/pull/1014#discussion_r1282046680
Fixes #
```release-note
NONE
```

Checking server version in integration tests

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

Update people to notify.
Update instructions for website and milestone.
Fixes #
```release-note
NONE
```

Update approvers and instructions in NEW_RELEASE template

---

pkg/controller/jobframework/interface.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go

/kind cleanup
https://go.dev/doc/effective_go#Getters
Fixes #
```release-note
NONE
```

Remove Get prefix from function name

---

site/layouts/shortcodes/include.html

/kind cleanup
Allows to include examples from anywhere in the hierarchy of docs.
Also adds an icon next to the filename to indicate it's a link to a file.
Fixes #
```release-note
NONE
```

Use absolute paths for include

---

pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go

/kind cleanup
In the `KubeflowJob`, I commonized the `OrderedReplicaTypes()` and the `PriorityClass()` functions as discussed in https://github.com/kubernetes-sigs/kueue/pull/1068#discussion_r1298664579.
Fixes #
```release-note
NONE
```

KubeflowJob: Commonize OrderedReplicaTypes and PriorityClass

---

main.go

/kind bug
Setting up indexes can fail if apiserver is temporarily unavailable. If we proceed, reconcilers could fail.
Exiting will cause kubelet to retry later.
Inspired by https://github.com/kubernetes-sigs/jobset/issues/263
```release-note
Terminate when internal setup fails, so setup can be retried.
```

Exit if fail to setup indexes

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
site/static/examples/sample-tfjob.yaml

I added the documentation for the TFJob intagration.
Fixes #
```release-note
Add a task to use the TFJob integration
```

Add docs for the TFJob integration

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/integrate_a_custom_job.md

Add Platform Developer section in `docs/tasks`.
Fixes #1007
```release-note
NONE
```

Add platform developer section to tasks index

---

site/content/en/docs/adopters/index.md

/kind document
/assign @alculquicondor 
Fixes #
```release-note
None
```

Add to adopter

---

keps/976-plain-pods/README.md
keps/976-plain-pods/kep.yaml

/kind feature
Design for support for plain Pods. 
Part of #976 
I listed all the stories that we can potentially support, but we might prioritize only 1 and 4.
```release-note
NONE
```

Add KEP for Pod support

---

keps/993-two-phase-admission/README.md

/kind cleanup
Renames QuotaBookingMode to PreemptionPolicy, as the previous name was conflicting with the condition `QuotaReserved`.
The new API is focused on the user visible effect: preemption. It also gives more clarity about how to interpret QuotaReserved and what to do when multiple AdmissionChecks have different PreemptionPolicies.
Fixes #
```release-note
NONE
```

Two-Stage Admission KEP: Rename QuotaBookingMode to PreemptionPolicy

---

config/components/rbac/kustomization.yaml

/kind bug
I forgot to add those roles to rbac in https://github.com/kubernetes-sigs/kueue/pull/1068.
Fixes #
```release-note
Add viewer and editor roles for TFJob to rbac
```

Add viewer and editor roles for TFJob to rbac

---

pkg/controller/core/clusterqueue_controller.go
pkg/util/kubeversion/kubeversion.go

/kind cleanup
Fixes #1100
```release-note
NONE
```

Do not export variables that are not externally used

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
site/static/examples/sample-xgboostjob.yaml

I added tasks for XGBoostJob integration to site.
Fixes #
```release-note
Add a task to use the XGBoostJob integration
```

[DOC] Add tasks for XGBoostJob integration to site

---

hack/update-codegen.sh

/kind bug
Fix out of GOPATH client-go generation after
`Bump K8s dependencies to v1.28 #1133`
Fixes #
```release-note
NONE
```

[hack] Fix out of GOPATH client-go generation.

---

CHANGELOG/CHANGELOG-0.4.md
README.md
charts/kueue/Chart.yaml
site/config.toml

Fixes #1200
```release-note
NONE
```

Update latest version to v0.4.2

---

site/content/en/docs/adopters/index.md

Add adopter for kueue

---

pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go

/kind cleanup
Using upstream (kubeflow) constants would be better.
Fixes #
```release-note
NONE
```

[KubeflowJobs] Use constants instead of raw strings

---

pkg/controller/jobframework/reconciler.go
pkg/webhooks/workload_webhook.go

/kind cleanup
We should use generic sets instead of deprecated sets.
Fixes #
```release-note
NONE
```

Use generic sets instead of deprecated sets

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/_index.md
site/content/en/docs/tasks/run_kubeflow_jobs/run_mxjobs.md
site/static/examples/jobs/sample-mxjob.yaml

I added the document for the `kubeflow.org.mxjob`.
Fixes #
```release-note
Add documentation for kubeflow.org/mxjob
```

Add document for the kubeflow.org/mxjob

---

pkg/controller/jobs/job/job_controller_test.go
pkg/features/kube_features.go
pkg/features/kube_features_test.go
pkg/scheduler/scheduler_test.go
site/content/en/docs/installation/_index.md
test/e2e/e2e_test.go
test/integration/controller/jobs/job/job_controller_test.go

/kind feature
Graduate PartialAdmission to beta and enable by default
Fixes #1212 
```release-note
Graduate Partial admission to Beta.
```

Graduate Partial admission to Beta.

---

site/content/en/docs/adopters/index.md

Add FAR AI as an adopter. I was asked to do so by @kerthcet 
Question: what kind of contact should we have in the contact column? Must it be a GitHub username?

Add FAR AI as an adopter to kueue

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

We need to update the chart version for any release, not just minor/major
Fixes #1228
```release-note
NONE
```

Update the chart versions for any release

---

go.mod
go.sum

/kind feature
Fixes #1155
```release-note
update ray-operator to v0.6.0
```

feat: update ray-operator to v0.6.0

---

pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
test/integration/controller/jobs/kubeflow/kubeflowjob.go
test/integration/controller/jobs/mxjob/mxjob_controller_test.go
test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
test/integration/controller/jobs/tfjob/tfjob_controller_test.go
test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
test/util/util.go

Commonize KubeflowJob Tests

---

site/content/en/docs/concepts/workload.md

Document dynamic reclaim.
Fixes #1217
```release-note
NONE
```

[doc] Dynamic Reclaim

---

site/content/en/docs/admission-check-controllers/_index.md
site/content/en/docs/admission-check-controllers/provisioning.md
site/content/en/docs/installation/_index.md
site/static/examples/provisioning/provisioning-setup.yaml
site/static/examples/provisioning/sample-job.yaml

/kind cleanup
Provisioning Admission Check Controller documentation.
Relates to #1136 
```release-note
NONE
```

[doc] Provisioning Admission Check Controller

---

site/content/en/docs/tasks/run_plain_pods.md

* Add information on how to set namespace selector for the pod webhook.
```release-note
NONE
```

Add information on pod webhook namespace selector

---

Makefile

/kind cleanup
- Whoever is writing a change should generate files before running tests.
- `make verify` already checks that everything is up to date.
- There is a strange failure in the periodic e2e tests, where somehow the git tree gets corrupted https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-e2e-main-1-27/1717183886879887360
This doesn't happen on pull runs, but I'm hoping this PR will fix the problem.
Fixes #
```release-note
NONE
```

Do not generate files when running tests

---

README.md

Add links to adopters and testgrids, so that the content is always up to date.
Fixes #
```release-note
NONE
```

Update production readiness status: testgrids and adopters

---

CHANGELOG/CHANGELOG-0.5.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/values.yaml
config/components/manager/kustomization.yaml
hack/e2e-test.sh

Prepare branch for release.
Part of #1256
This was based out of #958
```release-note
NONE
```

Add release notes and references for release-0.5

---

CHANGELOG/CHANGELOG-0.5.md
README.md
charts/kueue/Chart.yaml
site/config.toml

Part of #1256
```release-note
NONE
```

Update version references to v0.5.0

---

site/content/en/docs/installation/_index.md

/kind bug
The Workload CRD is too big to fit in the annotation for client-side apply
Fixes #
```release-note
NONE
```

Install kueue with server-side apply

---

apis/kueue/v1beta1/workload_types.go
charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml

/kind cleanup
[api] Fix Admission check state enum documentation.
Fixes #
```release-note
NONE
```

[api] Fix Admission check state enum documentation.

---

site/content/en/docs/concepts/cluster_queue.md

Formatting fixed and missing parameter added
Fixes #
```release-note
NONE
```

[doc] Update preemption section

---

site/content/en/docs/adopters/index.md

Fixes #
add shopee in adopters
```release-note
none
```

add shopee in adopters

---

Makefile
site/content/en/docs/reference/kueue.v1beta1.md

/kind cleanup
Update `genref` version.
Fixes #
```release-note
NONE
```

Update `genref` version

---

site/content/en/docs/adopters/index.md

Replaces #1323, to bypass CLA requirement.
```release-note
NONE
```

Add Mondoo as adopter

---

site/content/en/docs/adopters/index.md

Fixes #
```release-note
NONE
```

Add Google Cloud as adopter

---

site/content/en/docs/adopters/index.md

To improve awareness of the page
Fixes #
```release-note
NONE
```

Add adopters to top menu

---

apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
apis/visibility/v1alpha1/types.go
client-go/applyconfiguration/visibility/v1alpha1/clusterqueue.go

/kind cleanup
JSON mapping in `apis/visibility/v1alpha1/types.go` did not follow convention
```release-note NONE
```

Fix JSON mapping in visibility types

---

CHANGELOG/CHANGELOG-0.5.md
README.md
charts/kueue/Chart.yaml
site/config.toml

Part of #1368 
```release-note
NONE
```

Update latest version to v0.5.1

---

site/content/en/docs/concepts/admission_check.md

Corrected multiple incorrect link
Fixes #1357 
```release-note
```

corrected incorrect links

---

pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
pkg/util/testingjobs/mxjob/wrappers.go
test/integration/controller/jobs/kubeflow/kubeflowjob.go
test/integration/controller/jobs/mxjob/mxjob_controller_test.go
test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
test/integration/controller/jobs/tfjob/tfjob_controller_test.go
test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go

/kind cleanup
- Add a unit test for applying node selectors on admission
- Clean up integration tests
As part of investigation for #1407
```release-note
```

Clean up unit and integration test for kubeflow

---

site/content/en/docs/concepts/cluster_queue.md

the original link will route to the top of the page
with fixing , it can jump to correct place
Tested on MacOS, both on Google Chrome and Microsoft Edge
Fixes #
```release-note
```

doc: fix link issue

---

test/e2e/e2e_test.go
test/e2e/suite_test.go

/kind feature
This PR continues the development of [KEP#168-2](https://github.com/kubernetes-sigs/kueue/pull/1300)
This PR is based on the [Return 404 for non-existent queues for the visibility endpoints](https://github.com/kubernetes-sigs/kueue/pull/1415) PR. I'll rebase this one when the mentioned PR is merged
```release-note
NONE
```

Add e2e tests that test RBAC to the Visibility API

---

Makefile
apis/visibility/v1alpha1/openapi/doc.go
charts/kueue/templates/rbac/role.yaml
config/components/rbac/role.yaml
pkg/visibility/server.go

/kind bug
Since we use the API Aggregation layer on the VisibilityOnDemand, the kueue-manager needs to have permission to list flowschemas and prioritylevelconfigurations.
Fixes #1430
```release-note
NONE
```

Add RBAC for the flowcontrol.apiserver.k8s.io

---

site/content/en/docs/concepts/resource_flavor.md

Add documentation for resource flavor tolerations.
Fixes #1233 
```release-note
NONE
```

[site] Add documentation for resource flavor tolerations.

---

pkg/scheduler/scheduler_test.go

/kind bug
/kind flake
Ensures resetting the value of a feature gate when the test finishes.
Fixes #1455
```release-note
NONE
```

Reset PrioritySortingWithinCohort when test finishes

---

pkg/constants/constants.go
pkg/controller/core/core.go
pkg/controller/core/workload_controller.go
pkg/controller/core/workload_controller_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/client.go

/kind bug
Cherry-pick  #1436 to release-0.5
Fixes #1392
```release-note
Added event for QuotaReserved and fixed event for Admitted to trigger when admission checks complete
```

[release 0.5] Record events when QuotaReservation and Admition take place.

---

cmd/kueue/main.go

/kind feature
Log which integrations are enabled, to improve observability.
Part of #1407
```release-note
NONE
```

Log setup of integrations

---

.openvex/templates/README.md
.openvex/templates/main.openvex.json

Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
`#SecuritySlam`
This PR adds an initial .openvex directory to the project.
This commit is part of the December 2023 Security Slam. 
```release-note
NONE
```

Initial .openvex setup

---

.github/workflows/openvex.yaml

Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
`#SecuritySlam`
This PR adds a github action to generate openvex data on each release.
This commit is part of the December 2023 Security Slam.
```release-note
NONE
```
/assign @ArangoGutierrez

Generate openvex data on each release

---

site/content/en/docs/concepts/workload.md

update documentation for .spec.Active field in Workload sections inside concepts
For issue #1091
```release-note
NONE
```

update documentation for Active field

---

Makefile
charts/kueue/templates/rbac/role.yaml
config/components/rbac/role.yaml
pkg/visibility/server.go

/kind bug
Fixes the RBAC for the APF controller, necessary for the apiserver-extensions.
Part of investigation for #1372 
I identified this problem while looking at the logs for the flaky E2E test.
This won't solve the flakiness, but will cleanup the log lines from one red-herring.
```release-note
NONE
```

Fix RBAC for the APF controller

---

hack/e2e-common.sh

/kind cleanup
Use `kind export logs` to get way more logs from kind.
Fixes #1452 
```release-note
NONE
```

call export logs for kind on e2e tests

---

charts/kueue/templates/rbac/role.yaml
config/components/rbac/role.yaml
pkg/visibility/server.go

/kind bug
Adds necessary patch permission for APF controller
Follow up to #1468
```release-note
NONE
```

Add patch permissions for flowcontrol

---

hack/kind-cluster.yaml

/kind cleanup
Increases log level of k8s components in order to diagnose problems such as #1372 in the future.
Fixes #
```release-note
NONE
```

Increase log level in k8s components

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
SECURITY-INSIGHTS.yaml
SECURITY-INSIGHTS.yml

Signed-off-by: Ashish Malik [malikashish493@gmail.com](mailto:malikashish493@gmail.com)
#SecuritySlam
This PR adds security insights yml file
This commit is part of the December 2023 Security Slam.
```release-note
NONE
```

Added security insight

---

site/genref/config.yaml

/kind bug
Current genref's config doesn't seem to work well: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1495/pull-kueue-verify-main/1737062759259967488
Fixes #
```release-note
NONE
```

Fix a genref's config

---

test/integration/controller/admissionchecks/provisioning/provisioning_test.go

/kind cleanup
Fix integration test for [test/integration/controller/admissionchecks/provisioning/provisioning_test.go](https://github.com/kubernetes-sigs/kueue/blob/main/test/integration/controller/admissionchecks/provisioning/provisioning_test.go)
Fixes #1484
```release-note
NONE
```

Fix provisioning request test

---

site/content/en/docs/concepts/cluster_queue.md

/kind cleanup
Fixes #
```release-note
None
```

fix invalid link for reserved resource name

---

charts/kueue/templates/rbac/role.yaml
config/components/rbac/role.yaml
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go

Manual cherry-pick of #1486 into 0.5.x branch.
/kind bug
Fixes #1485
```release-note
Add Missing RBAC on integration finalizers sub-resources
```

Add required RBAC on integration finalizers sub-resources (#1486)

---

cmd/experimental/podtaintstolerations/controller/pod_jobs.go

/kind clenaup
Just walk through some pod related codes, and found some cleanup.
Fixes #
```release-note
None
```

cleanup for pod jobs

---

pkg/cache/clusterqueue.go
pkg/cache/clusterqueue_test.go

/kind cleanup
This was missed in #932
```release-note
NONE
```

Fix copyright in cache package

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
.github/workflows/sbom.yaml

Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
`#SecuritySlam`
This PR adds a github action to generate an sbom for each release.
The action must be run manually, AFTER the release has been cut. 
The NEW_RELEASE template has also been updated to include this step as part of the release process.
This commit is part of the December 2023 Security Slam.
```release-note
NONE
```
/assign @ArangoGutierrez

Generate SBOM on each release

---

test/integration/scheduler/scheduler_test.go

/kind bug
/kind flake
Add a hold in the CQ, observe all workloads in metrics and then remove the hold.
This is more reliable than the older approach of creating the localQueue after the workloads, because we can't guarantee Kueue observes workloads and queue updates in order.
Fixes #1543
While this issue has always existed, it's not possible to backport, because the stopPolicy is a new feature.
Nevertheless, the failure rate of the test is extremely low.
```release-note
NONE
```

Fix flaky test: hold CQ until all workloads are observed

---

pkg/controller/jobs/pod/pod_controller_test.go
test/integration/controller/jobs/pod/pod_controller_test.go

/kind cleanup
More complex unit test for replacement in a pod group, involving different phases.
Fixes #
```release-note
NONE
```

UT for replacement in pod group with different phases

---

hack/e2e-common.sh
pkg/util/kubeversion/kubeversion.go
pkg/util/testingjobs/pod/wrappers.go
test/e2e/config/controller_manager_config.yaml
test/e2e/config/kustomization.yaml
test/e2e/config_1_26/kustomization.yaml
test/e2e/config_1_26/manager_e2e_patch.yaml
test/e2e/singlecluster/pod_test.go
test/integration/scheduler/scheduler_test.go
test/util/util.go

/kind cleanup
Adds a basic E2E for pod groups (admit, check finished, clean up).
Fixes #
I'll follow up with more tests about retries and preemption.
```release-note
NONE
```

Basic E2E test for pod groups

---

charts/kueue/templates/webhook/webhook.yaml

This PR aims to sync the [webhook.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/charts/kueue/templates/webhook/webhook.yaml) with [manifest.yaml](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/webhook/manifests.yaml) manually first.
Only after those two files in the same sequence, we can push forward to write a [script](https://github.com/kubernetes-sigs/kueue/blob/main/hack/update-helm.sh), and sync the webhook config automatically.
part of #1560
```release-note
Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob, and JobSet
```

Helm: Add Mutating WebhookConfigurations for the AdmissionCheck, RayJob and JobSet

---

pkg/scheduler/scheduler_test.go

/kind cleanup
To demonstrate that the code works as expected in the scenario depicted in [here](https://github.com/kubernetes-sigs/kueue/assets/43413443/3ee2a4f6-d8ee-4bb4-96d8-2e9662e8869c). See also for discussion under: https://github.com/kubernetes-sigs/kueue/pull/1571.
The actual test scenario here is simplified, but captures the same intention, that the workload awaiting for CQ B is not blocked.
Fixes #
I tested that the test fails if the changes are simplified as attempted in https://github.com/kubernetes-sigs/kueue/pull/1571
```release-note
NONE
```

Add unit test for preemption while borrowing when multiple jobs in a cycle

---

test/e2e/singlecluster/e2e_test.go
test/e2e/singlecluster/pod_test.go
test/util/util.go

/kind cleanup
Improve E2E coverage for pod groups with cases:
- Delete an incomplete group.
- Replace a failed Pod.
Fixes #
```release-note
NONE
```

E2E tests partial pod groups and replacements

---

pkg/controller/jobframework/validation.go

/kind cleanup
Fixes #
```release-note
NONE
```

Use constants in the supportedPrebuildWlJobGVKs

---

test/e2e/config/kustomization.yaml
test/e2e/config_1_26/kustomization.yaml

/kind cleanup
Part of #1593
```release-note
NONE
```

Use log level 3 in E2E tests

---

test/util/util.go

/kind cleanup
Improve debuggability of Pod cleanup
Part of #1591
```release-note
NONE
```

Wrapping errors when cleaning up pods

---

pkg/controller/jobframework/interface.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/pod/pod_controller_test.go

/kind bug
Issue one event per pod during admission.
Fixes #
Fix for unreleased feature.
```release-note
NONE
```

Event for pod admission once per pod

---

CHANGELOG/CHANGELOG-0.5.md
README.md
charts/kueue/Chart.yaml

I updated the version in manifests and docs.
Fixes #
```release-note
NONE
```

Prepare release for v0.5.2

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

I updated the `Submit a PR against [k8s.io](https://github.com/kubernetes/k8s.io)` step.
Fixes #
```release-note
NONE
```

Update an issue template for the new release

---

CHANGELOG/CHANGELOG-0.5.md
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/config.toml

Part-of: #1539
```release-note
NONE
```

Update latest version to v0.5.2

---

keps/693-multikueue/README.md

/kind cleanup
To make a clear statement that MultiKueue will run each job on a single worker, so that mirroring is simple.
This is going to be referenced from https://github.com/kubernetes/enhancements/pull/4370 for the
means of discussion: https://github.com/kubernetes/enhancements/pull/4370#discussion_r1458782164
Part of #693
```release-note
NONE
```

Explicit non-goal for distributing Jobs across multiple worker clusters

---

pkg/controller/jobs/pod/pod_controller.go
pkg/util/parallelize/parallelize.go
pkg/util/parallelize/parallelize_test.go

/kind feature
Paralelize updates to pod objects. These operations can be slow, as they require a connection with the apiserver.
Fixes #
```release-note
NONE
```

Parallelize operations in groups of pods

---

site/content/en/docs/tasks/_index.md

Add JobSet to tasks
Fixes #1522
```release-note
NONE
```

add jobset to tasks

---

pkg/config/validation.go

/kind cleanup
I replaced the "k8s.io/utils/strings/slices" with a native `slices` library.
Fixes #
```release-note
NONE
```

Use a native slices library

---

keps/1136-provisioning-request-support/README.md

/kind cleanup
Fixes links in KEP 1136
```release-note
```

Improve links in KEP #1136

---

.github/dependabot.yml

/kind cleanup
Dependabot is opening up PRs individually for k8s packages. We can actually group all the Kubernetes dependencies together to minimize the amount of PRs that we are getting for updates.
See https://github.com/cri-o/cri-o/pull/7707 for an example of what this syntax does.
Fixes #
```release-note
NONE
```

Dependabot can update kubernetes dependencies as a group

---

site/content/en/docs/tasks/run_rayjobs.md

Add one of the following kinds:
Updates RayJob documentation
Fixes #
```release-note
RayJob integration is enabled by default, updated its documentation to reflect this
```

[website] Updated RayJob Documentation

---

site/content/en/docs/overview/_index.md

Just a small single-letter typo fix.

fix: typo in, "Why Kueue?"

---

CHANGELOG/CHANGELOG-0.5.md
README.md
charts/kueue/Chart.yaml

Update manifest versions
Part of #1711
```release-note
NONE
```

Prepare for release v0.5.3

---

CHANGELOG/CHANGELOG-0.5.md
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/config.toml

Update latest release
Part of #1711
```release-note
NONE
```

Update latest release v0.5.3

---

pkg/queue/cluster_queue_best_effort_fifo.go
pkg/queue/cluster_queue_impl.go
pkg/queue/cluster_queue_impl_test.go
pkg/queue/cluster_queue_strict_fifo.go
pkg/queue/manager_test.go

/kind cleanup
I removed unnecessary stubs from clusterQueueBase.
Fixes #
Context: https://github.com/kubernetes-sigs/kueue/pull/1709#discussion_r1486394042
```release-note
NONE
```

Remove stubs from clusterQueueBase

---

site/content/en/docs/concepts/workload.md
site/content/en/docs/tasks/setup_sequential_admission.md

I added documentation for the PodsReadyRequeueStrategy.
Fixes #1282 
```release-note
NONE
```

Doc: Add PodsReadyRequeueStrategy documentation

---

CHANGELOG/CHANGELOG-0.6.md
Makefile
README.md
charts/kueue/Chart.yaml
config/components/manager/kustomization.yaml
site/config.toml

Prepare release notes and files for v0.6.0
Part of #1729
```release-note
NONE
```

Prepare release notes and files for v0.6.0

---

.github/workflows/openvex.yaml

/kind bug
Fixes #
```release-note
NONE
```

Fix filename for openvex artifact

---

site/content/en/docs/admission-check-controllers/multikueue.md
site/content/en/docs/reference/kueue-alpha.v1alpha1.md
site/genref/config.yaml
site/static/examples/multikueue/multikueue-setup.yaml

Add documentation for MultiKueue..
Relates to #693 
```release-note
NONE
```

[doc] MultiKueue

---

pkg/cache/snapshot.go

/kind cleanup
Clone is slightly faster
Fixes #
```release-note
NONE
```

Use maps.Clone when snapshotting

---

pkg/controller/jobs/pod/pod_controller_test.go

/kind cleanup
This PR adds tests to ensure that pods are still observed in case errors occur during the cleanup process's create/update operations
Fixes [#1636](https://github.com/kubernetes-sigs/kueue/issues/1636)
```release-note
NONE
```

Test that pods are observed when there are error during the cleanup

---

site/content/en/docs/admission-check-controllers/_index.md

Small typo fix in Kueue documentation

Admisssion to Admission doc typo

---

site/content/en/docs/admission-check-controllers/provisioning.md
site/content/en/docs/adopters/index.md
site/content/en/docs/concepts/admission_check.md
site/content/en/docs/concepts/cluster_queue.md
site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
site/content/en/docs/tasks/run_rayclusters.md
site/static/examples/python/README.md

/kind 
Typo fixes from all docs inside `/site`
Addresses this comment from previous PR: https://github.com/kubernetes-sigs/kueue/pull/1748#issuecomment-1948642434 
cc: @alculquicondor @tenzen-y Thanks!

Typo fixes on all /site docs

---

.openvex/templates/README.md
CHANGELOG/CHANGELOG-0.3.md
CONTRIBUTING.md
keps/168-2-pending-workloads-visibility/README.md
keps/168-pending-workloads-visibility/README.md
keps/487-kubectl-plugin/README.md
keps/582-preempt-based-on-flavor-order/README.md
keps/693-multikueue/README.md
keps/78-dynamically-reclaiming-resources/README.md
keps/79-hierarchical-cohorts/README.md
keps/83-workload-preemption/README.md
keps/976-plain-pods/README.md
keps/993-two-phase-admission/README.md
pkg/controller/jobs/rayjob/rayjob_webhook.go
pkg/queue/cluster_queue_best_effort_fifo_test.go
pkg/scheduler/flavorassigner/flavorassigner.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/webhooks/workload_webhook.go
pkg/webhooks/workload_webhook_test.go
pkg/workload/workload.go
pkg/workload/workload_test.go
test/integration/controller/jobs/kubeflow/kubeflowjob.go

Typo fixes on all `.md` files + on the `AssigmentClusterQueueState` type and made updates in the codebase accordingly.
This is a follow-on PR from https://github.com/kubernetes-sigs/kueue/pull/1744 . Thanks @mimowo for the previous review and suggestion.

Typo fixes on all docs and on 'AssignmentClusterQueueState' type

---

site/content/en/docs/concepts/cluster_queue.md

add documents for feature LendingLimit
#1224 
```release-note
NONE
```

[Doc]Add documents for feature LendingLimit

---

Makefile

/kind cleanup
Speeds up integration tests via parallelization
Related to #1737
```release-note
NONE
```

Parallelize integration tests

---

pkg/cache/cache.go

/kind cleanup
Fixes #
```release-note
NONE
```

Remove unnecessary nil check

---

hack/create-multikueue-kubeconfig.sh
hack/multikueue-e2e-test.sh

/kind feature
Use a custom service account and role when generating the multikueue kubeconfigs.
Relates to  #693 
```release-note
NONE
```

[e2e/multikue] Use a custom service account and role

---

Makefile

After upgrading the CI image to kubekins, the golangci-lint was failing tests. Upgrading to a newer version in the makefile fixed it.
Fixes #
cc @alculquicondor 
```release-note
NONE
```

Upgrade golangci-lint to `v1.56.2`

---

keps/1788-pass-parameters-to-ProvReq/README.md

To correct changes done by mentioned [here](https://github.com/kubernetes-sigs/kueue/pull/1793#discussion_r1512828373)
```release-note
NONE
```

Discard the alpha infix in the ProvReq annotation name

---

.golangci.yaml
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/raycluster/raycluster_webhook.go
test/integration/controller/jobs/jobset/jobset_controller_test.go
test/integration/controller/jobs/mpijob/mpijob_controller_test.go
test/integration/controller/jobs/raycluster/raycluster_controller_test.go
test/integration/controller/jobs/rayjob/rayjob_controller_test.go
test/util/util.go

/kind cleanup
This PR removes unnecessary conversions throughout the codebase. Additionally, it enables `unconvert` linter to automatically detect these types of redundancies.
```release-note
NONE
```

Simplify code by removing unnecessary conversions

---

pkg/controller/admissionchecks/multikueue/multikueuecluster.go
pkg/controller/admissionchecks/multikueue/workload.go

/kind bug
Limit the number and severity of logged errors during normal operations.
Fixes #1814 
```release-note
NONE
```

[multikueue] Decrease the number logged errors

---

config/visibility/kustomization.yaml

/kind bug
[e2e] Fix visibility tests.
Fixes #
```release-note
NONE
```

[e2e] Fix visibility tests.

---

Makefile
hack/e2e-common.sh
hack/e2e-test.sh
hack/multikueue-e2e-test.sh

/kind bug
Restore the manager's image from the bash scripts.
The bug looks to be introduced by :
- #1730
Fixes #
```release-note
NONE
```

[e2e] Restore the manager's image from the bash scripts.

---

pkg/util/testing/client.go
test/util/util.go

/kind cleanup
I cleaned up test utils.
- Remove unused function
- Fix typos
- Make vars to camelCase
Fixes #
```release-note
NONE
```

Clean up test utils

---

CHANGELOG/CHANGELOG-0.6.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/config.toml

Part of #1842
```release-note
NONE
```

Update latest version to v0.6.1

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
site/content/en/_index.html

Fixes spelling in the `GitHub` word.
See https://github.com/logos
```release-note
NONE
```

[doc] fix typo in 'GitHub'

---

site/content/en/docs/concepts/resource_flavor.md

A simple typo fix, for [the very first 'Concept'](https://kueue.sigs.k8s.io/docs/concepts/resource_flavor/) on the website.
None.
None.
```release-note
NONE
```

Fix typo in resource_flavor.md

---

CONTRIBUTING.md
SECURITY.md

Looks like there are non-trivial updates in [kubernetes-template-project](https://github.com/kubernetes/kubernetes-template-project/) after this repository was generated from there. So this PR aggregates those changes in PRs [41](https://github.com/kubernetes/kubernetes-template-project/pull/41), [42](https://github.com/kubernetes/kubernetes-template-project/pull/42), and [43](https://github.com/kubernetes/kubernetes-template-project/pull/43), then introduces the aggregated changes here.
None
None
```release-note
NONE
```

[doc] Catch up the recent changes in kubernetes-template-project

---

pkg/controller/admissionchecks/multikueue/indexer_test.go
pkg/controller/admissionchecks/provisioning/indexer_test.go
pkg/util/admissioncheck/admissioncheck_test.go
pkg/util/testing/client.go

/kind cleanup
use utilruntime package wrap panic method
Fixes #
None
```release-note
None
```

test: use utilruntime package wrap panic method

---

site/content/en/docs/concepts/multikueue.md
site/content/en/docs/reference/kueue.v1beta1.md
site/content/en/docs/tasks/manage/setup_sequential_admission.md
site/layouts/shortcodes/include.html

Fixes website spelling mistakes.
Extracted from #1862
```release-note
NONE
```

[doc] typo fixes on site

---

keps/1136-provisioning-request-support/README.md
keps/693-multikueue/README.md
keps/78-dynamically-reclaiming-resources/kep.yaml
keps/976-plain-pods/README.md

Fixes spelling mistakes.
```release-note
NONE
```

[doc] typo fixes on keps

---

Makefile
test/e2e/multikueue/suite_test.go

/kind cleanup
We want to decrease the execution time of the e2e tests. In order to do so, I want to create a separate make target for the multikueue tests and remove multikueue tests from the existing test-e2e target (this PR) and run them in a separate job in the presubmits/periodic tests (separate PR as this is in a different repository).
Plus it fixes a typo in test/e2e/multikueue/suite_test.go 
Fixes #
```release-note
NONE
```
NONE

e2e speedup

---

cmd/importer/README.md

Fixes #
```release-note
NONE
```

Mention published importer image tag

---

cmd/importer/README.md

/kind cleanup
fix readme typo
Fixes #
None
```release-note
None
```

fix for importer readme

---

.golangci.yaml
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/job/job_controller_test.go

Reverts kubernetes-sigs/kueue#1907

Revert "[jobframework] Return all errors when updating workload status"

---

CHANGELOG/CHANGELOG-0.6.md
Makefile
README.md
charts/kueue/Chart.yaml
site/config.toml

Part of #1964
```release-note
NONE
```

Prepare release v0.6.2

---

Makefile
test/integration/controller/jobs/job/job_webhook_test.go

/kind cleanup
Update the default testing k8s versions
Fixes #
```release-note
None
```

Update the default testing k8s versions

---

CHANGELOG/CHANGELOG-0.6.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part of #1964
```release-note
NONE
```

Update latest version to v0.6.2

---

cmd/importer/README.md

Add more information about the importer flags.
Fixes #
```release-note
None
```

[importer] Extend README.md

---

pkg/scheduler/preemption/preemption.go

/kind cleanup
Remove unnecessary parameter
Follow up to #1979
```release-note
NONE
```

Remove unnecessary parameter for minimalPreemptions

---

keps/1714-fair-sharing/README.md

Fixes typos and clarifies rules in Fair Sharing KEP #1773 
None
```release-note
None
```

Fair sharing KEP rule typo fix

---

keps/1714-fair-sharing/README.md

Fixes sublists in KEP #1714 
```release-note
NONE
```

Fix sublists in KEP #1714

---

site/content/en/docs/admission-check-controllers/provisioning.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md

There isn't a troubleshooting case for cluster resources not matching what the pod needs.
Fixes #
NONE
```release-note
docs: troubleshooting section for matching cluster-queue resources
```

docs: add troubleshooting resource requests

---

site/content/en/docs/tasks/run/plain_pods.md

The example pod yaml in running plain pod has a generated name, which should use `kubectl create` instead of `kubectl apply` to execute.
Fixes #
```release-note
NONE
```

site: fix kubectl command of tasks example

---

site/content/en/docs/tasks/run/jobsets.md

- fix website url
- %w can be used only once in a format string
Fixes #
```release-note
None
```

doc: website jobset url

---

site/static/examples/jobs/sample-pytorchjob.yaml

/kind feature
Fixes #1910 
@kannon92 @tenzen-y 
```release-note
NONE
```

Update kubeflow sample pytorchjob to pytorch 2.x and cuda 12.x (#1910)

---

site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md

Fixes #
```release-note
NONE
```

docs: add troubleshooting resource requests (cherry pick of #2001)

---

test/e2e/multikueue/e2e_test.go

/kind bug
- Increased timeout for "Waiting for the cluster do become active" test.
Fixes #2045

[multikueue] Fix e2e test timeout issue

---

Makefile
test/scalability/README.md
test/scalability/minimalkueue/main.go
test/scalability/runner/main.go
test/scalability/runner/scraper/scraper.go

/kind feature
Make the scalability runner able to periodically scrape the metrics endpoint.
Relates to #1912
```release-note
None
```

Scalability scrape

---

site/content/en/docs/tasks/run/jobsets.md

fix jobset url
Fixes #
```release-note
```

docs: web url

---

pkg/workload/workload.go

/kind cleanup
This PR makes sure that all messages used to create conditions are truncated to avoid excessive length. Also, this contributes to code consistency.
Fixes #2064 
```release-note
NONE
```

Conditions creation code cleanup

---

Makefile

/kind cleanup
[makefile] Drop old `test-scalability` make target. 
`test-scalability` was only a temporary alias.
Fixes #
```release-note
None
```

[makefile] Drop old `test-scalability` make target.

---

Makefile
test/performance/scheduler/checker/checker_test.go
test/performance/scheduler/default_rangespec.yaml

/kind bug
- Extend the admission time for large workloads
- Only check the average mCPU usage of minimalkueue (not sys and user times)
- Extend the runner's timeout to 8 min
Fixes #2066
```release-note
None
```

[sclability] Relax the expectations.

---

pkg/scheduler/preemption/preemption_test.go

/kind bug
The test was referencing a CQ that didn't exist.
Fixes #
```release-note
NONE
```

Fix UTs for preemption with borrowing, missing CQ

---

pkg/controller/jobframework/validation.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/jobset/jobset_webhook.go
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_webhook.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_webhook.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
pkg/controller/jobs/mpijob/mpijob_webhook.go
pkg/controller/jobs/pod/pod_webhook.go
pkg/controller/jobs/raycluster/raycluster_webhook.go
pkg/controller/jobs/rayjob/rayjob_webhook.go

To simplify external integration, there should be a stable API that encapsulates the validation that is expected to be performed from webhooks on create and update operations on GenericJobs.
/kind cleanup
The jobframework should expose a stable and simple API that encapsulates all validation actions
that need to be performed from the web hooks of integrated frameworks. 
Fixes #
```release-note
NONE
```

Stable API to encapsulate Job validation for webhooks

---

site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_queues.md

Completing the troubleshooting puzzle.
Fixes #
```release-note
NONE
```

Doc for troubleshooting queues

---

test/performance/scheduler/default_rangespec.yaml

/kind flake
Fixes #2140
```release-note
NONE
```

Relax the threshold for the "Average wait for admission" scalability test

---

site/content/en/docs/concepts/cluster_queue.md

Add examples for namespaceSelector via matchLabels and matchExpressions.

---

site/content/en/docs/admission-check-controllers/provisioning.md

Sample manifest buttons in the `Provisioning Admission Check Controller` link to invalid `https://examples/provisioning/***.yaml` URLs.
e.g., 
https://kueue.sigs.k8s.io/docs/admission-check-controllers/provisioning/#setup
Fixes #
```release-note
NONE
```

[doc] Fix sample manifests path

---

pkg/controller/admissionchecks/provisioning/controller.go
test/integration/controller/admissionchecks/provisioning/provisioning_test.go

/kind bug
When provisioning request has Accepted=True and Provisioned is nil we cannot dereference the Provisioned status. Fixing it by checking that Provisioned is explicitly set to False. Testing it by separately setting Accepted=True (leaving Provisioned empty) and only then changing Provisioned=False. 
Fixes #2149
```release-note
Fix a bug that there is a potential null pointer error in the provisioning request controller.
```

Fixing a bug when provisioned condition is missing

---

site/content/en/docs/installation/_index.md
site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md

The visibility API manifest has been separated from the main manifest and the way of installing the visibility API has changed because of it. The updated documentation contains a new (correct) way to install the visibility API.
Fixes #
```release-note
NONE
```

Update and improve the visibility API documentation

---

test/integration/scheduler/podsready/scheduler_test.go

/kind cleanup
Cleanup the left over TODO after it has been addressed in https://github.com/kubernetes-sigs/kueue/pull/2131
Fixes #
```release-note
NONE
```

Cleanup the TODO in the integration test

---

site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md

Trying to enhance the documentation making very few assumptions about the knowledge of a Kubernetes system.
Fixes #
```release-note
NONE
```

Enhance troubleshooting for pending jobs

---

site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md

Cherry pick of #2185 on website.
#2185: Enhance troubleshooting for pending jobs
```release-note
```

Automated cherry pick of #2185: Enhance troubleshooting for pending jobs

---

pkg/controller/admissionchecks/multikueue/fswatch_test.go

Some tests for fswatch not working on Mac OS due to errors on fsnotify (https://github.com/fsnotify/fsnotify/issues/636 and https://github.com/fsnotify/fsnotify/issues/637). It's not critical to test it on MacOS, so we can skip it for now until it's fixed on external library.
Fixes #
```release-note
NONE
```

Skip invalid fswatch tests on Mac OS.

---

test/e2e/singlecluster/pod_test.go

Cherry pick of #2236 on release-0.6.
#2236: Fixed "Pod groups when Single CQ should admit group that
```release-note
NONE
```

Automated cherry pick of #2236: Fixed "Pod groups when Single CQ should admit group that

---

Makefile

/kind bug
Fixes #
[release-0.6]Update golangci-lint to 1.55.2 (the latest release before go 1.22 support).
This should fix a linter panic observed in #2271 and #2273
```release-note
None
```

[release-0.6]Update golangci-lint to 1.55.2

---

go.mod
go.sum
pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
pkg/controller/admissionchecks/multikueue/workload_test.go
pkg/controller/admissionchecks/provisioning/controller_test.go
pkg/controller/core/workload_controller_test.go
pkg/controller/jobs/job/job_controller_test.go
pkg/controller/jobs/pod/pod_controller_test.go
pkg/controller/jobs/raycluster/raycluster_controller_test.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/client.go
pkg/workload/workload_test.go

Cherry pick of #1819 to release-0.6
```release-note
```

Cherry pick of #1819 to release-0.6

---

CHANGELOG/CHANGELOG-0.6.md

Part of #2231
```release-note
NONE
```

Add additional fix to v0.6.3

---

cloudbuild.yaml

/kind cleanup
Looking at the testgrid (https://testgrid.k8s.io/sig-k8s-infra-gcb#post-kueue-push-images), we can see that building the main branch is taking around 30 minutes. This is somehow reasonable, as we build 3 images, each with multiple architectures.
Then the only alternative is to use a bigger VM
Fixes #
```release-note
NONE
```

Use a bigger machine for cloudbuild

---

CHANGELOG/CHANGELOG-0.6.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part of #2231
```release-note
NONE
```

Update latest version to v0.6.3

---

charts/kueue/values.yaml
config/components/manager/controller_manager_config.yaml

There is not the default value in the `waitForPodsReady.requeuingStrategy.backoffMaxSeconds`.
Fixes #
```release-note
NONE
```

Add the default parameters in the waitForPodsReady.requeuingStrategy.backoffMaxSeconds

---

.github/workflows/sbom.yaml

/kind cleanup
We should use the root Go version in the gh-actions.
xref: https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
Fixes #
```release-note
NONE
```

Use root Go version in gh-actions

---

site/content/en/docs/admission-check-controllers/provisioning.md
site/content/en/docs/concepts/admission_check.md
site/content/en/docs/concepts/cluster_queue.md
site/static/examples/provisioning/provisioning-setup.yaml

This is a follow up to #1996 to make the new setting more discoverable.
Fixes #
```release-note
NONE
```

Enhance documentation for admissionChecksStrategy

---

Makefile
hack/multiplatform-build.sh
site/content/en/docs/reference/kubectl-kueue/installation.md

/kind bug
Unfortunately github doesn't allow to upload directories. So we need to build binaries to `artifacts` root directory.
Fixes #
For more details  you can a look on https://github.com/kubernetes-sigs/kueue/pull/2306#issuecomment-2140506121.
```release-note
NONE
```

[kueuectl] Build binaries to artifact directory

---

site/content/en/docs/concepts/_index.md
site/content/en/docs/concepts/cluster_queue.md
site/content/en/docs/concepts/multikueue.md
site/content/en/docs/concepts/preemption.md
site/content/en/docs/installation/_index.md

Make a concept page just for preemption and explain both classic preemption and fair sharing.
Part of #1714
Preview of new page https://deploy-preview-2322--kubernetes-sigs-kueue.netlify.app/docs/concepts/preemption/#fair-sharing
```release-note
NONE
```

Add documentation for fair sharing

---

CHANGELOG/CHANGELOG-0.7.md
Makefile
README.md
charts/kueue/Chart.yaml
config/components/manager/kustomization.yaml
site/hugo.toml

Part of #2305
```release-note
NONE
```

Prepare release-0.7 branch

---

.github/workflows/sbom.yaml

/kind cleanup
To fetch Go version from go.mod, we need to perform the checkout action, first.
Fixes #
```release-note
NONE
```

Move checkout action to the top

---

go.mod

/kind bug
It looks like the dependencies don't like having a minor version only. Adding latest patch version for now.
Fixes #
```release-note
NONE
```

Use latest patch version for golang

---

site/content/en/docs/installation/_index.md

Document issue #2277.  Didn't mark as fixing so that the issue won't be auto-closed just because we document the problem.
```release-note
NONE
```

document that enabling manageJobsWithoutQueueName can be risky

---

cmd/OWNERS

Adds @trasc as approver for `<kueue>/cmd`
Fixes #
```release-note
None
```

Add myself as approver for `<kueue>/cmd`

---

CHANGELOG/CHANGELOG-0.7.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part of #2305
```release-note
NONE
```

Update latest release to v0.7.0

---

OWNERS
hack/OWNERS
pkg/OWNERS
test/OWNERS

/kind cleanup
This is a follow up to the gradual increase of my approval rights started in https://github.com/kubernetes-sigs/kueue/pull/1722 (February 2024).
My reviewing contributions are 203 merged PRs by now: https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Amimowo+-author%3Amimowo.
Fixes #
Before approving bigger or less obvious changes to KEPs or APIs, or changes which are outside of my area of expertise, I'm going to still defer for input from @tenzen-y or @alculquicondor. 
```release-note
NONE
```

Self-nominate mimowo as top-level approver

---

test/integration/kueuectl/list_test.go

/kind flake
Make test "should print workloads list with paging" less likely to fail
Part of  #2353
Sometime it's not enough one second to create resources and execute command. And it's printing Age with 1s instead 0s.
```release-note
NONE
```

Make test "should print workloads list with paging" less likely to fail

---

charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
hack/internal/tools/go.mod
hack/internal/tools/go.sum

/kind cleanup
Bumps [sigs.k8s.io/controller-tools](https://github.com/kubernetes-sigs/controller-tools) from 0.14.0 to 0.15.0.
Fixes #
```release-note
None
```

[manual] Bump sigs.k8s.io/controller-tools from 0.14.0 to 0.15.0 in /hack/internal/tools

---

test/e2e/multikueue/suite_test.go
test/e2e/singlecluster/suite_test.go
test/integration/framework/framework.go
test/util/util.go

/kind cleanup
Setup the controller-runtime logger in e2e tests. 
Fixes #
```release-note
None
```

Setup the controller-runtime logger in e2e tests.

---

pkg/queue/cluster_queue.go
pkg/queue/cluster_queue_test.go

/kind bug
When backoff finished we have race condition on the Workload Reconcile and the Scheduler. The Scheduler using old version of the Workload (version of workload before updated Requeue condition to true) and rewriting conditions (already updated by reconciler) when admitting. So we need to wait before Requeue condition to be true.
Fixes #2291 
```bash
> kubectl get workload -w --output-watch-events -ocustom-columns=EVENT:.type,NAME:.object.metadata.name,ACTIVE:.object.spec.active,CONDITIONS:.object.status.conditions | ts "%Y-%m-%d %H:%M:%.S"
2024-06-04 09:06:58.564580 EVENT   NAME                   ACTIVE   CONDITIONS
2024-06-04 09:06:58.564735 ADDED   job-sample-job-992ea   true     <none>
2024-06-04 09:06:58.572070 MODIFIED   job-sample-job-992ea   true …
```

Wait for Requeue condition before push to heap.

---

Makefile-deps.mk

/kind bug
Corrects the name of the module from which the helm version comes.
Fixes #2284
```release-note
NONE
```

[tools] Fix the name of the module from which the helm version comes.

---

test/OWNERS

Add myself as approver for <kueue>/test
Fixes #
```release-note
None
```

Add myself as approver for `<kueue>/test`

---

charts/kueue/values.yaml

fix typo in comment

---

site/content/en/docs/tasks/manage/setup_sequential_admission.md

Fixes #
```release-note
NONE
```

docs(site): Fix typo in sequential admission docs

---

cmd/kueuectl/app/cmd.go
cmd/kueuectl/app/testing/fake.go
cmd/kueuectl/app/version/version.go
cmd/kueuectl/app/version/version_test.go
site/content/en/docs/reference/kubectl-kueue/commands/version.md

/kind feature
Add version command
Fixes #
```release-note
CLI: Added version command.
```

[kueuectl] Add version command

---

test/integration/kueuectl/list_test.go

/kind flake
Fix "Should print cluster queues list with paging" test.
Fixes #2353
Fixes for https://github.com/kubernetes-sigs/kueue/issues/2353#issuecomment-2159897688.
`Active` status calculated by `meta.IsStatusConditionTrue(cq.Status.Conditions, v1beta1.ClusterQueueActive)`. Sometime we don't have time to set this condition to `True` between creation clusterqueues (an `JustBeforeEach`) and print list of clusterqueues. That's why we have `active = false`. So we need to wait time to be sure that status set to `true`.
```release-note
NONE
```

[kueuectl] Fix "Should print cluster queues list with paging" test.

---

cmd/kueuectl/app/list/helpers.go
cmd/kueuectl/app/list/list_workload.go
cmd/kueuectl/app/list/list_workload_test.go
cmd/kueuectl/app/testing/fake.go
cmd/kueuectl/app/util/client_getter.go

/kind feature
Allows filtering workloads by:
- Name
- Type
- API Group
Fixes #2168 
```release-note
Adds 'for' filter to list workloads.
```

[kueuectl]  Add `for` filter to list workloads

---

test/integration/controller/jobs/jobset/jobset_controller_test.go

/kind flake
Fixes the flaky test of jobset controller 
Fixes #2398 
```release-note
NONE
```

Fix flaky jobset integration test

---

cmd/kueuectl/app/completion/completion.go
cmd/kueuectl/app/completion/completion_test.go
cmd/kueuectl/app/list/list_workload.go
cmd/kueuectl/app/resume/resume.go
cmd/kueuectl/app/resume/resume_localqueue.go
cmd/kueuectl/app/stop/stop.go
cmd/kueuectl/app/stop/stop_localqueue.go
site/content/en/docs/reference/kubectl-kueue/commands/resume.md
site/content/en/docs/reference/kubectl-kueue/commands/stop.md
test/integration/kueuectl/resume_test.go
test/integration/kueuectl/stop_test.go

/kind feature
Add stop/resume localqueue commands.
Fixes #2138 #2139
```release-note
CLI: Add stop/resume localqueue commands
```

[kueuectl] Add stop/resume localqueue commands.

---

test/integration/kueuectl/list_test.go

/kind cleanup
Move "List workload" test to Describe instead of another When.
Fixes #
```release-note
NONE
```

[kueuectl] Move "List workload" test to Describe.

---

pkg/controller/admissionchecks/multikueue/admissioncheck.go
pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
pkg/controller/admissionchecks/multikueue/indexer.go
pkg/controller/admissionchecks/multikueue/jobset_adapter.go
pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
pkg/controller/admissionchecks/multikueue/workload.go
pkg/controller/admissionchecks/multikueue/workload_test.go
test/integration/multikueue/multikueue_test.go

/kind cleanup
Use the MultiKueue controller name defined in the API `kueuealpha.MultiKueueControllerName` and drop it's local definition.
Relates to #2416
```release-note
None
```

[multikueue] Use the API controller name.

---

test/integration/controller/admissionchecks/provisioning/provisioning_test.go

/kind cleanup
Deletes repetitive variable assignments in provisioning integration tests
```release-note
NONE
```

Clean up provisioning integration tests

---

keps/693-multikueue/README.md
keps/693-multikueue/kep.yaml

Add subcomponents and integration details in MultiKueue's KEP. 
Relates to #693
```release-note
None
```

[multikueue] KEP add subcomponents and integration details.

---

.github/dependabot.yml

/kind feature
Update dependabot to track package updates for kjobctl.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/2444#discussion_r1646588379
```release-note
NONE
```

Update dependabot to track package updates for kjobctl.

---

site/content/en/docs/admission-check-controllers/provisioning.md

Add link to ClusterAutoscaler ProvisioningRequest FAQ

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/clusterqueue.go
pkg/cache/clusterqueue_test.go
pkg/cache/snapshot.go
pkg/cache/snapshot_test.go
pkg/resources/resource.go
pkg/scheduler/flavorassigner/flavorassigner.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

- Move FlavorResourceQuantities to its own package
- Define FlavorResource, FlavorResourceQuantitiesFlat
- Update tests to use new types
/kind cleanup
Completes parts 1-3 of #2447 - broken into commits corresponding to each of those parts. There are no changes to logic, only updating references to the old type, and updating tests to use the new type.
I recommend reviewing this PR starting one commit at a time, as they are logically grouped.
Changes to tests (commit#3) were executed in an automated fashion using [this code](https://github.com/gabesaba/GoLangAutomaticRefactor/blob/cee237f6698ecacde83dc23dfffc7b5588f5e0c6/kueue_2448/main.go), and some formatting via sed.
```release-note
NONE
```

Define FlavorResource, FlavorResourceQuantitiesFlat

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
SECURITY-INSIGHTS.yaml

/kind cleanup
Fixes #1470 
```release-note
NONE
```

Add sbom section to the security insights file

---

Dockerfile
cmd/experimental/podtaintstolerations/Dockerfile
cmd/importer/Dockerfile

/kind cleanup
Set `AS` to uppercase in Dockerfile  to avoid FromAsCasing warning.
Fixes #
> While Dockerfile keywords can be either uppercase or lowercase, mixing case styles is not recommended for readability. This rule reports violations where mixed case style occurs for a `FROM` instruction with an `AS` keyword declaring a stage name.
https://docs.docker.com/reference/build-checks/from-as-casing/
```release-note
NONE
```

Set `AS` to uppercase in Dockerfile  to avoid FromAsCasing warning.

---

cmd/experimental/kjobctl/go.mod
cmd/experimental/kjobctl/go.sum
cmd/experimental/kjobctl/pkg/builder/builder.go
cmd/experimental/kjobctl/pkg/builder/builder_test.go
cmd/experimental/kjobctl/pkg/builder/job_builder.go
cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
cmd/experimental/kjobctl/pkg/constants/constants.go

/kind feature
Add job builder for kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add job builder.

---

apis/visibility/v1alpha1/conversion_test.go
apis/visibility/v1alpha1/defaults.go

/kind cleanup
it is desirable to have hermetic API packages (not depending on packages in `pkg/`). This PR removes such dependency. 
Fixes #
```release-note
NONE
```

Remove dependency of apis/ on pkg/

---

site/content/en/docs/tasks/dev/integrate_a_custom_job.md

Document that part of registering an external framework is augmenting the RBAC's for the Kueue controller. 
Fixes #
```release-note
NONE
```

Document RBAC augmentation for external frameworks

---

.shellcheckrc
hack/verify-shellcheck.sh

/kind fix
Disable ignoring warnings and error for shellcheck
Fixes #
```release-note
NONE
```

Fix shellcheck not working

---

go.mod

/kind cleanup
Update golang to the latest version.
Fixes #
```release-note
NONE
```

Update golang version (1.22.3 -> 1.22.4)

---

Makefile

/kind cleanup
Remove kjobctl verification from main Makefile.
Fixes #
We already have specific test `pull-kueue-test-kjobctl` for kjobctl. So now it's not need to verify it on main verification command.
```release-note
NONE
```

Remove kjobctl verification from main Makefile.

---

pkg/cache/snapshot.go
pkg/scheduler/logging.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler.go
pkg/workload/workload.go

/kind feature
Improving logging to better diagnose issues with scheduling and preemption.
Added a number id to each scheduling cycle for better filtering.
Fixes #
```release-note
Improved logging for scheduling and preemption in levels 4 and 5
```

Enhance scheduler and preemption logging

---

test/util/util.go

/kind cleanup
To prevent Handling job with no workload error we need to clean jobsets.
Fixes #
```
2024-06-29T03:29:55.453135835Z	ERROR	jobframework/reconciler.go:384	Handling job with no workload	{"controller": "jobset", "controllerGroup": "jobset.x-k8s.io", "controllerKind": "JobSet", "JobSet": {"name":"job-set","namespace":"multikueue-nrj5n"}, "namespace": "multikueue-nrj5n", "name": "job-set", "reconcileID": "b28cdef5-4081-4672-934d-f206a91336b4", "job": "multikueue-nrj5n/job-set", "gvk": "jobset.x-k8s.io/v1alpha2, Kind=JobSet", "error": "workloads.kueue.x-k8s.io \"jobset-job-set-273af\" is forbidden: unable to create new content in namespace multikueue-nrj5n because it is being terminated"}
sigs.k8s.io/kueue/pkg/controller/jobframework.(*JobReconciler).ReconcileGenericJob …
```

Clean all jobsets on delete namespace.

---

.gitignore
hack/generate_krew.sh

/kind feature
We need to generate krew plugin configuration to update it on krew after release.
Fixes #
```release-note
NONE
```

[kueuectl] Generate krew plugin configuration.

---

hack/multiplatform-build.sh

/kind feature
To configure krew plugin we need to have tar.gz artifacts.
```
Krew plugins must be packaged as .zip or .tar.gz archives, and should be accessible to download from a user’s machine.
```
https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/
Fixes #
```release-note
CLI: kubectl-kueue tar.gz archives is part of the release artifacts.
```

[kueuectl] Build kubectl-kueue tar.gz archives to artifact directory.

---

site/layouts/partials/head.html

/kind cleanup
The async Google Analytics template from the Hugo project is no longer needed as has been deprecated - see https://github.com/gohugoio/hugo/issues/10899 -. This change is causing the error `no such template "_internal/google_analytics_async.html"` when running `make site-server` with the latest versions of Hugo.
Fixes #
```release-note
NONE
```

Remove deprecated Hugo template

---

apis/kueue/v1alpha1/multikueue_types.go
apis/kueue/v1beta1/clusterqueue_types.go
pkg/controller/admissionchecks/multikueue/workload.go
pkg/controller/jobframework/interface.go
pkg/controller/jobs/job/job_multikueue_adapter.go
pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
pkg/metrics/metrics.go
pkg/resources/resource.go
pkg/util/heap/heap.go
pkg/util/maps/maps.go
pkg/util/testingjobs/pod/wrappers.go
pkg/visibility/api/rest/cluster_queue.go
pkg/visibility/api/rest/local_queue.go
pkg/workload/workload.go
site/content/en/docs/reference/kueue.v1beta1.md
test/util/constants.go

/kind cleanup
Regarding https://go.dev/wiki/CodeReviewComments#comment-sentences suggestion, comments should begin with the name of the thing being described and end in a period.
Fixes #
```release-note
NONE
```

Fixed prefixes on comments.

---

pkg/cache/clusterqueue.go

/kind cleanup
Unused code
```release-note
NONE
```

Delete Unused IsBorrowing

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/clusterqueue.go
pkg/cache/clusterqueue_test.go
pkg/cache/snapshot.go

/kind cleanup
Followup to #2519. Other packages should only be interacting with cache directly, or otherwise with snapshot types.
```release-note
NONE
```

Unexport cache ClusterQueue and Cohort

---

CHANGELOG/CHANGELOG-0.7.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Update latest version to v0.7.1
Part of #2542
```release-note
NONE
```

Update latest version to v0.7.1

---

cmd/kueuectl/app/list/list_resourceflavor_printer.go
cmd/kueuectl/app/list/list_resourceflavor_printer_test.go
cmd/kueuectl/app/list/list_resourceflavor_test.go
site/static/examples/admin/single-clusterqueue-setup.yaml
test/integration/kueuectl/list_test.go

/kind feature
Added `Node Labels` column on resource flavor list on kueuectl.
Fixes #
```release-note
CLI: Added Node Labels column on resource flavor list.
```

[kueuectl] Added Node Labels column on resource flavor list.

---

Makefile-test.mk
test/integration/framework/framework.go

Adds a way to record apiserver logs during integration tests.
The logs recording can be enabled by setting  `INTEGRATION_API_LOG_LEVEL` environment variable to a numerical valued grater then 0. 
Fixes #
```release-note
None
```

[test/integration] Add API logging

---

keps/2076-kueuectl/README.md

Add `Node Labels` column on List ResourceFlavors.
Fixes #
```release-note
NONE
```

[kueuectl] Add Node Labels column on List ResourceFlavors.

---

pkg/controller/jobframework/defaults.go
pkg/controller/jobframework/errors.go
pkg/controller/jobframework/events.go
pkg/controller/jobframework/indexer.go
pkg/controller/jobframework/interface.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobframework/validation.go
pkg/podset/podset.go
pkg/util/routine/error_channel.go
pkg/util/routine/error_channel_test.go
test/integration/controller/jobs/raycluster/suite_test.go

/kind cleanup
Fix license.
Fixes #
```release-note
NONE
```

Fix license.

---

.github/dependabot.yml

/kind cleanup
The same as other depandabot workflows, we should add the prow labels, `ok-to-test` and `release-note-none` in the `"github-actions"` workflow so that we can easily manage the PRs created by depandabot.
Fixes #
```release-note
NONE
```

Add the prow labels to the dependabot

---

README.md
site/content/en/docs/installation/_index.md

As we described in the latest release note, Kueue supports the Kubernetes v1.25 or newer version due to the CEL validation limitations.
Fixes #
```release-note
NONE
```

Upgrade the minimum required kubernetes version in docs

---

pkg/cache/clusterqueue_test.go

/kind cleanup
We test DominantResourceShare without relying on internals of the snapshot.
Additionally, we increase test coverage by testing DominantResourceShare for the cache type, in addition to the snapshot type.
#2502
```release-note
NONE
```

Refactor DominantResourceShare tests; Increase Coverage

---

cmd/experimental/podtaintstolerations/controller/pod_jobs.go
cmd/kueuectl/app/list/list_localqueue.go
cmd/kueuectl/app/list/list_workload.go
cmd/kueuectl/app/resume/resume_clusterqueue.go
cmd/kueuectl/app/resume/resume_localqueue.go
cmd/kueuectl/app/stop/stop_clusterqueue.go
cmd/kueuectl/app/stop/stop_localqueue.go
pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
pkg/controller/admissionchecks/provisioning/controller.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/jobframework/reconciler.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/jobset/jobset_webhook.go
pkg/controller/jobs/mpijob/mpijob_webhook.go
pkg/controller/jobs/noop/noop_webhook.go
pkg/controller/jobs/pod/event_handlers.go
pkg/controller/jobs/raycluster/raycluster_webhook.go
pkg/controller/jobs/rayjob/rayjob_webhook.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler.go
pkg/visibility/api/rest/pending_workloads_cq.go
pkg/webhooks/clusterqueue_webhook.go
pkg/webhooks/resourceflavor_webhook.go
pkg/webhooks/workload_webhook.go

/kind cleanup
Remove unused parameters.
Fixes #
```release-note
NONE
```

Remove unused parameters.

---

pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go

/kind cleanup
Remove non-necessary conditions.
Fixes #
```release-note
NONE
```

Remove non-necessary conditions.

---

site/content/en/docs/installation/_index.md

fix typo, `beta` -> `Beta`
Fixes #
```release-note
NONE
```

docs: fix typo, beta -> Beta

---

pkg/scheduler/scheduler_test.go

/kind cleanup
#2502
```release-note
NONE
```

Stop manually setting ClusterQueueSnapshot.Usage in scheduler_test

---

site/content/en/docs/concepts/workload.md
site/content/en/docs/overview/_index.md

Fixes #
```release-note
NONE
```

[website] fix broken link

---

config/components/rbac/kustomization.yaml

/kind bug
Add raycluster roles to manifests.yaml.
Fixes #
```release-note
Added raycluster roles to manifests.yaml
```

Add raycluster roles to manifests.yaml

---

pkg/cache/clusterqueue.go
pkg/cache/resource.go

/kind cleanup
We were creating a lot of garbage by not calling make with a size, and creating intermediate slices.
```release-note
NONE
```

Create []FlavorResource more efficiently

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
charts/kueue/Chart.yaml
config/components/manager/kustomization.yaml
site/hugo.toml

Part of #2628
```release-note
NONE
```

Prepare release v0.8.0

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part of #2628
```release-note
NONE
```

Update latest kueue v0.8.0

---

site/content/en/docs/tasks/manage/setup_job_admission_policy.md

It would be helpful to understand in advance which feature gates are necessary for the `ValidatingAdmissonPolicy.`
Fixes #
```release-note
NONE
```

Add an enabling the feturegate note to the setup a job admission policy docs

---

.golangci.yaml
pkg/controller/jobframework/setup_test.go
pkg/webhooks/workload_webhook.go

/kind bug
To find slice declarations with non-zero initial length.
Fixes #
```release-note
NONE
```

Add makezero linter.

---

site/content/en/docs/reference/kubectl-kueue/installation.md

Adds installing kubectl-kueue plugin via Krew guide.
Fixes #
```release-note
Adds installing kubectl-kueue plugin via Krew guide.
```

[website] Adds installing kubectl-kueue plugin via Krew guide.

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
cmd/experimental/kjobctl/docs/installation.md

Update release version on installation guide.
Fixes #
Version is automatically updating on `make prepare-release-branch`. 
https://github.com/kubernetes-sigs/kueue/blob/cfbd456e46efcc782342ebc3b652dff8ba959374/Makefile#L279-L283
```release-note
NONE
```

[kjobctl] Update release version on installation guide.

---

cmd/experimental/kjobctl/go.mod
cmd/experimental/kjobctl/go.sum
cmd/experimental/kjobctl/pkg/cmd/create/create.go

/kind cleanup
Removes Kubernetes from kjobctl dependencies.
Relates to #2573 
```release-note
NONE
```

[kjobctl] Remove k8s dependency

---

Makefile
Makefile-test.mk
hack/push-chart.sh

/kind bug
Since the new staging registry provides a repo for charts, we don't need to store the chart in the same repo as the Kueue image anymore.
Relates to #2377, #2476
```release-note
Support for helm charts in the us-central1-docker.pkg.dev/k8s-staging-images/charts repository
```

Fix Helm chart repository name

---

.github/workflows/krew-release.yml
.krew.yaml
hack/generate_krew.sh
hack/multiplatform-build.sh

/kind feature
Adds [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) that automates the update of plugin manifests in [krew-index](https://github.com/kubernetes-sigs/krew-index) repository when a new version of `kubectl-kueue` plugin is released.
Fixes #
Follow up for https://github.com/kubernetes-sigs/krew-index/pull/3967#issuecomment-2241307022.
https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/
```release-note
NONE
```

[krew] Add krew release bot.

---

cmd/experimental/kjobctl/Makefile

/kind cleanup
Split `test` to `test-unit` and `test-integration` commands on `kjobctl`. 
Fixes #
```release-note
NONE
```

[kjobctl] Split test to test-unit and test-integration commands.

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
Makefile

/kind feature
Add `make update-security-insights` to automate the  SECURITY_INSIGHTS.yaml file update step of the release process.
Fixes #2650
```release-note
NONE
```

Add update-security-insights directive

---

test/integration/framework/framework.go

/kind cleanup
Remove duplicate of rayv1.AddToScheme on SetupClient.
Fixes #
```release-note
NONE
```

Remove duplicate of rayv1.AddToScheme on SetupClient.

---

site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md

I extended the Job troubleshooting guide by adding a short section about identifying ResourceFlavor of a Job
```release-note
NONE
```

Add ResourceFlavor section to Job troubleshooting guide

---

cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_interactive.md
cmd/experimental/kjobctl/pkg/cmd/list/list.go
cmd/experimental/kjobctl/pkg/cmd/list/list_interactive.go
cmd/experimental/kjobctl/pkg/cmd/list/list_interactive_printer.go
cmd/experimental/kjobctl/pkg/cmd/list/list_interactive_test.go
cmd/experimental/kjobctl/pkg/cmd/util/helpers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/pod_wrappers.go

/kind feature
Add `list interactive` command to kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add list interactive command

---

site/go.mod
site/go.sum

/kind cleanup
Bump github.com/google/docsy from v0.9.1 to v0.10.0 to fix warning:
```
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
```
Fixes #
```release-note
NONE
```

Bump github.com/google/docsy from v0.9.1 to v0.10.0.

---

test/e2e/multikueue/e2e_test.go

/kind bug
/kind flake
Update job's distributions across multikueue worker clusters.
Fixes #
```release-note
None
```

[multikueue][e2e] Update job's distributions across workers

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

I added a step to the new release flow so that we never forget to add the presubmits jogs.
Fixes #
```release-note
NONE
```

Add a step to create a presubmits jobs for the next patch release in the New Release flow

---

site/content/en/docs/reference/kubectl-kueue/installation.md

/kind cleanup
Adds tabs on kueuectl installation guide to separate installation commands between different platforms.
Fixes #
```release-note
NONE
```

[kueuectl] Add tabs on installation guide.

---

.github/dependabot.yml

/kind cleanup
Automatically dependency updates would be helpful.
Fixes #
```release-note
NONE
```

Add dependabot configuration for the site directory

---

.github/dependabot.yml

/kind cleanup
Add dependabot npm configuration for the site directory.
Fixes #
```release-note
NONE
```

Add dependabot npm configuration for the site directory.

---

hack/e2e-common.sh
hack/multiplatform-build.sh
hack/verify-shellcheck.sh

/kind bug
We should fail verify test on shellcheck error.
Fixes #
```release-note
NONE
```

Fail verify test on shellcheck error.

---

hack/update-helm.sh

/kind cleanup
Fail update-helm.sh on first error.
Fixes #
```release-note
NONE
```

Fail update-helm.sh on first error.

---

hack/verify-shellcheck.sh

/kind cleanup
Bump shellcheck version v0.9.0 -> v0.10.0.
Fixes #
```release-note
NONE
```

Bump shellcheck version v0.9.0 -> v0.10.0.

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/run/deployment.md
site/static/examples/deployment-kueue/kueue-deployment.yaml

Documents how to use Kueue for Deployments
Fixes #2677
https://deploy-preview-2698--kubernetes-sigs-kueue.netlify.app/docs/tasks/run/deployment/
```release-note
Documentation on how to use Kueue for Deployments is added
```

Document how to use Kueue for Deployments

---

Makefile
cmd/experimental/kjobctl/Makefile
cmd/experimental/kjobctl/hack/multiplatform-build.sh

/kind feature
Add kjobctl artifacts to Kueue artifacts.
Fixes #
```release-note
NONE
```

[kjobctl] Build kjobctl executables

---

cmd/experimental/kjobctl/hack/multiplatform-build.sh

/kind bug
Fix shell-lint errors on kjobctl.
Fixes #
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2779/pull-kueue-verify-main/1820733879254781952
```release-note
NONE
```

[kjobctl] Fix shell-lint errors

---

site/content/en/docs/concepts/_index.md

fix docs: typo on concepts page

---

hack/multikueue-e2e-test.sh

/kind bug
Fix junit reporting in multikueue e2e tests.
Relates to  #2763 
```release-note
None
```

[multikueue-e2e]Fix junit reporting

---

site/content/en/docs/tasks/manage/setup_multikueue.md
site/content/en/docs/tasks/run/jobsets.md
site/content/en/docs/tasks/run/kubeflow/mpijobs.md
site/content/en/docs/tasks/run/kubeflow/mxjobs.md
site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
site/content/en/docs/tasks/run/kubeflow/tfjobs.md
site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
site/content/en/docs/tasks/run/rayclusters.md
site/content/en/docs/tasks/run/rayjobs.md

Set `primary` instead `note` color on `Note` block.
Fixes #
After update docsy version v0.9.0 -> v0.10.0 in some places `Note` block  isn't working as expected.
```release-note
NONE
```

Set primary instead note color on Note block.

---

site/content/en/docs/tasks/run/rayclusters.md
site/content/en/docs/tasks/run/rayjobs.md
site/static/examples/jobs/ray-cluster-sample.yaml
site/static/examples/jobs/ray-job-code-sample.yaml
site/static/examples/jobs/ray-job-sample.yaml

/kind cleanup
Ray job and ray cluster examples very old and not working with ray-operator v1.1.0 and newer.
Fixes #
```release-note
NONE
```

Update ray examples.

---

site/content/en/docs/installation/_index.md

Add command to wait for Kueue to be fully available on installation guide.
Fixes #2791
```release-note
NONE
```

Add command to wait for Kueue to be fully available on installation guide.

---

cmd/kueuectl/app/create/create_clusterqueue.go
hack/internal/tools/kueuectl-docs/templates/main.html
keps/2076-kueuectl/README.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_clusterqueue.md

/kind bug
Fix examples for create clusterqueue command on kueuectl.
Fixes #2790
```release-note
CLI: Fix examples for create clusterqueue command.
```

[kueuectl] Fix examples for create clusterqueue command.

---

cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go

/kind feature
Add `describe interactive` command to kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add describe interactive command

---

cmd/experimental/kjobctl/Makefile
cmd/experimental/kjobctl/hack/multiplatform-build.sh

/kind feature
Make kubectl-kjob binaries statically linked.
Part of #2801
```release-note
NONE
```

[kjobctl] Make kubectl-kjob binaries statically linked.

---

cmd/experimental/kjobctl/LICENSE

/kind feature
We need to have separate LICENSE file for kjobctl because we will move kjobctl to another repository. 
Fixes #
```release-note
NONE
```

[kjobctl] Add LICENSE file.

---

cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_raycluster.md
cmd/experimental/kjobctl/pkg/cmd/list/list.go
cmd/experimental/kjobctl/pkg/cmd/list/list_ray_cluster.go
cmd/experimental/kjobctl/pkg/cmd/list/list_ray_cluster_printer.go
cmd/experimental/kjobctl/pkg/cmd/list/list_ray_cluster_test.go
cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_spec_wrapper.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go

/kind feature
Add list raycluster command in kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add list raycluster command.

---

charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml

/kind feature
Add kueue.x-k8s.io_cohorts.yaml helm template.
Fixes #
```release-note
Added Cohorts CRD to helm.
```

Add kueue.x-k8s.io_cohorts.yaml helm template.

---

cmd/experimental/kjobctl/test/util/util.go

/kind cleanup
Delete RayJobs and RayClusters on delete namespace in integration tests on kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Delete RayJobs and RayClusters on delete namespace.

---

cmd/experimental/kjobctl/docs/commands/kjobctl_delete/_index.md
cmd/experimental/kjobctl/docs/commands/kjobctl_delete/kjobctl_delete_interactive.md
cmd/experimental/kjobctl/docs/commands/kjobctl_delete/kjobctl_delete_job.md
cmd/experimental/kjobctl/docs/commands/kjobctl_delete/kjobctl_delete_raycluster.md
cmd/experimental/kjobctl/docs/commands/kjobctl_delete/kjobctl_delete_rayjob.md
cmd/experimental/kjobctl/pkg/cmd/cmd.go
cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
cmd/experimental/kjobctl/pkg/cmd/completion/completion_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_interactive.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_interactive_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_job.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_job_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_ray_cluster.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_ray_cluster_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_ray_job.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_ray_job_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/helpers.go

/kind feature
Add delete command on kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add delete command.

---

site/content/en/docs/concepts/cluster_queue.md

Fix hierarchy between flavors and resources in documentation. In the past, resources where listed before flavors, but after we changed that, the documentation remained with the opposite wording.
Also give a better example of when to use multiple resource groups. Typically, GPUs are tied to cpus and memory, so the example should have them in the same resource group.
Fixes #
```release-note
NONE
```

Fix hierarchy between flavors and resources in documentation

---

pkg/cache/cache.go
pkg/cache/clusterqueue.go

/kind cleanup
This function never returns error
```release-note
NONE
```

Update signature of resetFlavorsAndResources

---

cmd/kueuectl/app/list/list_pods.go
pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/interface.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
pkg/controller/jobs/kubeflow/kubeflowjob/interface.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go

As we discussed [here](https://github.com/kubernetes-sigs/kueue/pull/2280#discussion_r1720034583) we should use the integration manager on `kueuectl list pods` command to get PodLabelSelector.
Fixes #2868
```release-note
NONE
```

[kueuectl] Use integration manager to get PodLabelSelector.

---

cmd/kueuectl/app/list/list_clusterqueue.go
hack/internal/tools/go.mod
hack/internal/tools/go.sum
pkg/util/testing/client.go

/kind cleanup
I added a commit for fixing lint errors to https://github.com/kubernetes-sigs/kueue/pull/2852.
```go
cmd/kueuectl/app/list/list_clusterqueue.go:206:5: S1009: should omit nil check; len() for []bool is defined as zero (gosimple)
if o.Active == nil || len(o.Active) == 0 {
^
pkg/util/testing/client.go:103:39: printf: non-constant format string in call to (*sigs.k8s.io/kueue/pkg/util/testing.EventRecorder).Eventf (govet)
tr.Eventf(object, eventType, reason, message)
```
Fixes #
```release-note
NONE
```

Bump github.com/golangci/golangci-lint from 1.59.1 to 1.60.1 in /hack/internal/tools

---

pkg/controller/jobframework/integrationmanager.go

/kind cleanup
Remove unnecessary PodLabelSelector integration callback.
Fixes #
It was added by mistake here https://github.com/kubernetes-sigs/kueue/pull/2875.
```release-note
NONE
```

Remove unnecessary PodLabelSelector integration callback.

---

pkg/cache/clusterqueue_snapshot.go
pkg/cache/cohort_snapshot.go
pkg/cache/resource.go
pkg/controller/jobs/pod/event_handlers.go
pkg/hierarchy/manager.go
pkg/hierarchy/manager_test.go
pkg/hierarchy/wired_clusterqueue.go
pkg/hierarchy/wired_cohort.go
pkg/queue/cohort.go
pkg/scheduler/flavorassigner/podset_reducer_test.go
pkg/scheduler/preemption/preemption_oracle.go
pkg/util/kubeversion/kubeversion.go
pkg/util/kubeversion/kubeversion_test.go
pkg/webhooks/common.go

/kind cleanup
```release-note
NONE
```

Add Copywrites

---

cmd/kueuectl/app/list/helpers.go
cmd/kueuectl/app/list/list_pods.go
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_pods.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md

Add explanation of --for=pod/foo option on kueuectl.
Fixes #
This is a follow up for https://github.com/kubernetes-sigs/kueue/pull/2875#discussion_r1727092768.
```release-note
NONE
```

[kueuectl] Add explanation of --for=pod/foo option.

---

cloudbuild.yaml
cmd/experimental/kjobctl/README.md
cmd/experimental/kjobctl/go.mod
cmd/experimental/kjobctl/hack/tools/go.mod
go.mod
hack/internal/tools/go.mod

/kind cleanup
I upgraded the Go version to v1.22.6 since the minimum required Go version is upgraded to v1.22.6 in the hugo: https://github.com/gohugoio/hugo/blob/c9777473d1369f812d727a6c07dc57ad7be7bf62/go.mod#L172
If we do not upgrade the version, developers face some dependency issues when they use the IDEs depend on the "'go list -modfile" like JetBrains.
Fixes #
```release-note
NONE
```

Upgrade Go version to v1.22.6

---

hack/cherry_pick_pull.sh

/kind bug
Add release notes to the body of the pull request on create cherry-pick.
Fixes #
```release-note
NONE
```

Add release notes to the body of the pull request on create cherry-pick.

---

.github/dependabot.yml

/kind cleanup
The primary motivation is to resolve the considerations of merging dependabot PRs.
The current dependabot often enforces us to consider the order of merging dependabot PRs like 
- https://github.com/kubernetes-sigs/kueue/pull/2849
- https://github.com/kubernetes-sigs/kueue/pull/2846
#2849 failed due to merge #2846 first.
Since this PR, we group codepending directories during automated dependabot go module update:
- Kueue
- "/"
- "/hack/internal/tools"
- "/site"
- KJobCtl
- "/cmd/experimental/kjobctl"
- "/cmd/experimental/kjobctl/hack/tools"
Fixes #
```release-note
NONE
```

Grouping codepending directory for the gomod dependabot configuration

---

pkg/webhooks/workload_webhook.go

/kind cleanup
I fixed typos for the `Posets` with `PodSets`.
Fixes #
```release-note
NONE
```

Fix typos for the Poset with PodSet
