site/content/en/docs/tasks/troubleshooting/troubleshooting_delete_clusterqueue.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md

Add a guide for deleting cluster queues.
Fixes #2835
```release-note
NONE
```

Add a guide for deleting cluster queues.

---

site/static/examples/admin/single-clusterqueue-setup.yaml

/kind cleanup
Remove test nodeLabels from example.
Fixes #
```release-note
NONE
```

Remove test nodeLabels from example.

---

site/content/en/docs/concepts/workload_priority_class.md

fix docs: workload_priority_class.md

---

cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go

/kind feature
Add describe rayjob  command on kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add describe rayjob command.

---

Makefile-test.mk
README.md

/kind cleanup
1.27 is no longer in support so we shouldn't test with it or report the testgrid dashboard.
Fixes #
```release-note
NONE
```

drop mentions of 1.27 in kueue and makefile testing

---

cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_slurm.md
cmd/experimental/kjobctl/pkg/builder/builder.go
cmd/experimental/kjobctl/pkg/builder/builder_test.go
cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
cmd/experimental/kjobctl/pkg/cmd/completion/completion_test.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
cmd/experimental/kjobctl/pkg/cmd/delete/delete_job.go
cmd/experimental/kjobctl/pkg/cmd/list/list.go
cmd/experimental/kjobctl/pkg/cmd/list/list_slurm.go
cmd/experimental/kjobctl/pkg/cmd/list/list_slurm_test.go
cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
cmd/experimental/kjobctl/pkg/constants/constants.go
cmd/experimental/kjobctl/pkg/testing/wrappers/configmap_wrappers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/pod_wrappers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_wrappers.go
cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go

/kind feature
Add list slurm command on kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add list slurm command.

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
To address this decision: https://github.com/kubernetes/org/pull/5128
Fixes #
```release-note
NONE
```

Update the release issue template with new admin, Michal

---

cmd/experimental/kjobctl/pkg/cmd/create/create.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/container_wrappers.go

/kind bug
Fix create interactive command on kjobctl. 
Fixes #
It is not working well after creation, because we don't have object name that generated on server side. We need to use created object instead generated.
```release-note
NONE
```

[kjobctl] Fix create interactive command.

---

cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_spec_wrapper.go
cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_wrappers.go
cmd/experimental/kjobctl/pkg/testing/wrappers/worker_group_spec_wrapper.go

/kind feature
Add describe raycluster command on kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add describe raycluster command.

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

Part of https://github.com/kubernetes-sigs/kueue/issues/2985
```release-note
NONE
```

Prepare release v0.8.1

---

pkg/hierarchy/manager.go

/kind cleanup
See https://github.com/kubernetes-sigs/kueue/pull/3000#discussion_r1746026531
Rename receiver from `c` to `m` for consistency with Manager type name. Update function name from `unwireClusterQueue` to `detachClusterQueueFromParent` for consistency with `detachCohortFromParent`.
```release-note
NONE
```

Cleanup hierarchy.Manager

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
cmd/experimental/kjobctl/docs/installation.md
site/hugo.toml

Update latest version to v0.8.1
Part of https://github.com/kubernetes-sigs/kueue/issues/2985
```release-note
NONE
```

Update latest version to v0.8.1

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
To maintain the release steps and make them as clear as possible. 
Fixes #
The update is based on experiences with https://github.com/kubernetes-sigs/kueue/issues/2985
```release-note
NONE
```

Update the new release steps

---

site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md

Use current version instead of $VERSION on [Install the visibility API](https://github.com/kubernetes-sigs/kueue/blob/687ee1e169cfa4f7cbdf4317353927fcb2320acf/site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md?plain=1#L34).
Fixes #
```release-note
NONE
```

Use current version instead of $VERSION.

---

test/e2e/config/multikueue/manager/kustomization.yaml
test/e2e/config/multikueue/worker/kustomization.yaml

/kind cleanup
Fix the "Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.".
Fixes #
Follow-up for https://github.com/kubernetes-sigs/kueue/pull/2880#pullrequestreview-2286509704.
```release-note
NONE
```

Fix Warning: 'commonLabels' is deprecated.

---

test/e2e/multikueue/suite_test.go

/kind cleanup
Clean roles and secrets after e2e multikueue test.
Fixes #
It's very hard to debug multikueue e2e tests. Sometimes, we need to restart the tests without rebuilding the entire cluster. However, this leads to conflicts because roles and secrets already exist.
```release-note
NONE
```

Clean roles and secrets after e2e multikueue test.

---

Makefile
cmd/experimental/kjobctl/docs/installation.md

As discussed [here](https://github.com/kubernetes-sigs/kueue/issues/2778) we will move `kjobctl` to another repository after MVP phase. Therefore, we can't use the Kueue release binaries and the Kueue release version. To avoid confusion, we should remove the 'Installing from Release Binaries' guide for now.
Fixes #
```release-note
NONE
```

[kjobctl] Fix installation guide.

---

site/content/en/docs/tasks/run/jobsets.md
site/content/en/docs/tasks/run/kubeflow/mpijobs.md
site/content/en/docs/tasks/run/kubeflow/mxjobs.md
site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
site/content/en/docs/tasks/run/kubeflow/tfjobs.md
site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
site/content/en/docs/tasks/run/rayclusters.md
site/content/en/docs/tasks/run/rayjobs.md

Updating the notes from this PR: https://github.com/kubernetes-sigs/kueue/pull/2685 
Notes have been previously added until https://github.com/kubernetes-sigs/kueue/issues/2414 is fixed. 
It is now fixed by this PR: https://github.com/kubernetes-sigs/kueue/pull/2574 and is being [cherry-picked to `release-0.8`](https://github.com/kubernetes-sigs/kueue/pull/2991)
Now that v0.8.1 has been released, we've updated the notes accordingly.
Fixes #
```release-note
NONE
```

Update the notes about the need to restart the kueue pod

---

pkg/cache/clusterqueue_snapshot.go
pkg/cache/resource_test.go
test/integration/scheduler/scheduler_test.go

/kind cleanup
/kind feature
Add test suite to give more confidence in the new resource accounting logic (#2881). Part of #79
```release-note
NONE
```

Create resource_test Suite

---

pkg/visibility/api/install.go
pkg/visibility/api/v1alpha1/cluster_queue.go
pkg/visibility/api/v1alpha1/local_queue.go
pkg/visibility/api/v1alpha1/pending_workloads_cq.go
pkg/visibility/api/v1alpha1/pending_workloads_cq_test.go
pkg/visibility/api/v1alpha1/pending_workloads_lq.go
pkg/visibility/api/v1alpha1/pending_workloads_lq_test.go
pkg/visibility/api/v1alpha1/test_utils.go
pkg/visibility/api/v1alpha1/utils.go

/kind cleanup
Rename the rest package to v1alpha1 on visibility API server.
Prepare for #3008.
```release-note
NONE
```

Rename rest package to v1alpha1.

---

test/integration/framework/framework.go

/kind cleanup
[integration][framework]Put bootstrapping in it's own By to improve the ginkgo-top reporting.
Relates to #2993 
```release-note
None
```

[integration][framework]Put bootstrapping in it's own By.

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/dev/develop-acc.md

Add `Develop an AdmissionCheck Controller` task page.
Fixes #2932 
```release-note
None
```

[doc] Develop ACC task.

---

cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
cmd/experimental/kjobctl/pkg/cmd/describe/helpers.go

/kind feature
Add `describe` slurm command to kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Add describe slurm

---

cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
cmd/kueuectl/app/completion/completion_test.go
cmd/kueuectl/app/create/create_resourceflavor_test.go
cmd/kueuectl/app/list/list_clusterqueue_test.go
cmd/kueuectl/app/list/list_localqueue_test.go
cmd/kueuectl/app/list/list_pods_test.go
cmd/kueuectl/app/list/list_resourceflavor_test.go
cmd/kueuectl/app/list/list_test.go
cmd/kueuectl/app/list/list_workload_test.go
cmd/kueuectl/app/testing/fake.go
cmd/kueuectl/app/util/client_getter.go
cmd/kueuectl/app/version/version_test.go

/kind cleanup
Use WithKueueClientset and WithK8sClientset methods on TestClientGetter.
Fixes #
```release-note
NONE
```

Use WithKueueClientset and WithK8sClientset methods on TestClientGetter.

---

site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md

Fix current version of visibility API.
Fixes #
```release-note
NONE
```

Fix current version of visibility API.

---

config/default/kustomization.yaml
config/prometheus/kustomization.yaml
config/visibility/kustomization.yaml

/kind cleanup
Fix commonLabels deprecated warning.
Fixes #
`# Warning: 'commonLabels' is deprecated. Please use 'labels' instead. Run 'kustomize edit fix' to update your Kustomization automatically.`
```release-note
NONE
```

Fix commonLabels deprecated warning.

---

Makefile
charts/kueue/README.md

/kind cleanup
Clean manager image tag in helm after create artifacts.
Fixes #
Each time after run `make artifacts` we have uncommitted values.yaml file.
```release-note
NONE
```

Clean manager image tag in helm after create artifacts.

---

cmd/kueuectl/app/passthrough/passthrough.go
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/_index.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_clusterqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_localqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_resourceflavor.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_delete/kueuectl_delete_workload.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_localqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/_index.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_clusterqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/_index.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_clusterqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_localqueue.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md
site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md

/kind cleanup
Add short description for first level pass-through commands.
Fixes #
```release-note
NONE
```

[kueuectl] Add short description for first level pass-through commands.

---

site/assets/scss/_styles_project.scss

/kind cleanup
Change background color for deprecated feature.
Part of #2256
```release-note
NONE
```

Change background color for deprecated feature.

---

keps/2076-kueuectl/README.md

Update "KEP-2076: Kueuectl":
- Add separate delete workload command, 
- Remove delete workload command from pass-through.
Part of #2975
```release-note
NONE
```

Update KEP-2076: Kueuectl.

---

pkg/queue/manager_test.go

/kind cleanup
Fix `TestUpdateClusterQueue` to allow to create inadmissible workloads.
Fixes #3066
```release-note
NONE
```

Fix TestUpdateClusterQueue.

---

test/integration/controller/jobs/raycluster/raycluster_controller_test.go
test/integration/controller/jobs/rayjob/rayjob_controller_test.go

/kind bug
[test][integration][ray] Fix cleanup for flavors and priority-class
Relates to https://github.com/kubernetes-sigs/kueue/issues/2993
The standard go defer is used since 
- https://github.com/onsi/ginkgo/issues/1284
```release-note
none
```

[test][integration][ray] Fix cleanup for flavors and priority-class

---

cmd/experimental/kjobctl/pkg/builder/builder.go
cmd/experimental/kjobctl/pkg/builder/builder_test.go
cmd/experimental/kjobctl/pkg/builder/interactive_builder.go
cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
cmd/experimental/kjobctl/pkg/builder/job_builder.go
cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go
cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go
cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
cmd/experimental/kjobctl/pkg/cmd/create/create.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/configmap_wrappers.go

/kind feature
Add ownerReference for additional Slurm objects in kjobctl. This allow to remove additional objects when removing Job.
Fixes #
Follow-up for https://github.com/kubernetes-sigs/kueue/pull/3072#discussion_r1773067656.
```release-note
NONE
```

[kjobctl] Add ownerReference for additional Slurm objects.

---

pkg/controller/jobframework/base_webhook.go
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go

/kind cleanup
To be inline with the name BaseWebhook.
DefaultWebhook is just confusing because it's a Defaulter and a Validator.
Fixes #
```release-note
NONE
```

Rename DefaultWebhookFactory to BaseWebhookFactory

---

pkg/workload/workload.go

/kind cleanup
Make better use of containers generics in the workload package.
Fixes #
```release-note
None
```

[workload] Make better use of container generics

---

OWNERS

/kind cleanup
I'm proposing to promote @mbobrovskyi to the top-level reviewer.
His contributions are the following:
- Review: https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+reviewed-by%3Ambobrovskyi+-author%3Ambobrovskyi+created (10)
- Opend PRs: https://github.com/kubernetes-sigs/kueue/pulls/mbobrovskyi (231)
Most actively involving PRs as a reviewer:
- https://github.com/kubernetes-sigs/kueue/pull/2280
- https://github.com/kubernetes-sigs/kueue/pull/2570
- https://github.com/kubernetes-sigs/kueue/pull/2880
- https://github.com/kubernetes-sigs/kueue/pull/2988
- https://github.com/kubernetes-sigs/kueue/pull/3076
- https://github.com/kubernetes-sigs/kueue/pull/2364
He became a community member 5 moths ago: https://github.com/kubernetes/org/issues/4915
Fixes #
```release-note
NONE …
```

Add mbobrovskyi to the top level reviewer

---

keps/2937-resource-transformer/README.md
keps/2937-resource-transformer/kep.yaml

/kind feature
KEP to propose a design to address issue #2937 
Fixes #
```release-note
NONE
```

KEP 2937: Configurable Resource Transformers

---

site/content/en/docs/tasks/dev/integrate_a_custom_job.md

Documents how to develop a webhook integration after all the caveats learned in #3132.
Ref #2878
```release-note
NONE
```

Docs: how to develop a webhook for a job integration

---

site/content/en/docs/tasks/_index.md
site/content/en/docs/tasks/run/jobsets.md
site/content/en/docs/tasks/run/multikueue/_index.md
site/content/en/docs/tasks/run/multikueue/jobsets.md

Reorganising documentation for running tasks in MultiKueue.
Part of #3134 
```release-note
NONE
```

Move jobsets multikueue run details to separte multikueue subfolder

---

site/content/en/docs/concepts/admission_check.md

/kind cleanup
Fixes an error from Hugo when building the website locally:
```
hugo v0.135.0+extended darwin/arm64 BuildDate=unknown
ERROR invalid front matter: date: 2024-13-06: see /Users/dgrove/code/platform/kueue/site/content/en/docs/concepts/admission_check.md
Built in 790 ms
```
Fixes #
```release-note
NONE
```

Fix date format in front matter block of docs/concepts/admission_check.md

---

charts/kueue/templates/webhook/webhook.yaml
config/components/webhook/kustomization.yaml
hack/update-helm.sh

/kind bug
[config][webhooks] Add namespace selectors for deployment webhooks.
[charts][webhooks] Add namespace selectors for deployment webhooks.
Fixes #3150 
```release-note
NONE
```

[webhooks] Add namespace selectors for deployment webhooks.

---

cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
cmd/experimental/kjobctl/pkg/builder/builder.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl
cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
cmd/experimental/kjobctl/pkg/cmd/create/create.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go

/kind feature
Use init container to initialise env on kjobctl Slurm mode.
Prepare for #3072
```release-note
NONE
```

[kjobctl] Use init container to initialise env on Slurm mode.

---

cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_interactive.md
cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_job.md
cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_raycluster.md
cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_rayjob.md
cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
cmd/experimental/kjobctl/pkg/builder/builder.go
cmd/experimental/kjobctl/pkg/builder/interactive_builder_test.go
cmd/experimental/kjobctl/pkg/builder/job_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder_test.go
cmd/experimental/kjobctl/pkg/builder/ray_job_builder_test.go
cmd/experimental/kjobctl/pkg/cmd/create/create.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
cmd/experimental/kjobctl/test/integration/kjobctl/create_test.go

/kind feature
Adds validation to check that localqueue exists  and the flag to skip the validation.
Fixes #
```release-note
NONE
```

[kjobctl] Add local queue validation

---

keps/993-two-phase-admission/README.md
keps/993-two-phase-admission/kep.yaml

Update "KEP-993: Two Stage Admission Process".
Fixes #2437
```release-note
NONE
```

Update "KEP-993: Two Stage Admission Process".

---

site/content/en/docs/reference/labels-and-annotations.md

Add Labels and Annotations to the documentation page.
Fixes #3198
```release-note
NONE
```

Add Labels and Annotations to the documentation page.

---

pkg/controller/jobframework/integrationmanager.go
test/integration/controller/jobframework/setup/setup_controllers_test.go
test/integration/controller/jobframework/setup/suite_test.go

/kind cleanup
Add integration tests for detecting CRD installed after Kueue started.
Fixes #3015
```release-note
NONE
```

Add integration tests for detecting CRD installed after Kueue started.

---

keps/349-all-or-nothing/README.md

Updates KEP-349 to reflect actual state of the `WaitForPodsReady` API
```release-note
NONE
```

Update KEP-349 to reflect actual state of the `WaitForPodsReady` API

---

cmd/experimental/kjobctl/docs/run_slurm.md

Adds documentation for the Slurm mode of Kjobctl.
Fixes #2954 
```release-note
NONE
```

[kjobctl] Add documentation for Slurm mode

---

charts/kueue/values.yaml
config/components/manager/controller_manager_config.yaml

/kind cleanup
Add deployment integration framework on manifests.
Part of #2717
```release-note
NONE
```

Add deployment integration framework on manifests.

---

cmd/experimental/kjobctl/docs/commands/kjobctl_create/kjobctl_create_slurm.md
cmd/experimental/kjobctl/pkg/builder/slurm_builder.go
cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
cmd/experimental/kjobctl/pkg/cmd/create/create.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go

Use busybox init image in kjobctl slurm mode.
/kind cleanup
Fixes #
```release-note
NONE
```

[kjobctl] Use busybox init image.

---

site/content/en/docs/reference/labels-and-annotations.md

Add `kueue.x-k8s.io/pod-group-fast-admission` annotation on docs.
Part of #2717
```release-note
NONE
```

Add `kueue.x-k8s.io/pod-group-fast-admission` annotation on docs.

---

keps/2724-topology-aware-schedling/README.md

/kind cleanup
To follow up on the discussion in #3237 
Part of #2724 
```release-note
NONE
```

Update TAS KEP after API discussions

---

site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
site/content/en/docs/tasks/run/multikueue/_index.md
site/content/en/docs/tasks/run/multikueue/jobsets.md
site/content/en/docs/tasks/run/multikueue/kubeflow.md

Provide a  user guide on how to use managedBy with the Kubeflow training-operator jobs.
Fixes #3121 
```release-note
NONE
```

Add JobManagedBy feature docs for Kubeflow

---

charts/kueue/values.yaml
config/components/manager/controller_manager_config.yaml

/kind cleanup
The same as other Config parameters, I added an example transformations parameters.
Part-of #2937
```release-note
NONE
```

Add example transformation parameters to the controllerConfig

---

charts/kueue/templates/manager/manager-pdb.yaml
charts/kueue/templates/manager/manager.yaml
charts/kueue/values.yaml

/kind feature
Adds option to specify PDB and topological spread constraint in helm chart
Fixes #
```release-note
Helm: Support the topologySpreadConstraints and PodDisruptionBudget
```

Add topology spread constraints to manager deployment

---

site/content/en/docs/concepts/cluster_queue.md
site/content/en/docs/concepts/preemption.md
site/content/en/docs/tasks/dev/integrate_a_custom_job.md
site/content/en/docs/tasks/run/multikueue/_index.md

The PR corrects grammar mistakes on the website.
```release-note
NONE
```

[doc] fix typos on website

---

pkg/controller/jobframework/tas_validation.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/job/job_webhook_test.go
pkg/controller/jobs/jobset/jobset_webhook.go
pkg/controller/jobs/jobset/jobset_webhook_test.go

/kind feature
Part of #2724 
Only covering Job and JobSet in the PR, but I would like to follow this up extending the support for all Job types hopefully for alpha. If the pattern is established it should be rather fast.
```release-note
NONE
```

TAS: validate the preferred and required annotations for Job and JobSet

---

test/integration/controller/core/admissioncheck_controller_test.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/core/resourceflavor_controller_test.go
test/integration/controller/core/workload_controller_test.go

/kind cleanup
Propagate gomega.Gomega on integration/controller/core tests.
Part of #3300
```release-note
NONE
```

Propagate gomega.Gomega on integration/controller/core tests.

---

test/integration/controller/admissionchecks/provisioning/provisioning_test.go
test/integration/framework/framework.go
test/integration/kueuectl/passthrough_test.go

/kind cleanup
Propagate gomega.Gomega on integration tests.
Part of #3300
```release-note
NONE
```

Propagate gomega.Gomega on integration tests.

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go
vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/openapi_generated.go
vendor/sigs.k8s.io/jobset/pkg/constants/constants.go

/kind cleanup
Bump sigs.k8s.io/jobset from 0.6.0 to 0.7.0.
Fixes #
Fix for https://github.com/kubernetes-sigs/kueue/pull/3336.
```release-note
NONE
```

Bump sigs.k8s.io/jobset from 0.6.0 to 0.7.0.

---

pkg/cache/cache_test.go
pkg/cache/clusterqueue_test.go
pkg/cache/resource_test.go
pkg/cache/snapshot.go
pkg/cache/snapshot_test.go
pkg/controller/core/cohort_controller_test.go
pkg/debugger/debugger.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind cleanup
This is a follow up to https://github.com/kubernetes-sigs/kueue/pull/3292#discussion_r1814679057 
Part of #2724 
it does not have any user-facing impact outside of TAS which is a feature which has not yet been released.
```release-note
NONE
```

TAS: surface errors when building snapshot

---

test/integration/controller/admissionchecks/provisioning/provisioning_test.go
test/integration/controller/core/clusterqueue_controller_test.go
test/integration/controller/jobs/job/job_controller_test.go
test/integration/controller/jobs/jobset/jobset_controller_test.go
test/integration/controller/jobs/raycluster/raycluster_controller_test.go
test/integration/controller/jobs/rayjob/rayjob_controller_test.go
test/integration/multikueue/multikueue_test.go
test/integration/scheduler/podsready/scheduler_test.go
test/util/util.go

/kind cleanup
Use HaveConditionStatusTrue instead of IsStatusConditionTrue.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3325.
```release-note
NONE
```

Use HaveConditionStatusTrue instead of IsStatusConditionTrue.

---

pkg/controller/jobs/job/job_controller_test.go

/kind cleanup
Extend job TestPodSet with TAS.
Prepare for #3372
```release-note
NONE
```

TAS: Extend job TestPodSet.

---

pkg/controller/jobs/rayjob/rayjob_controller.go
pkg/controller/jobs/rayjob/rayjob_controller_test.go
pkg/controller/jobs/rayjob/rayjob_webhook.go
pkg/controller/jobs/rayjob/rayjob_webhook_test.go

/kind feature
Support TAS for RayJob.
Part of #3372
```release-note
NONE
```

TAS: Support RayJob.

---

pkg/scheduler/flavorassigner/flavorassigner.go
pkg/scheduler/scheduler_test.go

/kind feature
Part of #2724 
This is built on top of https://github.com/kubernetes-sigs/kueue/pull/3361.
WIP to merge first the scheduler-level tests.
```release-note
NONE
```

TAS: Skip RFs which don't match PodSet TAS requirements

---

test/util/util.go

/kind bug
/kind flake
Skip further checks after NotFound error on `ExpectPodsFinalizedOrGone()` and `ExpectWorkloadsFinalizedOrGone()` functions to avoid verifying finalizers on the old Workload/Pod object.
Fixes #3368
```release-note
NONE
```

Skip further checks after NotFound error on ExpectPodsFinalizedOrGone() and ExpectWorkloadsFinalizedOrGone() functions.

---

test/integration/controller/admissionchecks/provisioning/provisioning_test.go

/kind cleanup
To cleanup the code
This is follow up requested before cherry-picking the actual fix to 0.8.2: https://github.com/kubernetes-sigs/kueue/issues/3371#issuecomment-2449335083
```release-note
NONE
```

Cleanup debug log in provisioning integration tests

---

test/e2e/singlecluster/tas_test.go

/kind cleanup
Add sanity e2e test for JobSet with TAS.
Fixes #3388
```release-note
NONE
```

TAS: Add sanity e2e test for JobSet.

---

pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/raycluster/raycluster_controller_test.go
pkg/controller/jobs/rayjob/rayjob_controller.go
pkg/controller/jobs/rayjob/rayjob_controller_test.go
pkg/util/testingjobs/raycluster/wrappers.go

/kind bug
cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/3384
Fixes #
```release-note
Support NumOfHosts when calculating PodSet assignments
```

[release-0.8][KubeRay] Support NumOfHosts when calculating PodSet assignments (#3386)

---

pkg/controller/jobframework/base_webhook.go

/kind cleanup
Remove WithName("mxjob-webhook") on BaseWebhook.
Fixes #
```release-note
NONE
```

Remove WithName("mxjob-webhook") on BaseWebhook.

---

test/integration/controller/jobs/jobset/jobset_controller_test.go
test/integration/controller/jobs/jobset/suite_test.go

/kind cleanup
Add TAS integration tests for JobSet.
Part of #3372
```release-note
NONE
```

TAS: Add integration tests for JobSet.

---

cmd/experimental/kjobctl/pkg/cmd/create/create.go

/kind bug
Add short flag -J for --job-name on kjobctl slurm mode.
Fixes #
```release-note
NONE
```

[kjobctl] Add short flag -J for --job-name on slurm mode.

---

pkg/scheduler/flavorassigner/flavorassigner_test.go

/kind cleanup
Avoid overriding CohortResources fields manually, set capacity and usage via ClusterQueues.
Fixes #2749
```release-note
NONE
```

Replace direct modification of cohort resources in flavorassigner_test

---

site/content/en/docs/concepts/workload.md
site/content/en/docs/reference/labels-and-annotations.md

Add documentation for Maximum execution time.
Fixes #3125 
```release-note
Added documentation for Maximum execution time.
```

[doc] Maximum execution time

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

Part-of #3371
```release-note
NONE
```

Prepare release v0.8.2

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part-of #3371
```release-note
NONE
```

Update latest version to v0.8.2

---

site/content/en/docs/adopters/index.md

Adds IBM Research to Adoptors page. 
Fixes #
```release-note
NONE
```

Add IBM Research to Kueue adoptors page

---

pkg/podset/podset.go

/cleanup
Fixes a typo in a function doc comment.
Fixes #
```release-note
NONE
```

fix typo in FromPodSet comment

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

Part-of https://github.com/kubernetes-sigs/kueue/issues/3441
```release-note
NONE
```

Prepare v0.8.3

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
We need to specify the repository name for the `gh` command.
Fixes #
```release-note
NONE
```

Updat artifact publishing step in the Release steps

---

site/content/en/docs/reference/labels-and-annotations.md

`kueue.x-k8s.io/managed` label is used for the ProvisioningRequest as well: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/admissionchecks/provisioning/controller.go#L274
Fixes #
```release-note
NONE
```

Doc: Mention about the ProvisioningRequest on the kueue.x-k8s.io/managed label

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part-of https://github.com/kubernetes-sigs/kueue/issues/3441
```release-note
NONE
```

Update latest version to v0.8.3

---

cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go
cmd/experimental/kjobctl/pkg/cmd/create/create_test.go

/kind cleanup
Use t.Cleanup to remove test script file in kjobctl.
Fixes #3382
```release-note
NONE
```

[kjobctl] Use t.Cleanup to remove test script file.

---

site/content/en/docs/overview/_index.md

Update Job-integrated features table.
Fixes #
```release-note
NONE
```

Update Job-integrated features table.

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
charts/kueue/Chart.yaml
config/components/manager/kustomization.yaml
site/hugo.toml

Part of #3302 
```release-note
NONE
```

Prepare release v0.9.0

---

OWNERS

/kind cleanup
I believe I met all the [requirments](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1) to become a reviewer, and it would be a great pleasure of mine to become one.
Check-list:
```release-note
NONE
```

Self-nominate pbundyra as a Kueue reviewer

---

charts/kueue/README.md

Fix readme repo and tag for manager image

---

pkg/controller/jobframework/base_webhook.go
pkg/controller/jobframework/base_webhook_test.go
pkg/controller/jobframework/interface.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go

/kind cleanup
Rename JobWithValidation to JobWithCustomValidation.
Fixes #
```release-note
NONE
```

Rename JobWithValidation to JobWithCustomValidation.

---

cmd/experimental/kjobctl/go.mod
cmd/experimental/kjobctl/go.sum

/kind cleanup
Bump Kueue version in kjobctl.
Fixes #3385
```release-note
NONE
```

[kjobctl] Bump Kueue version.

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
site/hugo.toml

Part of #3302 
```release-note
NONE
```

Update latest kueue v0.9.0

---

site/static/examples/multikueue/multikueue-setup.yaml

update multikueue setup examples to v1beta1 api

---

pkg/queue/cluster_queue_test.go

Sorry for the mess maintainers!!
```release-note
NONE
```

Revert "[cleanup]: refactor code to show the use of fakeClock explicitly in pkg/queue(#3380)"

---

apis/kueue/v1beta1/resourceflavor_types.go
apis/kueue/v1beta1/zz_generated.deepcopy.go
client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go
pkg/cache/tas_flavor.go
pkg/cache/tas_flavor_snapshot.go
pkg/controller/tas/resource_flavor.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/wrappers.go
site/content/en/docs/reference/kueue.v1beta1.md

/kind cleanup
Use TopologyReference instead of string.
Fixes #3492
```release-note
NONE
```

Use TopologyReference instead of string.

---

site/content/en/docs/concepts/multikueue.md

Update MultiKueue feature state.
Fixes #
```release-note
NONE
```

Update MultiKueue feature state.

---

CHANGELOG/CHANGELOG-0.9.md

Update release notes.
Fixes #3497
```release-note
NONE
```

Update release-notes with upgrading steps to 0.9.x

---

pkg/cache/clusterqueue.go
pkg/scheduler/scheduler_test.go
pkg/workload/workload.go

/kind bug
Fixes #3482
```release-note
Fix accounting for usage coming from TAS workloads using multiple resources. The usage was multiplied
by the number of resources requested by a workload, which could result in under-utilization of the cluster.
It also manifested itself in the message in the workload status which could contain negative numbers.
```

TAS: fix accounting for usage from TAS workloads using multiple resources

---

cmd/experimental/kjobctl/test/e2e/slurm_test.go

/kind cleanup
Add delete e2e test for kjobctl slurm.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3288#issuecomment-2432175113.
```release-note
NONE
```

[kjobctl] Slurm delete e2e test.

---

site/static/examples/tas/sample-queues.yaml

Fixes #3481
```release-note
NONE
```

fix: nodelabels in tas's sample

---

site/static/examples/serving-workloads/sample-deployment.yaml
site/static/examples/serving-workloads/sample-statefulset.yaml

Use nginx image on StatefulSet example.
Fixes #
```release-note
NONE
```

Use nginx image on StatefulSet example.

---

charts/kueue/templates/rbac/role.yaml
charts/kueue/templates/webhook/webhook.yaml
config/components/rbac/role.yaml
config/components/webhook/manifests.yaml
pkg/controller/jobs/statefulset/statefulset_controller.go
pkg/controller/jobs/statefulset/statefulset_reconciler.go
pkg/controller/jobs/statefulset/statefulset_reconciler_test.go
pkg/controller/jobs/statefulset/statefulset_webhook.go
pkg/controller/jobs/statefulset/statefulset_webhook_test.go
test/e2e/singlecluster/statefulset_test.go
test/util/util.go

/kind feature
Allow StatefulSet scaling down to zero and scale up from zero.
Part of #3279
```release-note
Allowed StatefulSet scaling down to zero and scale up from zero.
```

Allow StatefulSet scaling down to zero and scale up from zero.

---

pkg/cache/clusterqueue_test.go

/kind feature
Test CQ validation for unsupported configurations of TAS.
Fixes #3516 
```release-note
NONE
```

Add unit test for CQ validation for unsupported configurations of TAS

---

site/content/en/docs/tasks/manage/setup_multikueue.md

To improve chances that users who go through "Setup MultiKueue" and want to use MPIJob or Kubeflow visit the dedicated pages.
Fixes #3535
```release-note
NONE
```

Point MK Manager Cluster CRDs installation to dedicated pages

---

pkg/controller/jobs/deployment/deployment_webhook_test.go

/kind cleanup
Optimize and extend deployment unit tests.
Prepare for #3555
```release-note
NONE
```

Optimize and extend deployment unit tests.

---

pkg/controller/jobs/deployment/deployment_webhook.go

/kind cleanup
Remove WithValues("deployment", klog.KObj(deployment)) in Webhook. The controller-runtime is adding this to the logger before this call.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3558#discussion_r1846039306.
```release-note
NONE
```

Remove WithValues("deployment", klog.KObj(deployment))

---

CHANGELOG/CHANGELOG-0.8.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

Part of #3563 
```release-note
NONE
```

Prepare v0.8.4

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

/kind cleanup
Fixes #
```release-note
NONE
```

Prepare release 0.9.1

---

CHANGELOG/CHANGELOG-0.8.md

Part of https://github.com/kubernetes-sigs/kueue/issues/3563
```release-note
NONE
```

Update changelog for 0.8.4

---

go.mod
go.sum
vendor/modules.txt

/kind cleanup
Bump sigs.k8s.io/jobset from 0.7.0 to 0.7.1.
Fixes #
```release-note
NONE
```

Bump sigs.k8s.io/jobset from 0.7.0 to 0.7.1

---

test/e2e/tas/job_test.go

/kind cleanup
To align with the e2e test for Jobset in https://github.com/kubernetes-sigs/kueue/pull/3591
```release-note
NONE
```

TAS: cleanup Job e2e tests

---

test/e2e/tas/jobset_test.go

/kind cleanup
Use g.Expect instead of gomega.Expect on gomega.Eventually.
Fixes #
We can't use `gomega.Expect` on `Eventually` if we are using `g gomega.Gomega`. It will stop Eventually on first error.
```release-note
NONE
```

Use g.Expect instead of gomega.Expect on gomega.Eventually.

---

hack/e2e-common.sh
hack/e2e-test.sh

/kind cleanup
The `-v` option in conditional expressions was introduced to bash in versions later than v3. Therefore, those versions that don't support it fail to run e2e tests returning the error `conditional binary operator expected`.
To avoid the above error, this PR replaces the condition to check if a variable is set.
Fixes #
```release-note
NONE
```

Make e2e scripts compatible with older versions of bash

---

cmd/experimental/kjobctl/docs/installation.md

Add install CRDs guide in kjobctl.
Fixes #
```release-note
NONE
```

[kjobctl] Install CRDs guide.

---

pkg/scheduler/preemption/preemption.go

/kind cleanup
Noticed a suggestion in the docstring for atomic add that suggested to use the `atomic.Int64` to avoid alignment issues on some architectures
See: https://pkg.go.dev/sync/atomic#pkg-note-BUG
```release-note
NONE
```

use automatically aligned Int64

---

test/integration/tas/tas_test.go

/kind cleanup
We used to implement validation and mutating testing based on webhooks and markers in the `/test/integration/webhook/core`. 
However, for Topology, we do not have any testing for those.
Fixes #
```release-note
NONE
```

Implement Topology CRD validations testing

---

site/content/en/docs/reference/labels-and-annotations.md

Addressed https://github.com/kubernetes-sigs/kueue/pull/3649#discussion_r1862429926
Fixes #
```release-note
NONE
```

Doc: Fix an incorrect reference formating

---

keps/2724-topology-aware-scheduling/README.md

Part of #3450 
In reference to the discussion here https://github.com/kubernetes-sigs/kueue/issues/3658#issuecomment-2505583333
```release-note
NONE
```

Update KEP to re-evaluate the support for topologies without hostname

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

We want to make sure we have coverage on release branches
Fixes #
```release-note
NONE
```

Add release checklist to add new periodic for patch release

---

pkg/cache/tas_flavor_snapshot.go
pkg/scheduler/scheduler_test.go

/kind bug
Fixes #3693 
Successor for https://github.com/kubernetes-sigs/kueue/pull/3694
```release-note
Fix Kueue crashing when the node for an admitted workload is deleted.
```

Fix Kueue crashing when a node is deleted

---

OWNERS
pkg/controller/OWNERS
pkg/util/OWNERS
pkg/webhooks/OWNERS

/kind cleanup
It's a great journey to incubate Kueue with a small team since early 2022, now, Kueue becomes a critical project in batch/AI training scenes in cloud native world. What impressed me most is the community vitality, more and more contributors join the community and help this project become better, it's amazing. 
However, I don't have time to review PRs anymore, so I would like to step down from my role. But I will not leave, actually, I'd  like to contribute more in the near future, particularly about the vcjob and the inference service. Let's discuss this later.
Last but not least, thanks all for the continuous efforts!
Fixes #
```release-note
None
```

Step down kerthcet as approvers

---

pkg/controller/jobs/statefulset/statefulset_webhook.go

/kind cleanup
Use QueueNameForObject in StatefulSet Webhook.
Fixes #
```release-note
NONE
```

Use QueueNameForObject in StatefulSet Webhook.

---

apis/kueue/v1alpha1/tas_types.go
pkg/controller/jobs/pod/pod_webhook.go
pkg/controller/jobs/statefulset/statefulset_webhook.go
pkg/controller/jobs/statefulset/statefulset_webhook_test.go
pkg/util/testingjobs/statefulset/wrappers.go
site/content/en/docs/reference/labels-and-annotations.md
test/e2e/tas/statefulset_test.go

/kind feature
TAS: Support rank-based ordering for StatefulSet.
Fixes #3735
```release-note
TAS: Support rank-based ordering for StatefulSet.
```

TAS: Support rank-based ordering for StatefulSet.

---

site/content/en/docs/reference/labels-and-annotations.md

Sort labels and annotations.
Fixes #
```release-note
NONE
```

Sort labels and annotations.

---

pkg/controller/jobs/pod/pod_webhook.go

/kind cleanup
Optimize podwebhook by only calling deep copy when the contents of the object were actually changed.
Fixes #
```release-note
NONE
```

optimize pod web hook by avoiding deep copy when no updates were made

---

OWNERS

/kind cleanup
As part of the effort to ensure new PRs are reviewed by the active reviewers, and trying to minimize notifications for the inactive ones. I contacted @denkensk and we aligned on the path forward
The change is based on [the repo activity dashboard](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes-sigs%2Fkueue&var-country_name=All) and follows k8s community guidelines
```release-note
NONE
```

Remove Denkensk from Kueue reviewers

---

README.md

Fixes #3377
- This is just a roadmap, be aware the plans may change, we can update it later
- feel free to propose additional items to include
```release-note
NONE
```

Refresh Kueue roadmap on the main page for 2025

---

cmd/experimental/kueue-viz/frontend/Dockerfile

/kind cleanup
Node 16 is out of support. We should use Node 22. https://endoflife.date/nodejs
Fixes #
```release-note
NONE
```

use node 22 instead of node 16

---

README.md

Fix some minor typos in README.md.
(The description for the kind documentation only mentions new documentation, not bugfixes for the documentation; maybe there's need for a clarification what kind to use for documentation fixes?)
The PR fixes some typos in README.md. Correctly spelled documentation is nice to have.
None
None

README.md: Fix some minor typos

---

.github/dependabot.yml

/kind cleanup
Configure Dependabot for kueue-viz.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3777#issuecomment-2530638876.
```release-note
NONE
```

Configure Dependabot for kueue-viz.

---

cmd/experimental/kueue-viz/frontend/package.json

/kind cleanup
Bump babel/plugin-proposal-private-property-in-object from 7.18.6 to 7.21.11
Fixes #
```release-note
NONE
```

Bump babel/plugin-proposal-private-property-in-object from 7.18.6 to 7.21.11

---

site/content/en/docs/adopters/index.md

Added Innovatrics to adopters list.
N/A
```release-note
NONE
```

[website] Add Innovatrics adopter

---

site/content/en/docs/concepts/cluster_queue.md

Update cluster queue document to match code example
N/A
```release-note
NONE
```

Update resource group example

---

Makefile

/kind cleanup
Developers should be able to `make generate` to generate docs for kueuectl and apiref.
Currently I run `make verify` to update these docs.
Fixes #
```release-note
NONE
```

generate should generate kueuectl and apiref rather than verify

---

charts/kueue/values.yaml
config/default/manager_auth_proxy_patch.yaml

/kind cleanup
Upgrade our defaults for kube-rbac-proxy
Fixes #
This will probably be dropped as a dependency eventually but in case it doesn't we should update the chart to use the latest 
v0.8.0 was published on 2020 and v0.16.0 was published in Feb 2024.
```release-note
NONE
```

Bump kube rbac proxy

---

site/content/en/docs/reference/labels-and-annotations.md

Add `kueue.x-k8s.io/pod-suspending-parent` to the documentation page.
Fixes #
/hold for #3815
```release-note
NONE
```

Add kueue.x-k8s.io/pod-suspending-parent to the documentation page.

---

site/content/en/docs/reference/labels-and-annotations.md
site/content/en/docs/tasks/manage/enforce_job_management/setup_default_local_queue.md

Fixes #2936
```release-note
NONE
```

Documentation for LocalQueueDefaulting

---

pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/integrationmanager_test.go
pkg/controller/jobs/pod/pod_webhook.go

/kind cleanup
Cleanup suggested in review of #3803 
```release-note
NONE
```

avoid hardcoding framework names in pod wehook 

---

site/content/en/docs/tasks/run/deployment.md
site/content/en/docs/tasks/run/plain_pods.md
site/content/en/docs/tasks/run/statefulset.md

/kind documentation 
Updates documentation on pod integration to prefer `managedJobsNamespaceSelector` as first
step towards eventual deprecation of `podOptions`. 
Fixes #
```release-note
NONE
```

update Pod integration docs to prefer managedJobsNamespaceSelector

---

pkg/queue/manager_test.go

/kind cleanup
We should not omit the error verifications in the testings.
Fixes #
```release-note
NONE
```

Check if unexpected errors did not occur in queue unit testings

---

site/content/en/docs/installation/_index.md

Cherry pick of #3725 on website.
#3725: fix table indenting
```release-note
NONE
```

Automated cherry pick of #3725: fix table indenting

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

/kind cleanup
Part-of https://github.com/kubernetes-sigs/kueue/issues/3670
```release-note
NONE
```

Prepare release v0.9.2

---

CHANGELOG/CHANGELOG-0.9.md

/kind cleanup
I did not update the documentations since the current latest Kueue version is v0.10.0 (https://github.com/kubernetes-sigs/kueue/pull/3863).
Part-of: https://github.com/kubernetes-sigs/kueue/issues/3670
```release-note
NONE
```

Add changelog v0.9.2

---

Makefile
cloudbuild.yaml

/kind feature
Adds Makefile target to build kueue-viz images and configure cloudbuild to build them.
Fixes #
Still needs slimming down the frontend image.
```release-note
NONE
```

Adds build and push of kueue-viz images

---

keps/349-all-or-nothing/README.md

/kind cleanup
Adds section about Workload's requeueState field to KEP#349. There is no new changes, it only updates KEP to better reflect current state
Fixes #
```release-note
NONE
```

Add section about Workload's requeueState field to KEP#349

---

Makefile

/kind bug
Build for only one platform on kueue-viz-image target.
Fixes #
Fix for https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3881/pull-kueue-build-image-main/1869367074451623936.
```release-note
NONE
```

Build for only one platform on kueue-viz-image target.

---

README.md
site/content/en/docs/contribution guidelines/_index.md
site/content/en/docs/talks_and_presentations/_index.md

To showcase Kueue based on publicly available materials and collect them in one place as a refence point.
This is a starting point, we can add more talks or presentations from wg-batch or other conferences.
```release-note
NONE
```

Talks and presentations page for Kueue

---

test/integration/tas/tas_test.go

/kind bug
/kind flake
Wait for finalizer added to the topology on integration test.
Fixes #3890
```release-note
NONE
```

Wait for finalizer added to the topology on integration test.

---

site/content/en/docs/adopters/index.md

Add Red Hat to the list of adopters
Fixes #
N/A
```release-note
NONE
```

[Website] Add Red Hat adopter

---

site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md

Improves instructions for disabling VisibilityOnDemand feature.
Fixes #3943. 
```release-note
NONE
```

improve instructions for disabling VisibilityOnDemand feature

---

site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md

Fixes #
None
```release-note
NONE
```

Doc: Fix an incorrect reference

---

OWNERS
cmd/OWNERS
test/OWNERS

/kind cleanup
Remove @trasc from reviewers and approvers lists.
Fixes #
```release-note
None
```

Remove trasc from reviewers and approvers lists.

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/clusterqueue.go

/kind cleanup
```release-note
NONE
```

rename usage variabale to be more clear

---

OWNERS

I believe that I've met all of the [requirements]([requirments](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1)), and would like to self-nominate as a Kueue Reviewer.
- Most notably, implemented Hierarchical Cohorts #79
```release-note
NONE
```

Self-nominate gabesaba@ as a reviewer

---

site/content/en/docs/tasks/dev/integrate_a_custom_job.md
site/content/en/docs/tasks/run/wrapped_custom_jobs.md
site/content/en/docs/tasks/run/wrapped_custom_workload.md
site/static/examples/jobs/appwrapper-leaderworkerset-sample.yaml

Documents how the AppWrapper integration can be leveraged to run custom Jobs.
Fixes #3975 
```release-note
NONE
```

document using AppWrappers to run wrapped custom Jobs

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part-of #https://github.com/kubernetes-sigs/kueue/issues/3950
```release-note
NONE
```

Prepare release v0.10.1

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

/kind cleanup
Part-of https://github.com/kubernetes-sigs/kueue/issues/3981
```release-note
NONE
```

Prepare release v0.9.3

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
Part of #3950 
```release-note
NONE
```

Improvements to the release instructions identified during 0.10.1

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #3950 
```release-note
NONE
```

Update latest version to v0.10.1

---

CHANGELOG/CHANGELOG-0.9.md

/kind cleanup
Part-of: https://github.com/kubernetes-sigs/kueue/issues/3981
The other files like `charts/kueue/Chart.yaml` should be `v0.10.1` as addressed in (https://github.com/kubernetes-sigs/kueue/pull/4018/files). 
```release-note
NONE
```

Update v0.9 release changelog

---

apis/config/v1beta1/configuration_types.go
charts/kueue/values.yaml
config/components/manager/controller_manager_config.yaml
pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
site/content/en/docs/reference/kueue-config.v1beta1.md
test/e2e/config/common/controller_manager_config.yaml

/kind cleanup
Rename leaderworkerset integration to leaderworkerset.x-k8s.io/leaderworkerset.
Fixes #
```release-note
NONE
```

Rename leaderworkerset integration to leaderworkerset.x-k8s.io/leaderworkerset.

---

test/integration/multikueue/multikueue_test.go

/kind bug
Workloads on the worker clusters to are deleted synchronously (evicted), if they are in the pending state due to AC Rejected state.
Relates to #3841
```release-note
NONE
```

 Document current behavior of workload deletion if AC is rejected

---

README.md

Fixes #
```release-note
NONE
```

Link Kueue's logos in README

---

Makefile-test.mk

/kind cleanup
We have introduced separate test-infra job for multikueue integration test.
Now it's time that they run separately.
Fixes #4040
```release-note
NONE
```

[Cleanup] Make test-integration to call only singlecluster tests

---

pkg/controller/jobframework/base_webhook.go
pkg/controller/jobframework/defaults.go
pkg/controller/jobframework/interface.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/job/job_webhook.go
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/jobset/jobset_webhook.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/mpijob/mpijob_webhook.go

/kind cleanup
Factors out managedBy defaulting (motivated by AppWrapper multi-kueue integration #3992) 
Fixes #
```release-note
NONE
```

factor out managedBy defaulting logic

---

pkg/controller/tas/resource_flavor.go
pkg/controller/tas/topology_controller.go

/kind cleanup
To improve debuggability of race conditions as in #4033
Part of #4033
I tried to induce the failure locally running the failed integration test over 1000 times under stress, but no success. So, I think the best way to move forward is to improve logging and investigate deeper when it repeats.
```release-note
NONE
```

Improve logging for TAS to debug rare CI failures

---

pkg/controller/tas/resource_flavor.go
pkg/controller/tas/topology_controller.go

Cherry pick of #4068 on release-0.10.
#4068: Improve logging for TAS to debug rare CI failures
```release-note
NONE
```

Automated cherry pick of #4068: Improve logging for TAS to debug rare CI failures

---

pkg/controller/tas/topology_controller.go

/kind cleanup
Follow up to https://github.com/kubernetes-sigs/kueue/pull/4068
I will also need to apply this to release-0.10, as this PR did it wrong too: https://github.com/kubernetes-sigs/kueue/pull/4087/files#diff-7f688e0706bb6b6775d35b320ee0d496f92ed367d87cb845979731898ea9d1eaR158
```release-note
NONE
```

TAS fix the topology create event logging

---

site/content/en/docs/tasks/run/external_workloads/argo_workflow.md

Fixes #
```release-note
none
```

Add linkTitle for argo workflow doc

---

site/content/en/docs/tasks/run/jobsets.md
site/static/examples/jobs/sample-jobset.yaml

As I was looking for jobset samples, I noticed that we did not have them in site/static/examples.
JobSet was inlined while other examples seem to reference the static examples.
Fixing this so jobset is consistent with other examples
Fixes #
```release-note
NONE
```

reference jobset sample rather than inline

---

pkg/controller/admissionchecks/provisioning/controller.go
pkg/controller/admissionchecks/provisioning/controller_test.go

Cherry pick of #4114 on release-0.9.
#4114: Update workload AdmissionChecks status on AdmissionRequest creation error.
```release-note
Fix the bug that prevented Kueue from updating the AdmissionCheck state in the Workload status on a ProvisioningRequest creation error.
```

Automated cherry pick of #4114: Update workload AdmissionChecks status on AdmissionRequest creation error.

---

hack/kind-cluster.yaml
hack/multikueue/manager-cluster.kind.yaml
hack/multikueue/worker-cluster.kind.yaml
hack/tas-kind-cluster.yaml

/kind cleanup
Increase log level for Kubernetes components.
Fixes #4111
```release-note
NONE
```

Increase log level for Kubernetes components.

---

pkg/workload/resources.go

/kind cleanup
This is a following PR of https://github.com/kubernetes-sigs/kueue/pull/4108.
I applied the following principle to the workload.resources lib:
- https://google.github.io/styleguide/go/decisions#variable-name-vs-type
- In Kubernetes, we do not distinguish between empty and 0 length slice.
Fixes #
```release-note
NONE
```

chore: Clean up workload resources lib

---

pkg/controller/admissionchecks/multikueue/workload.go

/kind cleanup
In this situation, slice initialization is not needed, as we can check here: https://go.dev/play/p/EMXJjf-C-qd
Fixes #
```release-note
NONE
```

chore: Avoid unnecessary slice initialization

---

cmd/importer/util/util.go
pkg/cache/tas_flavor.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/statefulset/statefulset_reconciler.go
pkg/controller/tas/topology_ungater.go
pkg/controller/tas/topology_ungater_test.go
pkg/util/pod/pod.go
pkg/util/pod/pod_test.go
pkg/util/testingjobs/pod/wrappers.go

/kind cleanup
We often check if a Pod is terminated by `p.Status.Phase == corev1.PodFailed || p.Status.Phase == corev1.PodSucceeded`.
So, I utilize the verification mechanism under the `pkg/util/pod` package.
Fixes #
```release-note
NONE
```

Utilize isPodTerminated

---

test/util/util.go

/kind cleanup
The gomega unexpected errors should be propagated to the top level.
Fixes #
```release-note
NONE
```

chore: Propagate testutil errors to the top level

---

pkg/scheduler/scheduler_test.go

/kind cleanup
To make sure TAS works with partial admission as this scenario is easy to break when working on preemptions.
```release-note
NONE
```

Add unit test for TAS to show it works with partial admission

---

pkg/controller/jobs/job/job_webhook_test.go

/kind cleanup
UTs are missing for the situation where the defaulter tries to mutate default LocalQueue against Job owned by Kueue managed Job in the following:
https://github.com/kubernetes-sigs/kueue/blob/96eb2e59692ae2bf1bb7341a073facbdbb0de12f/pkg/controller/jobframework/defaults.go#L87-L90
Fixes #
```release-note
NONE
```

Implement LocalQueueDefaulting UTs for owner is managed by Kueue

---

pkg/controller/jobs/statefulset/statefulset_webhook_test.go

/kind cleanup
We must use empty enabledIntegrations in every test case since each test case must be isolated.
Fixes #
```release-note
NONE
```

Clean up enabled integrations every UT cases

---

cloudbuild.yaml

/kind cleanup
Based on https://github.com/kubernetes-sigs/kueue/pull/4222#issuecomment-2650555066 discussion, we try to improve image building performance by increasing machine size and building concurrency.
Fixes #
```release-note
NONE
```

chore: Increase machine size to 'E2_HIGHCPU_32' for post container image buildings

---

pkg/cache/tas_flavor_snapshot.go

/kind cleanup
I simplified the `sortedDomains` function powered by `slices` and `cmp`.
Fixes #
```release-note
NONE
```

TAS: simplify domain sorting

---

site/content/en/docs/tasks/run/multikueue/kubeflow.md

Fixes #2552 
```release-note
NONE
```

[MultiKueue] Update Kubeflow Jobs run documentation

---

pkg/cache/tas_cache_test.go

/kind cleanup
I added this as we can easily debug something powered by logging.
Fixes #
Follow-up of https://github.com/kubernetes-sigs/kueue/pull/4271#discussion_r1957396308
```release-note
NONE
```

chore: Enable logger for tas_cash UTs

---

apis/kueue/v1beta1/clusterqueue_types.go
site/content/en/docs/reference/kueue.v1beta1.md

/kind cleanup
See https://github.com/kubernetes-sigs/kueue/pull/4288#discussion_r1959973984
```release-note
NONE
```

Make FairSharing optional in ClusterQueue

---

site/content/en/docs/concepts/multikueue.md

The Concepts chapter includes a section called What's next.
The link in Multikueue's What's next describes a link to submit a workload to Kueue, but it is more relevant to describe a link to submit a workload in Multikueue.
In this PR, the link in Multikueue's What's next is changed from a link to submit a workload to Kueue to a link to submit a workload to MultiKueue.
NONE
```release-note
NONE
```

fix(docs): Change the What's next link in the Multikueue documentation from a Kueue link to a Multikueueue link

---

apis/kueue/v1beta1/workload_types.go
pkg/visibility/api/v1beta1/pending_workloads_cq_test.go
test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go
test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go
test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go
test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go

/kind cleanup
These are unused.
Fixes #
```release-note
NONE
```

chore: Remove unused constants

---

charts/kueue/Chart.yaml

/kind cleanup
Fixes #3971
The comments are confusing. These are standard auto-generated comments for helm packages, but we have our custom logic in Kueue CI which overrides the fields. For more info check: https://github.com/kubernetes-sigs/kueue/issues/3971#issuecomment-2667895039.
```release-note
NONE
```

Clarify the comment for versioning of HELM charts in Kueue

---

site/content/en/docs/tasks/run/deployment.md
site/content/en/docs/tasks/run/external_workloads/argo_workflow.md
site/content/en/docs/tasks/run/external_workloads/tektoncd.md
site/content/en/docs/tasks/run/plain_pods.md
site/content/en/docs/tasks/run/statefulset.md

Replaces mentions of `v1/pod` as the integration name for `pod` which could have potentially caused confusion.
Fixes #
```release-note
NONE
```

docs: update pod integration name in documentation

---

site/content/en/docs/concepts/multikueue.md
site/content/en/docs/tasks/run/multikueue/deployment.md
site/content/en/docs/tasks/run/multikueue/plain_pods.md

Closes: #2341
```release-note
NONE
```

docs: add user examples for multikueue pods and deployments

---

pkg/cache/tas_cache_test.go

/kind cleanup
This `cases` struct has `requests` and `request`, but those use completely different typed. This renaming helps to avoid confusing.
Fixes #
```release-note
NONE
```

chore: Rename request with topologyRequest

---

test/e2e/customconfigs/skipjobswithoutqueuename_test.go

/kind cleanup
This PR adds e2e tests for the pod integration when `manageJobsWithoutQueueName=true`. This is part of #3767  
Fixes #
```release-note
NONE
```

Pod: Add e2e tests for the manageJobsWithoutQueueName

---

site/content/en/docs/installation/_index.md

I added how to install Kueue by Helm (released artifacts and OCI)
Part-of #4143
```release-note
NONE
```

Doc: Add Helm installation guides

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

Part-of #4143
```release-note
NONE
```

Update release process with promoting Helm chart

---

test/e2e/singlecluster/e2e_test.go
test/e2e/singlecluster/tas_test.go
test/integration/singlecluster/controller/jobs/job/job_controller_test.go
test/util/util.go

/kind cleanup
We have 2 same testing util, `expectJobUnsuspendedWithNodeSelectors `. So, I commonized it in `test/util` package.
Fixes #
```release-note
NONE
```

chore: Commonize duplicated expectJobUnsuspendedWithNodeSelectors()

---

pkg/cache/cache_test.go

/kind cleanup
Follow up for https://github.com/kubernetes-sigs/kueue/pull/4363#discussion_r1967197374 comments.
/assign @mbobrovskyi 
Fixes #
```release-note
NONE
```

chore: Use plural for variables typed []PodSetAssignment

---

cmd/importer/pod/import_test.go
pkg/cache/cache_test.go
pkg/cache/snapshot_test.go
pkg/cache/tas_cache_test.go
pkg/controller/admissionchecks/provisioning/controller_test.go
pkg/controller/core/workload_controller_test.go
pkg/controller/jobs/job/job_controller_test.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go
pkg/queue/cluster_queue_test.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/scheduler_test.go
pkg/util/testing/wrappers.go
pkg/webhooks/workload_webhook_test.go
pkg/workload/workload_test.go
test/e2e/singlecluster/e2e_test.go
test/integration/singlecluster/controller/jobs/job/job_controller_test.go
test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
test/integration/singlecluster/scheduler/scheduler_test.go
test/integration/singlecluster/scheduler/workload_controller_test.go
test/integration/singlecluster/webhook/core/workload_test.go

/kind cleanup
Use the default PodSet name as constants
Fixes #
```release-note
NONE
```

chore: Use constants default PodSet name

---

charts/kueue/templates/rbac/leader_election_role.yaml
charts/kueue/templates/rbac/leader_election_role_binding.yaml
config/components/rbac/leader_election_role.yaml
config/components/rbac/leader_election_role_binding.yaml

/kind bug
These 2 resources are missing a namespace in the Helm chart, meaning creating manifests with `helm template` gives an incorrect result.
```release-note
NONE
```

Set namespace for leader election role/rolebinding

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4318
```release-note
NONE
```

Prepare release v0.10.2

---

CHANGELOG/CHANGELOG-0.9.md
Makefile
README.md
charts/kueue/Chart.yaml
site/hugo.toml

/kind cleanup
Part-of https://github.com/kubernetes-sigs/kueue/issues/4317
```release-note
NONE
```

Prepare release v0.9.4

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/4318
```release-note
NONE
```

Update main to v0.10.2

---

pkg/controller/admissionchecks/multikueue/admissioncheck.go
pkg/controller/admissionchecks/multikueue/multikueuecluster.go
pkg/controller/admissionchecks/multikueue/workload.go
pkg/controller/admissionchecks/provisioning/controller.go
pkg/controller/core/admissioncheck_controller.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/core/cohort_controller.go
pkg/controller/core/localqueue_controller.go
pkg/controller/core/resourceflavor_controller.go
pkg/controller/core/workload_controller.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
pkg/controller/jobs/statefulset/statefulset_reconciler.go
pkg/controller/tas/resource_flavor.go
pkg/controller/tas/topology_ungater.go

/kind cleanup
Clean up reconcile logs and remove unnecessary values.
Fixes #
As we discussed [here](https://github.com/kubernetes-sigs/kueue/pull/4359#discussion_r1967189192) we don't need to use WithValues since it’s already captured in the logs.
```
2025-02-24T08:23:01.568360276Z	LEVEL(-2)	tas/topology_controller.go:96	Reconcile Topology	{"controller": "tas_topology_controller", "controllerGroup": "kueue.x-k8s.io", "controllerKind": "Topology", "Topology": {"name":"hostname"}, "namespace": "", "name": "hostname", "reconcileID": "0c96f8bd-5e05-4d4e-9973-4405a8c1197e"}
```
```release-note
NONE
```

Clean up Reconcile() logs.

---

site/content/en/docs/concepts/topology_aware_scheduling.md

fix typo, `nods` -> `nodes`
Fixes #
```release-note
NONE
```

docs: fix typo, nods -> nodes

---

pkg/controller/jobframework/defaults.go
pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/validation.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/pod/pod_controller_test.go
pkg/controller/jobs/pod/pod_webhook.go

/kind cleanup
Commonize the code for checking if workload is managed by Kueue.
Fixes #4000
```release-note
NONE
```

Commonize the code for checking if workload is managed by Kueue.

---

test/e2e/customconfigs/skipjobswithoutqueuename_test.go

/kind cleanup
This PR adds e2e tests for the deployment integration when `manageJobsWithoutQueueName=true`. This is part of #3767  
Fixes #
```release-note
NONE
```

Deploy: Add e2e tests for the manageJobsWithoutQueueName

---

charts/kueue/README.md
charts/kueue/templates/kueue-viz/backend-deployment.yaml
charts/kueue/templates/kueue-viz/frontend-deployment.yaml
hack/update-helm.sh

Fixes #4394
```release-note
Adds kueueViz helm charts and params `enableKueueViz`, `kueueViz.backend.image` and `kueueViz.frontend.image` 
```

Document kueueViz charts and adds params for backend and frontend images

---

pkg/workload/workload.go

/kind cleanup
To make code easier to maintain.
It is part of the refactoring which will make life easier for https://github.com/kubernetes-sigs/kueue/pull/4418
```release-note
NONE
```

Cleanup: remove redundant helpers for scaling requests

---

test/e2e/customconfigs/skipjobswithoutqueuename_test.go

/kind cleanup
This PR adds e2e tests for the StatefulSet integration when `manageJobsWithoutQueueName=true`
Fixes #3767
```release-note
NONE
```

StatefulSet: Add e2e tests for the manageJobsWithoutQueueName

---

pkg/scheduler/scheduler.go

/kind cleanup
To make the logic easier to understand. In particular the PartialAdmission feature gate now clearly protects only the call to `wl.CanBePartiallyAdmitted`.
I 'm also modifying this code as part of https://github.com/kubernetes-sigs/kueue/pull/4418 so sending the preparatory PR to reduce the final diff.
```release-note
NONE
```

Cleanup getAssignments wrt calling partial admission

---

charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
hack/internal/tools/go.mod
hack/internal/tools/go.sum

/kind cleanup
Bump sigs.k8s.io/controller-tools from 0.17.1 to 0.17.2 in /hack/internal/tools
Fixes #
Manual fix for https://github.com/kubernetes-sigs/kueue/pull/4459.
```release-note
NONE
```

Bump sigs.k8s.io/controller-tools from 0.17.1 to 0.17.2 in /hack/internal/tools

---

test/e2e/customconfigs/skipjobswithoutqueuename_test.go

/kind bug
Some e2e tests when `manageJobsWithoutQueueName=true` are comparing the pod(s) labels map using the `BeComparableTo` Gomega function. This introduces flakiness because the pod labels map may change at runtime and therefore may contain more labels than expected at the time of assertion. 
This PR fixes the issue by asserting that the map contains the expected key and value instead of comparing the entire map.
Fixes #4462
```release-note
NONE
```

Fix flaky deploy ManageJobsWithoutQueue e2e test

---

site/content/en/docs/installation/_index.md

https://prometheus-operator.dev/docs/prologue/quick-start/ is not found.
Fixes #
```release-note
NONE
```

Doc: Fix Prometheus Operator installing guide link

---

pkg/cache/clusterqueue_snapshot.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/scheduler.go

/kind cleanup
Unused return value. Cleanup in prep for #3759
```release-note
NONE
```

ClusterQueueSnapshot.DominantResourceShare - Delete unused return value

---

pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind cleanup
Preparation for #3759. We will use this EntryIterator to define an iterator for FairSharing, as the ordering of FairSharing with Hierarchical Cohorts is quite complex, and cannot be done statically.
```release-note
NONE
```

Define EntryIterator

---

cmd/experimental/kueue-viz/frontend/package.json

/kind cleanup
Bump material dependencies
Bump @mui/material and @mui/icons-material from 5.16.14 to 6.4.6 in /cmd/experimental/kueue-viz/frontend
Fixes #
Fix for https://github.com/kubernetes-sigs/kueue/pull/4454 and https://github.com/kubernetes-sigs/kueue/pull/4453. The packages @mui/material and @mui/icons-material should be updated together.
```release-note
NONE
```

Bump mui/material and mui/icons-material from 5.16.14 to 6.4.6 in /cmd/experimental/kueue-viz/frontend

---

charts/kueue/templates/manager/manager.yaml
charts/kueue/values.yaml
config/default/kustomization.yaml
config/default/manager_metrics_patch.yaml

/kind bug
```bash
kehannon@kehannon-thinkpadp1gen4i:~/Work/kueue$ k get endpoints -n kueue-system
NAME                                       ENDPOINTS          AGE
kueue-controller-manager-metrics-service   10.244.0.70:8443   27s
kueue-visibility-server                    10.244.0.70:8082   27s
kueue-webhook-service                      10.244.0.70:9443   27s
```
Before this change, the metrics service never had an endpoint because the deployment 
was not referencing the port.
This causes issues for prometheus to find the service.
Fixes #
```release-note
NONE
```

add binding metrics port for helm and kustomize

---

pkg/scheduler/fair_sharing_iterator.go

/kind cleanup
Follow-up. See https://github.com/kubernetes-sigs/kueue/pull/4503#discussion_r1984946395
```release-note
NONE
```

Simply Clearing of FairSharingIterator's DRSValue map

---

pkg/scheduler/fair_sharing_iterator.go
pkg/scheduler/scheduler.go

/kind cleanup
Follow up. See https://github.com/kubernetes-sigs/kueue/pull/4503#discussion_r1984948160
```release-note
NONE
```

Improve Scheduling and FairSharingIterator logging

---

test/integration/controller/jobs/mxjob/mxjob_controller_test.go

In cb91c2464a7750532e1b24350285f2a41a838a17 the test was not updated.
/king bug
/kind flake
Integration test fails in release-0.10
Fixes #4344
```release-note
NONE
```

Fix integration test on release-0.10

---

test/integration/singlecluster/tas/tas_test.go

/kind bug
/kind flake
Create the `ResourceFlavor` before the `Topology` to avoid flakiness.
Fixes #4506
```release-note
NONE
```

Create ResourceFlavor before Topology

---

pkg/controller/jobs/deployment/deployment_webhook.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
pkg/controller/jobs/pod/pod_webhook.go
pkg/webhooks/resourceflavor_webhook.go
pkg/webhooks/workload_webhook.go

/kind cleanup
The `field.ErrorList` is a sllice. So it would be better not to initialize it with an empty slice.
Fixes #
```release-note
NONE
```

chore: Avoid to initialize field.ErrorList with an empty slice

---

charts/kueue/values.yaml

/kind bug
If I don't use 8443 as the port, I have trouble with metrics working.
This matches what we have for kustomize.
Fixes #
```release-note
NONE
```

use 8443 instead of target port

---

site/content/en/docs/concepts/topology_aware_scheduling.md

Fixes #3761
```release-note
NONE
```

TAS: cohorts and preemptions are no longer limitations

---

pkg/scheduler/preemption/preempted_workloads.go
pkg/scheduler/scheduler.go

/kind cleanup
A little organization. Motivated by getting annoyed when typing `go test ./pkg/preempt`, and tab autocomplete not working
```release-note
NONE
```

Move preempted_workloads to preemption package

---

go.mod
go.sum
hack/e2e-common.sh
pkg/controller/jobframework/reconciler_test.go
pkg/controller/jobframework/validation.go
pkg/controller/jobs/appwrapper/appwrapper_controller.go
pkg/controller/jobs/statefulset/statefulset_webhook_test.go
vendor/github.com/project-codeflare/appwrapper/api/v1beta2/groupversion_info.go
vendor/modules.txt

/kind feature
Updates AppWrapper version to v1.1.0.
The AppWrapper v1.1.0 release was tested against Kueue 0.11.0-rc.0.
```release-note
NONE
```

Update AppWrapper to v1.1.0

---

test/integration/singlecluster/scheduler/scheduler_test.go

/kind cleanup
Fix mixed variable names.
Fixes #
```release-note
NONE
```

Fix mixed variable names.

---

keps/2724-topology-aware-scheduling/README.md
keps/2724-topology-aware-scheduling/kep.yaml

https://github.com/kubernetes-sigs/kueue/pull/4574#issuecomment-2721156510
Fixes #
```release-note
NONE
```

TAS: KEP: Remove implicit unconstrained default

---

pkg/cache/clusterqueue_snapshot.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_oracle.go
pkg/scheduler/scheduler.go

/kind cleanup
Preparatory PR for #https://github.com/kubernetes-sigs/kueue/issues/3759
This will help reduce diff in #4572. See https://github.com/kubernetes-sigs/kueue/pull/4572#discussion_r1993294390 and https://github.com/kubernetes-sigs/kueue/pull/4572#issuecomment-2721329881
```release-note
NONE
```

[FairSharing] Add Workload Usage to Snapshot

---

site/content/en/docs/contribution_guidelines/testing.md

Fixes #4432 
follow-up for https://github.com/kubernetes-sigs/kueue/pull/4552#discussion_r1991107257
```release-note
NONE
```

Add link to stress tool website in docs

---

OWNERS
charts/kueue/OWNERS
config/OWNERS
pkg/controller/jobs/jobset/OWNERS
site/OWNERS
test/OWNERS

Nominate myself for reviewer for Kueue
Following https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer,
- https://github.com/kubernetes-sigs/kueue/issues?q=reviewed-by%3Akannon92%20-author%3Akannon92
- https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+author%3Akannon92+ 
- https://github.com/kubernetes-sigs/kueue/pull/421
- https://github.com/kubernetes-sigs/kueue/pull/382
- https://github.com/kubernetes-sigs/kueue/pull/4385
- https://github.com/kubernetes-sigs/kueue/pull/3071
- https://github.com/kubernetes-sigs/kueue/pull/4444 
- https://github.com/kubernetes-sigs/kueue/pull/3760
- https://github.com/kubernetes-sigs/kueue/pull/3595
- https://github.com/kubernetes-sigs/kueue/pull/2725
- https://github.com/kubernetes-sigs/kueue/pull/4337
- …

self nominate for kannon92 for reviewer

---

Makefile-test.mk
test/e2e/customconfigs/suite_test.go
test/e2e/multikueue/suite_test.go
test/e2e/singlecluster/suite_test.go
test/e2e/tas/suite_test.go
test/integration/framework/framework.go
test/util/util.go

/kind cleanup
Add TEST_LOG_LEVEL env variable to control logging verbosity.
Fixes #4555
```release-note
NONE
```

Add TEST_LOG_LEVEL env variable to control logging verbosity.

---

pkg/controller/core/localqueue_controller.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in localqueue-controller.
This allows us to use the `TypedPredicate` rather than `Predicate` which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.LocalQueue)`) everywhere.
Fixes #
I am planning to apply the same approach to all controllers.
Related PRs:
- Workload controller: https://github.com/kubernetes-sigs/kueue/pull/4630
- AdmissionCheck controller: https://github.com/kubernetes-sigs/kueue/pull/4631
- Cohort controller: https://github.com/kubernetes-sigs/kueue/pull/4632
- ResouceFlavor controller: https://github.com/kubernetes-sigs/kueue/pull/4633
```release-note
NONE
```

Use TypedControllerManagedBy in localqueue controller

---

pkg/controller/core/clusterqueue_controller.go

/kind cleanup
I consolidated the `wlUpdateCh`, `rfUpdateCh`, `topologyUpdateCh`, and `acUpdateCh` into single `nonCQUpdateCh` powered by `TypedGenericEventHandler[iter.Seq[kueue.ClusterQueueReference]]`.
This improvement has some advantages in the following:
- Reducing the kind of channel reduces the number of maintaining EventHandlers and allows us to reduce memory consumption.
- The `iter.Seq[kueue.ClusterQueueReference]` can reduce the time complexity since this allows us to perform just once loop against same data structure to obtain reconcile Request.
Fixes #
Although I did not change anything in this PR, we could improve more by refining returning typed with `iter.Seq[kueue.ClusterQueueReference]` in `cache.ClusterQueuesUsingFlavor()`, `cache.ClusterQueuesUsingAdmissionCheck()`, and …

Consolidate object update channel source into one in clusterqueue controller

---

pkg/controller/core/workload_controller.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the workload controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.Workload)`) everywhere.
Fixes #
Related PRs:
- LocalQueue controller: https://github.com/kubernetes-sigs/kueue/pull/4625
- AdmissionCheck controller: https://github.com/kubernetes-sigs/kueue/pull/4631
- Cohort controller: https://github.com/kubernetes-sigs/kueue/pull/4632
- ResouceFlavor controller: …

Use TypedControllerManagedBy in workload controller

---

pkg/controller/core/admissioncheck_controller.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the admissioncheck controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.AdmissionCheck)`) everywhere.
Fixes #
Related PRs:
- LocalQueue controller: https://github.com/kubernetes-sigs/kueue/pull/4625
- Workload controller: https://github.com/kubernetes-sigs/kueue/pull/4630
- Cohort controller: https://github.com/kubernetes-sigs/kueue/pull/4632
- ResouceFlavor controller: …

Use TypedControllerManagedBy in the admissioncheck controller

---

pkg/controller/core/cohort_controller.go
pkg/controller/core/cohort_controller_test.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the cohort controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.Cohort)`) everywhere.
Fixes #
Related PRs:
- Workload controller: https://github.com/kubernetes-sigs/kueue/pull/4630
- AdmissionCheck controller: https://github.com/kubernetes-sigs/kueue/pull/4631
- LocalQueue controller: https://github.com/kubernetes-sigs/kueue/pull/4625
- ResouceFlavor controller: …

Use TypedControllerManagedBy in the cohort controller

---

pkg/controller/core/resourceflavor_controller.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the resourceflavor controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.ResourceFlavor)`) everywhere.
Fixes #
Related PRs:
- Workload controller: https://github.com/kubernetes-sigs/kueue/pull/4630
- AdmissionCheck controller: https://github.com/kubernetes-sigs/kueue/pull/4631
- Cohort controller: https://github.com/kubernetes-sigs/kueue/pull/4632
- LocalQueue controller: …

Use TypedControllerManageBy in the resourceflavor controller

---

keps/2724-topology-aware-scheduling/README.md

/kind cleanup
Part of #3450 
reference the issue: https://github.com/kubernetes-sigs/kueue/issues/4634
This was suggested in https://github.com/kubernetes-sigs/kueue/pull/4591#discussion_r1998155126
```release-note
NONE
```

TAS: KEP update to add perf test to Beta requirements

---

pkg/controller/tas/topology_controller.go

/kind cleanup
The `resourceFlavorHandler` is not referenced by anywhere. That is just initialization.
Fixes #
```release-note
NONE
```

chore: remove unreferenced struct member

---

pkg/controller/tas/topology_ungater.go

/kind bug
The TopologyUngator is reconciled for the Workload object. So, the leader change should be triggered by the Workload object.
Fixes #
```release-note
TAS: Fix a bug that TopolologyUngator cound not be triggered the leader change when enabled HA mode
```

TAS: Fix TopologyUngator LeaderElection trigger

---

test/e2e/tas/rayjob_test.go

/kind flake
We temporarily don't assert on the exact number of Pods as this flakes on Ray 1.2.2
due to the submitter Pod and Job not being created occasionally 
(See https://github.com/kubernetes-sigs/kueue/issues/4508#issuecomment-2724257298 for more details).
Fixes #4508 
```release-note
NONE
```

[Flaky] Revisit RayJob TAS e2e tests to not count submitter job pod

---

pkg/scheduler/preemption/preemption_test.go

/kind cleanup
Part of #4553. This is the data structure most likely to be changed by a bug in preemption. I wanted to get this in before 0.11, to feel more confident about #4572
Fixes #
```release-note
NONE
```

Resource Node Unchanged During Preemption

---

pkg/controller/tas/topology_ungater.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the topology ungator.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.Workload)`) everywhere.
Fixes #
```release-note
NONE
```

Use TypedControllerManagedby in topology ungator

---

pkg/controller/tas/topology_controller.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the topology controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueuealpha.Topology)`) everywhere.
Fixes #
```release-note
NONE
```

Use TypedControllerManagedby in topology controller

---

pkg/controller/tas/resource_flavor.go

/kind cleanup
I introduced the `TypedControllerManagedBy` instead of `ControllerManagedBy` in the TAS resourceflavor controller.
This allows us to use the `TypedPredicate` rather than `Predicate`, which allows us to avoid typed inference (`obj, ok := e.Object.(*kueue.ResourceFlavor)`) everywhere.
Fixes #
```release-note
NONE
```

Use TypedControllerManagedby in TAS ResourceFlavor controller

---

test/util/constants.go

Short explanation of the different behaviors as well as a link to full agnhost docs
https://github.com/kubernetes-sigs/kueue/pull/4621#issuecomment-2728439146
```release-note
NONE
```

add comments to agnhost behavior

---

site/content/en/docs/tasks/run/multikueue/kuberay.md

We need to provide a documentation on how to use Kuberay with Kueue.
Relates to #3822
```release-note
NONE
```

[MultiKueue] Update Kuberay run documentation

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4682
```release-note
NONE
```

Prepare release v0.10.3

---

CHANGELOG/CHANGELOG-0.9.md

Part-of https://github.com/kubernetes-sigs/kueue/issues/4683
```release-note
NONE
```

Add v0.9.5 to CHANGELOG

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/content/en/docs/installation/_index.md
site/hugo.toml

/kind cleanup
Part of  #4682
```release-note
NONE
```

Update main to v0.10.3

---

site/content/en/docs/tasks/manage/productization/prometheus.md

Follow up from tls certs doc PR.
Fixes #
```release-note
NONE
```

add nits for prometheus section as follow up for review

---

pkg/util/testing/wrappers.go
test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
test/util/util.go

/kind cleanup
Prepare to write more integration tests for https://github.com/kubernetes-sigs/kueue/issues/3759 by reducing verbosity
```release-note
NONE
```

Refactor Fair Sharing Integration Tests

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
config/components/manager/kustomization.yaml
site/hugo.toml

/kind cleanup
Part of #4533
The PR also includes fixing the Makefile goal for preparing the branch:
https://github.com/kubernetes-sigs/kueue/pull/4698/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L284-R285
It reverts the line changed in https://github.com/kubernetes-sigs/kueue/pull/4693/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R284
```release-note
NONE
```

Prepare the 0.11.0 release

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4533
```release-note
NONE
```

Adjust main after 0.11 release

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
Post #4533
```release-note
NONE
```

Update the release steps post 0.11.0

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md

/kind cleanup
Post  #4533
```release-note
NONE
```

Update the release procedure step

---

Makefile
charts/kueue/README.md

/kind cleanup
Follow up to https://github.com/kubernetes-sigs/kueue/pull/4712
This is a manual cherry-pick to align the releasing script for all branches.
```release-note
NONE
```

Align the prepare-release-branch script for 0.10

---

go.mod
go.sum
vendor/github.com/project-codeflare/appwrapper/pkg/utils/utils.go
vendor/modules.txt

/kind feature
Updates AppWrapper from v1.1.0 to v1.1.1.
AppWrapper v1.1.0 was built against Kueue 0.11.0-rc.0.  AppWrapper v1.1.1 was built against the actual Kueue 0.11.0 release.
```release-note
Update AppWrapper to v1.1.1
```

Update AppWrapper to v1.1.1

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4706
```release-note
NONE
```

Prepare v0.11.1

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4706
```release-note
NONE
```

Update main after v0.11.1

---

site/content/en/docs/concepts/multikueue.md
site/content/en/docs/tasks/manage/setup_multikueue.md
site/content/en/docs/tasks/run/kubeflow/_index.md
site/content/en/docs/tasks/run/kubeflow/mpijobs.md
site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
site/content/en/docs/tasks/run/kubeflow/tfjobs.md
site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
site/content/en/docs/tasks/run/multikueue/kubeflow.md
site/content/en/docs/tasks/run/multikueue/mpijob.md

The kubeflow `training-operator` was rebranded as `Trainer`. So, we want to replace `training-operator` word with `trainer` in our documentation as well.
Fixes #
```release-note
NONE
```

Adapt Kubeflow integration documentations with new Trainer brand

---

site/content/en/docs/tasks/run/multikueue/kuberay.md

That is officially `KubeRay` instead of `Kuberay`.
https://docs.ray.io/en/master/cluster/kubernetes/index.html
Fixes #
```release-note
NONE
```

Doc: Replace Kuberay with KubeRay

---

test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go

Additional testing
Integration test for FairSharing x Hierarchical Cohorts, featuring scheduling and preemption
Fixes #3759
```release-note
NONE
```

[FSxHC] Add Integration Test

---

hack/push-chart.sh

/kind bug
Enables the image names substition for production release for kueue-viz backend and frontend images
When pushing production images, the registry and repository must be set properly.
This PR fixes that for kueue-viz
Fixes https://github.com/kubernetes-sigs/kueue/issues/4726
```release-note
NONE
```

Fix push-char for kueue-viz images

---

Makefile
charts/kueue/README.md
charts/kueue/templates/kueue-viz/backend-deployment.yaml
charts/kueue/templates/kueue-viz/frontend-deployment.yaml
charts/kueue/values.yaml
config/components/kueue-viz/backend-deployment.yaml
config/components/kueue-viz/frontend-deployment.yaml
hack/push-chart.sh

/kind cleanup
Align kueue-viz tags
Fixes #
```release-note
NONE
```

Align kueue-viz tags to `main` instead if `main-latest`

---

site/content/en/docs/contribution_guidelines/testing.md

Part of #4555
```release-note
NONE
```

Update testing docs.

---

cmd/experimental/kueue-viz/frontend/.gitignore

/kind cleanup
On a failed build, Cypress generates screenshots:
```
cmd/experimental/kueue-viz/frontend/cypress/screenshots
└── app.cy.js
├── Kueue Dashboard -- should navigate to cluster-queue and verify local queues (failed).png
├── Kueue Dashboard -- should navigate to resource-flavors and verify table content (failed).png
└── Kueue Dashboard -- should verify cohort link and navigate to cohorts page (failed).png
```
We should ignore this directory to prevent accidentally adding these files to git.
Fixes #
```release-note
NONE
```

Ignore cypress screenshots.

---

apis/kueue/v1alpha1/cohort_types.go
apis/kueue/v1beta1/clusterqueue_types.go
apis/kueue/v1beta1/fairsharing_types.go
charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
site/content/en/docs/reference/kueue-alpha.v1alpha1.md
site/content/en/docs/reference/kueue.v1beta1.md

I added FairSharingStatus API documentation to Cohort and ClusterQueue APsI.
Fixes #
```release-note
NONE
```

Add FairsharingStatus API documentation to Cohort and ClusterQueue

---

hack/e2e-kueueviz-backend.sh
hack/e2e-kueueviz-frontend.sh
hack/e2e-kueueviz-local.sh

/kind cleanup
Add License prefix for KueueViz sh files.
Fixes #
```release-note
NONE
```

Add License prefix for KueueViz sh files.

---

cloudbuild.yaml

/kind bug
We have an issue in post-kueue-push-images:
```
make: *** No rule to make target 'kueue-viz-image-push'.  Stop.
ERROR
ERROR: build step 0 "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240718-5ef92b5c36" failed: step exited with non-zero status: 2
```
It happens after https://github.com/kubernetes-sigs/kueue/pull/4753.
Fixes #
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-kueue-push-images/1904115121601384448
```release-note
NONE
```

Fix post-kueue-push-images.

---

cmd/kueueviz/frontend/src/App.css
cmd/kueueviz/frontend/src/ClusterQueueDetail.jsx
cmd/kueueviz/frontend/src/ClusterQueues.jsx
cmd/kueueviz/frontend/src/CohortDetail.jsx
cmd/kueueviz/frontend/src/Cohorts.jsx
cmd/kueueviz/frontend/src/Dashboard.jsx
cmd/kueueviz/frontend/src/ErrorMessage.jsx
cmd/kueueviz/frontend/src/LocalQueueDetail.jsx
cmd/kueueviz/frontend/src/LocalQueues.jsx
cmd/kueueviz/frontend/src/ResourceFlavorDetail.jsx
cmd/kueueviz/frontend/src/ResourceFlavors.jsx
cmd/kueueviz/frontend/src/WorkloadDetail.jsx
cmd/kueueviz/frontend/src/Workloads.jsx
cmd/kueueviz/frontend/src/WorkloadsList.jsx
cmd/kueueviz/frontend/src/useWebSocket.js

/kind cleanup
Fixes https://github.com/kubernetes-sigs/kueue/issues/4052
```release-note
NONE
```

Cleaner and more detailed error message for kueueviz frontend

---

cmd/kueueviz/README.md

https://github.com/kubernetes-sigs/kueue/blob/main/cmd/kueueviz/assets/kueueviz.png
Fixes None
```release-note
None
```

update kueueviz dashboard image path

---

Makefile
cmd/kueueviz/INSTALL.md

Generates kueueviz.yaml artifact that allows installation of kueueviz using:
```
kubectl create -f artifacts/kueueviz.yaml
```
/kind feature
Generates kueueviz.yaml artifact that allows installation of kueueviz using:
```
kubectl create -f artifacts/kueueviz.yaml
```
Fixes #
```release-note
NONE
```

Generates kueueviz.yaml artifact

---

charts/kueue/README.md

/kind documentatoin
Fixes #4774
```release-note
```

use official helm release instead of staging

---

test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
test/util/util_scheduling.go

/kind cleanup
Prep for #4809, so we can reuse these utils in non-FairSharing integration tests
```release-note
NONE
```

Move Integ Test Helpers from FairSharing to Util

---

test/e2e/singlecluster/metrics_test.go

/kind cleanup
Make it more clear which line is failing 
```release-note
NONE
```

Add Offset to Metric E2E Test Assertion

---

CHANGELOG/CHANGELOG-0.10.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4816
```release-note
NONE
```

Prepare for release v0.10.4

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part-of https://github.com/kubernetes-sigs/kueue/issues/4817
```release-note
NONE
```

Prepare for release v0.11.2

---

CHANGELOG/CHANGELOG-0.10.md

/kind cleanup
Part of #4816
```release-note
NONE
```

Update CHANGELOG after v0.10.4

---

cmd/kueueviz/frontend/package.json

/kind cleanup
Bump mui packages from 6.4.9 to 7.0.1 in /cmd/kueueviz/frontend 
Fixes #
Manual fix for https://github.com/kubernetes-sigs/kueue/pull/4833 and https://github.com/kubernetes-sigs/kueue/pull/4832.
```release-note
NONE
```

Bump mui packages from 6.4.9 to 7.0.1 in /cmd/kueueviz/frontend 

---

pkg/workload/resources.go

docs: fix typo in error message

---

charts/kueue/templates/rbac/topology_editor_role.yaml
charts/kueue/templates/rbac/topology_viewer_role.yaml
config/alpha-enabled/kustomization.yaml
config/components/rbac/kustomization.yaml
config/components/rbac/topology_editor_role.yaml
config/components/rbac/topology_viewer_role.yaml

Fixes #4831 
```release-note
Fix RBAC configuration for the Topology API to allow reading and editing by the service accounts using the Kueue Batch Admin role.
```

add rbac for topologies

---

site/content/en/docs/tasks/manage/setup_multikueue.md

As discussed in the community meeting, add Open Cluster Management MultiKueue solution link to the Kueue doc. 
Fixes #
```release-note
NONE
```

add Open Cluster Management MultiKueue solution link to the doc

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4878 
```release-note
NONE
```

Prepare for v0.11.3

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #4878 
```release-note
NONE
```

Update main after v0.11.3

---

pkg/controller/jobframework/base_webhook_test.go
pkg/controller/jobs/appwrapper/appwrapper_controller.go
pkg/resources/requests.go
pkg/scheduler/fair_sharing_iterator.go
pkg/scheduler/flavorassigner/flavorassigner.go
pkg/workload/workload.go

/kind cleanup
Use the same receiver name.
Fixes #
```release-note
NONE
```

Use the same receiver name.

---

hack/e2e-common.sh

/kind cleanup
Change image tag search pattern for the Kubeflow.
This will also change in the 1.9.1, from `kubeflow/training-operator` to `ghcr.io/kubeflow/training-v1/training-operator`.
Thus require change from exactly match to contains.
Relates to https://github.com/kubernetes-sigs/kueue/pull/4836
```release-note
NONE
```

[Cleanup] Change image tag search pattern

---

charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_multikueueconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_provisioningrequestconfigs.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloadpriorityclasses.yaml
charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
config/components/crd/bases/kueue.x-k8s.io_multikueueconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_provisioningrequestconfigs.yaml
config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
config/components/crd/bases/kueue.x-k8s.io_workloadpriorityclasses.yaml
config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
hack/internal/tools/go.mod
hack/internal/tools/go.sum

/kind cleanup
Bump sigs.k8s.io/controller-tools from 0.17.2 to 0.17.3 in /hack/internal/tools
Fixes #
Original PR https://github.com/kubernetes-sigs/kueue/pull/4883.
```release-note
NONE
```

Bump sigs.k8s.io/controller-tools from 0.17.2 to 0.17.3 in /hack/internal/tools

---

site/content/en/docs/tasks/run/appwrappers.md
site/content/en/docs/tasks/run/external_workloads/wrapped_custom_workload.md
site/static/examples/appwrapper/deployment-sample.yaml
site/static/examples/appwrapper/leaderworkerset-sample.yaml
site/static/examples/appwrapper/pytorch-sample.yaml

Add AppWrapper with Deployment example.
Fixes #
```release-note
NONE
```

Add AppWrapper with Deployment example.

---

Makefile

/kind cleanup
Helm charts can break without issues.
We should have a step in our verify that atleast makes sure there is nothing completely wrong.
We run template on a configuration options that can cause different branching.
Fixes #
```release-note
NONE
```

add helm verify step to confirm charts render correctly

---

pkg/scheduler/fair_sharing_iterator.go

/kind cleanup
Simplify
Fixes #
```release-note
NONE
```

Use SimulateUsageAddition in FairSharingIterator

---

go.mod
go.sum
vendor/github.com/project-codeflare/appwrapper/api/v1beta2/appwrapper_types.go
vendor/modules.txt

/kind cleanup
Bumps AppWrapper version from 1.1.1 to 1.1.2
```release-note
NONE
```

bump AppWrapper version from v1.1.1 to v1.1.2

---

Makefile

/kind cleanup
Add helm lint and smoke test for `make verify` to catch potential helm bugs
Fixes #
```release-note
NONE
```

[release-0.11]: Fix helm verify release 0 11

---

site/content/en/docs/talks_and_presentations/_index.md

Reformats the talk/presentation page to include sched links in addition to direct YouTube links.
If we like this changed format, I'll adjust #4902 to use the same style
```release-note
NONE
```

Include sched links in talks/presentation page

---

charts/kueue/templates/certmanager/certificatemetrics.yaml
config/components/certmanager/certificate-metrics.yaml
config/default/kustomization.yaml
test/e2e/certmanager/certmanager_test.go
test/e2e/certmanager/metrics_test.go
test/e2e/certmanager/suite_test.go
test/e2e/config/certmanager/cert_metrics_manager_patch.yaml
test/e2e/config/certmanager/controller_manager_config.yaml
test/e2e/config/certmanager/kustomization.yaml
test/e2e/config/certmanager/mutating_webhookcainjection_patch.yaml
test/e2e/config/certmanager/validating_webhookcainjection_patch.yaml

/kind cleanup
/kind bugfix
Fixes #https://github.com/kubernetes-sigs/kueue/issues/4164
Addresses https://github.com/kubernetes-sigs/kueue/issues/4164#issuecomment-2734285266
```release-note
cert-manager: allow for external self-signed certificates for the metrics endpoint.
```

certmanager: add test to curl metrics data using certs

---

hack/push-chart.sh

/kind bug
This fixes an inconsistency between Helm chart version in OCI registry and version reported by the chart metadata (`Chart.yaml`)
Fixes #4928 
Tested locally
* comment the last line of the script (to prevent pushing to registry)
* run `./hack/push-chart.sh`
* go to `bin`
* extract `kueue-0.11.3.tgz`
* `cat kueue/Chart.yaml`
```
> cat Chart.yaml
```yaml
apiVersion: v2
appVersion: v0.11.3-dirty
description: Kueue is a set of APIs and controller for job queueing. It is a job-level
manager that decides when a job should be admitted to start (as in pods can be created)
and when it should stop (as in active pods should be deleted).
name: kueue
type: application
version: 0.11.3-dirty
```
No: the chart version reported in the registry stays the same (no `v` prefix); only the chart …
```

Helm: ensure Chart version matches version in registry

---

pkg/controller/core/core.go
pkg/features/kube_features.go

/kind cleanup
I updated the HierarchicalCohorts feature gate in the followings:
1. FG owner should be feature owner
2. Fixed a typo for `HierarchicalCohorts`
3. Fixed the FG introduced versions.
Fixes #
```release-note
NONE
```

Fix HierarchicalCohorts feature gate

---

hack/push-chart.sh

Follow-up of #4929 for 0.10
```release-note
NONE
```

[release-0.10] Helm: ensure Chart version matches version in registry

---

test/e2e/tas/leaderworkerset_test.go

/kind bug
/kind flake
Fix assignment verification in the LeaderWorkerSet test.
Fixes #
Follow up fix for https://github.com/kubernetes-sigs/kueue/pull/4790#issuecomment-2809222377.
```release-note
NONE
```

Fix assignment verification in the LeaderWorkerSet test.

---

pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
pkg/scheduler/preemption/fairsharing/target.go

/kind cleanup
```release-note
NONE
```

Fair Sharing Preemption - Small Cleanup

---

pkg/controller/jobframework/integrationmanager.go
pkg/controller/jobframework/integrationmanager_test.go
pkg/controller/jobs/appwrapper/appwrapper_controller.go
pkg/controller/jobs/deployment/deployment_controller.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go
pkg/controller/jobs/statefulset/statefulset_controller.go

/kind cleanup
Remove IsManagingObjectsOwner from IntegrationCallbacks.
Fixes #4940
```release-note
NONE
```

Remove IsManagingObjectsOwner from IntegrationCallbacks.

---

site/content/en/docs/concepts/multikueue.md
site/content/en/docs/tasks/run/multikueue/plain_pods.md

Mention support of pod groups for the MultiKueue.
Fixes #4719
```release-note
NONE
```

[Docs] Update MultiKueue documentation for pod groups

---

site/content/en/docs/tasks/run/external_workloads/argo_workflow.md

Fixes a typo in docs
```release-note
NONE
```

Fix tiny typo in docs

---

site/content/en/docs/tasks/run/rayclusters.md
site/content/en/docs/tasks/run/rayjobs.md

[KubeRay GH pages](https://ray-project.github.io/kuberay/) have been deprecated for years, and all documentation has been moved to the Ray website. This PR replaces links to deprecated KubeRay GitHub pages with links to the Ray docs.
```release-note
NONE
```

[Doc][Ray] Replace links to deprecated KubeRay GitHub pages with links to the Ray docs

---

site/content/en/docs/talks_and_presentations/_index.md

Adds KubeConEU 2025 talks to website
```release-note
NONE
```

Add KubeConEU'25 presentations

---

Makefile-test.mk

/kind cleanup
Remove kueuectl from test-multikueue-integration.
Fixes #
We don't use kueuectl in multikueue integration tests.
```release-note
NONE
```

Remove kueuectl from test-multikueue-integration.

---

README.md

Update Production Readiness status.
Fixes #
```release-note
NONE
```

Update Production Readiness status.

---

site/content/en/docs/talks_and_presentations/_index.md

Fixes #
```release-note
NONE
```

Add a KubeCon talk to the Kueue docs

---

CHANGELOG/CHANGELOG-0.10.md

Part-of https://github.com/kubernetes-sigs/kueue/issues/4997
```release-note
NONE
```

Update 0.10.5 release-note for preparation

---

CHANGELOG/CHANGELOG-0.11.md

Part-of https://github.com/kubernetes-sigs/kueue/issues/4996
```release-note
NONE
```

Update v0.11.4 release-note for preparation

---

CHANGELOG/CHANGELOG-0.11.md

Fixes #
```release-note
NONE
```

Remove duplicated release note for v0.11.4

---

Makefile-test.mk
hack/e2e-common.sh
hack/e2e-kueueviz-backend.sh
hack/e2e-kueueviz-local.sh

/kind bug
Kueue-viz was pulling images directly from staging repo and not using the built image in the PR.
Fixes #
```release-note
NONE
```

Use locally built kind images for kueue-viz e2e tests

---

hack/push-chart.sh

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/4997
Part of https://github.com/kubernetes-sigs/kueue/issues/4996
The `GIT_TAG` has date and hash as described in https://github.com/kubernetes-sigs/kueue/blob/370c547f017568998324631359331e5012b9ce42/cloudbuild.yaml#L22-L24
However, we want to retrieve the semantic versioning.
```release-note
NONE
```

Use EXTRA_TAG for Helm App version if it is semantic versioning

---

CHANGELOG/CHANGELOG-0.10.md

/kind cleanup
Part of  #4997
```release-note
NONE
```

Update CHANGELOG after v0.10.5

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

Fixes #
```release-note
NONE
```

Update the latest version with v0.11.4

---

Dockerfile

/kind cleanup
Kueue is based on go 1.24.0 as specified in the go.mod file, so we should also bump the version in the Dockerfile.
Fixes #
```release-note
NONE
```

Bump go version in Dockerfile

---

charts/kueue/templates/rbac/topology_editor_role.yaml
charts/kueue/templates/rbac/topology_viewer_role.yaml
config/components/rbac/topology_editor_role.yaml
config/components/rbac/topology_viewer_role.yaml

/kind bug
ClusterRole generated with current templates does not seem to work correctly due to singular form in the rbac.
Permission issue with topology when using "kube-batch-admin-role":
```text
Error from server (Forbidden): topologies.kueue.x-k8s.io "example-cq" is forbidden: User "system:serviceaccount:test-ns:test-sa" cannot patch resource "topologies" in API group "kueue.x-k8s.io" at the cluster scope
```
```release-note
Fix RBAC configuration for the Topology API
```

Fix topologies rbac to specify resource in plural form

---

Makefile-test.mk

/kind cleanup
Remove FORCE target.
Fixes #
```release-note
NONE
```

Remove FORCE target.

---

Makefile-test.mk

/kind cleanup
Use setup-e2e-env target for all e2e tests.
Fixes #
```release-note
NONE
```

Use setup-e2e-env target for all e2e tests.

---

hack/e2e-test.sh
hack/multikueue-e2e-test.sh

/kind cleanup
Change E2E_RUN_ONLY_ENV read argument to "-p" to allow to display prompt,
"-r" does not work.
```release-note
NONE
```

[Cleanup] Change E2E_RUN_ONLY_ENV read argument to -p

---

pkg/cache/snapshot.go
pkg/cache/tas_flavor.go

/kind cleanup
A few things I noticed when reading code
```release-note
NONE
```

Cache - Small Cleanup

---

test/util/e2e.go

/kind cleanup
Export kind logs in the CustomConfig e2e tests before each restart to preserve logs from the previous version, before the pods are terminated.
Fixes #5164
```release-note
NONE
```

Export kind logs in the CustomConfig e2e tests before each restart

---

.gitignore
hack/get_build_logs.sh

/kind feature
Our CI produces a lot of logs, sometimes in vast structures of folders.
It is cumbersome to click on each to do the search for specific strings.
This script allows you to download all the artefacts from the CI job
and let you search required strings in the comfort of your IDE.
```release-note
NONE
```

[Feature] [Tool] Script to download logs/artifacts from the CI job.

---

test/e2e/singlecluster/deployment_test.go

/kind bug
/kind flake
Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.
Fixes #5161
The problem is that sometimes workloads don’t have enough time to reach QuotaReservation=false (which we're checking below) after the pods running. We should use `gomega.Eventually` to ensure this condition is met.
```release-note
NONE
```

Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.

---

pkg/scheduler/preemption/preemption_test.go

/kind cleanup
Fixing [#4961](https://github.com/kubernetes-sigs/kueue/issues/4961#issuecomment-2853918711) also fixed a bug where Cohorts/ClusterQueues with weight 0 couldn't reclaim their nominal quota.
We add some unit tests to cover this behavior. I tested that these new tests fail before #4962
Fixes #
```release-note
NONE
```

[Tests] Reclaim Nominal Quota with Zero Weight

---

CHANGELOG/CHANGELOG-0.11.md

Fixes #
```release-note
NONE
```

Update changelog about corrupted 0.11.x (x<=2)

---

site/go.mod
site/go.sum

/kind cleanup
Bump github.com/google/docsy from v0.10.0 to v0.11.0
Fixes #
```release-note
NONE
```

Bump github.com/google/docsy from v0.10.0 to v0.11.0

---

Dockerfile
Makefile
cloudbuild.yaml

/kind cleanup
1. Corrects some misconceptions in the build comments
2. Fixes multi-arch build to use the correct base image. 
- The previous build "worked" because the base image is all static files, but it will have the metadata for the host platform instead of the target platform. Some container runtime builds out there may have rejected this image.
3. Avoid depending on implicit copy relative path while using explicit entrypoint full path
4. Optimizes iterative build caching for the docker image
5. Fixes development / kind image targets to build for `linux/$(go env GOARCH)` instead of `linux/amd64`, this will work on amd64 or arm64 currently.
Fixes #
```release-note
NONE
```
(I don't know if any of these would merit release notes, if you'd like to let developers know about the makefile …

build cleanup

---

Makefile
cmd/kueueviz/backend/handlers/cluster_queues.go
cmd/kueueviz/backend/handlers/handlers.go
cmd/kueueviz/backend/handlers/local_queues.go
cmd/kueueviz/backend/handlers/resource_flavors.go
cmd/kueueviz/backend/handlers/websocket_handler.go
cmd/kueueviz/backend/handlers/workloads_dashboard.go
cmd/kueueviz/backend/main.go
hack/internal/tools/ginkgo-top/ginkgo-top.go
hack/internal/tools/pinversion.go

/kind cleanup
Currently, we only check the main .go files and exclude child modules. This change allows us to include and check child modules as well.
Fixes #
```release-note
NONE
```

Include child modules in golangci-lint.

---

Dockerfile

/kind cleanup
Follow-up to https://github.com/kubernetes-sigs/kueue/pull/5193#discussion_r2078913335
Simplifies and improves logging for the image build.
Fixes #
```release-note
NONE
```

dockerfile: drop redundant GOOS=linux and let buildx template the go env

---

.dockerignore

/kind cleanup
1. Makes `.dockerignore` a regular file instead of a symlink to `.gitignore`
2. `.dockerignore`s a lot of source files in the ~5MB range that are not used in docker images AFAICT.
Fixes #
```shell
$ for d in site keps charts .github .openvex; do du -h -d0 $d; done
2.4M    site
1.0M    keps
1.1M    charts
48K    .github
8.0K    .openvex
```
```release-note
NONE
```

split gitignore and dockerignore, dockerignore a few MB of source files

---

pkg/scheduler/scheduler.go

/kind bug
/kind cleanup
Fixes #
Follow up to https://github.com/kubernetes-sigs/kueue/pull/5138
```release-note
NONE
```

Follow up on scheduler panic fix to improve logging

---

.dockerignore
Dockerfile
Makefile
Makefile-test.mk
pkg/version/version.go

/kind cleanup
Add GIT_TAG and GIT_COMMIT args on Dockerfile to avoid copying .git directory and .gitignore file.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5206#discussion_r2080445556.
```release-note
NONE
```

Add GIT_TAG and GIT_COMMIT args on Dockerfile.

---

site/content/en/docs/reference/labels-and-annotations.md

Relates to  #4446
```release-note
NONE
```

[Site] Add 'kueue.x-k8s.io/podset' label to the site

---

pkg/controller/jobframework/reconciler.go
pkg/controller/jobframework/validation.go
pkg/controller/jobs/deployment/deployment_webhook.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go
pkg/controller/jobs/statefulset/statefulset_webhook.go
test/e2e/singlecluster/e2e_test.go

/kind bug
Follow-up of #5197.
See: https://github.com/kubernetes-sigs/kueue/pull/5197#discussion_r2086735190.
Relates to #5197
```release-note
NONE
```

Do not allow removal of workload priority

---

cmd/kueueviz/OWNERS
test/e2e/kueueviz/OWNERS

What this PR does / why we need it:
I believe that I've met all of the requirements, and would like to self-nominate as a Kueue Reviewer.

Self-nominate akram as reviewer for kueueviz code and tests

---

pkg/controller/jobframework/tas.go
pkg/controller/jobframework/tas_validation.go
pkg/controller/jobs/appwrapper/appwrapper_controller.go
pkg/controller/jobs/job/job_controller.go
pkg/controller/jobs/jobset/jobset_controller.go
pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go
pkg/controller/jobs/mpijob/mpijob_controller.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/jobs/raycluster/raycluster_controller.go
pkg/controller/jobs/rayjob/rayjob_controller.go

/kind cleanup
Allow us to statically analyze which controllers are using `PodIndexLabel` and `SubGroup`
Fixes #
```release-note
NONE
```

TAS/Controllers - Small Cleanup

---

charts/kueue/templates/kueueviz/backend-deployment.yaml
charts/kueue/templates/kueueviz/frontend-deployment.yaml
config/components/kueueviz/backend-deployment.yaml
config/components/kueueviz/frontend-deployment.yaml

/kind bug
Specifying limits & requests is a good practice in k8s. Otherwise the container may cause distruptions of other containers.
Also, it would be harder to introduce the resource requests in the future, as this could be considered a breaking change for some users.
Fixes #
I'm not setting release note, because KueueViz hasn't been released yet.
```release-note
NONE
```

Specify resource requests and limits for KueueViz containers

---

Makefile
config/components/kueueviz/backend-deployment.yaml
config/components/kueueviz/frontend-deployment.yaml
config/components/kueueviz/kustomization.yaml

/kind bug
Fixes #
I would like to test it with RC1.
```release-note
NONE
```

Fix tagging of the images for KueueViz

---

hack/push-chart.sh

/kind bug
Fixes #
```release-note
NONE
```

Fix tagging of release candidate images for helm

---

site/static/examples/tas/sample-queues.yaml

- Add LQ that is referenced in tas example job
- Aligns rf nodeSelector with `hack/tas-kind-cluster.yaml` cluster
Fixes #
```release-note
NONE
```

Improve TAS example

---

config/components/kueueviz/frontend-deployment.yaml
config/components/kueueviz/kustomization.yaml

/kind cleanup
To make the formatting consistent with other yaml files. Also, my vs-code  constantly reformats the files. 
This will make future cherrypicks easier.
Fixes #
```release-note
NONE
```

Fix formatting of KueueViz config yamls

---

pkg/controller/tas/node_failure_controller.go
pkg/controller/tas/node_failure_controller_test.go

/kind cleanup
Small follow-up to #5272
Extract EvictWorkload to function, and reduce scope of several variables. 
Fixes #
```release-note
NONE
```

Extract EvictWorkload to Function

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/clusterqueue.go
pkg/cache/fair_sharing_test.go
pkg/cache/snapshot_test.go
pkg/controller/core/clusterqueue_controller_test.go
pkg/controller/core/localqueue_controller_test.go
pkg/controller/core/workload_controller.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind cleanup
Fixes #
Proposal addressing the question in comment:  https://github.com/kubernetes-sigs/kueue/pull/5276#discussion_r2104319714
```release-note
NONE
```

Use logger inside cache

---

CHANGELOG/CHANGELOG-0.12.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
config/components/manager/kustomization.yaml
site/hugo.toml

/kind cleanup
Part of #5265
```release-note
NONE
```

Prepare release v0.12.0

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #5233
```release-note
NONE
```

Prepare v0.11.5

---

CHANGELOG/CHANGELOG-0.12.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of #5265 
```release-note
NONE
```

Update main after v0.12.0

---

charts/kueue/values.yaml
config/components/manager/controller_manager_config.yaml

/kind cleanup
Adds commented AFS configuration to the Kueue's manifests, for the ease of use  
Fixes #
Tested manually e2e
```release-note
NONE
```

Add commented exemplary configuration to Kueue manifest

---

Makefile

/kind bug
Fix restoring of the image after the "artifacts" goal with custom `IMAGE_REGISTRY` used (as during the release process)
Fixes #
```release-note
NONE
```

Fix restoring of the image in artifacts goal

---

Makefile

/kind cleanup
Add generate-code target.
Fixes #5216
```release-note
NONE
```

Add generate-code target.

---

cmd/importer/util/util.go
pkg/cache/clusterqueue.go
pkg/cache/clusterqueue_snapshot.go
pkg/controller/core/clusterqueue_controller.go
pkg/controller/jobs/pod/pod_controller.go
pkg/controller/tas/topology_ungater.go
pkg/metrics/metrics_test.go
pkg/scheduler/flavorassigner/flavorassigner.go
pkg/util/heap/heap_test.go
pkg/util/maps/maps_test.go
pkg/util/testing/wrappers.go
pkg/util/testingjobs/node/wrappers.go
pkg/util/testingjobs/pod/wrappers.go
test/e2e/singlecluster/fair_sharing_test.go
test/integration/singlecluster/scheduler/preemption_test.go
test/integration/singlecluster/webhook/core/clusterqueue_test.go
test/integration/singlecluster/webhook/core/resourceflavor_test.go
test/performance/scheduler/runner/generator/generator.go

/kind cleanup
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./pkg/... ./test/... ./cmd/...
make lint-fix
```
Fixes #
```release-note
NONE
```

Modernize and lint-fix

---

charts/kueue/templates/rbac/cohort_editor_role.yaml
charts/kueue/templates/rbac/cohort_viewer_role.yaml
config/components/rbac/cohort_editor_role.yaml
config/components/rbac/cohort_viewer_role.yaml
config/components/rbac/kustomization.yaml

/kind cleanup
Provides RBAC permissions for the Cohort API to update & read by admins.
Fixes #[5275](https://github.com/kubernetes-sigs/kueue/issues/5275)
```release-note
RBAC permissions for the Cohort API to update & read by admins are now created out of the box.
```

Kueue should provide RBAC permissions for cohorts OOTB

---

pkg/cache/tas_flavor_snapshot.go

/kind cleanup
The current utils are a bit redundant.
Fixes #
```release-note
NONE
```

TAS: Simplify TAS profile selection utils

---

CHANGELOG/CHANGELOG-0.11.md

/kind cleanup
Part-of https://github.com/kubernetes-sigs/kueue/issues/5458
```release-note
NONE
```

Add v0.11.6 changelog

---

site/content/en/docs/concepts/cohort.md

Fixes #
```release-note
NONE
```

Doc: Fix a HC typo

---

Makefile
hack/helm-chart-package.sh

/kind cleanup
Commonize the Helm chart artifact generation process.
Fixes #
```release-note
NONE
```

Commonize the Helm chart artifact generation process.

---

Makefile
charts/kueue/templates/kueueviz/backend-deployment.yaml
charts/kueue/templates/kueueviz/frontend-deployment.yaml
charts/kueue/values.yaml
hack/helm-chart-package.sh
hack/processing-plan.yaml

/kind bug
Align the Helm configuration for the image of KueueViz with the main controller
Fixes #5398
````release-note
Helm: 
- Fixed KueueViz installation when enableKueueViz=true is set with default values.
- Split the image value into separate repository and tag fields for the KueueViz backend and frontend configurations. 
ACTION REQUIRED: Helm users need to replace KueueViz chart values in the following:
```diff
kueueViz:
backend:
-   image: xyz
+   image:
+     repository: xyz
+     tag: abc
frontend:
-   image: xyz
+   image:
+     repository: xyz
+     tag: abc
```
````

Align the Helm configuration for the image of KueueViz with the main controller

---

apis/config/v1beta1/defaults.go
apis/config/v1beta1/defaults_test.go

/kind cleanup
I simplified the zero value defaulting in Config API by Go standard [cmp.Or()](https://pkg.go.dev/cmp#Or).
Fixes #
```release-note
NONE
```

Simplify Kueue Config defaultings by cmp.Or()

---

.dockerignore
.gitignore

/kind cleanup
As described in Go references, we should not contain the go.work in git version management.
> It is generally inadvisable to commit go.work files into version control systems, for two reasons:
> 
> - A checked-in go.work file might override a developer’s own go.work file from a parent directory, causing confusion when their use directives don’t apply.
> - A checked-in go.work file may cause a continuous integration (CI) system to select and thus test the wrong versions of a module’s dependencies. CI systems should generally not be allowed to use the go.work file so that they can test the behavior of the module as it would be used when required by other modules, where a go.work file within the module has no effect.
https://go.dev/ref/mod#go-work-file
Fixes #
```release-note …
```

Exclude go.work from git management

---

site/content/en/docs/concepts/_index.md
site/content/en/docs/concepts/admission_fair_sharing.md
site/content/en/docs/concepts/fair_sharing.md
site/content/en/docs/installation/_index.md

Fixes #
```release-note
NONE
```

[AFS] Add documentation to Kueue website 

---

hack/helm-chart-package.sh

/kind bug
Change repo only for promoted images in helm chart package.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5521#issuecomment-2945166830.
```release-note
NONE
```

Change repo only for promoted images in helm chart package.

---

Makefile
cloudbuild.yaml

/kind cleanup
Remove IMAGE_EXTRA_TAG and use branch name instead.
Fixes #
```release-note
NONE
```

Remove IMAGE_EXTRA_TAG and use branch name instead.

---

charts/kueue/README.md

Update charts/kueue README.md.
Part of #5523
Follow up for https://github.com/kubernetes-sigs/kueue/issues/5523#issuecomment-2948366704.
```release-note
NONE
```

Update charts/kueue README.md.

---

hack/e2e-common.sh
hack/e2e-kueueviz-local.sh

/kind cleanup
Fix Makefile test-e2e-kueueviz-local target.
Fixes #
When running `make test-e2e-kueueviz-local`, I got an error:
```
hack/e2e-common.sh: line 244: cd: config/components/manager: No such file or directory
```
```release-note
NONE
```

Fix Makefile test-e2e-kueueviz-local target.

---

Makefile
Makefile-deps.mk
Makefile-test.mk

/kind cleanup
- Use `$(BIN_DIR)` instead of `$(PROJECT_DIR)/hack/internal/tools`
- Use `$(TOOLS_DIR)` instead of `$(PROJECT_DIR)/bin`
- Move `*_ROOT` variables from `Makefile-test.mk` to `Makefile-deps.mk`.
Fixes #5567
```release-note
NONE
```

Optimize Makefiles.

---

Makefile
Makefile-deps.mk
Makefile-test.mk

Cherry pick of #5569 on release-0.11.
#5569: Optimize Makefiles.
```release-note
NONE
```

Automated cherry pick of #5569: Optimize Makefiles.

---

Makefile
charts/kueue/Chart.yaml

/kind cleanup
Update Chart version on prepare release branch.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5641#discussion_r2145262171.
```release-note
NONE
```

Update Chart version on prepare release branch.

---

Makefile
Makefile-deps.mk
charts/kueue/README.md
charts/kueue/README.md.gotmpl
charts/kueue/values.yaml
hack/internal/tools/go.mod
hack/internal/tools/go.sum

Use helm-docs to generate README.md for Helm.
Fixes #5637
```release-note
NONE
```

Use helm-docs to generate README.md for Helm.

---

Dockerfile

In case the kueue image is built without using the
`image-build` from the Makefile, the following arg
would be evaluated as `CGO_ENABLED=`, without a value,
causing the kueue-controller-manager to fail with
`exec /manager: no such file or directory`. This commit
fixes the issue by ensuring that argument has a default value.
/kind bug
Fixes #
```release-note
NONE
```

Fix Dockerfile to work when not using Makefile

---

hack/e2e-kueueviz-local.sh

/kind cleanup
We should install node_modules packages automatically before running tests.
Fixes #
```release-note
NONE
```

[KueueViz] Install node_modules on running test-e2e-kueueviz-local target.

---

hack/e2e-kueueviz-local.sh

/kind cleanup
Remove the redundant headless flag to avoid warning:
```
npm warn Unknown cli config "--headless". This will stop working in the next major version of npm.
```
Fixes #
```release-note
NONE
```

[KueueViz] Remove the redundant headless flag.

---

pkg/cache/tas_flavor_snapshot.go

/kind cleanup
This is a follow-up PR for this PR: https://github.com/kubernetes-sigs/kueue/pull/5353. It includes part of the comments.
Related to: https://github.com/kubernetes-sigs/kueue/issues/5375
```release-note
NONE
```

Two-level scheduling follow up / Improve readability

---

cmd/kueueviz/INSTALL.md

I tried using it, but I need to run them with the namespace.
None
```release-note
NONE
```

kueueviz: Update  INSTALL.md

---

site/content/en/docs/tasks/manage/productization/_index.md

Add a recommended installation note to the Productionization page.
Fixes #5523
Follow up for https://github.com/kubernetes-sigs/kueue/issues/5523#issuecomment-2970644645.
```release-note
NONE
```

Add a recommended installation note to the Productionization page.

---

pkg/scheduler/scheduler.go

/kind cleanup
This indirection is hard to read
Fixes #
```release-note
NONE
```

Simplify scheduler.netUsage

---

site/content/en/docs/concepts/multikueue.md

`Plain Pods` and `Deployment` should be the same level as `batch/job`, `JobSet`, and `Kubeflow`.
Fixes #
```release-note
NONE
```

Doc: Fix MultiKueue supporting Jobs listing level

---

pkg/scheduler/flavorassigner/flavorassigner.go

/kind cleanup
Panic makes sense for enum conversion. However, the panic messages should be helpful.
Fixes #
```release-note
NONE
```

Make panic more infoamable

---

site/content/en/docs/tasks/run/multikueue/kubeflow.md
site/content/en/docs/tasks/run/multikueue/kuberay.md

Only those places use the `info` color as a Note in the entire documentation.
So, I replaced those with `primary`.
Fixes #
```release-note
NONE
```

Doc: Use the same primary color for Note

---

pkg/scheduler/scheduler_test.go

/kind cleanup
This is a follow up after #5698 to add tests which actually demonstrate the logic change (fail before that PR).
The new tests address all open comments in the original PR.
```release-note
NONE
```

Add unit tests for the improved accuracy of flavor assigner

---

Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
site/hugo.toml

Part-of: https://github.com/kubernetes-sigs/kueue/issues/5616
```release-note
NONE
```

Update main branch with the latest v0.12.3

---

site/content/en/docs/concepts/multikueue.md
site/content/en/docs/tasks/run/multikueue/appwrapper.md

AppWrapper integration also has MultiKueue support. 
```release-note
NONE
```

AppWrapper also supports MultiKueue

---

Makefile
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Fix KueueViz frontend version.
Fixes #
```release-note
NONE
```

Fix KueueViz frontend version.

---

.github/dependabot.yml

/kind cleanup
Confugure Dependabot for cypress dependencies.
Fixes #
```release-note
NONE
```

Confugure Dependabot for cypress dependencies.

---

cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json

/kind cleanup
Bump KueueViz frontend dependencies.
Fixes #
Manual fix for https://github.com/kubernetes-sigs/kueue/pull/5774.
```release-note
NONE
```

Bump KueueViz frontend dependencies.

---

cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json

/kind cleanup
Bump the mui-packages group in /cmd/kueueviz/frontend with 2 updates
Fixes #
```release-note
NONE
```

Bump the mui-packages group in /cmd/kueueviz/frontend with 2 updates

---

site/content/zh-CN/docs/installation/_index.md
site/content/zh-CN/docs/overview/_index.md

```bash
On branch docs/sync-zh-overview-and-installation
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
modified:   content/zh-CN/docs/installation/_index.md
modified:   content/zh-CN/docs/overview/_index.md
```
Fixes #
try to sync two pages to zh-cn.
Why did I submit 3 PRs?
I found and optimized the issues while translating.
However, from the perspective of a good PR, It's should be separated.
```release-note
NONE
```

[zh-cn] sync installation and overview

---

site/content/zh-CN/docs/adopters/index.md

Localize site/content/zh-CN/docs/adopters/index.md
Fixes #
```release-note
NONE
```

[zh-cn] Localize adopters

---

site/content/en/docs/concepts/multikueue.md

Revise the text to fix inconsistencies and improve clarity, while preserving the original meaning.
/kind cleanup
```release-note
NONE
```
[Current Website Page](https://kueue.sigs.k8s.io/docs/concepts/multikueue/) | [Preview](https://deploy-preview-5836--kubernetes-sigs-kueue.netlify.app/docs/concepts/multikueue/)

[Docs] Clean up concepts/multikueue.md

---

hack/e2e-common.sh

/kind cleanup
In some OSes and devices (for example, MacOS and zsh), bash parameter substitution hits a limit and is unable to run a replace procedure, resulting in an inability to run e2e tests locally. Replacing it with sed helps to improve compatibility.
```release-note
NONE
```

fix: use sed in e2e-common.sh build and deploy

---

keps/4136-admission-fair-sharing/README.md
keps/4136-admission-fair-sharing/kep.yaml

/kind bug
Discuss in KEP the risk and mitigation related to AFS
Part of #5339
```release-note
NONE
```

[AFS] Describe entry penalty in KEP

---

pkg/scheduler/scheduler.go

/kind cleanup
Improve code readability and simplify the admit logic.
Fixes #
```release-note
NONE
```

refactor(scheduler): extract workload admission metrics recording into separate methods

---

pkg/controller/admissionchecks/multikueue/multikueuecluster.go
pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go
pkg/controller/core/workload_controller.go

/kind bug
follow up: https://github.com/kubernetes-sigs/kueue/pull/5796
Fixes #
@tenzen-y 
```release-note
NONE
```

Fix unexpected issues caused by IgnoreNotFound-related changes

---

pkg/cache/tas_flavor_snapshot.go

/kind cleanup
To make the TAS logs less verbose.
Fixes #
```release-note
NONE
```

TAS: Specify and adjust logging levels

---

site/content/zh-CN/docs/concepts/local_queue.md

[Docs][zh-CN] Localize site/content/zh-CN/docs/concepts/local_queue.md
Fixes #
```release-note
NONE
```

[Docs][zh-CN] Localize local_queue.md

---

site/content/zh-CN/docs/concepts/fair_sharing.md

/language zh
[Docs][zh] Localize site/content/zh-CN/docs/concepts/fair_sharing.md
Fixes #
```release-note
NONE
```

[Docs][zh] Localize fair_sharing

---

Makefile
charts/kueue/README.md
charts/kueue/templates/kueueviz/backend-deployment.yaml
charts/kueue/templates/kueueviz/frontend-deployment.yaml
charts/kueue/templates/manager/manager.yaml
charts/kueue/tests/manager_test.yaml
charts/kueue/values.yaml
hack/processing-plan.yaml

/kind feature
fix for https://github.com/kubernetes-sigs/kueue/issues/5814
Fixes #5814
```release-note
Helm: support for specifying nodeSelector and tolerations for all Kueue components
```

helm: support for specifying nodeSelector and tolerations for all Kueue components

---

site/content/zh-CN/docs/tasks/manage/run_job_with_workload_priority.md

/language zh
[Docs][zh]Localize run_job_with_workload_priority.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize run_job_with_workload_priority.md

---

site/content/zh-CN/docs/tasks/dev/enabling_pprof_endpoints.md

/release-note-none
/language zh
Localize site/content/zh-CN/docs/tasks/dev/enabling_pprof_endpoints.md
Fixes #
```release-note
```

[Docs][zh]sync enabling_pprof_endpoints

---

site/content/zh-CN/docs/tasks/dev/develop-acc.md

/language zh
Localize site/content/zh-CN/docs/tasks/dev/develop-acc.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize develop-acc.md

---

.github/dependabot.yml
Makefile
hack/depcheck/Dockerfile
hack/depcheck/verify.sh
test/e2e/kueueviz/.dockerignore
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Add npm-depcheck Makefile target to find unused dependencies.
Fixes #
```release-note
NONE
```

Add npm-depcheck Makefile target.

---

site/content/zh-CN/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md

/language zh
[Docs][zh]Localize manage_jobs_without_queue_name
Fixes #
```release-note
NONE
```

[Docs][zh]Localize manage_jobs_without_queue_name

---

site/content/zh-CN/docs/tasks/manage/productization/cert_manager.md

/language zh
[Docs][zh]Localize site/content/zh-CN/docs/tasks/manage/productization/cert_manager.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize cert_manager.md

---

CHANGELOG/CHANGELOG-0.11.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
site/hugo.toml

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/5885
```release-note
NONE
```

Prepare v0.11.8 release

---

CHANGELOG/CHANGELOG-0.12.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part of #5884 
```release-note
NONE
```

Prepare v0.12.4

---

Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part #5884 
```release-note
NONE
```

Update main after v0.12.4

---

CHANGELOG/CHANGELOG-0.11.md

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/5885
```release-note
NONE
```

Add v0.11.8 changelog

---

CHANGELOG/CHANGELOG-0.12.md

/kind cleanup
Part of #5884
```release-note
NONE
```

Update CHANGELOG after v0.12.4

---

hack/e2e-common.sh
hack/multikueue-e2e-test.sh

/kind cleanup
Use trap to restore managers image in kueue_deploy.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5949#discussion_r2201435078.
```release-note
NONE
```

Use trap to restore managers image in kueue_deploy.

---

site/content/zh-CN/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md

/language zh
[Docs][zh]Localize pending_workloads_in_status
Fixes #
```release-note
NONE
```

[Docs][zh]Localize pending_workloads_in_status

---

test/e2e/tas/suite_test.go

/kind flake
TAS E2E test fails due to concurrent node changes.
Retry to patch if the other client update the resource.
Fixes #5772 
```release-note
NONE
```

[Flake] Update node resources with eventually

---

site/content/zh-CN/docs/installation/_index.md

Cleanup MultiplePreemptions and WorkloadResourceRequestsSummary feature gates.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5996.
```release-note
NONE
```

Cleanup MultiplePreemptions and WorkloadResourceRequestsSummary feature gates.

---

site/content/zh-CN/docs/concepts/workload_priority_class.md

Fixes #
```release-note
NONE
```

[zh] Sync site/content/zh-CN/docs/concepts/workload_priority_class.md to Chinese

---

site/content/zh-CN/docs/tasks/run/external_workloads/argo_workflow.md

/language zh
[Docs][zh]Localize site/content/zh-CN/docs/tasks/run/external_workloads/argo_workflow.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize argo_workflow.md

---

site/content/zh-CN/docs/tasks/run/jobs.md

/language zh
[zh] Sync docs/tasks/run/jobs.md to Chinese.
```release-note
NONE
```

[zh] Sync docs/tasks/run/jobs.md to Chinese.

---

pkg/scheduler/scheduler_test.go

/kind cleanup
Fixes #
```release-note
NONE
```

chore: wrapper objects should be built by Obj() function

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_version/_index.md

Fixes #
```release-note
NONE
```

[Docs][zh-cn] command kueuectl_version

---

site/content/zh-CN/docs/tasks/run/external_workloads/wrapped_custom_workload.md

/language zh
[Docs][zh]Localize  site/content/zh-CN/docs/tasks/run/external_workloads/wrapped_custom_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize wrapped_custom_workload.md

---

site/content/zh-CN/docs/tasks/run/external_workloads/flux_miniclusters.md

/language zh
[Docs][zh]Localize flux_miniclusters.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize flux_miniclusters.md

---

pkg/util/client/client.go

/kind cleanup
To avoid code duplication
Fixes #
```release-note
NONE
```

Cleanup patch handling by commonizing the code

---

pkg/controller/core/indexer/indexer.go
pkg/controller/jobframework/indexer.go
pkg/workloadslicing/workloadslicing.go
pkg/workloadslicing/workloadslicing_test.go

/kind cleanup
To remove the code and logic for indexing workloads per Job.
Follow up to  #5510
```release-note
NONE
```

Eliminate code duplication for indexing Workloads

---

pkg/util/client/client.go

/kind cleanup
Small cleanup. See https://github.com/kubernetes-sigs/kueue/pull/6159#discussion_r2227889989
Fixes #
```release-note
NONE
```

Refactor client.go Patch

---

site/content/zh-CN/docs/tasks/run/kubeflow/pytorchjobs.md

/language zh
[Docs][zh]Localize site/content/zh-CN/docs/tasks/run/kubeflow/pytorchjobs.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize pytorchjobs.md

---

site/content/zh-CN/docs/tasks/run/external_workloads/_index.md

/language zh
[Docs][zh] site/content/zh-CN/docs/tasks/run/external_workloads/_index.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize external_workloads/_index

---

site/content/zh-CN/docs/tasks/run/kubeflow/tfjobs.md

/language zh
[Docs][zh]Localize kubeflow/tfjobs.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kubeflow/tfjobs.md

---

pkg/cache/snapshot.go
pkg/queue/cluster_queue.go
pkg/queue/manager.go
pkg/scheduler/scheduler.go
pkg/workload/workload.go
test/integration/singlecluster/scheduler/fairsharing/suite_test.go

/kind cleanup
Follow-up of #5933 
Related to #5933 
```release-note
NONE
```

[AFS] Follow up -  Add entrance penalty

---

site/content/zh-CN/docs/tasks/run/rayjobs.md

/language zh
[Docs][zh]Localize rayjobs.md
```release-note
NONE
```

[Docs][zh]Localize rayjobs.md

---

site/content/zh-CN/docs/tasks/run/rayclusters.md

/language zh
[Docs][zh]Localize rayclusters.md
```release-note
NONE
```

[Docs][zh]Localize rayclusters.md

---

site/content/zh-CN/docs/tasks/run/kubeflow/jaxjobs.md

/language zh
[Docs][zh]Localize kubeflow/jaxjobs.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kubeflow/jaxjobs.md

---

site/content/zh-CN/docs/tasks/run/kubeflow/xgboostjobs.md

/language zh
[Docs][zh]Localize  site/content/zh-CN/docs/tasks/run/kubeflow/xgboostjobs.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kubeflow/xgboostjobs.md

---

CHANGELOG/CHANGELOG-0.13.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Fixes #
```release-note
NONE
```

Update main with the latest v0.13.0

---

site/content/zh-CN/docs/tasks/run/external_workloads/tektoncd.md

/language zh
[Docs][zh] site/content/zh-CN/docs/tasks/run/external_workloads/tektoncd.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize tektoncd.md

---

site/content/zh-CN/docs/tasks/manage/enable_kubeviz.md

/language zh
[zh] sync docs/task/manage/enable_kubeviz.md to Chinese.
```release-note
NONE
```

[zh] sync docs/task/manage/enable_kubeviz.md to Chinese.

---

pkg/workloadslicing/workloadslicing.go
pkg/workloadslicing/workloadslicing_test.go

/kind bug
**This PR addresses a regression introduced in [#6203](https://github.com/kubernetes-sigs/kueue/pull/6203)**
In the process of handling workload slice `creationTimestamp` collisions, the behavior of `FindNotFinishedWorkloads` was inadvertently altered. Instead of returning a **sorted list of active workload slices** (oldest first), the updated version returned **a single, and potentially incorrect, "old" workload slice**.
As a result, the regression extended beyond workloads with timestamp collisions and began affecting **any job reconciled in a transitional state**, where both an old and a pending new workload slice are present, **regardless of `creationTimestamp` values**.
This PR corrects the regression by restoring the original behavior of returning a sorted list of active …

Address workload-slice regression which may result in incorrect workload slice to job assignment.

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/_index.md

/language zh
[Docs][zh]Localize kueuectl_describe/_index.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_describe/_index.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_clusterqueue.md

/language zh
[Docs][zh]Localize kueuectl_describe/kueuectl_describe_clusterqueue.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_describe/kueuectl_describe_clusterqueue.md

---

site/content/en/docs/concepts/admission_fair_sharing.md

Updates AFS documentation.
Fixes #6249 
```release-note
NONE
```

AFS: Add explanation of entry penalty to documentation

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_resourceflavor.md

/language zh
[Docs][zh]Localize kueuectl_describe/kueuectl_describe_resourceflavor.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_describe/kueuectl_describe_resourceflavor.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_describe/kueuectl_describe_workload.md

/language zh
[Docs][zh]Localize kueuectl_describe/kueuectl_describe_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_describe/kueuectl_describe_workload.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_localqueue.md

/language zh
[Docs][zh]Localize kueuectl_edit/kueuectl_edit_localqueue.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_edit/kueuectl_edit_localqueue.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_resourceflavor.md

/language zh
[Docs][zh]Localize kueuectl_edit/kueuectl_edit_resourceflavor.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_edit/kueuectl_edit_resourceflavor.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_edit/kueuectl_edit_workload.md

/language zh
[Docs][zh]Localize kueuectl_edit/kueuectl_edit_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_edit/kueuectl_edit_workload.md

---

test/e2e/multikueue/e2e_test.go

/kind cleanup
To reduce code duplication
```release-note
NONE
```

[Cleanup] Unify function that checks no objects are left in the worker clusters

---

site/content/zh-CN/docs/tasks/run/multikueue/jobsets.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize jobsets.md

---

site/content/zh-CN/docs/tasks/run/multikueue/kubeflow.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kubeflow.md

---

site/content/en/docs/concepts/multikueue.md

Update documentation related to the MultiKueue Dispatcher.
Fixes #6202
```release-note
NONE
```

[website] Update MultiKueue Dispatcher API site

---

site/content/zh-CN/docs/tasks/run/multikueue/job.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize multikueue/job.md

---

CHANGELOG/CHANGELOG-0.13.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/6291
```release-note
NONE
```

Prepare release v0.13.1

---

CHANGELOG/CHANGELOG-0.12.md

/kind cleanup
part of #6292 
```release-note
NONE
```

Update CHANGELOG after v0.12.6

---

CHANGELOG/CHANGELOG-0.13.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/6291
```release-note
NONE
```

Update main with the latest v0.13.1

---

test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go

/kind cleanup
Cleanup provisioning integration tests.
Part of #6331
```release-note
NONE
```

Cleanup provisioning integration tests.

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/_index.md

/language zh
[Docs][zh]Localize kueuectl_patch/_index.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_patch/_index.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_workload.md

/language zh
[Docs][zh]Localize kueuectl_get_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_get_workload.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_list/_index.md

/language zh
[Docs][zh]Localize kueuectl_list/_index.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_list/_index.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_localqueue.md

/language zh
[Docs][zh]Localize kueuectl_get_localqueue.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_get_localqueue.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_resourceflavor.md

/language zh
[Docs][zh]Localize kueuectl_get_resourceflavor.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_get_resourceflavor.md

---

cmd/kueueviz/backend/handlers/api_handlers.go
cmd/kueueviz/backend/handlers/cluster_queues.go
cmd/kueueviz/backend/handlers/cohorts.go
cmd/kueueviz/backend/handlers/local_queue_workloads.go
cmd/kueueviz/backend/handlers/local_queues.go
cmd/kueueviz/backend/handlers/namespaces.go
cmd/kueueviz/backend/handlers/resource_flavors.go
cmd/kueueviz/backend/handlers/websocket_handler.go
cmd/kueueviz/backend/handlers/workloads.go
cmd/kueueviz/backend/handlers/workloads_dashboard.go

/kind cleanup
Use request context instead of context.TODO().
Fixes #
```release-note
NONE
```

Use request context instead of context.TODO().

---

pkg/features/kube_features.go
pkg/scheduler/flavorassigner/flavorassigner.go

/kind cleanup
I replaced typos, "fungiblity" with "fungibility".
Fixes #
```release-note
NONE
```

chore: Fix a typo for fungibility

---

site/content/zh-CN/docs/tasks/run/leaderworkerset.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize leaderworkerset.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_get/kueuectl_get_clusterqueue.md

/language zh
[Docs][zh]Localize kueuectl_get_clusterqueue.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_get_clusterqueue.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_resourceflavor.md

/language zh
[Docs][zh]Localize kueuectl_patch_resourceflavor.md
Fixes #
```release-note
```

[Docs][zh]Localize kueuectl_patch_resourceflavor.md

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_patch/kueuectl_patch_workload.md

/language zh
[Docs][zh]Localize kueuectl_patch_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_patch_workload.md

---

pkg/controller/core/workload_controller.go
pkg/controller/tas/node_failure_controller.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/scheduler.go
pkg/workload/admissionchecks.go
pkg/workload/workload.go

/kind bug
/kind cleanup
Fixes #6296
```release-note
NONE
```

Commonize workload eviction and fix accounting for related metrics

---

hack/e2e-kueueviz-local.sh

/kind cleanup
Support E2E_RUN_ONLY_ENV for kueueviz e2e tests.
Fixes #
```release-note
NONE
```

Support E2E_RUN_ONLY_ENV for kueueviz e2e tests.

---

hack/e2e-test.sh
hack/multikueue-e2e-test.sh
site/content/en/docs/contribution_guidelines/testing.md
site/content/zh-CN/docs/contribution_guidelines/testing.md

Ask for cleanup if E2E_RUN_ONLY_ENV=true.
Fixes #
For single cluster:
```
Do you want to cleanup? [Y/n] n
Skipping cleanup for kind cluster.
Kind cluster cleanup:
kind delete cluster --name kind
```
For multikueue:
```
Do you want to cleanup? [Y/n] n
Skipping cleanup for kind clusters.
Manager kind cluster cleanup:
kind delete cluster --name kind-manager
Worker1 kind cluster cleanup:
kind delete cluster --name kind-worker1
Worker2 kind cluster cleanup:
kind delete cluster --name kind-worker2
```
```release-note
NONE
```

Ask for cleanup if E2E_RUN_ONLY_ENV=true.

---

test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go

/kind bug
When creating CQ in tests we also created LQ with the same name. This PR deletes those redundant LQs, as they were not used and created noise in the logs 
Fixes #6416 
```release-note
NONE
```

[AFS] Get rid of creating redundant LQs in integration tests

---

pkg/cache/cache_test.go
pkg/cache/clusterqueue_test.go
pkg/cache/fair_sharing_test.go
pkg/cache/resource_node_test.go
pkg/cache/snapshot_test.go
pkg/controller/core/cohort_controller_test.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/scheduler_test.go
test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
test/integration/singlecluster/scheduler/scheduler_test.go
test/integration/singlecluster/webhook/core/cohort_test.go

/kind cleanup
Fixes #
```release-note
NONE
```

chore: FlavorQuotas testing wrapper should be built by Obj()

---

README.md

/kind cleanup
Fix the links after https://github.com/cncf/artwork/pull/545 moved them.
```release-note
NONE
```

Update the logos links

---

README.md

/kind cleanup
- because Aldo who is the original owner of the docs is no longer maintaining the project, but still occasionally receives access requests
- the docs are quite outdated already
- we have much richer documentation + presentations than in the past
Fixes #
```release-note
NONE
```

Drop the Architecture README section

---

hack/releasing/sync-notes.sh

/kind cleanup
Prepare ./hack/releasing/sync-notes.sh to automatically sync release notes to the issue.
Usage:
```
./hack/releasing/sync-notes.sh <version>
Sync notes on the release issue
Example:
./hack/releasing/sync-notes.sh v0.13.2
```
Part of #6288
```release-note
NONE
```

Prepare ./hack/releasing/sync-notes.sh.

---

CHANGELOG/CHANGELOG-0.12.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part of https://github.com/kubernetes-sigs/kueue/issues/6413
```release-note
NONE
```

Prepare release v0.12.7

---

CHANGELOG/CHANGELOG-0.12.md

I updated only Changelog for v0.12.7 since the latest patch version is v0.13.2.
Part of https://github.com/kubernetes-sigs/kueue/issues/6413
```release-note
NONE
```

Add v0.12.7 changelog to the main branch

---

site/content/zh-CN/docs/tasks/run/appwrappers.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize appwrappers.md

---

site/content/zh-CN/docs/tasks/manage/administer_cluster_quotas.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize administer_cluster_quotas.md

---

test/e2e/multikueue/e2e_test.go

/kind cleanup
Use wrapper which additionally has extended timeout.
```release-note
NONE
```

[Cleanup] Use wrapper for workload admission

---

site/content/en/docs/concepts/_index.md
site/content/en/docs/concepts/elastic_workload.md
site/content/en/docs/tasks/run/jobs.md
site/static/examples/jobs/sample-scalable-job.yaml

This PR updates Kueue documentation to include ElasticJobs Concept and elastic job support in `batchv1/Job`
Fixes #6349
```release-note
NONE
```

Add initial documentation for ElastiJobs - batchv1/Job

---

test/util/e2e.go

/kind cleanup
Those functions serves different purposes and they are not always needed together e.g. would be beneficial [here](https://github.com/kubernetes-sigs/kueue/pull/6466/files#r2257041119)
```release-note
NONE
```

[Cleanup] Separate deploy availability and check no restarts

---

OWNERS
pkg/cache/OWNERS
pkg/hierarchy/OWNERS
pkg/resources/OWNERS
pkg/scheduler/OWNERS
pkg/util/OWNERS
test/OWNERS

Follow-up to https://github.com/kubernetes-sigs/kueue/pull/5269. As of 2025-08-12 I've reviewed [75 PRs](https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Agabesaba+-author%3Agabesaba+) and released v0.13.2 (https://github.com/kubernetes-sigs/kueue/issues/6414)
**Contributions:**
- #79
- #3759
- #3547
- #2811
- #2641
**Reviews:**
- #4806
- #5272
- #5353
- #4252
- #4687
Fixes #
```release-note
NONE
```

Self-Nominate gabesaba@ as Full Approver

---

site/content/zh-CN/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload.md

/language zh
[Docs][zh]Localize kueuectl_list_workload.md
Fixes #
```release-note
NONE
```

[Docs][zh]Localize kueuectl_list_workload.md

---

CHANGELOG/CHANGELOG-0.13.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

Part-of https://github.com/kubernetes-sigs/kueue/issues/6624
```release-note
NONE
```

Prepare release v0.13.3

---

CHANGELOG/CHANGELOG-0.13.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

Part of https://github.com/kubernetes-sigs/kueue/issues/6624
```release-note
NONE
```

Update the latest version with v0.13.3

---

pkg/controller/jobframework/tas_test.go

/kind cleanup
Add unit tests for jobframework/tas.go.
Fixes #6646
```release-note
NONE
```

Add unit tests for jobframework/tas.go.

---

pkg/scheduler/flavorassigner/tas_flavorassigner.go

It just corrects punctuation in a Go comment.
It's my first PR in this repo, intended to practice the process.
Fixes #
```release-note
NONE
```

Add a full stop at the end of a comment.

---

Makefile

/kind cleanup
Use BASE_BUILDER_IMAGE.
Fixes #6724
```release-note
NONE
```

Use BASE_BUILDER_IMAGE.

---

charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
site/content/en/docs/installation/_index.md

kind/documentation
This PR fixes minor typos in the documentation.
Fixes #
```release-note
NONE
```

(docs): fix minor typos in the documentation

---

pkg/config/validation.go

/kind cleanup
Currently if in `config.waitForPodsReady`, enable is set to false, and related fields like timeout, blockAdmission and requeuingStrategy are set, they'll be silently ignored. This PR adds an info level log during such cases.
Fixes #3809 
```release-note
NONE
```
Verified by running setup with enable set to true/false and setting rest of the fields

Add info logging to config.waitForPodsReady when enable is set to false and rest fields are set

---

cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json

/kind cleanup
Bump the all group in /cmd/kueueviz/frontend with 3 updates
Fixes #
Manual fix for https://github.com/kubernetes-sigs/kueue/pull/6748.
```release-note
NONE
```

Bump the all group in /cmd/kueueviz/frontend with 3 updates

---

pkg/controller/jobframework/base_webhook_test.go

/kind cleanup
This is a follow-up PR to https://github.com/kubernetes-sigs/kueue/pull/6687
with minor touch-ups and added test cases.
Fixes #
```release-note
NONE
```

Improve base_webhook_test.go ValidateUpdate unit-test coverage.

---

.github/ISSUE_TEMPLATE/NEW_RELEASE.md
hack/releasing/ci_pull.sh
hack/releasing/common.sh

/kind cleanup
Prepare ci_pull.sh.
Fixes #6288
```release-note
NONE
```

Prepare ci_pull.sh.

---

pkg/cache/snapshot.go
pkg/controller/core/localqueue_controller.go
pkg/scheduler/preemption/classical/candidate_generator.go
pkg/scheduler/preemption/classical/hierarchical_preemption.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_test.go

Cherry pick of #6328 on release-0.13.
#6328: AFS: Increase logging for Admission Fair Sharing
```release-note
NONE
```

Automated cherry pick of #6328: AFS: Increase logging for Admission Fair Sharing

---

pkg/cache/scheduler/fair_sharing.go

/kind cleanup
Old comment is not accurate. We do not restrict the return value to 1,000,000.
Fixes #
```release-note
NONE
```

update FS comment

---

site/content/zh-CN/docs/tasks/manage/setup_wait_for_pods_ready.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize setup_wait_for_pods_ready.md

---

pkg/controller/tas/node_failure_controller.go

/kind cleanup
Improve logs in nodeFailureReconciler.
Fixes #6804
```release-note
NONE
```

Improve logs in nodeFailureReconciler.

---

pkg/controller/tas/node_failure_controller_test.go
pkg/features/kube_features.go
pkg/scheduler/scheduler_test.go
site/content/en/docs/concepts/topology_aware_scheduling.md
site/content/en/docs/installation/_index.md
test/e2e/config/default/controller_manager_config.yaml
test/e2e/config/default/values.yaml
test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
test/integration/singlecluster/tas/tas_test.go

/kind feature
Graduate Hot Swap feature gates.
Fixes #
```release-note
TAS: Graduated to Beta the following feature gates responsible for enabling and default configuration of the Node Hot Swap mechanism: 
TASFailedNodeReplacement, TASFailedNodeReplacementFailFast, TASReplaceNodeOnPodTermination.
```

TAS: Graduate Hot Swap feature gates.

---

pkg/cache/scheduler/fair_sharing.go

/kind bug
/kind flake
Fixes #6960
It seems like regeression after https://github.com/kubernetes-sigs/kueue/pull/6925/files#diff-94a0ecf880b4ffc718449fd8ae642ff0c5bed4136b5458ac33e95c307d76b43bR71 because quantity.AsDec is stateful mutation: https://github.com/kubernetes/apimachinery/blob/da5b06e2fb6698d6db8866899150ec2c1b4518d9/pkg/api/resource/quantity.go#L538
No release note because the previous PR introducing the issue wasn't released yet.
```release-note
NONE
```

Fix fair sharing flake due to data race after calling AsFloat64Slow

---

site/content/zh-CN/docs/tasks/manage/setup_multikueue.md
site/content/zh-CN/docs/tasks/manage/setup_wait_for_pods_ready.md

/language zh
Fixes #
```release-note
NONE
```

[Docs][zh]Localize tasks/manage/setup_multikueue

---

pkg/scheduler/fair_sharing_iterator.go
pkg/scheduler/flavorassigner/flavorassigner.go
pkg/scheduler/flavorassigner/flavorassigner_test.go
pkg/scheduler/flavorassigner/tas_flavorassigner.go
pkg/scheduler/logging.go
pkg/scheduler/preemption/classical/candidate_generator.go
pkg/scheduler/preemption/classical/hierarchical_preemption.go
pkg/scheduler/preemption/fairsharing/least_common_ancestor.go
pkg/scheduler/preemption/fairsharing/ordering.go
pkg/scheduler/preemption/fairsharing/target.go
pkg/scheduler/preemption/policy.go
pkg/scheduler/preemption/preemption.go
pkg/scheduler/preemption/preemption_oracle.go
pkg/scheduler/preemption/preemption_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind cleanup
This should many of the conflicts when trying to cherry-pick onto release-0.13 after #6612
Fixes #
```release-note
NONE
```

[release-0.13] import cache as schdcache in ./pkg/scheduler

---

site/content/en/docs/concepts/admission_fair_sharing.md

Adjusts section titles in admission fair share documentation to fit standard English language usage. 
Fixes #
```release-note
NONE
```

[docs][minor][Admission fair sharing] Update section titles for better English usage

---

cmd/importer/pod/import.go
pkg/controller/admissionchecks/multikueue/workload.go
pkg/controller/core/workload_controller.go
pkg/controller/jobframework/reconciler.go
pkg/controller/tas/node_failure_controller.go
pkg/controller/workloaddispatcher/incrementaldispatcher.go
pkg/scheduler/scheduler.go
pkg/workload/workload.go
pkg/workload/workload_test.go
test/integration/multikueue/dispatcher_test.go
test/integration/singlecluster/controller/core/workload_controller_test.go
test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
test/integration/singlecluster/scheduler/podsready/scheduler_test.go
test/integration/singlecluster/webhook/core/workload_test.go
test/performance/scheduler/runner/controller/controller.go
test/util/util.go
test/util/util_scheduling.go

/kind cleanup
Add options to PatchAdmissionStatus().
Fixes #
```release-note
NONE
```

Add options to PatchAdmissionStatus().

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go
vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/openapi_generated.go
vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/zz_generated.deepcopy.go
vendor/sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2/failurepolicyrule.go
vendor/sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2/jobset.go

/kind cleanup
Fixes #
```release-note
NONE
```

Bump sigs.k8s.io/jobset from 0.9.0 to 0.10.1.

---

Dockerfile
cmd/kueueviz/backend/go.mod
go.mod
hack/internal/tools/go.mod
site/go.mod

/kind cleanup
Upgrade Go version to 1.25
Fixes #
```release-note
NONE
```

Upgrade Go version to 1.25

---

CHANGELOG/CHANGELOG-0.14.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
charts/kueue/values.yaml
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Part of #6756
```release-note
NONE
```

Prepare release v0.14

---

CHANGELOG/CHANGELOG-0.12.md

/kind cleanup
Part of #6946
```release-note
NONE
```

Update changelog after v0.12.10

---

keps/77-dynamically-sized-jobs/README.md

/kind cleanup
This is a follow up to: https://github.com/kubernetes-sigs/kueue/pull/7068#discussion_r2390150874
Fixes #7092
```release-note
NONE
```

Update KEP-77 calling out additional Beta graduation criteria.

---

pkg/controller/jobs/pod/pod_controller.go

/kind cleanup
Remove JobWithFinalize duplication.
Fixes #
```release-note
NONE
```

Add JobWithSkip interface compliance check for *Pod.

---

pkg/controller/jobs/trainjob/trainjob_controller.go

/kind bug
Synchronise to avoid data race related to accessing kubeflow trainer `RuntimeInfo`.
Fixes #7078 
```release-note
NONE
```

[Fix] Synchronise access to RuntimeInfo to avoid data race

---

pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_tas_test.go

Cherry pick of #7153 on release-0.13.
#7153: Remove patchAdmission stub from scheduler.
```release-note
NONE
```

Automated cherry pick of #7153: Remove patchAdmission stub from scheduler.

---

pkg/scheduler/flavorassigner/flavorassigner.go

/kind cleanup
This is a small, local refactor aiming at making it clear how Kueue actually deals with FlavorFungibility policies.
The current code feels hard to reason about, and I think its logic can be expressed much clearer.
Fixes nothing but should enhance discussion, e.g. in the ongoing review of PR #7117.
I split this PR to **8 tiny commits** - each small enough to clearly preserve logical equivalence. \
I'd suggest to review these commits **one by one**. \
(Otherwise, the final effect looks quite distant from the original code).
```release-note
NONE
```

Reorganize `shouldTryNextFlavor` to make the logic more clear.

---

CHANGELOG/CHANGELOG-0.14.md
Makefile
README.md
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Prepare release v0.14.1.
Part of #7186
```release-note
NONE
```

Prepare release v0.14.1

---

CHANGELOG/CHANGELOG-0.14.md
Makefile
README.md
SECURITY-INSIGHTS.yaml
charts/kueue/Chart.yaml
charts/kueue/README.md
charts/kueue/README.md.gotmpl
cmd/kueueviz/INSTALL.md
cmd/kueueviz/frontend/package-lock.json
cmd/kueueviz/frontend/package.json
site/hugo.toml
test/e2e/kueueviz/package-lock.json
test/e2e/kueueviz/package.json

/kind cleanup
Update main with the latest v0.14.1.
Part of #7186
```release-note
NONE
```

Update main with the latest v0.14.1

---

CHANGELOG/CHANGELOG-0.13.md

Part of https://github.com/kubernetes-sigs/kueue/issues/7187
```release-note
NONE
```

update CHANGELOG with 0.13.6
