test/e2e/multikueue/e2e_test.go
/kind cleanup
Remove unnecessary IgnoreConditionTimestampsAndObservedGeneration for ReplicaStatus object.
Fixes #
```release-note
NONE
```
=> Remove unnecessary IgnoreConditionTimestampsAndObservedGeneration for ReplicaStatus object.

charts/kueue/templates/rbac/role.yaml, config/components/manager/controller_manager_config.yaml, config/components/rbac/role.yaml, keps/79-hierarchical-cohorts/README.md, pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/resource_test.go, pkg/cache/snapshot_test.go, pkg/controller/core/cohort_controller.go, pkg/controller/core/cohort_controller_test.go, pkg/controller/core/core.go, pkg/queue/manager.go, pkg/util/testing/client.go, pkg/util/testing/wrappers.go, test/integration/scheduler/scheduler_test.go
/kind feature
Implement Cohort Reconciler, as part of #79. This is the minimum reconciler implementation. Updating status will be implemented in a future PR.
Until we implement the Cohort webhook in a follow-up PR, this logic is inaccessible to users.
We diverge slightly from the other reconcilers: we only do reconciliation in the Reconcile method. The `ClusterQueue` reconciler, for example, updates the cache/queue in the event filter.
```release-note
NONE
```
=> Implement Cohort Reconciler

pkg/cache/snapshot_test.go, pkg/hierarchy/cycle.go, pkg/hierarchy/manager.go, pkg/hierarchy/manager_test.go, pkg/scheduler/preemption/preemption_test.go
/kind feature
Cycle checking logic in hierarchy.Manager. Will be used by both `queue.manager` and `cache.Cache`. I'm pulling it out of #3006 to reduce diff. Part of #79
```release-note
NONE
```
=> Implement Cohort cycle detection in hierarchy.Manager

keps/168-2-pending-workloads-visibility/README.md, keps/168-2-pending-workloads-visibility/kep.yaml
Update "KEP-168-2: Pending-workloads-visibility" before graduation to Beta.
Related to #3008
```release-note
NONE
```
=> Update "KEP-168-2: Pending-workloads-visibility" before graduation to Beta

test/e2e/singlecluster/visibility_test.go
/kind bug
Fix the "Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about pending workloads in LocalQueue" flaky e2e test.
Fixes #3044
```release-note
NONE
```
=> Fix "Should allow fetching information about pending workloads in LocalQueue" e2e test.

.golangci.yaml, pkg/hierarchy/cohort.go
/kind cleanup
- Enable `unused` linter,
- Lint:ignore U1000 for hierarchy.Cohort struct.
Fixes #2965
Also created separate issue to fix it https://github.com/dominikh/go-tools/issues/1602.
UPDATE: It is a know issue on https://github.com/dominikh/go-tools/issues/1294 and https://github.com/dominikh/go-tools/issues/1440 and waiting for https://github.com/golang/go/issues/63982.
```release-note
NONE
```
=> Lint:ignore U1000 for hierarchy.Cohort struct.

test/e2e/singlecluster/jobset_test.go
/kind bug
/kind cleanup
WIP because for now this is just an e2e that documents the issue. We will be able to fix it once https://github.com/kubernetes-sigs/jobset/pull/625 is fixed at the JobSet side, and is bumped in Kueue.
Fixes #
```release-note
NONE
```
=> Add e2e test for JobSet fix on suspend

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/cohort.go, pkg/cache/resource_node.go, pkg/cache/resource_test.go, pkg/cache/snapshot.go, pkg/cache/snapshot_test.go, pkg/controller/core/cohort_controller.go, pkg/controller/core/cohort_controller_test.go
/kind feature
Support HierarchicalCohorts (#79), with cycle-detection, in the cache and snapshot. 
I wrote tests which check resource usage. I will add them to this PR once #3005 merges.
```release-note
Hierarchical Cohorts
```
=> Support Hierarchical Cohorts in Cache/Snapshot

pkg/scheduler/scheduler.go
/kind cleanup
Avoid unnecessary calls to `assignment.RepresentativeMode()` and `else` after `return`.
Fixes #
```release-note
None
```
=> [scheduler] Avoid unnecessary calls

cmd/experimental/kjobctl/pkg/builder/builder.go
/kind bug
Fix fetching VolumeBundles in kjobctl builder.
Fixes #
Each ApplicationProfile should only have its associated VolumeBundles. However, we are currently retrieving all existing VolumeBundles in the namespace.
```release-note
NONE
```
=> [kjobctl] Fix fetching VolumeBundles in builder.

cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go, cmd/kueuectl/app/util/client_getter.go
/kind feature
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which, compared to the default JSON encoding, reduces CPU consumption related to (de)serialization, reduces overall latency of the API calls, reduces memory footprint and the work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
Core system components of K8s default their serialization method to protobuf for 8 years already: https://github.com/kubernetes/kubernetes/pull/25738.
No issue is opened for that.
Some benchmarks comparing JSON vs. protobuf showcasing how the latter data format (de)serializes faster and uses less memory:
- https://medium.com/@akresling/go-benchmark-json-v-protobuf-4ec3c62ec8d4
- …
=> Use protobuf encoding for core K8s APIs in kueue

pkg/config/config.go, pkg/config/config_test.go
/kind cleanup
When the manager is terminated, the leader role replica should voluntarily steps down from its own leader role
so that backup role can take the leader role as soon as possible.
Fixes #
```release-note
NONE
```
=> When the leader election is enabled, set true in leaderElectionReleaseOnCancel

pkg/queue/cohort.go, pkg/queue/manager.go, pkg/queue/manager_test.go, test/integration/scheduler/scheduler_test.go
/kind feature
Part of #79. We support hierarchical cohorts in the queue package, by requeueing all inadmissible workloads in the Cohort tree upon any events which may allow inadmissible workloads to be scheduled.
Once #3066 is resolved, we can add a unit test to make sure that all workloads in tree are moved. Until then, we have coverage via an integration test, and a unit test to cover the cycle-path in the `queue` package
```release-note
NONE
```
=> Requeue all inadmissible workloads in Cohort Tree

test/integration/kueuectl/passthrough_test.go
/kind cleanup
Add more integration tests for passthrough in kueuectl to cover localqueue and clusterqueue commands.
Fixes #
```release-note
NONE
```
=> [kueuectl] Add passthrough integration tests for ClusterQueue and LocalQueue

cmd/kueuectl/app/cmd.go, cmd/kueuectl/app/passthrough/passthrough.go
/kind cleanup
Move `exec.LookPath("kubectl")` to RunE function in kueuectl pass-through commands to return an error only on execute this commands.
Fixes #
```release-note
NONE
```
=> [kueuectl] Move exec.LookPath("kubectl") to RunE function.

apis/kueue/v1alpha1/cohort_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml, config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml, site/content/en/docs/reference/kueue-alpha.v1alpha1.md
/kind cleanup
Document incompatibility of Fair Sharing with Hierarchical Cohorts. Cleanup unused variable - this can be added back when we update status when cycles exist. Related to #79
```release-note
NONE
```
=> Update Cohort Documentation; Delete Unused Variable

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/preemption/preemption_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/workload/workload.go
/kind bug
- Fix the flow that allows a workload to be partially admitted while preempting lower priority workloads. 
- Add an unit test for preemption while partially admitting.
Fixes #2799 
```release-note
Fix some scenarios for partial admission which are affected by wrong calculation of resources
used by the incoming workload which is partially admitted and preempting.
```
=> [PartialAdmission] Fix preemption while partially admitting.

pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_controller_test.go
/kind bug
RayJob status has both a `JobStatus` field and a `JobDeploymentStatus` field. The former represents the status of the running Ray job and the latter represents the state of the RayCluster and RayJob. The `Finished()` implementation in Kueue for RayJob should look at the JobDeployment for "finished" since that is what represents whether resources for the job have been cleaned up. This will also catch some cases where JobStatus will remain "Running" even though JobDeploymentStatus is "Failed". This can specifically happen when `activeDeadlineSeconds` is exceeded.
Fixes #
```release-note
RayJob's implementation of Finished() now inspects at JobDeploymentStatus 
```
=> RayJob: update Finished() to account for JobDeploymentStatus

keps/168-pending-workloads-visibility/README.md, keps/168-pending-workloads-visibility/kep.yaml
Part of #2256
```release-note
NONE
```
=> Update "KEP-168-pending-workload-visibility" before deprecation.

cmd/experimental/kjobctl/pkg/builder/interactive_builder.go, cmd/experimental/kjobctl/pkg/builder/job_builder.go, cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go, cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go, cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/testing/wrappers/job_template_wrappers.go, cmd/experimental/kjobctl/pkg/testing/wrappers/pod_template_wrappers.go, cmd/experimental/kjobctl/pkg/testing/wrappers/ray_cluster_template_wrappers.go, cmd/experimental/kjobctl/pkg/testing/wrappers/ray_job_template_wrappers.go
/kind cleanup
Ignore `kubectl.kubernetes.io/last-applied-configuration` on copying annotations from template in kjobctl.
Fixes #
After building objects we have unnecessary `kubectl.kubernetes.io/last-applied-configuration` annotation like this:
```
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"kjobctl.x-k8s.io/v1alpha1","kind":"JobTemplate","metadata":{"annotations":{},"name":"sample-slurm-template","namespace":"default"},"template":{"spec":{"completionMode":"Indexed","completions":3,"parallelism":3,"template":{"spec":{"containers":[{"image":"python:3-slim","name":"sample-container"}],"restartPolicy":"OnFailure"}}}}}
creationTimestamp: "2024-09-24T14:51:37Z"
```
```release-note
NONE
```
=> [kjobctl] Ignore kubectl.kubernetes.io/last-applied-configuration on copying annotations from template.

apis/config/v1beta1/configuration_types.go, apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/features/kube_features.go, site/content/en/docs/installation/_index.md, site/content/en/docs/reference/kueue-config.v1beta1.md, site/content/en/docs/reference/kueue.v1beta1.md, site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
/kind feature
Deprecate QueueVisibility feature and corresponding API.
Fixes #2256
```release-note
The QueueVisibility feature and its corresponding API was deprecated.
ACTION REQUIRED: The QueueVisibility feature and its corresponding API was deprecated and will be removed in the v1beta2. Please use VisibilityOnDemand (https://kueue.sigs.k8s.io/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand/) instead.
```
=> Deprecate QueueVisibility feature and corresponding API.

apis/kueue/v1beta1/clusterqueue_types.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/util/maps/maps.go, test/integration/controller/core/clusterqueue_controller_test.go
/kind feature
[cache] Add more details in the clusterQueues inactive message.
Enhance the detail level in the ClusterQueues `status.conditions[Active].message` to possibly incorporate the Flavors and/or AdmissionChecks that are causing the inactive status.
Fixes #3099 
```release-note
Provides more details on the reasons for ClusterQueues being inactive.
ACTION REQUIRED: If you were watching for the reason `CheckNotFoundOrInactive` in the ClusterQueue condition, watch `AdmissionCheckNotFound` and `AdmissionCheckInactive` instead.
```
=> [cache] Add more details in the clusterQueues inactive message.

test/integration/multikueue/suite_test.go
/kind bug
/kind flake
[test][int][multikueue] Ignore error on config namespace multiple creation.
Ignore Already Exists error when creating the kueue config namespace.
Fixes #
```release-note
none
```
=> [test][int][multikueue] Ignore error on config namespace multiple creation.

go.mod, pkg/controller/jobframework/base_webhook.go, pkg/controller/jobframework/noop_webhook.go, pkg/controller/jobframework/webhook/builder.go, pkg/controller/jobframework/webhook/defaulter.go, pkg/controller/jobframework/webhook/defaulter_test.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook.go
/kind bug
Prevent job webhooks from dropping fields for newer API fields when Kueue libraries are behind the latest released CRDs.
This was possible by reusing controller-runtime's handler for CustomDefaulter, by dropping the "remove" operations from the jsondiffs.
I had to duplicate controller-runtime's webhook builder, because there is no way to introduce a custom handler in it. I have an open PR to upstream this ability https://github.com/kubernetes-sigs/controller-runtime/pull/2932
Fixes #2878
Just to expand on why I decided to go with this approach of dropping the remove operations:
Another option I considered was for every job to return jsonpatches in the Suspend operation. But then it becomes quite hard to explain how to do your own, if you aren't already familiar with jsonpatches. …
=> Drop remove operations from webhook patches

pkg/util/testing/core.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/kubeflow/kubeflowjob.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/controller/jobs/rayjob/rayjob_controller_test.go
/kind bug
/kind flake
[test][integration] Relax `CheckLatestEvent` to `CheckEventRecordedFor`.
Instead of expecting that an event is recorded last, check that the event was recorded for a specific object.
Fixes #3144
```release-note
none
```
=> [test][integration] Relax `CheckLatestEvent` to `CheckEventRecordedFor`.

pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, test/integration/webhook/jobs/job_webhook_test.go
/kind bug
[batch/job] Allow unsuspending a job with a parallelism equal or less then min.
The minimum can be reached in the usual partial admission operation. Values less then minimum can be reached in case of readmitting jobs which have marked a good part of their pods as reclaimable.
Fixes #3140
```release-note
Fix webook validation for batch/Job to allow partial admission of a Job to use all available resources.
It also fixes a scenario of partial re-admission when some of the Pods are already reclaimed.
```
=> [batch/job] Allow unsuspending a job with a parallelism equal or less then minimum.

pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, test/integration/webhook/jobs/job_webhook_test.go
/kind bug
[batch/job] Fix parallelism restoration after partial admission.
Fixes #3151 
```release-note
Fix restoring parallelism on eviction for partially admitted batch/Jobs.
```
=> [batch/job] Fix parallelism restoration after partial admission.

test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Fix "Failed Pod can be replaced in group" e2e test.
Fixes #3147
Sometimes the garbage collector takes more than 5 seconds to delete a finalized Pod. We don't need to wait for the Pod to be removed after it's been replaced; we only need to confirm that the finalizer has been removed.
```release-note
NONE
```
=> Fix "Failed Pod can be replaced in group" e2e test.

site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Corrects the documentation for external framework RBAC changes.  Discussion [here](https://github.com/kubernetes-sigs/kueue/pull/2478#pullrequestreview-2334348832). 
Fixes #
```release-note
NONE
```
=> Fix description of RBAC directives for external integrations

Makefile-test.mk, test/integration/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/controller/core/clusterqueue_controller_test.go, test/integration/controller/core/localqueue_controller_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/framework/framework.go, test/integration/multikueue/multikueue_test.go, test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/podsready/scheduler_test.go, test/integration/scheduler/scheduler_test.go, test/integration/scheduler/workload_controller_test.go
/kind feature
Add spec labels and the ability to skip long running and redundant tests.
Two ginkgo labels are added:
- `SlowSpec` - For starters added to specs that take more the 5s to run.
- `RedundantSpec` - Added to kubeflow jobs other then pytourch.
When running `make test-integration` ,  the user has the option to set `INTEGRATION_RUN_ALL=false` and the Slow and Redundant specs are skipped.
As a followup `INTEGRATION_RUN_ALL` should be set to false in PR related CI jobs.
Relates to #2993 
```release-note
None
```
=>  [test][integration] Add spec labels support

test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/kubeflow/kubeflowjob.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/controller/jobs/rayjob/rayjob_controller_test.go, test/integration/framework/framework.go, test/integration/multikueue/suite_test.go
/kind feature
[test][integration] Start the multikueue test clusters in parallel.
Relates to #2993
```release-note
None
```
=> [test][integration] Start the multikueue test clusters in parallel.

test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind cleanup
Fix "Provisioning when A workload is using a provision admission check Should set the condition rejected when the provision fails" flaky test.
Fixes #3079
After investigating the logs in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/3078/pull-kueue-test-integration-main/1836042561878233088, I found that the failure occurred because the `LocalQueue` reconciler ran after the `Workload` reserved quota. As a result, we now have QuotaReserved=False with the message "Workload is inadmissible because of missing LocalQueue."
```
STEP: Setting the quota reservation to the workload @ 09/17/24 14:06:29.885
2024-09-17T14:06:29.886934773Z	LEVEL(-2)	workload-reconciler	core/workload_controller.go:653	Workload update event	{"workload": …
```
=> Fix "Should set the condition rejected when the provision fails" test.

test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/podsready/scheduler_test.go, test/integration/scheduler/preemption_test.go, test/util/util.go
/kind cleanup
Just now we are waiting second to be ensure that the new created object has a later creation time. To be more accurate we need to wait difference between next second after last creation time of object and current time. 
Fixes #
```release-note
NONE
```
=> Time sleep optimization on tests.

test/integration/framework/framework.go, test/integration/kueuectl/suite_test.go, test/integration/scheduler/fairsharing/suite_test.go, test/integration/scheduler/suite_test.go, test/integration/webhook/core/suite_test.go, test/integration/webhook/jobs/pod_webhook_test.go, test/integration/webhook/jobs/raycluster_webhook_test.go
/kind cleanup
[test][integration] Drop the framework's `RunManager` in favor of `SetupClient` and `StartManager`
Related to:  #2993
```release-note
None
```
=> [test][integration] Drop `fwk.RunManager` in favor of `SetupClient` and `StartManager`

cmd/experimental/kjobctl/pkg/builder/builder.go, cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl, cmd/experimental/kjobctl/pkg/cmd/create/create.go, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind feature
Add `--chdir` flag to Slurm for changing directory before executing the script.
Fixes #
```release-note
NONE
```
=> [kjobctl] Add --chdir flag to Slurm mode

site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md, site/static/examples/visibility/cluster-role-and-binding.yaml
Add steps how to access VisibilityOnDemand via curl.
Review remarks for #1824
```release-note
NONE
```
=> Add steps how to access VisibilityOnDemand via curl

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/util/cert/cert.go
/kind bug
Add RBAC permissions for ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding resources.
Fixes #
To fix an issue:
```
W1004 06:39:21.286539       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ValidatingAdmissionPolicyBinding: validatingadmissionpolicybindings.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:kueue-system:kueue-controller-manager" cannot list resource "validatingadmissionpolicybindings" in API group "admissionregistration.k8s.io" at the cluster scope
E1004 06:39:21.286701       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ValidatingAdmissionPolicyBinding: failed to list *v1.ValidatingAdmissionPolicyBinding: …
```
=> Add RBAC permissions for ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding resources.

cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind bug
Fix issue with `--mem-per-cpu` flag.
Fixes #
```release-note
NONE
```
=> [kjobctl] Fix --mem-per-cpu flag

cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/cmd/create/create.go, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind bug
Fix issue that passes the wrong value to GPUs parser when using `--mem-per-gpu`.
Fixes #
```release-note
NONE
```
=> [kjobctl] Fix --mem-per-gpu flag

pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go
/kind feature
It produces an event when an error during provisioning request creation occurs.
Fixes #3025
```release-note
NONE
```
=> Record an event when provisioning request fails

Makefile-test.mk, cmd/experimental/kjobctl/Makefile
/kind cleanup
Fix `has malformed LC_DYSYMTAB` warning on darwin platform.
Fixes #3196
When we running `make test` on Darwing platform we have warnings:
```
=== Errors
ld: warning: '/private/var/folders/y3/rwbwnplx2cz9gf0t71dhp5k00000gn/T/go-link-3229174941/000012.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
ld: warning: '/private/var/folders/y3/rwbwnplx2cz9gf0t71dhp5k00000gn/T/go-link-2692282886/000012.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
ld: warning: '/private/var/folders/y3/rwbwnplx2cz9gf0t71dhp5k00000gn/T/go-link-3121826813/000012.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at …
```
=> Fix `has malformed LC_DYSYMTAB` warning on darwin platform.

apis/kueue/v1beta1/admissioncheck_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml, config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml, site/content/en/docs/reference/kueue.v1beta1.md
/kind cleanup
API deprecation notice should be aligned with standardized form so that linter can detect the deprecation comment in external projects.
https://go.dev/wiki/Deprecated
Fixes #
```release-note
NONE
```
=> Align the retryDelayMinutes deprecation notice with the standard form

pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, test/integration/controller/jobs/job/job_webhook_test.go
Cherry pick of #3152 on release-0.8.
#3152: [batch/job] Allow unsuspending a job with a parallelism equal or less then minimum.
```release-note
Fix webook validation for batch/Job to allow partial admission of a Job to use all available resources.
It also fixes a scenario of partial re-admission when some of the Pods are already reclaimed.
```
=> Automated cherry pick of #3152: [batch/job] Allow unsuspending a job with a parallelism equal or less then minimum.

pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, test/integration/controller/jobs/job/job_webhook_test.go
Cherry pick of #3153 on release-0.8.
#3153: [batch/job] Fix parallelism restoration after partial admission.
```release-note
Fix restoring parallelism on eviction for partially admitted batch/Jobs.
```
=> Automated cherry pick of #3153: [batch/job] Fix parallelism restoration after partial admission.

pkg/controller/admissionchecks/provisioning/controller.go
/kind feature
Follow up of #3056 . This PR truncates condition and event messages when they're too long.
Discussion: https://github.com/kubernetes-sigs/kueue/pull/3056#discussion_r1796666498  
Relates to #3025
```release-note
NONE
```
=> Truncate message when provisioning request creation fails

Dockerfile, cmd/experimental/kjobctl/README.md, cmd/experimental/kjobctl/go.mod, cmd/experimental/kjobctl/hack/tools/go.mod, go.mod, hack/internal/tools/go.mod
/kind cleanup
Before we release the next minor version (v0.9), upgrading Go version would be better.
Fixes #
```release-note
NONE
```
=> Upgrade Go version to 1.23

keps/3122-expose-flavors-in-localqueue-status/README.md, keps/3122-expose-flavors-in-localqueue-status/kep.yaml
KEP for Expose Flavors in LocalQueue Status.
Part of #3122
```release-note
NONE
```
=> KEP-3122: Expose Flavors in LocalQueue Status.

apis/kueue/v1alpha1/tas_types.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobs/job/job_controller_test.go, pkg/features/kube_features.go, site/content/en/docs/installation/_index.md
/kind feature
Part of #2724
The annotation and label are used only for TAS now, but the names are generic since they can be used in other contexts too. For TAS they are used by TopologyUngater to lookup The admitted Workload from a Pod.
```release-note
Introduce the new PodTemplate annotation kueue.x-k8s.io/workload, and label kueue.x-k8s.io/podset.
```
=> PodSet label and Workload annotation for PodTemplates

pkg/controller/jobs/pod/pod_controller_test.go
/kind cleanup
Cleanup unit test code to reuse the same constant rather than copy and paste
Fixes #
```release-note
NONE
```
=> use constant for podUUID 

test/e2e/singlecluster/jobset_test.go
/kind cleanup
Use E2eTestSleepImage constant on e2e tests.
Fixes #
```release-note
NONE
```
=> Use E2eTestSleepImage constant on e2e tests.

keps/2724-topology-aware-schedling/README.md
/kind cleanup
To reflect API decision changes during implementation:
- better comments
- change the TopologyAssignment in workload:
- use `domain` rather than group consistently
- break nodeLabels for domains into order list of keys common for all domains, and ordered list of values. This saves a lot of space for large assignments, avoiding duplication of the keys.
- included example [here](https://github.com/kubernetes-sigs/kueue/pull/3237/files#diff-40027534eab1ffd244e3c960acbf91b55b9556bebd8cd56077ba5f3270648284R481-R489)
Part of #2724
```release-note
NONE
```
=> TAS: KEP update for API

test/integration/scheduler/podsready/scheduler_test.go
/kind bug
/kind flake
Fix flaky test: Should not block admission of one new workload if two are considered in the same scheduling cycle.
Fixes #3212
```release-note
None
```
=> Fix "Scheduler with WaitForPodsReady Suite"

test/integration/scheduler/workload_controller_test.go
/kind cleanup
Cleanup tests introduced in #3026 as [requested](https://github.com/kubernetes-sigs/kueue/pull/3026#discussion_r1805521518) 
Fixes #
```release-note
NONE
```
=> test cleanup: replace equality.DeepEqual by gomega.BeComparableTo

pkg/scheduler/scheduler.go
/kind bug
Change the insufficient resource event type from Normal to Warning.
Fixes #3263
```release-note
Changed the `type` of `Pending` events, emitted when a Workload can't be admitted, from `Normal` to `Warning`.
ACTION REQUIRED: Update tools that process this event if they depend on the event `type`.
```
=> Change the insufficient resource event type from Normal to Warning

pkg/podset/podset.go, pkg/podset/podset_test.go
/kind feature
To add the scheduling pods to the PodTemplate (and thus the Pods) admitted by TAS.
Part of #2724 
No release note here, I will add it in a single PR which adds the API.
The assignment is done in PR #3256 . The gate will be removed in a follow up PR. This PR can be merged indepdendently of computing the assignment or topology ungater, but all 3 PRs are required for the feature to work e2e.
```release-note
NONE
```
=> TAS: Add scheduling gate to Pods admitted by TAS

pkg/controller/jobs/pod/event_handlers.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/util/expectations/store.go, pkg/util/expectations/store_test.go
/kind cleanup
This is a preparatory PR to move the expectations mechanism to utils, so that I can use it in TopologyUngater.
Part of #2724 
Related to https://github.com/kubernetes-sigs/kueue/pull/3266
```release-note
NONE
```
=> TAS: move expecatations store to utils to share with TopologyUngater

pkg/controller/jobframework/reconciler.go, pkg/controller/jobs/job/job_controller_test.go, site/content/en/docs/reference/labels-and-annotations.md, test/integration/controller/jobs/job/job_controller_test.go
/kind feature
Wait for the prebuilt Workload if a Job is running before it.
Fixes #3051
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3131#issuecomment-2413187780.
```release-note
Best effort support for scenarios when the Job is created at the same time as prebuilt workload or momentarily before the workload. In that case an error is logged to indicate that creating a Job before prebuilt-workload is outside of the intended use.
```
=> Wait for the prebuild workload.

test/integration/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/controller/core/admissioncheck_controller_test.go, test/integration/controller/core/localqueue_controller_test.go, test/integration/controller/core/resourceflavor_controller_test.go, test/integration/kueuectl/list_test.go, test/integration/scheduler/podsready/scheduler_test.go, test/util/util.go
/kind cleanup
Add `ExpectClusterQueuesToBeActive` in `test/util` and use it in the integration tests.
Fixes #
```release-note
none
```
=> [test][util] Add 'ExpectClusterQueuesToBeActive'

test/e2e/singlecluster/e2e_test.go
/kind bug
/kind flake
Await for pods to be running before delete all pods in "Kueue When Creating a Job With Queueing Should run with prebuilt workload" test.
Fix for https://github.com/kubernetes-sigs/kueue/pull/3131#issuecomment-2422662658.
```release-note
NONE
```
=> Await for pods to be running before delete all pods.

Makefile-test.mk
/kind cleanup
`-ldflags=-linkmode=internal` using to fix `malformed LC_DYSYMTAB` issue. But it's deprecated and now we have errors:
```
=== Errors
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
```
To fix it we can force using Go linker to do the whole linking instead of old Apple linker. For more details https://github.com/golang/go/issues/61229#issuecomment-1988965927.
Fixes #
```release-note
NONE
```
=> Use -ldflags=-linkmode=internal to fix malformed LC_DYSYMTAB issue.

apis/kueue/v1alpha1/tas_types.go, keps/2724-topology-aware-schedling/README.md, pkg/podset/podset.go, pkg/podset/podset_test.go
/kind feature
This label will be used in two places:
- to trigger reconcile from TopologyUngater only for pods managed by TAS, without relying on the fact that the "workload" 
annotation or "podset" label is only used for TAS
- used when computing usage from non-TAS pods, by selector which avoids TAS pods
Part of #2724 
No release note here, as I added one already for TAS in the API PR.
```release-note
NONE
```
=> TAS: introduce dedicated TAS label

cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind bug
It fixes a crash issue when the Slurm template has one container and --ntasks is greater than 1.
Fixes #
```release-note
NONE
```
=> [kjobctl] Fix crash issue in Slurm mode when ntasks > 1

site/content/en/docs/tasks/manage/administer_cluster_quotas.md, site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Adds user-facing documentation on configurable resource transformations (KEP-2937) to website
Fixes #
I'm putting NONE for the release note, because #3026 which is the implementation PR contains the release note text.
Written under the assumption that we'll be merge 3026 in time to make 0.9. 
```release-note
NONE
```
=> Add user documentation for KEP-2937 to website

cmd/kueue/main.go, go.mod, pkg/controller/tas/constants.go, pkg/controller/tas/controllers.go, pkg/controller/tas/indexer.go, pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go, pkg/util/tas/tas.go, pkg/util/testing/wrappers.go, pkg/util/testingjobs/pod/wrappers.go
/kind feature
Part of #2724 
Done since the initial version:
- use the TAS dedicated label to filiter out non-TAS pods (DONE)
- expectations mechanism to prevent race conditions (DONE)
I have also tested the handlers already in the e2e prototype PR: https://github.com/kubernetes-sigs/kueue/pull/3218
```release-note
NONE
```
=> TAS: TopologyUngater

cmd/experimental/kjobctl/Makefile
/kind cleanup
`-ldflags=-linkmode=internal` using to fix `malformed LC_DYSYMTAB` issue. But it's deprecated and now we have errors:
```
=== Errors
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
ld: warning: -ld_classic is deprecated and will be removed in a future release
```
To fix it we can force using Go linker to do the whole linking instead of old Apple linker. For more details https://github.com/golang/go/issues/61229#issuecomment-1988965927.
Fixes #
```release-note
NONE
```
=> [kjobctl] Use -ldflags=-linkmode=internal to fix malformed LC_DYSYMTAB issue.

pkg/features/kube_features.go
/kind cleanup
Set deprecated PreRelease for QueueVisibility feature.
Part of #2256
```release-note
NONE
```
=> Set deprecated PreRelease for QueueVisibility feature.

keps/1136-provisioning-request-support/README.md, keps/1136-provisioning-request-support/kep.yaml
Introduces configurable retry strategy for ProvisioningRequests
Part of #1353 
```release-note
NONE
```
=> [KEP] Add retry strategy to the ProvisionigRequestConfig API

cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/builder/slurm_builder_test.go, cmd/experimental/kjobctl/pkg/builder/templates/slurm_entrypoint_script.sh.tmpl, cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind cleanup
Move SBATCH_ variables to entrypoint script in kjobctl Slurm mode.
Prepare https://github.com/kubernetes-sigs/kueue/pull/3269.
Sbatch variables are not using in init-entrypoint.sh, so there's no need to generate them in the init script.
```release-note
NONE
```
=> [kjobctl] Move SBATCH_ variables to entrypoint script.

cmd/experimental/kjobctl/Makefile, cmd/experimental/kjobctl/hack/e2e-test.sh, cmd/experimental/kjobctl/hack/tools/go.mod, cmd/experimental/kjobctl/hack/tools/go.sum, cmd/experimental/kjobctl/hack/tools/pinversion.go, cmd/experimental/kjobctl/test/e2e/e2e_test.go, cmd/experimental/kjobctl/test/e2e/suite_test.go, cmd/experimental/kjobctl/test/util/util.go
/kind cleanup
Adds initial setup for e2e tests in kjobctl.
Fixes #
```release-note
NONE
```
=> [kjobctl] Init e2e tests

apis/kueue/v1beta1/clusterqueue_types.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/admissionchecks/multikueue/admissioncheck.go, pkg/controller/admissionchecks/multikueue/admissioncheck_test.go, pkg/features/kube_features.go, site/content/en/docs/installation/_index.md, test/integration/controller/core/clusterqueue_controller_test.go, test/integration/multikueue/multikueue_test.go
/kind bug
`SingleInstanceInClusterQueue` and `FlavorIndependent` are confusing to the multi-cluster users.
We need to wrap them with feature gate, but preserve the logic for MultiKueue Admission Checks constraints without those status conditions.
Fixes #3094 
```release-note
Deprecated SingleInstanceInClusterQueue and FlavorIndependent status conditions.
ACTION REQUIRED: the Admission check status conditions “FlavorIndependent” and “SingleInstanceInClusterQueue” are no longer supported by default.
If you were using any of these conditions for your external AdmissionCheck you need to enable the `AdmissionCheckValidationRules` feature gate. 
For the future releases you will need to provide validation by an external controller.
```
=> [MultiKueue] Introduce Admission Check Validation feature gate

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, site/content/en/docs/concepts/preemption.md, site/content/en/docs/reference/kueue.v1beta1.md
1. Clarifies API docs for reclaimWithinCohort 'if the pending Workload fits within the nominal quota' wording.
2. Makes it more obvious in concept docs that fair sharing works in addition to the preemption policies set.
Fixes #3286
```release-note
NONE
```
=> Add more clarify on how reclaimWithinCohort interacts with fair sharing

keps/3125-maximum-execution-time/README.md, keps/3125-maximum-execution-time/kep.yaml
Proposed KEP fo Maximum Execution Time feature.
Relates to #3125 
```release-note
none
```
=> [KEP] Maximum Execution Time

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor.go, pkg/cache/tas_flavor_snapshot.go, pkg/controller/tas/topology_ungater.go, test/integration/tas/tas_job_test.go
/kind cleanup
To address non-blocking review remarks for the main PRs:
- https://github.com/kubernetes-sigs/kueue/pull/3266 (one remark done here about Predicate)
- https://github.com/kubernetes-sigs/kueue/pull/3256 (all other remarks)
Part of #2724 
```release-note
NONE
```
=> TAS: cleanups after merging main PRs

cmd/experimental/kjobctl/pkg/cmd/delete/delete_slurm.go, cmd/experimental/kjobctl/pkg/cmd/delete/delete_slurm_test.go
/kind cleanup
We added `ownerReference` for additional Slurm objects in https://github.com/kubernetes-sigs/kueue/pull/3129, so it's no longer necessary to manually remove the ConfigMaps.
Fixes #
```release-note
NONE
```
=> [kjobctl] Skip removing ConfigMap on delete Slurm.

apis/kueue/v1beta1/clusterqueue_types.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, test/integration/controller/core/clusterqueue_controller_test.go
/kind cleanup
The PR corrects a typo in the constant `ClusterQueueActiveReasonMultiKueueAdmissionCheckAppliedPerFlavor`. Should be `Multi`, not `Mutli`.
This constant was introduced yesterday in PR #3254. I believe we can fix it.
```release-note
NONE
```
=> [MultiKueue] Fix a typo in cluster queue type constant

test/e2e/singlecluster/tas_test.go
/kind cleanup
To make sure TAS works e2e, including computing the assignment and ungatibg the pods.
Part of #2724 
I'm happy to add more scenarios in this PR or on follow ups.
```release-note
NONE
```
=> TAS: introduce sanity e2e test

pkg/cache/snapshot.go, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor.go
/kind feature
To include capacity from non-TAS pods. Mainly DaemonSets, but not only.
Part of #2724 
I have initially done indexing of all  non-TAS, scheduled and non-terminal pods, but it is more code, so I decided for now to do minimal change and filter the terminal pods when accounting for capacity. 
```release-note
NONE
```
=> TAS: include usage from non-TAS Pods

test/e2e/singlecluster/statefulset_test.go, test/util/util.go
/kind bug
/kind flake
Fix "Stateful set integration when Single CQ should admit group that fits" test.
Fixes #3299
Removing a StatefulSet sometimes takes more than 5 seconds. However, we don't need to wait for the StatefulSet to be completely removed; instead, we just need to ensure that the workload is removed.
```release-note
NONE
```
=> Fix "Stateful set integration when Single CQ should admit group that fits" test.

pkg/controller/jobs/statefulset/statefulset_webhook.go, test/e2e/singlecluster/statefulset_test.go
/kind cleanup
Remove statefulSetUID parameter from GetWorkloadName.
Fixes #
We are not using statefulSetUID parameter in GetWorkloadName() method.
```release-note
NONE
```
=> Remove statefulSetUID parameter from GetWorkloadName.

test/e2e/multikueue/e2e_test.go
/kind cleanup
Propagate gomega.Gomega on multikueue tests.
Part of #3300
```release-note
NONE
```
=> Propagate gomega.Gomega on multikueue tests.

hack/e2e-common.sh, hack/multikueue-e2e-test.sh, pkg/controller/jobs/mpijob/mpijob_controller.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go, pkg/controller/jobs/mpijob/mpijob_webhook.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, test/e2e/multikueue/e2e_test.go, test/integration/multikueue/multikueue_test.go
/kind feature
Support MPIJob managedBy feature for the MultiKueue.
Allow for installing `mpi-operator` in management cluster instead of only crds. 
Fixes #3257 
```release-note
MultiKueue: Add support for  MPIJob  `spec.runPolicy.managedBy` field
```
=> Support MPIJob managedBy feature for the MultiKueue

pkg/controller/constants/constants.go, pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go
/kind feature
[jobs] Add max execution time.
Adds a new label `kueue.x-k8s.io/max-exec-time-seconds` that can be used by any supported job to enforce
a maximum execution time for its workload.
Related to #3125
```release-note
Added a new label `kueue.x-k8s.io/max-exec-time-seconds` that can be used by any supported job to enforce
a maximum execution time for its workload.
```
=> [jobs]Add max execution time

pkg/config/validation.go, pkg/constants/constants.go, pkg/webhooks/clusterqueue_webhook.go
/kind cleanup
It would be better to hold self-defined constants.
Fixes #
```release-note
NONE
```
=> Use IsNegativeErrorMsg in the apimachnery lib instead of self deined one

site/content/en/docs/concepts/workload.md
This change removes a word "that" that was used twice in the dentence and was thus redundant.
Fixes #
```release-note
NONE
```
=> [nit] Remove redundant "that" in workload.md

pkg/util/testing/condition_matchers.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/tas_test.go
/kind cleanup
Add gomega status condition matcher.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3319#discussion_r1816980898.
```release-note
NONE
```
=> Add gomega status condition matcher.

.github/ISSUE_TEMPLATE/NEW_RELEASE.md, OWNERS, SECURITY_CONTACTS
I'm super proud of what we have achieved with this project that started almost 3 years ago.
We not only built important features for real users, but we did so with care and passion for writing good software.
And it paid off. Kueue is an important building block for large and small companies doing AI training on Kubernetes.
I am confident that @tenzen-y and @mimowo can lead the project to higher levels. And we are already seeing multiple other contributors stepping up with designs, code and ideas.
Fixes #
/hold
I can still help around until Friday, but I wanted to have the PR ready to go :)
```release-note
NONE
```
=> Remove alculquicondor from OWNERS

pkg/util/testing/error_matchers.go, test/integration/webhook/core/admissioncheck_test.go, test/integration/webhook/core/clusterqueue_test.go, test/integration/webhook/core/localqueue_test.go, test/integration/webhook/core/workload_test.go, test/integration/webhook/jobs/job_webhook_test.go, test/integration/webhook/jobs/pod_webhook_test.go, test/integration/webhook/jobs/raycluster_webhook_test.go
/kind cleanup
Propagate gomega.Gomega on integration/webhook tests.
Part of #3300
```release-note
NONE
```
=> Propagate gomega.Gomega on integration/webhook tests.

test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/kubeflow/kubeflowjob.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/controller/jobs/rayjob/rayjob_controller_test.go
/kind cleanup
Propagate gomega.Gomega on integration/controller/jobs tests.
Part of #3300
```release-note
NONE
```
=> Propagate gomega.Gomega on integration/controller/jobs tests.

test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/podsready/scheduler_test.go, test/integration/scheduler/preemption_test.go, test/integration/scheduler/scheduler_test.go, test/integration/scheduler/workload_controller_test.go
/kind cleanup
Propagate gomega.Gomega on integration/scheduler tests.
Part of #3300
```release-note
NONE
```
=> Propagate gomega.Gomega on integration/scheduler tests.

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/scheduler.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go, test/e2e/singlecluster/e2e_test.go, test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind bug
Currently, when AdmissionCheck is in `Retry` state, the Workloads gets evicted and there's no actual retry. The changes improves that flow, changing all AdmissionChecks to `Pending` if one of them is in `Retry` state (unless there's a `Rejected` AdmissionCheck).
Fixes #3322 
```release-note
Workload is requeued with all AdmissionChecks set to Pending if there was an AdmissionCheck in Retry state.
```
=> Reset all Ready and Ready AdmissionChecks on Eviction as Pending

apis/kueue/v1beta1/clusterqueue_types.go, apis/kueue/v1beta1/provisioningrequestconfig_types.go, pkg/cache/clusterqueue.go, pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go, pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler_test.go, pkg/controller/admissionchecks/provisioning/constants.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go, pkg/controller/admissionchecks/provisioning/indexer.go, pkg/controller/admissionchecks/provisioning/indexer_test.go, test/e2e/singlecluster/tas_test.go, test/integration/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/tas/tas_job_test.go, test/integration/tas/tas_test.go
/kind feature
Part of #2724 
```release-note
NONE
```
=> TAS: validation for CQs using TAS

site/content/en/docs/tasks/run/multikueue/kubeflow.md, site/content/en/docs/tasks/run/multikueue/mpijob.md
Document how to use managedBy provided by the mpi-operator.
Fixes #3313 
```release-note
NONE
```
=> [MultiKueue] Document  MPI Operator managedBy field

pkg/workload/workload.go
/kind bug
Forces ownership of the workload.status.admissioncheck field so the update can happen
Fixes #3351 
```release-note
NONE
```
=> Force status field ownership by core Kueue to fix the MultiKueue integration

go.mod, pkg/controller/jobframework/base_webhook.go, pkg/controller/jobframework/webhook/builder.go, pkg/controller/jobframework/webhook/defaulter.go, pkg/controller/jobframework/webhook/defaulter_test.go, pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook.go
Cherry pick of #3132 on release-0.8.
#3132: Drop remove operations from webhook patches
Created manually due to https://github.com/kubernetes-sigs/kueue/pull/3132#issuecomment-2443986857.
Summary:
- Fixed go.mod conflicts.
- Skip `noop_webhook.go`.
- Skip `deployment_webhook.go`.
Fixes #3349
```release-note
Prevent job webhooks from dropping fields for newer API fields when Kueue libraries are behind the latest released CRDs.
```
=> Automated cherry pick of #3132: Drop remove operations from webhook patches

test/e2e/singlecluster/pod_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/util/util.go
/kind cleanup
Propagate gomega.Gomega.
Fixes #3300
```release-note
NONE
```
=> Propagate gomega.Gomega.

pkg/cache/clusterqueue_test.go, pkg/cache/snapshot_test.go, pkg/controller/core/localqueue_controller_test.go, pkg/scheduler/flavorassigner/flavorassigner_test.go
/kind cleanup
Provide consistent style of using contexts, use previously created contexts instead of using the background context in consecutive calls.
Fixes #3343
```release-note
NONE
```
=> Use previously created context instead of the background

test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Fix "Pod groups when Single CQ should admit group that fits" flaky e2e test.
Fixes #3368
It was "uncovered" after https://github.com/kubernetes-sigs/kueue/pull/3347/files#diff-000300ee149e2c9a17277a7dd35995d69b733d88486f7c5fa1fbe2ba367025d7R127-R130.
Pod removal can take more than 5 seconds due to the garbage collector. However, the workload can be finalized after the pods are deleted.
```release-note
NONE
```
=> Fix "Pod groups when Single CQ should admit group that fits" test.

pkg/controller/jobs/jobset/jobset_controller_test.go, pkg/util/testingjobs/jobset/wrappers.go
/kind cleanup
Add jobset TestPodSet.
Part of #3372
```release-note
NONE
```
=> TAS: Add jobset TestPodSet.

pkg/cache/clusterqueue.go, pkg/cache/tas_cache_test.go, pkg/controller/tas/resource_flavor.go, pkg/scheduler/scheduler_test.go, pkg/util/tas/tas.go, pkg/util/testing/wrappers.go
/kind cleanup
To do not work-around accounting for TAS pods and workloads.
Part of #2724 
This was ticked as "Account for usage from TAS workloads in the unit tests for cache" in the [spreadsheet](https://docs.google.com/spreadsheets/d/1MXCjKZtAfqBTb61bJo46u7jIUqRIlu1NrYj1L8Xz-UU/).
I'm going to expand the tests in follow up tasks.
I moved already the most "workaround"-ish test, but I could move tests in the future, let me know.
```release-note
NONE
```
=> TAS: introduce scheduler-level tests

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go
/kind cleanup
Follow up to https://github.com/kubernetes-sigs/kueue/pull/3373#discussion_r1822966614
Part of #2724 
```release-note
NONE
```
=> TAS: Cleanup flavor assigner check

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/scheduler.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go, test/e2e/singlecluster/e2e_test.go, test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind bug
Manually cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/3323.
The below are conflict points:
- pkg/workload/workload.go: The commit conflicts with ResourceTransformation MaxExecTime codes.
- pkg/scheduler/scheduler.go: The commit conflicts with ResourceTransfomation / codes and fake clock.
- test/e2e/singlecluster/e2e_test.go: The commit conflicts with gomega.Gomega propagation and test case semantic changes related to these bug fixes.
Fixes #
```release-note
Workload is requeued with all AdmissionChecks set to Pending if there was an AdmissionCheck in Retry state.
```
=> Cherry-pick of Reset all Ready and Ready AdmissionChecks on Eviction as Pending (#3323)

pkg/constants/constants.go, pkg/controller/jobframework/tas.go, pkg/controller/jobs/job/job_controller.go, pkg/controller/jobs/jobset/jobset_controller.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_controller.go
/kind feature
Support TAS for Pod.
Fixes #3372
```release-note
NONE
```
=> TAS: Support Pod.

pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/raycluster/raycluster_controller_test.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go
/kind feature
Support TAS for RayJob.
Part of #3372
```release-note
NONE
```
=> TAS: Support RayCluster.

test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/job/suite_test.go
/kind cleanup
Add TAS integration tests for job.
Part of #3372
```release-note
NONE
```
=> TAS: Add integration tests for job.

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/scheduler/scheduler_test.go
/kind feature
This is a small improvement to skip from consideration TAS flavors which don't match by the requested topology level.
Part of #2724 
```release-note
NONE
```
=> TAS: skip flavor checks which don't have requested level

pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/raycluster/raycluster_controller_test.go, pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_controller_test.go, pkg/util/testingjobs/raycluster/wrappers.go
/kind bug
NumOfHosts is a new field we added to KubeRay RayCluster to support multi-host training / inference with accelerators like TPUs. Kueue needs to be updated to check NumOfHosts and appropriately adjust podset assignments if NumOfHosts is greater than 1 
Fixes #
```release-note
Account for NumOfHosts when calculating PodSet assignments for KubeRay jobs
```
=> [KubeRay] Support NumOfHosts when calculating PodSet assignments

test/e2e/singlecluster/tas_test.go
/kind bug
/kind flake
Fix "TopologyAwareScheduling when Creating a JobSet requesting TAS should admit a JobSet via TAS" e2e test.
Fixes #3406
```release-note
NONE
```
=> Fix "Should admit a JobSet via TAS" test.

cmd/experimental/kjobctl/docs/run_slurm.md
Update run_slurm.md docs.
Fixes #
```release-note
NONE
```
=> [kjobctl] Update run_slurm.md docs.

test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pod/suite_test.go
/kind cleanup
Merge managerSetup and managerAndSchedulerSetup.
Prepare for  #3409
```release-note
NONE
```
=> Optimize pod managerSetup.

apis/kueue/v1alpha1/tas_types.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, test/e2e/singlecluster/tas_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pod/suite_test.go
/kind feature
TAS: Enable for Pod integration.
Part of #3372
We need to manually add the `kueue.x-k8s.io/topology` scheduler gate and `kueue.x-k8s.io/tas` label for Pod integration, as Composable Job replacing current implementation of TAS. The idea is to add it on the Webhook Default() method.
```release-note
NONE
```
=> TAS: Enable for Pod integration.

cmd/experimental/kjobctl/pkg/builder/builder.go, cmd/experimental/kjobctl/pkg/builder/builder_test.go
/kind bug
Add validation for priority required field in kjobctl slurm mode.
Fixes #
```release-note
NONE
```
=> [kjobctl] Add validation for priority required field.

pkg/controller/jobs/mpijob/mpijob_controller.go, pkg/controller/jobs/mpijob/mpijob_controller_test.go, pkg/controller/jobs/mpijob/mpijob_webhook.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mpijob/suite_test.go
/kind feature
Support TAS for MPIJob.
Part of #3372
```release-note
NONE
```
=> TAS: Support MPIJob.

site/content/en/docs/concepts/_index.md, site/content/en/docs/concepts/topology_aware_scheduling.md, site/static/examples/tas/sample-job-preferred.yaml, site/static/examples/tas/sample-queues.yaml
Part of #2724 
I think it would also be useful to have a tasks page, but I'm unlikely to be able to write it before 0.9.0.
```release-note
NONE
```
=> TAS: Add documentation page for concepts

pkg/controller/jobframework/base_webhook_test.go
/kind cleanup
Use testGenericJob on testing BaseWebhook.
Part of #3372
This is prepare PR for #3414.
```release-note
NONE
```
=> Use testGenericJob on BaseWebhook tests.

test/integration/scheduler/podsready/scheduler_test.go
/kind bug
/kind flake
Fix "Scheduler with WaitForPodsReady Suite: [It] SchedulerWithWaitForPodsReady Short PodsReady timeout Should requeue a workload which exceeded the timeout to reach PodsReady=True" integration test.
Fixes #3366
Sometimes, `prodWl1` is already evicted on 
https://github.com/kubernetes-sigs/kueue/blob/236a1e4bfe7d291676918231c313ddf37d3550a8/test/integration/scheduler/podsready/scheduler_test.go#L223-L226
It happens because we are waiting for `prodWl2` to be waiting.
https://github.com/kubernetes-sigs/kueue/blob/236a1e4bfe7d291676918231c313ddf37d3550a8/test/integration/scheduler/podsready/scheduler_test.go#L218
```release-note
NONE
```
=> Fix "Should requeue a workload which exceeded the timeout to reach PodsReady=True" test.

pkg/cache/cache_test.go, pkg/queue/manager_test.go, pkg/util/wait/backoff_test.go
/kind cleanup
Add missed defer cancel() on unit tests.
Part of #3382
```release-note
NONE
```
=> Add missed defer cancel().

pkg/util/testing/error_matchers.go, test/integration/webhook/core/admissioncheck_test.go, test/integration/webhook/core/clusterqueue_test.go, test/integration/webhook/core/cohort_test.go, test/integration/webhook/core/localqueue_test.go, test/integration/webhook/core/resourceflavor_test.go, test/integration/webhook/core/workload_test.go, test/integration/webhook/jobs/job_webhook_test.go, test/integration/webhook/jobs/jobset_webhook_test.go, test/integration/webhook/jobs/mpijob_webhook_test.go, test/integration/webhook/jobs/raycluster_webhook_test.go, test/integration/webhook/jobs/rayjob_webhook_test.go
/kind cleanup
Make error matcher more verbosity.
Fixes #
The error matcher doesn't show actual error. This is an example https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3445/pull-kueue-test-multikueue-e2e-main/1853747452654391296.
```release-note
NONE
```
=> Make error matcher more verbosity.

test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/framework/framework.go
/kind cleanup
Use redundand specs flag for kubeflow integrations.
Fixes #
```release-note
NONE
```
=> TAS: Use redundand specs flag for kubeflow integrations.

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/multikueue/workload_test.go
/kind cleanup
Functionality redundant as being done by Workload Controller with workload.ResetChecksOnEviction() - 
`ResetChecksOnEviction sets all AdmissionChecks to Pending`.
Tested in "workload with retry checks should be evicted and checks should be pending”, thus "the local workload's admission check is set to Pending when it is in Retry without quota" test is no longer realizable.
Fixes #3359
```release-note
```
=> Delete redundant retry logic in MultiKueue controller.

test/integration/multikueue/multikueue_test.go
/kind bug
Update waitForWorkloadToFinishAndRemoteWorkloadToBeDeleted().
Check that both worker clusters had finished, only second one was checked so far.
```release-note
NONE
```
=> Fix MK integration test helper function

pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go
/kind cleanup
Reduce number of API requests in the Provisioning Controller
Fixes #3471
```release-note
NONE
```
=> Reduce number of API requests in the Provisioning Controller

pkg/controller/jobs/pod/pod_controller.go
/kind cleanup
Remove duplication of Named() function.
Fixes #
```release-note
NONE
```
=> Remove duplication of Named() function.

pkg/queue/cluster_queue_test.go
/kind cleanup
Explicitly tells us where `fakeClock` is used in the code
part of #3380 
This PR is work-in-progress. I've refactored the code inside `pkg/queue`. 
```release-note
NONE
```
=> [cleanup]: refactor code to show the use of fakeClock explicitly in pkg/queue(#3380)

site/content/en/docs/concepts/multikueue.md, site/content/en/docs/tasks/run/multikueue/job.md, site/content/en/docs/tasks/run/multikueue/jobsets.md, site/content/en/docs/tasks/run/multikueue/kubeflow.md, site/content/en/docs/tasks/run/multikueue/mpijob.md
Document how to use managedBy provided by the Job Controller.
Fixes #3357 
```release-note
NONE
```
=> [MultiKueue] Document batch/Job managedBy field usage

cmd/experimental/kjobctl/pkg/builder/builder.go, cmd/experimental/kjobctl/pkg/builder/interactive_builder.go, cmd/experimental/kjobctl/pkg/builder/job_builder.go, cmd/experimental/kjobctl/pkg/builder/ray_cluster_builder.go, cmd/experimental/kjobctl/pkg/builder/ray_job_builder.go, cmd/experimental/kjobctl/pkg/builder/slurm_builder.go, cmd/experimental/kjobctl/pkg/cmd/create/create_test.go
/kind cleanup
We don't need to add kueue labels to child objects like ConfigMap or Service.
Fixes #
```release-note
NONE
```
=> [kjobctl] Skip kueue labels on child objects.

Makefile, charts/kueue/README.md
Makes the helm OCI repo more discoverable.
```release-note
NONE
```
=> Add example using helm repo to helm installation guide

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go
/kind bug
Fixes #3494
I reproduced the same issue for JobSet, so this is not specific to MPIJob. Any Job is affected with multiple PodSets requesting the same RF using the same topology.
The issue was the capacity for non-leaf nodes was counted twice. The newly added test fails on the main branch, the workload gets admitted by with empty assignment.
```release-note
Fix computing the topology assignment for workloads using multiple PodSets requesting the same
topology. In particular, it was possible for the set of topology domains in the assignment to be empty,
and as a consequence the pods would remain gated forever as the TopologyUngater would not have
topology assignment information.
```
=> TAS: fix computing assignment when multiple PodSets

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go
Cherry pick of #3514 on release-0.9.
#3514: TAS: fix computing assignment when multiple PodSets
```release-note
Fix computing the topology assignment for workloads using multiple PodSets requesting the same
topology. In particular, it was possible for the set of topology domains in the assignment to be empty,
and as a consequence the pods would remain gated forever as the TopologyUngater would not have
topology assignment information.
```
=> Automated cherry pick of #3514: TAS: fix computing assignment when multiple PodSets

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/scheduler/preemption/preemption.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go, test/integration/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/controller/core/workload_controller_test.go
Cherry pick of #3350 on release-0.9.
#3350: reset admission check after deactivation
```release-note
Fix the flow of deactivation for workloads due to rejected AdmissionChecks. 
Now, all AdmissionChecks are reset back to the Pending state on eviction (and deactivation in particular), 
and so an admin can easily re-activate such a workload manually without tweaking the checks.
```
=> Automated cherry pick of #3350: reset admission check after deactivation

cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go, cmd/experimental/kjobctl/pkg/cmd/describe/helpers.go
/kind cleanup
This PR simplifies implementation of `describeConfigMap` by using `utilmaps.SortedKeys` and removing the `sortMapKeys` function.
```release-note
NONE
```
=> [kjobctl] refactor to use utilmaps.SortedKeys

pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/util/kubeversion/kubeversion.go, test/e2e/singlecluster/pod_test.go, test/integration/webhook/jobs/job_webhook_test.go
/kind cleanup
Removes skip of tests which are not supported on k8s with version less then 1.27, since we are running tests on 1.28+
Fixes #
Done per discussion here: https://github.com/kubernetes-sigs/kueue/pull/3001#discussion_r1800671498
```release-note
Kubernetes 1.27 is removed from supported Kubernetes versions
```
=> Remove kubernetes 1.27 from supported versions

pkg/resources/requests.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/scheduler_test.go
/kind cleanup
Simplifies FlavorAssigner in preparation for #3405
```release-note
Change, and in some scenarios fix, the status message displayed to user when a workload doesn't fit in available capacity.
```
=> Refactor FlavorAssigner

Makefile-test.mk
/kind cleanup
Remove `run-test-tas-e2e` from `test-e2e` target, as the target `test-tas-e2e` runs separately. 
Fixes #3480
```release-note
NONE
```
=> Remove run-test-tas-e2e from test-e2e

cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/tas/util.go, test/integration/controller/core/admissioncheck_controller_test.go, test/integration/controller/core/clusterqueue_controller_test.go, test/integration/controller/core/localqueue_controller_test.go, test/integration/controller/core/resourceflavor_controller_test.go, test/integration/controller/core/workload_controller_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/controller/jobs/rayjob/rayjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/scheduler/podsready/scheduler_test.go, test/integration/scheduler/scheduler_test.go, test/integration/scheduler/workload_controller_test.go
/kind cleanup
We are not generating docs with kubebuilder and this is not needed in tests.
```release-note
NONE
```
=> Remove kubebuilder:docs-gen marker from tests.

pkg/controller/tas/topology_ungater.go
/kind cleanup
To prepare for the support for ranks. 
Part of #3533
Part of #3450 
Here I split the `podsetPodsToUngate` function into 3 phases:
- listing the pods by `podsForPodSet`
- `assignGatedPodsToDomains` assigns gated pods to domains (for pods which are going to be ungated)
- `podsToUngateInfo` - translates the domainID information into node selectors for each pod to ungate
This allows to reuse easily the code for `podsForPodSet` and `podsToUngateInfo` in case of rank ordering.
The ideas is to split `assignGatedPodsToDomains` into two: `assignGatedPodsToDomainsGreedy` ( current), or `assignGatedPodsToDomainsWithRanks` (when ranks are available), but this will be follow up.
The follow up is WIP: https://github.com/kubernetes-sigs/kueue/pull/3539 - I added the …
=> TAS: cleanup TopologyUngater to prepare for ranks support

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler_test.go, test/integration/scheduler/scheduler_test.go
/kind bug
We fix the calculation of borrowing in FlavorAssignment for `Preemption` fit mode. Now, it matches how we calculate borrowing for `Fit` mode. This ensures that a workload which fits within its CQ's nominal capacity is sorted before an earlier created workload which pushes its CQ over nominal capacity. This sorting is important as this borrowing workload may invalidate the non-borrowing workload's preemption calculations
Fixes #3405
We tweak an integ test which relied on details of FlavorAssigner's borrowing calculations for ordering. By updating the priority of `pendingWl`, we ensure that it reservers resources and prevents  `blockedWl` from scheduling.
```release-note
Determine borrowing more accurately, allowing preempting workloads which fit in nominal quota to schedule …
```
=> Prioritize Workload which fits in its CQ's Nominal Capacity

pkg/cache/clusterqueue_snapshot.go, pkg/resources/requests.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler_test.go, test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/scheduler_test.go
I had to manually reimplement PotentiallyAvailable, as that was introduced with HierarchicalCohorts (0.9)
```release-note
- Change, and in some scenarios fix, the status message displayed to user when a workload doesn't fit in available capacity.
- Determine borrowing more accurately, allowing preempting workloads which fit in nominal quota to schedule faster
```
=> Cherry pick #3536 and #3547 to 0.8

test/e2e/singlecluster/statefulset_test.go
/kind bug
/kind flake
Fix StatefulSet created should allow to scale up after scale down to zero test
Fixes #3546
```release-note
NONE
```
=> Fix StatefulSet created should allow to scale up after scale down to zero test

pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go, test/e2e/tas/tas_test.go
/kind bug
Part of #3450 
```release-note
Fix running Job when parallelism < completions, before the fix the replacement pods for the successfully
completed Pods were not ungated.
```
=> TAS: fix scenario when parallelism < completions

pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go
/kind cleanup
Remove unnecessary manageJobsWithoutQueueName field on deployment webhook.
Prepare for #3555
```release-note
NONE
```
=> Remove unnecessary manageJobsWithoutQueueName field on deployment webhook.

pkg/controller/jobs/deployment/deployment_webhook.go
/kind cleanup
Use QueueNameForObject in Deployment Webhook to validate both QueueName Label and QueueName Annotation. 
Prepare for #3555
```release-note
NONE
```
=> Use QueueNameForObject in Deployment Webhook.

pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go
Cherry pick of #3559 on release-0.9.
#3559: TAS: fix scenario when parallelism < completions
```release-note
Fix running Job when parallelism < completions, before the fix the replacement pods for the successfully
completed Pods were not ungated.
```
=> Automated cherry pick of #3559: TAS: fix scenario when parallelism < completions

pkg/util/testingjobs/deployment/wrappers.go, test/e2e/config/common/controller_manager_config.yaml, test/e2e/singlecluster/deployment_test.go
/kind cleanup
Add Deployment e2e test.
Prepare for #3528
```release-note
NONE
```
=> Add Deployment e2e test.

pkg/controller/jobframework/validation.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/pod/pod_webhook.go
/kind bug
Add validation for Deployment queue-name to fail fast
Prepare #3528
```release-note
Added validation for Deployment queue-name to fail fast
```
=> Add validation for Deployment queue-name to fail fast

test/integration/webhook/jobs/deployment_webhook_test.go
Fix manageJobsWithoutQueueName on Deployment.
/kind cleanup
Optimize and extend deployment integration tests.
Prepare for #3528
```release-note
NONE
```
=> Optimize and extend deployment integration tests.

pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go
/kind feature
Part of #3533 
Part of #3450 
```release-note
TAS: support rank-ordering of Pods for the Kubernetes batch Job.
```
=> TAS: assign pods based on ranks for Job

pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go
/kind bug
Add validation for StatefulSet queue-name to fail fast.
Fixes #
```release-note
Added validation for StatefulSet queue-name to fail fast.
```
=> Add validation for StatefulSet queue-name to fail fast.

CHANGELOG/CHANGELOG-0.9.md
We previously suggested during KubeCon and on other occasions that Rank Ordering in TAS would be part of Kueue release `0.9.1`. Since the users are highly anticipating this feature and release `0.9.1` was released without it we want to make sure that we didn't mislead anyone and so that people don't waste their time testing feature which was not part of the release. That's why I'd like to request adding this note section to the `0.9.1` release notes to make things very clear.
```release-note
NONE
```
=> Added info to 0.9.1 about Rank Ordering being deferred to the next release

test/e2e/tas/tas_test.go
/kind cleanup
Part of #3450 
Part of #3533 
* I was also thinking about an alternative assert that `rack(pod0)==rack(pod1)` and `rack(pod2)==rack(pod3)`, but I think it will be harder to debug when the assert fails. With the exact assignment check we can easily see the full assignment.
* I have confirmed locally that when not using TAS the distributions of pods is completely random (I commented out setting the TopologyName and TAS PodSet annotation), then got:
```
[FAILED] Expected object to be comparable, diff:   map[string]string{
- 	"0": "kind-worker",
+ 	"0": "kind-worker5",
- 	"1": "kind-worker2",
+ 	"1": "kind-worker7",
"2": "kind-worker3",
"3": "kind-worker4",
}
```
I ran it a 4 times and it failed all repeats.
```release-note
NONE
```
=> TAS: add e2e tests for rank ordering for Job

CHANGELOG/CHANGELOG-0.9.md, Makefile, README.md, SECURITY-INSIGHTS.yaml, charts/kueue/Chart.yaml, site/hugo.toml
Cherry pick of #3573 on website.
#3573: Update latest version to v0.9.1
```release-note
NONE
```
=> Automated cherry pick of #3573: Update latest version to v0.9.1

pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go, pkg/util/testingjobs/jobset/wrappers.go, test/e2e/tas/jobset_test.go
/kind feature
Part of #3450 
Part of #3533 
I don't have e2e test yet, but getting early feedback would be great.
```release-note
TAS: support rank-based ordering for JobSet
```
=> TAS: support rank-based ordering for JobSet

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor.go, pkg/cache/tas_flavor_snapshot.go
/kind feature
/kind cleanup
- Optimizes memory used by `TASFlavorSnapshot` by deleting fields: sortName, childIDs, parentIDs
- Improves code clarity by moving fields which where previously 'perDomain' to the actual domain object
Fixes #3522 
```release-note
NONE
```
=> TAS: Clean up TAS flavor snapshot

pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pytorch_test.go, test/util/util.go
/kind feature
TAS: support rank-ordering for Kubeflow
Part of #3450
Part of #3533
```release-note
TAS: support rank-based ordering for Kubeflow
```
=> TAS: support rank-ordering for Kubeflow

pkg/controller/tas/resource_flavor.go
/kind bug
To fix the bug where Kueue drops reconcile events for the non-leading replica, due to the handling [here](https://github.com/kubernetes-sigs/kueue/blob/4bbddce73eb368caa54a6f570fed683f46fa78b6/pkg/controller/core/leader_aware_reconciler.go#L73-L89).
The reconciled type for the object was passed wrong (ClusterQueue instead of ResourceFlavor), and thus this was returning NotFound, and thus be ignored [here](https://github.com/kubernetes-sigs/kueue/blob/4bbddce73eb368caa54a6f570fed683f46fa78b6/pkg/controller/core/leader_aware_reconciler.go#L79C55-L82).
As a consequence, after a rolling restart, the previously non-leading replica would not perform Reconcile when becoming the leading replica (and the events where lost). Users could observe this as workloads stuck with the following …
=> TAS: fix dropping of reconcile events for non-leading replica

cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go, cmd/experimental/kjobctl/pkg/parser/slurm.go, cmd/kueuectl/app/list/list_pods_test.go, cmd/kueuectl/app/list/list_workload_test.go
/kind cleanup
This PR refactors code by replacing `bytes.NewReader([]byte(str))` with `strings.NewReader(str)` to avoid extra allocation and shorten statements.
```release-note
NONE
```
=> Replace bytes.NewReader with strings.NewReader

.golangci.yaml, cmd/experimental/kjobctl/cmd/kjobctl-docs/generators/doc.go, cmd/kueuectl-docs/generators/doc.go, pkg/cache/tas_flavor_snapshot.go, pkg/controller/tas/topology_ungater.go, pkg/util/testing/client.go
/kind cleanup
Simplify code by replacing `strings.Compare` with `cmp.Compare` or string comparison operators.
https://pkg.go.dev/cmp#Compare
The PR enables `gocritic.stringsCompare` to automatically search for unnecessary `strings.Compare`.
```release-note
NONE
```
=> Simplify functions by removing strings.Compare

cmd/importer/pod/check.go, cmd/importer/util/util.go, cmd/kueuectl/app/create/create_clusterqueue.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/snapshot.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/resourceflavor_controller.go, pkg/controller/tas/resource_flavor.go
/kind cleanup
A ResourceFlavor name is referenced in different ways through the code, either as a `ResourceFlavorReference` or as a `string`.  This PR ensures that only `ResourceFlavorReference` is used unless a cast to string is absolutely necessary.
Fixes #3491
```release-note
NONE
```
=> Use ResourceFlavorReference for ResourceFlavor names

charts/kueue/templates/webhook/webhook.yaml, config/components/webhook/manifests.yaml, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/util/testingjobs/deployment/wrappers.go, test/e2e/singlecluster/deployment_test.go, test/integration/webhook/jobs/deployment_webhook_test.go
/kind feature
Allow mutating queue name in Deployment Webhook.
Fixes #3552
```release-note
Allow mutating the queue-name label for non-running Deployments.
```
=> Allow mutating queue name in Deployment Webhook.

cmd/kueue/main.go, pkg/controller/admissionchecks/multikueue/controllers.go, pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go, pkg/controller/admissionchecks/multikueue/workload_test.go, pkg/controller/jobframework/integrationmanager.go, test/integration/multikueue/multikueue_test.go, test/integration/multikueue/suite_test.go
/kind bug
MK adapter didn't contain the condition to only allow enabled integrations.
Thus while using multi cluster setup, all registered MK adapters were used to setup controllers.
In result we get `ClientConnectionFailed error with no matches for kind "XYZ" in "version v1" message`
Fixes #3582
```release-note
Fix the bug which prevented the use of MultiKueue if there is a CRD which is not installed
and removed from the list of enabled integrations.
```
=> [MultiKueue] fix using MultiKueue when some integrations are disabled

cmd/kueue/main.go, pkg/controller/admissionchecks/multikueue/controllers.go, pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go, pkg/controller/admissionchecks/multikueue/workload_test.go, pkg/controller/jobframework/integrationmanager.go, test/integration/multikueue/multikueue_test.go, test/integration/multikueue/suite_test.go
Cherry pick of #3603 on release-0.9.
#3603: GetMultiKueueAdapters() returns only registered and enabled 
Manually resolved conflict:
Remove  fakeClock from `TestWlReconcile`
```release-note
Fix the bug which prevented the use of MultiKueue if there is a CRD which is not installed
and removed from the list of enabled integrations.
```
=> Automated cherry pick of #3603: [MultiKueue] fix using MultiKueue when some integrations are disabled

test/e2e/tas/job_test.go
/kind bug
/kind flake
Fixes #3620
```release-note
NONE
```
=> TAS: fix panic in e2e test when parallelism < completions

test/e2e/singlecluster/deployment_test.go
/kind bug
/kind bug
/kind flake
Fixes #3626
```release-note
NONE
```
=> Fix should admit workloads after change queue-name if AvailableReplicas = 0 test.

test/e2e/singlecluster/visibility_test.go
/kind cleanup
It would be better to use the Gomega matcher instead of directly comparing reasons.
Fixes #
I confirmed that e2e testings failed if we specify the incorrect error reason.
```shell
Kueue visibility server when A subject is bound to kueue-batch-user-role, but not to kueue-batch-admin-role Should return an appropriate error
/Users/tenzen/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:555
STEP: Wait for ResourceNotFound error instead of Forbidden to make sure the role bindings work @ 11/26/24 15:58:06.764
STEP: Returning a Forbidden error due to insufficient permissions for the ClusterQueue request @ 11/26/24 15:58:06.768
[FAILED] in [It] - /Users/tenzen/go/src/sigs.k8s.io/kueue/test/e2e/singlecluster/visibility_test.go:559 @ 11/26/24 15:58:06.769
• [FAILED] …
```
=> Use gomega Matcher in the visibility E2E testings

apis/kueue/v1alpha1/tas_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml, config/components/crd/bases/kueue.x-k8s.io_topologies.yaml
/kind bug
Make topology levels immutable to prevent issues with inconsistent state of the TAS cache.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3615#issuecomment-2497280353.
```release-note
Make topology levels immutable to prevent issues with inconsistent state of the TAS cache.
```
=> Make topology levels immutable.

keps/79-hierarchical-cohorts/README.md
/kind cleanup
I refined the Hierarchical Cohort KEP to align with actual APIs in the following:
- Make `.spec.parent` non pointer
- Remove Status
For the status, we should reconsider and clarify the status implementation and how we can expose those stats when we decide to implement it in the future.
Fixes #
```release-note
NONE
```
=> Sync KEP and actual APIs for Hierarchical Cohort

test/e2e/tas/job_test.go
/kind cleanup
Use g.Expect instead of gomega.Expect on gomega.Eventually.
Fixes #
```release-note
NONE
```
=> Use g.Expect instead of gomega.Expect on gomega.Eventually.

pkg/cache/tas_flavor.go, pkg/controller/tas/indexer/indexer.go, pkg/controller/tas/resource_flavor.go, test/integration/tas/tas_test.go
/kind bug
Fixed bug that doesn't allow to update cache on delete Topology.
Fixes #3614
```release-note
TAS: Fixed bug that doesn't allow to update cache on delete Topology.
```
=> TAS: Update cache on delete Topology.

pkg/cache/cache_test.go, pkg/cache/tas_cache_test.go, pkg/scheduler/scheduler_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pytorch_test.go
/kind cleanup
Instead of self-defined "kubernetes.io/hostname", we use the core API hostname label.
Fixes #
```release-note
NONE
```
=> Reuse the core API hostname node label

test/e2e/multikueue/e2e_test.go
Fix one issue on multikueue e2e test related to expected empty strings.
Fixes #3664 
```release-note
NONE
```
=> Fix multikueue e2e test failure due to empty strings

pkg/controller/jobframework/base_webhook.go, pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/mpijob/mpijob_webhook.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/webhooks/clusterqueue_webhook.go, pkg/webhooks/cohort_webhook.go, pkg/webhooks/resourceflavor_webhook.go, pkg/webhooks/workload_webhook.go
/kind cleanup
I removed the redundant logging information in the webhooks.
The controller runtime has already added the inflight object information into loggers.
This is similar to https://github.com/kubernetes-sigs/kueue/pull/3576.
Actually, we can observe the redundant loggings in the followings:
```
Validating create	{
"webhookGroup": "ray.io",
"webhookKind": "RayJob",
"RayJob": {
"name": "parent-job",
"namespace": "raycluster-xg8h7"
},
"namespace": "raycluster-xg8h7",
"name": "parent-job",
"resource": {
"group": "ray.io",
"version": "v1",
"resource": "rayjobs"
},
"user": "admin",
"requestID": "ca808e9c-0102-401c-804c-ce7f217a927e",
"job": {
"name": "parent-job",
"namespace": "raycluster-xg8h7"
}
}
```
```
Validating update	{
"webhookGroup": "kubeflow.org",
"webhookKind": "PyTorchJob", …
```
=> Remove redundant inflight object informations from webhook loggings

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/controller/tas/topology_ungater.go, pkg/controller/tas/topology_ungater_test.go
/kind feature
Reduce the amount of sorting as in TAS Snapshot it's done only once . Account for future changes regarding #3671 
Part of #3671 
```release-note
NONE
```
=> TAS: Move sorting domains lexicographically from TopologyUngater to TAS Snapshot

pkg/cache/tas_flavor.go, pkg/cache/tas_flavor_snapshot.go
/kind cleanup
To move the code for adding node into one place rather than scattered across two functions.
It will make the support for taints easier as the TAS snapshot will be aware of node level.
Prepare for #3658 
```release-note
NONE
```
=> TAS: introduce addNode function to prepare for taints support

pkg/controller/tas/topology_ungater.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> TAS: TopologyUngater clean up for Pod groups

keps/3589-manage-jobs-selectively/README.md, keps/3589-manage-jobs-selectively/kep.yaml
/kind feature
KEP to propose a design for #3589 
```release-note
NONE
```
=> KEP 3589: Uniformly filter manageJobsWithoutQueueNames by namespace

pkg/cache/tas_cache_test.go, pkg/util/testingjobs/node/wrappers.go
/kind cleanup
Creating nodes for testing is quite verbose. This PR introduces the `NodeWrapper` to make them their creation more compact.
Fixes #3661 
This PR only refactors **one test file**. Adding the wrapper and refactoring all test files that create Node objects at once would make the PR too lengthy and difficult to review. The remaining test files will be refactored in a follow-up PR.
```release-note
NONE
```
=> Add NodeWrapper for testing

pkg/scheduler/scheduler_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/tas/tas_test.go
/kind cleanup
This PR replaces the Node object creation in the test files by the `NodeWrapper` to keep consistency and make the code more compact
Fixes #3661 
This is a follow-up of the #3689 PR
```release-note
NONE
```
```
=> Use NodeWrapper in test files

test/e2e/tas/pod_group_test.go
/kind bug
/kind flake
Fix e2e pod-group TAS tests
Fixes #3695
Fixes #3696 
```release-note
NONE
```
=> Fix pod-group tas tests

pkg/cache/cohort_snapshot.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go
/kind bug
Previously, we were only gathering preemption candidates from the nearest Cohort of the ClusterQueue. We update this logic to find ClusterQueues from the entire Cohort Tree.
Fixes #3583
```release-note
Fix preemption when using Hierarchical Cohorts by considering as preemption candidates workloads
from ClusterQueues located further in the hierarchy tree than direct siblings.
```
=> Fix preemption.findCandidates for Hierarchical Cohorts

apis/kueue/v1alpha1/tas_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_topologies.yaml, config/components/crd/bases/kueue.x-k8s.io_topologies.yaml, test/integration/tas/tas_test.go
/kind feature
Validate that kubernetes.io/hostname can only be at the lowest level in Topology.
Fixes #3688
```release-note
TAS: validate that kubernetes.io/hostname can only be at the lowest level
```
=> TAS: validate that kubernetes.io/hostname can only be at the lowest level

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go
/kind bug
Fixes #3721 
```release-note
NONE
```
=> Fix assigning ResourceFlavor tolerations during assignment

keps/2936-local-queue-defaulting/README.md, keps/2936-local-queue-defaulting/kep.yaml
issue #2936 
```release-note
NONE
```
cc: @mimowo @mwielgus @PBundyra
=> KEP-2936: LocalQueue defaulting

pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/util/pod/pod.go, pkg/util/pod/pod_test.go
/kind cleanup
Use ReadUIntFromLabelWithMax to get and validate pod index.
Fixes #3651
```release-note
NONE
```
=> Use ReadUIntFromLabelWithMax to get and validate pod index.

site/content/en/docs/installation/_index.md
/cleanup
Fixes table indenting caused by GitHub merge of review comment on previous PR
Fixes #
```release-note
NONE
```
=> fix table indenting

pkg/controller/admissionchecks/multikueue/workload_test.go, pkg/controller/jobs/job/job_multikueue_adapter.go, pkg/controller/jobs/job/job_multikueue_adapter_test.go
/kind bug
/kind flake
Adds a check when syncing jobs on multikueue to avoid trying to patch the spec before resuming the job.
Fixes #3581 
```release-note
Fix a bug which occasionally prevented updates to the PodTemplate of the Job on the management cluster
when starting a Job (e.g. updating nodeSelectors), when using `MultiKueueBatchJobWithManagedBy` enabled.
```
=> Fix live-updates for kubernetes Job getting stuck occasionally

pkg/controller/tas/indexer/indexer.go, pkg/util/slices/slices.go, pkg/util/tas/tas.go, pkg/util/testingjobs/node/wrappers.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/tas/tas_test.go, test/util/util.go
/kind cleanup
Remove node.kubernetes.io/not-ready taint if status active after creation.
Fixes #3709
```release-note
NONE
```
=> Remove node.kubernetes.io/not-ready taint if status active after creation.

hack/e2e-common.sh, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/statefulset/statefulset_reconciler.go, pkg/controller/jobs/statefulset/statefulset_reconciler_test.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/pod/wrappers.go, pkg/util/testingjobs/statefulset/wrappers.go, site/content/en/docs/reference/labels-and-annotations.md, test/e2e/singlecluster/statefulset_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/util/e2e.go
/kind bug
Fix rolling update for StatefulSet integration
Fixes #3690
```release-note
Fixed rolling update for StatefulSet integration
```
=> Fix rolling update for StatefulSet integration

keps/976-plain-pods/README.md
Add Serving Workload section on plain pod KEP.
Part of https://github.com/kubernetes-sigs/kueue/issues/3690
```release-note
NONE
```
=> Add Serving Workload section on KEP-976.

test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/pod_group_test.go
/kind cleanup
/kind flake
Check object deletion in e2e TAS tests
Fixes #3695 
```release-note
NONE
```
=> Check resource deletion in tas e2e tests

apis/kueue/v1beta1/resourceflavor_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml, config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml, test/integration/tas/tas_test.go
/kind feature
TAS: Make ResourceFlavorSpec that defines `topologyName` immutable
Part of #3733 
```release-note
ResourceFlavorSpec that defines topologyName is not immutable
```
=> TAS: Make ResourceFlavorSpec that defines `topologyName` immutable

charts/kueue/README.md, charts/kueue/values.yaml, cmd/experimental/podtaintstolerations/config/deployment.yaml, config/default/manager_auth_proxy_patch.yaml
/kind cleanup
Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
For more details: https://github.com/kubernetes-sigs/kubebuilder/discussions/3907
Part of #3737
```release-note
Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
```
=> Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.

charts/kueue/README.md, charts/kueue/values.yaml, cmd/experimental/podtaintstolerations/config/deployment.yaml, config/default/manager_auth_proxy_patch.yaml
Cherry pick of #3747 on release-0.8.
#3747: Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
```release-note
Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.
```
=> Automated cherry pick of #3747: Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy with registry.k8s.io/kubebuilder/kube-rbac-proxy.

pkg/cache/cache_test.go, pkg/cache/clusterqueue_test.go, pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go, test/e2e/singlecluster/tas_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/tas/tas_test.go
/kind cleanup
Change Levels method of TopologyWrapper to the variadic function to ease the declaration process.
Part of #3662 
```release-note
NONE
```
=> Use variadic function to set levels in TopologyWrapper

site/content/en/docs/tasks/manage/enforce_job_management/_index.md, site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md, site/content/en/docs/tasks/manage/enforce_job_management/setup_job_admission_policy.md, site/static/examples/sample-validating-policy.yaml
Document how to use `manageJobsNamespaceSelector` in conjunction with `manageJobsWithoutQueueName`
Part of #3589. 
```release-note
NONE
```
=> document manageJobsNamespaceSelector

pkg/controller/jobframework/defaults.go, pkg/controller/jobframework/defaults_test.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go
/kind feature
Normalizes handling of manageJobsWithoutQueueName and managedJobsNamespaceSelector for the Pods, Deployment, and StatefulSet integrations.
Part of #3589 
```release-note
NONE
```
=> managedJobsNamespaceSelector for Deployment, StatefulSets, and Pods

pkg/controller/core/clusterqueue_controller.go
/kind cleanup
Replaces `time.Now()` to use the Now() function present inside `clock` package.
Part of #3380
This PR is work-in-progress. 
```release-note
NONE
```
=> Replace time.Now() with clock.Now() in pkg/core

pkg/controller/constants/constants.go, pkg/controller/jobframework/base_webhook.go, pkg/controller/jobframework/base_webhook_test.go, pkg/controller/jobframework/defaults.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, pkg/controller/jobs/mpijob/mpijob_webhook.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/features/kube_features.go, pkg/queue/local_queue.go, pkg/queue/manager.go, site/content/en/docs/installation/_index.md, test/integration/controller/jobs/pod/suite_test.go, test/integration/controller/jobs/raycluster/suite_test.go
/kind feature
Fixes #2936
```release-note
If LocalQueueDefaulting feature gate is set to true, the LocalQueue with name default will be used as default LocalQueue in the corresponding namespace"
```
cc: @mwielgus @KPostOffice
=> Implement default LocalQueue

test/integration/scheduler/scheduler_test.go
/kind flake
Make sure previous workload has finished so cq has enough resources for another workload.
To avoid flaky test.
Fixes #3633
```release-note
NONE
```
=> [Flaky] Integration tests - Using cohorts for sharing unused resources 

pkg/controller/jobframework/defaults.go
/kind cleanup
Injecting a default queue-name that we will then ignore because the owner is managed by Kueue
will be confusing to users.
Fixes #
```release-note
NONE
```
=> Do not default the queue-name for jobs with kueue managed owners

pkg/cache/cache_test.go, pkg/scheduler/scheduler_test.go, pkg/util/testing/defaults.go, test/e2e/singlecluster/tas_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go, test/e2e/tas/statefulset_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/tas/tas_test.go
/kind cleanup
Add default one, two and three level Topologies to be used in tests.
Fixes #3662 
```release-note
NONE
```
=> Add default topologies for tests

apis/kueue/v1beta1/clusterqueue_types.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/core.go, pkg/controller/tas/resource_flavor.go, pkg/queue/manager.go, test/integration/tas/tas_test.go
/kind feature
/kind bug
Fixes #3645 
```release-note
TAS: The CQ referencing a Topology is deactivated if the topology does not exist.
```
=> Deactivate ClusterQueue if there is no Topology

pkg/controller/jobframework/integrationmanager.go
/kind bug
To address https://github.com/kubernetes-sigs/kueue/pull/3803/files#r1879511754 which could be sometimes an issue when installing a new integration
No need for release note because it was not released yet.
```release-note
NONE
```
=> Use lock when accessing IsIntegrationEnabled

pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/deployment/wrappers.go, pkg/util/testingjobs/statefulset/wrappers.go
/kind cleanup
To address https://github.com/kubernetes-sigs/kueue/pull/3803/files#r1879550890
No need for release note as this has not been released yet.
```release-note
NONE
```
=> Use annotation rather than label for serving workloads

pkg/controller/core/clusterqueue_controller_test.go, pkg/controller/core/workload_controller.go, pkg/queue/manager.go, pkg/queue/manager_test.go, pkg/visibility/api/v1beta1/pending_workloads_cq_test.go, pkg/visibility/api/v1beta1/pending_workloads_lq_test.go
/kind cleanup
Fixes #3527 
It added some log output for better debugging without breaking the function..
NONE
```release-note
Fix misleading log messages from workload_controller indicating not existing LocalQueue or
Cluster Queue. For example "LocalQueue for workload didn't exist or not active; ignored for now"
could also be logged the ClusterQueue does not exist.
```
=> Added Log output for LocalQueue and ClusterQueue

pkg/controller/core/clusterqueue_controller_test.go, pkg/controller/core/workload_controller.go, pkg/queue/manager.go, pkg/queue/manager_test.go, pkg/visibility/api/v1alpha1/pending_workloads_cq_test.go, pkg/visibility/api/v1alpha1/pending_workloads_lq_test.go, pkg/visibility/api/v1beta1/pending_workloads_cq_test.go, pkg/visibility/api/v1beta1/pending_workloads_lq_test.go
This is an manual cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/3605
Fixes #
```release-note
Fix misleading log messages from workload_controller indicating not existing LocalQueue or
Cluster Queue. For example "LocalQueue for workload didn't exist or not active; ignored for now"
could also be logged the ClusterQueue does not exist.
```
=> [release-0.9] [Manual cherry-pick] 1Added Log output for LocalQueue and ClusterQueue

apis/kueue/v1beta1/clusterqueue_types.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/core.go, pkg/controller/tas/resource_flavor.go, pkg/queue/manager.go, test/integration/tas/tas_test.go
Cherry pick of #3770 on release-0.9.
#3770: Deactivate ClusterQueue if there is no Topology
```release-note
TAS: The CQ referencing a Topology is deactivated if the topology does not exist.
```
=> Automated cherry pick of #3770: Deactivate ClusterQueue if there is no Topology

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/multikueue/workload_test.go
/kind bug
Fixes #3818 
I have unit tests added and they fail without the change:
```
--- FAIL: TestWlReconcile (0.22s)
--- FAIL: TestWlReconcile/deleted_MultiKueue_workload_is_deleted_from_cache_-_the_worker_will_be_deleted_by_GC (0.01s)
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/workload_test.go:1166: unexpected deletedWlCache len 1 expecting 0
--- FAIL: TestWlReconcile/deleted_regular_workload_is_removed_from_the_cache (0.01s)
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/workload_test.go:1166: unexpected deletedWlCache len 1 expecting 0
```
```release-note
Fix memory leak due to workload entries left in MultiKueue cache. The leak affects the 0.9.0 and 0.9.1 
releases …
```
=> Fix memory leak due to workload entries left in MultiKueue cache

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/multikueue/workload_test.go
Cherry pick of #3835 on release-0.9.
#3835: Fix memory leak due to workload entries left in MultiKueue cache
```release-note
Fix memory leak due to workload entries left in MultiKueue cache. The leak affects the 0.9.0 and 0.9.1 
releases which enable MultiKueue by default, even if MultiKueue is not explicitly used on the cluster.
```
=> Automated cherry pick of #3835: Fix memory leak due to workload entries left in MultiKueue cache

pkg/controller/core/workload_controller.go, pkg/queue/manager.go, pkg/queue/manager_test.go
/kind cleanup
In the https://github.com/kubernetes-sigs/kueue/pull/3605, we dropped the inactive LocalQueue and ClusterQueue reason.
But we still face errors in situations where those are inactive.
Additionally, we should not omit errors verifications in testing.
Fixes #
```release-note
NONE
```
=> Distinguish errors for non-existing LocalQueue and ClusterQueue in the workload-controller

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/controller/tas/constants.go, pkg/controller/tas/controllers.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, test/e2e/singlecluster/tas_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/controller/jobs/mxjob/mxjob_controller_test.go, test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/tas/tas_test.go
/kind feature
Use `kueue.x-k8s.io/resource-in-use` finalizer for Topology.
Fixes #3821
```release-note
NONE
```
=> Use kueue.x-k8s.io/resource-in-use finalizer for Topology.

pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_controller_test.go, pkg/util/testingjobs/rayjob/wrappers.go, test/integration/controller/jobs/rayjob/rayjob_controller_test.go, test/integration/webhook/jobs/raycluster_webhook_test.go
/kind bug
RayJob by default creates a "submitter" Job that runs "ray job submit"  against the provisioned Ray Cluster. However, we never accounted for the resources used by this Job in the RayJob PodSets. In many cases this is fine since the submitter Job only uses 500m CPUs but in resource constraint clusters it can prevent the RayJob from running. This PR ensures that we are always accounting for the submitter Job in the RayJob PodSets. 
Fixes #1434 
```release-note
PodSets for RayJobs now account for submitter Job when spec.submissionMode=k8sJob is used.
ACTION REQUIRED: if you used the RayJob integration you may need to revisit your quota settings, 
because now Kueue accounts for the resources required by the KubeRay submitter Job
when the spec.submissionMode=k8sJob (by default 500m …
```
=> Add RayJob submitter job into PodSets

CHANGELOG/CHANGELOG-0.10.md, Makefile, README.md, charts/kueue/Chart.yaml, charts/kueue/README.md, site/hugo.toml
Cherry pick of #3863 on website.
#3863: Update latest kueue v0.10.0
```release-note
NONE
```
=> Automated cherry pick of #3863: Update latest kueue v0.10.0

pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go
/kind cleanup
Move topologyHandler logic to topology controller.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3824#discussion_r1884240482.
```release-note
NONE
```
=> Move topologyHandler logic to topology controller.

cmd/kueue/main.go
/kind bug
The call to load the configuration file was accidently moved to before the call to `ctrl.SetLogger()` in #3805.  As a result, the log message that dumped the manager configuration went to /dev/null. 
Fixes #
```release-note
Fixes a bug in 0.10.0 which resulted in the kueue manager configuration not being logged. 
```
=> fix logging of manager configuration

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/controller/tas/topology_controller.go
Report errors like this:
```
{"level":"error","ts":"2024-12-26T05:32:34.012480568Z","caller":"controller/controller.go:316","msg":"Reconciler error","controller":"tas-topology-controller","controllerGroup":"kueue.x-k8s.io","controllerKind":"Topology","Topology":{"name":"default"},"namespace":"","name":"default","reconcileID":"276f685c-1d43-4d07-bf1a-2a062eee43bf","error":"topologies.kueue.x-k8s.io \"default\" is forbidden: User \"system:serviceaccount:kueue-system:kueue-controller-manager\" cannot update resource \"topologies\" in API group \"kueue.x-k8s.io\" at the cluster scope","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/ …
```
=> Fix: kueue-manager-role can not update topologies

pkg/controller/jobframework/reconciler.go, pkg/scheduler/scheduler.go, pkg/workload/workload.go, pkg/workload/workload_test.go, test/integration/controller/jobs/job/job_controller_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/integration/controller/jobs/pod/pod_controller_test.go, test/performance/scheduler/runner/controller/controller.go, test/util/util.go
/kind cleanup
Replaces `time.Now()` to use the Now() function present inside `clock` package.
Part of #3380
This PR is work-in-progress. 
```release-note
NONE
```
=> Replace `time.Now()` with `clock.Clock.Now()` in pkg/workload/workload.go

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/util/cert/cert.go, pkg/visibility/server.go
VAP is a default admission plugin enabled while starting an API server for visibility ([ref](https://github.com/kubernetes-sigs/kueue/blob/95bc3b28da49862186f5e38924e1507ce4b7c703/pkg/visibility/server.go#L75)). The Kueue
controller has additional permissions to watch those GVKs even though it is not required. Disabling the plugin from api server helps in keeping it minimal and maintaining compatibility with previous versions of K8s.
For details:
By default, the admission server enables the default set of admission plugins while starting an API server in K8s: https://github.com/kubernetes/kubernetes/blob/e85c72d4177fba224cb1baa1b5abfb5980e6d867/pkg/kubeapiserver/options/admission.go#L59. However, all the plugins are not necessary, as the visibility server is publishing metrics though …
=> [Fix] Remove the requirement for VAP

keps/349-all-or-nothing/README.md
Reverts kubernetes-sigs/kueue#3882
/kind cleanup
The API change was accidentally added in the https://github.com/kubernetes-sigs/kueue/pull/3882 to the KEP.
The `Requeue` state API was added by the KEP-1282: Pods Ready Requeue Strategy https://github.com/kubernetes-sigs/kueue/tree/main/keps/1282-pods-ready-requeue-strategy#workload
Fixes #
```release-note
NONE
```
=> Revert "Add section about Workload's requeueState field to KEP#349"

test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Fix "Pod groups when Single CQ should allow to preempt the lower priority group" flaky test.
Fixes #3915
```release-note
NONE
```
=> Fix "should allow to preempt the lower priority group" test.

Makefile
/kind bug
At push time, the `debug` image is not tagged with `main`. This causes the `dump_cache.sh` script to fail because it [references the `main` tag by default](https://github.com/kubernetes-sigs/kueue/blob/4c2a0cddc35b80995653c24a9fe85cb57743179f/hack/dump_cache.sh#L25)
Fixes #3873
```release-note
NONE
```
=> Publish the debug:main image

pkg/cache/tas_flavor_snapshot.go, pkg/resources/requests.go, pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go
/kind bug
Fixes https://github.com/kubernetes-sigs/kueue/issues/3887
```release-note
None
```
=> Fix: TAS assignment error

pkg/cache/tas_flavor_snapshot.go, pkg/resources/requests.go, pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go
/kind bug
This is an manual cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/3937
```release-note
Fix building TAS assignments for workloads with multiple PodSets (eg. JobSet or kubeflow Jobs). The assignment was computed independently for the PodSets which could result in conflicts rendering the pods unschedulable by the kube-scheduler.
```
=> [release-0.9] Fix: TAS assignment error

pkg/controller/tas/topology_controller.go, test/integration/tas/tas_test.go
/kind bug
/kind flake
After removing the finalizers in the topology they were re-added which caused the resource not to be deleted.
Fixes #3890 
```release-note
NONE
```
=> Do not add finalizer to the topology after removal

test/integration/multikueue/multikueue_test.go
/kind bug
Fixes #3841
```release-note
NONE
```
=> MultiKueue: add tests to show worker workloads are deleted when MK AC is rejected

README.md
This pull request fixes the link to the `examples` directory in the README.
Fixes #3976 
```release-note
NONE
```
=> Fix link to examples directory in README

pkg/controller/core/localqueue_controller.go, test/integration/controller/core/localqueue_controller_test.go, test/util/util.go
/kind bug
Local queue resource metrics are now registered correctly.
Part of #3746 
```release-note
Fix populating the LocalQueue metrics: `kueue_local_queue_resource_usage` and `kueue_local_queue_resource_reservation`.
```
=> Register local queue resource metrics

Makefile-deps.mk, Makefile-test.mk, charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, hack/e2e-common.sh, hack/multikueue-e2e-test.sh, pkg/controller/jobframework/validation.go, pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go, pkg/util/testingjobs/rayjob/wrappers.go, site/static/examples/multikueue/create-multikueue-kubeconfig.sh, test/e2e/multikueue/e2e_test.go, test/e2e/multikueue/suite_test.go, test/integration/controller/jobs/raycluster/suite_test.go, test/integration/controller/jobs/rayjob/suite_test.go, test/integration/webhook/jobs/suite_test.go, test/util/e2e.go
/kind feature
We want to be able to run Kuberay workloads RayJob in MultiKueue.
RayCluster will come as separate PR.
Testing: 
Unit and multikueue e2e tests are provided.
Multikueue integration tests will be provided in separate PR - agreed with @mimowo.
Relates to  #3822
```release-note
Support RayJob in MultiKueue, assuming only Ray CRDs are installed on the management cluster.
```
=> [Feature] Kuberay RayJob MultiKueue adapter 

pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/statefulset/wrappers.go
/kind bug
Allow to change replicas  in StatefulSet without queue-name.
Fixes #3996
```release-note
Fix bug that doesn't allow scaling StatefulSets which aren't managed by Kueue
```
=> [StatefulSet] Allow to change replicas without queue-name.

pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/statefulset/wrappers.go
Cherry pick of #3991 on release-0.9.
#3991: [StatefulSet] Allow to change replicas without queue-name.
```release-note
Fix the bug that prevented scaling StatefulSets which aren't managed by Kueue when the "statefulset" integration is enabled.
```
=> Automated cherry pick of #3991: [StatefulSet] Allow to change replicas without queue-name.

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/util/cert/cert.go, pkg/visibility/server.go
Cherry-pick: https://github.com/kubernetes-sigs/kueue/pull/3908
Fixes #
```release-note
Disable the unnecessary Validating Admission Policy for the visibility server, and drop the associated RBAC permissions to make the server minimal. This also prevents periodic error logging on clusters above Kubernetes 1.29+.
```
=> Cherry-pick #3908: Fix the requirement for VAP

site/content/en/docs/concepts/admission_check.md
Add one of the following kinds:
Optionally add one or more of the following kinds if applicable:
adding  how to `adminssionCheck ` doc link 
Fixes #
```release-note
NONE
```
=> doc: add admissionCheck example link

test/integration/multikueue/multikueue_test.go
Reverts kubernetes-sigs/kueue#3938
Due to reported issue #4003 
```release-note
NONE
```
=> Revert "MultiKueue: add tests to show worker workloads are deleted when MK AC is rejected"

test/integration/controller/jobs/job/job_controller_test.go, test/integration/multikueue/multikueue_test.go
/kind bug
Fix integration tests fail after upgrade to 1.32.
Fixes #4027
```release-note
NONE
```
=> Fix integration tests fail after upgrade to 1.32.

pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
/kind bug
same like https://github.com/kubernetes-sigs/kueue/pull/3980 but for leaderworkerset
Fixes #
```release-note
NONE
```
=> fix: propagate priority-class label for leaderworkerset

pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go
/kind bug
Due to file modification conflicts, cherry-pick was manually performed at https://github.com/kubernetes-sigs/kueue/pull/3980
Fixes #
```release-note
Propagate the top-level setting of the `kueue.x-k8s.io/priority-class` label to the PodTemplate for
Deployments and StatefulSets. This way the Workload Priority class is no longer ignored by the workloads.
```
=> cherry-pick for 0.10: fix: propagate priority-class label for deploy and statefulset

pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go
/kind bug
Due to file modification conflicts, cherry-pick was manually performed at https://github.com/kubernetes-sigs/kueue/pull/3980
Fixes #
```release-note
Propagate the top-level setting of the `kueue.x-k8s.io/priority-class` label to the PodTemplate for
Deployments and StatefulSets. This way the Workload Priority class is no longer ignored by the workloads.
```
=> cherry-pick for 0.9: fix: propagate priority-class label for deploy and statefulset

pkg/controller/jobframework/validation.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_multikueue_adapter.go, pkg/controller/jobs/pod/pod_multikueue_adapter_test.go, site/static/examples/multikueue/create-multikueue-kubeconfig.sh, test/e2e/multikueue/e2e_test.go, test/e2e/multikueue/suite_test.go, test/integration/multikueue/multikueue_test.go, test/integration/multikueue/suite_test.go
/kind feature
This PR adds the Pod MultiKueue adapter allowing for the scheduling and up to date statuses of pods running on remote clusters.
This PR covers a particular implementation discussed in #3802 which is gating the pod on the management cluster and supporting status updates.
Part of #3802
```release-note
Support Pod integration in MultiKueue.
```
=> [MultiKueue] Add Pod MK adapter

Makefile-test.mk, test/integration/controller/admissionchecks/provisioning/suite_test.go, test/integration/controller/core/suite_test.go, test/integration/controller/jobframework/setup/setup_controllers_test.go, test/integration/controller/jobframework/setup/suite_test.go, test/integration/controller/jobs/appwrapper/suite_test.go, test/integration/controller/jobs/job/suite_test.go, test/integration/controller/jobs/jobset/suite_test.go, test/integration/controller/jobs/mpijob/suite_test.go, test/integration/controller/jobs/mxjob/suite_test.go, test/integration/controller/jobs/paddlejob/suite_test.go, test/integration/controller/jobs/pod/suite_test.go, test/integration/controller/jobs/pytorchjob/suite_test.go, test/integration/controller/jobs/raycluster/suite_test.go, test/integration/controller/jobs/rayjob/suite_test.go, test/integration/controller/jobs/tfjob/suite_test.go, test/integration/controller/jobs/xgboostjob/suite_test.go, test/integration/framework/framework.go, test/integration/importer/suite_test.go, test/integration/kueuectl/suite_test.go, test/integration/multikueue/suite_test.go, test/integration/scheduler/fairsharing/suite_test.go, test/integration/scheduler/podsready/suite_test.go, test/integration/scheduler/suite_test.go, test/integration/tas/suite_test.go, test/integration/webhook/core/suite_test.go, test/integration/webhook/jobs/suite_test.go, test/util/constants.go, test/util/util.go
/kind cleanup
Indirect path to CRDs are confusing and varies depending on the folder structure.
Make them follow one direct path based on the PROJECT_DIR.
Relates #4040 
```release-note
NONE
```
=> [Cleanup] Use PROJECT_DIR for crd path instead of indirect path

pkg/controller/admissionchecks/multikueue/workload.go
/kind cleanup
As agreed in [discussion](https://github.com/kubernetes-sigs/kueue/issues/3841#issuecomment-2614967796) - "remove the TODO as the place may actually be confusing".
Related to #3841 
```release-note
NONE
```
=> Remove comment for #3841

pkg/controller/jobframework/reconciler.go
/kind cleanup
We should ignore workloads controlled by another object but return an error if it occurs with something else.
Fixes #
Prepare for https://github.com/kubernetes-sigs/kueue/pull/4023
```release-note
NONE
```
=> Ignore the workload is controlled by another object.

pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/statefulset/wrappers.go
/kind bug
Fix a bug that allowed changes to PodSpec fields other than the image field.
Fixes #
```release-note
Fix a bug that allowed changes to PodSpec fields other than the image field.
```
=> [StatefulSet] Disallow changes to PodSpec fields other than the image field

pkg/controller/jobframework/integrationmanager.go, pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/setup.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/statefulset/statefulset_reconciler.go, pkg/util/testing/wrappers.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, pkg/util/testingjobs/pod/wrappers.go, test/e2e/singlecluster/leaderworkerset_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
/kind feature
Support LeaderReadyStartupPolicy on LeaderWorkerSet.
Fixes #3232
```release-note
NONE
```
=> [LeaderWorkerSet] Support LeaderReadyStartupPolicy

.golangci.yaml, pkg/cache/clusterqueue_test.go, pkg/cache/resource_node.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/queue/cluster_queue.go, pkg/scheduler/scheduler_test.go, test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/controller/jobs/kubeflow/kubeflowjob.go, test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go
/kind cleanup
The PR slightly simplify code by refactoring to `++` instead of ` += 1`. Enables `revive.increment-decrement` to prevent such issues in the future.
https://go.dev/ref/spec#IncDec_statements
```release-note
NONE
```
=> refactor: use increment instead of `+= 1`

keps/349-all-or-nothing/README.md, keps/349-all-or-nothing/kep.yaml
/kind feature
Described in #2732 
Part of #2732 
As an alternative,  instead of adding a new timeout, we could reuse the existing one to provide the needed functionality
Pros:
- no API changes requried
Cons:
- Users cannot set different timeouts for different scenarios
```release-note
NONE
```
=> KEP: Introduce a new timeout to WaitForPodsReady config

pkg/controller/jobs/jobset/jobset_multikueue_adapter.go, pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_multikueue_adapter.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go
/kind cleanup
Follow-up of #3685 
Fixes #3730 
```release-note
MultiKueue: Do not update the status of the Job on the management cluster while the Job is suspended. This is updated  for jobs represented by JobSet, Kubeflow Jobs and MPIJob.
```
=> Prevent updating Job status on suspended jobs

test/util/constants.go
/kind cleanup
Related to #4033
To minimize the chance the tests fail occasionally due to the machines being under load. 
I suppose the slow propagation of events could be the reason for the flake https://github.com/kubernetes-sigs/kueue/issues/4033.
I seem to remember in the past we also observed flakes which we attributed to slow processing of events, so having a bit extra time seems reasonable. 
We use [10s timeout](https://github.com/kubernetes-sigs/jobset/blob/ec942521899668e414d1775da8a2acffbd1b1d17/test/integration/controller/jobset_controller_test.go#L45
) for JobSet integration tests. 
The core k8s integration tests mostly use [5s](https://github.com/kubernetes/kubernetes/blob/3bc8f01c74e80cb85e6f3813db1b410adba22bfe/test/integration/job/job_test.go#L4104), …
=> Increase the timeout for integration tests

pkg/util/strings/strings.go, pkg/util/strings/strings_test.go, pkg/util/testing/wrappers.go, test/e2e/config/default/controller_manager_config.yaml, test/e2e/config/default/manager_e2e_patch.yaml, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/suite_test.go, test/util/e2e.go, test/util/util.go
/kind cleanup
Adds sanity tests for general and local queue metrics
Fixes #3746 
```release-note
NONE
```
=> Add metrics e2e tests

test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go, test/e2e/tas/statefulset_test.go, test/util/util.go
/kind cleanup
/kind flake
Wait for Pods to be deleted in AfterEach.
Fixes #4056
```release-note
NONE
```
=> Wait for Pods to be deleted in AfterEach.

pkg/controller/jobframework/base_webhook_test.go
/cleanup
Explicit unit tests for managedBy defaulting in the basewebhook.  The code was already being implicitly tested by 
the unit tests for other webhooks (Job, JobSet, MPIJob), but it still probably better to have a test for the basewebhook too.
Fixes #
```release-note
NONE
```
=> unit tests for ApplyDefaultForManagedBy

pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go
/kind bug
Update workload AdmissionChecks status on AdmissionRequest creation error.
Fixes #3025
```release-note
Fix the bug that prevented Kueue from updating the AdmissionCheck state in the Workload status on a ProvisioningRequest creation error.
```
=> Update workload AdmissionChecks status on AdmissionRequest creation error.

pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go
Cherry pick of #4114 on release-0.10.
#4114: Update workload AdmissionChecks status on AdmissionRequest creation error.
```release-note
Fix the bug that prevented Kueue from updating the AdmissionCheck state in the Workload status on a ProvisioningRequest creation error.
```
=> Automated cherry pick of #4114: Update workload AdmissionChecks status on AdmissionRequest creation error.

hack/kind-cluster.yaml, hack/multikueue/manager-cluster.kind.yaml, hack/multikueue/worker-cluster.kind.yaml
Cherry pick of #4095 on release-0.9.
#4095: Increase log level for Kubernetes components.
```release-note
NONE
```
=> Automated cherry pick of #4095: Increase log level for Kubernetes components.

pkg/scheduler/scheduler.go, pkg/workload/resources.go
/kind cleanup
- Update attemptCount to schedulingCycleCount, which will be a little more clear in logs
- Update workload sorting comment to include fair sharing
- Move validation functions to more appropriate package (`workload`)
```release-note
Renamed Log key from "attemptCount" to "schedulingCycleCount". This key tracks how many scheduling cycles we have done since starting Kueue.
```
=> cleanup scheduler.go

pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, test/integration/singlecluster/webhook/jobs/jobset_webhook_test.go
/kind bug
Fixed a bug that doesn't allow to validate JobSet when both kueue.x-k8s.io/podset-required-topology and kueue.x-k8s.io/podset-preferred-topology annotations are set.
Fixes #4122
```release-note
TAS: Fixed a bug that allows to create a JobSet with both kueue.x-k8s.io/podset-required-topology and kueue.x-k8s.io/podset-preferred-topology annotations set on the PodTemplate.
```
=> TAS: Fix JobSet validation.

pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go, pkg/util/testing/wrappers.go
/kind bug
Create `PodTemplate` before `ProvisioningRequest`.
Fixes #3957
```release-note
Fix a bug that occurs when a PodTemplate has not been created yet, but the Cluster Autoscaler attempts to process the ProvisioningRequest and marks it as failed.
```
=> Create PodTemplate before ProvisioningRequest

pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go
/kind cleanup
Replaces `time.Now()` to use the Now() function present inside `clock` package.
Fixes #3380
```release-note
NONE
```
=> Replace `time.Now()` with `clock.Clock.Now()` in pkg/pod

site/content/en/docs/tasks/run/external_workloads/_index.md, site/content/en/docs/tasks/run/external_workloads/tektoncd.md, site/static/examples/pod-based-workloads/tekton-hello-task.yaml, site/static/examples/pod-based-workloads/tekton-pipeline-run.yaml, site/static/examples/pod-based-workloads/tekton-pipeline.yaml, site/static/examples/pod-based-workloads/tekton-sleep-task.yaml
Example integration with TektonCD
Fixes #
```release-note
NONE
```
=> Document Tekton Pipeline support with pod integration

.golangci.yaml, pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go, pkg/controller/admissionchecks/provisioning/controller.go
/kind cleanup
This PR enables [`nolintlint`](https://golangci-lint.run/usage/linters/#nolintlint) linter in golangci-lint. This simple linter controls `//nolint` directives and suggests removing unused `//nolint` comments.
```release-note
NONE
```
=> chore: enable nolintlint to detect unused //nolint

pkg/controller/jobframework/validation.go, pkg/controller/jobframework/validation_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/pod/pod.go
/kind bug
Fix a bug that allowed changes to PodSpec fields, other than the image field, resulting in the StatefulSet getting stuck on Pods with schedulingGates.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/3952#issuecomment-2618888311.
```release-note
Fix a bug that allowed unsupported changes to some PodSpec fields which were resulting in the StatefulSet getting stuck on Pods with schedulingGates. 
The validation blocks mutating the following Pod spec fields: `nodeSelector`, `affinity`, `tolerations`, `runtimeClassName`, `priority`, `topologySpreadConstraints`, `overhead`, `resourceClaims`, plus container (and init container) fields: `ports` and `resources.requests`. 
Mutating other fields, such as container image, command or args, remains allowed and supported. …
```
=> Allow to change mutable PodSpec fields.

pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, test/integration/webhook/jobs/jobset_webhook_test.go
Cherry pick of #4130 on release-0.9.
#4130: TAS: Fix JobSet validation.
```release-note
TAS: Fixed a bug that allows to create a JobSet with both kueue.x-k8s.io/podset-required-topology and kueue.x-k8s.io/podset-preferred-topology annotations set on the PodTemplate.
```
=> Automated cherry pick of #4130: TAS: Fix JobSet validation.

test/e2e/multikueue/e2e_test.go
/kind feature
This PR is the second part in enabling deployments for MultiKueue with #4034 being part 1
Part of #3802
@mimowo Seeing as Deployments do not have workload support we are unable to create an adapter and utilize Sync Job for creating a remote deployment and syncing status that way. 
On the other hand as the Pods progress on the Manager Cluster the deployment's status is updated as if they were running on single cluster. 
Another note is a concern in relation to which cluster the Pods are created in. In this implementation the pods can run on any cluster and are not run as a group on a single cluster. Is this something we should be wary of? 
If we are happy with this implementation I can remove the WIP.
```release-note
NONE
```
=> Deployment e2e tests for MultiKueue

pkg/controller/jobs/job/job_controller.go, pkg/controller/jobs/job/job_multikueue_adapter.go, pkg/controller/jobs/job/job_multikueue_adapter_test.go, pkg/controller/jobs/jobset/jobset_controller.go, pkg/controller/jobs/jobset/jobset_multikueue_adapter.go, pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go, pkg/controller/jobs/mpijob/mpijob_controller.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_multikueue_adapter.go, pkg/controller/jobs/pod/pod_multikueue_adapter_test.go, pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/raycluster/raycluster_multikueue_adapter.go, pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go, pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
/kind cleanup
I replaced the `multikueue` with `multiKueue` only for struct and variable names.
For the package name (`multikueue`) should be fine and could be justified for the `multikueue` based on https://go.dev/doc/effective_go#package-names. 
But, for struct and variable names, it should be CamelCase.
Fixes #
```release-note
NONE
```
=> chore: Use multiKueue intead of multikueue for struct and variable name

charts/kueue/templates/webhook/webhook.yaml, config/components/webhook/kustomization.yaml, hack/update-helm.sh
/kind bug
Pod and Deployments are guarded by a namespace selector. I think statefulset should have a similar pattern.
For kind deployments, I'm not sure anyone would have statefulsets in the namespace kueue-system or kube-system. But this is a template that people would follow and I think this namespace selector is useful.
Fixes #
```release-note
Disable the StatefulSet webhook in the kube-system and kueue-system namespaces by default. 
This aligns the default StatefulSet webhook configuration with the Pod and Deployment configurations.
```
=> statefulset should have same namespace selector as pod and deployment

test/e2e/singlecluster/metrics_test.go
/kind flake
Strictly check the deleted metrics from the test environment. This way the test will target only the metrics from the current test run, and ignore the metrics that might not have been cleared previously.
Part of #4139 
```release-note
NONE
```
=> Check deleted metrics form the test ns

charts/kueue/templates/webhook/webhook.yaml, config/components/webhook/manifests.yaml, pkg/controller/jobs/appwrapper/appwrapper_controller.go, test/integration/singlecluster/webhook/jobs/appwrapper_webhook_test.go, test/integration/singlecluster/webhook/jobs/suite_test.go
/kind bug
Adds the kubebuilder directives to properly configure the AppWrapper webhooks. 
This should have been part of #3953. 
No release notes because we haven't made a release with appwrapper.  The release note from #3953 is sufficient.
```release-note
NONE
```
=> properly configure appwrapper webhooks

keps/2937-resource-transformer/kep.yaml, pkg/features/kube_features.go, pkg/scheduler/scheduler_test.go, pkg/workload/workload.go, site/content/en/docs/installation/_index.md, site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md, test/integration/singlecluster/scheduler/workload_controller_test.go
/kind cleanup
Graduate WorkloadResourceRequestsSummary to stable and cleanup code/tests for WorkloadResourceRequestsSummary=false
```release-note
Promote WorkloadResourceRequestsSummary feature gate to stable
```
=> Graduate WorkloadResourceRequestsSummary to Stable

pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_oracle.go
/kind cleanup
Preparatory PR for https://github.com/kubernetes-sigs/kueue/pull/4171
While working on that PR I needed to pass a new parameter representing "tasRequests" and it becomes a chore to pump the parameter through all interfaces (such as the `minimalPreemptions` and `fairSharingPreemptions`  functions) down to the `workloadFits` function (such as currently `requests are passed). 
This concept is analogous to what we do in the core k8s Job controller: https://github.com/kubernetes/kubernetes/blob/39f1c90ac014828803a156b40d49f0c58fb7384a/pkg/controller/job/job_controller.go#L128 for the very same reason.
```release-note
NONE
```
=> Introduce preemption context to reduce passing of parameters

pkg/controller/jobs/job/job_multikueue_adapter_test.go, pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go, pkg/controller/jobs/mpijob/mpijob_multikueue_adapter_test.go, pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go
/kind cleanup
This is a follow-up of #3685 and #4070 PR.
We should verify the behavior by UTs, basically, since only integration or E2E level tests hide the root cause.
Hidden root causes sometimes lead us to a rabbit hole in the case of debugging.
Fixes #
```release-note
NONE
```
=> MultiKueue: Implement suspended Job status propagation UTs

cmd/kueuectl/app/create/create_resourceflavor.go, cmd/kueuectl/app/create/create_resourceflavor_test.go, site/content/en/docs/reference/kubectl-kueue/commands/kueuectl_create/kueuectl_create_resourceflavor.md, test/integration/singlecluster/kueuectl/create_test.go
/kind cleanup
I replaced `beta.kubernetes.io/arch` and `beta.kubernetes.io/os` node labels with `kubernetes.io/arch` and `kubernetes.io/os` since as we can see the below, those node labes are deprecated in K8s 1.14.
- [`beta.kubernetes.io/arch`](https://github.com/kubernetes/kubernetes/blob/69ab91a5c59617872c9f48737c64409a9dec2957/pkg/api/node/util.go#L30)
- [`beta.kubernetes.io/os`](https://github.com/kubernetes/kubernetes/blob/69ab91a5c59617872c9f48737c64409a9dec2957/pkg/api/node/util.go#L31)
Fixes #
```release-note
NONE
```
=> KueueCtl: Use stable node label in help description

pkg/controller/jobs/jobset/jobset_controller_test.go, pkg/controller/jobs/jobset/jobset_multikueue_adapter_test.go, pkg/util/testingjobs/jobset/wrappers.go
/kind cleanup
Only JobSet Wrapper uses `Deepcopy` function name to clone the wrapper.
Otherwise use `Clone` as a function name like batch/v1 Job: https://github.com/kubernetes-sigs/kueue/blob/f06389aff1d714e3804743deecba5edbcd1a4d25/pkg/util/testingjobs/job/wrappers.go#L69-L72
Fixes #
```release-note
NONE
```
=> chore: Rename JobSet Wrapper Deepcopy with Clone

pkg/controller/admissionchecks/provisioning/controller.go
/kind bug
In this PR (https://github.com/kubernetes-sigs/kueue/pull/4114), we start to truncate AC condition message.
But it should not be truncated; we should truncate only event messages due to event message size limitation.
Fixes #
```release-note
Fix a bug truncating AdmissionCheck condition message for ProvisioningRequest
```
=> ProvReq: avoid to truncate AC conditon message

test/e2e/multikueue/e2e_test.go
/kind cleanup
We should use aarch64 Ray image only when the platform is arm64. The darwin does not indicate arm64 platform.
Fixes #
```release-note
NONE
```
=> chore: Use Ray aarch64 image only when test executed platform is arm64

pkg/controller/admissionchecks/provisioning/controller.go
Cherry pick of #4185 on release-0.10.
#4185: ProvReq: avoid to truncate AC conditon message
```release-note
Fix a bug truncating AdmissionCheck condition message for ProvisioningRequest
```
=> Automated cherry pick of #4185: ProvReq: avoid to truncate AC conditon message

cmd/kueue/main.go, pkg/controller/admissionchecks/provisioning/indexer.go
/kind feature
Adding a CRD check could help pinpoint the root cause. This improvement will ensure users can quickly identify the issue and avoid wasting time in the future.
Fixes #3195
```release-note
Improve error messages when the ProvisioningRequest Admission Check is not initialized due to a missing or unsupported version of the ProvisioningRequest CRD.
```
=> Improve error messages when ProvisioningRequest CRD is missing or unsupported

client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go, client-go/applyconfiguration/kueue/v1beta1/podset.go, client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go, client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go, hack/update-codegen.sh
/kind bug
This PR adds the external types the Kueue API depends on to the code-generator command so the generated client apply configurations are complete and do not rely on "non-apply" types.
```release-note
Add missing external types to apply configurations
```
=> Add missing external types to apply configurations

pkg/controller/admissionchecks/provisioning/controller.go
/kind cleanup
/kind bug
Truncate admission check error message.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/4185#issuecomment-2647143664.
```release-note
Fix a bug truncating AdmissionCheck condition message at `1024` characters when creation of the associated ProvisioningRequest or PodTemplate fails. 
Instead, use the `32*1024` characters limit as for condition messages.
```
=> Truncate admission check error message.

pkg/controller/admissionchecks/provisioning/controller.go
Cherry pick of #4190 on release-0.10.
#4190: Truncate admission check error message.
```release-note
Fix a bug truncating AdmissionCheck condition message at `1024` characters when creation of the associated ProvisioningRequest or PodTemplate fails. 
Instead, use the `32*1024` characters limit as for condition messages.
```
=> Automated cherry pick of #4190: Truncate admission check error message.

pkg/controller/jobs/statefulset/statefulset_reconciler.go, pkg/controller/jobs/statefulset/statefulset_reconciler_test.go, test/e2e/singlecluster/statefulset_test.go
/kind bug
Finalize Pods if StatefulSet is not found.
Fixes #4160
Fixes #4138
```release-note
Fix a bug that doesn't allow Kueue to delete Pods after a StatefulSet is deleted.
```
=> Finalize Pods if StatefulSet is not found.

Makefile-test.mk, test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/customconfigs/suite_test.go, test/util/constants.go, test/util/e2e.go, test/util/util.go
/kind cleanup
This PR adds e2e tests for the `manageJobsWithoutQueueName: true` configuration.  This is one of the tasks required to close #3767 
Fixes #
The test suite sets `manageJobsWithoutQueueName: true` during the setup phase of the description block (just before running the test specs). It then initiates a rollout of the controller deployment to ensure that the new configuration is picked up by the pods. To confirm that the deployment rollout has started, the setup function waits for the Deployment to have the condition `DeploymentCondition=false`.
To ensure that this condition is met, the rollout strategy is set to `Recreate`, which guarantees that the pods are terminated before being recreated, resulting in the condition not being satisfied (see …
=> Add e2e tests for manageJobsWithoutQueueName

client-go/applyconfiguration/kueue/v1beta1/localqueueflavorstatus.go, client-go/applyconfiguration/kueue/v1beta1/podset.go, client-go/applyconfiguration/kueue/v1beta1/podsetupdate.go, client-go/applyconfiguration/kueue/v1beta1/resourceflavorspec.go, hack/update-codegen.sh
Cherry pick of #4191 on release-0.10.
#4191: Add missing external types to apply configurations
```release-note
Add missing external types to apply configurations
```
=> Automated cherry pick of #4191: Add missing external types to apply configurations

pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/scheduler/scheduler_test.go
/kind cleanup
/kind bug
Prepares for https://github.com/kubernetes-sigs/kueue/pull/4200
Do you think worth a cherry-pick?
```release-note
Improve error message in the event when scheduling for TAS workload fails due to unassigned flavors.
```
=> TAS: Improve error message for TAS workloads when no flavor assigned

charts/kueue/templates/rbac/role.yaml, config/components/rbac/role.yaml, pkg/controller/jobs/statefulset/statefulset_controller.go, pkg/controller/jobs/statefulset/statefulset_reconciler.go, pkg/controller/jobs/statefulset/statefulset_reconciler_test.go, test/e2e/singlecluster/statefulset_test.go
Cherry pick of #4150 on release-0.9.
#4150: Finalize Pods if StatefulSet is not found.
```release-note
Fix a bug that doesn't allow Kueue to delete Pods after a StatefulSet is deleted.
```
=> Automated cherry pick of #4150: Finalize Pods if StatefulSet is not found.

cloudbuild.yaml
/kind cleanup
Currently, our post container building usually takes over 30 min.
https://testgrid.k8s.io/sig-k8s-infra-gcb#post-kueue-push-images
This causes the blocker when we release something. ~~So, I increased the  machine type based on https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#machinetype, and then parallelize the execution.~~
We decided to increase machine size in a separately: https://github.com/kubernetes-sigs/kueue/pull/4214#issuecomment-2650008829
Fixes #
```release-note
NONE
```
=> Perform container building in parallel

cloudbuild.yaml
/kind cleanup
My `make` command was incorrect as we can see: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-kueue-push-images/1889247515904053248
```
make: the '-j' option requires a positive integer argument
Usage: make [options] [target] ...
Options:
-b, -m                      Ignored for compatibility.
-B, --always-make           Unconditionally make all targets.
-C DIRECTORY, --directory=DIRECTORY
Change to DIRECTORY before doing anything.
-d                          Print lots of debugging information.
--debug[=FLAGS]             Print various types of debugging information.
-e, --environment-overrides
Environment variables override makefiles.
-E STRING, --eval=STRING    Evaluate STRING as a makefile statement.
-f FILE, --file=FILE, --makefile=FILE
Read FILE as a makefile. …
```
=> Fix post container building commands

cloudbuild.yaml
/kind cleanup
As I described in https://github.com/kubernetes-sigs/kueue/pull/4222#issuecomment-2650505614, the cloudbuild or DinD does not support the multi-architecture container buildings by `docker buildx build --platform A,B,C`.
If we want to perform concurrently image buildings, we need to build a single arch image, and then amend those image manifests into one.
Fixes #
```release-note
NONE
```
=> Revert #4214 #4222: Make post container buildings as sequentially

cloudbuild.yaml
/kind cleanup
As we can check https://github.com/kubernetes-sigs/kueue/pull/4225#issuecomment-2650755516, we found that the concurrency completely does not have any compatible with infra.
Fixes #
```release-note
NONE
```
=> chore: Drop concurrency (-j=3) from cloudbuild

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/limitrange/limitrange.go, pkg/util/limitrange/limitrange_test.go, pkg/util/testing/wrappers.go, pkg/workload/resources.go, pkg/workload/resources_test.go
/kind cleanup
I have done the following to stabilize the `ValidateResources` function in the `workload` package:
- Added Unit Tests
- Fixed incorrect field path. The previous incorrect field paths do not have the appropriate PodSet index.
Fixes #
```release-note
Fix a bug is incorrect field path in inadmissible reasons and messages when container requests exceed limits
```
=> Stabilizing workload ValidateResources

pkg/controller/admissionchecks/multikueue/admissioncheck.go, pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/controller/tas/topology_ungater.go
/kind bug
The controller name must be compatible with Prometheus based on https://github.com/kubernetes-sigs/controller-runtime/blob/c5bb1d4d8e7d0e49bb06f8276785e7f7cbcbf2b8/pkg/builder/controller.go#L247-L257
Fixes #
```release-note
Fix a bug that prevented tracking some of the controller-runtime metrics in Prometheus.
```
=> Use compatible controller name with Prometheus

pkg/controller/admissionchecks/multikueue/admissioncheck.go, pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_ungater.go
Cherry pick of #4217 on release-0.9.
#4217: Use compatible controller name with Prometheus
```release-note
Fix a bug that prevented tracking some of the controller-runtime metrics in Prometheus.
```
=> Automated cherry pick of #4217: Use compatible controller name with Prometheus

pkg/controller/jobs/statefulset/statefulset_reconciler.go
/kind cleanup
If no Pods are found on the `fetchAndFinalizePods`, there's nothing to do and we can skip fetching StatefulSet.
Fixes #
```release-note
NONE
```
=> Optimize StatefulSet reconciler.

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/limitrange/limitrange.go, pkg/util/limitrange/limitrange_test.go, pkg/util/testing/wrappers.go, pkg/workload/resources.go, pkg/workload/resources_test.go
Cherry pick of #4216 on release-0.10.
#4216: Stabilizing workload ValidateResources
```release-note
Fix a bug is incorrect field path in inadmissible reasons and messages when container requests exceed limits
```
=> Automated cherry pick of #4216: Stabilizing workload ValidateResources

pkg/cache/clusterqueue_snapshot.go, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/resources/requests.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go
/kind cleanup
Part of #3761
Preparatory for https://github.com/kubernetes-sigs/kueue/pull/4171
The main change in this PR is to refactor how the TAS assignment is computed when there are multiple PodSets. Previously the usage from previous podsets was already accounted regardless of the final scheduling result, see [here](https://github.com/kubernetes-sigs/kueue/compare/main...mimowo:tas-refactor-podset-usage?expand=1#diff-5414dcb324187d1d853329b419691cde79632a6d77e1a7c2b503dc1a3688c081L351). This works well only assuming the FindTopologyAssignment function is called once. 
However, to support preemptions I will need to run this function multiple times for a different set of target workloads. Similarly, this assumption is also invalid for cohorts.
So I introduce a concept of …
=> Refactor computation of TAS assignments

site/content/en/docs/installation/_index.md
Add a table that mentions deprecated/ga features.
This is necessary because over time feature gates will be removed or they will be deprecated on particular versions. This is helpful for end-users to know what state features are in.
Kubernetes has two separate tables for this.
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
Fixes #4230 
```release-note
NONE
```
=> add feature gates table for graduated or deprecated features

test/e2e/singlecluster/leaderworkerset_test.go
/kind cleanup
Extend e2e tests for scaling the LWS when LeaderReadyStartupPolicy.
Part of #3232
Follow up for https://github.com/kubernetes-sigs/kueue/issues/3232#issuecomment-2619318530.
```release-note
NONE
```
=> Extend e2e tests for scaling the LWS when LeaderReadyStartupPolicy.

site/content/en/docs/concepts/resource_flavor.md
As described in https://github.com/kubernetes-sigs/kueue/issues/4257, the `PreferNoSchedule` effect is not respected by Kueue flavorassigner.
Fixes #
```release-note
NONE
```
=> Doc: mention the supported ResourceFlavor nodeTaints effect

Makefile-test.mk
/kind cleanup
This PR removes the `test-e2e-customconfigs` Makefile target invocation from the `run-test-e2e` Makefile target. This is a follow-up of #4112 .
Part of #3767
```release-note
NONE
```
=> Don't run 'test-e2e-customconfigs' Makefile target as part of 'run-test-e2e' Makefile target

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go
/kind cleanup
I removed unused parameters from `WorkloadTopologyRequests()` function.
Fixes #
```release-note
NONE
```
=> TAS: Remove unused argumentes from WorkloadsTopologyRequests()

pkg/util/testing/metrics_matchers.go, test/e2e/singlecluster/metrics_test.go
/kind cleanup
Improve output of metrics e2e tests to understand potential failures more clearly.
Fixes #4139 
Example of failed test output:
```
Expected to contain metric:
<[]string | len:3, cap:3>: [
"kueue_nonexistent_metric",
"tag1",
"tag2",
]
Actual:
<string>: kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.005"} 0
kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.01"} 1
kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.025"} 1
kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.05"} 1
kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.1"} 1
kueue_admission_attempt_duration_seconds_bucket{result="success",le="0.25"} 1
kueue_admission_attempt_duration_seconds_bucket{result="success", …
```
=> Improve output messages in case of failed e2e tests for metrics

pkg/controller/jobs/pod/pod_controller.go
/kind cleanup
If we do not specify the reconcile concurrency for Pods in ConfigAPI, the logging message is following:
```
2025-02-17T01:54:27.907248+09:00      INFO    pod/pod_controller.go:124       Setting up Pod reconciler       {"concurrency": 0}
```
Fixes #
```release-note
NONE
```
=> chore: Fix concurrency logging info in JobFramework Pod reconciler

pkg/util/limitrange/limitrange_test.go, pkg/util/testing/wrappers.go
/kind cleanup
Leveraging wrappers for `LimitRange` during UTs.
Fixes #
```release-note
NONE
```
=> chore: Use LimitRange wrappers during UTs

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/limitrange/limitrange.go, pkg/util/limitrange/limitrange_test.go, pkg/workload/resources.go, pkg/workload/resources_test.go, test/integration/singlecluster/scheduler/scheduler_test.go
/kind bug
I have done the following to stabilize the `ValidateLimitRange` function in the `workload` package:
- Added Unit Tests
- Fixed incorrect field path. The previous incorrect field paths do not have the appropriate PodSet and containers index.
Fixes #
This is a follow-up PR of https://github.com/kubernetes-sigs/kueue/pull/4216.
```release-note
Fix a bug is incorrect field path in inadmissible reasons and messages when Pod resources requests do not satisfy LimitRange constraints.
```
=> Stabilizing workload.ValidateLimitRange

site/content/en/docs/tasks/_index.md, site/content/en/docs/tasks/run/leaderworkerset.md, site/static/examples/serving-workloads/sample-leaderworkerset.yaml
Add documentation for LeaderWorkerSet.
Part of #3232
```release-note
NONE
```
=> Add documentation for LeaderWorkerSet.

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/limitrange/limitrange.go, pkg/util/limitrange/limitrange_test.go, pkg/workload/resources.go, pkg/workload/resources_test.go, test/integration/scheduler/scheduler_test.go
Cherry pick of #4267 on release-0.10.
#4267: Stabilizing workload.ValidateLimitRange
```release-note
Fix a bug is incorrect field path in inadmissible reasons and messages when Pod resources requests do not satisfy LimitRange constraints.
```
=> Automated cherry pick of #4267: Stabilizing workload.ValidateLimitRange

pkg/cache/tas_flavor_snapshot.go
/kind cleanup
This `usage` calculation has never been contributed to anything for now.
For background, this was introduced as a part of bug fixes https://github.com/kubernetes-sigs/kueue/pull/3937, and then we replaced the mechanism with assumedUsage, https://github.com/kubernetes-sigs/kueue/pull/4200.
Fixes #
```release-note
NONE
```
=> TAS: Remove non-contributed usage calculation

pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobs/job/job_controller_test.go, pkg/util/testingjobs/appwrapper/wrappers.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go
/kind feature
Allows multiple levels of owner links between the job being reconciled and the top-level Kueue managed job that has a queuename/workload (for example Job-->JobSet-->AppWrapper).
In particular, this fixes an endless reconcile loop I observed when `managedJobsWithoutQueueName` is true for the scenario of an AppWrapper containing  a JobSet.
Technically this is a long standing bug, but since we haven't made a release with AppWrappers as a fully supported integration yet, I think we can skip cherry-picking it to release branches. 
```release-note
NONE
```
=> Generalize handling of parent jobs in ReconcileGenericJob

pkg/controller/core/workload_controller.go
/kind cleanup
I removed redundant logic that checks if the `waitFor` value is negative, since we don't use afterwards
```release-note
NONE
```
=> WaitForPodsReady cleanup

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go
/kind feature
Simplifies logic of WaitForPodsReady countdown. Countdown is now measured since the `Admitted` condition a not since the `PodsReady=False` condition, which I believe should be intended behavior.
```release-note
WaitForPodsReady countdown is now measured since the admission of the workload instead of setting `PodsReady` condition to `False`
```
=> Simplify logic of WaitForPodsReady countdown

pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/clusterqueue_test.go, pkg/cache/snapshot.go, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/scheduler_test.go, test/integration/singlecluster/tas/tas_test.go
/kind feature
Part of  #3761
I will follow up enabling preemption across multiple ClusterQueues in a cohort. This is slightly more complicated because we currently allow for multiple workloads to be considered in the same scheduling cycle. For this we need the ability to reserve quota partially. This requires more code, and more tests.
For the ease of reviewing let me annotate the purpose of the main changes:
1. [this code](https://github.com/kubernetes-sigs/kueue/pull/4171/files#diff-441da8393964615cf5b020d0afb9199588e157e50718e83b527788eb679391ecL285-L288) enables the preemption for TAS which was explicitly blocked, CQs with preemption and TAS were deactivated
2. [this code](https://github.com/kubernetes-sigs/kueue/pull/4171/files#diff-3e801025e890fc24825a58862fb7b9132ccc64d37b72453696f1 …
=> TAS: support preemption within ClusterQueue

site/content/en/docs/tasks/run/deployment.md, site/content/en/docs/tasks/run/plain_pods.md, site/content/en/docs/tasks/run/statefulset.md
Cherry pick of #4309 on website.
#4309: docs: update pod integration name in documentation
```release-note
NONE
```
=> Automated cherry pick of #4309: docs: update pod integration name in documentation

pkg/controller/jobframework/events.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go
/kind cleanup
Follow up from #4251.  Limit number of ancestor links traversed and emit warning event when search is terminated because the limit is reached.
Fixes #
Happy to change the Reason text if you have a better idea. 
```release-note
NONE
```
=> limit traversal of ancestor links in getAncestorJobManagedByKueue

pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/util/testingjobs/pod/wrappers.go, site/content/en/docs/reference/labels-and-annotations.md, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
/kind cleanup
Use consistent naming for prebuilt workload across the codebase
Fixes #4324
```release-note
NONE
```
=> Use consistent naming for prebuilt workload across the codebase

apis/config/v1beta1/configuration_types.go, apis/config/v1beta1/defaults.go, apis/config/v1beta1/defaults_test.go, charts/kueue/templates/webhook/webhook.yaml, charts/kueue/values.yaml, cmd/kueue/main.go, config/components/manager/controller_manager_config.yaml, hack/update-helm.sh, pkg/config/config_test.go, pkg/config/validation.go, pkg/config/validation_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, site/content/en/docs/reference/kueue-config.v1beta1.md, site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md, site/content/en/docs/tasks/run/plain_pods.md, site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/webhook/jobs/pod_webhook_test.go, test/integration/singlecluster/webhook/jobs/statefulset_webhook_test.go
/kind cleanup
Deprecates integrations.podOptions:
+ mark podOptions as deprecated
+ remove defaulting of podOptions
+ adjust impl and tests to not assume podOptions is defaulted
+ update documentation to steer users to managedJobsNamespaceSelector
+ update helm chart generation tooling
Fixes #4168 
```release-note
The configuration field `integrations.podOptions` is deprecated. 
ACTION_REQUIRED: Users who set the `Integrations.PodOptions` namespace selector to a non-default
value should plan for migrating to use `managedJobsNamespaceSelector` instead, as the PodOptions
selector is going to be removed in a future release.
```
=> Deprecate integrations.podOptions

hack/e2e-common.sh, test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/multikueue/suite_test.go, test/e2e/singlecluster/appwrapper_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/singlecluster/visibility_test.go, test/e2e/tas/appwrapper_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/leaderworkerset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pytorch_test.go, test/e2e/tas/statefulset_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/util/constants.go, test/util/e2e.go
/kind cleanup
The gcr.io image registry is deprecated and will be shut down in 2025.
Use agnhost instead as proposed [here](https://github.com/kubernetes-sigs/kueue/issues/3772#issuecomment-2625572045)
Fixes #3772 
```release-note
NONE
```
=> [Cleanup] Replace using gcr.io sleep with agnhost in tests

pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, site/content/en/docs/reference/labels-and-annotations.md, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go
/kind bug
/kind flake
- Fix "Should ungate pods with prebuild workload" integration test.
- Add validation for prebuilt workloads in Pod groups to ensure that the prebuilt workload name cannot be different from the workload name.
Fixes #4113
When updating the Workload, we should catch an event to trigger the PodReconciler.
We send this event here 
https://github.com/kubernetes-sigs/kueue/blob/c74db07260c20ff8a4e3a611b9ac20f5b1f48582/pkg/controller/jobs/pod/event_handlers.go#L150-L153 
But the problem is that we send the group name instead of the prebuilt Workload name.
And here
https://github.com/kubernetes-sigs/kueue/blob/c74db07260c20ff8a4e3a611b9ac20f5b1f48582/pkg/controller/jobs/pod/pod_controller.go#L614-L618
we will not find it due to workload name different.
To …
=> Validate prebuilt workload for Pod groups.

apis/config/v1beta1/configuration_types.go, apis/config/v1beta1/defaults.go, apis/config/v1beta1/defaults_test.go, apis/config/v1beta1/zz_generated.deepcopy.go, apis/kueue/v1beta1/workload_types.go, charts/kueue/values.yaml, config/components/manager/controller_manager_config.yaml, pkg/config/config_test.go, pkg/config/validation.go, pkg/config/validation_test.go, pkg/controller/core/core.go, pkg/controller/core/workload_controller.go, site/content/en/docs/reference/kueue-config.v1beta1.md
/kind feature
Introduces a new `waitForPodsReady.recoveryTimeout` API, following [this KEP](https://github.com/kubernetes-sigs/kueue/pull/2737)
Part of #2732 
This is one of two PRs for this feature. This one introduces API only, and the second one adds logic.
```release-note
Kueue exposes a new recovery mechanism as part of the WaitForPodsReady API. This evicts jobs which surpasses configured threshold for pod's recovery during runtime
```
=> Extend the WaitForPodsReady API with `.recoveryTimeout` field

pkg/cache/clusterqueue.go, pkg/cache/cohort.go, pkg/cache/cohort_snapshot.go, pkg/cache/fair_sharing.go, pkg/cache/fair_sharing_test.go, pkg/cache/resource_node.go, pkg/cache/resource_node_test.go, pkg/cache/snapshot.go, pkg/cache/snapshot_test.go
/kind feature
We define FairShare (DominantResourceShare) score for Cohorts.
We additionally support the case where a CQ or Cohort has some lendable resource available to it, but not in its direct parent. Rather than counting only lendable resources in the parent Cohort, we use the `potentiallyAvailable` function to see how much capacity is available to that Cohort, when it borrows from its parent. While this doesn't differentiate capacity available in the parent Cohort's subtree, versus capacity that the parent Cohort borrows, the FairShare score should only be used for local comparisons: comparing two children of the same node. Therefore, this will serve as a valid denominator.
Part of #3759
No release note for this change, as we will do a single release note for the entire feature. …
=> Define FairShare Score for Cohorts; Generalize to Hierarchical Case

test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/singlecluster/tas/tas_test.go, test/util/util.go
/kind cleanup
It would be great to obviously clarify what the util function will do. The current `CreateNods` function name does not represent what that will do.
Fixes #
```release-note
NONE
```
=> chore: Rename CreateNodes with CreateNodesWithStatus

pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/jobset/jobset_controller_test.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go, pkg/controller/jobs/mpijob/mpijob_controller_test.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/raycluster/raycluster_controller_test.go, pkg/controller/jobs/rayjob/rayjob_controller_test.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/util/testing/wrappers.go, pkg/webhooks/workload_webhook_test.go, test/integration/singlecluster/webhook/core/workload_test.go
/kind cleanup
There are many places where we directly define PodSet instead of using `PodSetWrapper`.
Fixes #
```release-note
NONE
```
=> chore: Use PodSet wrapper during UTs

pkg/scheduler/scheduler_test.go, pkg/util/limitrange/limitrange_test.go, pkg/util/resource/resource.go, pkg/util/resource/resource_test.go, pkg/workload/resources_test.go
/kind cleanup
It would be better to use core ResourceName typed instead of string in GetGreaterKeys() to avoid casting (`ResourceName` -> `string`) everywhere.
Fixes #
```release-note
NONE
```
=> chore: Use core ResourceName typed instead of string in GetGreaterKeys()

test/e2e/singlecluster/jobset_test.go, test/e2e/tas/jobset_test.go, test/util/util.go
/kind cleanup
We have `DeleteAllXXXJobsInNamespace` util functions every for Job kinds, and all processings are completely the same.
Fixes #
```release-note
NONE
```
=> chore: Consolidated all DeleteAllXXXJobsInNamespace() processings into deleteAllObjectsInNamespace()

pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go, pkg/controller/admissionchecks/multikueue/workload_test.go, pkg/util/admissioncheck/admissioncheck.go, pkg/util/expectations/store.go, test/e2e/singlecluster/pod_test.go
/kind cleanup
`sets.New()` predicts typed from input initial data.
Fixes #
```release-note
NONE
```
=> chore: Remove redundant type parameters for sets

pkg/cache/cache_test.go, pkg/controller/jobframework/reconciler.go
/kind cleanup
We are using `podSetFlavor` for typed [`PodSetAssignment`](https://github.com/kubernetes-sigs/kueue/blob/651e8deb5193e6974db3c2e05636845d2cdcafe9/apis/kueue/v1beta1/workload_types.go#L132) as variable name.
However, today, we have non-RF information like `ResourceUsage` and `TopologyAssignment`.
So, the `podSetFlavor` confuses.
Fixes #
```release-note
NONE
```
=> chore: Rename podSetFlavor with psAssignment

pkg/controller/jobs/appwrapper/appwrapper_controller.go, pkg/controller/jobs/appwrapper/appwrapper_controller_test.go, test/e2e/tas/appwrapper_test.go, test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go
/kind feature
We enhanced the AppWrapper controller in v1.0.6 to propagate Kind-specific TAS information via annotations on the AppWrapperPodSetInfo.  This PR updates the Kueue appwrapper integration to process these annotations.  Also minor updates to the integration and test cases to accommodate small changes in the go-level APIs of the AppWrapper utils package that is used to implement the Kueue integration.
```release-note
NONE
```
=> AppWrapper TAS: full support for PodSetTopologyRequest

pkg/util/testing/condition_matchers.go, test/integration/multikueue/multikueue_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/util/util.go
/kind cleanup
Use condition matcher instead of apimeta.FindStatusCondition().
Fixes #
```release-note
NONE
```
=> Use condition matcher instead of apimeta.FindStatusCondition().

CHANGELOG/CHANGELOG-0.9.md
/kind cleanup
I added v0.9.4 CHANGELOG to main branch.
Part of: https://github.com/kubernetes-sigs/kueue/issues/4317
I did not do other main branch synchronization since v0.10.2 is the latest release.
```release-note
NONE
```
=> Add v0.9.4 to CHANGELOG

test/e2e/multikueue/e2e_test.go
/kind cleanup
```release-note
NONE
```
=> Fix inaccurate By message in appwrapper multikueue test case

test/e2e/singlecluster/leaderworkerset_test.go
/kind bug
/kind flake
Fix LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy test.
Fixes #4374
```release-note
NONE
```
=> Fix LeaderWorkerSet created should allow to scale down LeaderReadyStartupPolicy test.

apis/kueue/v1beta1/resourceflavor_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml, config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml, site/content/en/docs/reference/kueue.v1beta1.md
/kind cleanup
As I described in https://github.com/kubernetes-sigs/kueue/issues/4257, cluster admins can specify the nodeTaints with `effect=PreferNoSchedule` in ResourceFlavor, but the flavorassigner never respects the taints.
So, I added API comments for which effects will be evaluated.
Fixes #
```release-note
NONE
```
=> Add RF API comments for evaluated nodeTaints effect

apis/kueue/v1beta1/workload_types.go, pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobs/job/job_controller_test.go, pkg/util/testingjobs/job/wrappers.go, pkg/workload/workload.go, test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/singlecluster/controller/jobs/raycluster/raycluster_controller_test.go, test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go, test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/singlecluster/scheduler/podsready/scheduler_test.go
/kind feature
It introduces a new logic to WaitForPodsReady feature, to support new `.recoveryTimeout` API, according to [this KEP](https://github.com/kubernetes-sigs/kueue/pull/2737)
Fixes #2732
This is one of two PRs for this feature. The [first one](https://github.com/kubernetes-sigs/kueue/pull/4302) introduces API only, and this one adds logic.
Please wait until the PR with API is merged
The integration test in this PR should be enough for the Kueue part, but I'd like to have an additional e2e test in the follow up, which covers full journey with the batchv1.Job controller 
```release-note
Kueue exposes a new recovery mechanism as part of the WaitForPodsReady API. This evicts jobs which surpasses configured threshold for pod's recovery during runtime
```
=> WaitForPodsReady.recoveryTimeout implementation

keps/349-all-or-nothing/README.md
Part of #2732 
```release-note
NONE
```
=> Update KEP with new PodsReady reasons

hack/e2e-common.sh, hack/e2e-test.sh, hack/multikueue-e2e-test.sh, test/e2e/multikueue/e2e_test.go, test/e2e/multikueue/suite_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/singlecluster/visibility_test.go, test/integration/controller/jobs/jobset/jobset_controller_test.go, test/util/constants.go, test/util/e2e.go, test/util/util.go
Cherry pick of #4145 on release-0.9.
#4145: [Cleanup] Replace using gcr.io sleep with agnhost in tests
```release-note
NONE
```
=> Automated cherry pick of #4145: [Cleanup] Replace using gcr.io sleep with agnhost in tests

pkg/cache/clusterqueue_snapshot.go, pkg/cache/tas_flavor.go, pkg/resources/requests.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/workload/workload.go
/kind cleanup
To simplify the code in tas_flavorassigner.go and workload.go.
And to make transitioning between SinglePodRequests and TotalRequests one-liners.
Longer term I would consider something like "PodGroupResources" with two functions: SinglePodResources() and TotalResources(), and it could be used in the TopologyDomainRequests.
```release-note
NONE
```
=> Use SinglePodRequests internally for TopologyDomainRequests

test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/statefulset_test.go
It was lost in translation for LWS and Stateful Set, where image was changed to agnhost.
/kind cleanup
During change from sleep to agnhost image 2 test cases of LWS and Stateful Set were modified and old image was replaced with new image value.
```release-note
NONE
```
=> [Fix] Bring back e2e test cases where image was updated from old to new

test/e2e/singlecluster/statefulset_test.go
Cherry pick of #4424 on release-0.10.
#4424: [Fix] Bring back e2e test cases where image was updated from old to new
```release-note
NONE
```
=> Automated cherry pick of #4424: [Fix] Bring back e2e test cases where image was updated from old to new

pkg/cache/clusterqueue_snapshot.go, pkg/cache/resource_test.go, pkg/cache/snapshot.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/workload/usage.go, pkg/workload/workload.go
/kind cleanup
Part of #3761
Preparatory PR for https://github.com/kubernetes-sigs/kueue/pull/4418
I introduce the workload.Usage to wrap the current ResourceFlavorQuantities (Quota usage) and TASUsage.
For now the benefits are:
- slight simplification to pkg/cache/snapshot.go
- simpler signature for workload.TASUsage returned type
```release-note
NONE
```
=> TAS: introduce the workload Usage struct

cmd/importer/pod/import.go, cmd/importer/pod/import_test.go, pkg/constants/constants.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/admissionchecks/provisioning/controller_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, pkg/util/testingjobs/pod/wrappers.go, test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/integration/multikueue/multikueue_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/importer/importer_test.go, test/integration/singlecluster/webhook/jobs/pod_webhook_test.go
Currently we are using `ManagedByKueueLabelKey` from pkg/controller/jobs/pod
https://github.com/kubernetes-sigs/kueue/blob/68fb53181457ec3f794888fb2397236c4735ea6f/pkg/controller/jobs/pod/pod_webhook.go#L49-L50
This constant is just  a copy of ManagedByKueueLabel from pkg/constants.
To do not duplicate value we can use constant from pkg/constants.
Also replace `true` to `ManagedByKueueLabelValue`.
/kind cleanup
Part of #3653
```release-note
NONE
```
=> Use ManagedByKueueLabelKey from pkg/constants.

pkg/cache/clusterqueue_snapshot.go, pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go, pkg/util/testingjobs/node/wrappers.go
/kind bug
I fixed two bugs as I described in #4436 and #4439.
The solution for #4436 is cloning the SinglePodRequests object to avoid write operation propagation.
The solution for #4439 is to count up and down the number of Pods in the `TASFlavorSnapshot.updateTASUsage`.
By this pods count, the preemptor can appropriately simulate if candidates preemptee allows higher workloads to make a room in the following:
https://github.com/kubernetes-sigs/kueue/blob/6e25ebfcf2491236e385f644e4f7280c3d315ead/pkg/scheduler/preemption/preemption.go#L289-L297
Fixes #4436
Fixes #4439
```release-note
NONE
```
=> Fix preemption with TAS failure in the case of fulfilled pods count limit on Nodes

test/e2e/singlecluster/pod_test.go
/kind flake
Prevent the situation that high-group-priority finish too fast.
Add control over when the pod group should finish.
Fixes #4434 
```release-note
NONE
```
=> [Flake] Change image behavior of high-priority-group pod

test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/suite_test.go
Cherry pick of #4438 on release-0.10.
#4438: [Flake] Change image behavior of high-priority-group pod
```release-note
NONE
```
=> Automated cherry pick of #4438: [Flake] Change image behavior of high-priority-group pod

pkg/scheduler/preempted_workloads.go, pkg/scheduler/scheduler.go
/kind cleanup
To offload the code of the main schedule function, and to prepare for https://github.com/kubernetes-sigs/kueue/pull/4418 and https://github.com/kubernetes-sigs/kueue/pull/4449 which requires to know the list of preempted workloads as `[]*workload.Info`, not just set of strings.
The computational complexity of `hasAny` and `insert` is `O(|newTargets|)` as before.
```release-note
NONE
```
=> Introduce the helper struct for preemptedWorkloads

pkg/cache/clusterqueue_snapshot.go, pkg/scheduler/scheduler.go
/kind cleanup
To prepare for the main [PR](https://github.com/kubernetes-sigs/kueue/pull/4418)
It builds on top of https://github.com/kubernetes-sigs/kueue/pull/4447.
The refactoring is needed for TAS because the concept of netUsage hard to define in the context of TAS. 
It does not worsen the asymptotic computational complexity, because when computing the set of preempted workloads in preemption.go we anyway had to simulate the removal of the usage of the workloads. In the worst case scenario, we re-do, but typically this will be only a small fraction of all computations done during determining the list of workloads to preempt.
Also, with this refactoring we are opening the possibility of allowing preemptions of multiple workloads with overlapping preemptions, but I keep the condition in …
=> Refactor the accounting for preempted workloads in scheduler

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue_test.go, pkg/cache/fair_sharing_test.go, pkg/cache/resource_node_test.go, pkg/cache/resource_test.go, pkg/cache/snapshot.go, pkg/cache/snapshot_test.go, pkg/controller/core/cohort_controller_test.go, pkg/hierarchy/manager.go, pkg/hierarchy/manager_test.go, pkg/queue/dumper.go, pkg/queue/manager.go, pkg/queue/manager_test.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_oracle.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
/kind cleanup
Unexports two map fields in `hierarchy.Manager` so that they can be modified only by corresponding `Add...` and `Delete...` methods. 
Fixes #2996 
I added `GetClusterQueue` and `GetCohort` methods to get objects by name and `GetClusterQueuesCopy` and `GetCohortsCopy` to get copy of map for using in range loops.
Also `NewManagerForTest` constructor was added to use only in tests, specifically in `cache/snapshot_test.go` where large map literals are used to initialize managers before comparing snapshots.
None
```release-note
NONE
```
=> Unexport manager fields

pkg/cache/tas_flavor_snapshot.go
/kind cleanup
It just a cleanup so the code is cleaner and more readable 
```release-note
NONE
```
=> Clean up TAS findLevelWithFitDomain loop

test/util/e2e.go
/kind cleanup
```release-note
NONE
```
=> rename local variable in WaitForAppWrapperAvailability

pkg/resources/resource.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_oracle.go
Properly serializes FlavorResource, FlavorResourceSet and FlavorResourceQuantities types which are logged in integration tests.
Fixes #4137 
As discussed in #4137 part of this issue depends on making serializable `k8s.io/apimachinery/pkg/util/sets.Set` in upstream repo.  In the second commit I created `FlavorResourceSet` type to make it work without changing upstream code.   Possible options are to keep it temporarily until upstream is fixed, keep it permanently, or just discart and keep only the first commit and wait till upstream issue is fixed.
```release-note
NONE
```
=> Serialization support for FlavorResource, FlavorResourceSet and FlavorResourceQuantities

pkg/scheduler/preemption/preemption_test.go
/kind bug
/kind flake
Use ReserveQuotaAt instead of ReserveQuotaAt on unit tests.
Fixes #4425
Currently we are using ReserveQuota() function that using time.Now() to set LastTransitionTime. We need to use time.Now() from test.
```release-note
NONE
```
=> Use ReserveQuotaAt instead of ReserveQuota on unit tests

test/util/e2e.go
/kind bug
Fixes #4477 
```release-note
NONE
```
=> fix construction of activePods in WaitForActivePodsAndTerminate

charts/kueue/README.md, charts/kueue/templates/prometheus/role.yaml, charts/kueue/values.yaml
Cherry pick of #4484 on release-0.10.
#4484: Allow for one to change namespace for roles for prometheus
```release-note
Helm: Fixed a bug that prometheus namespace is enforced with namespace the same as kueue-controller-manager
```
=> Automated cherry pick of #4484: Allow for one to change namespace for roles for prometheus

test/e2e/tas/rayjob_test.go
/kind cleanup
Extra check to verify that after RayJob was deleted, the pods were removed by Ray-controller before next test.
Relates to #3716 
```release-note
NONE
```
=> Add check to verify RayJob tas pods were deleted

test/util/constants.go
/kind flake
Extend VeryLongTimeout duration to 5 minutes.
It's been used mostly for Kuberay related setup and had too little margin.
Fixes #4497 
```release-note
NONE
```
=> [Flake] Extend VeryLongTimeout duration to 5 minutes

test/e2e/tas/appwrapper_test.go
/kind bug
Cleaning up from a bad merge that resulted in an invalid command line argument to the test image.
Fixes #4495 
```release-note
NONE
```
=> fix arguments to AgnHostImage in AppWrapper TAS test

test/e2e/singlecluster/pod_test.go, test/util/e2e.go
/kind cleanup
Add ability to filter which pods will be terminated with WaitForActivePodsAndTerminate with listOptions.
Log pod name that's going to be terminated.
Relates to #4434 
```release-note
NONE
```
=> [Cleanup] Add listOptions to WaitForActivePodsAndTerminate

pkg/cache/clusterqueue_snapshot.go, pkg/cache/cohort_snapshot.go, pkg/cache/resource_test.go, pkg/cache/snapshot.go, pkg/hierarchy/cohort.go, pkg/scheduler/fair_sharing_iterator.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
/kind feature
We define the order in which to consider workloads
in the scheduling cycle, that is compatible with Fair Sharing in Hierarchical Cohorts (#3759).
We run a tournament, from leaf to root, where each node nominates
a workload which it considers greedily most fair. This process is repeated
until one workload remains at the root. See comments for detailed description of algorithm.
I wanted to get feedback on the algorithm before
investing time in tests. I will add those after initial pass.
No release note for this change, as we will do a single release note for the entire feature
```release-note
NONE
```
=> Determine candidate ordering for Fair Sharing in Hierarchical Cohorts

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, site/content/en/docs/concepts/cluster_queue.md, site/content/en/docs/concepts/preemption.md, site/content/en/docs/reference/kueue.v1beta1.md
/kind bug
preemption.borrowWithinCohort is being used to override dominantResourceShare, causing preemptions which do not match scheduling order, resulting in the bug described [here](https://github.com/kubernetes-sigs/kueue/issues/3779#issuecomment-2585719122). We do not document preemption.borrowWithinCohort as applying to FairSharing, but only the other two preemption policies - [link](https://github.com/kubernetes-sigs/kueue/blob/8541885fb81e7dcbea20aab937322c144cf1dc85/site/content/en/docs/concepts/preemption.md?plain=1#L121-L122).
Fixes #3779
```release-note
Update FairSharing to be incompatible with ClusterQueue.Preemption.BorrowWithinCohort. Using these parameters together is a no-op, and will be validated against in future releases. This change fixes an edge case which triggered …
```
=> Do not consider preemption.borrowWithinCohort in FairSharing preemptions

keps/3899-remove-finalizers-with-strict-patch/README.md, keps/3899-remove-finalizers-with-strict-patch/kep.yaml
Create a KEP for RemoveFinalizersWithStrictMode feature-gate.
Part of #3899 
```release-note
NONE
```
=> docs: create RemoveFinalizersWithStrictPatch KEP

pkg/util/testingjobs/rayjob/wrappers.go, test/e2e/multikueue/e2e_test.go, test/e2e/tas/rayjob_test.go
/kind cleanup
It would be better not to use an empty slice.
Fixes #
This is follow-up of https://github.com/kubernetes-sigs/kueue/pull/4341
```release-note
NONE
```
=> chore: Avoid empty slice usage in RaJob testings

Makefile-test.mk
/kind cleanup
I applied the same approach as https://github.com/kubernetes-sigs/kueue/pull/3202 to our integration tests.
In the integration testings, object files will be created when gomega builds each package for testings.
Fixes #
Related to https://github.com/kubernetes-sigs/kueue/issues/3196
```release-note
NONE
```
=> Fix 'has malformed LC_DYSYMTAB' warnings for integration testings for MacOS

pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, pkg/scheduler/scheduler_test.go, site/content/en/docs/concepts/preemption.md, test/integration/singlecluster/scheduler/preemption_test.go, test/util/util.go
/kind feature
Adds the JobUID to preemption condition messages.  This makes it easy to get the preempting workload using `kubectl get workloads --selector=kueue.x-k8s.io/job-uid=<JobUID>`
Fixes #4038
```release-note
Adds the JobUID to preemption condition messages.  This makes it easy to get the preempting workload using `kubectl get workloads --selector=kueue.x-k8s.io/job-uid=<JobUID>`
```
=> Add JobUID to preemption condition messages

pkg/cache/snapshot.go, pkg/cache/tas_flavor_snapshot.go, pkg/cache/tas_flavor_snapshot_test.go
/kind feature
Allows to dump the free capacity of TAS snapshots per domain.
Fixes #3493
```release-note
NONE
```
=> TAS: allow to dump the usage of domains for TAS ResourceFlavors

.golangci.yaml, pkg/controller/admissionchecks/multikueue/multikueuecluster.go, pkg/controller/jobs/jobset/jobset_controller.go
/kind cleanup
Enable `nilerr` and `nilnesserr` linters to find places where returning `nil` may be wrong.
[`nilerr`](https://golangci-lint.run/usage/linters/#nilerr) finds places that return nil even if it checks that the error is not nil.
[`nilnesserr`](https://golangci-lint.run/usage/linters/#nilnesserr) reports constructs that checks for err != nil, but returns a different nil value error.
The `nilerr` linter founds two places where `err` is not `nil`, but returned value is `nil`:
1. In the `clustersReconciler.Reconcile`:
```go
err := c.localClient.Get(ctx, req.NamespacedName, cluster)
if client.IgnoreNotFound(err) != nil {
return reconcile.Result{}, err
}
log.V(2).Info("Reconcile MultiKueueCluster")
if err != nil || !cluster.DeletionTimestamp.IsZero() { …
```
=> chore: Enable nilerr, nilnesserr

pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/snapshot.go, pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/workload/workload.go, test/integration/singlecluster/tas/tas_test.go
/kind feature
Fixes #3754
```release-note
Use TAS for workloads implicitly (without TAS annotations) when the target CQ is TAS-only, meaning
all the resource flavors have spec.topologyName specified. The implied behavior is as for the "preferred" 
annotation pointing to the lowest topology level.
```
=> TAS: Use TAS implicitly when CQ is TAS-only

keps/2724-topology-aware-scheduling/README.md
Part of  #3754
This is a follow up to the implementation PR: https://github.com/kubernetes-sigs/kueue/pull/4519
```release-note
NONE
```
=> TAS: Update KEP with the implicit defaulting of TAS annotations

pkg/controller/jobframework/setup.go
/kind bug
Fixes webhook registration bug for enabled frameworks whose APIs were not available when the Kueue controller started.
Fixes #4546 
```release-note
Fixes a bug that would result in default values not being properly set on creation for enabled integrations whose API was not available when the Kueue controller started.
```
=> fix webhook registration when API is available

keps/4377-metrics-tls/README.md, keps/4377-metrics-tls/kep.yaml
KEP for securing metrics with TLS.
KEP for #4377 
```release-note
NONE
```
=> KEP-4377: Secured Prometheus metrics endpoints

pkg/scheduler/preemption/preemption.go
/kind cleanup
This cleanup will make the preemption PR for #3759 much smaller in size and easier to review.
Please review commits in order
* First commit: a minimal move. We redefine some variables in each function, and recompute `newNominatedShareValue` in `runSecondFsStrategy`
* Second commit: some cleanup for better structure and readability
```release-note
NONE
```
=> Refactor FairSharing Preemption

keps/2724-topology-aware-scheduling/kep.yaml, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/features/kube_features.go
/kind cleanup
Add discussed here: https://github.com/kubernetes-sigs/kueue/pull/4560#issuecomment-2717339479 this is a preparatory PR 
Part of #4474 
```release-note
NONE
```
=> TAS: Rename MostAllocatedFit -> BestFit, LeastAllocatedFit -> MostFreeCapacityFit

test/util/e2e.go
/kind cleanup
Thanks to @mimowo we identified 2 issues with `WaitForActivePodsAndTerminate`:
* we consider pods in Pending state, which is too early
* we do not check if the agnhost service is ready and listen on the port
Due to that some of request were send into void or to not completely ready test pod.
This PR addresses both of those issues.
We consider only Running pods and they must also response to `readyz` request.
This fix will potentially resolve many flakiness of the e2e tests.
Fixes #4514
```release-note
NONE
```
=> [Cleanup] make terminating pods not racy

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, site/content/en/docs/concepts/cluster_queue.md, site/content/en/docs/concepts/preemption.md, site/content/en/docs/reference/kueue.v1beta1.md
/kind bug
Cherry-pick bug fix https://github.com/kubernetes-sigs/kueue/pull/4165 to 0.9
```release-note
Update FairSharing to be incompatible with ClusterQueue.Preemption.BorrowWithinCohort. Using these parameters together is a no-op, and will be validated against in future releases. This change fixes an edge case which triggered an infinite preemption loop when these two parameters were combined.
```
=> Do not consider preemption.borrowWithinCohort in FairSharing preemptions (to 0.9)

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, site/content/en/docs/concepts/cluster_queue.md, site/content/en/docs/concepts/preemption.md, site/content/en/docs/reference/kueue.v1beta1.md
/kind bug
Cherry-pick bug fix #4165 to 0.10
```release-note
Update FairSharing to be incompatible with ClusterQueue.Preemption.BorrowWithinCohort. Using these parameters together is a no-op, and will be validated against in future releases. This change fixes an edge case which triggered an infinite preemption loop when these two parameters were combined.
```
=> Do not consider preemption.borrowWithinCohort in FairSharing preemptions (to 0.10)

apis/kueue/v1alpha1/tas_types.go, apis/kueue/v1beta1/workload_types.go, apis/kueue/v1beta1/zz_generated.deepcopy.go, charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml, charts/kueue/values.yaml, client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go, config/components/crd/bases/kueue.x-k8s.io_workloads.yaml, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/controller/jobframework/tas.go, pkg/controller/jobframework/tas_validation.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go, pkg/features/kube_features.go, site/content/en/docs/reference/kueue.v1beta1.md, test/integration/singlecluster/controller/jobs/job/job_controller_test.go
/kind feature
This PR introduces changes described in this KEP #4542 :
- Adds a new annotation
- Extends PodSetTopologyRequest API with .unconstrained field
Part of #4474 
```release-note
TopologyAwareScheduling can now be used with `kueue.x-k8s.io/podset-unconstrained-topology` annotation
```
=> TAS: Add the `kueue.x-k8s.io/podset-unconstrained-topology` annotation

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/config/validation.go, pkg/config/validation_test.go, pkg/features/kube_features.go
/kind feature
This PR introduces changes described in this KEP #4542 :
- Adds TAS profiles 
- Adds LeastFreeCapacityFit algorithm
Part of https://github.com/kubernetes-sigs/kueue/issues/4474
Part of https://github.com/kubernetes-sigs/kueue/issues/4570
I'll add more integration test, but it's already ready for the first pass
```release-note
TopologyAwareScheduling can now be used with profiles based on feature gates. TopologyAwareScheduling has now a new algorithm LeastFreeCapacityFit
```
=> TAS: Add TAS profiles and the LeastFreeCapacityFit algorithm

pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go
/kind cleanup
Previously, we'd fall back on non FairSharing logic if there were
only candidates from the preempting ClusterQueue.
I was debugging some unit tests in #4572, and had
to write some strange logic to make sure we hit the FairSharing branch,
if there were only candidates from the ClusterQueue.
For consistency, and ease of debugging when FS is enabled, it is
better that FairSharing is a well lit path, and that we will only go down
that branch when the FairSharing flag is enabled.
```release-note
NONE
```
=> Always use FairSharing preemption logic when FS enabled

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/features/kube_features.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go
… improve integration test to showcase unconstrained works as intended
/kind feature
https://github.com/kubernetes-sigs/kueue/pull/4574#issuecomment-2721156510
Fixes #
```release-note
NONE
```
=> TAS: change implied default to unconstrained, remove the `TASImplicitDefaultUnconstrained` feature gate

apis/config/v1beta1/configuration_types.go, charts/kueue/templates/certmanager/certificatemetrics.yaml, charts/kueue/templates/manager/manager.yaml, charts/kueue/templates/prometheus/monitor.yaml, charts/kueue/values.yaml, cmd/kueue/main.go, config/components/certmanager/certificate-metrics.yaml, config/components/certmanager/kustomization.yaml, config/components/prometheus/kustomization.yaml, config/components/prometheus/monitor_tls_patch.yaml, config/default/cert_metrics_manager_patch.yaml, config/default/kustomization.yaml, site/content/en/docs/reference/kueue-config.v1beta1.md
/kind feature
Add a way to give tls certificates to metrics server
Fixes #4377 
```release-note
Allow one to configure certificates for metrics
```
=> add ability to give tls certificates to metrics server

pkg/hierarchy/cycle.go
/kind cleanup
Fix typo, memoizing -> memorizing.
Fixes #
```release-note
NONE
```
=> Fix typo, memoizing -> memorizing.

pkg/scheduler/fairsharing/strategy.go, pkg/scheduler/preemption/preemption.go
/kind cleanup
Part of #https://github.com/kubernetes-sigs/kueue/issues/3759. This will help to reduce diff in #4572.
Introducing the new types will ensure that the correct DominantResourceShare is passed to the fairsharing.Strategy. Additionally, move FairSharing strategies to a new package/file. Finally, we rename variables to match new types.
Please review each commit individually
```release-note
NONE
```
=> Refactor and Introduce Types to FairSharingStrategy

pkg/cache/tas_flavor_snapshot.go, pkg/controller/admissionchecks/multikueue/controllers.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/jobframework/webhook/builder.go, pkg/hierarchy/manager.go, pkg/util/testingjobs/appwrapper/wrappers.go, pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go, pkg/util/testingjobs/tfjob/wrappers_tfjob.go
/kind cleanup
Fix comment prefixes.
Fixes #
```release-note
NONE
```
=> Fix comment prefixes.

pkg/cache/tas_flavor_snapshot.go
/kind bug
I cherry-picked the part of https://github.com/kubernetes-sigs/kueue/pull/4441.
> The solution for https://github.com/kubernetes-sigs/kueue/issues/4436 is cloning the SinglePodRequests object to avoid write operation propagation.
Only this is cherry-picked to release-0.10 and the following fixes are not cherry-picked since this update operation is only for TAS preemption and release-0.10 does not have such mechanism
> The solution for https://github.com/kubernetes-sigs/kueue/issues/4439 is to count up and down the number of Pods in the TASFlavorSnapshot.updateTASUsage.
By this pods count, the preemptor can appropriately simulate if candidates preemptee allows higher workloads to make a room in the following:
Fixes #
```release-note
NONE
```
=> [release-0.10] Fix unintended write Operation for TAS SinglePodRequests

test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/appwrapper_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/kueuectl_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/singlecluster/visibility_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/pod_group_test.go, test/util/util.go
/kind cleanup
Wait for all Pods deleted in AfterEach block.
Part of #4520
```release-note
NONE
```
=> Wait for all Pods deleted in AfterEach block.

test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
/kind flake
Fix "Admits workloads respecting fair share" test.
Fixes #
Catch it on stress test.
```release-note
NONE
```
=> Fix Admits workloads respecting fair share test.

test/util/e2e.go
/kind cleanup
To know how long it takes on CI to start an operator individually. This might be useful knowledge when debugging some flakes. Also, the more granual logging helps to know locally when something is going wrong.
```release-note
NONE
```
=> e2e testing: Log wait time per operator

test/e2e/tas/appwrapper_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go
/kind cleanup
Cleanup to exit tests cleanly. Also, killing pods occassionally might be taking long - if the DELETE request hits the "Running" Pods before the SIGTERM trap is registered, then SIGKILL will be triggered in 30s, but this takes unnecessary time.
```release-note
NONE
```
=> TAS: use exit fast images wherever possible (cleanup)

pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/controller/tas/topology_ungater.go
/kind cleanup
The `ungateBatchPeriod` and `nodeBatchPeriod` are the same batch period as `constants. UpdatesBatchPeriod` as you can see this.
https://github.com/kubernetes-sigs/kueue/blob/3eaae45a95d6307b17cfa0b68de8a4e1a20f1709/pkg/constants/constants.go#L32
Fixes #
```release-note
NONE
```
=> chore: Use reconcile batch period constants

pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/cohort.go, pkg/cache/resource_node.go, pkg/cache/snapshot.go, pkg/cache/snapshot_test.go, pkg/hierarchy/cycle.go, pkg/hierarchy/manager.go, pkg/hierarchy/manager_test.go, pkg/queue/cohort.go, pkg/queue/manager.go, pkg/scheduler/preemption/preemption_test.go
/kind cleanup
Get rid of memoizing. This isn't a performance critical section, and this is a bug risk.
See https://github.com/kubernetes-sigs/kueue/pull/4561#discussion_r1995727103, where stress testing uncovered (probably harmless) memory race
Fixes #
```release-note
NONE
```
=> Make HasCycle Stateless

apis/config/v1beta1/configuration_types.go, apis/kueue/v1beta1/clusterqueue_types.go, apis/kueue/v1beta1/fairsharing_types.go, apis/kueue/v1beta1/workload_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml, pkg/metrics/metrics.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, pkg/scheduler/scheduler.go, site/content/en/docs/reference/kueue-config.v1beta1.md, site/content/en/docs/reference/kueue.v1beta1.md
/kind cleanup
Consistently present Fair Sharing to users. In this change, we update api, code, and generated files. Also see https://github.com/kubernetes-sigs/kueue/pull/4649, where we update docs
Fixes #
```release-note
Preemption reason changed from "fair sharing within the cohort" to "Fair Sharing within the cohort"
```
=> Consistently Capitalize Fair Sharing - api/pkg

test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/pod_test.go, test/util/util.go
/kind cleanup
Make sure terminated pods are filtered by the job name to not accidentally remove pods from other test.
Increase debug ability in pod_test - `Pod groups when Single CQ should allow to preempt the lower priority group` by dumping pod status of pod that is in wrong phase.
Fixes #4434
```release-note
NONE
```
=> [Cleanup] Filter termination of pods in tests by job name

pkg/util/testingjobs/deployment/wrappers.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go, pkg/util/testingjobs/statefulset/wrappers.go, test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/tas/leaderworkerset_test.go, test/e2e/tas/statefulset_test.go
/kind flake
We have faced a lot of flakiness lately, possibly due to high load on test infra, thus increased timeouts.
Add TerminationGracePeriod when applicable for tests to decrease pod deletion waiting time and possible timeouts.
Fixes #4626
```release-note
NONE
```
=> [Flake] Add TerminationGracePeriod when applicable for tests

pkg/util/testingjobs/deployment/wrappers.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go, pkg/util/testingjobs/statefulset/wrappers.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/tas/statefulset_test.go
Cherry pick of #4660 on release-0.10.
#4660: [Flake] Add TerminationGracePeriod when applicable for tests
```release-note
NONE
```
=> Automated cherry pick of #4660: [Flake] Add TerminationGracePeriod when applicable for tests

test/util/e2e.go
/kind cleanup
Stick to proper Kuberay operator namespace which is "ray-system"
Relates to #3822
```release-note
NONE
```
=> [Cleanup] Add TODO note to fix Kuberay operator namespace

hack/e2e-common.sh, hack/multikueue-e2e-test.sh, pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/raycluster/raycluster_multikueue_adapter.go, pkg/controller/jobs/raycluster/raycluster_multikueue_adapter_test.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter.go, pkg/controller/jobs/rayjob/rayjob_multikueue_adapter_test.go, pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go, pkg/util/testingjobs/raycluster/wrappers.go, pkg/util/testingjobs/rayjob/wrappers.go, test/e2e/multikueue/suite_test.go
/kind feature
As of Kuberay v1.3.1 ManagedBy is fully supported.
Kueue needs to make use of it and also we can start to use Kuberay operator in management cluster.
Relates to #3822
```release-note
NONE
```
=> [Feature] Integrate support of Kuberay ManagedBy

Makefile, charts/kueue/Chart.yaml
/kind cleanup
This is just a cleanup without user-facing implications, because the charts published actually have the leading "v":
```
> helm list -nkueue-system       
NAME 	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
kueue	kueue-system	1       	2025-03-20 14:04:01.522860323 +0100 CET	deployed	kueue-v0.11.0	v0.11.0 
```
This is because the value is actually overwritten in `hack/push-chart.sh`
I will also cherry-pick to 0.10.
```release-note
NONE
```
=> Adjust setting the appVersion for charts in makefile script

pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_pod_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, test/e2e/singlecluster/leaderworkerset_test.go
/kind bug
Fix workload priority for LeaderWorkerSet.
Fixes #
On create LeaderWorkerSet with WorkloadPriorityClass we have an error
```
"error":"admission webhook \"[vpod.kb.io](http://vpod.kb.io/)\" denied the request: metadata.labels[[kueue.x-k8s.io/priority-class](http://kueue.x-k8s.io/priority-class)]: Invalid value: \"high-priority\": field is immutable"...
```
```release-note
Fixed bug that doesn't allow to use WorkloadPriorityClass on LeaderWorkerSet.
```
=> Fix workload priority for LeaderWorkerSet.

pkg/util/testingjobs/statefulset/wrappers.go, test/e2e/singlecluster/statefulset_test.go
/kind cleanup
Add sanity e2e test for WorkloadPriorityClass on StatefulSet.
Fixes #
```release-note
NONE
```
=> Add sanity e2e test for WorkloadPriorityClass on StatefulSet.

test/e2e/tas/rayjob_test.go
/kind cleanup
After upgrade of Kuberay v1.3.1 we should see no flakiness around creation of submitter pod.
Fixes #4665
```release-note
NONE
```
=> [Cleanup] Make sure RayJob submitter pod was created

test/integration/singlecluster/scheduler/scheduler_test.go, test/util/e2e.go
/kind cleanup
A followup to the discussion in https://github.com/kubernetes-sigs/kueue/pull/4690
Relates to #4654
```release-note
NONE
```
=> [Cleanup] Provide a function that creates namespace from wrapper

test/e2e/certmanager/suite_test.go
/kind cleanup
Use `util.SetupLogger()` in the certmanager suite, like in other places, to control logging verbosity.
Part of #4555
```release-note
NONE
```
=> Use util.SetupLogger() on certmanager suite.

pkg/controller/admissionchecks/multikueue/controllers.go, pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/multikueue/workload_test.go, test/integration/multikueue/multikueue_test.go
/kind feature
Enable to check which Worker Cluster was admitted by MultiKueue from the Workload Event of the Manager Cluster.
I would like to be able to check which worker clusters have been admitted by watching the events of the manager cluster's workloads.
Fixes #4749 
```release-note
Output events to indicate which Worker Cluster was admitted to the Manager Cluster's workload.
```
=> feat: Output MultiKueue's Event to workload

test/e2e/multikueue/e2e_test.go, test/integration/multikueue/multikueue_test.go
/kind flake
Testing RayCluster Suspend feature in Kueue is pointless and breaks the rule that only Kueue manipulates the field when the job is managed by the Kueue. 
Fixes #4760
```release-note
NONE
```
=> [Flake] Do not manipulate RayCluster suspend field

test/util/constants.go
/kind flake
Use `agnhost test-web server` instead of `agnhost pause` for e2e tests.
To avoid flakiness observed and summarised in https://github.com/kubernetes/kubernetes/issues/131021
Fixes #4733
```release-note
NONE
```
=> [Flake] Use agnhost `test-webserver` instead of `pause`

test/e2e/customconfigs/skipjobswithoutqueuename_test.go
/kind flake
Prevent test flakiness in Customconfigs for steps of `wait for X to be unsuspended`.
Fixes #4780
```release-note
NONE
```
=> [Flake] Customconfigs Increase timeout waiting for unsuspended to escape flakiness

Makefile-test.mk, README.md
/kind cleanup
Stop supporting k8s v1.29.
Fixes #
```release-note
NONE
```
=> Stop supporting k8s v1.29.

site/content/en/docs/concepts/resource_flavor.md, site/static/examples/admin/resource-flavor-empty.yaml, site/static/examples/admin/resource-flavor-taints.yaml, site/static/examples/admin/resource-flavor-tolerations.yaml
- Update the ResourceFlavor site documentation to enhance readability and ensure a smoother user experience.
Fixes #4499 
```release-note
NONE
```
=> Update ResourceFlavor site documentation

pkg/controller/jobs/appwrapper/appwrapper_controller.go, pkg/controller/jobs/appwrapper/appwrapper_controller_test.go, pkg/controller/jobs/job/job_controller.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/jobset/jobset_controller.go, pkg/controller/jobs/jobset/jobset_controller_test.go, pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go, pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go, pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go, pkg/controller/jobs/mpijob/mpijob_controller.go, pkg/controller/jobs/mpijob/mpijob_controller_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go, pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/raycluster/raycluster_controller_test.go, pkg/controller/jobs/rayjob/rayjob_controller.go, pkg/controller/jobs/rayjob/rayjob_controller_test.go
/kind cleanup
PodSetTopologyRequests are now configured only when TopologyAwareScheduling feature gate is enabled.
Fixes #4590
```release-note
PodSetTopologyRequests are now configured only when TopologyAwareScheduling feature gate is enabled.
```
=> fix: configure PodSetTopologyRequests only when TAS enabled

.golangci.yaml, client-go/applyconfiguration/utils.go, cmd/kueuectl/app/list/list_pods_test.go, cmd/kueueviz/backend/handlers/cluster_queues.go, cmd/kueueviz/backend/handlers/cohorts.go, cmd/kueueviz/backend/handlers/local_queue_workloads.go, cmd/kueueviz/backend/handlers/local_queues.go, cmd/kueueviz/backend/handlers/resource_flavors.go, cmd/kueueviz/backend/handlers/websocket_handler.go, cmd/kueueviz/backend/handlers/workloads.go, cmd/kueueviz/backend/handlers/workloads_dashboard.go, pkg/config/config_test.go, pkg/controller/jobframework/integrationmanager_test.go, pkg/controller/jobframework/validation.go, pkg/util/heap/heap.go, pkg/util/pod/pod.go, pkg/util/testing/client.go, pkg/util/testing/condition_matchers.go, pkg/util/testing/error_matchers.go
/kind cleanup
Replace `interface{}` with `any` for consistency. Enable `revive.use-any` to enforce that.
```release-note
NONE
```
=> chore: use 'any' instead of 'interface{}' for consistency

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, site/content/en/docs/concepts/cluster_queue.md, site/content/en/docs/concepts/preemption.md, site/content/en/docs/reference/kueue.v1beta1.md
/kind bug
Allows to upgrade to the latest 0.10.x version of Kueue to the users who use FairSharing and ClusterQueue.Preemption.BorrowWithinCohort.
This combination is buggy, but for now we don't have a better replacement, and no mitigation is known.
This will give users time to mitigate or find replacement configurations.
The reverting is only applied to 0.10 as 0.11 and main drifted already too much. 
Hopefully, we will have a better replacement for the configuration in the future. 
At the very least we give time to users to figure out a mitigation in the long run.
```release-note
Revert making ClusterQueue.Preemption.BorrowWithinCohort as no-op when used with FairSharing, by reverting
https://github.com/kubernetes-sigs/kueue/pull/4165, which was done to prevent infinite-preemption loops …
```
=> Revert "Do not consider preemption.borrowWithinCohort in FairSharing..."

pkg/scheduler/preemption/policy.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go, test/integration/scheduler/fairsharing/fair_sharing_test.go, test/integration/scheduler/scheduler_test.go, test/util/util_scheduling.go
/kind bug
Cherry-pick #4813. We additionally cherry-pick #4813, #4812, and copy some code from #4695
Merge conflicts:
- e2e Metrics test file doesn't exist in 0.10
- TestScheduleForTASPreemption doesn't exist in 0.10
- TestScheduleForTASCohorts doesn't exist in 0.10
- FS Integration test "using hierarchical cohorts" doesn't exist in 0.10
- Dependency of FinishEvictionOfWorkloadsInCQ, workload.ApplyAdmissionStatus, takes one fewer parameter
- Needed to add function MakeWorkloadWithGeneratedName, which new tests depend on
```release-note
Fix bug which resulted in under-utilization of the resources in a Cohort.
Now, when a ClusterQueue is configured with `preemption.reclaimWithinCohort: Any`,
its resources can be lent out more freely, as we are certain that we can reclaim
them later. Please …
```
=> [release-0.10] cherry-pick #4813

hack/e2e-common.sh, hack/multikueue/manager-cluster.kind.yaml, hack/multikueue/worker-cluster.kind.yaml
for multi-node single cluster e2e tests
/kind cleanup
Right now we load all the images to all the nodes in the single cluster e2e tests.
However there is no need to spend precious seconds (multiplied by number of images and their size) to do that for `control-plane` node.
This is especially true when we talk about e.g. Ray-project image that has 2.2GB. 
```release-note
NONE
```
=> [Cleanup] Do not load images onto control-plane nodes

test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/customconfigs/suite_test.go
/kind cleanup
Move update kueue configuration logic to separate function. We need it to do not duplicate this logic in future Describe blocks.
Fixes #
Prepare PR for #4824
```release-note
NONE
```
=> Move update kueue configuration logic to separate function.

hack/e2e-common.sh
/kind cleanup
New version of Kubeflow training-Operator(v1.9.1) does not place image at the deployment.
That was caught by the dependabot run: https://github.com/kubernetes-sigs/kueue/pull/4836
It could be consider a bug on the Kubeflow side or we could adjust.
This change takes the image version from the kustomization.yaml directly.
Fixes #
```release-note
NONE
```
=> [Cleanup] Fix the kubeflow/training-operator image version reference

test/integration/multikueue/enabled_integration_test.go, test/integration/multikueue/jobs_test.go, test/integration/multikueue/no_gc_test.go, test/integration/multikueue/setup_test.go, test/integration/multikueue/suite_test.go, test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
/kind cleanup
As a follow-up on the request to correct MultiKueue naming letter case - https://github.com/kubernetes-sigs/kueue/pull/4855#discussion_r2024209455 
```release-note
NONE
```
=> Cleanup MultiKueue naming letter case.

config/alpha-enabled/kustomization.yaml
/kind cleanup
To fix artifact generation, as
```
> make artifacts IMAGE_REGISTRY=registry.k8s.io/kueue GIT_TAG=$VERSION
cd config/components/manager && /usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/kustomize edit set image controller=registry.k8s.io/kueue/kueue:v0.11.3
if [ -d artifacts ]; then rm -rf artifacts; fi
mkdir -p artifacts
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/kustomize build config/default -o artifacts/manifests.yaml
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/kustomize build config/dev -o artifacts/manifests-dev.yaml
/usr/local/google/home/michalwozniak/go/src/sigs.k8s.io/kueue/bin/kustomize build config/alpha-enabled -o artifacts/manifests-alpha-enabled.yaml
Error: accumulating resources: accumulation …
```
=> Fix artifact generation due to wrong alpha-enabled manifests

pkg/util/testingjobs/deployment/wrappers.go, test/e2e/customconfigs/skipjobswithoutqueuename_test.go, test/e2e/singlecluster/appwrapper_test.go
/kind cleanup
Add sanity tests for deployment suspend by parent logic.
Fixes #
```release-note
NONE
```
=> Add sanity tests for deployment suspend by parent logic.

test/e2e/singlecluster/deployment_test.go
Cherry pick of #4894 on release-0.10.
#4894: Use ns.Name instead of ns.Namespace on client.InNamespace()
```release-note
NONE
```
=> Automated cherry pick of #4894: Use ns.Name instead of ns.Namespace on client.InNamespace()

pkg/controller/core/core.go, pkg/features/kube_features.go
/kind bug
Alpha apis should be guarded by feature gate in case people want to disable them.
Cohorts are required to be enabled since the controller is looking for these objects. This means that we must register the alpha API.
Fixes #4869 
```release-note
Allow one to disable cohorts via a HiearachialCohort feature gate
```
=> add feature gate to control cohort controller

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/jobs/pod/pod_multikueue_adapter.go, pkg/controller/jobs/pod/pod_multikueue_adapter_test.go, pkg/util/testingjobs/pod/wrappers.go, test/e2e/multikueue/e2e_test.go, test/integration/multikueue/jobs_test.go
Cherry pick of #4854 on release-0.11.
#4854: Pod groups MultiKueue adapter
```release-note
Fix the support for pod groups in MutliKueue.
```
=> Automated cherry pick of #4854: Pod groups MultiKueue adapter

pkg/webhooks/clusterqueue_webhook.go, pkg/webhooks/clusterqueue_webhook_test.go, pkg/webhooks/cohort_webhook.go, pkg/webhooks/cohort_webhook_test.go
When parent cohort is empty it uses "parent" for cohort and "cohort" for cluster queue.
/kind bug
It fixes misleading error message in case of empty parent for hierarchical cohort and non-zero borrowing/lending limit.
Fixes #4392 
```release-note
NONE
```
=> Differentiate error message for cohort and cluster queue

pkg/controller/core/core.go, pkg/features/kube_features.go
Cherry pick of https://github.com/kubernetes-sigs/kueue/pull/4870 on release-0.11.
```release-note
Allow one to disable cohorts via a HiearachialCohort feature gate
```
=> Manual cherry pick of #4870 add feature gate to control cohort controller

pkg/scheduler/preemption/preemption_test.go
/kind flake
It ensures the assertion catches modifications to mutable state ,that could indicate a bug in preemption logic and specificity ignoring irrelevant differences.
Fixes #
https://github.com/kubernetes-sigs/kueue/issues/4553#event-16794070155
```release-note
NONE
```
=> Assert Snapshot Unmodified in Preemption Tests

pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/util/testing/wrappers.go, pkg/util/testingjobs/jobset/wrappers.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go
/kind bug
Fix `getAncestorWorkload` when one of middle owner object disabled or not managed by Kueue.
Part of #4860
In case
```
Job -> JobSet(disabled) -> AppWrapper (with queue name)
```
or
```
Job -> CustomResource -> AppWrapper (with queue name)
```
we should traverse to root object and get Workload for AppWrapper even if one of middle resources not managed by Kueue.
```release-note
Fixed a bug that caused Kueue to create redundant workloads for each Job when manageJobsWithoutQueueName was enabled, JobSet integration was disabled, and AppWrapper was used for JobSet.
```
=> Fix getAncestorWorkload if integration disabled.

pkg/controller/jobframework/interface.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/pod/pod_controller.go, pkg/util/testing/wrappers.go, pkg/util/testingjobs/jobset/wrappers.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go
Cherry pick of #4824 on release-0.11.
#4824: Fix getAncestorWorkload if integration disabled.
```release-note
Fixed a bug that caused Kueue to create redundant workloads for each Job when manageJobsWithoutQueueName was enabled, JobSet integration was disabled, and AppWrapper was used for JobSet.
```
=> Automated cherry pick of #4824: Fix getAncestorWorkload if integration disabled.

Makefile, netlify.toml
…to change the netlify.toml hugo version to the latest version
/kind cleanup
This PR sets the Sed command to auto bump hugo on release.
Fixes #4811
```release-note
NONE
```
=> Add sync-hugo-version target to sync HUGO_VERSION.

pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/cohort.go, pkg/cache/cohort_snapshot.go, pkg/cache/resource_node.go, pkg/cache/snapshot_test.go, pkg/scheduler/preemption/preemption_test.go
/kind cleanup
Follow up to #4553. After #4635, we can revert #4658 as it is repeating the same assertion. Additionally, we unexport ResourceNode, with the expectation it will only be accessed indirectly behind ClusterQueueSnapshot and CohortSnapshot interfaces.
Fixes #
```release-note
NONE
```
=> Unexport ResourceNode; Cleanup Preemption Test

test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/integration/singlecluster/controller/jobs/kubeflow/kubeflowjob.go, test/util/e2e.go, test/util/util.go
/kind cleanup
Use MustCreate for all Success object creation as we did in other places.
Fixes #
```release-note
NONE
```
=> Use MustCreate for all Success object creation.

site/static/examples/multikueue/create-multikueue-kubeconfig.sh
This PR adds missing `appwrappers` and `appwrappers/status` permissions for the `multikueue-sa` ServiceAccount in the example script `create-multikueue-kubeconfig.sh`.
Without these permissions, `MultiKueueCluster` resources referencing clusters with `AppWrapper` workloads will remain inactive due to permission errors such as:
```
❯ kubectl --context kind-management-kueue-cluster get clusterqueues cluster-queue -o jsonpath="{range .status.conditions[?(@.type == \"Active\")]}CQ - Active: {@.status} Reason: {@.reason} Message: {@.message}{'\n'}{end}"
kubectl  --context kind-management-kueue-cluster get admissionchecks sample-multikueue -o jsonpath="{range .status.conditions[?(@.type == \"Active\")]}AC - Active: {@.status} Reason: {@.reason} Message: …
```
=> Add appwrappers permissions to multikueue service account example.

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/cohort.go, pkg/scheduler/fair_sharing_iterator.go, pkg/scheduler/preemption/fairsharing/least_common_ancestor.go, pkg/scheduler/preemption/fairsharing/ordering.go
/kind cleanup
Fixes #4644 
~Let me know if this was the approach that was expected or if there's a way to make this generic so that the iterator doesn't have to be implemented twice~
**Solved** I was able to implement this in the generic ClusterQueue and Cohort structs
```release-note
NONE
```
=> make iterable function for traversing to root

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/localqueue.go
/kind cleanup
Preparatory for https://github.com/kubernetes-sigs/kueue/pull/4687
Creates a separate file for LocalQueue in cache and moves its type there
Fixes misleading message in LQ update
This is follow up to the discussion https://github.com/kubernetes-sigs/kueue/pull/4687#discussion_r2013912448
```release-note
NONE
```
=> Create public type for LQ in cache

pkg/controller/core/cohort_controller.go, pkg/controller/core/cohort_controller_test.go
/kind bug
We were filtering Cohort reconciles when only FairSharing weight updated. This meant that our internal representation of Cohort was not matching the API representation.
Fixes #4960
```release-note
Fix bug where update to Cohort.FairSharing didn't trigger a reconcile. This bug resulted in the new weight not being used until the Cohort was modified in another way.
```
=> Reconcile Cohort when FairSharing Weight Updated

site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
Fixes #
```release-note
NONE
```
=> Document waitForPodsReady.recoveryTimeout

Makefile-test.mk, site/content/en/docs/contribution_guidelines/testing.md
/kind cleanup
This PR sets the `E2E_KIND_VERSION` Makefile variable based on the `E2E_K8S_VERSION` variable. This is needed to make `test-infra` jobs pass only the `E2E_K8S_VERSION` variable
Part of #4729
```release-note
NONE
```
=> Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION

pkg/resources/requests.go, pkg/resources/requests_test.go, pkg/scheduler/scheduler_test.go
Cherry pick of #4973 on release-0.10.
#4973: [release-0.11] Handle request value with zero in CountIn
```release-note
TAS: Fix bug where scheduling panics when the workload using TopologyAwareScheduling has container request value specified as zero.
```
=> Automated cherry pick of #4973: Handle request value with zero in CountIn

Makefile-test.mk, site/content/en/docs/contribution_guidelines/testing.md
Cherry pick of #4950 on release-0.11.
#4950: Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION
```release-note
NONE
```
=> Automated cherry pick of #4950: Set the E2E_KIND_VERSION mk variable based on the E2E_K8S_VERSION

apis/kueue/v1beta1/fairsharing_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml, pkg/cache/fair_sharing.go, pkg/cache/fair_sharing_test.go, pkg/metrics/metrics.go, pkg/scheduler/preemption/preemption_test.go, site/content/en/docs/reference/kueue.v1beta1.md
/kind bug
We protect workloads running under nominal quota from being preempted, even when Cohort has FairWeight of 0. We do this by only returning math.MaxInt score when the Cohort is borrowing. When a Cohort is not borrowing, it gets a FairShare score of 0.
Fixes #4961
```release-note
Fix bug where Cohorts with FairWeight set to 0 could have workloads running within Nominal Quota preempted
```
=> Protect GuaranteedQuota When FairSharing Weight=0

test/e2e/tas/leaderworkerset_test.go, test/util/util.go
/kind bug
/kind flake
We should delete LeaderWorkerSet before StatefulSets and Pods to prevent situation that LeaderWorkerSet have time to recreate child objects.
Fixes #4908
```release-note
NONE
```
=> Delete LeaderWorkerSets before cleanup StatefulSets and Pods.

hack/push-chart.sh
Follow-up of #4929 for 0.11 release branch
```release-note
NONE
```
=> [release-0.11] Helm: ensure Chart version matches version in registry

pkg/features/kube_features.go
/kind cleanup
Based on https://github.com/kubernetes-sigs/kueue/pull/4985#discussion_r2044812668 discussion, we will handle the FG version as a separate from feature introducting version.
Fixes #
```release-note
NONE
```
=> Update HierarchicalCohorts FG version

Makefile-test.mk
/kind cleanup
This PR removes the `test-e2e-all` Makefile target since is not used anymore. This is a follow-up from #4950 
Fixes #
```release-note
NONE
```
=> Drop test-e2e-all Makefile target

pkg/controller/core/core.go, pkg/features/kube_features.go
Cherry pick of #4985 on release-0.11.
#4985: Fix HierarchicalCohorts feature gate
```release-note
NONE
```
=> Automated cherry pick of #4985: Fix HierarchicalCohorts feature gate

go.mod, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler_test.go, pkg/controller/jobs/pod/pod_controller.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/singlecluster/leaderworkerset_test.go
/kind bug
Add LeaderWorkerSet as owner of Workload.
Fixes #4724
Fixes #4966
```release-note
Fixed a bug that prevented Kueue from retaining the LeaderWorkerSet workload in deactivation status.
Fixed a bug that prevented Kueue from automatically deleting the workload when the LeaderWorkerSet was deleted.
```
=> Add LeaderWorkerSet as owner of Workload.

pkg/util/testingjobs/appwrapper/wrappers.go, pkg/util/testingjobs/job/wrappers.go, pkg/util/testingjobs/jobset/wrappers.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, pkg/util/testingjobs/pod/wrappers.go
/kind cleanup
Use AppendOwnerReference for consistency with other parts of the code.
Fixes #
```release-note
NONE
```
=> Use AppendOwnerReference.

test/e2e/certmanager/suite_test.go, test/e2e/customconfigs/suite_test.go, test/e2e/multikueue/suite_test.go, test/e2e/singlecluster/suite_test.go, test/e2e/tas/suite_test.go
/kind cleanup
Wait for LeaderWorkerSet in E2E customconfigs tests.
Fixes #
```release-note
NONE
```
=> Wait for LeaderWorkerSet in E2E customconfigs tests.

test/util/e2e.go
/kind cleanup
It's common practice to avoid using `fmt.Sprintf` in logs and instead use key-value pairs to make logs more structured. The only place where using `log.info(fmt.Sprintf(...))` is acceptable is in a test utility, and it's fine to use it there. I just opened this PR to follow common practice. This is purely a coding style issue, and I'm fine with closing this PR if the Kueue maintainers prefer the current approach.
Screenshot for running e2e tests with this PR:
```release-note
NONE
```
=> [chore][log] Remove `fmt.Sprintf` from `log.info`

pkg/util/testingjobs/job/wrappers.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/customconfigs/suite_test.go, test/e2e/customconfigs/waitforpodsready_test.go
/kind feature
Add e2e tests for WaitForPodsReady feature
Fixes #4429 
```release-note
NONE
```
=> test: add WaitForPodsReady e2e test

apis/kueue/v1beta1/admissioncheck_types.go, pkg/cache/admissioncheck.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go
/kind cleanup
Remove unused FlavorIndependentAdmissionCheck.
Fixes #
It was missed and not removed in https://github.com/kubernetes-sigs/kueue/pull/4995.
```release-note
NONE
```
=> Remove unused FlavorIndependentAdmissionCheck constant.

apis/kueue/v1beta1/workload_types.go, pkg/controller/core/workload_controller.go, pkg/workload/workload.go
/kind cleanup
Drop deprecated WorkloadEvictedByDeactivation reason.
Fixes #
```release-note
Remove deprecated InactiveWorkload condition reason.
```
=> Drop deprecated WorkloadEvictedByDeactivation reason.

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, test/integration/singlecluster/tas/tas_test.go
/kind bug
This PR adds support for node selectors in TAS. 
Fixes #4571 
The PR has the following changes:
1. Getting node selectors from nodes and using them to filter out non matching nodes.
2. 2 new integrations tests for cases when a node label is either added or updated.
3. Added additional check of `ExpectClusterQueuesToBeActive` for test suite `Node is mutated during test cases` which seemed to be missing compare to the other suites.
```release-note
Add support for Node Selectors in TAS Workloads.
```
=> Add support for node selectors based filtering in TAS

keps/4136-admission-fair-sharing/README.md, keps/4136-admission-fair-sharing/kep.yaml
/kind feature
KEP for a new resource fair sharing method.
Fixes #4136 
```release-note
NONE
```
=> KEP-4136: Admission Fair Sharing

Makefile-test.mk
/kind cleanup
Split integration tests into baseline and extended targets.
Part of #5062
Sometimes we miss testing the slow and redundant integration tests before merging to main, which results in errors in periodic tests. This happens because the presubmit integration tests are filtered by the `INTEGRATION_RUN_ALL` flag.
https://github.com/kubernetes-sigs/kueue/blob/3279d9c05817e465229fac6bdc64250c890ea7dd/Makefile-test.mk#L51-L54
To prevent this, I propose running the slow and redundant tests in parallel with the required tests instead of skipping it in presubmit tests.
```release-note
NONE
```
=> Split integration tests into baseline and extended targets.

test/performance/scheduler/checker/checker_test.go, test/performance/scheduler/default_rangespec.yaml
/kind bug
/kind flake
As agreed in https://github.com/kubernetes-sigs/kueue/issues/4851#issuecomment-2815069263 , the assertions for CPU and memory have been removed from CommandStats.
Fixes #4851 
```release-note
NONE
```
=> Fix flaky perf scheduling test

Makefile-test.mk
Cherry pick of #5068 on release-0.10.
#5068: Split integration tests into baseline and extended targets.
```release-note
NONE
```
=> Automated cherry pick of #5068: Split integration tests into baseline and extended targets.

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, test/integration/tas/tas_test.go
Cherry pick of #4989 on release-0.10.
#4989: Add support for node selectors based filtering in TAS
**Comments for reviewers**:
Some adjustments to tests were needed between this PR and corresponding ones for [main](https://github.com/kubernetes-sigs/kueue/pull/4989) and [release-0.11](https://github.com/kubernetes-sigs/kueue/pull/5079). Namely a specific topology had to be specified because assumed topology was introduced in 0.11.
```release-note
Add support for Node Selectors in TAS Workloads.
```
=> Automated cherry pick of #4989: Add support for node selectors based filtering in TAS

.github/workflows/sync-dependabot.yaml
This PR will automate the hugo version bumping and it will alter dependabot's commits to bump the version where dependabot can't.
Fixes #4811
```release-note
NONE
```
=> Add git hub action to automatically bump hugo version on dependabot commit

hack/push-chart.sh
Cherry pick of #5097 on release-0.11.
#5097: Fix script to push helm chart
```release-note
NONE
```
=> Automated cherry pick of #5097: Fix script to push helm chart

hack/push-chart.sh
Cherry pick of #5105 on release-0.11.
#5105: Use EXTRA_TAG for Helm App version if it is semantic versioning
```release-note
NONE
```
=> Automated cherry pick of #5105: Use EXTRA_TAG for Helm App version if it is semantic versioning

pkg/workload/workload.go, pkg/workload/workload_test.go
/kind bug
fix infinite inequality loop for propagate resource requests check
Fixes #5058
```release-note
Fix a bug where PropagateResourceRequests would always trigger an API status patch call.
```
=> fix: PropagateResourceRequests map equality check

pkg/util/testing/condition_matchers.go, pkg/util/testing/condition_matchers_test.go, test/e2e/customconfigs/waitforpodsready_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/tas/leaderworkerset_test.go
/kind cleanup
Use condition matcher with reason.
Fixes #
```release-note
NONE
```
=> Use condition matcher with reason.

apis/kueue/v1beta1/resourceflavor_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml, config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml, site/content/en/docs/concepts/resource_flavor.md, site/content/en/docs/reference/kueue.v1beta1.md
As we discussed in https://github.com/kubernetes-sigs/kueue/issues/4646, we want to mention what happens if nodeTains and tolerations are specified in the same ResourceFlavor.
Fixes https://github.com/kubernetes-sigs/kueue/issues/4646
```release-note
NONE
```
=> Add ResourceFlavor specificatios for coupling of nodeTaints and tolerations to documentation

test/e2e/singlecluster/deployment_test.go
Cherry pick of #5163 on release-0.10.
#5163: Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.
```release-note
NONE
```
=> Automated cherry pick of #5163: Fix "Deployment should admit workloads after change queue-name if AvailableReplicas = 0" e2e test.

Makefile-test.mk, test/e2e/singlecluster/kuberay_test.go
/kind feature
To ensure the basic integration with KubeRay works.
Fixes #3829
```release-note
NONE
```
=> [Feature] Add sanity singlecluster e2e tests for KubeRay

pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go
/kind bug
If a RayJob is created without the Kueue label or
without the `manageJobsWithoutQueueName` enabled, but
it has `LocalQueueDefaulting` feature enabled
and not used as has no localQueue named default,
that job is still being marked as Kueue managed when it's not.
This commit fixes the issue by ensuring that having the
`LocalQueueDefaulting` feature enabled (without existance
of a localqueue default) is not a factor to
define if a Job is managed by Kueue.
Fixes #
```release-note
Fix RayJob webhook validation when `LocalQueueDefaulting` feature is enabled.
```
=> Fix RayJob webhook validation 

pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go
Cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/5073 to release-0.11.
If a RayJob is created without the Kueue label or
without the `manageJobsWithoutQueueName` enabled, but it has `LocalQueueDefaulting` feature enabled
and not used as has no localQueue named default,
that job is still being marked as Kueue managed when it's not. This commit fixes the issue by ensuring that having the `LocalQueueDefaulting` feature enabled (without existance of a localqueue default) is not a factor to
define if a Job is managed by Kueue.
Fixes #
```release-note
Fix RayJob webhook validation when `LocalQueueDefaulting` feature is enabled.
```
=> cherry pick of #5073: Fix RayJob webhook validation

pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go
cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/5179 to release-0.10
If a RayJob is created without the Kueue label or
without the `manageJobsWithoutQueueName` enabled, but it has `LocalQueueDefaulting` feature enabled
and not used as has no localQueue named default,
that job is still being marked as Kueue managed when it's not. This commit fixes the issue by ensuring that having the `LocalQueueDefaulting` feature enabled (without existance of a localqueue default) is not a factor to
define if a Job is managed by Kueue.
Fixes #
```release-note
Fix RayJob webhook validation when `LocalQueueDefaulting` feature is enabled.
```
=> cherry-pick of 5179: Fix RayJob webhook validation 

Makefile, hack/e2e-common.sh
/kind cleanup
In CI we only use amd64 architecture. 
The need to specify different architectures for e2e tests is purely for local use.
Remove architecture based conditions in the Makefile and test scripts and
allow to override PLATFORMS locally for e2e tests.
Fixes #5152
```release-note
NONE
```
=> [Cleanup] Drop architecture conditions for Ray image env

test/e2e/multikueue/e2e_test.go
/kind flake
Align with other test cases for the RayCluster and RayJob. This allows to prevent timeout when used with full ray image - periodic tests.
Fixes #4853
```release-note
NONE
```
=> [Flake] Extend timeout for RayCluster MultiKueue e2e tests

test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
/kind feature
Fixes #4948
```release-note
NONE
```
=> Deflake ProvReq integration test by adding 100ms sleep to avoid data race

test/integration/multikueue/jobs_test.go
/kind flake
When for some reason worker's cq creation event is delayed, 
a workload coming from the manager's cq is inadmissible due to lack of cq existence. 
Make sure both cq and lq for each cluster are ready before each test.
Fixes #5169
```release-note
NONE
```
=> [Flake] MK integration test: Wait for cq and lq to become ready before the test execution.

test/integration/multikueue/jobs_test.go
Correct obvious typo
Related to #5169
```release-note
NONE
```
=> [Cleanup] Correct ExpectClusterQueuesToBeActive for worker2Cq in mk integration

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
This change prevents a potential nil pointer panic in the scheduler when a ClusterQueue is deleted between the time a workload is selected for scheduling and when its ClusterQueue is retrieved from the snapshot.
/kind bug
Fixes # https://github.com/kubernetes-sigs/kueue/issues/4959#issuecomment-2831045590
```release-note
Fix panic due to nil ptr exception in scheduler when ClusterQueue is deleted concurrently.
```
=> scheduler: Fix nil ClusterQueue handling

.github/workflows/sync-dependabot.yaml
/kind cleanup
Run sync-dependabot workflow only with `ok-to-test` label.
Fixes #
To avoid running dependabot workflow from fork repo. See https://github.com/kubernetes-sigs/kueue/pull/5218.
```release-note
NONE
```
=> Run sync-dependabot workflow only with ok-to-test label.

test/util/util.go
/kind cleanup
Use proper offset (2)  because expectCounterMetric is called indirectly via other helper functions. 
With the offset the line number points to the actual test code, not the helper.
Fixes #
```release-note
NONE
```
=> Fix the message produced by integration tests by using proper offset

test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
/kind cleanup
To simplify the test code, these calls aren't necessary because the workload's status.admissionChecks is initialized by the workload_controller.go `reconcileSyncAdmissionChecks`. 
Fixes #
```release-note
NONE
```
=> Drop unnecessary use of SetWorkloadsAdmissionCheck in tests

keps/1282-pods-ready-requeue-strategy/README.md, keps/1282-pods-ready-requeue-strategy/kep.yaml
Update KEP-1282 to support WaitForPodsReady metrics for eviction by reason.
Part of #5071
```release-note
NONE
```
=> Update KEP-1282 to support WaitForPodsReady metrics for eviction by reason

pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/resourceflavor_controller.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_multikueue_adapter.go
/kind cleanup
When the deletionTimestamp is zero, we should handle the object the same as null deletionTimestamp.
Fixes #
```release-note
NONE
```
=> Do not distinguish null and zero in DeletionTimestamp

apis/kueue/v1beta1/provisioningrequestconfig_types.go
/kind cleanup
Follow up to https://github.com/kubernetes-sigs/kueue/pull/5204
```release-note
NONE
```
=> Drop unnecessary omitempty for ProvisioningRequestConfig fields

pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/validation.go, pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/deployment/deployment_webhook_test.go, pkg/controller/jobs/job/job_controller_test.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go, pkg/controller/jobs/statefulset/statefulset_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook_test.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go
/kind feature
To allow users to update a workload's priority from a job.
Fixes #5004
```release-note
Allow users to update the priority of a workload from within a job.
```
=> Update Workload priority based on update of the `kueue.x-k8s.io/priority-class` label 

site/content/en/docs/tasks/run/deployment.md
The queue-name label will be propagated from `.metadata.label` to `.spec.template.metadata.labels` in the admission webhook controller: https://github.com/kubernetes-sigs/kueue/blob/f9cb97fdb04309358e2a042478dab2fb4ccb8d3d/pkg/controller/jobs/deployment/deployment_webhook.go#L86-L89
So, I refined the deployment queue-name label description to align with other Pods' dependent workload documentations:
- StatefulSet queue-name label section: https://kueue.sigs.k8s.io/docs/tasks/run/statefulset/#a-queue-selection
- LeaderworkerSet queue-name label section: https://kueue.sigs.k8s.io/docs/tasks/run/leaderworkerset/
Fixes #
```release-note
NONE
```
=> Doc: Fix the outdated deployment queue-name label section

pkg/controller/jobframework/integrationmanager.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobs/job/job_webhook_test.go, test/e2e/singlecluster/e2e_test.go, test/util/util.go
/kind bug
Fixes #5235
```release-note
Fix the bug which prevented running Jobs (with queue-name label) owned by other Jobs for which Kueue does not 
have the necessary RBAC permissions (for example kserve or CronJob).
```
=> Fix Kueue ownership traversal resulting in permission errors

pkg/controller/jobframework/integrationmanager.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobs/job/job_webhook_test.go, test/e2e/singlecluster/e2e_test.go, test/util/util.go
Cherry pick of #5252 on release-0.11.
#5252: Fix Kueue ownership traversal resulting in permission errors
```release-note
Fix the bug which prevented running Jobs (with queue-name label) owned by other Jobs for which Kueue does not 
have the necessary RBAC permissions (for example kserve or CronJob).
```
=> Automated cherry pick of #5252: Fix Kueue ownership traversal resulting in permission errors

keps/973-workload-priority/README.md
/kind cleanup
Since https://github.com/kubernetes-sigs/kueue/issues/5004, we allow them to replace the PriorityClassName with a non-empty name in Workloads.
Fixes #
```release-note
NONE
```
=> KEP-973: Mutable PriorityClassName for suspended Workloads

test/e2e/singlecluster/e2e_test.go
/kind cleanup
Follow-up of #5241.
See: https://github.com/kubernetes-sigs/kueue/pull/5241#pullrequestreview-2844247378
Relates to #5241
```release-note
NONE
```
=> Follow-up: Clean up tests for updating the Workload priority label.

pkg/cache/cache.go, pkg/cache/clusterqueue.go
/kind cleanup
Preparatory PR for: https://github.com/kubernetes-sigs/kueue/pull/5276 and follow up to https://github.com/kubernetes-sigs/kueue/pull/5052, which replaced the use of addWorkload to addOrUpdateWorkload, which does not throw if already exists.
Fixes #
```release-note
NONE
```
=> Cleanup addOrUpdateWorkload in cache

hack/push-chart.sh
/kind bug
Fixes #
This PR reverts the generic approach attempted in https://github.com/kubernetes-sigs/kueue/pull/5280
This is not working because the "grep" on busybox does not recognize "-P".
```
https://storage.googleapis.com/kubernetes-ci-logs/logs/post-kueue-push-images/1924436373746487296/artifacts/build.log
[9:02](https://kubernetes.slack.com/archives/D05KY8M2MRQ/p1747767751405919)
Installed plugin: unittest
EXTRA_TAG="v0.12.0-rc.1" GIT_TAG="v20250519-v0.12.0-rc.1" IMAGE_REGISTRY="us-central1-docker.pkg.dev/k8s-staging-images/kueue" HELM_CHART_REPO="us-central1-docker.pkg.dev/k8s-staging-images/kueue/charts" IMAGE_REPO="us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue" HELM="/workspace/bin/helm" YQ="/workspace/bin/yq" ./hack/push-chart.sh
grep: unrecognized option: P …
```
=> Fix tagging for helm charts

test/e2e/customconfigs/waitforpodsready_test.go
/kind flake
Move curl pod management to test cases to ensure its availability and resolve test flakiness
Fixes #5302
```release-note
NONE
```
=> test: waitforpodsready e2e move curl-pod to test cases

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/cache/fair_sharing_test.go, pkg/cache/resource_test.go, pkg/cache/snapshot_test.go, pkg/controller/core/admissioncheck_controller.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/resourceflavor_controller.go, pkg/controller/jobframework/base_webhook_test.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/preemption/preemption_test.go, pkg/scheduler/scheduler_test.go
/kind cleanup
Follow up to https://github.com/kubernetes-sigs/kueue/pull/5324
Fixes #
```release-note
NONE
```
=> Use logger inside cache 2.0

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go
/kind bug
This PR fixes assumedUsage calculation in TAS
Before this change, for each domain present in podset assignment algorithm was adding total requested resources for the whole podset instead of resources actually used by the pods assigned to that domain. This resulted in some workloads with more than 1 podset not fitting in the topology which should have enough resources to accomodate that workload.
This PR fixes that by replacing `TotalRequests` with `SinglePodRequests` scaled by the number of pods actually assigned to that domain.
Fixes #
```release-note
TAS: fix accounting of TAS usage for workloads with multiple PodSets. This bug could prevent admitting workloads which otherwise could fit.
```
=> Fix assumedUsage calculation in TAS

pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, test/integration/singlecluster/tas/tas_test.go
/kind bug
To avoid admitting TAS workloads incorrectly just after restart of Kueue.
This issue was reported in the PRs which attempted to fix it directly: https://github.com/kubernetes-sigs/kueue/pull/5221 and https://github.com/kubernetes-sigs/kueue/pull/5104.
Fixes #
Experiment running the new tests in a loop: https://github.com/kubernetes-sigs/kueue/pull/5305 (200 x 2 Its)
```release-note
Fix the bug where TAS workloads may be admitted after restart of the Kueue controller.
```
=> TAS: account for TAS usage after reboot

cmd/kueueviz/frontend/src/LocalQueueDetail.jsx, cmd/kueueviz/frontend/src/WorkloadDetail.jsx, cmd/kueueviz/frontend/src/Workloads.jsx, cmd/kueueviz/frontend/src/WorkloadsList.jsx
/kind bug
kueueViz is displaying "Unknown" for workload status. This is sloppy and confusing.
It turns out that kueueViz was trying to find a non existent value in the workload API. It was trying to display workload.status.state which does not exist.
Removing this column.
Fixes #5139 
```release-note
NONE
```
=> drop workload state from kueueviz as its always unknown

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/cache/resource_test.go, pkg/cache/snapshot_test.go, pkg/controller/core/admissioncheck_controller.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/clusterqueue_controller_test.go, pkg/controller/core/resourceflavor_controller.go, pkg/controller/core/workload_controller.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/jobset/jobset_webhook_test.go, pkg/controller/jobs/mpijob/mpijob_webhook_test.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/preemption/preemption_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
/kind cleanup
Fixes #
Cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/5324 and https://github.com/kubernetes-sigs/kueue/pull/5326
This is preparatory cherry-pick before cherry-pick for https://github.com/kubernetes-sigs/kueue/pull/5276
```release-note
NONE
```
=> Use logger in cache (cherry-pick to release-0.10)

pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/tas/resource_flavor.go, test/integration/tas/tas_test.go
/kind bug
Fixes #
This is cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/5276 on top of the logger cherry-pick https://github.com/kubernetes-sigs/kueue/pull/5333
```release-note
Fix the bug where TAS workloads may be admitted after restart of the Kueue controller.
```
=> TAS: account for TAS usage after reboot (cherry-pick to 0.10)

pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, test/integration/singlecluster/tas/tas_test.go
/kind bug
Fixes #
This is cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/5276 on top of the logger cherry-pick https://github.com/kubernetes-sigs/kueue/pull/5329
```release-note
TAS: Fix the bug where TAS workloads may be admitted after restart of the Kueue controller.
```
=> TAS: account for TAS usage after reboot  (cherry-pick to 0.11)

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_test.go, pkg/cache/tas_cache.go, pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/scheduler/scheduler_test.go
/kind bug
/kind cleanup
Cleanup motivated by the work on #5276
I think this PR greatly simplifies the reasoning about the TAS cache because:
1. When initializing the tasCache it does not rely on the order of adding ResourceFlavor or Topology
2. Eliminates the need for throwing Listing of ResourceFlavors from event handlers ([example](https://github.com/kubernetes-sigs/kueue/pull/5309/files#diff-2335ebd2fdb62e9d56dbd44087a20a915598a260557bd0afd92681e5529f47afL141-L143))
3. Removes the two-level write access to TAS cache, via cache [example](https://github.com/kubernetes-sigs/kueue/pull/5309/files) or tasCache [example](https://github.com/kubernetes-sigs/kueue/pull/5309/files#diff-7f688e0706bb6b6775d35b320ee0d496f92ed367d87cb845979731898ea9d1eaL177), greatly simplifying the flow
Because of …
=> TAS: refactor the tasCache access and fix initialization issues

charts/kueue/templates/webhook/manifests.yaml, hack/processing-plan.yaml
Based on the documentation https://kueue.sigs.k8s.io/docs/reference/kueue-config.v1beta1/ :
> ManagedJobsNamespaceSelector provides a namespace-based mechanism to exempt jobs from management by Kueue.
But currently we still catch all jobs creation without respecting this namespace selector.
Fixes #5260
```release-note
Fix missing namespace selector on webhook manifest. ManagedJobsNamespaceSelector option was only applied to pods/deployment/statefulset, now it is applied to all kind of jobs.
Kube-system and Kueue release namespaces are still not excluded automatically by default.
```
=> Fix missing namespace selector on webhook manifest

Makefile-test.mk
/kind cleanup
To allow to observe potential panics during parallelised integration tests.
Fixes #5315
```release-note
NONE
```
=> Allow to observe panics during integration tests

Makefile, README.md, SECURITY-INSIGHTS.yaml, charts/kueue/Chart.yaml, charts/kueue/README.md, site/hugo.toml
Cherry pick of #5362 on website.
#5362: Update main after v0.11.5
```release-note
NONE
```
=> Automated cherry pick of #5362: Update main after v0.11.5

test/e2e/singlecluster/e2e_test.go
/kind bug
/kind flake
Remove CronJob in AfterEach instead of DeferCleanup.
Fixes #5350
DeferCleanup running after all AfterEach blocks. We should delete CronJobs before LocalQueue and ClusterQueue.
```release-note
NONE
```
=> Remove CronJob in AfterEach instead of DeferCleanup.

.github/dependabot.yml, Makefile-test.mk, hack/cypress/Dockerfile, hack/e2e-kueueviz-backend.sh
/kind cleanup
Configure Dependabot to automatically bump the Cypress image tag
Fixes #
```release-note
NONE
```
=> Configure Dependabot to automatically bump the Cypress image tag

Makefile
Cherry pick of #5278 on release-0.11.
#5278: Fix restoring of the image in artifacts goal
```release-note
NONE
```
=> Automated cherry pick of #5278: Fix restoring of the image in artifacts goal

test/integration/singlecluster/tas/tas_test.go
/kind cleanup
Reword comments in tas_test.
```release-note
NONE
```
=> [Cleanup] Reword tas_test comments

test/integration/singlecluster/tas/tas_test.go
/kind cleanup
Strange behaviour was observed during the flaky test.
Wl1 was recreated with another namespace and disappeared without being deleted or preempted.
It appears that we forgot to cleanup namespaces after each test node.
Fixes #5395
```release-note
NONE
```
=> [Cleanup] Flaky tas test preemption cleanup

pkg/controller/jobframework/base_webhook.go, pkg/controller/jobframework/validation.go, pkg/controller/jobframework/validation_test.go, pkg/controller/jobs/job/job_webhook.go, pkg/controller/jobs/jobset/jobset_webhook.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go, pkg/controller/jobs/mpijob/mpijob_webhook.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook.go
/kind bug
The localQueueDefaulting feature enables cluster admins to configure namespaces with default localQueues, thus ensuring that all instances of Kinds that are being managed by Kueue that are created in such a namespace will have
`kueue.x-k8s.io/queue-name` labels.  However, nothing prevented a user from editing a job after it was created
to remove the label.  Without such enforcement, a user can easily bypass the admin-created mechanism for quota enforcement by editing a job to remove its local queue label and setting suspend to false.
This PR extends the validation logic for queue name updates to prevent them from being removed in namespaces with default local queues when localQueueDefaulting is enabled. 
Fixes #
```release-note
Fix a bug that would allow a user to bypass …
```
=> Prevent removal of queue-name label in namespaces with default localqueue

pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/snapshot.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/scheduler/scheduler_test.go
Cherry pick of #5426 on release-0.12.
#5426: TAS: Fix using reservation is the second flavor is Provisioning
```release-note
TAS: Fix bug which prevented admitting any workloads if the first resource flavor is reservation, and the fallback is using ProvisioningRequest.
```
=> Automated cherry pick of #5426: TAS: Fix using reservation is the second flavor is Provisioning

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go
/kind bug
In the current TAS domain sorting algorithm with LeastFreeCapacityAlgorihtm, it violates the domain level ordering.
However, we should keep the level ordering even when the algorithm is LeastFreeCapacityAlgorithm.
For example, if the cluster has a flat host domain in the following, the LeastFreeCapacityAlgorihtm selects `x3`.
However, the expectation is `x1`.
```
x1 (free cpu=1) x2 (free cpu=2) x3 (free cpu=1)
```
Fixes #
Before this PR, `sortedDomains()` sorts in the following steps:
1. The sort func (`slices.SortFunc`) sorts in descending order
```
x2 (free cpu=2) x1 (free cpu=1) x3 (free cpu=1)
```
2. The reverse func (`slices.Reverse`) just reverses those, ignoring level ordering:
```
x3 (free cpu=1) x1 (free cpu=1) x2 (free cpu=2)
```
Since this PR, `sortedDomains()` sorts …
=> TAS: Keep level ordering even when algorithm is LeastFreeCapacityAlgorithm

apis/config/v1beta1/defaults.go, apis/config/v1beta1/defaults_test.go, pkg/config/config_test.go, pkg/util/cert/cert.go
The cert-manager rotator previously used a hardcoded default certificate directory (/tmp/k8s-webhook-server/serving-certs), ignoring the configured webhook.certDir value. This commit updates the logic to use the configured value if provided, falling back to the default only when necessary.
/kind bug
Fixes #5430
No
```release-note
Fix the bug that the webhook certificate setting under `controllerManager.webhook.certDir` was ignored by the internal cert manager, effectively always defaulting to /tmp/k8s-webhook-server/serving-certs.
```
=> Respect configured webhook.certDir in cert-manager rotator

site/content/en/docs/admission-check-controllers/provisioning.md
To clarify the list of fields considering PodSets when podSetMergePolicy: IndenticalWorkloadSchedulingRequirements is used.
```release-note
NONE
```
=> Cleanup and extend docs on podSetMergePolicy

site/content/en/docs/installation/_index.md
There are no below FGs in the installation guides.
- HierarchicalCohort
- TASFailedNodeReplacement
- TASProfileMostFreeCapacity
- TASProfileLeastFreeCapacity
- TASProfileMixed
- AdmissionFairSharing
However, I did not add AdmissionFairSharing in this PR since https://github.com/kubernetes-sigs/kueue/pull/5476 tries to introduce it to the list.
Fixes #
```release-note
NONE
```
=> Doc: Add missing FGs to installation guide

site/content/en/docs/tasks/manage/setup_object_retention_policy.md
Add a documentation page for the object retention functionality
Fixes #5261 
```release-note
NONE
```
=> docs: add object retention page

test/integration/singlecluster/tas/tas_test.go
/kind flake
As we see in this [log](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5461/pull-kueue-test-integration-baseline-main/1930264942032719872/build-log.txt).
Workload `wl1` entry from test `Nodes are created before test with the hostname being the lowest level  should evict workload when multiple assigned nodes fail` outlives the test in the scheduler's cache.
That's because it was re-queued for second pass.
Thus it is still visible in test `Preemption is enabled within ClusterQueue  should preempt the low and mid priority workloads to fit the high-priority workload` in result it is considered as possible preemption for `wl2` causing preemption failure
```
2025-06-04T14:11:53.966698632Z	
ERROR	
scheduler	
scheduler/scheduler.go:271	Failed to …
```
=> [Flaky] TAS tests unique cq names

Makefile, hack/helm-chart-package.sh
Cherry pick of #5521 on release-0.11.
#5521: Remove redundant EXTRA_TAG variable from helm-chart-package.sh.
```release-note
NONE
```
=> Automated cherry pick of #5521: Remove redundant EXTRA_TAG variable from helm-chart-package.sh.

Makefile, cloudbuild.yaml
Cherry pick of #5543 on release-0.11.
#5543: Remove IMAGE_EXTRA_TAG and use branch name instead.
```release-note
NONE
```
=> Automated cherry pick of #5543: Remove IMAGE_EXTRA_TAG and use branch name instead.

Makefile-test.mk, hack/e2e-kueueviz-local.sh
/kind cleanup
Remove redundant CYPRESS_IMAGE_NAME variable.
Fixes #
```release-note
NONE
```
=> Remove redundant CYPRESS_IMAGE_NAME variable.

Makefile-deps.mk, Makefile-test.mk
Cherry pick of #5386 on release-0.11.
#5386: Cleanup Makefiles.
```release-note
NONE
```
=> Automated cherry pick of #5386: Cleanup Makefiles.

Makefile, cloudbuild.yaml, hack/helm-chart-package.sh
Cherry pick of #5537 on release-0.11.
#5537: Cleanup Makefile.
```release-note
NONE
```
=> Automated cherry pick of #5537: Cleanup Makefile.

test/integration/singlecluster/tas/tas_test.go
/kind bug
/kind flake
The flakiness is due to the fact that upon a single-node failure, we replace the broken node. In this test we want to check if when multiple nodes fail, we will evict the workload. The problem is that, if there is a delay between the two delete events, the replacement mechanism might kick in and find a healthy replacement which would lead to failure of this test. To prevent that from happening I would like to restrict the workload (using nodeSelector) to a single block that contains in this setup only two nodes x1 and x2.
Fixes #5559
```release-note
NONE
```
=> [Deflake] TAS integration test "should evict workload when multiple assigned nodes are deleted"

pkg/util/testing/wrappers.go, pkg/workload/workload.go, pkg/workload/workload_test.go
/kind bug
To avoid unnecessary second passes by scheduler. These were sometimes spot when running https://github.com/kubernetes-sigs/kueue/issues/5511. 
Fixes #
```release-note
TAS: fix the bug which would trigger unnecessary second pass scheduling for nodeToReplace
in the following scenarios: 
1. Finished workload
2. Evicted workload
3. node to replace is not present in the workload's TopologyAssignment domains
```
=> Fix the NeedsSecondPass check

pkg/queue/manager.go, pkg/queue/manager_test.go, pkg/queue/second_pass_queue.go, test/integration/singlecluster/tas/tas_test.go
/kind bug
/kind flake 
Fixes #5511
The issue is that the forgetWorkload called on the secondPassQueue would hit the void while the workload awaits for 1s [here](https://github.com/kubernetes-sigs/kueue/blob/d2f9f2efcd066f007930e9f04fe7629ed8983a0a/pkg/queue/manager.go#L793). Now we prequeue such a workload, and if forgetWorkload is called in the meanwhile, then "enqueue" is forgotten either.
Adding a reliably reproducing integration test is tricky. Running the test https://github.com/kubernetes-sigs/kueue/pull/5513 in a loop reproduces in consistently, but requires multiple many repeats.
To prove the fix works:
- I ran the CI build, with commit https://github.com/kubernetes-sigs/kueue/pull/5587/commits/418b65e2b5fe12fed7c5125cccad3be629d9cb3a, and it passed [here]( …
=> Fix second pass entries outliving the workload delete

pkg/queue/manager.go, pkg/queue/manager_test.go, pkg/queue/second_pass_queue.go, test/integration/singlecluster/tas/tas_test.go
Cherry pick of #5587 on release-0.12.
#5587: Fix second pass entries outliving the workload delete
```release-note
TAS: fix the scenario when deleted workload still lives in the cache.
```
=> Automated cherry pick of #5587: Fix second pass entries outliving the workload delete

pkg/controller/jobframework/tas_validation.go, pkg/controller/jobs/job/job_webhook_test.go
/kind feature
https://github.com/kubernetes-sigs/kueue/pull/5353 introduces two-level scheduling, however it does not add validation. This PR is a preparation PR that introduces validation for annotations `kueue.x-k8s.io/podset-slice-required-topology` and `kueue.x-k8s.io/podset-slice-size`.
Related to https://github.com/kubernetes-sigs/kueue/issues/5439
For better readability I've added tests only for Job. I see that we repeat the same tests for each (or at least most of) Job type. That would be copy-paste, so I've decided to present tests for Job for now and once I get an approval I'll add the rest of the tests or do it in next PR.
I think we should also validate that the slice size is not greater than the number of pods in PodSet, because if someone sets it to a huge number algorithm …
=> Validate slice annotations

test/e2e/singlecluster/e2e_test.go
Cherry pick of #5378 on release-0.11.
#5378: Remove CronJob in AfterEach instead of DeferCleanup.
Fixes #5350
```release-note
NONE
```
=> Automated cherry pick of #5378: Remove CronJob in AfterEach instead of DeferCleanup.

pkg/controller/core/workload_controller.go, pkg/queue/manager.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/util/constants.go
Cherry pick of #5625 on release-0.11.
#5625: Don’t add the Workload to the Queues Manager if it is deactivated.
```release-note
Fix the bug that Kueue, upon startup, would incorrectly admit and then immediately deactivate
already deactivated Workloads.
This bug also prevented the ObjectRetentionPolicies feature from deleting Workloads
that were deactivated by Kueue before the feature was enabled.
```
=> Automated cherry pick of #5625: Don’t add the Workload to the Queues Manager if it is deactivated.

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go, pkg/controller/jobframework/tas.go, pkg/controller/jobframework/tas_validation.go, test/e2e/tas/jobset_test.go
/kind feature
Currently Topology-Aware Scheduling considers the whole PodSet as a single unit for which we look for a matching domain. However, there are use-cases in which we would like to allow user to define a sub-podset topology and two-level topologies (schedule the whole podset in one higher-level topology and schedule each subset of the podset in other, lower-level topology).
An example is a JobSet in which user can define topology for all Jobs resulting from a single ReplicatedJob. We want to allow user to define topology for each such Job and possibly co-locate all such Jobs in higher-level topology.
This PR introduces two-level scheduling allowing user to define required topology for PodSet chunks and required or preferred topology for the whole PodSet. We are also allowing user …
=> Two level TAS scheduling / PodSet chunk topology

Makefile, charts/kueue/README.md, charts/kueue/templates/manager/manager.yaml, charts/kueue/tests/manager_test.yaml, charts/kueue/values.yaml
/kind feature
On some deployments Kueue is a critical Pod, and to reflect that users would like to set the priority as `system-cluster-critical`. This PR allows setting the Pod priority from the Helm chart by exposing the `priorityClassName` property
Fixes #5614
```release-note
Allow setting the controller-manager's Pod `PriorityClassName` from the Helm chart
```
=> Allow setting the controller-manager PriorityClassName in helm

Makefile, charts/kueue/README.md, charts/kueue/templates/manager/manager.yaml, charts/kueue/tests/manager_test.yaml, charts/kueue/values.yaml
Cherry pick of #5631 on release-0.12.
#5631: Allow setting the controller-manager PriorityClassName in helm
```release-note
Allow setting the controller-manager's Pod `PriorityClassName` from the Helm chart
```
=> Automated cherry pick of #5631: Allow setting the controller-manager PriorityClassName in helm

site/content/en/docs/concepts/topology_aware_scheduling.md
Documentation paragraph for TAS failed node replacement.
Fixes #
```release-note
NONE
```
=> Documentation describing the TAS failed node replacement 

test/integration/singlecluster/scheduler/scheduler_test.go
/kind bug
/kind flake
Currently, we check the Admission status against `nil`, which is not correct. While the initial status may be `nil`, we should compare it with the status _after_ Admission.
Fixes #5588
```release-note
NONE
```
=> Fix "Should admit workloads with admission checks" test.

test/integration/singlecluster/scheduler/scheduler_test.go
Cherry pick of #5671 on release-0.11.
#5671: Fix "Should admit workloads with admission checks" test.
```release-note
NONE
```
=> Automated cherry pick of #5671: Fix "Should admit workloads with admission checks" test.

pkg/controller/jobframework/reconciler.go
/kind cleanup
A simple optimization: only log a warning if the job has multiple workloads.
Fixes #
```release-note
NONE
```
=> refactor: only log warning when job has multiple workloads

test/e2e/customconfigs/waitforpodsready_test.go
/kind bug
/kind flake
Fix customconfigs WaitForPodsReady E2E Tests.
Fixes #5358
Originally, we updated the Kueue Configuration after creating the `ResourceFlavor`, `ClusterQueue`, and `LocalQueue` resources in `BeforeEach` block. However, this can lead to race conditions – especially when resources are being deleted and created, and the controller manager is restarted during that time. This may interrupt operations.
To avoid this, we should update the Kueue Configuration first, and only then create the resources.
Since `updateKueueConfiguration` is a slow operation, I’ve split each configuration update into a separate Describe block and moved the logic into the BeforeAll block. This approach will make it easier to extend and add new test cases in the future. …
=> Fix customconfigs WaitForPodsReady E2E Tests.

pkg/controller/jobframework/tas.go, pkg/controller/jobs/appwrapper/appwrapper_controller.go, pkg/controller/jobs/job/job_controller.go, pkg/controller/jobs/jobset/jobset_controller.go, pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/controller/jobs/mpijob/mpijob_controller.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/raycluster/raycluster_controller.go, pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
This is a follow up after https://github.com/kubernetes-sigs/kueue/pull/5353. In one of the comments it has been spotted that we are silently ignoring errors from TAS request builder. This PR fixes the issue by refactoring builder and propagating errors.
Related to: https://github.com/kubernetes-sigs/kueue/issues/5439
```release-note
NONE
```
=> Propagate error from TAS request builder

hack/e2e-common.sh, hack/e2e-kueueviz-backend.sh, hack/e2e-kueueviz-local.sh, test/e2e/certmanager/metrics_test.go, test/e2e/certmanager/suite_test.go, test/e2e/customconfigs/suite_test.go, test/e2e/customconfigs/waitforpodsready_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/multikueue/suite_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/suite_test.go, test/e2e/singlecluster/visibility_test.go, test/util/e2e.go
/kind cleanup
Fixes #4558 
e2e run with the customize namespace-> https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/5647/pull-kueue-test-e2e-main-1-33/1934069238855634944
```release-note
NONE
```
=> Allow user opt-in namespace for running e2e testsuite

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler_test.go
/kind cleanup
We use the simulation preemption results for more accurate flavor assignment in the case when `val <= rQuota.Nominal || mayReclaimInHierarchy`. This allows upgrading to a flavor where preemption is possible.
Contributes to #4135
```release-note
More accurate flavor assignment by using the results of preemption simulation in more cases
```
=> FlavorAssigner - Use Preemption Simulation Results in More Cases

pkg/controller/jobs/job/job_multikueue_adapter.go, test/integration/multikueue/jobs_test.go
/kind bug
Fixes an issue where the local Job status was not updated to reflect the final state
of the remote Job when using MultiKueue with the default (disabled) 
MultiKueueBatchJobWithManagedBy feature gate. The update was previously 
skipped if the local Job remained suspended, contrary to documented behavior.
Fixes #5613
```release-note
MultiKueue: Fix a bug that batch/v1 Job final state is not synced from Workload cluster to Management cluster when disabling the `MultiKueueBatchJobWithManagedBy` feature gate.
```
=> Ensure Job status is updated after remote completion

README.md
/kind cleanup
To make the links point to the report for the latest release.
Currently the links point to report for Kueue v0.3.1 from 2 years back: 
using the new links:
Surprisingly when using "refresh report" it automatically redirects to report for sigs.k8s.io/kueue.
```release-note
NONE
```
=> Fix the links for GoReport to point to the latest release

pkg/cache/tas_flavor_snapshot.go
/kind cleanup
This PR removes a duplication between two functions: `findBestFitDomain` and `findBestFitDomainForSlices`. This improvement was suggested in a comment here: https://github.com/kubernetes-sigs/kueue/pull/5353/files/4bfd8844c197791804491904ff032376d2f83975#r2142313188
Related to: https://github.com/kubernetes-sigs/kueue/issues/5439
```release-note
NONE
```
=> Remove duplication of findBestFitDomain function

pkg/util/testing/wrappers.go, pkg/util/testingjobs/jaxjob/wrappers.go, pkg/util/testingjobs/leaderworkerset/wrappers.go, pkg/util/testingjobs/mpijob/wrappers_mpijob.go, pkg/util/testingjobs/paddlejob/wrappers.go, pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go, pkg/util/testingjobs/tfjob/wrappers_tfjob.go, pkg/util/testingjobs/xgboostjob/wrappers.go
/kind cleanup
I cleaned up wrappers in the following:
- Fixed incorrect function names in comments
- Use the same receiver names for the same wrapper.
- Remove redundant receiver pointer copies.
Fixes #
```release-note
NONE
```
=> Clean up wrappers

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler_test.go
Cherry pick of #5698 on release-0.12.
#5698: Improve accuracy of flavor assignment using preemption simulation in more cases
```release-note
Use simulation of preemption for more accurate flavor assignment. 
In particular, the previous heuristic would wrongly state that preemption
in a flavor was possible even if no preemption candidates could be found. 
Additionally, in scenarios when preemption while borrowing is enabled,
the flavor in which reclaim is possible is preferred over flavor where 
priority-based preemption is required. This is consistent with prioritizing 
flavors when preemption without borrowing is used.
```
=> Automated cherry pick of #5698: Improve accuracy of flavor assignment using preemption simulation in more cases

site/content/en/docs/concepts/multikueue.md
We have MultiKueue-supported job documentation in the tasks and concepts page.
And the concepts page one is a bit outdated, like a lack of supported Jobs list, and outdated limitations.
So, I removed those from the concept page and just added links to the tasks page.
Fixes #
```release-note
NONE
```
=> Doc: Single Truth of MultiKueue supported Jobs documentations

CHANGELOG/CHANGELOG-0.11.md
/kind cleanup
Part of #5617
```release-note
NONE
```
=> Update CHANGELOG after v0.11.7

charts/kueue/README.md, charts/kueue/templates/webhook/webhook.yaml, charts/kueue/values.yaml, hack/update-helm.sh
Cherry pick of #5063 on release-0.11.
#5063: Mutating webhook with reinvocation policy
```release-note
Helm: Add an option to configure Kueue's mutation webhook with "reinvocationPolicy"
```
=> Automated cherry pick of #5063: Mutating webhook with reinvocation policy

pkg/controller/core/resourceflavor_controller.go
/kind bug
If the resourceFlavor resource does not exist, we should return err = nil to prevent it from being re-queued into the workqueue.
Fixes #
```release-note
NONE
```
=> fix: ignore not-found errors when updating ResourceFlavor finalizers

pkg/queue/manager.go
/kind cleanup
The redundant `m.secondPassQueue.takeAllReady()...)` calling brings us additional computation costs.
Fixes #
```release-note
NONE
```
=> chore: Fix redundant workloads initializations in queue manager

pkg/cache/tas_cache_test.go, pkg/cache/tas_flavor_snapshot.go
/kind bug
Fixes #5450 
Took the same logic as here: https://github.com/kubernetes-sigs/kueue/pull/5450 and rebased, added new UTs and adjusted old ones
```release-note
Bug fix for TAS LeastFreeCapacityFit
```
=> Fix TAS LeastFreeCapacityFit for fit where nodes that are not the smallest one can accommodate Workload

pkg/controller/tas/node_failure_controller.go
/kind bug
As described in https://github.com/kubernetes-sigs/controller-runtime/blob/4c2e9cec2954e6d5a9522c65b2e22f24acb750b5/pkg/builder/controller.go#L247-L257, the controller name must be a Prometheus compatible one.
Fixes #
```release-note
TAS: Fix a bug for the incompatible NodeFailureController name with Prometheus
```
=> Fix a bug for tas_node_failure_controller name

pkg/controller/admissionchecks/multikueue/admissioncheck.go, pkg/controller/admissionchecks/multikueue/multikueuecluster.go, pkg/controller/admissionchecks/provisioning/admissioncheck_reconciler.go, pkg/controller/core/admissioncheck_controller.go, pkg/controller/core/cohort_controller.go, pkg/controller/core/workload_controller.go
/kind bug
follow-up: https://github.com/kubernetes-sigs/kueue/pull/5786#issuecomment-3012681011
Fixes #
```release-note
NONE
```
=> refactor: improve error handling with client.IgnoreNotFound in controllers

pkg/controller/core/admissioncheck_controller.go, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/cohort_controller.go, pkg/controller/core/localqueue_controller.go, pkg/controller/core/resourceflavor_controller.go, pkg/controller/core/workload_controller.go, pkg/controller/tas/node_failure_controller.go, pkg/controller/tas/resource_flavor.go, pkg/controller/tas/topology_controller.go, pkg/controller/tas/topology_ungater.go
/kind bug
The GroupKindConcurrency in the Kueue Config must be propagated to each controller in the following:
https://github.com/kubernetes-sigs/controller-runtime/blob/4c2e9cec2954e6d5a9522c65b2e22f24acb750b5/pkg/config/controller.go#L35-L45
However, some controllers use the `WatchesRawSource` instead of `For` for registrations. So, in the case of `WatchesRawSource`, we need to manually specify the concurrency propagated from Kueue Config.
Fixes #
Before this PR:
```shell
2025-06-30T23:21:36.198723+09:00      INFO    controller/controller.go:195    Starting workers        {"controller": "localqueue_controller", "worker count": 1}
```
After this PR:
```shell
2025-06-30T23:19:29.05779+09:00       INFO    controller/controller.go:195    Starting workers        {"controller": …
```
=> Fix a bug for the non propagated controller concurrency

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go
/kind bug
Fixes #
```release-note
TAS: Fix the bug when Kueue crashes if the preemption target, due to quota, is using a node which is already deleted.
```
=> TAS: fix Kueue crashing when quota-based preemption is targeting a workload using deleted Node

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go
Cherry pick of #5833 on release-0.12.
#5833: TAS: fix Kueue crashing when quota-based preemption is targeting a workload using deleted Node
```release-note
TAS: Fix the bug when Kueue crashes if the preemption target, due to quota, is using a node which is already deleted.
```
=> Automated cherry pick of #5833: TAS: fix Kueue crashing when quota-based preemption is targeting a workload using deleted Node

pkg/controller/tas/node_failure_controller.go
/kind bug
Before this PR, if leader election is enabled, the node failure controller unexpectedly start the reconciliation even if it is not leader replica. 
Fixes #
```release-note
TAS: Fix a bug that the tas-node-failure-controller unexpectedly is started under the HA mode even though the replica is not the leader.
```
=> TAS: Support the LeaderElection for NodeFailure controller

hack/e2e-common.sh, test/e2e/certmanager/metrics_test.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/customconfigs/objectretentionpolicies_test.go, test/e2e/customconfigs/waitforpodsready_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/appwrapper_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jaxjob_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/pytorchjob_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/singlecluster/visibility_test.go, test/e2e/tas/appwrapper_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/leaderworkerset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go, test/e2e/tas/statefulset_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/util/e2e.go
/kind flake
Remove digest from the agnhost images in e2e tests so that they are not re-pulled.
Fixes #5639
Fixes #5640
Agnhost image is already being preloaded in the hack/e2e-common.sh:
```bash
export E2E_TEST_AGNHOST_IMAGE_OLD=registry.k8s.io/e2e-test-images/agnhost:2.52@sha256:b173c7d0ffe3d805d49f4dfe48375169b7b8d2e1feb81783efd61eb9d08042e6
E2E_TEST_AGNHOST_IMAGE_OLD_WITHOUT_SHA=${E2E_TEST_AGNHOST_IMAGE_OLD%%@*}
export E2E_TEST_AGNHOST_IMAGE=registry.k8s.io/e2e-test-images/agnhost:2.53@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85
E2E_TEST_AGNHOST_IMAGE_WITHOUT_SHA=${E2E_TEST_AGNHOST_IMAGE%%@*}
```
However, due to the preloaded image being loaded to the containerd without the sha256 digest, and the tests strictly  requiring the use of an …
=> fix: use agnhost images preloaded to the containerd in tests

test/integration/singlecluster/scheduler/preemption_test.go
/kind bug
Cleanup needed for integration tests
Fixes #5864
```release-note
NONE
```
=> Add missing cleanups to preemption integration tests

hack/e2e-common.sh, test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/appwrapper_test.go, test/e2e/singlecluster/deployment_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/e2e/singlecluster/tas_test.go, test/e2e/singlecluster/visibility_test.go, test/e2e/tas/appwrapper_test.go, test/e2e/tas/job_test.go, test/e2e/tas/jobset_test.go, test/e2e/tas/leaderworkerset_test.go, test/e2e/tas/mpijob_test.go, test/e2e/tas/pod_group_test.go, test/e2e/tas/pytorch_test.go, test/e2e/tas/statefulset_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/util/e2e.go
Cherry pick of #5780 on release 0.11.
#5780: fix: use agnhost images preloaded to the containerd in tests
```release-note
NONE
```
=> Automated cherry pick of #5780: fix: use agnhost images preloaded to the containerd in tests

Makefile, charts/kueue/README.md, charts/kueue/templates/kueueviz/backend-deployment.yaml, charts/kueue/templates/kueueviz/frontend-deployment.yaml, charts/kueue/templates/manager/manager.yaml, charts/kueue/tests/manager_test.yaml, charts/kueue/values.yaml, hack/processing-plan.yaml
Cherry pick of #5820 on release-0.12.
#5820: helm: support for specifying nodeSelector and tolerations for all Kueue components
```release-note
Helm: support for specifying nodeSelector and tolerations for all Kueue components
```
=> Automated cherry pick of #5820: helm: support for specifying nodeSelector and tolerations for all Kueue components

cmd/kueue/main.go, pkg/cache/cache.go, pkg/cache/clusterqueue.go, pkg/cache/clusterqueue_snapshot.go, pkg/cache/snapshot.go, pkg/queue/cluster_queue.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, pkg/util/admissionfairsharing/admission_fair_sharing.go, pkg/workload/workload.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/integration/singlecluster/scheduler/fairsharing/suite_test.go
/kind bug
- Adds `AdmissionScope` field to the interal ClusterQueue representation and CQ Snapshot
- Adds `LocalQueueUsage` field to Workload info to represent the historical LQ's usage in Snapshot
- Populates the `LocalQueueUsage` field if the AFS feature gate is enabled, and the CQ AdmissionMode is set to `UsageBasedAdmissionFairSharing`
- Order candidates for preemption based on the LQ's historical usage
Fixes #5827 
KEP update: https://github.com/kubernetes-sigs/kueue/pull/5817
```release-note
AdmissionFairSharing: preemption candidates are now ordered within ClusterQueue with respect to LQ's usage. 
The ordering of candidates coming from other ClusterQueues is unchanged.
```
=> [AFS] Support preemption based on historical LQ's usage

keps/3589-manage-jobs-selectively/README.md, keps/3589-manage-jobs-selectively/kep.yaml
/kind bug
This PR updates the KEP to reflect that Kueue will reconcile Jobs only in namespaces selected by managedJobsNamespaceSelector, ensuring consistent behavior across all supported integrations, including Pods, Deployments, and StatefulSets.
Fixes # https://github.com/kubernetes-sigs/kueue/issues/5260
Once this change is implemented, namespaces will need to match managedJobsNamespaceSelector (e.g., carry the appropriate label) for their Jobs to be reconciled by Kueue—even if those Jobs specify a queue-name. This makes opting into Kueue management explicit for all integrations, including Jobs, and no longer optional by default.
=> KEP: Reconcile jobs only in opt-in namespaces

pkg/cache/tas_flavor_snapshot.go, pkg/controller/jobframework/tas.go, test/e2e/tas/jobset_test.go
/kind bug
To achieve slice-only TAS, user has to provide slice required topology, slice size and optionally unconstrained annotation. Due to a bug in validation, if user provides slice required topology without required, preferred or unconstrained annotations, Kueue will ignore slice topology and rank-ordering of the pods.
This PR fixes that issue and adds explicit end-to-end test for rank-ordering in slice-only TAS.
I am leaving release notes as `NONE`, because this is a fix to TAS which is targeted at 0.13 anyway.
```release-note
NONE
```
=> Fix slice-only TAS

pkg/workload/workload.go
/kind flake
Fixes flaky test
Fixes #5898
```release-note
NONE
```
=> [flaky test] AFS integration test makes Kueue panic / crash

Makefile
/kind cleanup
To allow calling `IMAGE_BUILD_EXTRA_OPTS="-o type=docker,dest=bin/kueue-image-dev.tar" make image-local-build`. This does not work currently, because then it calls `make image-build PUSH= IMAGE_BUILD_EXTRA_OPTS=-o type=docker,dest=bin/kueue-image-dev.tar`, resulting in 
```
docker buildx build \
...
\
-o \  <- split on the first space
./
```
```release-note
NONE
```
=> Fix passing IMAGE_BUILD_EXTRA_OPTS in Makefile when it contains spaces

pkg/util/testing/context.go, test/util/util.go
/kind cleanup
https://kueue.sigs.k8s.io/docs/contribution_guidelines/testing/#increase-logging-verbosity
This ENV variable was no-op for unit tests
Fixes #
```release-note
NONE
```
=> Allow modification of TEST_LOG_LEVEL for Unit Tests

test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/customconfigs/objectretentionpolicies_test.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/leaderworkerset_test.go, test/e2e/singlecluster/pod_test.go, test/e2e/singlecluster/statefulset_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/controller/jobs/rayjob/rayjob_controller_test.go, test/integration/singlecluster/scheduler/scheduler_test.go, test/integration/singlecluster/scheduler/workload_controller_test.go, test/integration/singlecluster/tas/tas_test.go, test/integration/singlecluster/webhook/jobs/job_webhook_test.go
/kind cleanup
As discussed [here](https://github.com/kubernetes-sigs/kueue/pull/5625#discussion_r2140912742), we should use ShortInterval with Consistently.
Fixes #
```release-note
NONE
```
=> Use ShortInterval with Consistently.

Makefile-test.mk, README.md, hack/multikueue-e2e-test.sh, test/e2e/multikueue/e2e_test.go, test/integration/multikueue/jobs_test.go, test/integration/multikueue/no_gc_test.go, test/integration/multikueue/suite_test.go
/kind cleanup
Remove support for Kubernetes 1.30.
Fixes #
Kubernetes 1.30 End of Life 2025-06-28.
https://kubernetes.io/releases/#release-v1-30
```release-note
NONE
```
=> Remove support for Kubernetes 1.30.

hack/e2e-common.sh, hack/e2e-kueueviz-backend.sh, hack/e2e-kueueviz-local.sh, hack/e2e-test.sh, hack/multikueue-e2e-test.sh
/kind cleanup
Running `make kind-image-build test-e2e E2E_RUN_ONLY_ENV=true` leaves changes in the Kustomize file, which can sometimes be accidentally committed. Since we no longer use these changes, we should revert them after deploying Kueue to prevent this.
Fixes #
```release-note
NONE
```
=> Restore managers image after deploy Kueue.

hack/e2e-common.sh, hack/e2e-test.sh, hack/multikueue-e2e-test.sh
Cherry pick of #5949 on release-0.11.
#5949: Restore managers image after deploy Kueue.
```release-note
NONE
```
=> Automated cherry pick of #5949: Restore managers image after deploy Kueue.

pkg/util/ptr/ptrs.go
/kind cleanup
The PR renames the package `maps` to `ptr` for clarity and consistency. It's confusing that the package containing utility functions for pointers was named `maps`.
This package is imported once, via an alias `utilptr`: 
https://github.com/kubernetes-sigs/kueue/blob/faf1eb382032a19a69d6dbed3c9718b12a625a71/pkg/workload/workload.go#L52
```release-note
NONE
```
=> Change package name from maps to ptr for consistency

pkg/controller/admissionchecks/provisioning/controller_test.go
/kind cleanup
Follow up. Use GVK rather than hard coded strings.
Fixes #5971 
```release-note
NONE
```
=> use group version kind instead of hard coded strings

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go
/kind bug
Prevents localQueue eviction from emitting eviction metric. It would be double counted because ClusterQueue eviction is already counting the eviction.
See context here: https://github.com/kubernetes-sigs/kueue/pull/5923#discussion_r2206658249
```release-note
Emit the Workload event indicating eviction when LocalQueue is stopped
```
=> Emit the Workload event indicating eviction when LocalQueue is stopped

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/scheduler/preemption/preemption.go, pkg/workload/workload.go, test/integration/singlecluster/scheduler/podsready/scheduler_test.go, test/util/util.go
/kind feature
This adds a metric that measures the time between when a workload starts running and preemption. It ultimately measures workload runtime when the workload does not run to completion.
```release-note
Adds a metric that measures the time between workload starting podsReady state and eviction
```
=> add metric for duration between workload podsReady and preemption

apis/config/v1beta1/defaults.go, cmd/kueue/main.go, pkg/config/validation.go, pkg/config/validation_test.go, pkg/controller/jobframework/defaults.go, pkg/controller/jobframework/defaults_test.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobs/pod/pod_webhook.go, pkg/controller/jobs/pod/pod_webhook_test.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go, pkg/features/kube_features.go, site/content/en/docs/installation/_index.md
/kind feature
Graduate ManagedJobNamespaceSelector to GA
Fixes #5983 
```release-note
Graduate ManagedJobNamespaceSelector to GA
```
=> graduate managedJobNamespaceSelector to GA

pkg/controller/jobs/pod/pod_webhook_test.go, site/content/en/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md, site/content/en/docs/tasks/run/plain_pods.md, site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md, site/content/zh-CN/docs/installation/_index.md, site/content/zh-CN/docs/tasks/manage/enforce_job_management/manage_jobs_without_queue_name.md, site/content/zh-CN/docs/tasks/run/plain_pods.md, site/content/zh-CN/docs/tasks/troubleshooting/troubleshooting_pods.md
/kind cleanup
Cleanup after graduation `ManagedJobsNamespaceSelector` feature.
Part of #5983
Follow-up for https://github.com/kubernetes-sigs/kueue/pull/5987.
```release-note
NONE
```
=> Cleanup after graduation ManagedJobsNamespaceSelector feature.

keps/2724-topology-aware-scheduling/README.md
This PR updates Topology-Aware Scheduling KEP introducing LeaderWorkerSet improvements to co-locate leader and workers within a single replica.
Related to https://github.com/kubernetes-sigs/kueue/issues/4531
```release-note
NONE
```
=> [KEP-2724] Add cross-podset TAS scheduling documentation

test/integration/singlecluster/controller/jobs/job/job_controller_test.go
/kind bug
/kind flake
Fix "Shouldn't admit deactivated Workload after manager restart" test.
Fixes #6018
```release-note
NONE
```
=> Fix "Shouldn't admit deactivated Workload after manager restart" test.

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/resource_node.go, test/integration/singlecluster/scheduler/scheduler_test.go
/kind bug
Fixes https://github.com/kubernetes-sigs/kueue/issues/5937
updates cohort tree resources in cache on clusterQueue deletion event
Fixes #5937
```release-note
Fix incorrect workload admission after CQ is deleted in a cohort reducing the amount of available quota. The culprit of the issue was that the cached amount of quota was not updated on CQ deletion.
```
=> Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted

apis/kueue/v1alpha1/topology_types.go, apis/kueue/v1beta1/workload_types.go, apis/kueue/v1beta1/zz_generated.deepcopy.go, charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml, client-go/applyconfiguration/kueue/v1beta1/podsettopologyrequest.go, config/components/crd/bases/kueue.x-k8s.io_workloads.yaml, pkg/controller/jobframework/tas.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_reconciler.go, pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/flavorassigner/podset_groups.go, pkg/util/testing/wrappers.go, site/content/en/docs/reference/kueue.v1beta1.md
/kind feature
To be able to co-locate leaders and workers in LeaderWorkerSet we need to ensure it is possible to find the same flavor for two (or more) PodSets.
This PR introduces `PodSetGroup` as a way to request flavor finding for a group of PodSets.
Details are described in KEP update here: https://github.com/kubernetes-sigs/kueue/pull/5895
Related to https://github.com/kubernetes-sigs/kueue/issues/4531
```release-note
NONE
```
=> Group PodSets together for finding common flavor

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/resource_node.go, test/integration/singlecluster/scheduler/scheduler_test.go
Cherry pick of #5985 on release-0.11.
#5985: Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted
```release-note
Fix incorrect workload admission after CQ is deleted in a cohort reducing the amount of available quota. The culprit of the issue was that the cached amount of quota was not updated on CQ deletion.
```
=> Automated cherry pick of #5985: Incorrect admission due to wrong borrowable resource when a cluster queue in cohort is deleted

pkg/controller/jobs/pod/pod_controller.go
/kind cleanup
This PR contains changes that simplifies `NewPod` instance creation options resulting in less confusing code.
Fixes #
```release-note
NONE
```
=> Simplify Pod configuration options.

pkg/cache/clusterqueue.go, pkg/cache/cohort.go
/kind cleanup
Update updateCohortTreeResources to use updateCohortTreeResourcesIfNoCycle when error silenced 
Fixes #6009 
This change doesn't need new tests. You can validate it works by seeing that existing tests work.
```release-note
NONE
```
=> clean up silenced errors

charts/kueue/templates/prometheus/monitor.yaml, hack/processing-plan.yaml
/kind bug
The Helm chart's ServiceMonitor template incorrectly renders the tlsConfig field as a string instead of a YAML object, causing schema validation failures when deploying with tools that validate against the ServiceMonitor CRD schema.
`ServiceMonitor kueue-controller-manager-metrics-monitor is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/endpoints/0/tlsConfig' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json#/properties/spec/properties/endpoints/items/properties/tlsConfig/type: expected object, but got string`
Instead of using `UPDATE`, I replaced it with `DELETE` and `INSERT_TEXT` following other examples in the file. I then regenerated monitor.yaml with `make …
=> bug fix: ServiceMonitor tlsConfig field

test/e2e/certmanager/suite_test.go, test/e2e/customconfigs/managejobswithoutqueuename_test.go, test/e2e/customconfigs/objectretentionpolicies_test.go, test/e2e/customconfigs/reconcile_test.go, test/e2e/customconfigs/suite_test.go, test/e2e/customconfigs/waitforpodsready_test.go, test/util/e2e.go
/kind cleanup
- Move UpdateKueueConfiguration() to utils.
- Use kind cluster name to save logs.
- Remove unnecessary cleanup for certmanager e2e tests.
Part of #5141 
Follow up for https://github.com/kubernetes-sigs/kueue/pull/5782#discussion_r2218663278.
```release-note
NONE
```
=> Move UpdateKueueConfiguration() to utils.

keps/582-preempt-based-on-flavor-order/README.md, keps/582-preempt-based-on-flavor-order/kep.yaml
Part of #5424 
```release-note
NONE
```
=> [KEP] Update KEP of the flavor fungibility feature

cmd/kueue/main.go, pkg/cache/snapshot.go, pkg/controller/core/core.go, pkg/controller/core/localqueue_controller.go, pkg/queue/afs_entry_penalties.go, pkg/queue/cluster_queue.go, pkg/queue/cluster_queue_test.go, pkg/queue/manager.go, pkg/scheduler/scheduler.go, pkg/util/admissionfairsharing/admission_fair_sharing.go, pkg/util/queue/local_queue.go, pkg/workload/workload.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/integration/singlecluster/scheduler/fairsharing/suite_test.go, test/util/util.go
/kind feature
Add entrance penalty to local queue for admitted workloads.
Fixes #5339 
```release-note
AdmissionFairSharing: Introduce the "entry penalty" for newly admitted workloads in a LQ. 
This mechanism is designed to prevent exploiting a flaw in the previous design which allowed
to submit and get admitted multiple workloads from a single LQ before their usage would be
accounted by the admission fair sharing mechanism.
```
=> Add entrance penalty for admitted Workloads

test/e2e/singlecluster/statefulset_test.go
/kind flake
Carry #6164 to release-0.11
Fixes #
There was a conflict with some of the MustCreate versus Create. The rebase was easy.
```release-note
NONE
```
=> manually carry 6164 to release-0.11

pkg/scheduler/scheduler.go, pkg/workloadslicing/workloadslicing.go, pkg/workloadslicing/workloadslicing_test.go
/kind bug
Fixes #6161
An alternative fix to https://github.com/kubernetes-sigs/kueue/pull/6194 proposed for #6161
```release-note
NONE
```
=> Fix workload slices when creation timestamps collide

site/content/en/docs/installation/_index.md
Add until section to the object retention policies alpha as it was graduated to beta
Follow-up for #6209
```release-note
NONE
```
=> docs: add until section to the object retention policies alpha

pkg/controller/core/localqueue_controller.go, pkg/queue/cluster_queue.go, pkg/queue/manager.go, pkg/scheduler/scheduler.go
/kind cleanup
Avoid leaking implementation details about heaps in the public API of a struct.
Fixes #6243 
```release-note
NONE
```
=> Rename ClusterQueue functions to hide heap implementation details

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/jobframework/reconciler.go, pkg/workload/workload.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/metrics_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/util/e2e.go
/kind bug
Fixes #5129
Fixes #5573
Fixes #5480
Since the issue has a racy nature I opened also experiment PRs:
- https://github.com/kubernetes-sigs/kueue/pull/6285 - aims to show the repro using 300 repeats on existing code
- https://github.com/kubernetes-sigs/kueue/pull/6284 - aims to show on CI the fix works
To minimize the scope of the fix I only use the strict mode for requests which operate on the status.admissionChecks.state. For other requests I leave non-strict (but we may revist that later).
```release-note
Fix the bug which could occasionally cause workloads evicted by the built-in AdmissionChecks
(ProvisioningRequest and MultiKueue) to get stuck in the evicted state which didn't allow re-scheduling.
This could happen when the AdmissionCheck controller would trigger eviction by …
```
=> Fix evicting workloads due to AdmissionCheck retry

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/controller/jobframework/reconciler.go, pkg/workload/workload.go, test/e2e/singlecluster/e2e_test.go, test/e2e/singlecluster/metrics_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/util/e2e.go
Cherry pick of #6298 on release-0.12.
#6298: [release-0.12] Fix evicting workloads due to AdmissionCheck retry
```release-note
Fix the bug which could occasionally cause workloads evicted by the built-in AdmissionChecks
(ProvisioningRequest and MultiKueue) to get stuck in the evicted state which didn't allow re-scheduling.
This could happen when the AdmissionCheck controller would trigger eviction by setting the
Admission check state to "Retry".
```
=> Automated cherry pick of #6298: [release-0.12] Fix evicting workloads due to AdmissionCheck retry

apis/config/v1beta1/configuration_types.go, cmd/kueue/main.go, site/content/en/docs/reference/kueue-config.v1beta1.md
Cherry pick of #6300 on release-0.12.
#6300: Support disabling the client-side rate limiting
```release-note
Support disabling client-side ratelimiting in Config API clientConnection.qps with a negative value (e.g., -1)
```
=> Automated cherry pick of #6300: Support disabling the client-side rate limiting

test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/e2e/singlecluster/jobset_test.go, test/e2e/singlecluster/metrics_test.go, test/e2e/singlecluster/tas_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/kueuectl/create_test.go, test/integration/singlecluster/webhook/core/clusterqueue_test.go, test/integration/singlecluster/webhook/core/cohort_test.go
/kind cleanup
Cleanup of resources to use predefined consts.
```release-note
NONE
```
=> [Cleanup] Tests to use resource consts

pkg/controller/admissionchecks/provisioning/controller.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
/kind bug
Fixes #6323 
It seems like Workload patch status's `.requeuState` was never copied properly so the provisioning controller always assumed the workload was never requeued before  
```release-note
ProvisioningRequest: Fix a bug that Kueue didn't recreate the next ProvisioningRequest instance after the
second (and consecutive) failed attempt.
```
=> [ProvReq] Fix ProvReq not recreating after second failed attempt 

site/content/en/docs/concepts/topology_aware_scheduling.md
I added a description for `kueue.x-k8s.io/podset-unconstrained-topology` annotation.
Other PodSet Group and Slice documentation will be added as part of https://github.com/kubernetes-sigs/kueue/issues/6251.
Fixes #
```release-note
NONE
```
=> Doc: Add kueue.x-k8s.io/podset-unconstrained-topology descriptions

config/components/certmanager/certificate-metrics.yaml, config/components/certmanager/common_name_transformer.yaml, config/components/certmanager/kustomization.yaml, config/components/certmanager/secret_name_transformer.yaml, config/default/cert_metrics_manager_patch.yaml, config/default/manager_webhook_patch.yaml, test/e2e/certmanager/metrics_test.go, test/e2e/config/certmanager/dev/kustomization.yaml, test/e2e/config/certmanager/kustomization.yaml
/kind cleanup
- When we build manifests from /tests/e2e/config/certmanager, the certmanager resources don't have the kueue- prefix.
- After deleting internalcert, the kueue- prefix is removed from secretName, we should add it manually.
- Add the kueue- prefix using a patch for the certificate commonName.
Fixes #
```release-note
Fixed a bug that prevented adding the kueue- prefix to the secretName field in cert-manager manifests when installing Kueue using the Kustomize configuration.
```
=> Add kueue- prefix for secretName on the Kustomize configuration

pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/controller/tas/node_failure_controller.go, pkg/metrics/metrics.go, pkg/scheduler/preemption/preemption.go, test/integration/singlecluster/controller/core/workload_controller_test.go, test/integration/singlecluster/scheduler/scheduler_test.go
/kind bug
Part of  #6296
This is the preparatory PR for https://github.com/kubernetes-sigs/kueue/pull/6297 to first align the user-observable behavior before commonizing the code.
```release-note
Fix accounting for the `evicted_workloads_once_total` metric:
- the metric wasn't incremented for workloads evicted due to stopped LocalQueue (LocalQueueStopped reason)
- the reason used for the metric was "Deactivated" for workloads deactivated by users and Kueue, now the reason label can have the following values: Deactivated, DeactivatedDueToAdmissionCheck, DeactivatedDueToMaximumExecutionTimeExceeded, DeactivatedDueToRequeuingLimitExceeded. This approach aligns the metric with `evicted_workloads_total`.
- the metric was incremented during preemption before the preemption request was issued. …
```
=> Fix accounting for the evicted_workloads_once_total metric

site/content/en/docs/concepts/cluster_queue.md
Fixes #6201
```release-note
NONE
```
=> FlavorFungibility: update documentation for FlavorFungibilityImplicitPreferenceDefault

test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/integration/singlecluster/scheduler/fairsharing/suite_test.go
/kind bug
/kind flake
Fix flaky test "Scheduler when Using AdmissionFairSharing at Cohort level should preempt a workload from LQ with higher recent usage"
Fixes #6227 
Giving some extra time to allow localqueue usage to be updated correctly, seem to fix the flakiness.
After applying the fix, the test was run for ~1 hour with 475 attempts, and no flakes occurred.
```release-note
NONE
```
=> [Flaky] Fix "should preempt a workload from LQ with higher recent usage"

pkg/controller/core/workload_controller.go, pkg/controller/tas/node_failure_controller.go, pkg/scheduler/preemption/preemption.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go
Cherry pick of #6459 on release-0.12.
#6459: Unexport workload functions and rename workload.EvictWorkload -> workload.Evict
```release-note
NONE
```
=> Automated cherry pick of #6459: Unexport workload functions and rename workload.EvictWorkload -> workload.Evict

test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go
/kind cleanup
Reserving quota should only happen for active CQ. We are bypassing currently the prevention mechanism which makes the tests rely on backdoor behavior. I think the intention of the tests is to reflect business use as close as possible.
Fixes #6311
I propose to drop the `readyAC` (which is actually pending) from tests, its intention is unclear, and it prevents making LQs and CQs active.
I can add a dedicated "When" test case if we figure out what was its intention, but I would prefer not to pollute most of the tests.
There was also another issue which prevented the CQ to be active - the mismatch in created RF name "on-demand" vs "rf1": https://github.com/kubernetes-sigs/kueue/pull/6483/files#diff-b524dd7e94e695c9007bf094b1ff9cd5a94952214c0db7de004c7ce5bea7ed1bR818-R822 …
=> Ensure CQ and LQ are active in ProvisioningRequests tests

hack/releasing/wait_for_images.sh
Prepare ./hack/releasing/wait_for_images.sh.
Prepare ./hack/releasing/wait_for_images.sh.
Usage: 
```
./hack/releasing/wait_for_images.sh <version>
Wait for images
Example:
./hack/releasing/wait_for_images.sh v0.13.2
```
Success logs:
```
./hack/releasing/wait_for_images.sh v0.13.1
Checking if "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue:v0.13.1" is available.
✅ Image "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue@sha256:f77326c7250c01a5389aa857a89e5ad69fc5700b811cea1c108c3da66b516091" is available.
Checking if "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueueviz-backend:v0.13.1" is available.
✅ Image "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueueviz-backend@sha256:5b53f49eb3535d727dce53a1f519662f0541d6bb274e75800c710a6d162fc281" is …
```
=> Prepare ./hack/releasing/wait_for_images.sh.

pkg/cache/tas_flavor_snapshot.go, pkg/resources/requests.go, pkg/scheduler/scheduler_test.go
Cherry pick of #6501 on release-0.12.
#6501: Fix Kueue crashing when PodSet count is 0
```release-note
TAS: fix the bug that Kueue is crashing when PodSet has size 0, eg. no workers in LeaderWorkerSet instance.
```
=> Automated cherry pick of #6501: Fix Kueue crashing when PodSet count is 0

test/e2e/multikueue/e2e_test.go
/kind cleanup
Change `ExpectObjectToBeDeleted` to `ExpectObjectToBeDeletedWithTimeout` in MultiKueue e2e tests.
To avoid timeouts as the Kueue controller is getting ready after reconnection.
Relates to #6399
```release-note
NONE
```
=> [Cleanup] Expect delete obj with timeout in MK e2e tests

pkg/cache/cache_test.go, pkg/cache/clusterqueue_test.go, pkg/cache/fair_sharing_test.go, pkg/cache/resource_node_test.go, pkg/cache/snapshot_test.go, pkg/controller/core/cohort_controller_test.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, pkg/scheduler/scheduler_test.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/integration/singlecluster/scheduler/scheduler_test.go, test/integration/singlecluster/webhook/core/cohort_test.go
Cherry pick of #6468 on release-0.12.
#6468: chore: FlavorQuotas testing wrapper should be built by Obj()
```release-note
NONE
```
=> Automated cherry pick of #6468: chore: FlavorQuotas testing wrapper should be built by Obj()

test/e2e/multikueue/e2e_test.go, test/util/e2e.go
/kind flake
In the test when we disconnect and re-connect worker cluster, we wait for Kueue deployment readiness.
However what sometimes is not ready are the kube-system pods, e.g. kindnet, kube-scheduler.
By checking their readiness after the reconnection we make sure the test does not fail.
Steps to eliminate flakines:
* Bind API Server address instead of docker connect/disconnect
* Wait for Kueue availability
* Wait for Kind cluster related components availability
* Add timeout for objects deletion after each test 
Fixes #6399 
This has been tested in repeated fashion, but locally.
I want to run couple retries on [pull-kueue-test-e2e-multikueue-main](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/6466/pull-kueue-test-e2e-multikueue-main/195270879138021 …
=> MultiKueue testing: allow running tests after: The connection to a worker cluster is unreliable

keps/77-dynamically-sized-jobs/README.md
Add Kueue-native Deployment support leveraging WorkloadSlices to Graducation Criteria:
- Alpha: Enable Kueue-native Deployment support.
- Beta: Re-evaluate Kueue-native Deployment support via `ElasticJobsViaWorkloadSlices`
Related #6334
This PR updates an existing KEP-77 per [suggestion](https://github.com/kubernetes-sigs/kueue/issues/6334#issuecomment-3168245874).
```release-note
NONE
```
=> Add Kueue-native Deployment support leveraging WorkloadSlices KEP-77 Graduation

pkg/controller/core/localqueue_controller.go
/kind cleanup
This PR removes an unused `ctx` parameter.
Fixes #6591
```release-note
NONE
```
=> refactor: remove unused 'ctx' parameter

pkg/cache/fair_sharing.go, pkg/cache/fair_sharing_test.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
When there are large values of quotas and (especially) fair weights, the rounding in DRS calculation causes the returned value to sometimes be 0 for borrowing CQs.  
With this PR I would like to make sure that any borrowing CQ gets DRS of at least 1. As expressed in the comment https://github.com/kubernetes-sigs/kueue/blob/6c61dda233c15975247f6338c5c745c976716541/pkg/cache/fair_sharing.go#L41-L48 `If zero, it means that the usage of the ClusterQueue is below the nominal` -- this PR is enforcing this rule. It was previously violated as all of the testcases added to this PR are failing without the fix.
This PR in my opinion should fix #6577 
Part of #6577
```release-note
FS: Fixing a bug where a preemptor ClusterQueue was unable to reclaim its nominal quota when the preemptee …
```
=> Fix fairsharing reclamation bug

cmd/kueueviz/backend/README.md, cmd/kueueviz/backend/middleware/cors.go
/kind bug
- Changed the default CORS setting in development mode from hardcoded localhost URLs to wildcard (`*`)
- Updated documentation in the backend README.md with current environment variables
Fixes #6584
```release-note
KueueViz: Fix KueueViz CORS configuration for development environments
```
=> fix(kueueviz): use wildcard for CORS allowed origins in development mode

test/e2e/customconfigs/objectretentionpolicies_test.go
/kind flake
Replace ExitFast behavior with WaitForDeletion in Object Retention Policy e2e test to ensure that the workload is not deleted before it's creation is verified
Fixes #6499
Fixes #6129
```release-note
NONE
```
=> fix: wait for workload creation object retention e2e

site/content/en/docs/concepts/cohort.md
Minor fix in link i came across while reading docs [here](https://kueue.sigs.k8s.io/docs/concepts/cohort/#configuring-quotas)
```release-note
NONE
```
=> Fix cohort link in docs

pkg/controller/tas/resource_flavor.go, pkg/controller/tas/resource_flavor_test.go, pkg/util/testingjobs/node/wrappers.go
/kind bug
This PR adds filtering for Node update events in the TAS (Topology-Aware Scheduling) controller to skip reconciliation when only `LastHeartbeatTime` is updated.
Previously, the TAS controller would trigger reconciliation for every Node update, including the periodic heartbeat updates.
Ref: #6551
```release-note
TAS: Fix a bug where new Workloads starve, caused by inadmissible workloads frequently requeueing due to unrelated Node LastHeartbeatTime update events.
```
=> TAS: Filter out Node updates with LastHeartbeatTime changes

hack/releasing/sync-notes.sh
/kind bug
Fix sync-notes.sh.
Part of #6288
```release-note
NONE
```
=> Fix sync-notes.sh.

pkg/cache/tas_flavor_snapshot_test.go, pkg/scheduler/flavorassigner/flavorassigner_test.go
/kind cleanup
Use utiltesting.ContextWithLog() for consistency and to increase verbosity.
Fixes #
```release-note
NONE
```
=> Use utiltesting.ContextWithLog().

pkg/cache/tas_flavor_snapshot_test.go
/kind cleanup
Add tests for HasLevel.
Fixes #5927
```release-note
NONE
```
=> Add tests for HasLevel.

pkg/scheduler/logging.go, pkg/scheduler/preemption/preemption.go, pkg/util/logging/logging.go
/kind cleanup
Adds logging to verify target selection for fairsharing.
Related to: https://github.com/kubernetes-sigs/kueue/issues/6577
We had no insight into why we were left with no preemption targets and what preemption targets were being considered after filtering during scheduling cycle for fairsharing.
```release-note
NONE
```
=> Add logging to verify target selection for fairsharing

pkg/scheduler/preemption/preemption.go
/kind cleanup
ensures that Target implements ObjectRefProvider interface at compile time
Fixes #
```release-note
NONE
```
=> ensures that Target implements ObjectRefProvider interface at compile time

pkg/scheduler/scheduler.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
Fix CrashLoopBackOff when using config/alpha-enabled and missing AdmissionFairSharing config.
Fixes #6663
```release-note
AFS: Fixed kueue-controller-manager crash when enabled AdmissionFairSharing feature gate without AdmissionFairSharing config.
```
=> Fix CrashLoopBackOff when using config/alpha-enabled.

pkg/controller/admissionchecks/multikueue/fswatch_test.go
/kind cleanup
Remove skipOnDarwin for TestFSWatchAddRm.
Fixes #
Here's an optimized and polished version of your text:
The issue https://github.com/fsnotify/fsnotify/issues/637 has been fixed and released. These tests now work on Darwin.
```release-note
NONE
```
=> Remove skipOnDarwin for TestFSWatchAddRm.

test/e2e/multikueue/e2e_test.go, test/e2e/singlecluster/pod_test.go, test/util/constants.go
/kind cleanup
Take into account Pod observedGeneration in E2E test for v1.34.
Fixes #6691
```release-note
NONE
```
=> Take into account Pod observedGeneration in E2E test for v1.34.

test/integration/singlecluster/controller/jobs/job/job_controller_test.go
/kind bug
This PR fixes bug in integration test impacting "Job with elastic jobs via workload-slices support".
Big thanks to @VassilisVassiliadis for spotting this issue! 
Fixes #
```release-note
NONE
```
=> Fix ElasticJob integration test bug.

pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/provisioning/controller.go, pkg/util/admissioncheck/admissioncheck.go, pkg/workload/admissionchecks.go, pkg/workload/admissionchecks_test.go, test/e2e/multikueue/e2e_test.go, test/integration/multikueue/dispatcher_test.go, test/integration/multikueue/enabled_integration_test.go, test/integration/multikueue/jobs_test.go, test/integration/multikueue/no_gc_test.go, test/integration/singlecluster/controller/admissionchecks/provisioning/provisioning_test.go, test/integration/singlecluster/controller/core/workload_controller_test.go, test/integration/singlecluster/tas/tas_test.go, test/util/util.go
/kind cleanup
As a prep PR for [this](https://github.com/kubernetes-sigs/kueue/pull/6601)
Relates to #6179
```release-note
NONE
```
=> [Cleanup] Move FindAdmissionCheck to admissioncheck pkg

pkg/scheduler/flavorassigner/flavorassigner.go
/kind cleanup
It factors out an inner loop from a helper function which grew a bit complex.
Fixes #6028 
1. I think the original function name (`findFlavorForPodSetResource`) was a bit out of date. \
(Given that after #5878  it takes a slice of PodSets, not a single one). \
I propose to rename it (to `findFlavorForPodSets`).
2. While the new helper should basically say "yes / no" (is the Flavor suitable for all PodSets?), there's one tricky case: \
When matching the node selector returns _an error_ (not just "no match"), the original code breaks _all loops_ and returns.
https://github.com/kubernetes-sigs/kueue/blob/21dbaa606e04d1a57c2fd17a703ff0e3ad48e5ed/pkg/scheduler/flavorassigner/flavorassigner.go#L686-L690
(This seems legit; AFAICS an error is returned only in [one …
=> Extract iteration over findFlavorForPodSetResource to a helper

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, pkg/controller/core/clusterqueue_controller.go, pkg/controller/core/clusterqueue_controller_test.go, pkg/controller/core/core.go, pkg/features/kube_features.go, pkg/features/kube_features_test.go, site/content/en/docs/installation/_index.md, site/content/en/docs/reference/components-tools/feature-gate-removed.md, site/content/en/docs/reference/kueue.v1beta1.md, site/content/zh-CN/docs/installation/_index.md, test/integration/singlecluster/controller/core/clusterqueue_controller_test.go
/kind deprecation
Сleans up the code, and related testing of QueueVisibility feature
Fixes #4240
```release-note
Stop serving the QueueVisibility feature, but keep APIs (`.status.pendingWorkloadsStatus`) to avoid breaking changes.
ACTION REQUIRED:
If you rely on the QueueVisibility feature (`.status.pendingWorkloadsStatus` in the ClusterQueue), you must migrate to VisibilityOndDemand 
(https://kueue.sigs.k8s.io/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand).
```
=> Drop the QueueVisibility feature

pkg/controller/jobs/deployment/deployment_webhook.go, pkg/controller/jobs/statefulset/statefulset_webhook.go
The deployment/sts  validate webhook prompt message is incorrect
Fixes #
```release-note
Fix the validation messages when attempting to remove the queue-name label from a Deployment or StatefulSet.
```
=> fix: parameter passing error

pkg/controller/jobframework/reconciler.go
/kind cleanup
Use RequeueAfter instead of Requeue.
Fixes #
As mentioned [here](https://github.com/kubernetes-sigs/controller-runtime/blob/e5878c995fc374a5d9b796b5fd4677f9be149571/pkg/reconcile/reconcile.go#L34-L42) Requeue is deprecated field and we should use RequeueAfter instead of Requeue.
```release-note
NONE
```
=> Use RequeueAfter instead of Requeue.

test/e2e/kueueviz/package-lock.json, test/e2e/kueueviz/package.json
/kind cleanup
Bump testing-library/cypress.
Fixes #
Manual fix for https://github.com/kubernetes-sigs/kueue/pull/6752.
```release-note
NONE
```
=> Bump testing-library/cypress.

pkg/scheduler/preemption/common/ordering.go, pkg/scheduler/preemption/fairsharing/ordering.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_test.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
- Moves `CandidatesOrdering` function to different package to avoid cyclic dependency 
- Uses `CandidatesOrdering` function in FS preemption algorithm in case of two ClusterQueues draw
- Adds logger to `TargetClusterQueueOrdering` so it can call `CandidatesOrdering`
- Adds integration test that tests the scenario described in the issue. Before the change the test failed
Fixes #6763 
I decided to keep moving the function and calling it in the same PR to be able to cherrypick it smoothly
```release-note
Fix the bug in FairSharing algorithm for identifying preemption candidates, as it could return a different
set of preemption target workloads (pseudo random) in consecutive attempts in tie-break scenarios,
resulting in excessive preemptions.
```
=> Order candidates for FS preemption using less function used to sort workloads

pkg/controller/tas/node_failure_controller.go, pkg/scheduler/flavorassigner/tas_flavorassigner.go, pkg/workload/workload.go
/kind cleanup
Rename failedNode to unhealthyNode.
Follow-up for https://github.com/kubernetes-sigs/kueue/pull/6806#pullrequestreview-3222717998
```release-note
NONE
```
=> Rename failedNode to unhealthyNode.

pkg/controller/jobs/pod/pod_controller.go
/kind cleanup
Step towards #4041
Both the label and the scheduling gate are set in the same place, so either both present in the "info" structure, or none.
https://github.com/kubernetes-sigs/kueue/blob/a54d1957188452834d1e75f0e556ee54e0ef8383/pkg/podset/podset.go#L65-L70
```release-note
NONE
```
=> TAS: don't rely on TAS label for Pod integration

hack/releasing/wait_for_images.sh
/kind cleanup
Interrupt wait_for_images.sh if gcloud is not installed.
Part of #6288
Follow-up for https://github.com/kubernetes-sigs/kueue/issues/6288#issuecomment-3285723576.
```release-note
NONE
```
=> Interrupt wait_for_images.sh if gcloud is not installed.

site/content/en/docs/concepts/topology_aware_scheduling.md
Fixes #
```release-note
NONE
```
=> [Doc] Add documentation about TAS fast hot swap

pkg/cache/hierarchy/manager_test.go, pkg/cache/queue/cohort.go, pkg/cache/queue/manager.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> (cleanup): remove redundant type arguments

pkg/scheduler/preemption/preemption.go
/kind cleanup
Collates preemptor workload name to UIDs in logs only
Fixes #
```release-note
NONE
```
=> Add workload and job UIDs to log

pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/pod/pod_controller_test.go
This PR refines the pod-integration `IsActive` logic by adding support for pods that are stuck in the **Terminating** state. Without this change, terminating pods with an expired grace period may still be treated as active, blocking quota release and preventing forward progress.
Related to #6757
N/A
```release-note
Pod-integration now correctly handles pods stuck in the Terminating state within pod groups, preventing them from being counted as active and avoiding blocked quota release.
```
=> Refine IsActive logic to ignore Pods stuck terminating in pod-integration pod-groups

pkg/util/cert/cert.go, pkg/util/cert/cert_test.go
/kind bug
This is a follow up to this [previous PR](https://github.com/kubernetes-sigs/kueue/pull/6869) which fixed an issue where the controller-manager would not start up properly when using a name other than kueue with internal cert management enabled. The helm chart takes into account the helm installation name when templating the MutatingWebhookConfiguration and ValidatingWebhookConfiguration. The controller, however, assumes a hard coded name of kueue. This updates the ManageCerts function to use the correct resource names when setting up the webhooks.
Fixes [# 6866](https://github.com/kubernetes-sigs/kueue/issues/6866) 
None
```release-note
Helm: Fixed bug where webhook configurations assumed a helm install name as "kueue".
```
=> fix: ensure webhook configurations use the correct resource name

apis/kueue/v1beta1/localqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml, pkg/config/validation_test.go, pkg/scheduler/scheduler_test.go, site/content/en/docs/reference/kueue.v1beta1.md, test/e2e/config/default/controller_manager_config.yaml, test/e2e/config/default/values.yaml, test/integration/singlecluster/controller/jobs/appwrapper/appwrapper_controller_test.go, test/integration/singlecluster/controller/jobs/jaxjob/jaxjob_controller_test.go, test/integration/singlecluster/controller/jobs/job/job_controller_test.go, test/integration/singlecluster/controller/jobs/jobset/jobset_controller_test.go, test/integration/singlecluster/controller/jobs/mpijob/mpijob_controller_test.go, test/integration/singlecluster/controller/jobs/paddlejob/paddlejob_controller_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/controller/jobs/pytorchjob/pytorchjob_controller_test.go, test/integration/singlecluster/controller/jobs/tfjob/tfjob_controller_test.go, test/integration/singlecluster/controller/jobs/xgboostjob/xgboostjob_controller_test.go, test/integration/singlecluster/tas/tas_test.go, test/integration/singlecluster/webhook/jobs/jobset_webhook_test.go, test/integration/singlecluster/webhook/jobs/paddlejob_webhook_test.go, test/integration/singlecluster/webhook/jobs/pytorchjob_webhook_test.go, test/integration/singlecluster/webhook/jobs/tfjob_webhook_test.go, test/integration/singlecluster/webhook/jobs/xgboostjob_webhook_test.go
/kind cleanup
Cleanup after graduation TAS to beta.
Fixes #3450
```release-note
NONE
```
=> Cleanup after graduation TAS to beta.

pkg/cache/tas_flavor_snapshot.go, pkg/scheduler/scheduler_test.go
Cherry pick of #6914 on release-0.13.
#6914: [TAS] Fix empty hot swap replacement for slices
```release-note
TAS: Fix the scenario when Node Hot Swap cannot find a replacement. In particular, if slices are used
they could result in generating invalid assignment, resulting in panic from TopologyUngater.
Now, such a workload is evicted.
```
=> Automated cherry pick of #6914: [TAS] Fix empty hot swap replacement for slices

pkg/cache/scheduler/cache.go, pkg/cache/scheduler/clusterqueue_snapshot.go, pkg/cache/scheduler/cohort_snapshot.go, pkg/cache/scheduler/fair_sharing.go, pkg/cache/scheduler/fair_sharing_test.go, pkg/scheduler/fair_sharing_iterator.go, pkg/scheduler/preemption/fairsharing/least_common_ancestor.go, pkg/scheduler/preemption/fairsharing/ordering.go, pkg/scheduler/preemption/fairsharing/strategy.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/scheduler_test.go, test/e2e/singlecluster/fair_sharing_test.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
We fix two FairSharing bugs:
1) Lack of precision when dividing integers in FairSharing. This is especially relevant to ClusterQueues/Cohorts with high FairSharing Weight, or large quotas
2) ClusterQueues/Cohorts with weight 0 infinite preemption loop.
Fixes #6774
Potentially fixes https://github.com/kubernetes-sigs/kueue/issues/4247, though we should discuss there whether we want to surface a more precise value in metrics/status
See also https://github.com/kubernetes-sigs/kueue/issues/6577. This builds upon https://github.com/kubernetes-sigs/kueue/pull/6617, removing the 1 DRS special case, while still passing the unit tests introduced in that PR.
1) Please apply extra scrutiny to the use of `float64`.
2) Please note the change in logging in `fair_sharing_iterator.go` @amy 
a) …
=> [Fair Sharing] Fix Rounding Bug

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml, pkg/webhooks/clusterqueue_webhook.go, pkg/webhooks/clusterqueue_webhook_test.go, site/content/en/docs/reference/kueue.v1beta1.md, test/integration/singlecluster/webhook/core/clusterqueue_test.go, test/integration/singlecluster/webhook/core/cohort_test.go
/kind feature
Currently Kueue limits the number of resource groups per ClusterQueue to 16, and then the number of flavors per resource group to 16, with the intention to limit the maximum number of flavors per ClusterQueue, since it can become a performance bottleneck. However, certain setups have very few resourcegroups but many flavors per resourcegroup, in which case the performance is perfectly fine as the total number of flavors is still acceptable, but they are just distributed across fewer resource groups. It makes much more sense to have a global "flavors per clusterqueue" limit than a limit on both lists.
This PR implements the following limits:
- Bump resource groups per clusterqueue from 16 to 64
- Bump flavors per resource group from 16 to 64
- Impose a new limit that limits …
=> Implement more flexible limitations on the number of Flavors per ClusterQueue

pkg/metrics/metrics.go, test/util/util.go
/kind cleanup
Cleanup after rename workload_priority_class label to priority_class.
Part of #5989
```release-note
NONE
```
=> Cleanup after rename workload_priority_class label to priority_class.

apis/config/v1beta1/defaults.go, apis/config/v1beta1/defaults_test.go, pkg/config/config_test.go, pkg/config/validation.go, pkg/config/validation_test.go, test/integration/singlecluster/kueuectl/suite_test.go
/kind cleanup
This PR cleans up of QueueVisibility config validation codes by removing all unused validation logic related to QueueVisibility configuration.
- Removed QueueVisibility-related constants and default settings from `apis/config/v1beta1/defaults.go`
- Cleaned test cases to remove QueueVisibility assertions
Fixes #6958
```release-note
NONE
```
=> [Cleanup] Remove QueueVisibility config validation code

pkg/cache/queue/manager.go, pkg/controller/core/core.go, pkg/controller/core/workload_controller.go, pkg/controller/core/workload_controller_test.go, pkg/dra/mapper.go, pkg/workload/workload.go, test/integration/singlecluster/controller/dra/dra_test.go, test/integration/singlecluster/controller/dra/suite_test.go
/kind bug
There is a difference between how DRA worklaods are processed and how other workloads are processed in Kueue. DRA workloads need some extra get calls, so they are skipped in event handlers and are instead processed in reconcile loop.
As a result, we need all the processing upon restart to happen through reconcile loop and avoid adding workloads to scheduler queue in all cases except the workload reconciler
Fixes #
```release-note
NONE
```
=> fix cases where DRA resources are skipping workload reconcile on their way to scheduler queue

pkg/cache/queue/manager.go, pkg/controller/core/workload_controller.go
/kind cleanup
This is a follow up from https://github.com/kubernetes-sigs/kueue/pull/6949 
Fixes #
```release-note
NONE
```
=> fix logging for dra code

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/flavorassigner/flavorassigner_test.go, test/integration/singlecluster/scheduler/preemption_test.go
* Fix: account for replaced workload slice in assigned flavor TotalRequestFor
Ensures that when a workload slice is replaced, its resource requests are properly reflected in `TotalRequestFor` during flavor assignment and subsequent preemption targets list generation.
(cherry picked from commit 19ebce0290ff2b1b7fa149c82037ca180ff93cdf)
/kind bug
This is 🍒 cherry-pick of "BugFix: scale-up workload stuck pending not triggering preemption."
Fixes #6969
```release-note
ElasticJob workloads correctly trigger workload preemption in response to a scale-up event.
```
=> [release-0.13] Cherry-pick 🍒 Fix Scale-up workload stuck pending not triggering preemption.

pkg/scheduler/scheduler.go
/kind cleanup
Remove unnecessary DeepCopy() on evictWorkloadAfterFailedTASReplacement.
Fixes #
```release-note
NONE
```
=> Remove unnecessary DeepCopy() on evictWorkloadAfterFailedTASReplacement.

apis/config/v1beta1/configuration_types.go, cmd/kueue/main.go, pkg/config/validation.go, pkg/controller/admissionchecks/multikueue/externalframeworks/adapter.go, pkg/controller/admissionchecks/multikueue/externalframeworks/adapter_test.go, pkg/controller/admissionchecks/multikueue/externalframeworks/config.go, pkg/controller/admissionchecks/multikueue/externalframeworks/config_test.go, site/content/en/docs/reference/kueue-config.v1beta1.md, test/integration/multikueue/external_job_test.go
This commit refactors the MultiKueue external frameworks adapter to improve code organization and centralize configuration validation.
Key changes include:
- Moves the adapter logic from `pkg/controller/jobs/generic` to `pkg/controller/admissionchecks/multikueue/externalframeworks` to better reflect its purpose.
- Renames `genericAdapter` to `Adapter`.
- Centralizes all validation for the `externalFrameworks` configuration into `pkg/config/validation.go`, including checks for feature gate enablement, duplicate GVKs, and conflicts with built-in adapters.
- Simplifies the adapter initialization by removing the `ConfigManager` in favour of package-level functions.
- Improves unit tests by using `cmp.Diff` for robust error comparison and removes a redundant integration test.
/kind cleanup …
=> refactor(multikueue): Rewrite external frameworks adapter

cmd/importer/pod/import.go, pkg/controller/core/workload_controller.go, pkg/controller/jobframework/reconciler.go, pkg/scheduler/scheduler.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go, test/integration/multikueue/dispatcher_test.go, test/integration/singlecluster/controller/core/workload_controller_test.go, test/integration/singlecluster/controller/jobs/pod/pod_controller_test.go, test/integration/singlecluster/scheduler/podsready/scheduler_test.go, test/integration/singlecluster/webhook/core/workload_test.go, test/performance/scheduler/runner/controller/controller.go, test/util/util.go, test/util/util_scheduling.go
/kind cleanup
Cleanup after prepare PatchAdmissionStatus().
Fixes #
```release-note
NONE
```
=> Optimize performance of controllers by skipping Reconcile if the object didn't change

pkg/controller/jobframework/tas_validation.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
/kind feature
Currently, the value of the `podset-group-name` annotation can be set to a value (matching `[0-9]+`) which will conflict of group keys:
https://github.com/kubernetes-sigs/kueue/blob/c824ca907b83c1f92c7381de072ecad2330c2d94/pkg/scheduler/flavorassigner/flavorassigner.go#L514-L517
Enforcing a stricter pattern will eliminate this possibility.
Even though, as far as I can see, this annotation is currently mostly geared towards `LeaderWorkerSet`, I made the validation part of the general TAS validation since it's part of `PodSetTopologyRequest`.
This is the first of a series of PRs related to #6242.
Even though technically this introduces a new user facing error, I wasn't sure whether a release note is warranted. _In theory_, someone could have used a value like "123" or even …
=> Validate `kueue.x-k8s.io/podset-group-name` annotation value

apis/kueue/v1beta1/workload_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml, config/components/crd/bases/kueue.x-k8s.io_workloads.yaml, pkg/controller/admissionchecks/multikueue/workload.go, pkg/controller/admissionchecks/multikueue/workload_test.go, pkg/controller/jobframework/reconciler.go, pkg/controller/jobframework/reconciler_test.go, pkg/controller/jobframework/validation.go, pkg/controller/jobframework/validation_test.go, pkg/controller/jobs/job/job_multikueue_adapter.go, pkg/controller/jobs/job/job_multikueue_adapter_test.go, pkg/scheduler/scheduler.go, pkg/util/testingjobs/job/wrappers.go, pkg/workload/workload.go, pkg/workloadslicing/workloadslicing.go, pkg/workloadslicing/workloadslicing_test.go, site/content/en/docs/reference/kueue.v1beta1.md, test/integration/multikueue/jobs_test.go
/kind feature
Now that the core ElasticJobsViaWorkloadSlices functionality has been introduced in Kueue as part of [KEP-77](https://github.com/kubernetes-sigs/kueue/tree/main/keps/77-dynamically-sized-jobs), this PR introduces MultiKueue support for ElasticJobsViaWorkloadSlices.
Fixes #6335 
```release-note
Add: Multikueue support for ElasticJobsViaWorklaodSlices with `batchv1/Job` support.
```
=> Introduce multi-Kueue support for ElasticJobs, with specific support for `batch/v1.Job` workloads when ElasticJob functionality is enabled.

pkg/scheduler/flavorassigner/flavorassigner.go, pkg/scheduler/scheduler_test.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
Cherry-pick #7024, #7040
Fixes #
```release-note
[Hierarchical Cohorts] When multiple borrowing flavors are available, prefer the flavor which
results in borrowing more locally (closer to the ClusterQueue, further from the root Cohort).
This fixes the scenario where a flavor would be selected which required borrowing
from the root Cohort in one flavor, while in a second flavor, quota was
available from the nearest parent Cohort.
```
=> [release-0.13] Cherry Pick #7024, #7040

apis/kueue/v1beta1/clusterqueue_types.go, charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml, charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml, config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml, config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml, site/content/en/docs/reference/kueue.v1beta1.md, test/integration/singlecluster/webhook/core/clusterqueue_test.go, test/integration/singlecluster/webhook/core/cohort_test.go
/kind bug
In PR https://github.com/kubernetes-sigs/kueue/pull/6906, the ClusterQueue coveredResource and Flavors limits where increased to 64. However, some fields still use the old limit of 16, including the [Resources under FlavorQuotas](https://github.com/kubernetes-sigs/kueue/blob/c05bfbd980952fd47b9957c9c5952dada41f0996/apis/kueue/v1beta1/clusterqueue_types.go#L215-L216) and [FlavorsReservation and FlavorsUsage under ClusterQueueStatus](https://github.com/kubernetes-sigs/kueue/blob/c05bfbd980952fd47b9957c9c5952dada41f0996/apis/kueue/v1beta1/clusterqueue_types.go#L277-L291). This PR increases those limits to 64 to make them consistent.
Fixes https://github.com/kubernetes-sigs/kueue/issues/7063
Increases ClusterQueue limit on Resources under FlavorQuotas, and FlavorsReservation and …
=> Fix limit for ClusterQueue Resources, FlavorReservation and FlavorUsage

pkg/controller/jobframework/tas_validation.go, pkg/controller/jobs/job/job_webhook_test.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_webhook_test.go
/kind cleanup
This is a follow-up to the #7051 which was merged with an ongoing discussion: https://github.com/kubernetes-sigs/kueue/pull/7051#discussion_r2388480522. It was agreed that this will be resolved in a second PR to get the original one merged quicker (https://github.com/kubernetes-sigs/kueue/pull/7051#issuecomment-3347779147).
Fixes #
I felt that it makes the most sense to "invert" the error message, i.e. treat `podset-group-name` as forbidden instead of the slicing annotations. This makes the validation cleaner, while the result remains pretty much identical identical since only the error message is changed.
If we are uncomfortable with the error message change for any reason, I'll revert 7fcc46c4c774455a1cb1df532f99a2288bb4e3d0, leaving just the restructuring commit which we …
=> Cleanup validation of `PodSet` simultaneous grouping and slicing in TAS

pkg/cache/scheduler/clusterqueue_snapshot.go, pkg/cache/scheduler/snapshot.go, pkg/scheduler/preemption/preemption_oracle.go, pkg/scheduler/scheduler.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go
/kind bug
During `SimulateWorkloadRemoval`, we were removing usage from the wrong ClusterQueue. I noticed this while debugging why we were assigning a suboptimal flavor in the context of #7015.
Because of this, in certain paths (notably [PreemptionOracle](https://github.com/kubernetes-sigs/kueue/blob/50b7ed542f9aef732cdbf95eb798f18308a577cb/pkg/scheduler/preemption/preemption_oracle.go#L60-L62)), we were claiming that [borrowingLevel=0](https://github.com/kubernetes-sigs/kueue/blob/50b7ed542f9aef732cdbf95eb798f18308a577cb/pkg/scheduler/flavorassigner/flavorassigner.go#L325-L330) for `Preempt` mode, but borrowingLevel>0 for `Fit` mode (after preemption successfully completed). In combination with `FlavorFungibilityImplicitPreferenceDefault=true`, this resulted in selecting the flavor with …
=> Fix SimulateWorkloadRemoval bug

test/e2e/customconfigs/reconcile_test.go
/kind cleanup
See https://github.com/kubernetes-sigs/kueue/pull/7048#discussion_r2390375173
Related to #7048 
I considered simplifying this by deleting all objects in the namespace, but wasn't sure if that would be safe. Instead, I went with tracking the jobs created in the default namespace and cleaning them up.
```release-note
NONE
```
=> Follow-up: Refactor reconcile_test to use AfterEach for default namespace cleanup

pkg/controller/jobframework/reconciler.go, pkg/scheduler/scheduler.go, pkg/util/testing/wrappers.go, pkg/workloadslicing/workloadslicing.go, pkg/workloadslicing/workloadslicing_test.go, test/integration/multikueue/jobs_test.go
/kind cleanup
We prefer to use Clock and setting transition times with the clock.
Rationale: https://github.com/kubernetes-sigs/kueue/issues/6901#issuecomment-3305105211
Fixes #7082
```release-note
NONE
```
=> [Cleanup] Use clock in WorkloadSlicing funcs

pkg/scheduler/preemption/fairsharing/ordering.go, pkg/scheduler/preemption/preemption.go, pkg/scheduler/preemption/preemption_oracle.go
Cherry pick of #7122 on release-0.13.
#7122: Use clock to get time.Now() in CandidatesOrdering.
```release-note
NONE
```
=> Automated cherry pick of #7122: Use clock to get time.Now() in CandidatesOrdering.

pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go
Replace scheduler stub with interceptor function in TestSchedule.
Fixes #6980
```release-note
NONE
```
=> Replace scheduler stub with interceptor function in TestSchedule.

site/content/en/docs/concepts/multikueue.md, site/content/en/docs/concepts/workload.md
Fixes #6158
```release-note
NONE
```
=> [Doc] Add WorkloadRequestUseMergePatch documentation

pkg/scheduler/scheduler_test.go
/kind cleanup
Replace scheduler stub with interceptor function in TestLastSchedulingContext.
Part of #6980
```release-note
NONE
```
=> Replace scheduler stub with interceptor function in TestLastSchedulingContext.

pkg/controller/jobframework/integrationmanager.go, pkg/controller/jobframework/integrationmanager_test.go, pkg/controller/jobframework/setup.go, pkg/controller/jobs/deployment/deployment_controller.go, pkg/controller/jobs/leaderworkerset/leaderworkerset_controller.go, pkg/controller/jobs/pod/pod_controller.go, pkg/controller/jobs/statefulset/statefulset_controller.go, test/e2e/customconfigs/podintegrationautoenablement_test.go
/kind feature
Automatically enable pod integration when pod-dependent frameworks (LWS, StatefulSet,
Deployment) are enabled, avoiding the need for users to explicitly enable it.
Fixes #6516
```release-note
Pod integration is now auto-enabled when using LeaderWorkerSet, StatefulSet, or Deployment frameworks.
```
=> Avoid explicit Pod integration enablement for pod-dependent frameworks

pkg/controller/jobframework/reconciler.go, pkg/scheduler/scheduler.go, pkg/util/testing/wrappers.go, pkg/workloadslicing/workloadslicing.go, pkg/workloadslicing/workloadslicing_test.go
Cherry pick of #7115 on release-0.13.
#7115: [Cleanup] Use clock in WorkloadSlicing funcs
```release-note
NONE
```
=> Automated cherry pick of #7115: [Cleanup] Use clock in WorkloadSlicing funcs

pkg/scheduler/scheduler_test.go, pkg/util/testing/wrappers.go, pkg/workload/admissionchecks.go, pkg/workload/workload.go
Cherry pick of #7118 on release-0.13.
#7118: Replace scheduler stub with interceptor function in TestSchedule.
```release-note
NONE
```
=> Automated cherry pick of #7118: Replace scheduler stub with interceptor function in TestSchedule.

pkg/controller/jobs/raycluster/raycluster_webhook.go, pkg/controller/jobs/raycluster/raycluster_webhook_test.go, pkg/controller/jobs/rayjob/rayjob_webhook.go, pkg/controller/jobs/rayjob/rayjob_webhook_test.go
/kind bug
While looking into `RayJob` validations for #7061, I noticed this weird path using a comma. Unless I'm missing something very obscure, this is a small typo. I figured I'll fix it.
Fixes #
```release-note
Fix malformed annotations paths being reported for `RayJob` and `RayCluster` head group specs.
```
=> Fix typos in `RayJob` and `RayCluster` head group metadata paths

pkg/cache/queue/cluster_queue.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/util/util_scheduling.go
/kind bug
When a workload, in a queue with BestEffortFIFO enabled, has preemption targets, we keep it at the head of the queue until it schedules (or returns inadmissible).
See original proposal here: https://github.com/kubernetes-sigs/kueue/issues/6929#issuecomment-3360978483
Fixes #7101, #6929
Let's discuss whether we want to put this behind a feature gate.
```release-note
With BestEffortFIFO enabled, we will keep attempting to schedule a workload as long as
it is waiting for preemption targets to complete. This fixes a bugs where an inadmissible
workload went back to head of queue, in front of the preempting workload, allowing
preempted workloads to reschedule
```
=> [BestEffortFIFO] Implement Sticky ClusterQueue Head Policy

pkg/queue/cluster_queue.go, pkg/queue/cluster_queue_test.go, pkg/queue/manager.go, test/integration/singlecluster/scheduler/fairsharing/fair_sharing_test.go, test/util/util_scheduling.go
/kind bug
Cherry-pick #7157, #7201
```release-note
With BestEffortFIFO enabled, we will keep attempting to schedule a workload as long as
it is waiting for preemption targets to complete. This fixes a bugs where an inadmissible
workload went back to head of queue, in front of the preempting workload, allowing
preempted workloads to reschedule
```
=> [release-0.13] Cherry-pick #7157, #7201
