kubernetes-sigs/kueue

- Makefile
- main.go
- pkg/constants/constants.go
- pkg/controller/core/capacity_controller.go
- pkg/controller/core/queue_controller.go
- pkg/controller/core/queuedworkload_controller.go
- pkg/controller/workload/job/job_controller.go
- test/integration/controller/job/job_controller_test.go
- test/integration/controller/job/suite_test.go
/kind cleanup
- Move integration tests into their own folder so that we can more easily run unit tests.
- Put controllers into pkg, splitting them in two kinds: core and workload (intended for integrating diverse custom job APIs).
Part of #20
Fixes #25
> Split integration tests into their own folder

- main.go
- pkg/constants/constants.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind feature
First Part of #9 
The event only includes the message that when it is assigned a capacity in the scheduling loop.
```bash
Status:
Conditions:
Last Probe Time:       2022-02-18T17:11:02Z
Last Transition Time:  2022-02-18T17:11:02Z
Message:               Job finished successfully
Reason:                JobFinished
Status:                True
Type:                  Finished
Events:
Type    Reason    Age   From           Message
----    ------    ----  ----           -------
Normal  Assigned  14s   kueue-manager  Assigned to capacity cluster-total
```
> add event for queuedWorkload

- pkg/capacity/snapshot_test.go
- pkg/queue/manager_test.go
- pkg/scheduler/scheduler.go
- Consolidate re-queuing in a single place (after finishing the scheduling cycle).
- Fix error messages
Follow up to #32
> Consolidate re-queuing in a single place

- config/rbac/role.yaml
- pkg/controller/core/capacity_controller.go
- pkg/controller/core/queue_controller.go
- pkg/controller/core/queuedworkload_controller.go
- pkg/controller/workload/job/job_controller.go
This is on the logs 
```bash
1.6455346824721851e+09  LEVEL(-2)       job-reconciler  Job assigned a capacity, unsuspending{"job": {"name":"sample-job-zkvlc","namespace":"default"}}                                       
E0222 12:58:02.473038       1 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"sample-job-zkvlc.16d61d13464ee05b", 
GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, D
eletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), …
```
> RBAC add missing resource to kubebuilder set

- Dockerfile
- Makefile
- README.md
example on with my setup
```bash
[eduardo@fedora kueue]$ make image-build                                                                                                                                                   [54/1922]
buildah bud -t quay.io/eduardoarango/kueue:21194b5-dirty \
--build-arg BASE_IMAGE=gcr.io/distroless/static:nonroot \                              
--build-arg BUILDER_IMAGE=golang:1.17 \                                                
\                          
./                            
[1/2] STEP 1/9: FROM golang:1.17 AS builder
Trying to pull docker.io/library/golang:1.17...                                         
Getting image source signatures
Copying blob 412caad352a3 skipped: …
```
> Makefile add arguments for img building and pushing

- config/samples/sample-job.yaml
After https://github.com/kubernetes-sigs/kueue/pull/50 , I am getting 
```bash
Warning  Failed     8s                 kubelet            Error: container create failed: time="2022-02-23T21:08:56Z" level=error msg="container_linux.go:380: starting container process ca
used: exec: \"sleep\": executable file not found in $PATH" 
```
this patch addresses that error
`sleep` bin is not in path , is in `/sleep` so we have to explicitly call if, see:
```bash
[eduardo@fedora kueue]$ skopeo inspect docker://gcr.io/k8s-staging-perf-tests/sleep:latest 
{
"Name": "gcr.io/k8s-staging-perf-tests/sleep",
"Digest": "sha256:366414c196307bd0336d71cba38843beec699a6264231b8ee025b9a288a0977f",
"RepoTags": [
"latest",
"v0.0.1",
"v0.0.2"
], …
```
> Update sample-job command

- README.md
/kind cleanup
Makefile states
```
IMAGE_REGISTRY ?= gcr.io/k8s-staging-kueue
IMAGE_NAME := kueue
IMAGE_TAG_NAME ?= $(VERSION)
```
But README goes all the way just on IMAGE_REGISTRY, this patch fix that
> README fix usage guidelines for IMAGE_REGISTRY

- Makefile
- config/manager/kustomization.yaml
/kind cleanup
After deploying, reverts the kustomize values back to the default image name. This will prevent contributors from accidentally changing the values in their commits.
> Make kustomize directive noop

- test/integration/controller/job/job_controller_test.go
- test/integration/controller/job/suite_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/suite_test.go
/kind cleanup
Puts duplicated code between suites in a framework package.
In the job controller, moves the manager setup from every case to once per suite. Initially I wanted to start a manager every time, but such isolation doesn't make much sense if we are sharing the same apiserver/etcd between tests.
Part of #68
> Add integration test framework

- pkg/capacity/capacity.go
- pkg/capacity/snapshot.go
- pkg/capacity/snapshot_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/wrappers.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Adds support for affinity matching with flavors
Fixes #3
still need to add integration tests
> Add support for affinity matching

- test/integration/controller/core/capacitycontroller_test.go
- test/integration/controller/job/job_controller_test.go
- test/integration/framework/constants.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
Refactor the scheduler integration tests so that resources are created in namespaces; also capacities and queues are created/deleted in before/afterEach closes.
> Refactor scheduler integration tests

- api/v1alpha1/queuedworkload_types.go
- config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
/kind cleanup
Remove Active condition from QW, we don't yet set it, and I don't think it is something that Kueue should be tracking. The Admitted condition is good enough for now.
We could add it back in the future if we get clarity on how to set it.
> Remove Active condition from QueuedWorkload

- main.go
- pkg/cache/cache.go
- pkg/cache/snapshot.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/queue/queue.go
- pkg/queue/queue_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/wrappers.go
- test/integration/controller/core/suite_test.go
- test/integration/scheduler/suite_test.go
/kind feature
Introduces a second implementation of ClusterQueue in `pkg/queue` which specializes on queueing.
Workloads associated to a Queue move as a block if the clusterQueue changes.
Fixes #87
> Have a single heap per ClusterQueue

- Makefile
/kind cleanup
Fixes #
From [GO 1.18 release notes](https://tip.golang.org/doc/go1.18):
>go get
go get no longer builds or installs packages in module-aware mode. go get is now dedicated to adjusting dependencies in go.mod. Effectively, the -d flag is always enabled. To install the latest version of an executable outside the context of the current module, use [go install example.com/cmd@latest](https://golang.org/ref/mod#go-install). Any [version query](https://golang.org/ref/mod#version-queries) may be used instead of latest. This form of go install was added in Go 1.16, so projects supporting older versions may need to provide install instructions for both go install and go get. go get now reports an error when used …
> Update `go-get-tool` in Makefile

- pkg/scheduler/scheduler.go
/kind bug
kueue panics when flavor is not found
```bash
2022-03-22T17:49:08.503+0800	DPANIC	scheduler	odd number of arguments passed as key-value pairs for logging	{"queuedWorkload": {"name":"job1","namespace":"default"}, "clusterQueue": {"name":"cluster-total"}, "ignored key": "default"}
sigs.k8s.io/kueue/pkg/scheduler.(*entry).assignFlavors
/Users/wangqingcan/Documents/github/kueue-denkensk/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:183
sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).nominate
/Users/wangqingcan/Documents/github/kueue-denkensk/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:162
sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).schedule
/Users/wangqingcan/Documents/github/kueue-denkensk/src/sigs.k8s.io/kueue/pkg/scheduler/scheduler.go:89 …
```
> fix panic when flavor is not found

- main.go
- pkg/constants/constants.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/core.go
- pkg/controller/core/queue_controller.go
- pkg/controller/core/queuedworkload_controller.go
- test/integration/controller/core/suite_test.go
- test/integration/scheduler/suite_test.go
/kind bug
Introduce and expose a Source so that a different controller can push events into the ClusterQueue controller.
This allows the QueuedWorkload controller to trigger CQ updates only after it has updated the cache, preventing race conditions.
Fixes #101
> Do ClusterQueue updates after QW is updated in cache

- api/v1alpha1/clusterqueue_types.go
- api/v1alpha1/queue_types.go
- api/v1alpha1/queuedworkload_types.go
- config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/crd/bases/kueue.x-k8s.io_queuedworkloads.yaml
- config/crd/bases/kueue.x-k8s.io_queues.yaml
/kind feature
Adds printer columns to all the resources for a quick overview of the resources
Part of #86
> Add printer columns to Queue, ClusterQueue and QueuedWorkload

- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
/kind bug
The helper was not updating the status when the condition already existed. It was passing an empty object to the client.
Added a unit test
Fixes #158
> Fix UpdateWorkloadStatus

- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/queue_controller.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_interface.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/queue/queue.go
- pkg/scheduler/scheduler.go
/kind bug
/kind flake
When requeueing, we need to notify the condition.
Also fixed queue manager to keep the most up-to-date object in a Queue
Fixes #158 
Used #161 to see that the scheduler issued a requeue, but there was no following scheduling attempts, suggesting that the scheduler was hanging waiting for kueues.
> Fix scheduler getting stuck when there are admission failures

- config/rbac/batch_admin_role.yaml
- config/rbac/batch_user_role.yaml
- config/rbac/clusterqueue_editor_role.yaml
- config/rbac/clusterqueue_viewer_role.yaml
- config/rbac/job_editor_role.yaml
- config/rbac/job_viewer_role.yaml
- config/rbac/kustomization.yaml
- config/rbac/queue_editor_role.yaml
- config/rbac/queuedworkload_editor_role.yaml
- config/rbac/queuedworkload_viewer_role.yaml
- config/rbac/resourceflavor_editor_role.yaml
- config/rbac/resourceflavor_viewer_role.yaml
- docs/tasks/README.md
- docs/tasks/setup_rbac.md
- Adds roles `kueue-batch-admin-role` and `kueue-batch-user-role` to simplify setting common permissions.
- Add a task that explains how to use them.
Fixes #64
> Add ClusterRoles and task on how to use them

- test/integration/controller/job/job_controller_test.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
The reference is important so that the QW is cleaned up when the Job is deleted
Bonus: fix some ginkgo lingo
Fixes #
I initially tested if the QW would get deleted when the Job is deleted, but it doesn't work because there is no GC running in integration :upside_down_face:
> Ensure that Job owns the QueuedWorkload

- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
We have had issues with phantom pods in kube-scheduler staying in the cache.
This test tries to replicate a similar scenario in kueue. I don't think there is currently a bug, because:
1. We don't use the `assumedWorkloads` map when calculating the snapshot.
1. Even if we used it, we use Update using the resourceVersion that we had in the queue, which cause the second scheduling attempt to fail.
1. We clear the assume cache on failure.
Fixes #
The challenging scenario is like follows:
1. Workload A doesn't fit because workload B is running
3. Workload A update comes in while we are attempting to admit workload A (this could be a status update)
4. Workload B finishes (or there is capacity for other reasons), so Workload A is admitted.
5. We try to admit workload A again …
> Add integration test for admitting multiple workloads after they didn't fit

- pkg/queue/manager.go
- pkg/queue/manager_test.go
/kind bug
When a workload update comes in while we are scheduling the same workload, we could be requeuing the same workload indefinitely even after it was already admitted.
It's unclear what happens in subsequent scheduling attempts. They might indefinitely fail or cause the workload to be re-admitted with no further effects.
Checking during requeue would put us on the safe side.
Fixes #
> Skip requeueing workload if it was already admitted

- apis/core/v1alpha1/clusterqueue_types.go
- config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- docs/concepts/cluster_queue.md
- docs/tasks/administer_cluster_quotas.md
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/snapshot_test.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/wrappers.go
/kind cleanup
Renames clusterQueue.spec.requestableResources[*].flavors[*].resourceFlavor -> spec.requestableResources[*].flavors[*].name
Fixes #
> Renamed flavor.resourceFlavor to flavor.name

- pkg/controller/workload/job/job_controller.go
- test/integration/controller/core/suite_test.go
- test/integration/controller/job/job_controller_test.go
- test/integration/controller/job/suite_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/suite_test.go
/kind feature
Adds an internal flag to control whether or not the job-controller reconciles jobs with no queue name set; by default those jobs are not processed.
This is important so users are not surprised that their existing running jobs get suspended when they first try Kueue.
This flag will be exposed to be configurable via ComponentConfig once we add it.
Fixes #
> Added an option to control processing jobs with no queue name set

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- config/prometheus/kustomization.yaml
- config/prometheus/role.yaml
- go.mod
- pkg/metrics/metrics.go
- pkg/scheduler/scheduler.go
/kind feature
Add metrics for admission attempts count and duration, needed to track that the scheduler is doing work.
Add role and rolebinding for prometheus to be able to list the services in the kueue-system namespace.
Part of #199 (4)
This doesn't add the prometheus ServiceMonitor, Role or RoleBinding by default, as users might have their own monitoring system, or they might not want to setup any prometheus at all.
In a follow up, I'll document how users can setup prometheus.
> Add metrics for admission attempts count and duration

- .golangci.yaml
- main.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/core.go
- pkg/controller/core/queue_controller.go
- pkg/queue/cluster_queue_interface.go
- pkg/queue/manager_test.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/queue_controller_test.go
- test/integration/controller/core/workload_controller_test.go
- test/integration/scheduler/suite_test.go
/kind cleanup
Enable goimports and automatically detects unorganized imports
Fixes https://github.com/kubernetes-sigs/kueue/pull/228#discussion_r856681587
> Enable goimports

- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
/kind bug
The number of pending workloads should include the workloads in the admissible staging area.
Fixes #
> Fix number of pending workloads in a BestEffortFIFO ClusterQueue

- pkg/queue/cluster_queue_best_effort_fifo_test.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/wrappers.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
https://github.com/kubernetes-sigs/kueue/pull/179#discussion_r844249409_
Fixes #
> Change make cluster queue in wrappers to bestfifo

- docs/setup/install.md
Signed-off-by: Jian Zeng <anonymousknight96@gmail.com>
We depends on cert-manager to handle webhook server certificates now, so we need to tell users to make user `cert-manager` has been installed before using `kueue`.
Ref #232
> doc: note how to install cert-manager

- CHANGELOG/CHANGELOG-0.2.md
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
/kind bug
/kind flake
If a workload is in the inadmissible set, but then we do an immediate requeue, the workload should move back into the queue.
Add a RELEASE NOTE
Part of #241
Should we cherry-pick into the release-0.1 branch?
> Immediate requeue in BestEffortFIFO should put a workload for retry

- go.mod
- go.sum
- main.go
- pkg/metrics/metrics.go
- pkg/queue/manager.go
- pkg/queue/queue.go
- test/integration/controller/core/queue_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Add metric pending_workloads. We only track it when there are changes in a queue. The total number of pending workloads for a cluster_queue can be obtained by aggregation.
Part of #199
> Add metric for pending workloads, broken down by queue and cluster_queue

- main.go
- test/integration/framework/framework.go
Signed-off-by: cmssczy smartczy@outlook.com
/kind cleanup
Currently all log timestamps are `epoch` by default. I think we can set the default log format to `RFC3339NanoTimeEncoder` to improve readability.
Fixes #
before
```
{"level":"info","ts":1651634969.944289,"logger":"setup","msg":"starting manager"}
```
after
```
{"level":"info","ts":"2022-05-04T04:09:51.19544479Z","logger":"setup","msg":"starting manager"}
```
> set default log timestamp format

- apis/kueue/v1alpha1/workload_webhook.go
- apis/kueue/v1alpha1/workload_webhook_test.go
- pkg/util/testing/wrappers.go
- test/integration/webhook/v1alpha1/workload_test.go
Signed-off-by: Jian Zeng <anonymousknight96@gmail.com>
/kind feature
Add basic validating webhook for Workload.
Part of #171
> Add validation for Workload via webhook

- pkg/util/testing/wrappers.go
- test/integration/scheduler/scheduler_test.go
> Update tolerated flavors integration test

- pkg/queue/manager.go
- pkg/queue/manager_test.go
/kind bug
Part of https://github.com/kubernetes-sigs/kueue/issues/241
> fix: update failure in requeue

- main.go
- test/integration/framework/framework.go
Signed-off-by: cmssczy smartczy@outlook.com
/kind feature
print filename and line number in log
Fixes #
you can see `caller` in log
```
{"level":"Level(-2)","ts":"2022-05-06T09:13:43.617296029Z","logger":"controller.workload","caller":"core/workload_controller.go:82","msg":"Reconciling Workload","reconciler group":"kueue.x-k8s.io","reconciler kind":"Workload","name":"pi","namespace":"default","workload":{"name":"pi","namespace":"default"}}
```
> add log filename and line number

- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
/kind bug
Met this panic several times in testing:
```
goroutine 560 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x21d9e40?, 0x31c25b0})
/Users/kerthcet/Workspaces/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0000ddc00?})
/Users/kerthcet/Workspaces/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/runtime/runtime.go:48 +0x75
panic({0x21d9e40, 0x31c25b0})
/Users/kerthcet/sdk/go1.18/src/runtime/panic.go:838 +0x207
sigs.k8s.io/kueue/pkg/queue.(*Manager).heads(0xc0000ddc00)
/Users/kerthcet/Workspaces/kueue/pkg/queue/manager.go:452 +0x32b
sigs.k8s.io/kueue/pkg/queue.(*Manager).Heads(0xc0000ddc00, {0x261b390, 0xc0009be210}) …
```
> fix: forget to cleanup inadmissibleWorkloads when deleteFromQueue

- pkg/util/priority/priority.go
- pkg/util/priority/priority_test.go
/kind cleanup
Added missing unit tests to the priority package (and fix a minor bug in it)
Fixes #
> test: add unit tests for the priority package

- CHANGELOG/CHANGELOG-0.1.md
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
> cherry-pick: Immediate requeue in BestEffortFIFO should put a workload for retry

- CHANGELOG/CHANGELOG-0.1.md
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
Cherry pick of #248 on release-0.1.
#248: fix: forget to cleanup inadmissibleWorkloads when
```release-note
Fixed bug in a BestEffortFIFO ClusterQueue where unadmissible workloads 
were not removed from the ClusterQueue when removing the corresponding Queue.
```
> Automated cherry pick of #248: fix: forget to cleanup inadmissibleWorkloads when

- pkg/cache/cache.go
- pkg/cache/cache_test.go
This reverts commit f9e7a83f2ace7851f4b72ef93de0ab9ec82553b7.
/kind cleanup
`Assumed` is a temporary state of workloads in memory, we can't rely on this to get all running workloads.
Fixes #
None
> Revert "Feat: add assumedWorkloads to ClusterQueue in package cache"

- test/integration/framework/framework.go
/kind bug
We should output more detail logs in integration tests for troubleshooting.
Fixes https://github.com/kubernetes-sigs/kueue/issues/287
```
2022-06-28T19:08:22.003145+08:00    LEVEL(-2)       controller.workload     cor^C8:00       LEVEL(-2)       controller.workload     core/workload_controller.go:82  Reconciling Workload    {"reconciler group": "kueue.x-k8s.io", "reconciler kind": "Workload", "name": "three", "namespace": "core-queue-sgw5f", "workload": {"name":"three","namespace":"core-queue-sgw5f"}}
2022-06-28T19:08:22.894131+08:00    LEVEL(-2)       controller.queue        core/queue_controller.go:72     Reconciling Queue       {"reconciler group": "kueue.x-k8s.io", "reconciler kind": "Queue", "name": "queue", "namespace": …
```
> Fix: integration tests missed detail logs

- pkg/scheduler/scheduler.go
/kind bug
The client would update the object in place. Since we store it in the cache, the object might be temporarily corrupted, which could cause conflicts with some cache update operations.
Fixes #
This is a candidate for cherry-pick, if we decide to release 0.1.2
> Make a copy of workload when admitting to avoid cache corruption

- test/integration/scheduler/scheduler_test.go
/kind cleanup
Before https://github.com/kubernetes-sigs/kueue/pull/263, we can delete a resourceFlavor without the impact of a clusterQueue, but now we added the finalizer to resourceFlavor, we'll wait in termination until the referenced clusterQueue deleted first. The test clusterQueue `Should be inactive when corresponding flavors deleted` is no longer suitable any more.
Fixes #
> Cleanup: remove no longer suitable tests in scheduler_test.go

- pkg/metrics/metrics.go
- pkg/queue/manager.go
- pkg/queue/queue.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/queue_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Remove the `queue` label from the `pending_workloads` metric.
As opposed to ClusterQueues, Queues are more likely to be unbounded by administrators, which could lead to cardinality explosion.
OTOH, administrators are more likely to care about metrics per ClusterQueue. Users, who might be the owners of Queues, might not even have access to metrics. They can still check the Queue status.
Ref https://github.com/kubernetes-sigs/kueue/pull/291#discussion_r916296493
> Reduce cardinality of pending_workloads metric

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/snapshot_test.go
- pkg/controller/core/core.go
- pkg/controller/core/queue_controller.go
- pkg/metrics/metrics.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/queue/queue.go
- pkg/workload/workload.go
- test/integration/controller/core/queue_controller_test.go
/kind feature
This PR doesn't have any user visible changes. The information can be used to populate the information into a Queue status, to improve observability of kueue.
This is a spin off from #291
Part of #259
> Track number of active running workloads per queue

- pkg/cache/cache.go
- pkg/metrics/metrics.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Add a metric that keeps track of admitted workloads that are still active (running).
This requires keeping track of admitted workloads per queue in the cache, which can also be used to report queue status.
Part of #199 
The metric will under-report active workloads if the queue is deleted, or the queue switches cluster queue, which should be disallowed with finalizers and webhooks #171
> Add metric for admitted active workloads

- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/workload_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup 
Fixes #
Another one `ExpectedResourceFlavorToBeDeleted` was addressed by https://github.com/kubernetes-sigs/kueue/pull/299
> Cleanup: rename ExpectedClusterQueueToBeDeleted

- apis/kueue/v1alpha1/resourceflavor_webhook.go
- apis/kueue/v1alpha1/resourceflavor_webhook_test.go
- config/webhook/manifests.yaml
- main.go
- pkg/controller/core/core.go
- pkg/controller/core/resourceflavor_controller.go
- pkg/util/testing/wrappers.go
- test/integration/controller/core/resourceflavor_controller_test.go
- test/integration/controller/core/suite_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
- test/integration/scheduler/suite_test.go
- test/integration/webhook/v1alpha1/resourceflavor_test.go
- test/integration/webhook/v1alpha1/suite_test.go
/kind feature
Fixes https://github.com/kubernetes-sigs/kueue/issues/283
> Add the finalizer via webhook when creating resourceFlavor

- apis/kueue/v1alpha1/workload_webhook_test.go
/kind cleanup
Fixes #
In tests, we set the old workload at the first place, but in `ValidateWorkloadUpdate` the first parameter is newObj. Mismatch here. 
https://github.com/kubernetes-sigs/kueue/blob/21091c614ea5261664274418c676cf71eee01f0c/apis/kueue/v1alpha1/workload_webhook_test.go#L145-L148
`func(oldObj, newObj)` seems more native than `func(newObj, oldObj)`.
> Refactor: change the parameters' order

- PROJECT
- apis/kueue/v1alpha1/queue_webhook.go
- apis/kueue/v1alpha1/queue_webhook_test.go
- config/crd/kustomization.yaml
- config/webhook/manifests.yaml
- main.go
- pkg/controller/core/core.go
- pkg/util/testing/wrappers.go
- test/integration/webhook/v1alpha1/queue_test.go
Signed-off-by: Jian Zeng <anonymousknight96@gmail.com>
/kind feature
Ref #171
> feat: implement validation webhook for Queue

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind bug
When adding a ClusterQueue to the cache, identify the resources that share the same list of flavors, which we call codependent.
When admitting, iterate through flavors, checking that all the codependent resources have enough quota for the flavor.
Fixes #167
This assumes that #308 is implemented.
> Assigning the same flavor to codependent resources

- pkg/metrics/metrics.go
- pkg/queue/manager.go
- pkg/scheduler/scheduler.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Add metrics per cluster_queue:
- `admitted_workloads_total`
- `admission_wait_time`
Fixes #199
> Add metrics for total number of admissions and wait time

- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
/kind feature
Default requests to limits if requests are not set.
This matches the internal defaulting for k8s Pods.
Fixes #316
> Default requests to limits in Workload

- test/integration/webhook/v1alpha1/workload_test.go
/kind cleanup
When testing workload defaulting, we should use plain workload for `MakeWorkload()` will set the podSet name automatically.
We don't have this problem in other API tests.
Fixes #
> fix test in workload defaulter

- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
/kind bug
If we always set a default name, we get an error like this:
```
The Workload "sample-workload" is invalid: spec.podSets[1]: Duplicate value: map[string]interface {}{"name":"main"}
```
Which is confusing, because the user didn't set this name.
Fixes #
This PR is based on #317. Review only from second commit.
> Only set a podSet name if there is only one

- apis/config/v1alpha1/groupversion_info.go
- apis/kueue/v1alpha1/groupversion_info.go
- apis/kueue/webhooks/workload_webhook.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/resourceflavor_controller.go
- pkg/controller/core/workload_controller.go
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/cluster_queue_interface.go
- pkg/queue/cluster_queue_strict_fifo.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/scheduler/scheduler_test.go
/kind bug
This PR updates the scheduler to avoid re-queueing workloads that don't match the cq NamespaceSelector.
The initial idea was to not add those workloads when first observed, but this is not enough to address this issue since a namespace label or CQ namespaceSelector could change by the time the workload that was initially accepted into the queue. Those changes could make the workload inadmissible due to not matching namespaceSelector, and so we still need a code path that handles the case during re-queueing.
The consequence is that such workloads will get evaluated, but at most once. To optimize away this wasted cycle, we will need to avoid adding the workload from the beginning, but this can be done as a followup because this PR is too long (I already made the changes to the …
> Avoid queueing workloads that don't match CQ namespaceSelector

- apis/kueue/v1alpha1/clusterqueue_types.go
- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
- config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
/kind feature
In a ClusterQueue two resources either have completely different flavors or they must share all flavors, in the same order.
Add validation and API documentation.
Fixes #308
> Validate codependent flavors in ClusterQueue

- apis/kueue/v1alpha1/clusterqueue_types.go
- apis/kueue/v1alpha1/resourceflavor_types.go
- apis/kueue/v1alpha1/workload_types.go
- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
- apis/kueue/webhooks/common.go
- apis/kueue/webhooks/queue_webhook.go
- apis/kueue/webhooks/queue_webhook_test.go
- apis/kueue/webhooks/resourceflavor_webhook.go
- apis/kueue/webhooks/resourceflavor_webhook_test.go
- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
- config/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
- config/crd/bases/kueue.x-k8s.io_workloads.yaml
/kind feature
Add validation for the maximum size of lists in the API. Notably:
- Max number of resources and flavors in ClusterQueue is 16
- Max number of labels and taints in ResourceFlavor is 8
- Max number of podSets in a Workload is 8
Also add some validations for some object references and taints.
Fixes #
This PR builds on top of #326, so you can review from the 2nd commit.
> Add validation for API lists sizes

- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
- apis/kueue/webhooks/resourceflavor_webhook.go
- apis/kueue/webhooks/resourceflavor_webhook_test.go
- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
/kind cleanup
Simplify error output for violations of API limits, by using TooMany instead of Invalid.
Fixes #
> Use TooMany instead of Invalid on validation errors

- .dockerignore
- Dockerfile
- Makefile
- main.go
- pkg/constants/constants.go
- pkg/util/useragent/useragent.go
- pkg/util/useragent/useragent_test.go
- pkg/version/version.go
/kind feature
Set user agent, which is used in apiserver logs:
```
"HTTP" verb="LIST" URI="/apis/kueue.x-k8s.io/v1alpha1/queues?limit=500&resourceVersion=0" latency="660.871µs" userAgent="kueue/0.2.0 (linux/amd64) 1f19339" audit-ID="dccde1a6-cb8b-467f-a4cb-7c2f56838aea
```
The first part of the user agent (`kueue`) would also be used as the field manager in the API objects created by kueue.
Also log the full version and commit:
```
{"level":"info","ts":"2022-08-17T18:58:01.271033131Z","logger":"setup","caller":"logr@v1.2.3/logr.go:261","msg":"Initializing","gitVersion":"0.2.0-devel-151-g1f19339-dirty","gitCommit":"1f1933977eaf9d2fa671dbeb6791df657e23a27f"}
```
Fixes #336
> Set user agent with semantic version

- pkg/controller/core/clusterqueue_controller.go
- pkg/metrics/metrics.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/cluster_queue_interface.go
- pkg/queue/manager.go
- pkg/scheduler/scheduler.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/job/job_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Adds a label for the status of workloads in a ClusterQueue. This is useful for administrators to tell if a ClusterQueue has too many inadmissible workloads, which could be an indication of misconfiguration.
Fixes #324
> Add status label to pending_workloads metric

- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
- test/integration/controller/core/workload_controller_test.go
- test/integration/webhook/v1alpha1/workload_test.go
/kind feature
queueName should only be immutable if the workload is admitted. Before admission (or after preemption) the user should be able to point to a different queue.
Also:
- validate that queueName is a valid reference name.
- validate that admission can be unset
Fixes #
> Validate queueName is immutable when the workload is admitted

- apis/kueue/v1alpha1/workload_types.go
- config/crd/bases/kueue.x-k8s.io_workloads.yaml
- main.go
- pkg/constants/constants.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/controller/job/suite_test.go
- test/integration/scheduler/suite_test.go
/kind feature
This would reduce the chances of conflict updating a Workload, because a controller might have updated the workload's status.
There would still be conflicts in the case of Spec updates. This is achieved setting the .metadata.generation field.
Fixes #164
> Use server-side-apply for admission

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/snapshot_test.go
- pkg/metrics/metrics.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Adds cluster_queue_status metric so administrators can monitor if a cluster queue is:
- pending: missing resource flavors
- active: ready to admit workloads
- terminating: marked for deletion but still has running workloads.
Fixes #340
> Add cluster_queue_status metric

- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
/kind cleanup
Use the same validation as for API resource names for `ClusterQueue.spec.cohort` to prevent arbitrary strings.
Fixes #
> Validate ClusterQueue cohort to be a valid object name

- config/components/prometheus/role.yaml
/kind bug
Both prometheus-k8s and prometheus-operator service accounts require permissions to list services, endpoints and pods.
Fixes #
> Fix prometheus rolebinding

- CHANGELOG/CHANGELOG-0.2.md
- README.md
- docs/concepts/README.md
- docs/concepts/cluster_queue.md
- docs/concepts/local_queue.md
- docs/concepts/queue.md
- docs/concepts/workload.md
- docs/setup/install.md
- docs/tasks/administer_cluster_quotas.md
- docs/tasks/run_jobs.md
Update documentation and changelog highlighting the main features and bugfixes.
Part of #222
> Enhance and update documentation

- Makefile
- README.md
- config/components/manager/kustomization.yaml
- docs/setup/install.md
Update version in install instructions and manifests.
Part of #352
> Release 0.2 update

- docs/concepts/cluster_queue.md
- docs/concepts/workload.md
- docs/tasks/administer_cluster_quotas.md
- docs/tasks/run_jobs.md
Cherry pick of #361 on release-0.2.
#361: Change references of v1alpha1 to v1alpha2 in docs
```release-note
```
> Automated cherry pick of #361: Change references of v1alpha1 to v1alpha2 in docs

- apis/kueue/v1alpha2/localqueue_types.go
- config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/controller/core/localqueue_controller.go
- test/integration/controller/core/localqueue_controller_test.go
Add AdmittedWorkloads to LocalQueueStatus API and update it in the LocalQueueController.
Fixes #259 
Sorry for the silliness with opening up multiple repos.  I have my laptop setup with CLA and github commits but I committed from another instance.  I didn't realize that if 1 commit doesn't have my email, it will fail the check.
> Add Admitted Workloads Field to LocalQueueStatus

- pkg/scheduler/scheduler_test.go
/kind cleanup
According to [this](https://pkg.go.dev/github.com/go-logr/logr@v1.2.3/testing), `github.com/go-logr/logr/testing` is deprecated. So we need to use `github.com/go-logr/logr/testr` instead of `github.com/go-logr/logr/testing`.
> Package testing provides support for using logr in tests. Deprecated. See github.com/go-logr/logr/testr instead.
Fixes #
> Stop using the deprecated library, github.com/go-logr/logr/testing

- CHANGELOG/CHANGELOG-0.3.md
- config/components/rbac/role.yaml
- pkg/controller/workload/job/job_controller.go
/kind bug
This fixes the manager's ClusterRole for clusters that have the [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) validation on, notably Red Hat's OpenShift.
Fixes #392
> Fix manager Role add jobs/finalizer resource

- Makefile
/kind bug
Running `make install` or `make uninstall` fails because it can't find the crd folder.
Fixes #
> Install and Uninstall should use config/components/crd

- Makefile
/kind cleanup
Test the same version as the API packages
Fixes #
> Upgrade envtest k8s version to 1.24

- test/integration/framework/framework.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
Exercise the multiple orders in which objects can be observed by kueue. They should all lead to admissible workloads.
Fixes #
> Add scheduler integration tests for creating objects out of order

- Makefile
- hack/update-toc.sh
- hack/verify-toc.sh
- keps/NNNN-template/README.md
- keps/NNNN-template/kep.yaml
Add an enhancements template, a trimmed version from k/enhancements.
Also copy the scripts to update and verify the TOC
Fixes #
> Add enhancements template and script for table of contents

- pkg/scheduler/scheduler.go
/kind bug
SSA requires these fields to be populated. The error looks like this.
```
Incorrect version specified in apply patch. Specified patch version: , expected: kueue.x-k8s.io/v1alpha2
```
Controller-runtime event objects don't include these fields.
Note that is issue is transient, as re-queuing would obtain the object from the client, which properly adds the fields. That's why I'm not adding an integration test, as they were all passing.
Fixes #406
> Add Kind and GroupVersion to SSA object

- docs/concepts/cluster_queue.md
- docs/setup/install.md
Changing Job template labels require k8s 1.23 or 1.22 with `JobMutableNodeSchedulingDirectives=true` (disabled by default).
Part of #406
> ResourceFlavor labels require k8s 1.23

- docs/concepts/cluster_queue.md
- docs/setup/install.md
Cherry pick of #408 on release-0.2.
#408: ResourceFlavor labels require k8s 1.23
```release-note
```
> Automated cherry pick of #408: ResourceFlavor labels require k8s 1.23

- Makefile
/kind bug
I fixed the `image-local-build` target so that we can propagate the `PUSH` variable to the `image-build` target.
- before
```shell
$ IMAGE_REGISTRY=ytenzen make image-local-push 
BUILDER=pensive_visvesvaraya
/Library/Developer/CommandLineTools/usr/bin/make image-build
docker buildx build -t ytenzen/kueue:v0.3.0-devel-59-g1a9514b-dirty \
--platform=linux/amd64,linux/arm64 \
--build-arg BASE_IMAGE=gcr.io/distroless/static:nonroot \
--build-arg BUILDER_IMAGE=golang:1.18 \
\
./
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 0.6s (1/1) FINISHED
...
````
- after
```shell
$ …
```
> Fix the image-local-build target

- Makefile
Adding testgrid test reports.  
I was told that adding junit report and saving those reports to artifacts.  The testgrid project should upload these and display more detailed test report.  
Fixes #402
> Adding junit.xml for unit/integration tests

- Makefile
- hack/e2e-test.sh
/kind bug
From the e2e-main log, we found that the kustomize not exists, then new built image will not be loaded successfully, this may cause test error like https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/414/pull-kueue-test-e2e-main/1595440995208531968#1:build-log.txt%3A299
```
Image: "gcr.io/k8s-staging-kueue/kueue:v0.3.0-devel-81-g2437b7f" with ID "sha256:03dc0be9da9af117f7ac63c8d968e29c966393c08da99d5a18475e0102dc4762" not yet present on node "kind-control-plane", loading...
./hack/e2e-test.sh: line 21: /home/prow/go/src/sigs.k8s.io/kueue/bin/kustomize: No such file or directory
```
Fixes #
> Fix e2e test not load the right image

- Makefile
- hack/e2e-test.sh
/kind feature
It allows us to run e2e tests on existing clusters. This could be useful for release testing on cloud vendors kubernetes clusters.
To run with a kind cluster
```
make test-e2e
```
To run with an existing cluster (assuming kubectl is configured for it)
```
make test-e2e USE_EXISTING_CLUSTER=true IMAGE_TAG=tag
```
Fixes #431 
I tested this by manually running a kind cluster and building the image built by the target `image-build`. Then I ran the e2e tests:
```
make test-e2e USE_EXISTING_CLUSTER=true IMAGE_TAG=gcr.io/k8s-staging-kueue/kueue:e0ec723-dirty
```
> configured e2e tests to run with existing cluster

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/framework/framework.go
/kind bug
The assumed status must be written before starting the admission goroutine. Otherwise, there is a race when requeuing, which needs to read the status.
In a separate commit: remove unnecessary log skip from integration tests.
Fixes #
This bug is unlikely to happen in production, as the goroutine first does an API call before attempting a requeue, which is slow.
> Fix race condition on admission error

- keps/349-all-or-nothing/README.md
- keps/349-all-or-nothing/kep.yaml
- keps/NNNN-template/README.md
/kind feature
It proposes an opt-in mechanism to avoid concurrent pod scheduling for workloads. It is useful for running workloads which require all pods to be running at the same time.
Part of: https://github.com/kubernetes-sigs/kueue/issues/349
> Design for all-or-nothing semantics for workload resource assignment

- test/performance/.env.example
- test/performance/.gitignore
- test/performance/README.md
- test/performance/config.yaml
- test/performance/job.yaml
- test/performance/local-queue.yaml
- test/performance/prerequisites/cluster-queue.template
- test/performance/prerequisites/resource-flavor.yaml
- test/performance/run-test.sh
This is an attempt to solve https://github.com/kubernetes-sigs/kueue/issues/45
The PR contains a [Clusterloader](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2) configuration to test job admission latency and throughput. It also includes a wrapper script that automates test scenario execution and captures the results.
Please see more details in the README file.
> Kueue performance tests

- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Calculate flavor assignments that could be satisfied with preemption.
If we find such assignment, prevent borrowing in the cohort. Actual preemption will be implemented in a follow up.
Part of #83 
This also solves what #403 was trying to solve.
> Prevent borrowing when preemption could help

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/controller/core/resourceflavor_controller.go
As discussed in https://github.com/kubernetes-sigs/kueue/pull/415#discussion_r1054785383, I updated `func (c *Cache) FlavorInUse(flavor string) (string, bool)` to `func (c *Cache) ClusterQueuesUsingFlavor(flavor string) []string` so that available to get clusterQueues with a specific resourceFlavor from the cache.
/kind cleanup
Fixes #
> Get ClusterQueues with a specific ResourceFlavor from the cache

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
/kind cleanup
Using a generic Set to hold the ClusterQueues in a cohort improves readability.
Exporting the members of the cohort enables the implementation of preemption within a cohort.
Fixes #
> Use generic Set for ClusterQueues in cohort

- pkg/cache/cache_test.go
/kind cleanup
This reduces a loop into a one-liner.
Although this caused the tests to check for namespaces, which should be preferred in the future, if we happen to add tests that exercise multiple namespaces.
Fixes #
> Use sets.KeySet to simplify cache tests

- pkg/cache/cache.go
- pkg/scheduler/scheduler.go
/kind cleanup
Consistency in the log schema is important for log processors
Follow up to #27
> Use klog.KRef when logging clusterQueue

- config/components/manager/controller_manager_config.yaml
/kind feature
Currently all controllers run on a single worker which may impact performance on larger clusters. The current configuration allows to define the concurrency but the setting is well hidden in the controller-runtime config api. The PR exposes the flags in the default config and increases the worker count to 3 for all controllers (except cert rotator). 
Before:
```
{"level":"info","ts":"2023-01-11T13:39:28.372773686Z","caller":"controller/controller.go:227","msg":"Starting workers","controller":"cert-rotator","worker count":1}
{"level":"info","ts":"2023-01-11T13:39:30.57174952Z","caller":"controller/controller.go:227","msg":"Starting workers","controller":"localqueue","controllerGroup":"kueue.x-k8s.io","controllerKind":"LocalQueue","worker count":1} …
```
> Explicitly set the number of controller workers in config and increase it to 3

- main.go
/kind bug
Currently the version and commit information is not printed due to wrong placement of the log (before init). This PR moves it after the init.
Before:
```
Version/commit is NOT printed
```
After:
```
{"level":"info","ts":"2023-01-11T14:53:15.204052+01:00","logger":"setup","caller":"kueue/main.go:85","msg":"Initializing","gitVersion":"v0.3.0-devel-168-gc326046-dirty","gitCommit":"c326046d8e41b57bf242fba021bedaa12613abf9"}
```
> Move version/commint logs after the logging is fully set up

- test/util/util.go
/kind cleanup
It seems to be an omission. The timeout in all other functions in `util.go` is 30s, but this function uses default which is 1s
Fixes #
> Configure timeouts for the ExpectWorkloadsToBeAdmitted as in other util functions

- keps/83-workload-preemption/README.md
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
/kind cleanup
Turns out we didn't need a distinction between two types of preemption (within Cohort and ClusterQueue).
Furthermore, the distinction implied that we could not preempt both from the Cohort and ClusterQueue, which limits preemption.
For example, you could have a case with an incoming workload requiring 2 cores, where 1 can be reclaimed from the cohort and the other from the ClusterQueue.
On the other side, this implies that we need an additional sorting criteria for preemption candidates: we should prioritize preempting workloads from ClusterQueues that are borrowing quota.
Part of #83
> One Preemption mode when assigning flavors

- pkg/controller/workload/job/job_controller.go
- test/integration/controller/job/job_controller_test.go
/kind bug
/kind cleanup
This is done to avoid the unnecessary flickering to the condition. 
Scenario. I create a job with 50 pods which sleep for 10s. 
The job is monitored with:
```shell
kubectl get job -w --output-watch-events -o=custom-columns="TYPE":.type,"NAME":.object.metadata.name,"SUSPEND":.object.spec.suspend,"READY":.object.status.ready,"ACTIVE":.object.status.active,"SUCCEEDED":.object.status.succeeded,"CONDITIONS":.o
bject.status.conditions
```
which outputs:
```
TYPE    NAME       SUSPEND   READY    ACTIVE   SUCCEEDED   CONDITIONS                                                                                                                                                                                                             [11/479]
ADDED   sleep10s   true      <none> …
```
> Do not update the PodsReady once True as long as the workload is admitted

- config/components/manager/controller_manager_config.yaml
/kind cleanup
On small to medium clusters higher parallelism on controllers other than Job, particularly ClusterQueue and LocalQueue controllers, can actually lead to poor performance. On those clusters the amount of ApiServer write QPS is fairly limited and using them for *Queue status (pod counter) updates chokes more important components.
> Set Job controller concurrency to 5 and drop other controllers to 1

- config/samples/sample-job.yaml
1. Add default namespace to Job, make sure it is in the sanme namespace with localQUeue
2. Add tag to image, no need to pull images always in kind
Signed-off-by: Kante Yin <kerthcet@gmail.com>
/kind cleanup
> Add default namespace to job in /samples

- pkg/cache/snapshot_test.go
Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>
/kind cleanup
I refactored tests for the snapshot.
Fixes #72,#269
> Refactor TestSnapshot

- config/components/rbac/role.yaml
- pkg/controller/core/workload_controller.go
/kind bug
Kueue needs watch permissions to maintain the informer for RuntimeClass
Fixes #564
This issue wouldn't show in integration tests.
And we can't simulate a RuntimeClass in a kind cluster, our current E2E test platform.
> Fix: add permission to watch RuntimeClass

- README.md
/kind document
Fixes https://github.com/kubernetes-sigs/kueue/issues/424
> Add roadmap to kueue

- pkg/controller/workload/job/job_controller.go
/kind cleanup
prefactor work before https://github.com/kubernetes-sigs/kueue/pull/544
The job controller work flow would like:
1. handling job is finished
2. handling workload is nil
3. processing only main job related logics
4. handling job is suspended
5. handling job is unsuspended
Fixes #
> Prefactor works of implementing job interface

- main.go
- pkg/scheduler/scheduler.go
- pkg/util/cert/cert.go
- test/integration/controller/job/suite_test.go
- test/integration/scheduler/podsready/suite_test.go
- test/integration/scheduler/suite_test.go
/kind bug
1. make workload scheduler to support leader election
2. make  webhook-server running in Primary and Secondary instance
Fixes #580 
@alculquicondor
> support workload scheduler leader election

- go.mod
- go.sum
/kind bug
Upgrade controller-runtime because the current version doesn't support SSA for the status subresource.
Fixes #601
> Upgrade controller-runtime

- apis/kueue/v1beta1/clusterqueue_types.go
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- site/content/en/docs/concepts/cluster_queue.md
Follow up to #514 
Fixes https://github.com/kubernetes-sigs/kueue/issues/576
I'm using v1beta1 in this PR, but updates to the rest of the documentation will come in a separate PR.
> Add documentation for preemption

- pkg/controller/jobframework/defaults.go
- pkg/controller/jobframework/indexer.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/validation.go
- pkg/controller/jobframework/webhook.go
- pkg/controller/jobframework/workload_names.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/job/job_webhook_test.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/mpijob/mpijob_webhook.go
/kind cleanup
/kind feature
1. to commonize the webhook and indexing code between Job and MPIJob
2. to introduce utility methods for webhood and indexing which will be ready to use for new frameworks
Part of #369
Related changes to GenericJob API:
- removed `error` being returned by some functions (such as `Suspend` and `UnSuspend`) it is not needed for now and it makes the code cleaner as the methods are used in webhooks
- renamed IsSuspend as IsSuspended
Note that, this changes could be a separate PR, but I coupled them for now to avoid conflicts as I'm using these functions.
> Commonize webhooks and indexing

- pkg/controller/core/clusterqueue_controller.go
/kind bug
According to [this](https://github.com/kubernetes-sigs/controller-runtime/blob/ffb74e54a54bcb10a615c501416820e06051b9b4/pkg/internal/controller/controller.go#L302-L312), the reconcileHandler requires a non-pointer `Request`. 
So current implementations, when the resourceFlavors were created, the clusterQueue controller can not queue clusterQueues to reconcileQueue like the following:
```shell
...
2023-03-16T01:09:36.715346+09:00      LEVEL(-2)       cluster-queue-reconciler        core/clusterqueue_controller.go:222     Got generic event       {"obj": {"name":"model-c"}, "kind": "/, Kind="}
2023-03-16T01:09:36.718727+09:00      ERROR   controller/controller.go:309    Queue item was not a Request    {"controller": "clusterqueue", "controllerGroup": "kueue.x-k8s.io", …
```
> Fix a generic event handler for resourceFlavors in the clusterQueue controller

- Makefile
/kind cleanup
Since k8s v1.24, envtest has started supporting arm64 architecture. So I removed a `--arch=amd64` from evntest command.
ref: https://github.com/kubernetes-sigs/kubebuilder/issues/2664
Fixes #
> Remove a --arch=amd64 flag from envtest command

- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
- config/components/rbac/role.yaml
- pkg/controller/core/indexer/indexer.go
- pkg/controller/core/workload_controller.go
- pkg/util/limitrange/limitrange.go
- pkg/util/limitrange/limitrange_test.go
- pkg/util/resource/resource.go
- pkg/util/resource/resource_test.go
- pkg/util/testing/wrappers.go
- test/integration/controller/core/workload_controller_test.go
/kind feature
Add the possibility to use default workload resource values based on [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/#constraints-on-resource-limits-and-requests) if present in the target namespace.
The order by which Requested resource values are set becomes:
1. Job spec
3. LimitRanges in the target namespace
2. Limits  set for the same container in the Job Spec
In addition, this provides a more generic alternative approach to fix #590, by moving the limits to request default in the workload controller without an impact to the workload's spec .
Fixes #541, #590
> [workload] Get default resource values from LimitRanges

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/localqueue_controller.go
- pkg/controller/core/workload_controller.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/localqueue_controller_test.go
- test/integration/controller/core/workload_controller_test.go
- test/util/util.go
To reduce complexity in the Workload controller and reduce API usage.
Set the Admitted condition value in the same API call that sets .status.admission.
Fixes #603
> 603 admitted condition swap complexity

- pkg/scheduler/scheduler.go
/kind cleanup
The precision of `creationTimestamp` is seconds, so it doesn't make sense to have higher precision in the admission event.
Fixes #
> Set wait time precision in admission event to seconds

- pkg/cache/cache.go
- pkg/controller/core/workload_controller.go
- pkg/workload/workload.go
/kind bug
Use resourceVersion in the SSA patch when setting Admitted=False. This guarantees that we don't accidentally override an admission that happens in a different routine.
The price to pay is potentially slower scheduling when workloads don't fit because of conflicts, but this should only happen just when a LocalQueue or ClusterQueue is created after a Workload.
Fixes #678
> Use resourceVersion when setting Admitted=False 

- pkg/controller/jobs/mpijob/mpijob_controller.go
Cherry pick of #682 on release-0.3.
#682: Fix typos for the MPIJob
```release-note
```
> Automated cherry pick of #682: Fix typos for the MPIJob

- CHANGELOG/CHANGELOG-0.4.md
- pkg/controller/jobframework/reconciler.go
- pkg/util/testingjobs/job/wrappers.go
- test/integration/controller/job/job_controller_test.go
/kind bug
Currently, the batch/job integration controller updates the queue name in workloads even if the batch/job is a child job, although a child job generally doesn't have a label indicating the queue name (`kueue.x-k8s.io/queue-name`).
So when we deploy the framework Jobs that use batch/job internally, such as MPIJob, and the framework job is waiting to be admitted by the ClusterQueue, the batch/job integration controller updates the `.spec.queueName` in the workload with an empty value by reconciling for a child batch/job.
Therefore I changed the condition to update the queue name in workloads so that the batch/job updates the field only when the batch/job is a parent job.
Fixes #697
> Update the queue name in workload only when the job is standalone

- CHANGELOG/CHANGELOG-0.4.md
- apis/kueue/v1beta1/workload_types.go
- pkg/controller/core/workload_controller.go
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/cluster_queue_strict_fifo.go
- pkg/queue/cluster_queue_strict_fifo_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/util/util.go
/kind feature
A new workload condition , `Evicted`, is added,  which gets set when:
1. The workload gets preempted
2. The workload hits the PodsReady timeout
In case of  PodsReady timeout, the condition transition timestamp will be used in scheduler sorting, therefore the workload will be moved at the end of the queue. 
Fixes #599
The  preemption based `Eviction` will be used in solving #510.
> [workload] WaitForPodsReady: Requeue at the back of the queue after timeout

- pkg/cache/cache.go
/kind bug
In the cache, the `admittedWorkloadsPerQueue` is indirectly updated via `updateWorkloadUsage` when running `AddClusterQueue`. So I removed the process to update `admittedWorkloadsPerQueue` from `AddClusterQueue`.
Fixes #
Same as #714
> Do not update allowedWorklodsPerQueue directly in AddClusterQueue

- CHANGELOG/CHANGELOG-0.4.md
- apis/kueue/webhooks/workload_webhook.go
- apis/kueue/webhooks/workload_webhook_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Add a way to control the number of pods a queue accepts at a given time.
Fixes #485
> Manage number of Pods as part of ClusterQueue quota

- pkg/cache/cache.go
- pkg/queue/manager.go
/kind cleanup
We used to check redundantly in some places since the fake client didn't support the field indexer.
However, since #588, we can use the field indexer for the fake client. 
So, I removed the redundant checks.
Fixes #
> Remove redundant checks in the cache

- CHANGELOG/CHANGELOG-0.4.md
- pkg/controller/core/workload_controller.go
- pkg/controller/jobframework/reconciler.go
- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_interface.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/scheduler.go
- test/integration/controller/job/job_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/integration/scheduler/preemption_test.go
- test/util/util.go
/kind feature
Keep evicted workloads in admitted while the associated jobs are still active
Fixes #510
> Keep evicted workloads in admitted while the associated jobs are still active

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/scheduler/preemption/preemption.go
- test/integration/controller/core/clusterqueue_controller_test.go
/kind bug
Enforce `.status.flavorUsage[*].resources[*].borrowed=0` if ClusterQueue doesn't belong to a cohort.
Fixes #746 
```release-note
Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort.
```
> Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort

- CHANGELOG/CHANGELOG-0.3.md
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/scheduler/preemption/preemption.go
- test/integration/controller/core/clusterqueue_controller_test.go
Cherry pick of #759 on release-0.3.
#759: Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort
```release-note
Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort.
```
> Automated cherry pick of #759: Fix: Enforce borrowed=0 if ClusterQueue doesn't belong to a cohort

- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobframework/integrationmanager_test.go
/kind cleanup
Fixes typos:
1. `registeres -> registers`
2. `registerd -> registered`
Fixes #
```release-note
None
```
> Fix typos in integrationmanager

- config/components/rbac/role.yaml
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
/kind bug
Even though the framework job controllers don't have permission to update the job status, controllers try to update statuses when stopJob.
https://github.com/kubernetes-sigs/kueue/blob/74f45f69612a2d36ace91ae455f1e9fdbcd53037/pkg/controller/jobframework/reconciler.go#L369-L373
In fact, I faced the below error in kueue v0.3.1:
```
{"level":"error","ts":"2023-05-23T10:29:47.851178422Z","caller":"jobframework/reconciler.go:265","msg":"stopping job","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"pi-1-launcher","namespace":"xxxxxxxxx"},"namespace":"xxxxxxxxx","name":"pi-1-launcher","reconcileID":"c8e2eff9-107f-48fd-a036-a5879372237c","job":"xxxxxxxxx/pi-1-launcher","error":"jobs.batch \"pi-1-launcher\" is forbidden: User …
```
> Add permission to update frameworkjob status

- .github/ISSUE_TEMPLATE/NEW_RELEASE.md
- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
/kind bug
When there is a mismatch between coveredResources and Flavors you can hit a panic.  
Fixes #786 
```release-note
Fix panic in cluster queue if resources and coveredResources do not have the same length.
```
> Fix cluster queue validating webhook

- go.mod
- go.sum
- main.go
- pkg/features/kube_features.go
- pkg/features/kube_features_test.go
/kind feature
/assign @alculquicondor 
Fixes https://github.com/kubernetes-sigs/kueue/issues/740
```release-note
Feature gates for alpha/experimental features is introduced to Kueue Project.
```
> Introduce feature gates

- apis/kueue/webhooks/clusterqueue_webhook.go
- apis/kueue/webhooks/clusterqueue_webhook_test.go
Cherry pick of #787 on release-0.3.
#787: Update steps of release process
```release-note
Fix panic in cluster queue if resources and coveredResources do not have the same length.
```
> Automated cherry pick of #787: fix panic in clusterqueue_webhook

- OWNERS
- pkg/controller/OWNERS
- pkg/util/OWNERS
- pkg/webhooks/OWNERS
/milestone v0.4
Add @kerthcet as approver for:
- deps (go.mod/go.sum)
- controllers (including integrations)
- webhooks
- utils
@kerthcet has been a long standing contributor to Kueue and has made numerous contributions and reviews to the project.
He is already deeply familiar with these packages and I'm confident that he can expand his ownership of kueue  in the future.
Fixes #
```release-note
NONE
```
> Add kerthcet as approver for deps, controllers, webhooks and utils

- Makefile
/kind cleanup
Use the cached MPI module to get its CRDs for integration tests.
Fixes #801 
```release-note
NONE
```
> [makefile] Use the cached MPI module to get its CRDs for integration tests

- OWNERS
- hack/OWNERS
- test/OWNERS
@tenzen-y has been a valuable contributor to kueue during the development of releases 0.3 and 0.4.
I can only imagine his ownership will grow from now.
For now, I propose he owns:
- The building stack (Makefile, Dockerfile, cloudbuild)
- The tests (integration, e2e, util).
Fixes #
```release-note
NONE
```
> Add tenzen-y as approver for Makefile, hack and test

- pkg/cache/cache.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/scheduler/preemption_test.go
- test/util/util.go
/kind bug
Giving a situation with a cohort composed of more than two queues, in which at least one queue is borrowing resources , when two new workloads are evaluated for admission within the same scheduling cycle, since the two workloads are not aware of each other,   they both can be evaluated as fit leading to over-admitting workloads within the cohort.
A simple solution could be to make sure that only one workload within a cohort is evaluated for admission within a single scheduling cycle, however since this can be a b drastic, we are limiting this limit to cohorts in which any of  its queues is borrowing.
Fixes #804
```release-note
Fix: Potential over-admission within cohort when borrowing.
```
> Fix concurrent admission in cohort when borrowing

- Makefile
/kind cleanup
I removed redundantly checks from Makefile. The `vet` and `fmt` are run at `verify`.
Fixes #
```release-note
None
```
> Remove redundantly checks from Makefile

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
/kind feature
Split the preemption process in two,  target selection and issuing, the first step can be use to check if preemption is possible without issuing preemption to any admitted workloads.
Relates to  #420 
```release-note
NONE
```
> [preemption] Two step preemption.

- Makefile
- charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
- config/components/rbac/role.yaml
- config/components/webhook/manifests.yaml
/kind cleanup
~~I upgraded the controller-tools to fix unknown field error in the following:~~
```
KubeAPIWarningLogger	log/warning_handler.go:65	unknown field "spec.podSets[0].template.metadata.creationTimestamp"
```
I upgraded the controller-tools to remove unneeded the creationTimestamp field.
xref: https://github.com/kubernetes-sigs/controller-tools/issues/402
Fixes #
```release-note
None
```
> Bumping controller-gen to remove unneeded creationTimestamp

- pkg/controller/constants/constants.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/known_frameworks.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/reconciler_test.go
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/job/job_webhook_test.go
- pkg/controller/jobs/mpijob/mpijob_webhook_test.go
- pkg/controller/jobs/rayjob/rayjob_webhook_test.go
- pkg/util/testing/client.go
- pkg/util/testingjobs/job/wrappers.go
- pkg/util/testingjobs/mpijob/wrappers_mpijob.go
- pkg/util/testingjobs/rayjob/wrappers.go
- test/integration/controller/job/job_controller_test.go
- test/integration/controller/job/job_webhook_test.go
- test/integration/controller/mpijob/mpijob_controller_test.go
- test/integration/controller/mpijob/suite_test.go
- test/integration/controller/rayjob/rayjob_controller_test.go
/kind bug
I fixed a bug that reconciles against unmanaged child batch/job.
Fixes #800
I have replicated https://github.com/kubernetes-sigs/kueue/pull/821.
```release-note
Fix a bug where a child batch/job of an unmanaged parent (doesn't have queue name) was being suspended.
```
> Ignore reconciling against unmanaged child jobs in the jobframework

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
/kind bug
Wrong candidate ordering for workloads admitted more recently first.
Fixes #840
```release-note
Fixed preemption to prefer preempting workloads that were more recently admitted.
```
> reverse condition for workloads admitted recently

- Makefile
- pkg/controller/core/resourceflavor_controller.go
- test/integration/controller/core/resourceflavor_controller_test.go
/kind bug
Fix integration test  `Core Controllers Suite: [It] ResourceFlavor controller when one clusterQueue references resourceFlavors Should delete the resourceFlavor when the corresponding clusterQueue no longer uses the resourceFlavor`
[Failed job link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-integration-main/1665373241604050944)
In addition:
- Add the possibility to provide additional arguments to Ginkgo when running integration test.
- Extend the logging in the resourceflavor controller.
Fixes #704
```release-note
NONE
```
> Fix failing ResourceFlavor controller integration test.

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
Make `ReclaimablePods` optional,  this way a job integration that is not supporting reclaimable no longer need to implement a dummy version of this method. 
Relates to #782
```release-note
NONE
```
> [jobframework] Make `ReclaimablePods` optional

- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/job/job_webhook_test.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller_test.go
- pkg/controller/jobs/mpijob/mpijob_webhook.go
/kind cleanup
Don't embed source job types , instead use type [re]definition this will remove the need of any allocations during type conversions.
Fixes #
```release-note
NONE
```
> Don't embed source job types 

- Makefile
- hack/e2e-test.sh
- test/e2e/suite_test.go
/kind cleanup
Add a new make target `test-e2e-all` which runs the e2e test for all k8s versions specified in `E2E_K8S_VERSIONS`.
Default `E2E_K8S_VERSIONS` is `1.24.7` `1.25.3` `1.26.2` `1.27.2`
Fixes #875
```release-note
NONE
```
> [makefile][e2e] Run e2e with multiple k8s versions.

- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/job/job_webhook_test.go
/kind cleanup
I added validation not to allow child jobs without ownerReference.
Follow-up: https://github.com/kubernetes-sigs/kueue/pull/821#discussion_r1211608721
```release-note
Add validation for child jobs without ownerReference.
```
> Add validation for child jobs without ownerReference

- pkg/cache/cache.go
- pkg/cache/cache_test.go
/kind bug
The resourceUsages should be in a stable order to avoid endless creation of update events.
So, I added processes to sort resourceUsages according to resourceName in ClusterQueue and LocalQueue. 
Fixes #902
```release-note
Fix a bug that updates events for clusterQueues are created endlessly.
```
> [Cache] Sort resourceUsages according to resourceName

- pkg/cache/cache.go
- pkg/cache/cache_test.go
Cherry pick of #907 on release-0.3.
#907: Sort resourceUsages according to resourceName
```release-note
Fix a bug that updates events for clusterQueues are created endlessly.
```
> Automated cherry pick of #907: Sort resourceUsages according to resourceName

- hack/e2e-test.sh
/kind cleanup
Proceed with cleanup if apiserver is down and logs cannot be obtained.
Fixes #
```release-note
NONE
```
> Continue E2E cleanup if apiserver is down

- hack/update-codegen.sh
/kind cleanup
The code-generator adds temporary module to go.mod when generating codes. So we should clean up go.mod.
```shell
diff --git a/go.mod b/go.mod
index 806cc12..4e11427 100644
--- a/go.mod
+++ b/go.mod
@@ -64,6 +64,7 @@ require (
github.com/stretchr/testify v1.8.2 // indirect
go.uber.org/atomic v1.11.0 // indirect
go.uber.org/multierr v1.11.0 // indirect
+       golang.org/x/crypto v0.1.0 // indirect
golang.org/x/mod v0.10.0 // indirect
golang.org/x/net v0.10.0 // indirect
golang.org/x/oauth2 v0.6.0 // indirect
diff --git a/go.sum b/go.sum
index ead83fc..d79d991 100644
--- a/go.sum
+++ b/go.sum
```
Fixes #
```release-note
NONE
```
> Clean up go module after generating codes

- pkg/cache/cache.go
/kind cleanup
We should use the same receiver name across all functions.
Fixes #
```release-note
NONE
```
> [Cache] Use the same reciever name for ClusterQueue

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller_test.go
- pkg/util/equality/podset.go
- pkg/util/equality/podset_test.go
- pkg/util/testing/wrappers.go
- pkg/workload/workload.go
/kind cleanup
Move `EquivalentToWorkload` functionality into the jobframework and simplify the GenericJob interface.
Fixes #782
```release-note
NONE
```
> [jobframework] Move `EquivalentToWorkload` functionality into framework

- charts/kueue/templates/rbac/role.yaml
/kind cleanup
Fixes #924
```release-note
NONE
```
> Added missing clusterrole rules for helm

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/snapshot.go
/kind cleanup
I refactored the cache package to increase maintainability. So I put the internal ClusterQueue on a separate file as discussed at #916.
Fixes #
```release-note
NONE
```
> [Cache] Put the internal ClusterQueue on a separate file

- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/jobset/jobset_controller_test.go
- pkg/util/testingjobs/jobset/wrappers.go
- test/integration/controller/jobset/jobset_controller_test.go
/kind feature
Adds support for dynamic reclaim in the JobSet integration.
Fixes #820 
```release-note
Add support for dynamic reclaim in the JobSet integration.
```
> Jobset dynamic reclaim

- test/integration/scheduler/scheduler_test.go
/kind bug
/kind flake
Fix flaky test  `Reclaimed resources are not accounted during admission`
Fixes #951
```release-note
NONE
```
> [test/integration] Fix scheduler reclaim flaky test

- site/content/en/docs/tasks/run_jobsets.md
Documenting JobSet support
Fixes #738 
```release-note
NONE
```
> Added docs on how to integrate JobSet

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/scheduler/scheduler.go
/kind bug
Trying to solve race condition when context is done
Fixes #886
```release-note
NONE
```
> Changed logic of pods ready cond

- examples/python/README.md
- examples/python/install-kueue-queues.py
- examples/python/requirements.txt
- examples/python/sample-job.py
- site/content/en/docs/tasks/_index.md
- site/content/en/docs/tasks/run_python_jobs.md
Problem: There are not examples for interacting with Kueue from Python Solution: Start a Python code samples directory. I am planning to add more to this but wanted to start with basic examples for installing Kueue and submitting a job.
There aren't good (or any) examples of interacting with Kueue via Python.
This will start to fix #947, however I'd like to add more complex examples to create an MPI job, a Flux Mini Cluster, and interact with queues / resource flavors from Python. I'm developing these into a workflow tool so likely will do them in subsequent PRs.
Sort of? It adds a README.md intended to be read by a user to the examples directory. However, there aren't changes to APIs, clients, etc, just scoped under documentation.
```release-note
NONE
```
> add python examples folder

- apis/config/v1beta1/configuration_types.go
- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
/kind feature
Fixes #486
```release-note
Added pprof endpoints for profiling
```
> Added pprof endpoint

- site/content/en/docs/tasks/run_python_jobs.md
- site/static/examples/python/install-kueue-queues.py
- site/static/examples/python/sample-queue-control.py
Problem: a developer user might want to (after submission) retrieve and list jobs.
Solution: provide a simple example of doing this.
A developer user might want to submit and monitor jobs, and this presents very simple monitoring. However, I'm wondering how this would scale? E.g., would hundreds of users be expected to be on the user-queue, in which case we'd have to (every time) get a complete listing of many jobs and iterate through? Or how would we do something like get jobs associated with a queue (I'm guessing this would be done via the label selector, which I mention at the end, but is that the only way?)
I started on an executor plugin for Snakemake using Kueue this weekend https://github.com/snakemake/snakemake-executor-kueue/ and these questions are real ones …
> add simple queue control example to python docs

- site/content/en/docs/tasks/run_flux_minicluster.md
- site/content/en/docs/tasks/run_python_jobs.md
- site/static/examples/python/sample-flux-operator-job.py
This will add a Python example for using Kueue with the Flux Operator! I have most of the MPI Operator done too, but ran into a bug with the ssh secret volume.
Users likely want to integrate Kueue into Python-based workflow tools, and examples are helpful for that!
Issue has been closed, previous issue is:
Fixes https://github.com/kubernetes-sigs/kueue/issues/947
This worked so well! I'm excited to try this out in an actual workflow tool
```release-note
NONE
```
> add flux operator python sdk example

- site/static/examples/python/sample-flux-operator-job.py
This is a quick fix for a typo mentioned in https://github.com/kubernetes-sigs/kueue/pull/962#discussion_r1267322857.
The docstring is referencing the wrong operator.
```release-note
NONE
```
> fix typo with reference to flux operator

- site/content/en/docs/installation/_index.md
- site/content/en/docs/reference/metrics.md
[site] Add cluster queue resource metrics
Relates to #972
```release-note
NONE
```
> [site] Add cluster queue resource metrics

- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/job/job_webhook_test.go
- pkg/util/testingjobs/job/wrappers.go
/kind feature
Synchronize `batch/job.completions` with `parallelism` in case of partial admission
Relates to: #970
This is the first step fixing #970.
```release-note
Synchronize batch/job.completions with parallelism in case of partial admission
```
> [batch/job] Partial admission - sync completions

- site/content/en/docs/tasks/run_mpi_jobs.md
- site/content/en/docs/tasks/run_python_jobs.md
- site/static/examples/python/sample-mpijob.py
This will add a Python example for Kueue + the MPI Operator. We were being blocked by https://github.com/kubernetes-sigs/kueue/issues/961, and determined that the order of operations for installing Kueue and the MPI Operator is important - the MPI operator must be installed first! Once that is done, each of the YAML applied example and the Python example worked. 
This is the last example (for the time being) of interacting with Kueue from Python. The use case is developers interacting with Kueue from Python (typically in workflow tools).
Fixes #961 
Also - if there is an additional documentation change we want to make to ensure it's clear about the order of install, I can add that here as well.
Happy Friday! Work is over wooo!
```release-note
NONE
```
> add example MPI operator job

- test/integration/controller/core/localqueue_controller_test.go
/kind bug
Fixes `Flaky test: Queue controller Should update status when workloads are created`.
Uses `util.ExpectResourceFlavorToBeDeleted` to make sure that ResourceFlavors were deleted completely.
Put the deletion of ClusterQueue before the deletion of ResoueceFlavors to avoid the ResoueceFlavors deletion failure.
Fixes #1015
```release-note
NONE
```
> Fix flaky test issue

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/util/testingjobs/job/wrappers.go
/kind bug
Preempting a batch/Job requires 3 API calls to the Job object because of the restrictions in the immutability of node affinity for started jobs.
This means that if any of the first 2 API calls fails, the job is not fully stopped and could have incompatible node affinities in a future admission.
This PR makes sure that a second sync is able to pick up from where the last failure happened.
Fixes #
```release-note
Improve job controller to be resilient to API failures during preemption
```
> Always try to stop a job on eviction

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind bug
When a CQ "A" with StrictFIFO strategy has pending workloads, it can block admissions in another CQ "B" in the same cohort with newer workloads, if they cannot be immediately admitted either, as introduced in #475 and #805. This allows CQ "A" to reclaim quota as soon as running workloads finish.
However, higher priority workloads should be able to be admitted first.
Fixes #
```release-note
Prevent workloads in ClusterQueue with StrictFIFO from blocking higher priority workloads in other ClusterQueues in the same cohort that require preemption
```
> Consider priority across ClusterQueues in a cohort

- test/e2e/e2e_test.go
- test/util/constants.go
/kind bug
Create const LongTimeout for e2e test. 
Pods in test sometimes takes long time because of the image pulling.
Fixes #1021
```release-note
NONE
```
> Fix Flaky test: Kueue when Creating a Job With Queueing [It] Should unsuspend a job and set nodeSelectors

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler_test.go
/kind bug
Following #805, in an admission cycle, we should only allow one admission/preemption if there are any CQs borrowing quota.
However, to make internal calculations, the preemption logic was deleting CQs from a cohort in the snapshot, corrupting the calculation of whether a cohort was borrowing quota in the scheduling cycle:
https://github.com/kubernetes-sigs/kueue/blob/0547fb163b2bb88dcaa42989fd2e513ca7d84d49/pkg/scheduler/scheduler.go#L144-L159
Fixes #
```release-note
Fixed scheduler to only allow one admission or preemption per cycle within a cohort that has ClusterQueues borrowing quota
```
> Avoid changing snapshot in preemption

- pkg/controller/constants/constants.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/util/testing/wrappers.go
/kind feature
* Added parent name and group-kind labels for workload objects.
* If parent's name, or group-kind exceeds the limit of 63 characters length, respective labels won't be added to a workload object.
Fixes #992
```release-note
NONE
```
> Add labels for workload parent

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller_test.go
/kind feature
Add a way to verify if the provided  PodSetsInfo is accepted by the job controller.
Fixes #
```release-note
NONE
```
> [jobframework] Check the potential failure of RunWithPodSetsInfo

- keps/168-pending-workloads-visibility/README.md
- keps/168-pending-workloads-visibility/kep.yaml
/kind feature
Fixes #168
```release-note
NONE
```
> KEP: Pending workloads visibility [expose in queue statuses]

- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller_test.go
/kind cleanup
[rayjob] Rework Info management test.
Fixes #
```release-note
NONE
```
> [rayjob] Make the TestNodeSelectors test table driven.

- test/integration/controller/job/job_controller_test.go
- test/integration/controller/jobset/jobset_controller_test.go
- test/integration/controller/mpijob/mpijob_controller_test.go
- test/integration/controller/rayjob/rayjob_controller_test.go
- test/integration/scheduler/scheduler_test.go
- test/integration/scheduler/workload_controller_test.go
/kind bug
* Fixes `resourceflavors.kueue.x-k8s.io "<RF-NAME>" already exists` errors.
* AfterEach functions in some of the tests didn't wait for ResourceFlavor objects to be fully deleted.
* Uses util.ExpectResourceFlavorToBeDeleted to wait for ResourceFlavor deletion.
Fixes #1027 
```release-note
NONE
```
> Fix flaky tests that had problems cleaning up RFs

- main.go
/kind cleanup
I removed an unused arg from `setupScheduler()`.
Fixes #
```release-note
NONE
```
> Remove an unused arg from setupScheduler()

- config/components/rbac/role.yaml
- go.mod
- main.go
/kind cleanup
Using RESTMapper, we can ensure that the manager recognizes the frameworks, and we can reduce passing permissions to the manager.
Fixes #
```release-note
NONE
```
> Ensure that the framework is available using RESTMapper instead of getting CRDs

- Makefile
- charts/kueue/templates/rbac/role.yaml
/kind cleanup
Extend `make verify` to fully check `charts/kueue/templates`
Fixes #
```release-note
NONE
```
> Extend `make verify` to fully check `charts/kueue/templates`

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/util/testing/wrappers.go
- test/integration/controller/job/job_controller_test.go
/kind feature
Add and manage resourceInUse finalizer for workloads, to add the posibility to restore the podSets Info upon workload deletion.
Fixes #518
This PR is split of #834 ,  the code was reviewed there.
```release-note
NONE
```
> Workload finalizer

- apis/config/v1beta1/configuration_types.go
- charts/kueue/templates/rbac/role.yaml
- charts/kueue/templates/rbac/tfjob_editor_role.yaml
- charts/kueue/templates/rbac/tfjob_viewer_role.yaml
- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- config/components/rbac/role.yaml
- config/components/rbac/tfjob_editor_role.yaml
- config/components/rbac/tfjob_viewer_role.yaml
- config/components/webhook/manifests.yaml
- main_test.go
- pkg/controller/jobs/kubeflow/jobs/jobs.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_webhook_test.go
- pkg/util/testingjobs/tfjob/wrappers_tfjob.go
- test/integration/controller/tfjob/suite_test.go
- test/integration/controller/tfjob/tfjob_controller_test.go
/kind feature
I added the tfjob-controller to the frameworkjob-manager.
Part-of https://github.com/kubernetes-sigs/kueue/issues/297
```release-note
Support kubeflow.org/tfjob
```
> Support kubeflow.org/tfjob

- keps/993-two-phase-admission/README.md
- keps/993-two-phase-admission/kep.yaml
Two Stage Admission Process - to allow external controllers to co-decide about workload admission. 
Fixes #993 
```release-note
```
> KEP 993: Two Stage Admission Process

- apis/kueue/v1beta1/admissioncheck_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
- config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
- test/integration/webhook/admissioncheck_test.go
- test/util/util.go
/kind cleanup
I synchronized the AdmissionCheck API with [KEP](https://github.com/kubernetes-sigs/kueue/tree/79d810b422f9851ca288e8a7fb9bfd81e67f062b/keps/993-two-phase-admission) one.
1. Clean up comments.
2. Make `.spec.ControllerName` required field.
3. Set default value to `.spec.retryDelayMinutes`.
Fixes #
```release-note
Set default value to `.spec.retryDelayMinutes`,
```
> Sync AmissionCheck API with KEP one

- charts/kueue/templates/rbac/role.yaml
- config/components/crd/kustomization.yaml
- config/components/rbac/role.yaml
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/controller/core/admissioncheck_controller.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/core.go
- pkg/util/testing/not_found_error_cmp.go
- pkg/util/testing/wrappers.go
- test/e2e/e2e_test.go
- test/integration/controller/core/admissioncheck_controller_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/util/util.go
/kind feature
[controller/core] Add AdmissionCheckReconciler
Its main goal at this stage is to help managing the active status of the
cluster queues mast on the admission checks presence.
Relate to #993
In draft pending #1045 merge.
```release-note
Manage cluster queue active state based on admission checks life cycle.
```
> Add AdmissionCheckReconciler

- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
- test/integration/controller/jobs/tfjob/tfjob_controller_test.go
/kind cleanup
I removed duplicated constants in the integration tests.
I found this in https://github.com/kubernetes-sigs/kueue/pull/1114#discussion_r1324234890.
Fixes #
```release-note
NONE
```
> Remove duplicated constants in the integration tests

- apis/config/v1beta1/configuration_types.go
- charts/kueue/templates/rbac/role.yaml
- charts/kueue/templates/rbac/xgboostjob_editor_role.yaml
- charts/kueue/templates/rbac/xgboostjob_viewer_role.yaml
- charts/kueue/values.yaml
- cmd/kueue/main_test.go
- config/components/manager/controller_manager_config.yaml
- config/components/rbac/kustomization.yaml
- config/components/rbac/role.yaml
- config/components/rbac/xgboostjob_editor_role.yaml
- config/components/rbac/xgboostjob_viewer_role.yaml
- config/components/webhook/manifests.yaml
- pkg/controller/jobs/kubeflow/jobs/jobs.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_webhook_test.go
- pkg/util/testingjobs/xgboostjob/wrappers.go
- test/integration/controller/jobs/xgboostjob/suite_test.go
- test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
/kind feature
Support kubeflow.org/xgboostjob.
Part-of https://github.com/kubernetes-sigs/kueue/issues/297
```release-note
Support kubeflow.org/xgboostjob
```
> Support kubeflow.org/xgboostjob

- hack/e2e-test.sh
/kind flake
Fixes flaky tests that were timing out as the images used in e2e were not being pulled in time.
This PR addresses [Issue - Pre-pull docker images used for testing](https://github.com/kubernetes-sigs/kueue/issues/1108). The issue contains more information on the flaky tests.
```release-note
NONE
```
> Pull and Load E2E Images

- pkg/queue/cluster_queue_impl.go
/kind cleanup
Fixes #1098
```release-note
None
```
> release lock as soon as finish using

- pkg/controller/core/clusterqueue_controller.go
- pkg/queue/manager.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/suite_test.go
/kind bug
/kind flake
Fixes #1122
When the snapshot is updated it triggers reconciliation, when the next status update is expected.
Tested by running in a loop and no flakes after 100 repeats
I have disabled the check for time https://github.com/kubernetes-sigs/kueue/blob/ee5b6ba29a1bbed1574262e362182573c5f6fa5e/pkg/controller/core/clusterqueue_controller.go#L603. With this check the test flakes, as there is a possibility, that the last reconciliation is triggered by snapshot updated, and `< UpdateInterval`, so it would not result in queue change. Further, the next snapshot check would not trigger another reconciliation as the snapshot is not changed. I think we can improve the behavior by marking a snapshot by snapshot revisions (1, 2, 3...). Then, we could skip comparing the contents of …
> Trigger cq reconciliation on snapshot change

- cmd/kueue/main.go
/kind cleanup
The kueue-controller should ensure whether or not framework CRDs are installed by `meta.IsNoMatchError()`.
Fixes #1054
I verified that the improvement works fine on my local:
```
...
{"level":"info","ts":"2023-09-19T18:33:52.997737585Z","logger":"setup","caller":"kueue/main.go:239","msg":"No matching API server for job framework, skip to create controller and webhook","jobFrameworkName":"jobset.x-k8s.io/jobset"}
...
{"level":"info","ts":"2023-09-19T18:33:52.998965835Z","logger":"setup","caller":"kueue/main.go:239","msg":"No matching API server for job framework, skip to create controller and webhook","jobFrameworkName":"kubeflow.org/pytorchjob"}
...
{"level":"info","ts":"2023-09-19T18:33:53.000000335Z","logger":"setup","caller":"kueue/main.go:239","msg":"No matching API …
```
> Ensure whether or not framework CRDs are installed by meta.IsNoMatchError()

- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/clusterqueue_controller_test.go
- pkg/features/kube_features.go
- site/content/en/docs/installation/_index.md
- test/integration/controller/core/admissioncheck_controller_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/localqueue_controller_test.go
- test/integration/controller/core/resourceflavor_controller_test.go
- test/integration/controller/core/suite_test.go
- test/integration/controller/core/workload_controller_test.go
/kind cleanup
Enable visibility of cluster queue using feature gate flag
Fixes #1102 
```release-note
Enabling/disabling visibility of cluster queue using feature gate flag
```
> Adding featuregate for cluster queue visibility

- apis/config/v1beta1/configuration_types.go
- charts/kueue/templates/rbac/paddlejob_editor_role.yaml
- charts/kueue/templates/rbac/paddlejob_viewer_role.yaml
- charts/kueue/templates/rbac/role.yaml
- charts/kueue/values.yaml
- cmd/kueue/main_test.go
- config/components/manager/controller_manager_config.yaml
- config/components/rbac/kustomization.yaml
- config/components/rbac/paddlejob_editor_role.yaml
- config/components/rbac/paddlejob_viewer_role.yaml
- config/components/rbac/role.yaml
- config/components/webhook/manifests.yaml
- pkg/controller/jobs/kubeflow/jobs/jobs.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_webhook_test.go
- pkg/util/testingjobs/paddlejob/wrappers.go
- test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
- test/integration/controller/jobs/paddlejob/suite_test.go
/kind feature
I added the paddlejob-controller to the frameworkjob-manager.
Part-of https://github.com/kubernetes-sigs/kueue/issues/297
I verified the behavior using https://github.com/kubernetes-sigs/kueue/pull/1148 example in the real cluster.
```release-note
Support kubeflow.org/paddlejob
```
> Support kubeflow.org/paddlejob

- Makefile
- go.mod
- go.sum
/kind feature
It enables us to use new packages introduced in go 1.21. It's required to merge [PR#1141](https://github.com/kubernetes-sigs/kueue/pull/1141)
```release-note
NONE
```
> Bump go version

- pkg/workload/workload.go
/kind cleanup
Avoids unnecessary allocation in workload.HasAllChecks
Relates to: #1090
```release-note
NONE
```
> [workload]Avoid unnecessary allocation in HasAllChecks

- pkg/util/slices/slices.go
/kind cleanup
Avoid unnecessary allocation in CmpNoOrde
Fixes #
```release-note
NONE
```
> [slices] Avoid unnecessary allocation in CmpNoOrder

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/scheduler/scheduler.go
- pkg/util/maps/maps.go
- pkg/util/maps/maps_test.go
- pkg/workload/workload.go
- test/integration/controller/jobs/job/job_controller_test.go
/kind cleanup
Fixes #1047
PR made according to the [discussion](https://github.com/kubernetes-sigs/kueue/pull/1141#discussion_r1332910569) 
```
NONE
```
> Replace utils/maps::Clone function with std maps::Clone function after it was introduced in go 1.21

- site/content/en/docs/tasks/_index.md
- site/content/en/docs/tasks/monitor_pending_workloads.md
Fixes #1159
```release-note
added a page that describes monitoring pending workloads
```
> [DOC] Queue visibility documentation

- pkg/controller/core/workload_controller.go
- pkg/workload/workload.go
- test/integration/controller/core/workload_controller_test.go
/kind feature
Finish the workload with failure if any of its admission checks is marked as Rejected.
Relates to  #1136 
```release-note
Finish the workload with failure if any of its admission checks is marked as Rejected.
```
> [workload] Finish with failure on admission check rejection.

- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/job/job_webhook_test.go
- pkg/controller/jobs/rayjob/rayjob_webhook_test.go
/kind cleanup
When validating CRDs, we should use apivalidation.ValidateImmutableField instead of field.Forbidden for simplicity.
Replaced field.Forbidden with apivalidation.ValidateImmutableField if possible.
Fixes #1175 
```release-note
NONE
```
> Use apivalidation.ValidateImmutableField instead of field.Forbidden

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller_test.go
/kind bug
* In the case of a finished job, it should be finalized before updating the Workload status, because if any errors are occurring during finalization, it will never be reached by reconciler again if workload has a 'Finished' condition.
Fixes #
```release-note
```
> Fix job finalization logic in generic reconciler

- keps/1145-additional-labels/README.md
- keps/1145-additional-labels/kep.yaml
/kind feature
Allows to set additional labels, annotations, tolerations and node selectors on Workload's pods based on AdmissionCheck needs.
Fixes #1145 
```release-note
NONE
```
> KEP-1145: Additional labels, annotations, tolerations and node selector for AdmissionChecks

- pkg/controller/jobs/rayjob/rayjob_controller.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
/kind bug
Fixes https://github.com/kubernetes-sigs/kueue/issues/1146
Fixes https://github.com/kubernetes-sigs/kueue/issues/1150
```release-note
Fix resuming of RayJob after preempted.
```
> Fix rayjob will not resume after preempted

- pkg/controller/jobs/rayjob/rayjob_controller.go
- test/integration/controller/rayjob/rayjob_controller_test.go
Cherry pick of #1156 on release-0.4.
#1156: Fix rayjob will not resume after preempted
```release-note
Fix resuming of RayJob after preempted.
```
> Automated cherry pick of #1156: Fix rayjob will not resume after preempted

- charts/kueue/values.yaml
/kind bug
We should enable JobSet integration by default when deploying the kueue using Helm.
Fixes #
```release-note
Helm: Enable the JobSet integration by default
```
> Enable jobset integration by default when deploying the kueue using Helm

- pkg/controller/core/workload_controller.go
- pkg/queue/manager.go
- pkg/workload/resources.go
- test/integration/scheduler/workload_controller_test.go
/kind bug
Workload requests need to be adjusted based on LimitRanges, PodOverhead and limits.
When a LocalQueue is added after Workloads for it have been created, we were not adjusting the requests.
Fixes #
```release-note
Adjust resources (based on LimitRanges, PodOverhead and resource limits) on existing Workloads when a LocalQueue is created
```
> Fix: Adjust resources when the LocalQueue is created after workloads

- cmd/experimental/podtaintstolerations/controller/pod_jobs.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
To improve naming consistency in the codebase. 
Fixes #
Changes:
1. podSetInfos -> podSetsInfo
2. nodeSelectors -> podSetsInfo (in interface.go)
```release-note
NONE
```
> Improve naming consistency for podSetsInfo

- config/components/webhook/manifests.yaml
- pkg/util/testing/wrappers.go
- pkg/webhooks/admissioncheck_webhook.go
- pkg/webhooks/admissioncheck_webhook_test.go
- pkg/webhooks/webhooks.go
- test/e2e/e2e_test.go
- test/integration/controller/core/admissioncheck_controller_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/localqueue_controller_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/webhook/admissioncheck_test.go
/kind feature
Add admission check webhook. 
Fixes #1218
```release-note
Validate AdmissionCheck objects
```
> [webhook] Add admission check webhook

- charts/kueue/templates/manager/manager.yaml
- config/default/manager_config_patch.yaml
- config/dev/manager_config_patch.yaml
- site/content/en/docs/installation/_index.md
/kind cleanup
The config mountPath is /controller_manager_config.yaml, yet it has been given to the manager in a command line arg without a path, simply trusting the current working directory to be the root.
When debugging kueue via a buildpack built container, the manager resides in another folder and the config isn't found without changing the --config arg. The command line arg could always simply specify the exact, matching path to the file.
This adds the path to the various instances of --config usage in the project.
Fixes #
This imposes no change to functionality anywhere, but makes setting up debugging easier.
```release-note
NONE
```
> fix config arg path to always match configmap mount path

- pkg/util/testing/wrappers.go
- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
/kind bug
Validate PodSetUpdates field to avoid errors during workload admission
Fixes #1187
```release-note
validate PodSetUpdates field of workload
```
> Validating admissionchecks

- charts/kueue/templates/webhook/webhook.yaml
/kind feature
* Now helm will use namespace selector from the kueue configuration for the pod webhook.
* If no namespace selector is set in the configuration, default selector will be used.
* If pod integration is disabled, pod related webhooks will have failurePolicy set to Ignore.
Related issue: #976 
```release-note
NONE
```
> Update webhook template for pod integration

- site/content/en/docs/concepts/cluster_queue.md
update document for FlavorFungibility
For issue #582
```release-note
```
> update document for FlavorFungibility

- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/workload_controller.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/controller/core/clusterqueue_controller_test.go
- test/integration/controller/core/localqueue_controller_test.go
- test/util/util.go
/kind bug
Drop the workloads quota reservation if it's not Admitted and the target ClusterQueue is deleted.
Fixes #1253 
```release-note
NONE
```
> [workload] Drop Quota Reservation on cluster queue deletion.

- test/integration/controller/jobs/pod/suite_test.go
/kind bug
Setup the core indexes in the pod integration tests.
Fixes #1258
```release-note
NONE
```
> [test/integration/pod] Setup all indexes.

- test/integration/scheduler/scheduler_test.go
- test/util/util.go
/kind cleanup
To increase coverage of the dynamic reclaiming behavior
Fixes #1216
```release-note
```
> Add integration test for resuming a partially completed job

- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
/kind feature
Fixes #1215
```release-note
Allow decrease reclaimable pods to 0 for suspended job
```
> Allow decrease reclaimable pods to 0 for suspended job

- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/controller/jobs/kubeflow/kubeflowjob.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
/kind cleanup
Avoid use of Consistently in integration tests
Fixes #1234
```release-note
NONE
```
> Avoid use of Consistently in integration tests

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/webhook/workload_test.go
/kind feature
Fixes #1038
```release-note
Jobs preserve their position in the queue if the number of pods change before being admitted
```
> Update workload when job changes before admission

- charts/kueue/templates/webhook/webhook.yaml
/kind bug
Parentheses around the optional dict as a mean of null-safety
Fixes #1315
```release-note
None
```
> [Helm] Error using default controllerManagerConfigYaml

- keps/487-kubectl-plugin/README.md
- keps/487-kubectl-plugin/kep.yaml
Problem: It is challenging to see all details of a Job/Workload Solution: Provide a dual command-line tool and plugin to expose this information.
KEP!
/kind feature
It's not currently possible to (easily) see information about jobs or queues.
Part of #487 
```release-note
NONE
```
> kep: issue 487 support for kubectl plugin

- charts/kueue/templates/_helpers.tpl
- charts/kueue/templates/manager/manager.yaml
- charts/kueue/values.yaml
/kind cleanup
Let Helm chart specify which FeatureGates should be used
Fixes #1230
```release-note
Allow configuring featureGates on helm charts.
```
> specify FeatureGates in helm chart

- pkg/scheduler/scheduler.go
- test/integration/scheduler/scheduler_test.go
/kind bug
Wipe the last assignment information when issuing preemptions, as the scheduler should retry all flavors in the next admission attempt.
Also ensure that the integration test checks for the admission flavor, not just that a workload was preempted.
Fixes #
```release-note
Fixed fungiblity policy `whenCanPreempt: Preempt`. The admission should happen in the flavor for which preemptions were issued.
```
> When preempting in a flavor, retry all flavors in the next iteration

- keps/168-2-pending-workloads-visibility/README.md
- keps/168-2-pending-workloads-visibility/kep.yaml
/kind feature
Introduces a new API to expose information about the position of pending workloads in both ClusterQueue and LocalQueue.
Part of #168 
```release-note
NONE
```
> KEP-168-2: Pending workloads visibility

- test/integration/controller/jobs/kubeflow/kubeflowjob.go
- test/integration/controller/jobs/mxjob/mxjob_controller_test.go
- test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/controller/jobs/tfjob/tfjob_controller_test.go
- test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
/kind cleanup
In this PR we make all kubeflows's tests common
Fixes #1119
```release-note
None
```
> Commonize KubeflowJob Tests

- pkg/controller/jobframework/reconciler.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
If the job is deleting, perform finalize processes. This can prevent the deletion of finalizers in the plain pod integration.
Fixes #1339 
Fixes #1340 
```release-note
Fix a bug that plain pods managed by kueue will remain a terminating condition forever.
```
> Perform finalize processes when job is deleting

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/util/testing/util.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind feature
Part of #1353
```release-note
Support for retry of provisioning request
```
> Retry provisioning request

- keps/1136-provisioning-request-support/README.md
/kind feature
Part of https://github.com/kubernetes-sigs/kueue/issues/1353
```release-note
NONE
```
> Retry for ProvisioningRequests KEP

- keps/1284-cluster-queue-stop/README.md
- keps/1284-cluster-queue-stop/kep.yaml
A mechanism to stop a ClusterQueue
Relates to #1284
```release-note
NONE
```
> [KEP] A mechanism to stop a ClusterQueue

- pkg/config/config.go
/kind cleanup
As we discussed in [this](https://github.com/kubernetes-sigs/kueue/pull/1356#discussion_r1403672040), it would be better to consistently use the `DeepEqual` function of the `equality` pkg instead of `reflect` pkg's one.
Fixes #
```release-note
NONE
```
> Use equality pkg instead of reflect pkg for the DeepEqual function

- pkg/controller/jobframework/errors.go
- pkg/controller/jobframework/indexer.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- pkg/util/testing/core.go
- pkg/util/testing/wrappers.go
- pkg/util/testingjobs/pod/wrappers.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pod/suite_test.go
- test/util/util.go
/kind feature
* Introduce new ComposableJob interface for jobs which has to be composed of different API objects.
* Add ComposableJob implementation for pod groups.
* Add webhook checks for pod group labels and annotations.
```release-note
Add support for groups of plain Pods.
```
> Add support for pod groups

- apis/visibility/v1alpha1/openapi/zz_generated.openapi.go
- apis/visibility/v1alpha1/types.go
- client-go/applyconfiguration/visibility/v1alpha1/pendingworkload.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/visibility/api/rest/pending_workload_CQ.go
- pkg/visibility/api/rest/pending_workload_CQ_test.go
- test/e2e/e2e_test.go
/kind feature
This PR continues the development of [KEP#168-2](https://github.com/kubernetes-sigs/kueue/pull/1300)
```release-note
Extend the information returned for the pending workloads in cluster queue, that is used to determine the workload position, including the workload position itself.
```
> Extend visibility ClusterQueue PendingWorkloads endpoint

- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/queue/cluster_queue_best_effort_fifo_test.go
- pkg/queue/cluster_queue_impl.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/integration/scheduler/scheduler_test.go
/kind bug
This PR fixes 3 problems:
- The AllocatableResourceGeneration for a ClusterQueue was changing for unrelated status updates (Thanks to @KunWuLuan for this fix)
- Needed to requeue immediately if there are pending flavors to try.
- The indexes for the lastattempt were accumulating across scheduling attempts.
Fixes #1344
This supersedes #1356.
I want to add more tests before merging.
```release-note
Fix fungibility policy `Preempt` where it was not able to utilize the next flavor if preemption was not possible.
```
> Fix fungibility: Try next flavor if can't preempt on first

- CHANGELOG/CHANGELOG-0.5.md
- README.md
- charts/kueue/Chart.yaml
Update versions in yamls and docs
Part of #1368
```release-note
NONE
```
> Prepare release for v0.5.1

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- pkg/util/testingjobs/pod/wrappers.go
/kind bug
* Add deletingWorkload for the Stop method of the JobWithCustomStop interface.
* Change Stop method for the pod controller to delete even suspended pods if workload is being deleted.
* Change pods in group finalization for the case of workload deletion. Now all pods in the group will be finalized right after the pod group has been stopped.
* Add new unit tests for the pod controller and webhook.
```release-note
NONE
```
> Improve pod/wl cleanup for pod groups

- keps/976-plain-pods/README.md
Part of #976
```release-note
NONE
```
> KEP update: Allow replacement pods in groups of pods

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
* Update equivalentToWorkload to consider workload equivalent to the pod group if any of the "first" roles in the group are absent from the cluster.
* Example of the case in which the previous implementation was failing: https://github.com/kubernetes-sigs/kueue/pull/1319#discussion_r1404471430.
Related to #976
```release-note
NONE
```
> Fix the equivalentToWorkload method for pod groups

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testingjobs/mxjob/wrappers.go
/kind bug
* Workload is not being recreated, when the job is finished.
* Job will be stopped if it's not suspended and matching workload is not found. This action doesn't depend on the job.Finished condition anymore.
```release-note
NONE
```
> Update wl/job handling for the case, when the job is finished

- site/content/en/docs/reference/kueue.v1beta1.md
/kind cleanup
Regenerate the API doc after the addition of `wl.spec.active`.
Relate To  #1091
```release-note
NONE
```
> Suspend a running Job without requeueing - API doc update

- Dockerfile
- Makefile
/kind feature
This PR parametrize's the CGO_ENABLED argument for the Kueue image build in both the dockerfile and makefile. This will make it easier for other consumers of Kueue to customize the image as needed.
Fixes #1382
```release-note
Make the image build setting CGO_ENABLED configurable
```
> Parametrize CGO_ENABLED argument for container build

- keps/168-2-pending-workloads-visibility/README.md
/kind cleanup
The single workload endpoint is redundant, as we can achieve the same goals using LocalQueue endpoint. We'd like to narrow the scope of KEP#168-2 and leave it as a potential follow-up feature.
```release-note
NONE
```
> Remove the proposal of the single workload endpoint from KEP#168-2

- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
/kind flake
Due to the multistage stop of batch/job the job is suspend with an unrestored parallelism for a brief period of time. Extend the `Eventually` to cover that time also.
Fixes #1369
```release-note
NONE
```
> [flaky][int/job] Fix flaky partial admission suspend check.

- pkg/visibility/api/rest/pending_workloads_cq_test.go
- pkg/visibility/api/rest/pending_workloads_lq_test.go
- pkg/visibility/api/rest/utils.go
- test/e2e/e2e_test.go
/kind feature
This PR continues the development of [KEP#168-2](https://github.com/kubernetes-sigs/kueue/pull/1300)
```release-note
Visibility.PendingWorkload object has the metav1.CreationTimestamp field filled with the value of corresponding kueue.Workload
```
> Fill the CreationTimestamp field in the visibility.PendingWorkload object

- site/content/en/docs/installation/_index.md
- site/content/en/docs/tasks/monitor_pending_workloads/_index.md
- site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_in_status.md
- site/content/en/docs/tasks/monitor_pending_workloads/pending_workloads_on_demand.md
This PR continues the development of [KEP#168-2](https://github.com/kubernetes-sigs/kueue/pull/1300)
```release-note
Add documentation for Kueue visibility on-demand
```
> Add documentation for Kueue visibility on-demand

- charts/kueue/templates/rbac/pending_workloads_lq_viewer_role.yaml
- config/components/rbac/pending_workloads_lq_viewer_role.yaml
/kind bug
It fixes RBAC so users with `kueue-batch-user-role` have access to pending workloads in namespaces they are bound to. Before that admins needed to create a separate `Role` for each namespace.
```release-note
RBAC to visibility into Local Queues is fixed
```
> Fix RBAC to visibility into Local Queues

- keps/976-plain-pods/README.md
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/jobset/jobset_controller_test.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/util/util.go
/kind feature
* A pod group is considered finished now if there are no running or pending pods, and at least one terminated pod has `retriable-in-group=false` annotation.
* Now pod groups support dynamically reclaiming quota. The quota from succeeded pods will always be released.
* The check of pod group total count in ConstructComposableWorkload was incorrect before. Failed pods should be filtered before checking if actual group total count is equal to the group total count annotation.
Related issue: #976 
```release-note
NONE
```
> Add retriable-in-group annotation handling for pod groups

- pkg/visibility/api/rest/pending_workloads_cq.go
- pkg/visibility/api/rest/pending_workloads_cq_test.go
- pkg/visibility/api/rest/pending_workloads_lq.go
- pkg/visibility/api/rest/pending_workloads_lq_test.go
- pkg/visibility/api/rest/test_utils.go
/kind bug
Method `cmpopts.EquateErrors()` returned diff due to different addresses of errors.
```release-note
Visibility endpoints return 404 code for non-existent queues
```
> Return 404 for non-existent queues for the visibility endpoints

- pkg/features/kube_features.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind feature
Allow to disable workload priority sorting in a cohort
Related to #1283
```release-note
The priority sorting within the cohort could be disabled by setting --prioritySortingWithinCohort to false
```
> Add feature gate for priorities sorting in a cohort

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testingjobs/pod/wrappers.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
* Move group metadata validation from `constructGroupPodSets`
method into a separate `validatePodGroupMetadata` method.
* Add `cleanupExcessPods` method which will delete and
finalize pods created last if the number of non-failed
pods is greater than group-total-count annotation.
* Add integration/unit tests for excess pods deletion.
```release-note
NONE
```
> Excess pods in group deletion

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/util/testing/client.go
/kind feature
An event associated to a Workload, for when the ProvisioningRequest is created, including it's name. Useful for debugging problems.
Fixes #1393
```release-note
NONE
```
> Add an event for when a ProvisioningRequest is created for a Workload

- pkg/constants/constants.go
- pkg/controller/core/core.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/client.go
/kind feature
Record  different events when QuotaReservation and Admition take place.
Fixes #1392 
```release-note
Added event for QuotaReserved and fixed event for Admitted to trigger when admission checks complete
```
> Record events when QuotaReservation and Admition take place.

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind bug
Fixes #1485
```release-note
Add Missing RBAC on integration finalizers sub-resources
```
> Add required RBAC on integration finalizers sub-resources

- .github/ISSUE_TEMPLATE/NEW_RELEASE.md
- .github/workflows/openvex.yaml
`#SecuritySlam`
/kind cleanup
This PR is a follow-up to #1465.
Instead of automatically running the openvex action whenever a new tag is created, this PR makes the openvex action require a manual trigger. 
The intention is to better integrate the action into the existing release workflow. To that end, a task was added to the new release template to run this task AFTER the release has been cut (similar to the approach in #1467). The action will then generate the openvex data and upload it to the release. 
The upload step is new in this PR.
This commit is part of the December 2023 Security Slam.
```release-note
NONE
```
/sig release
/assign @ArangoGutierrez
> Makes openvex action manual trigger only

- test/e2e/multikueue/e2e_test.go
/kind bug
/kind flake
Check only the created workload spec in "Cluster kubeconfig propagation" test.
Fixes #1490 
```release-note
NONE
```
> [e2e/multikueue] Check only the created workload spec.

- pkg/util/testingjobs/job/wrappers.go
- test/e2e/singlecluster/e2e_test.go
/kind bug
/kind flake
Fixes #1482
Alternative fix is to set very high priority for the blocking job, but I think it does not capture the intention that well.
I reproduced the failure by looping the test locally, it failed 2/1000. After the proposed fix it passed 1000 repeats.
```release-note
NONE
```
> Fix the flaky e2e test for pending workloads

- test/e2e/singlecluster/e2e_test.go
- test/util/constants.go
- test/util/e2e.go
/kind cleanup
Increase startup timeout to 3m (see https://ahmet.im/blog/kubernetes-secret-volumes-delay/ for rationale).
Downgraded some waits to simple Timeout, as they don't involve more than one controller.
Fixes #1372
```release-note
NONE
```
> Increase startup timeout

- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/scheduler_test.go
/kind cleanup
To make the logic simpler, and easier to modify in https://github.com/kubernetes-sigs/kueue/pull/1397.
Part of #1337
The only exported API where we use `assignment.TotalBorrow` is `Borrows()` used by scheduler:
```golang
func (a *Assignment) Borrows() bool {
return len(a.TotalBorrow) > 0
}
```
So, it is much simpler to just keep a bool "borrowing" instead, it will also have better memory usage.
```release-note
NONE
```
> Simplify flavorassigner to only return bool if borrowing is required

- go.mod
- go.sum
/kind bug
This PR upgrades cert-controller to v0.10.1 so it includes open-policy-agent/cert-controller#166.
Fixes #1445
I've successfully tested webhooks are served in non-leading replicas, and admission requests fail over the other replicas when deleting the leading one.
```release-note
Webhooks are served in non-leading replicas
```
> Fix webhooks serving in non-leading replicas

- go.mod
- go.sum
Cherry pick of #1509 on release-0.5.
#1509: Fix webhooks serving in non-leading replicas
```release-note
Webhooks are served in non-leading replicas
```
> Automated cherry pick of #1509: Fix webhooks serving in non-leading replicas

- charts/kueue/templates/visibility/kustomization.yaml
- hack/update-helm.sh
/kind cleanup
remove charts/kueue/templates/visibility/kustomization.yaml, and modify the [hack/update-helm.sh](https://github.com/kubernetes-sigs/kueue/blob/main/hack/update-helm.sh).
Fixes #1459
```release-note
NONE
```
> Remove charts/kueue/templates/visibility/kustomization.yaml

- pkg/controller/jobs/pod/pod_controller.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
* If pod is not found, it shouldn't be skipped, since there could be a dangling workload that should be finalized.
* Update `Skip` method for the pod controller to return false if the pod is not found.
* Add an integration test for the case when pods are finalized and deleted before the workload finalizer is removed.
Fixes #1450
The integration test could be replaced with a unit test for the sake of testing speed increase.
```release-note
NONE
```
> Update pod controller to reconcile not found pods

- pkg/controller/jobframework/reconciler.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
* If pod is not found, it shouldn't be skipped, since there could be a dangling workload that should be finalized.
* Add an integration test for the case when pod is finalized and deleted before the workload finalizer is removed.
Fixes #1450
```release-note
NONE
```
> Fix for JobWithSkip in case when job is not found

- pkg/scheduler/preemption/preemption.go
/kind bug
~Based on my understanding, even `borrowlingLimit` not nil, if `cq.cohort == nil`, we should still not consider the borrowingLimit in calculation. cc @alculquicondor is this a real bug or as designed?~
Just for explaination.
Fixes #
```release-note
None
```
> Add comments to explain special cases

- cmd/kueue/main.go
- pkg/cache/snapshot.go
- pkg/debugger/debugger.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/cluster_queue_interface.go
- pkg/queue/dumper.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/scheduler/logging.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind feature
Produces a dump of the cache into the logs at log level 5.
A dump of the cache and queues can be logged on demand using SIGUSR2, regardless of the log level.
Refactored some existing dump methods used for testing to use slices for better performance and simpler formatting.
Fixes #1438 #1437
```release-note
At log level 6, the usage of ClusterQueues and cohorts is included in logs.
The status of the internal cache and queues is also logged on demand when a SIGUSR2 is sent to kueue, regardless of the log level.
```
> Verbose logging of cache and queues

- Makefile
- cloudbuild.yaml
- hack/debugpod/Dockerfile
- hack/dump_cache.sh
/kind feature
- Configuration to build a debug image in the pipeline.
- A script to produce a dump of the cache into the kueue Pod logs
Fix #1437
```release-note
The image gcr.io/k8s-staging-kueue/debug:main, along with the script ./hack/dump_cache.sh can be used to trigger a dump of the internal cache into the logs.
```
> Debug image and cache dump script

- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
/kind flake
I added a dedicated finalizer to verify if the pod has an expected eviction status after the workload is evicted.
Please see the root cause: https://github.com/kubernetes-sigs/kueue/issues/1501#issuecomment-1878114456
Fixes #1501
```release-note
NONE
```
> Fix flaky test: add a dedicated finalizer to verify the pod's status after the workload is evicted

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
/kind bug
To fix handling of preemption within a cohort when there is no borrowingLimit. In that case
during preemption the available resources coming from borrowing were calculated as if borrowingLimit=0.
Fixes #
```release-note
Fix handling of preemption within a cohort when there is no borrowingLimit. In that case,
during preemption, the permitted resources to borrow were calculated as if borrowingLimit=0, instead of unlimited.
As a consequence, when using `reclaimWithinCohort`, it was possible that a workload, scheduled to ClusterQueue with no borrowingLimit, would preempt more workloads than needed, even though it could fit by borrowing.
```
> Fix preemption within cohort when there is no borrowingLimit

- apis/config/v1beta1/configuration_types.go
- apis/kueue/v1beta1/admissioncheck_types.go
- apis/kueue/v1beta1/clusterqueue_types.go
- apis/kueue/v1beta1/localqueue_types.go
- apis/kueue/v1beta1/provisioningrequestconfig_types.go
- apis/kueue/v1beta1/resourceflavor_types.go
- apis/kueue/v1beta1/workloadpriorityclass_types.go
- pkg/controller/core/admissioncheck_controller.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/localqueue_controller.go
- pkg/controller/core/resourceflavor_controller.go
- pkg/controller/core/workload_controller.go
- pkg/util/cert/cert.go
- pkg/visibility/server.go
- test/e2e/singlecluster/suite_test.go
- test/integration/controller/admissionchecks/provisioning/suite_test.go
- test/integration/controller/core/suite_test.go
- test/integration/controller/jobs/job/suite_test.go
- test/integration/controller/jobs/jobset/suite_test.go
- test/integration/controller/jobs/mpijob/suite_test.go
- test/integration/controller/jobs/pod/suite_test.go
- test/integration/controller/jobs/pytorchjob/suite_test.go
- test/integration/controller/jobs/rayjob/suite_test.go
- test/integration/controller/jobs/tfjob/suite_test.go
- test/integration/controller/jobs/xgboostjob/suite_test.go
- test/integration/multikueue/suite_test.go
- test/integration/scheduler/podsready/suite_test.go
- test/integration/scheduler/suite_test.go
/kind cleanup
This PR aligns the kubebuilder markers to use a leading space comment consistently.
That's useful to get rid of IDE warnings and automated formatting discrepancies.
```release-note
NONE
```
> Align all kubebuilder markers with leading space

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
Cherry pick of #1561 on release-0.5.
#1561: Fix the borrowing while preemption when no borrowingLimit
```release-note
```
Note: I had a conflict with https://github.com/kubernetes-sigs/kueue/commit/7aff0611ea52163b32b73d466bc621804459d8ae, but the other PR didn't contribute logic difference, so I resolved the conflict by using the new logic for the `workloadFits` function.
> Automated cherry pick of #1561: Fix the borrowing while preemption when no borrowingLimit

- pkg/controller/jobframework/indexer.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/workload_names.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/pod/event_handlers.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/util/testing/wrappers.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
* Add new method Run for the ComposableJob interface. Same as RunWithPodSetsInfo, but unsuspends all members of the composable job.
* And new job event handler for the generic reconciler.
* Implement Run for the pod groups.
```release-note
NONE
```
> Pod group concurrent reconciles

- test/integration/multikueue/multikueue_test.go
/kind bug
/kind flake
Check only the created workload spec in the `Multikueue Suite: [It] Multikueue when Using multiple clusters Cluster kubeconfig propagation ` integration tests.
Fixes #1540
```release-note
None
```
> [integration/multikueue] Check only the created workload spec.

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testing/wrappers.go
- pkg/workload/workload.go
/kind bug
Workload will be finalized if it has a Finished condition and no OwnerReferences.
Fixes #1450
```release-note
NONE
```
> Fix: remove workload finalizer if workload is finished

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testingjobs/mxjob/wrappers.go
/kind bug
- Do not recreate workload for a finished Job
- Ensure finalization of job when workload is finished
Ref #1383 and #1450
```release-note
Avoid recreating a Workload for a finished Job and finalize a job when the workload is declared finished.
```
> Skip recreating a workload for a finished job

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/errors.go
- pkg/controller/jobframework/events.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/pod/pod_controller.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
* Added workload finished event for the job reconciler.
* Added event reason constants for the job reconciler.
Fixes #1387
```release-note
NONE
```
> Add workload finished event

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/workload/workload.go
- test/integration/controller/core/workload_controller_test.go
/kind bug
Allow the workload reconciler to trigger the eviction of a workload that has `Rejected` admission checks and is `Admitted`, before making it as `Finished`.
Fixes #
```release-note
Trigger an eviction for an admitted Job after an admission check changed state to Rejected.
```
> Trigger the workloads eviction on admission check rejection.

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
/kind bug
If gated Pods are deleted before a Workload is created, they should be finalized.
This covers a scenario where a group was never complete and the user decides to delete the Pods.
Fixes #
No release note because this is an unreleased feature.
```release-note
NONE
```
> Finalize deleted gated Pods from groups without a Workload

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
/kind bug
The combination of #1524 and #1502 causes `p.pod` to be empty, leading to a nonexistent owner key. 
This could lead to infinite reconcile attempts for this key, and an unfinalized Workload if previous reconcile attempts failed to remove the finalizer.
Fixes #
Fixes unreleased feature.
```release-note
NONE
```
> Use constant gvk for pod owner index

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/reconciler.go
- pkg/util/testing/wrappers.go
- pkg/workload/workload.go
/kind bug
Cherry-pick of #1523 
Fixes #
```release-note
NONE
```
> [release-0.5] Fix: remove workload finalizer if workload is finished

- pkg/scheduler/scheduler_test.go
/kind bug
/kind flake
Fixes #1578
The test was added recently in https://github.com/kubernetes-sigs/kueue/pull/1576 to cover the logic modified in https://github.com/kubernetes-sigs/kueue/pull/1399.
The test used to flake as the order of considered workloads in a single scheduling cycle could be (A,B) or (B, A). The intention of the test is to cover scenario when (A,B). Thus adding 2*time.Second to the creation time of B.
Also, make sure all timestamps refer to the same `now`. Otherwise, it would be technically possible that `time.Now().Add(time.Second) > time.Now().Add(2*time.Second)` (though it would be super unlikely).
```release-note
NONE
```
> Fix the flake preemption while borrowing unit test

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
- pkg/util/equality/podset.go
- pkg/util/equality/podset_test.go
/kind cleanup
Fixes #1264
```release-note
Adding toleration to a job leads to update workload
```
> Adding toleration to the job doesn't trigger workload change

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
/kind bug
/kind flake
Fixes #1558
The root cause of the issue is that the returned map by `activeOrLastPRForChecks` could contain
the pr-1, instead of pr-2. This could happen when on the list of PRs passed to the function
we have [pr-2, pr-1]. I wanted to test `TestReconcile` but it appears that the order of PRs returned by the
List is always alphabetical in unit tests, even though it does not need to be from the production client.
The new unit test fails on the main branch consistently.
I assume it also fixes #1401, but will double check.
```release-note
Fix the synchronization of the admission check state based on the second provisioning request
```
> Fix syncing of the second provisioning request

- Makefile
/kind cleanup
/kind testing
Update Kind to 0.20.0 so we can pick up 1.29.0 images.
Drop deprecated kubernetes versions.
Fixes #
I am noticing something odd in Kind 0.20.0 around cert rotation so I think we should test the CI pretty well here once 1.29 test-infra PR merges.
See https://github.com/kubernetes-sigs/jobset/issues/357 for some discussion on this.
```release-note
NONE
```
> update kind to 0.20.0

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/jobframework/reconciler.go
/kind cleanup
I replaced the no need `Eventf()` function with `Event()`.
Fixes #
```release-note
NONE
```
> Replace the no need Eventf() with Event()

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/util/testing/util.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
Cherry pick of #1351 on release-0.5.
#1351: Support retry for provisioning requests
```release-note
Support for retry of provisioning request.
```
It includes the fix PR https://github.com/kubernetes-sigs/kueue/pull/1585 (except for the commit https://github.com/kubernetes-sigs/kueue/pull/1585/commits/916bddb28c9bf4c2811d7a3aa78e0e4e2ab424ab, because on the release-0.5 branch `NewController` does not return `err`).
> Automated cherry pick of #1351: Support retry for provisioning requests

- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- test/e2e/config/controller_manager_config.yaml
/kind feature
Increase the number of reconcilers for Pod in the default configuration and E2E tests.
Also doing the same for Workload object, which are expected to be a significant number of objects.
Fixes #
```release-note
Increase the default number of reconcilers for Pod and Workload objects to 5, each.
```
> Increase reconcilers for Pod

- site/content/en/docs/concepts/cluster_queue.md
- site/content/en/docs/installation/_index.md
Fixes #1283
```release-note
None
```
> Add documentation about PrioritySortingWithinCohort feature

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/pod/event_handlers.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
Simplifies the factory for genericJobReconciler.
The Pod integration no longer uses the genericJobReconciler, as it behaves significantly different.
Fixes #
I will use this new PodReconciler to fix #1593
```release-note
NONE
```
> Simplify generic job reconciler factory

- CHANGELOG/CHANGELOG-0.5.md
- README.md
- charts/kueue/Chart.yaml
- site/config.toml
Cherry pick of #1613 on website.
#1613: Update latest version to v0.5.2
```release-note
```
> Automated cherry pick of #1613: Update latest version to v0.5.2

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
/kind bug
Fixes #1605
I tested this in a loop and already >2500 repeats passed, which makes me confident the test is fixed.
A potential drawback scenario is when the check is flipped to Ready, but the workload awaits long (>10min) for other checks, if in the meantime the ProvReq is manually deleted then it will not be recreated. As a consequence the nodes might be collected by CA (Cluster Autoscaler) before the workload is admitted. Not sure we want to support the scenario.
```release-note
Do not (re)create ProvReq is the state of admission check is Ready
```
> Do not (re)create ProvReq is the state of admission check is Ready

- pkg/controller/jobs/pod/event_handlers.go
- pkg/controller/jobs/pod/expectations.go
- pkg/controller/jobs/pod/expectations_test.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
/kind bug
- After cleaning up pods, await to observe them in the event handlers before cleaning up more pods.
- When sorting pods for clean up, prefer the ones that are still gated or have lost their finalizer.
This prevents unnecessary cleanups in two scenarios:
- The user creates an excess pod when the group just was started. Previously, the reconciler might not have observed the pods that it ungated, deleting one of these pods.
- The user creates two replacement pods to fill up a Failed Pod. Previously, the reconciler might delete one the Pods in the first reconcile, and the other one in the second reconcile.
Fixes #1593
Adding parallelism simplified handling of expectations when there are failures. But I extracted the changes specific to parallelism into a separate PR #1632
Unreleased …
> Do not cleanup excess pods when awaiting to observe previous clean ups

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
Cherry pick of #1617 on release-0.5.
#1617: Do not (re)create ProvReq is the state of admission check is
```release-note
```
> Automated cherry pick of #1617: Do not (re)create ProvReq is the state of admission check is

- pkg/scheduler/flavorassigner/flavorassigner.go
/kind bug
Kueue is crashing currently when the log is at level 6.
This is the error log: 
```
goroutine 481 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x175e3ae?})
/go/pkg/mod/k8s.io/apimachinery@v0.28.6/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x22b8780?, 0x3fa68e0?})
/usr/local/go/src/runtime/panic.go:914 +0x21f
sigs.k8s.io/kueue/pkg/scheduler/flavorassigner.AssignFlavors({{0x2a96818?, 0xc000a64360?}, 0x14?}, 0xc000f9bc00, 0x4?, 0xc0011541e0, {0x0, 0x0, 0xc001805880?})
/workspace/pkg/scheduler/flavorassigner/flavorassigner.go:245 +0x220
sigs.k8s.io/kueue/pkg/scheduler.(*Scheduler).getAssignments(0xc0007c6780, {{0x2a96818?, 0xc000a64360?}, 0xc000a64270?}, 0xc000f9bc00, 0xc000ebb838)
/workspace/pkg/scheduler/scheduler.go:382 +0xf5 …
```
> Fix kueue crashing when clearing outdated assignment on log level 6

- pkg/controller/core/admissioncheck_controller.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/core.go
- pkg/controller/core/leader_aware_reconciler.go
- pkg/controller/core/localqueue_controller.go
- pkg/controller/core/resourceflavor_controller.go
- pkg/controller/core/workload_controller.go
- test/e2e/config/kustomization.yaml
/kind feature
This PR enables multiple replicas of the Kueue deployment to serve the visibility extension API endpoint.
This is achieved by:
1.  Starting controllers that feed the queue manager unconditionally, with the addition of `controller.Options{NeedLeaderElection: ptr.To(false)}` as extra option to these controllers;
2. Skipping any actual reconciliation for these controllers, with the addition of `WithLeadingManager(mgr, r)`, which discards the reconciliation requests for non-leading replicas (still consuming the requests from the event queues), until one acquires the leader election lease if the leading replica has failed to renew it.
The scheduling decisions process is untouched and left to the responsibility of the leading replica, based on the state of its local queue manager. …
> Add HA support for the visibility API

- keps/976-plain-pods/README.md
/kind cleanup
To clarify the expected behavior. This is a follow up after the confusion discussed here: https://github.com/kubernetes-sigs/kueue/issues/1641. One might expect Kueue would re-create pods it deleted during preemption (so there is some asymmetry in handling of pod management).
Fixes #
We should follow up with a docs page about the feature, but until that we can refer users to the KEP.
```release-note
NONE
```
> Pod groups: add a note about not recreating pods deleted by kueue

- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/singlecluster/pod_test.go
/kind cleanup
To verify the feature works as expected and prevent regressions.
Fixes #
In order to verify the tests aren't flaky I let them run for 1h (until timeout) in a loop, and no errors.
```release-note
NONE
```
> Pod groups: e2e tests for diverse pods and preemption

- charts/kueue/templates/webhook/service.yaml
- charts/kueue/templates/webhook/webhook.yaml
- hack/update-helm.sh
/kind cleanup
Implement scripts to sync webhookConfigurations to helm charts and validate automatically.
Fixes #1461
```release-note
NONE
```
> [Helm]Add script to sync webhookConfigurations to helm charts automatically

- pkg/controller/core/leader_aware_reconciler.go
- test/integration/controller/core/suite_test.go
- test/integration/controller/jobs/job/suite_test.go
- test/integration/controller/jobs/jobset/suite_test.go
- test/integration/controller/jobs/mpijob/suite_test.go
- test/integration/controller/jobs/mxjob/suite_test.go
- test/integration/controller/jobs/paddlejob/suite_test.go
- test/integration/controller/jobs/pod/suite_test.go
- test/integration/controller/jobs/pytorchjob/suite_test.go
- test/integration/controller/jobs/rayjob/suite_test.go
- test/integration/controller/jobs/tfjob/suite_test.go
- test/integration/controller/jobs/xgboostjob/suite_test.go
- test/integration/framework/framework.go
- test/integration/multikueue/suite_test.go
- test/integration/scheduler/podsready/suite_test.go
- test/integration/scheduler/suite_test.go
- test/integration/webhook/suite_test.go
/kind cleanup
A quick follow-up on #1554 to incorporate #1598 as discussed here: https://github.com/kubernetes-sigs/kueue/pull/1554#discussion_r1448863168.
This avoids the duplication of the default leader election lease duration.
```release-note
NONE
```
> Use leader election defaulting to set up controllers HA

- pkg/webhooks/clusterqueue_webhook.go
- pkg/webhooks/clusterqueue_webhook_test.go
/kind bug
Prevent the cluster queue validation webhook from panicking for existing resources, whose `.spec.preemption.borrowWithinCohort` field haven't been defaulted yet.
Fixes #1669
```release-note
NONE
```
> Prevent cluster queue webhook from panicking for existing resources

- apis/kueue/v1alpha1/multikueue_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_multikueueclusters.yaml
- config/components/crd/bases/kueue.x-k8s.io_multikueueclusters.yaml
- keps/693-multikueue/README.md
- pkg/controller/admissionchecks/multikueue/indexer_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/testdata/worker1KubeConfig
- pkg/util/testing/wrappers.go
- test/e2e/multikueue/e2e_test.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Add Path location type for MultiKueue cluster KubeConfigs
Relates to #693
```release-note
Add Path location type for MultiKueue cluster KubeConfigs
```
> [multikueue] Add Path kubeConfig location type

- cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
- cmd/kueue/main.go
- hack/e2e-common.sh
- test/e2e/multikueue/suite_test.go
- test/e2e/singlecluster/suite_test.go
- test/util/e2e.go
/kind bug
To fix the flaky test.
To also let users wait for Kueue webhooks ready without the need for creating / deleting objects as in `KueueReadyForTesting`
Fixes #1658
Tested locally, trying to see what will happen on GH CI.
```release-note
NONE
```
> Fix Kueue startup by waiting for webhooks server using probes

- cmd/experimental/podtaintstolerations/test/e2e/suite_test.go
- cmd/kueue/main.go
- hack/e2e-test.sh
- test/e2e/suite_test.go
Cherry pick of #1676 on release-0.5.
#1676: Wait for webhooks server using probes
```release-note
```
I needed to resolve simple conflicts, because due to the test code being in different places in release-0.5 and main. On main we now have e2e-common.sh, and we have singlecluster and multicluster subfolders for tests.
> Automated cherry pick of #1676: Wait for webhooks server using probes

- pkg/controller/core/workload_controller.go
- test/integration/controller/core/clusterqueue_controller_test.go
This fixes #1555 and also adds an integration test as suggested in https://github.com/kubernetes-sigs/kueue/issues/1555#issuecomment-1912423532.
/kind bug
Fixes #1555
```release-note
Remove deleted pending workloads from the cache
```
> Remove deleted pending workloads from the cache so the visibility API results are correct

- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testing/client.go
- test/e2e/singlecluster/pod_test.go
- test/e2e/singlecluster/suite_test.go
- test/util/e2e.go
/kind cleanup
/kind bug
Solve two issues with events for pod groups:
1. the event indicating the a pod in pod group was emitted repeatedly, while the intention is to sent it once
2. the event was emitted only for the first pod in group, but because the Load function may return the pods in different order, we could get both pods covered with at least one event
This PR also adds e2e test to ensure the events are emitted per pod in the group.
Fixes #
Fix for unreleased feature
```release-note
NONE
```
> Fix emitting events for pods preempted by Kueue [pod groups]

- pkg/controller/core/workload_controller.go
- test/integration/controller/core/clusterqueue_controller_test.go
Cherry pick of #1679 on release-0.5.
#1679: Make sure pending workloads are removed from the cache
```release-note
Remove deleted pending workloads from the cache
```
> Automated cherry pick of #1679: Make sure pending workloads are removed from the cache

- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testing/client.go
/kind cleanup
Fixes #
this is a follow up after https://github.com/kubernetes-sigs/kueue/pull/1667#discussion_r1478882245
```release-note
NONE
```
> Cleanup unit test for events

- pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
- pkg/controller/admissionchecks/multikueue/controllers.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/util/testingjobs/jobset/wrappers.go
- test/e2e/multikueue/e2e_test.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Add live status updates for multikueue jobs
Relates to #693 
```release-note
Add live status updates for multikueue jobs
```
> [multikueue] Job live status update

- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/setup_test.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testing/wrappers.go
/kind cleanup
To simplify the testig code.
Fixes #
This is a follow up after https://github.com/kubernetes-sigs/kueue/pull/1683#discussion_r1479919704
```release-note
NONE
```
> Cleanup OwnerReference helper functions for tests

- pkg/controller/jobframework/events.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- test/e2e/singlecluster/pod_test.go
/kind feature
Fixes #
This is a follow up to https://github.com/kubernetes-sigs/kueue/pull/1667
```release-note
NONE
```
> Emit event when excess pods are deleted by Kueue [pod groups]

- keps/1282-pods-ready-requeue-strategy/README.md
- keps/1282-pods-ready-requeue-strategy/kep.yaml
Part-of: #1282
```release-note
NONE
```
> KEP: Add an exponential backoff mechanism to the requeueing strategy

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/util/testing/wrappers.go
- pkg/workload/workload.go
/kind bug
Skips assigning Finished workloads to the newly added cluster queues in cache.
Fixes #1654
```release-note
NONE
```
> [cache] Don't assign finished workloads to newly add CQs.

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
Removes `.spec.volumes` from pod role hash calculation. Allows for users to specify different volumes for pods in a pod group.
Fixes #1697 
```release-note
NONE
```
> Remove .spec.volumes from role hash for pods

- site/content/en/docs/tasks/run_jobsets.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_mpijobs.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_mxjobs.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_paddlejobs.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_pytorchjobs.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_tfjobs.md
- site/content/en/docs/tasks/run_kubeflow_jobs/run_xgboostjobs.md
Add one of the following kinds:
/kind cleanup
Related to this comment (https://github.com/kubernetes-sigs/kueue/pull/1678#pullrequestreview-1856548892), documentation for other custom job frameworks indicate that you need to enable the integration when it's already enabled by default according to this: https://github.com/kubernetes-sigs/kueue/blob/main/config/components/manager/controller_manager_config.yaml
Fixes #
```release-note
NONE
```
> [website] Custom Jobs integrations documentation cleanup

- site/content/en/docs/admission-check-controllers/provisioning.md
Update provisioning admission check controller public doc with supported CA version
Fixes #1665 
NONE
NONE
> [Site] Update provisioning admission check controller public doc with supported CA version

- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
/kind bug
/kind cleanup
Retry on remote workload creation failure and extend unit tests with a secondary worker client.
Relate to #693 
```release-note
NONE
```
> [multikueue] Retry on remote wl creation failure

- cmd/kueue/main.go
/kind bug
/kind flake
Check certificates readiness before checking if the webhook server is ready.
Fixes #1700
```release-note
NONE
```
> [kueue] Check certificates readiness before the webhook server.

- site/content/en/docs/tasks/run_plain_pods.md
- site/static/examples/pods-kueue/kueue-pod-group.yaml
Part of #976
```release-note
NONE
```
> Extend documentation on pod group support [pod groups]

- hack/e2e-common.sh
- hack/multikueue/manager-cluster.kind.yaml
- hack/multikueue/worker-cluster.kind.yaml
- test/e2e/multikueue/suite_test.go
- test/e2e/singlecluster/suite_test.go
- test/util/constants.go
- test/util/e2e.go
/kind flake
/kind bug
E2e extend startup interval.
Move availability checks in the test suite.
Improve k8s components logging in multikueue clusters.
Fixes #1700 
```release-note
NONE
```
> E2e extend startup interval

- keps/79-hierarchical-cohorts/README.md
- keps/79-hierarchical-cohorts/kep.yaml
/kind feature
Introduces a hierarchy among Cohorts via a new API object.
Part of #79
```release-note
NONE
```
> KEP-79: Hierarchical Cohorts

- pkg/controller/core/workload_controller.go
/kind cleanup
In the current approach, the workload controller always checks not ready workload even if the workload already has been inactive or had Evicted=true condition.
Fixes #
```release-note
NONE
```
> Avoid reconciles without any meaningful changes when the workload controller checks PodsReadyTimeout

- .github/ISSUE_TEMPLATE/NEW_RELEASE.md
- Makefile
- charts/kueue/Chart.yaml
- charts/kueue/values.yaml
- hack/e2e-test.sh
- hack/multikueue-e2e-test.sh
/kind cleanup
Add a make rule to prepare a branch for release: update version in README.md, site, kustomize and chart.
To simplify the process, I decided that from now on, the chart in the main branch will use the tag for the latest released version.
Fixes #
```release-note
NONE
```
> Add make rule to prepare branch for release

- CHANGELOG/CHANGELOG-0.6.md
- Makefile
- README.md
- SECURITY-INSIGHTS.yaml
- charts/kueue/Chart.yaml
- site/config.toml
Part of #1729
```release-note
NONE
```
> Update latest release to v0.6.0

- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
/kind cleanup
Add a FlavorAssigner struct to hold unchanging parameters and reduce the number of arguments passed to multiple functions.
Also doing some variable name changes.
Fixes #1420
```release-note
NONE
```
> Refactor flavorassigner to reduce number of passed arguments

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
Removes fields that are not relevant to queueing or autoscaling from role hash calculation.
In particular, users of pod groups might have labels to identify a particular instance within a group.
In general, Pod labels don't have an influence in kueue or in cluster-autoscaler, so the easiest solution is to remove labels from hash calculations.
We can add pod labels or other fields back in a case-by-case fashion, if we identify any that might lead to different autoscaling behavior.
Fixes #
```release-note
Exclude Pod labels, preemptionPolicy and container images when determining whether pods in a pod group have the same shape.
```
> Exclude labels, image, preemptionPolicy from pod role hash calculation

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
This is a cherry-pick of #1758
Fixes #
```release-note
Exclude Pod labels, preemptionPolicy and container images when determining whether pods in a pod group have the same shape.
```
> Automated cherry pick of #1723: Exclude labels, image, preemptionPolicy from pod role hash calculation

- charts/kueue/templates/_helpers.tpl
- charts/kueue/templates/visibility/apiservice.yaml
- charts/kueue/templates/visibility/role_binding.yaml
- charts/kueue/templates/visibility/service.yaml
- charts/kueue/values.yaml
- config/alpha-enabled/kustomization.yaml
- config/default/kustomization.yaml
- config/visibility/kustomization.yaml
- hack/update-helm.sh
- test/e2e/config/kustomization.yaml
- test/e2e/config_1_26/kustomization.yaml
/kind bug
Don't deploy visibility by default to avoid 
```
E0216 16:57:43.448953  907490 memcache.go:287] couldn't get resource list for visibility.kueue.x-k8s.io/v1alpha1: the server is currently unable to handle the request
E0216 16:57:43.451994  907490 memcache.go:121] couldn't get resource list for visibility.kueue.x-k8s.io/v1alpha1: the server is currently unable to handle the request
```
in older k8s versions.
Fixes #1519 
```release-note
NONE
```
> Don't deploy visibility by default

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/workload_names.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/raycluster/raycluster_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- test/e2e/multikueue/e2e_test.go
- test/e2e/singlecluster/e2e_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/controller/jobs/kubeflow/kubeflowjob.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/controller/jobs/raycluster/raycluster_controller_test.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
- test/integration/multikueue/multikueue_test.go
/kind cleanup
[jobframework] Use the jobs uuid in workload's name hash. With this we can avoid name collisions for workloads create for jobs having the same name and type created at different pints in time.
Fixes #1726
```release-note
The hash suffix of the workload's name are now influenced by the job's object UID. Recreated jobs with the same name and kind will use different workload names.
```
> [jobframework] Use the jobs uid in workload's name hash.

- apis/kueue/v1beta1/admissioncheck_types.go
/kind cleanup
Update description for "Retry" and "Rejected" states. to be in sync with the site documentation.
Fixes #
```release-note
NONE
```
> [AC] Update description for "Retry" and "Rejected" states.

- pkg/controller/jobframework/integrationmanager.go
Cleanup the comment/docs on an exported function.
Fixes #
```release-note
NONE
```
> chore: typo in RegisterIntegration comment

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
/kind cleanup
Remove CapacityAvailable condition check to avoid dependency on the old version of autoscaler: https://github.com/kubernetes-sigs/kueue/pull/1740#issuecomment-1956667795
> Remove check for CapacityAvailable ProvReq condition

- .golangci.yaml
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
- test/e2e/singlecluster/pod_test.go
- test/util/util.go
/kind cleanup
The PR removes redundant duplicate imports in several files in tests. It enables the `gocritic` linter with the `dupImport` check to prevent such issues in the future.
```
> make verify
...
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go:25:2: dupImport: package is imported 2 times under different aliases on lines 25 and 26 (gocritic)
corev1 "k8s.io/api/core/v1"
^
pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go:26:2: dupImport: package is imported 2 times under different aliases on lines 25 and 26 (gocritic)
v1 "k8s.io/api/core/v1"
^
test/util/util.go:29:2: dupImport: package is imported 2 times under different aliases on lines 29 and 30 (gocritic)
"k8s.io/apimachinery/pkg/api/errors"
^
test/util/util.go:30:2: dupImport: package is imported …
```
> Fix duplicated imports reported by gocritic linter

- cmd/kueue/main_test.go
- pkg/config/config_test.go
/kind cleanup
Refactor tests by replacing `os.MkdirTemp` with `t.TempDir`.
[`T.TempDir`](https://pkg.go.dev/testing#T.TempDir)  automatically removes the temporary directory.
```release-note
NONE
```
> Simplify tests by using T.TempDir

- Makefile
/kind cleanup
Fix the path to `main.go` in the `run` make target.
The `run` target has become broken since https://github.com/kubernetes-sigs/kueue/pull/1088.
```release-note
NONE
```
> Fix run make target: update path to main.go

- .golangci.yaml
- cmd/experimental/podtaintstolerations/test/e2e/e2e_test.go
- test/e2e/singlecluster/e2e_test.go
- test/e2e/singlecluster/pod_test.go
- test/e2e/singlecluster/visibility_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/controller/jobs/raycluster/raycluster_controller_test.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/integration/scheduler/scheduler_test.go
- test/integration/webhook/workload_test.go
/kind cleanup
Fix and refactor e2e and integration tests according to the `ginkgolinter` suggestions.
Changes:
- Add missing assertion method statements.
- Replace `gomega.Equal(false)`/`gomega.Equal(true)` with `gomega.False()`/`gomega.True()`.
- Replace `gomega.Equal` with `gomega.HaveLen` for slices.
- Replace `gomega.Equal(0)` with `gomega.Empty` for slices.
The whole log of running golangci-lint:
```
❯ ./bin/golangci-lint run
test/integration/controller/jobs/mpijob/mpijob_controller_test.go:197:3: ginkgo-linter: wrong length assertion; consider using `gomega.Expect(createdJob.Spec.MPIReplicaSpecs[kubeflow.MPIReplicaTypeLauncher].Template.Spec.NodeSelector).Should(gomega.HaveLen(1))` instead (ginkgolinter)
gomega.Expect(len(createdJob.Spec.MPIReplicaSpecs[kubeflow.MPIReplicaTypeLaunche …
```
> Fix test lint issues reported by ginkgolinter

- keps/976-plain-pods/README.md
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/slices/slices.go
- pkg/util/slices/slices_test.go
- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/singlecluster/pod_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
Finalize the Failed pods in a pod-group once a replacement pods are created.
Fixes #1762 
```release-note
The Failed pods in a pod-group are finalized once a replacement pods are created.
```
> [pods] Finalize the replaced pods

- keps/976-plain-pods/README.md
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/slices/slices.go
- pkg/util/slices/slices_test.go
- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/singlecluster/pod_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
Manual cherry-pick of #1766
Fixes #
The automatic  cherry-pick was blocked by a conflict on deduplication of `corev1` import in e2e tests.  Solved, no impact on the main logic.
```release-note
The Failed pods in a pod-group are finalized once a replacement pods are created.
```
> [release-0.6][pods] Finalize the replaced pods

- keps/1788-pass-parameters-to-ProvReq/README.md
- keps/1788-pass-parameters-to-ProvReq/kep.yaml
Contributes to fixing issue #1788 
Fixes #
```release-note
NONE
```
> KEP #1788: Passing parameters to ProvisioningRequest

- .golangci.yaml
- apis/visibility/v1alpha1/conversion_test.go
- pkg/cache/cache_test.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/core/workload_controller.go
- pkg/controller/jobframework/validation.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/util/maps/maps_test.go
- pkg/util/testing/wrappers.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/e2e/multikueue/e2e_test.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/multikueue/multikueue_test.go
- test/integration/scheduler/scheduler_test.go
/kind cleanup
The PR fixes typos in unexported variable/function/field names, test messages, and comments. Additionally, the PR enables `misspell` linter that can catch some mistakes.
```release-note
NONE
```
> Fixes typos in variables, comments, and tests

- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- test/e2e/multikueue/e2e_test.go
/kind feature
[multikueue] Cluster connection monitoring and reconnect.  Try to reconnect to the worker cluster when any of its watch loops ends.
Fix #1787
Relates to #693 
```release-note
Added MultiKueue  worker connection monitoring and reconnect. 
```
> [multikueue] Cluster connection monitoring and reconnect.

- test/performance/local-queue.yaml
- test/performance/prerequisites/cluster-queue.template
- test/performance/prerequisites/resource-flavor.yaml
- test/performance/run-test.sh
Update the api version from v1alpha2 to v1beta1, and update cluster-template as cluster-queue API has changed in the meantime
/kind cleanup
```release-note
NONE
```
> [performance test] Fix cluster-queue template and update api version

- pkg/controller/jobs/job/job_controller_test.go
/kind cleanup
```release-note
NONE
```
> Improve readability of job controller unit tests

- pkg/queue/cluster_queue_best_effort_fifo.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/cluster_queue_strict_fifo.go
- pkg/queue/local_queue.go
- pkg/util/heap/heap.go
- pkg/util/heap/heap_test.go
/kind cleanup
This simplifies code, but it also opens the possibility to use the heap in other aspects, such as implementing fair-sharing algorithms #1714
Fixes #217 
```release-note
NONE
```
> Generalize heap implementation

- go.mod
- go.sum
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/raycluster/raycluster_controller_test.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/client.go
- pkg/workload/workload_test.go
/kind cleanup
- Bump sigs.k8s.io/controller-runtime to v0.17.2
- Add a SSA to fake StrategicMerge fake client patch inteceptor.
Fixes #
```release-note
NONE
```
> Bump sigs.k8s.io/controller-runtime to v0.17.2

- go.mod
- go.sum
This reverts commit 38fee15a013552af42ea51feb002734a73c0b636.
/kind bug
Released "github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0" was removed :(
https://github.com/ray-project/kuberay/tags
Fixes #
Currently, we can not build the kueue-manager-controller:
```bash
$ go build -o /tmp/kueue-manager cmd/kueue/main.go 
go: downloading github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0
pkg/controller/jobs/raycluster/raycluster_controller.go:20:2: reading github.com/ray-project/kuberay/ray-operator/go.mod at revision ray-operator/v1.1.0-rc.0: unknown revision ray-operator/v1.1.0-rc.0
pkg/controller/jobs/rayjob/rayjob_controller.go:23:2: reading github.com/ray-project/kuberay/ray-operator/go.mod at revision ray-operator/v1.1.0-rc.0: unknown revision ray-operator/v1.1.0-rc.0
``` …
> Revert "Bump github.com/ray-project/kuberay/ray-operator (#1786)"

- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/scheduler/preemption/preemption_test.go
/kind bug
cc @B1F030 I reproduced the bug with a preemption test, PTAL.
Fixes https://github.com/kubernetes-sigs/kueue/pull/1385#discussion_r1496476805
```release-note
Fix incorrect quota management when lendingLimit enabled in preemption
```
> Fix incorrect snapshot usage when lendingLimit enabled

- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/workload_controller.go
- pkg/metrics/metrics.go
- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- test/integration/scheduler/scheduler_test.go
- test/util/util.go
/kind cleanup
Kueue updates ClusterQueues to include pending or admitted workloads, among other things. These changes shouldn't trigger requeueing.
This not only saves CPU cycles, but API calls to the apiserver for Events.
Fixes #
```release-note
Skip requeueing of Workloads when there is a status update for a ClusterQueue, saving on API calls for Workloads that were already attempted for admission.
```
> Avoid requeue on ClusterQueue status update

- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
/kind cleanup
Relates to #1814 
Relates to #693
[multikueue] Don't use reconnecting clients in WL reconnecting.
```release-note
NONE
```
> [multikueue] Don't use reconnecting clients in WL reconnecting.

- .golangci.yaml
- Makefile
- pkg/controller/jobframework/reconciler.go
/kind cleanup
The PR enables `govet`, removes `vet` from `verify` make target; fixes `govet.nilness` issue.
`govet` is enabled in the https://github.com/kubernetes/kubernetes/blob/e0621034bedeeabe83383e5c300cf2d4fb616f36/hack/golangci.yaml#L136, so I've also enabled it here with all default analyzers and `nilness` analyzer.
So, the whole enabled `govet` analyzers list looks like this:
```
❯ GL_DEBUG=govet ./golangci-lint run
...
DEBU [govet] Enabled by config analyzers (33): [appends asmdecl assign atomic bools buildtag cgocall composites copylocks defers directive errorsas framepointer httpresponse ifaceassert loopclosure lostcancel nilfunc nilness printf shift sigchanyzer slog stdmethods stringintconv structtag testinggoroutine tests timeformat unmarshal unreachable unsafeptr …
```
> Enable govet linter; disable vet in make verify

- config/components/manager/controller_manager_config.yaml
- pkg/controller/jobs/pod/pod_controller.go
/kind bug
There were 2 problems:
- The Pod reconciler doesn't use `For`, which controller-runtime uses to map to groupKindConcurrency.
- The GroupKind is actually just `Pod`, not `Pod.`.
Fixes #
Thanks to @gabesaba for spotting the problem.
It's not easy to test this issue, but I did a manual run to verify the number of reconcilers.
```release-note
Fix the configuration for the number of reconcilers for the Pod integration. It was only reconciling one group at a time.
```
> Fix number of reconcilers for Pod integration

- Makefile
- hack/e2e-common.sh
- hack/e2e-test.sh
- hack/multikueue-e2e-test.sh
/kind bug
Cherry pick of #1830
Fixes #
```release-note
NONE
```
> [release-0.6] [e2e] Restore the manager's image from the bash scripts. (Cherry pick #1830)

- charts/kueue/templates/webhook/webhook.yaml
- config/components/webhook/manifests.yaml
- pkg/controller/core/workload_controller.go
- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/integration/webhook/workload_test.go
/kind bug
As @alculquicondor mentioned https://github.com/kubernetes-sigs/kueue/issues/1821#issuecomment-1994761605, mutating webhooks seems not to be possible to update `spec` and `status` in a single webhook call.
So, we must reset requeueState while reconciling instead of webhooks.
Fixes #1821
```release-note
WaitForPodsReady: Fix a bug that the requeueState isn't reset.
```
> WaitForPodsReady: Reset the requeueState while reconciling

- charts/kueue/templates/webhook/webhook.yaml
- config/components/webhook/manifests.yaml
- pkg/controller/core/workload_controller.go
- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/integration/webhook/workload_test.go
Cherry pick of #1838 on release-0.6.
#1838: WaitForPodsReady: Reset the requeueState while reconciling
```release-note
WaitForPodsReady: Fix a bug that the requeueState isn't reset.
```
> Automated cherry pick of #1838: WaitForPodsReady: Reset the requeueState while reconciling

- pkg/controller/core/workload_controller.go
- pkg/controller/jobframework/reconciler.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/admissionchecks.go
- pkg/workload/workload.go
/kind cleanup
Skip unnecessary API calls for noop updates related to admission attempts.
Fixes #
```release-note
Avoid API calls for admission attempts when Workload already has condition Admitted=false
```
> Do not make API calls when the workload already has condition Admitted=false

- pkg/controller/core/workload_controller.go
- pkg/controller/jobframework/reconciler.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/admissionchecks.go
- pkg/workload/workload.go
Cherry pick of #1820 on release-0.6.
#1820: Do not make API calls when the workload already has condition
```release-note
Avoid API calls for admission attempts when Workload already has condition Admitted=false
```
> Automated cherry pick of #1820: Do not make API calls when the workload already has condition

- CHANGELOG/CHANGELOG-0.6.md
- Makefile
- README.md
- charts/kueue/Chart.yaml
- site/config.toml
Change-Id: I7cc659b2b013cd4a0b907b0e3002b877dac2e4ae
Fixes #
```release-note
NONE
```
> Prepare release v0.6.1

- pkg/controller/jobframework/defaults.go
- pkg/controller/jobs/raycluster/raycluster_webhook.go
- test/integration/controller/jobs/raycluster/raycluster_webhook_test.go
- test/integration/controller/jobs/raycluster/suite_test.go
Fixes #1844
This is a regression introduced in #1747.
```release-note
Do not default to suspending a job whose parent is already managed by Kueue
```
> Do not default to suspending a job whose parent is already managed by Kueue

- test/integration/controller/jobs/raycluster/raycluster_controller_test.go
/kind bug
/kind flake
When there's a no fit Job the inadmissible count for `ExpectPendingWorkloadsMetric()` should be 1
Fixes #1829 
```release-note
```
> Flaky integration test "RayCluster Job controller interacting with scheduler" 

- site/content/en/docs/admission-check-controllers/provisioning.md
- site/content/en/docs/concepts/workload.md
- site/content/en/docs/contribution guidelines/_index.md
- site/content/en/docs/tasks/_index.md
- site/content/en/docs/tasks/run_python_jobs.md
- site/content/en/docs/tasks/setup_sequential_admission.md
Fixes broken URLs on https://kueue.sigs.k8s.io/
Broken links found by the [linkchecker](https://linkchecker.github.io/linkchecker/).
<details>
<summary>linkchecker output</summary>
```
❯ linkchecker --no-warnings https://kueue.sigs.k8s.io/
INFO linkcheck.cmdline 2024-03-15 22:18:12,314 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.4.0
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2023 LinkChecker Authors
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it under
certain conditions. Look at the file `COPYING' within this distribution.
Read the documentation at https://linkchecker.github.io/linkchecker/
Write comments and bugs to …
```
> [doc] fix website broken links

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/scheduler/preemption_test.go
/kind bug
The previous check didn't allow any preemptions if the workload has any common resources with pending workloads that were sorted first. In other words, a preemption only was permitted for the first workload in the list for each cohort.
By definition, preempting workloads don't fit in the cohort. Here I propose that, by cohort, we just allow one preemption per cycle if there wasn't already an admission in the same cohort. This could be enhanced with a more comprehensive approach.
Fixes #
I propose a follow up: #1867
However, the fix in this PR is a better candidate for backport.
```release-note
Fix preemption to reclaim quota that is blocked by an earlier pending Workload from another ClusterQueue in the same cohort.
```
> Fix preemption blocked by earlier pending Workload

- cmd/importer/README.md
- cmd/importer/main.go
- cmd/importer/pod/check.go
- cmd/importer/pod/check_test.go
- cmd/importer/pod/import.go
- cmd/importer/pod/import_test.go
- cmd/importer/util/util.go
- go.mod
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- test/integration/framework/framework.go
- test/integration/importer/importer_test.go
- test/integration/importer/suite_test.go
/kind feature
Add a CLI tool able to import existing pods into Kueue.
Fixes #
```release-note
NONE
```
> Add pod importer

- cmd/importer/README.md
- cmd/importer/main.go
- cmd/importer/pod/check.go
- cmd/importer/pod/check_test.go
- cmd/importer/pod/import.go
- cmd/importer/pod/import_test.go
- cmd/importer/util/util.go
- cmd/importer/util/util_test.go
- go.mod
- test/integration/importer/importer_test.go
/kind feature
[importer] Extend mapping capabilities. 
Fixes #
```release-note
None
```
> [importer] Extend mapping capabilities. 

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/util/testing/wrappers.go
- test/integration/scheduler/preemption_test.go
- test/util/util.go
/kind bug
When there are multiple workloads waiting for preemption and multiple candidates with the same timestamp, it was possible that all these candidates would be preempted across a few admission attempts.
This can be mitigated by using the information about the workloads pending preemption and introducing stable sorting.
In this fix, I'm using the UID as an arbitrary unpredictable key to do stable sorting.
Fixes #
```release-note
Avoid unnecessary preemptions when there are multiple candidates for preemption with the same admission timestamp
```
> Avoid unnecessary preemptions when candidates have the same timestamp

- cmd/importer/util/util_test.go
/kind cleanup
[importer] Add missing header in test file.
Fixes #
```release-note
none
```
> [importer] Add missing header in test file.

- Makefile
/kind cleanup
So Github CI/CD works correctly with go 1.21
This caused following [failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1869/pull-kueue-test-integration-main/1771137982699409408)
```release-note
NONE 
```
> Use the setup-evnvtest version compatible with go 1.21

- site/content/en/docs/tasks/_index.md
- site/content/en/docs/tasks/troubleshooting/_index.md
- site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Part of #1410
This is very basic for now, but we have to start somewhere.
I plan to follow up with more details for misconfigured ClusterQueues and another page dedicated to Pods, as they are very different from the rest of the jobs.
```release-note
NONE
```
> Troubleshooting: checking whether job is admitted or preempted

- Makefile
- cloudbuild.yaml
- cmd/importer/Dockerfile
- cmd/importer/README.md
- cmd/importer/run-in-cluster/deps.yaml
- cmd/importer/run-in-cluster/importer.yaml
- cmd/importer/run-in-cluster/kustomization.yaml
- cmd/importer/run-in-cluster/mapping.yaml
/kind feature
[importer] Run in cluster
Fixes #
```release-note
none
```
> [importer] Run in cluster

- Makefile
- cloudbuild.yaml
/kind cleanup
Build all images in a single cloudbuild step.
Fixes #
```release-note
none
```
> [cloudbuild] Build all images in a single step.

- go.mod
/kind feature
Bump golang to 1.22.
Fixes #
Testing this right now. https://github.com/kubernetes-sigs/jobset/pull/471 is open but failing for some infrastructure issues.
Want to confirm if its limited to image.
```release-note
NONE
```
> bump to golang 1.22

- site/content/en/docs/tasks/_index.md
- site/content/en/docs/tasks/troubleshooting/troubleshooting_pods.md
Add basic steps to troubleshoot single pods or pod groups
Part of #1410 
The links in this change assume that #1888 is merged.
```release-note
NONE
```
> Troubleshooting pods

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind bug
The initial attempt to clear finalizers after declaring a Workload as finished might fail partially. At this point, some succeeded pods might be gone, so the group can no longer be interpreted as finished. But we shouldn't be checking that again.
Fixes #1898
```release-note
Fix Pods in Pod groups stuck with finalizers when deleted immediately after Succeeded
```
> Fix Pod finalizers for succeeded groups

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/controller/constants/constants.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/jobset/jobset_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/mxjob/mxjob_controller_test.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/admissioncheck/admissioncheck.go
- pkg/util/testing/wrappers.go
- pkg/util/testingjobs/jobset/wrappers.go
- pkg/util/testingjobs/mxjob/wrappers.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
/kind feature
/kind api-change 
This implements changes introduced in #1788 and #1793 
Fixes #1788
I've done manual e2e testing
```release-note
User can now pass parameters to ProvisioningRequest using job's annotations
```
> Passing parameters to ProvisioningRequest from annotations

- pkg/controller/core/workload_controller.go
I was investigating why we were doing a large amount of workload reconciles, and found that this equality check wasn't working as intended.
Compare workload reconciles before/after (1k jobs, 10k pods)
```release-note
None
```
> Dereference StopPolicy before equality check

- test/e2e/singlecluster/pod_test.go
- test/util/constants.go
- test/util/util.go
/kind cleanup
Based on experience fixing flaky tests, a timeout of 30s just adds to development time.
If Kueue doesn't react within 5 seconds, it likely won't in a longer time.
And for operations which require multiple pieces to interact (mainly E2E tests), we still have the `LongTimeout` variable which can be used on a case-by-case basis.
The duration for Consistent checks can also be limited, as these are more of sanity checks. We try not to use these checks.
Fixes #
```release-note
NONE
```
> Adjust base timeouts for integration and E2E tests

- Makefile
- hack/e2e-common.sh
- hack/e2e-test.sh
- hack/multikueue-e2e-test.sh
- test/e2e/singlecluster/e2e_test.go
- test/e2e/singlecluster/jobset_test.go
- test/util/util.go
/kind cleanup
Kueue and JobSet are like two peas in a pod. We should have e2e tests verifying the behavior in single-cluster like we have for multikueue.
Fixes #
Partially https://github.com/kubernetes-sigs/kueue/issues/1463
```release-note
NONE
```
> add e2e test for single cluster jobset

- site/content/en/docs/tasks/run/flux_miniclusters.md
- site/content/en/docs/tasks/run/jobs.md
- site/content/en/docs/tasks/run/jobsets.md
- site/content/en/docs/tasks/run/kubeflow/mpijobs.md
- site/content/en/docs/tasks/run/kubeflow/mxjobs.md
- site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
- site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
- site/content/en/docs/tasks/run/kubeflow/tfjobs.md
- site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
- site/content/en/docs/tasks/run/plain_pods.md
- site/content/en/docs/tasks/run/python_jobs.md
- site/content/en/docs/tasks/run/rayclusters.md
- site/content/en/docs/tasks/run/rayjobs.md
- site/static/_redirects
This PR fixes broken links to the [*Administer Cluster Quotas* page](https://kueue.sigs.k8s.io/docs/tasks/manage/administer_cluster_quotas/) throughout the docs, and in server-side redirect definitions.
The links in the latest documentation currently lead to a 404 page.
```release-note
NONE
```
> docs: Fix broken link in Kubernetes Jobs guide

- cmd/importer/README.md
/kind cleanup
```release-note
NONE
```
> Fix README formatting

- .shellcheckrc
- hack/verify-shellcheck.sh
/kind cleanup
Add `.shelcheckrc` to store `shellcheck` configuration to improve readability and maintainability.
Updates #1518
I'm aware that the Kubernetes project uses the `SHELLCHECK_DISABLED` variable in [`hack/verify-shellcheck.sh`](https://github.com/kubernetes/kubernetes/blob/d1a2a134c532109540025c990697a6900c2e62fc/hack/verify-shellcheck.sh#L54) to ignore issues, rather than using a `.shellcheckrc` file. This is due to historical reasons: when Kubernetes first introduced `shellcheck`, it did not support config files.
```release-note
NONE
```
> Load shellcheck configuration from the .shellcheckrc

- .golangci.yaml
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
/kind cleanup
Extends the logic of `ReconcileGenericJob` to return all errors that occur when updating the status of the starting job fails.
This was prompted by a `loggercheck` lint issue found in the log message.
Initially, this PR only corrects the log message output and enables [`loggercheck`](https://golangci-lint.run/usage/linters/#loggercheck) linter to prevent similar mistakes in the future.
This PR arrose because [`log.Error`](https://pkg.go.dev/github.com/go-logr/logr@v1.4.1#Logger.Error) accepts key-value pairs, not format-value args:
```
func (l Logger) Error(err error, msg string, keysAndValues ...any)
```
The output from `loggercheck`:
```
pkg/controller/jobframework/reconciler.go:397:83: odd number of arguments passed as key-value pairs for logging (loggercheck) …
```
> [jobframework] Return all errors when updating workload status

- test/integration/scheduler/preemption_test.go
/kind cleanup
The integration test "When most quota is in a shared ClusterQueue in a cohort" in preemption_test.go fails deterministically when "In a cohort with StrictFIFO" runs in the same process. It fails because the resource flavor "one" already exists, left by the "StrictFIFO" test.
Fixes #
Discovered locally when running the tests with  `INTEGRATION_NPROC=1`.
```release-note
NONE
```
> Cleanup resources created by the preemption integration test

- Makefile
/kind cleanup
Uses gnu version of sed while using Darwin OS
Fixes #
```release-note
NONE
```
> [makefile] Support for sed on Darwin

- charts/kueue/templates/webhook/webhook.yaml
- config/components/webhook/manifests.yaml
- pkg/controller/jobframework/setup_test.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller_test.go
- pkg/controller/jobs/rayjob/rayjob_webhook.go
- pkg/controller/jobs/rayjob/rayjob_webhook_test.go
- pkg/util/testingjobs/rayjob/wrappers.go
- site/static/examples/jobs/ray-job-sample.yaml
- test/integration/controller/jobs/raycluster/raycluster_webhook_test.go
- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
- test/integration/framework/framework.go
KubeRay has promoted the RayJob API from v1alpha1 to v1 with KubeRay v1.0.0. While the v1alpha1 version is still served in KubeRay v1.1.0, it'll be removed in v1.2.0.
Fixes #1335.
Supersedes #1435.
```release-note
Upgrade RayJob API to v1
ACTION REQUIRED
If you use KubeRay older than v1.0.0, you'll have to upgrade your existing installation
to KubeRay v1.0.0, or any more recent version, that supports KubeRay v1 APIs, for it to
remain compatible with Kueue.
```
> Upgrade RayJob API to v1

- pkg/queue/cluster_queue_impl.go
- pkg/queue/cluster_queue_impl_test.go
- test/integration/scheduler/scheduler_test.go
/kind bug
Fixes #1937
```release-note
Properly count the number of pending workloads in StrictFIFO queue, when the first workload cannot be admitted.
```
> Count inflight workload as pending 

- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
- test/integration/scheduler/fairsharing/fair_sharing_test.go
- test/integration/scheduler/fairsharing/suite_test.go
- test/integration/scheduler/scheduler_test.go
Implements the concept of a "fair share" for a ClusterQueue or a ClusterQueue with an additional workload as defined in #1773:
```
For a given resource r provided by a ClusterQueue or cohort c, we calculate T_r as the total
requests consumed by the Workloads for that resource in that CQ or cohort, independent of the
flavor, that are above the nominal quota. The value for a resource is the ratio of T_r and the
total nominal quotas, or lendingLimits if defined, in the hierarchy of the parent of C.
The value for the CQ or cohort is the maximum among the values for each resource,
divided by the weight, if defined.
```
The fair share value is used for sorting the heads of the ClusterQueues during admission.
Part of #1714
There is no API for this feature in this PR. That's because we don't want …
> Fair share during admission

- .golangci.yaml
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
/kind cleanup
Removes duplicated word `the` in the comment and enables [`dupword`](https://golangci-lint.run/usage/linters/#dupword) linter to prevent similar typos.
```release-note
NONE
```
> Remove duplicated word reported by dupword

- site/content/en/docs/concepts/cluster_queue.md
the `lendingLimit` is limit quota can be lend to other ClusterQueues.
And `team-b-cq` set `lendingLimit` to 1 means `team-a-cq` can use up to 9+1 cpus.
And `team-a-cq` set `lendingLimit` as empty,  means all its quota can be lend out, so `team-b-cq` can use up to 12+9
Fixes #
```release-note
NONE
```
> fix some issue about lendingLimit docs

- keps/1432-admission-check-per-resource-flavor/README.md
- keps/1432-admission-check-per-resource-flavor/kep.yaml
/kind feature
Design for support for AdmissionChecks per ResourceFlavor
Part of #1432 
```release-note
NONE
```
> KEP-1432: AdmissionCheck per ResourceFlavor

- charts/kueue/templates/webhook/service.yaml
- charts/kueue/values.yaml
- hack/update-helm.sh
/kind feature
Fixes #
add support allow configuration of `ipFamilyPolicy` for ipDualStack kubernetes cluster
```release-note
add support allow configuration of `ipFamilyPolicy` for ipDualStack kubernetes cluster
```
> allow configuration of ipFamilyPolicy

- test/integration/controller/jobs/rayjob/rayjob_controller_test.go
/kind bug
/kind flake
Wait for workload admission change in rayjob preemption integration  test.
Maybe fixes #1943
```release-note
NONE
```
> [test/int] Wait for workload admission change in rayjob preemption test.

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
A quick follow up after  #1802 to remove duplicated custom logic for Pods ownership by RayClusters.
```release-note
NONE
```
> Remove redundant RayCluster logic from Pod controller

- pkg/controller/jobs/pod/indexer.go
- pkg/controller/jobs/pod/pod_controller.go
This is a hotspot when there are many pods within a namespace. Compare a 60s CPU sample, pivoting around client.List
**Before:**
**After**
```release-note
Improve pod integration performance
```
> Index PodGroupName

- apis/kueue/v1beta1/workload_types.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- test/integration/scheduler/preemption_test.go
/kind feature
Fixes #1874
```release-note
A new condition with type Preempted allows to distinguish different reasons for the preemption to happen
```
> Distinguish preemption reasons

- pkg/features/kube_features.go
- site/content/en/docs/admission-check-controllers/provisioning.md
- site/content/en/docs/installation/_index.md
/kind feature
Graduate the Provisioning Admission Check Controller feature from alpha to beta (this means that the feature will be enabled by default).
```release-note
Provisioning Admission Check Controller (ProvisioningACC) feature is now enabled by default
```
> Graduate Admission Check Controller to beta

- apis/kueue/v1beta1/resourceflavor_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
- config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
- pkg/webhooks/resourceflavor_webhook.go
- pkg/webhooks/resourceflavor_webhook_test.go
- pkg/webhooks/workload_webhook.go
- test/integration/webhook/resourceflavor_test.go
/kind cleanup
This PR replaces some of the validations executed by webhooks for the `resourceflavor` type with CRD validation rules.
Relates to #463 
Due to the [resource constraints](https://kubernetes.io/docs/reference/using-api/cel/#resource-constraints) imposed by the API Server, only have been replaced those validations which costs don't exceed the limits.
```release-note
Added CRD validation rules to ResourceFlavor.
ACTION REQUIRED: Requires Kubernetes 1.25 or newer
```
> Add CEL rules to ResourceFlavor

- .golangci.yaml
- Makefile
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/util/priority/priority.go
- pkg/util/priority/priority_test.go
/kind cleanup
Clean up unnecessary loop variable copying and enable the `copyloopvar` linter for detecting this redundant variable copying.
After the project upgraded to Go version 1.22 in #1895, copying variables inside a `for` loop became unnecessary. See this [blog post](https://go.dev/blog/loopvar-preview) for a detailed explanation.
The `copyloopvar` linter is only available from `golangci-lint` v1.57 onwards, so we also need to update this tool.
```release-note
NONE
```
> Remove unneeded loop variable copying

- Makefile
/kind feature
This PR will add the support for s390x and ppc64le for multi-arch image build
We have successfully created multi-arch images and pushed into local image registry. We have successfully deployed the created images on Openshift platform runs on s390x architecture. We have also shared screenshots for the same.
```release-note
NONE
```
> Added support for s390x and ppc64le for multi-arch image build

- pkg/queue/manager.go
/king bug
This function should lock and unlock to prevent race conditions.
Fixes #1954 
```release-note
NONE
```
> Add a lock to ClusterQueueFromLocalQueue

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler_test.go
Cherry pick of #1979 on release-0.6.
#1979: Fix preemption algorithm to reduce the number of
```release-note
```
> Automated cherry pick of #1979: Fix preemption algorithm to reduce the number of

- apis/kueue/v1beta1/clusterqueue_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
- pkg/webhooks/clusterqueue_webhook.go
- pkg/webhooks/clusterqueue_webhook_test.go
- test/integration/webhook/clusterqueue_test.go
/kind cleanup
It replaces some of the validations executed by webhooks for the `ClusterQueue` type with CRD validation rules.
Relates to #463 
Only validation rules with a cost within the API server limits have been added.
```release-note
Added CRD validation rules to ClusterQueue.
ACTION REQUIRED: Requires Kubernetes 1.25 or newer
```
> Add CEL rules to ClusterQueue

- hack/multikueue-e2e-test.sh
- pkg/controller/admissionchecks/multikueue/batchjob_adapter.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/util/testingjobs/jobset/wrappers.go
- site/content/en/docs/concepts/multikueue.md
- site/content/en/docs/tasks/run/jobsets.md
- test/e2e/multikueue/e2e_test.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Add support for JobSet `spec.managedBy`.
Fixes #693 
```release-note
Add MultiKueue support for  JobSet  `spec.managedBy` field.
```
> MultiKueue JobSet managedBy

- cmd/importer/pod/check_test.go
- cmd/importer/pod/import_test.go
- pkg/controller/admissionchecks/multikueue/controllers.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/podset/podset_test.go
/kind cleanup
Corrects spelling mistakes in variable names.
Safe to merge because only unexported or local variables are affected.
```release-note
NONE
```
> Fix typos in unexported variable names

- test/e2e/singlecluster/e2e_test.go
/kind cleanup
This PR reduces the time it takes to run the singlecluster e2e tests by removing the need to use long runtime containers in two tests 
The `pull-kueue-test-e2e-main-X-XX` test suite execution time went down **from ~80 seconds to ~65 seconds** (in all tested k8s versions):
* `Should unsuspend a job and set nodeSelectors`: from 9.505s to 4.182s
* `Should partially admit the Job if configured and not fully fits`: from 9.509s to 8.490s
* `Should unsuspend a job only after all checks are cleared`: from 10.803s to 5.967s
Fixes #1449 
```release-note
NONE
```
> Improve e2e execution time

- Makefile
- pkg/util/testing/kubeconfig.go
- pkg/util/testing/wrappers.go
- test/integration/multikueue/suite_test.go
- test/scalability/README.md
- test/scalability/checker/checker_test.go
- test/scalability/default_generator_config.yaml
- test/scalability/default_rangespec.yaml
- test/scalability/minimalkueue/main.go
- test/scalability/runner/controller/controller.go
- test/scalability/runner/generator/generator.go
- test/scalability/runner/generator/generator_test.go
- test/scalability/runner/main.go
- test/scalability/runner/recorder/recorder.go
- test/scalability/runner/stats/stats.go
/kind feature
Add scalability test to be able to detect regressions in Kueue's overall scheduling performance.
Relates to #1912 
This should be the fist stage of this change, once this is merged and we have a CI job set up, we should refine the generator config and the expected metrics value.
```release-note
Added scalability test
```
> Scalability tests

- site/content/en/docs/concepts/cluster_queue.md
Fixes #1974
```release-note
NONE
```
> Preemption algorithm described

- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/util/testing/wrappers.go
- test/integration/scheduler/fairsharing/fair_sharing_test.go
/kind feature
This is an implementation of rule S2-a of https://sigs.k8s.io/kueue/keps/1714-fair-sharing#choosing-workloads-from-clusterqueues-for-preemption
In simple terms:
Preempt if the CQ of the incoming workload doesn't obtain a share higher than the final share of the CQ being preempted.
Part of #1714
WIP because I would still like to write an integration test that causes preemptions from multiple workloads to multiple workloads.
A follow up PR will include rule S2-b, which is not immediately obvious.
Not yet. The boolean that determines the use of fair sharing is not accessible through any API.
```release-note
NONE
```
> Fair preemptions in a cohort, rule S2-a

- apis/kueue/v1beta1/clusterqueue_types.go
- apis/kueue/v1beta1/zz_generated.deepcopy.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
- pkg/util/admissioncheck/admissioncheck.go
- pkg/util/testing/wrappers.go
- pkg/webhooks/clusterqueue_webhook.go
- pkg/webhooks/clusterqueue_webhook_test.go
- pkg/workload/workload.go
- test/integration/scheduler/workload_controller_test.go
/kind bug
Addresses comments of an already merged PR #1960 
Part of #1432 
```release-note
NONE
```
> Make ClusterQueue's AdmissionCheckStrategy a pointer, avoid type casting

- apis/kueue/v1beta1/workload_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
- site/content/en/docs/tasks/run/jobs.md
- site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
/kind cleanup
* Renames "Admitted by" to "Reserving in" printed column of `kubectl get workload`
* Adds "Admitted" printed column to `kubectl get workload`
Fixes #1790
```release-note
Improve the kubectl output for workloads using admission checks.
```
> Non-admitted workloads with QuotaReserved condition are shown as Admitted by kubectl

- apis/kueue/v1beta1/workload_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
- site/content/en/docs/tasks/run_jobs.md
Cherry pick of #1991 on release-0.6.
#1991: * Rename "Admitted by" to "Reserving in" printed column *
```release-note
Improve the kubectl output for workloads using admission checks.
```
> Automated cherry pick of #1991: * Rename "Admitted by" to "Reserving in" printed column *

- .golangci.yaml
- pkg/controller/constants/constants.go
/kind cleanup
Changes deprecation comment format for `constants.QueueAnnotation` according to the https://go.dev/wiki/Deprecated.
The wrong format of the deprecation comment for the `constants.QueueAnnotation` is found with `gocritic`'s `deprecatedComment` check.
Can't replace `constants.QueueAnnotation` with `constants.QueueLabel`, see the discussion below https://github.com/kubernetes-sigs/kueue/pull/1976#discussion_r1566379045
```release-note
NONE
```
> Fix deprecated comment for constants.QueueAnnotation

- Makefile
- test/scalability/checker/checker_test.go
- test/scalability/default_rangespec.yaml
- test/scalability/runner/controller/controller.go
- test/scalability/runner/main.go
- test/scalability/runner/recorder/recorder.go
/kind feature
Adds scalability runner measured metrics, a set of measurements results extracted from the API events monitored by the runner which can be easily used to detect regressions in kueue's scheduling.
Currently a summary is generated like:
```yaml
clusterQueueClasses:
cq:
cpuAverageUsage: 358300
cpuUsed: 123130721000
firstEventTime: "2024-04-17T13:07:53.831208896+03:00"
lastEventTime: "2024-04-17T13:13:37.48321136+03:00"
nominalQuota: 600000
workloadClasses:
large:
averageTimeToAdmissionMs: 8288
averageTimeToFinishMs: 9292
count: 1500
totalEvictions: 0
medium:
averageTimeToAdmissionMs: 77447
averageTimeToFinishMs: 77951
count: 3000
totalEvictions: 1
small:
averageTimeToAdmissionMs: 214757
averageTimeToFinishMs: 214962
count: 10500
totalEvictions: 8
```
The checker will  verify …
> [test] Scalability runner metrics

- .golangci.yaml
- pkg/controller/jobframework/reconciler.go
/kind cleanup
The PR corrects the log message output and enables [loggercheck](https://golangci-lint.run/usage/linters/#loggercheck) linter to prevent similar mistakes in the future.
We can't return all errors `log.Error` is needed here. See #1907 and #1940 for details.
This PR arrose because [log.Error](https://pkg.go.dev/github.com/go-logr/logr@v1.4.1#Logger.Error) accepts key-value pairs, not format-value args:
```
func (l Logger) Error(err error, msg string, keysAndValues ...any)
```
The output from loggercheck:
```
pkg/controller/jobframework/reconciler.go:397:83: odd number of arguments passed as key-value pairs for logging (loggercheck)
log.Error(errUpdateStatus, "Updating workload status, on start failure %s", err.Error())
^
```
```release-note
NONE
```
> [jobframework] Fix logging of error message

- pkg/queue/cluster_queue.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/util/heap/heap.go
/kind feature
Continues #1948, adding rule S2-b from https://github.com/kubernetes-sigs/kueue/tree/main/keps/1714-fair-sharing#choosing-workloads-from-clusterqueues-for-preemption
```
value of AlmostLCA(y,x) (with z) is strictly higher than AlmostLCA(x,y) with admitted workload w. Here the case is that Y’s sub-org is greedy, and doesn’t allow smaller requests on the x’s size. If no other preemption option is possible inside any other CQ, z should be considered for preemption. Maybe y has a smaller workload that could be admitted, and then both x and y will be ”happy”. In practice this rule prevents huge workloads from taking the whole unused capacity, blocking everyone else and claiming that this is fair-sharing.
```
In other words, allow preemption if the highest share value among the …
> Rule s2-b for flat fair preemption

- apis/config/v1beta1/configuration_types.go
- keps/1282-pods-ready-requeue-strategy/README.md
- pkg/controller/core/core.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- test/integration/scheduler/podsready/suite_test.go
/kind bug
Part of #2009
WIP because still testing, and I need to update the estimations from KEP and API comments.
Early feedback is welcome.
```release-note
Make the defaults for PodsReadyTimeout backoff more practical, as for the original values
the couple of first requeues made the impression as immediate on users (below 10s, which 
is negligible to the wait time spent waiting for PodsReady). 
The defaults values for the formula to determine the exponential back are changed as follows:
- base `1s -> 10s`
- exponent: `1.41284738 -> 2`
So, now the consecutive times to requeue a workload are: 10s, 20s, 40s, ...
```
> Make the defaults for PodsReadyTimeout backoff more practical

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind feature
It propagates the message from the Provisioning Request (condition Provisioned = false) into the Workload. The message will contain the expected time for the resources to be provisioned. Exposing this information to the users will allow them to understand why the job is still pending and how long until the resources will be available.
Fixes #1749
```release-note
The message for a ProvisioningRequest being provisioned (which might include an ETA, depending on the implementation) is now propagated to workloads.
```
> Propagate provisioning status of a ProvReq into the Workload status

- keps/1714-fair-sharing/README.md
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
/kind feature
Consider a case where there are two flavors of CPU, with the following quotas and usage:
- `on-demand`: nominal=20, usage=25
- `spot`: nominal=80, usage=5
This CQ is borrowing 5 units of `on-demand`. However, the old logic would give the CQ a score of `0`, because (25+5<=20+80).
This would have prevented legitimate preemptions in the on-demand flavor.
Part of https://github.com/kubernetes-sigs/kueue/issues/1714
This interpretation would actually simplify a lot of the changes that I did in #1777 
We basically only need to keep the total "lendable" quota for a cohort.
Sorry for not realizing this problem earlier :(
But I'll leave the clean up for the next PR.
Feature not released yet
```release-note
NONE
```
> Make dominant resource share flavor aware

- charts/kueue/values.yaml
/kind bug
We forgot to update this in #1835
Fixes #
```release-note
Fix chart values configuration for the number of reconcilers for the Pod integration.
```
> Fix number of pod reconcilers in default chart values

- pkg/controller/core/core.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
/kind cleanup
To make the unit test assert on the requeueAt time precisely, not just using "After".
Fixes #
WIP because still testing
```release-note
NONE
```
> Tighten asserts for PodsReady requeueAt by using a fake clock and jitter=0

- charts/kueue/templates/manager/auth_proxy_service.yaml
- charts/kueue/templates/manager/manager.yaml
- charts/kueue/values.yaml
/kind feature
I have changed to be able to set Custom Annotations on Service resources and Deployment's Pod resources via Helm Chart.
Fixes #1619 
```release-note
add support allow configuration of custom annotations on Service and Deployment's Pod
```
> add: custom annotations on service and deployment

- site/content/en/docs/tasks/manage/setup_sequential_admission.md
Fixes #2009
```release-note
NONE
```
> Add a note on PodsReady timeout requeuing

- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/jobframework/reconciler.go
- pkg/queue/cluster_queue.go
- pkg/util/testingjobs/jobset/wrappers.go
- pkg/util/testingjobs/mxjob/wrappers.go
- pkg/util/testingjobs/pod/wrappers.go
- pkg/util/testingjobs/raycluster/wrappers.go
/kind cleanup
- fix Receiver names are different
- fix some useless comments
Fixes #
None
```release-note
None
```
> cleanup useless comments, and fix receiver names are different

- test/scalability/default_rangespec.yaml
/kind feature
Adapt scalability  test range spec to the observed CI results.
Relates to #1912
```release-note
None
```
> Adapt scalability range spec to the CI results

- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
/kind cleanup
Follow up to #2037.
The only information we need from the cohort to calculate a dominant resource share is how much lendable resources there are.
Fixes #
```release-note
NONE
```
> Cleanup CQ and cohort resource stats

- site/content/en/docs/concepts/admission_check.md
- site/content/en/docs/concepts/cluster_queue.md
- site/static/examples/admin/minimal-cq.yaml
Part of #1432 
```release-note
NONE
```
> Add AdmissionCheckStrategy documentation

- pkg/controller/admissionchecks/provisioning/constants.go
- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind bug
Fixes #2051 
I've tested it e2e manually
```release-note
Pods created by Kueue have now the ProvisioningRequest's classname annotation
```
> Add the ProvisioningRequest's classname annotation

- apis/kueue/v1beta1/admissioncheck_types.go
- pkg/cache/admissioncheck.go
- pkg/cache/cache.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/controller/admissionchecks/multikueue/admissioncheck.go
- pkg/controller/admissionchecks/multikueue/admissioncheck_test.go
- pkg/util/testing/wrappers.go
- test/integration/multikueue/multikueue_test.go
/kind feature
- Allow to validate if a MultiKueue admission check is configured only for a subset of flavors.
Fixes #2021
```release-note
NONE
```
> Validate admission check applies to all flavors

- pkg/controller/core/workload_controller.go
/kind cleanup
Currently, the log messages suggest that the workload is admitted, only if it has quota reserved.
This is confusing when debugging issues related to admission checks.
Fixes #
```release-note
Correctly log workload status for workloads with quota reserved, but awaiting for admission checks.
```
> Improve logging of workload status

- .golangci.yaml
- Makefile
/kind cleanup
Enables [gci](https://github.com/daixiang0/gci) to ensure import order established on the project
Fixes #
It will reformat this:
```go
import (
"context"
"testing"
kueue "sigs.k8s.io/kueue/apis/kueue/v1beta1"
"sigs.k8s.io/kueue/pkg/cache"
"sigs.k8s.io/controller-runtime/pkg/client/interceptor"
"sigs.k8s.io/controller-runtime/pkg/reconcile"
)
```
To this:
```go
import (
"context"
"testing"
"sigs.k8s.io/controller-runtime/pkg/client/interceptor"
"sigs.k8s.io/controller-runtime/pkg/reconcile"
kueue "sigs.k8s.io/kueue/apis/kueue/v1beta1"
"sigs.k8s.io/kueue/pkg/cache"
)
```
```release-note
NONE
```
> Deterministic import order linter

- pkg/controller/core/workload_controller.go
- pkg/queue/manager.go
/kind cleanup
/kind flake
Fixes #2020
In this scenario occasionally the workload `pendingAlphaWl` gets admitted before `useAllAlphaWl`
is requeued.
The scenario can be reproduced reliably by inserting a time delay (say 500ms) around [here](https://github.com/kubernetes-sigs/kueue/blob/9ea94ac20f4a4b5546ab899c60f3627b23bd0a74/pkg/controller/core/workload_controller.go#L560), between `r.cache.DeleteWorkload(wl)` and `!r.queues.AddOrUpdateWorkload(wlCopy)`.
```release-note
Fix handling of eviction in StrictFIFO to ensure the evicted workload is in the head.
Previously, in case of priority-based preemption, it was possible that the lower-priority
workload might get admitted while the higher priority workload is being evicted.
```
> Fix handling of eviction in StrictFIFO to ensure the evicted workload is in the head

- apis/kueue/v1beta1/workload_types.go
- cmd/experimental/podtaintstolerations/controller/pod_jobs.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/interface.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/raycluster/raycluster_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/multikueue/e2e_test.go
- test/e2e/singlecluster/e2e_test.go
- test/e2e/singlecluster/jobset_test.go
- test/integration/controller/core/workload_controller_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Replaces workload finished reason with succeeded and failed reasons
Fixes #1982
```release-note
Workload finished reason replaced with succeeded and failed reasons
```
> Include a Failed condition in Workloads

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/client/client.go
/kind bug
/kind feature
Using patch/apply on update pods.
Fixes #2056 
```release-note
Use PATCH updates for pods. This fixes support for Pods when using the latest features in Kubernetes v1.29
```
> Using patch/apply on update pods.

- charts/kueue/templates/certmanager/certificate.yaml
- charts/kueue/templates/internalcert/secret.yaml
/kind bug
Without these changes the integration with cert-manager is not working
```release-note
Helm Chart: Fix a bug that the kueue does not work with the cert-manager.
```
> fix(helm): wrong secret name in certificate

- Makefile
/kind bug
- Changed binary directory of scalability runner and minimalkueue to bin.
Fixes #2075
```release-note
None
```
> [scalability] Changed binary directory of scalability runner and minimalkueue.

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
/kind bug
This is the same bug as #1974, but for the case when borrowing is enabled.
I followed the same approach as #1979: exclude workloads from other CQs that are not above the threshold, to avoid hitting this conditional: https://github.com/kubernetes-sigs/kueue/blob/8b7dea3a70500a20fb36b53cdc5d97c2f4cb6cbc/pkg/scheduler/preemption/preemption.go#L219
Fixes #1974
```release-note
Fix preemption algorithm to reduce the number of preemptions within a ClusterQueue when reclamation is not possible, and when using .preemption.borrowWithinCohort
```
> Reduce preemptions within ClusterQueue when preemption with borrowing is enabled

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
Cherry pick of #2110 on release-0.6.
#2110: Reduce preemptions within ClusterQueue when preemption with
```release-note
Fix preemption algorithm to reduce the number of preemptions within a ClusterQueue when reclamation is not possible, and when using .preemption.borrowWithinCohort
```
> Automated cherry pick of #2110: Reduce preemptions within ClusterQueue when preemption with

- keps/2076-kueuectl/README.md
- keps/2076-kueuectl/kep.yaml
- keps/487-kubectl-plugin/kep.yaml
/kind feature
Introduces command line tool for Kueue management and API listing. 
Fixes #2076
```release-note
NONE
```
> KEP 2076: Kueuectl

- apis/kueue/v1beta1/workload_types.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/raycluster/raycluster_controller_test.go
- pkg/workload/workload.go
- test/integration/controller/core/workload_controller_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/job/suite_test.go
/kind bug
- fixed Requeued condition transition on activate/deactivate workload
- fixed Requeued condition transition on WaitForPodsReady
Fixes #2038 
```release-note
Fix transitions of Requeued condition.
```
> Fix transitions of Requeued condition

- site/content/en/docs/tasks/troubleshooting/troubleshooting_jobs.md
Just a quick note about what to look for when using admission checks. We should probably have a dedicated page for ProvisioningRequest and MultiKueue specifically, but I'll leave those for a follow up.
Fixes #
@pajakd recently improved the messaging for ProvisioningRequest in #2007, but we can update that in a separate PR, after we cherry-pick this one.
I also opened #2121 to improve the Admitted condition during this time.
```release-note
NONE
```
> Add troubleshooting note for pending admission checks

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
Clear RequeuAt on workload backoff finished.
Fixes #2038 
```release-note
Сlear RequeuAt on workload backoff finished.
```
> Сlear RequeuAt on workload backoff finished

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
/kind cleanup
I moved the eviction by inactivation mechanism to the workload controller so that users can avoid re-implementing the same mechanism in the user's integrations controller without the jobframework reconciler.
Fixes #1841 
```release-note
JobFramework: The eviction by inactivation mechanism was moved to the workload controller.
```
> Move the eviction by inactivation mechanism from the jobframework reconciler to the workload controller

- pkg/util/limitrange/limitrange.go
- pkg/util/limitrange/limitrange_test.go
- pkg/util/testing/wrappers.go
/kind bug
Includes `SidecarContainers` in the computation of total resource requests of a pod.
Fixes #2068 
The new formula to calculate the total was extracted from [KEP-753](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers#resources-calculation-for-scheduling-and-pod-admission).
```release-note
Fix the resource requests computation taking into account sidecar containers.
```
> Add sidecar containers to resource requests computation

- charts/kueue/templates/certmanager/certificate.yaml
- charts/kueue/templates/internalcert/secret.yaml
Cherry pick of #2087 on release-0.6.
#2087: fix(helm): wrong secret name in certificate
```release-note
Helm Chart: Fix a bug that the kueue does not work with the cert-manager.
```
> Automated cherry pick of #2087: fix(helm): wrong secret name in certificate

- pkg/util/limitrange/limitrange.go
- pkg/util/limitrange/limitrange_test.go
- pkg/util/testing/wrappers.go
Cherry pick of #2099 on release-0.6.
#2099: Add sidecar containers to resource requests computation
```release-note
Fix the resource requests computation taking into account sidecar containers.
```
> Automated cherry pick of #2099: Add sidecar containers to resource requests computation

- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
/kind flake
Fixed "should requeued after job status ready" test.
Fixes #2155 
```release-note
None
```
> Fix "should requeued after job status ready" test.

- charts/kueue/templates/manager/manager.yaml
/kind bug
Changes to Kueue config requires Pod to be restarted in order of being picked up
```release-note
NONE
```
> fix(helm): ensure Manager Deployment is restarted when config changes

- keps/1136-provisioning-request-support/README.md
/kind cleanup
Describes behavior of ProvisioningRequest controller regarding recently introduced new [conditions](https://github.com/kubernetes/autoscaler/blob/349559c32f496900ccd643172c7e4f87a8fecc02/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1/types.go#L177)
Part of #2041 
```release-note
NONE
```
> [KEP] Support new ProvisioningRequest's conditions

- Makefile
- test/performance/scheduler/runner/main.go
/kind cleanup
To collect more data which will help us diagnose regressions, or failures. 
The logs can be helpful to understand why some certain workloads took long. 
The metrics can be helpful to understand how the dynamics changes over time during the test (e. g. first we accumulate pending workloads, then gradually process).
Fixes #
To eval the performance I checked 5 builds for `scrape 5s + logs`:
1787881265534341120
1788122597204955136
1788130374614781952
1788133679826997248
1788136923525550080
And 12 builds for `scrape 1s + logs + cpu profile`:
1787379334198071296
1783914210393067520
1787401375009738752
1787442170244894720
1787454666427076608
1787461693572386816
1787463978864087040
1787486099027791872
1787488286453796864
1787493923178942464
1787500095751589888
1787519348999458816 …
> [scalability] Collect extra information by default (metrics and logs)

- cmd/kueuectl/app/create/create_localqueue.go
- site/content/en/docs/reference/kubectl-kueue.md
- test/e2e/singlecluster/kueuectl_test.go
- test/integration/kueuectl/create_test.go
/kind feature
To prevent the creation of a localqueue if a clusterqueue not exist.
Fixes #2112 
```release-note
Add validation for ClusterQueue on creating LocalQueue
```
> [kueuectl] Added validation for ClusterQueue on creating LocalQueue.

- cmd/kueue/main.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobframework/setup_test.go
/kind cleanup
Based on this discussion (https://github.com/kubernetes-sigs/kueue/pull/2130#discussion_r1593749594), I replaced the arguments `.integrations` with `.integrations.frameworks` to enforce the pre-check null pointer when performing the `WithEnabledFrameworks()`.
Fixes #
```release-note
JobFramework: Repaced the argument ".integrations" with the ".integrations.frameworks" in the "WithEnabledFrameworks()".
```
> Enforce the pre null pointer check for the Integrations when performing WithEnabledFrameworks()

- pkg/workload/admissionchecks.go
- pkg/workload/admissionchecks_test.go
- test/integration/controller/core/workload_controller_test.go
/kind cleanup
Use `UnsatisfiedChecks` instead of `NoChecks` in the Admitted condition Reason.
Fixes #2121 
```release-note
When using admission checks, and they are not satisfied yet, the reason for the Admission condition with status=False is now
`UnsatisfiedChecks`
ACTION REQUIRED: If you were watching for the reason `NoChecks` in the Admitted condition, use `UnsatisfiedChecks` instead.
```
> Change the Admitted condition reason while using admission checks.

- pkg/controller/admissionchecks/multikueue/admissioncheck.go
/kind bug
[multikueue] Reconcile the relevant ACs on cluster create.
Fixes #2117 
```release-note
MultiKueue: MultiKueue: Fix a bug that could potentially cause the failure of MultiKueue creation.
```
> [multikueue] Reconcile the relevant ACs on cluster create.

- pkg/controller/core/clusterqueue_controller_test.go
- pkg/controller/core/workload_controller.go
- pkg/controller/jobframework/reconciler.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/queue/manager.go
- pkg/scheduler/preemption/preemption.go
- pkg/util/testing/metrics/metrics.go
- pkg/util/testing/metrics/metrics_test.go
- site/content/en/docs/reference/metrics.md
- test/integration/controller/core/workload_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/integration/scheduler/preemption_test.go
- test/integration/scheduler/scheduler_test.go
- test/util/util.go
/kind feature
Expose a metrics to record workloads eviction number in cluster queue
Fixes #1741
```release-note
metric `evicted_workloads` is  number of evicted workloads per 'cluster_queue'
```
> add a metric for eviction number in cluster queue

- test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Wait independently for pods and workload deletion in e2e tetst.
Fixes #2146
```release-note
None
```
> [e2e/pod] Wait independently for pods and workload deletion.

- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/job/suite_test.go
/kind bug
Disable scheduler on "should requeued after job status ready" test.
Fixes #2155 and #2158
Related for this comment https://github.com/kubernetes-sigs/kueue/pull/2158#discussion_r1593690691.
```release-note
None
```
> Disabled scheduler on "should requeued after job status ready" test.

- pkg/metrics/metrics.go
/kind bug
To make the name of the metric prefixed with `kueue_`, which allows to easily grep all kueue metrics.
Fixes #
None since the metric wasn't released yet.
```release-note
NONE
```
> Set Subsystem for the evicted_workloads_total metric

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
/kind bug
Fix panic reporting evicted workload when status admission nil.
```release-note
None
```
> Fixed panic on report evicted workloads.

- cmd/kueue/main.go
- pkg/cache/cache.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/jobset/jobset_webhook.go
- pkg/controller/jobs/jobset/jobset_webhook_test.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
- pkg/visibility/api/rest/pending_workloads_lq.go
- site/content/en/docs/tasks/run/jobsets.md
- test/e2e/singlecluster/jobset_test.go
/kind feature
Sets jobSet's ManagedBy field by default if it's managed by MultiKueue
Fixes #2022
```release-note
The ManagedBy field in jobSet will now be set by default if managed by MultiKueue.
```
> [MultiKueue] Default managedBy for ClusterQueues configured to use MultiKueue AC

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
/kind bug
Currently, the Workload `Evicted` condition with an `InactiveWorkload` reason is added regardless of whether the Worklads already have an `Evicted` reason with other reasons like `Preempted` and `PodsReadyTimeout`.
But, we should keep the previous reason to avoid losing the truth reason of the eviction reason and double counting the eviction reason.
Fixes #
```release-note
NONE
```
> Should update Evicted condition only when the Workload have not already got Eviction

- go.mod
- pkg/controller/admissionchecks/multikueue/controllers.go
- pkg/controller/admissionchecks/multikueue/fswatch.go
- pkg/controller/admissionchecks/multikueue/fswatch_test.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Add the watch for changes to kubeconfigs provided as `PathLocationType`.
Fixes #
```release-note
None
```
> [multikueue] Add file system kubeconfig watch.

- Makefile
- Makefile-deps.mk
- Makefile-test.mk
/kind cleanup
Splits Makefile, so that it's more readable
Fixes #1997
Projects worth referencing:
- https://github.com/kubernetes-sigs/kustomize/blob/master/Makefile
- https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile
Can be done in follow-up or in this PR:
- It's common to [pin tools' versions in go.mod](https://github.com/kubernetes-sigs/kustomize/blob/master/hack/go.mod) in [separate module and install after cd'ing into it](https://github.com/kubernetes-sigs/kustomize/blob/e244b83844cd5e1d114b731713c7f437e510c023/Makefile-tools.mk#L59). Should we adopt it?
Problems:
- If one target is used(included) in multiple files, it results in warning. e.g.: `Makefile-test.mk:53: warning: ignoring old commands for target `gomod-download'`
- It's a common practice to have Makefile …
> Split Makefile to test, debug, external-crds, tools

- cmd/kueuectl/app/cmd.go
- cmd/kueuectl/app/options/update_workload_activation_options.go
- cmd/kueuectl/app/resume/resume.go
- cmd/kueuectl/app/resume/resume_workload.go
- cmd/kueuectl/app/stop/stop.go
- cmd/kueuectl/app/stop/stop_workload.go
- site/content/en/docs/reference/kubectl-kueue/_index.md
- site/content/en/docs/reference/kubectl-kueue/commands/_index.md
- site/content/en/docs/reference/kubectl-kueue/commands/create.md
- site/content/en/docs/reference/kubectl-kueue/commands/resume.md
- site/content/en/docs/reference/kubectl-kueue/commands/stop.md
- site/content/en/docs/reference/kubectl-kueue/installation.md
- test/integration/kueuectl/resume_test.go
- test/integration/kueuectl/stop_test.go
/kind feature
- To puts the given Workload on hold using kueuectl.
- To resumes the Workload using kueuectl.
Fixes #2132 and #2133
```release-note
Added stop/resume workload commands
```
> [kueuectl] Add stop/resume workload commands

- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/kubeflow/kubeflowjob/kubeflowjob_controller.go
- pkg/controller/jobs/mpijob/mpijob_controller.go
- pkg/controller/jobs/raycluster/raycluster_controller.go
- pkg/controller/jobs/rayjob/rayjob_controller.go
/kind cleanup
The PR simplifies implementation of `Finished()` method for all types of jobs.
I think this `for` loop is more readable
```go
for _, c := range conditions {
if (c.Type == JobComplete || c.Type == JobFailed) && c.Status == ConditionTrue {
return c.Message, c.Type != JobFailed, true
}
}
return "", true, false
```
than
```go
var conditionType JobConditionType
for _, c := range conditions {
if (c.Type == JobComplete || c.Type == JobFailed) && c.Status == ConditionTrue {
conditionType = c.Type
finished = true
message = c.Message
break
}
}
success = true
if conditionType == JobFailed {
success = false
}
return message, success, finished
```
Also, using one liner `success = conditionType != JobFailed` is readable enough.
Of course, it's subjective and reviewers can decline this PR. …
> [jobs] refactor GenericJob.Finished implementation

- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
Split "should requeued after job status ready" test into two, with two different values for BackoffBaseSeconds. One large, which will be used to assert that Requeued=False, and one short to assert that Requeued=True.
Fixes #2155 
Related for this comment https://github.com/kubernetes-sigs/kueue/pull/2161#discussion_r1595141135.
```release-note
None
```
> Split "should requeued after job status ready" test.

- cmd/kueuectl/app/cmd.go
- cmd/kueuectl/app/create/create.go
- cmd/kueuectl/app/create/create_localqueue.go
- cmd/kueuectl/app/list/helpers.go
- cmd/kueuectl/app/list/list.go
- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/list/list_localqueue_printer.go
- cmd/kueuectl/app/list/list_localqueue_printer_test.go
- cmd/kueuectl/app/list/list_localqueue_test.go
- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/options/update_workload_activation_options.go
- cmd/kueuectl/app/resume/resume.go
- cmd/kueuectl/app/resume/resume_workload.go
- cmd/kueuectl/app/stop/stop.go
- cmd/kueuectl/app/stop/stop_workload.go
- cmd/kueuectl/app/testing/fake.go
- cmd/kueuectl/app/util/client_getter.go
- pkg/util/testing/wrappers.go
- site/content/en/docs/reference/kubectl-kueue/_index.md
- site/content/en/docs/reference/kubectl-kueue/commands/list.md
- test/integration/kueuectl/list_test.go
/kind feature
To get list LocalQueues that match the given criteria: point to a specific CQ, being active/inactive, belonging to the specified namespace or matching the label selector.
Fixes #2115 
```release-note
Add list LocalQueue command on kueuectl
```
> [kueuectl] Add list LocalQueue command.

- site/content/en/docs/installation/_index.md
- site/content/en/docs/tasks/dev/integrate_a_custom_job.md
Expand documentation on integrating a new Job type and adds material on external integrations.
Fixes #2082 
```release-note
NONE
```
> Restructure integration page and add content on external integrations

- .golangci.yaml
- cmd/importer/pod/check.go
- cmd/importer/pod/import.go
- pkg/config/validation.go
- pkg/controller/admissionchecks/multikueue/admissioncheck.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobs/job/job_webhook.go
- pkg/controller/jobs/pod/expectations.go
- pkg/queue/manager_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/scheduler_test.go
- pkg/util/admissioncheck/admissioncheck.go
- pkg/util/resource/resource.go
- pkg/util/testing/client.go
- pkg/util/testing/wrappers.go
- pkg/visibility/api/rest/pending_workloads_cq_test.go
- pkg/visibility/api/rest/pending_workloads_lq_test.go
- pkg/workload/workload.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
/kind cleanup
Fixes `gocritic` lint issues: `assignOp`, `captLocal`, `commentFormatting`, `elseif`, `ifElseChain`.
Follows #1946. See also https://github.com/kubernetes-sigs/kueue/pull/1946/files#r1552980330
<details>
<summary>Full log</summary>
```
❯ golangci-lint run
pkg/util/resource/resource.go:35:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}' (gocritic)
} else {
^
pkg/util/testing/client.go:143:72: captLocal: `SubResourceName' should not be capitalized (gocritic)
func TreatSSAAsStrategicMerge(ctx context.Context, clnt client.Client, SubResourceName string, obj client.Object, patch client.Patch, opts ...client.SubResourcePatchOption) error {
^
pkg/util/testing/wrappers.go:988:49: captLocal: `LocationType' should not be capitalized (gocritic)
func (mkc …
```
> Fix lint issues reported by gocritic

- .golangci.yaml
/kind cleanup
Removes `gci` from the `linter-settings` golangci-lint's config because it's does nothing. This reverts #2069.
Adding `gci` to `linters-settings` has no effect. This can be checked by running golangci-lint in verbose mode (see "Active 14 linters"):
```
❯ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/Oleksandr_Redko/src/github.com/kubernetes-sigs/kueue /Users/Oleksandr_Redko/src/github.com/kubernetes-sigs /Users/Oleksandr_Redko/src/github.com /Users/Oleksandr_Redko/src /Users/Oleksandr_Redko /Users /] 
INFO [config_reader] Used config file .golangci.yaml 
INFO [lintersdb] Active 14 linters: [copyloopvar dupword errcheck ginkgolinter gocritic goimports gosimple govet ineffassign loggercheck misspell staticcheck unconvert unused] 
INFO [loader] Go …
```
> Remove gci linter because it breaks import comments

- .golangci.yaml
- pkg/util/wait/backoff_test.go
/kind cleanup
Fixes `ms` function implementation in `wait` package tests to prevent future bugs.
Actually, there are no current bugs because `ms` is always called with an integer number. However, if someone calls `ms` with `time.Duration`, the result will be a much larger value than expected. For example, `ms(time.Minute)` will yield `60000000000` milliseconds, but the expected result is `60000`.
This was discovered using the [durationcheck](https://github.com/charithe/durationcheck) linter.
```release-note
NONE
```
> Fix ms function implementation

- .golangci.yaml
- apis/config/v1beta1/defaults.go
- apis/visibility/v1alpha1/defaults.go
- cmd/importer/pod/import.go
- pkg/controller/admissionchecks/multikueue/fswatch.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/pod/pod_controller.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/scheduler_test.go
- pkg/util/resource/resource_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/performance/scheduler/runner/main.go
- test/performance/scheduler/runner/recorder/recorder.go
- test/performance/scheduler/runner/scraper/scraper.go
/kind cleanup
Refactor unexported variable names: remove underscores and change case for initialisms. Enable `revive.var-naming` rule to enforce proper variable names.
From the [Google style guide](https://google.github.io/styleguide/go/guide#mixed-caps):
> Go source code usually uses `MixedCaps` or `mixedCaps` (camel case) rather than `underscores` (snake case) when writing multi-word names.
From [Effective Go](https://go.dev/doc/effective_go#mixed-caps):
> Finally, the convention in Go is to use MixedCaps or mixedCaps rather than underscores to write multiword names.
From [Go wiki](https://go.dev/wiki/CodeReviewComments#initialisms):
> Words in names that are initialisms or acronyms (e.g. “URL” or “NATO”) have a consistent case. For example, “URL” should appear as “URL” or “url” (as in …
> Refactor variable names according to Go style guide

- cmd/importer/util/util_test.go
- pkg/controller/admissionchecks/multikueue/fswatch_test.go
- test/integration/multikueue/multikueue_test.go
- test/performance/scheduler/runner/generator/generator_test.go
- test/performance/scheduler/runner/main.go
/kind cleanup
Refactor to use only `filepath.Join` when dealing with OS paths for consistency.
`filepath.Join` is preferred when dealing with paths even if the project doesn't run on Windows. From the [path doc](https://pkg.go.dev/path):
> to manipulate operating system paths, use the [path/filepath](https://pkg.go.dev/path/filepath) package
Also, I chose `filepath.Join` because the number of existing occurrences:
```
❯ grep -r -w --include=\*.go "filepath.Join" . | wc -l
59
❯ grep -r -w --include=\*.go "path.Join" . | wc -l
32
```
```release-note
NONE
```
> Refactor to use filepath.Join instead of path.Join for consistency

- pkg/config/config_test.go
- pkg/config/validation.go
- pkg/config/validation_test.go
/kind feature
I implemented the `.waitForPodsReady` validations.
Also, I consolidated the valid test cases for the `waitForPodsReady` into one case, and added fields to the defaulting tests.
Part-of https://github.com/kubernetes-sigs/kueue/issues/2084
```release-note
Added validations for the "waitForPodsReady.timeout" in the Configuration.
```
> configAPI: Implement waitForPodsReady validations

- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
I added the default parameters to the waitForPodsReady configuration.
Fixes #
```release-note
NONE
```
> Add default parameters in the waitForPodsReady configuration

- pkg/controller/jobs/pod/pod_controller.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/util/testing/wrappers.go
- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/singlecluster/pod_test.go
/kind bug
Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.
Fixes #2208
```release-note
Consider deleted pods without `spec.nodeName` inactive and subject for pod replacement.
```
> [pods] Consider deleted pods without `spec.nodeName` inactive.

- apis/config/v1beta1/defaults.go
- apis/config/v1beta1/defaults_test.go
/kind bug
If we don't set the `requeuingStrategy.timestamp` , the `backoffLimitCount` is ignored.
Fixes #
This has already been fixed in #2040 as a feature enhancement.
```release-note
Fix a bug that the ".waitForPodsReady.requeuingStrategy.backoffLimitCount" is ignored when the ".waitForPodsReady.requeuingStrategy.timestamp" is not set.
```
> [release-0.6] WaitForPodsReady: Load the backoffLimitCount regardless of the requeueingStrategy.timestamp

- Makefile-test.mk
- apis/kueue/v1beta1/clusterqueue_types.go
- apis/kueue/v1beta1/localqueue_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_localqueues.yaml
- cmd/kueuectl/app/cmd.go
- cmd/kueuectl/app/passthrough/passthrough.go
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml
- keps/2076-kueuectl/README.md
- site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
- test/integration/kueuectl/passthrough_test.go
- test/integration/kueuectl/suite_test.go
/kind feature
Add pass-through commands support in `kueuectl`. 
Fixes #2180
```release-note
Added pass-through commands support in `kueuectl` for `get`, `describe`, `edit`, `patch` and `delete`.
```
> [kueuectl] Pass-through commands.

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
Cherry pick of #2131 on release-0.6.
#2131: Move the eviction by inactivation mechanism from the
```release-note
JobFramework: The eviction by inactivation mechanism was moved to the workload controller.
```
> Automated cherry pick of #2131: Move the eviction by inactivation mechanism from the

- test/integration/scheduler/podsready/scheduler_test.go
Cherry pick of #2189 on release-0.6.
#2189: Cleanup the TODO in the integration test
```release-note
NONE
```
> Automated cherry pick of #2189: Cleanup the TODO in the integration test

- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/options/update_workload_activation_options.go
- cmd/kueuectl/app/resume/resume.go
- cmd/kueuectl/app/resume/resume_clusterqueue.go
- cmd/kueuectl/app/stop/helpers.go
- cmd/kueuectl/app/stop/stop_clusterqueue.go
- cmd/kueuectl/app/util/dry_run.go
- site/content/en/docs/reference/kubectl-kueue/commands/resume.md
- site/content/en/docs/reference/kubectl-kueue/commands/stop.md
- test/integration/kueuectl/resume_test.go
- test/integration/kueuectl/stop_test.go
/kind feature
Adds `kueuectl stop clusterqueue`, `kueuectl resume clusterqueue` commands
Fixes #2136 and #2137
```release-note
Stop/Resume ClusterQueue (`kueuectl stop clusterqueue`, `kueuectl resume clusterqueue`) commands are available
```
> [kueuectl] Stop/resume cluster queue

- test/e2e/singlecluster/pod_test.go
/kind flake
Flaky test: Pod groups when Single CQ should admit group that fits.
Fixes #2225
```release-note
NONE
```
> Flaky test: Pod groups when Single CQ should admit group that fits.

- test/performance/scheduler/default_rangespec.yaml
/kind bug
/kind flake
Relax the the constraints for the average CPU usage during performance scheduler tests.
Fixes #2240 
There is no indication of a systematic usage growth analyzing the periodic runs making the failed test just a "victim"  of CI environment status , in my opinion. However let's extend the accepted range wit 5%.  
```release-note
None
```
>  Relax the the constraints for the average CPU usage during performance scheduler tests.

- test/integration/kueuectl/resume_test.go
- test/integration/kueuectl/stop_test.go
/kind bug
/kind flake
Delete the used CQ at the end of stop/resume integration tests.
Fixes #2245
```release-note
None
```
> [test/int/kueuectl] Delete the used CQ at the end of stop/resume tests.

- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/suite_test.go
/kind bug
Added an integration test for the pod integration that exercises the case of not sending replacement pods.
Fixes #2222 
```release-note
NONE
```
> Added "should evict workload due workload deactivated on pods ready timeout" test.

- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/pod/suite_test.go
Cherry pick of #2230 on release-0.6.
#2230: Added "should evict workload due workload deactivated on pods
Changes:
- Using  `cmpopts.IgnoreFields(metav1.Condition{}, "LastTransitionTime", "ObservedGeneration")),` instead of `util.IgnoreConditionTimestampsAndObservedGeneration`;
- Using `core.WithControllerRequeuingBaseDelaySeconds(1)` instead of `BackoffBaseSeconds: ptr.To[int32](1)`.
```release-note
NONE
```
> Automated cherry pick of #2230: Added "should evict workload due workload deactivated on pods

- apis/config/v1beta1/configuration_types.go
- apis/config/v1beta1/defaults.go
- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- keps/1282-pods-ready-requeue-strategy/README.md
- pkg/controller/core/workload_controller.go
- site/content/en/docs/reference/kueue-config.v1beta1.md
- site/content/en/docs/tasks/manage/setup_sequential_admission.md
/kind cleanup
Set DefaultRequeuingBackoffBaseSeconds to 60s.
Fixes #2215
```release-note
Increased the default value in the `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` to 60
ACTION REQUIRED: You can configure `.waitForPodsReady.requeuingStrategy.backoffBaseSeconds` as needed.
```
> Set DefaultRequeuingBackoffBaseSeconds to 60s.

- pkg/scheduler/preemption/preemption.go
/kind bug
/kind flake
[preemption] Use strict patching when issuing evictions to avoid duplicate workload preemption.
Fixes #2244
```release-note
None
```
> [preemption] Use strict patching when issuing evictions.

- site/content/en/docs/installation/_index.md
There will be an error if servicemonitorCRD not installed :
`no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first`
Fixes #2085
```release-note
```
> servicemonitorCRD is need before install prometheus.yaml

- test/integration/controller/jobs/pod/pod_controller_test.go
- test/util/util.go
Fixes failing test caused by changes in isPodRunnableOrSucceeded of #2212
```
-	if p.DeletionTimestamp != nil && len(p.Spec.SchedulingGates) > 0 {
+	if p.DeletionTimestamp != nil && len(p.Spec.NodeName) == 0 {
```
It's solely tests issue, since node name was not set, the workload reconciliation was stuck in a reclaimable pods reset attempt
Fixes #2243
```release-note
NONE
```
> Pod controller: "when Using pod group Should keep the running pod group with the queue name if workload is evicted" flakes

- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/util/equality/podset.go
- pkg/util/equality/podset_test.go
Cherry pick of #2239 on release-0.6.
#2239: Plain Pod gets deleted once admitted via ProvisioningRequest
```release-note
Ignore tolerations for admitted workloads
```
> Automated cherry pick of #2239: Plain Pod gets deleted once admitted via ProvisioningRequest

- pkg/controller/jobs/job/job_controller_test.go
- pkg/util/equality/podset_test.go
/kind cleanup
Follow-up of #2239
Fixes #2213
* Test for ignoreTolerations
* Add node selector to test to make sure it's not a part of equality check
```release-note
None
```
> Follow-up of #2239

- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
- test/integration/webhook/workload_test.go
/kind bug
Allow an admission check controller to provide podSetUpdates for a podSet subset when needed.
Fixes #2260
```release-note
Fix support for MPIJobs when using a ProvisioningRequest engine that applies updates only to worker templates.
```
> [workload] Allow specifying PodSetUpdates for a subset of PodSets

- pkg/webhooks/workload_webhook.go
- pkg/webhooks/workload_webhook_test.go
- test/integration/controller/jobs/mpijob/mpijob_controller_test.go
Cherry pick of #2265 on release-0.6.
#2265: Allow specifying PodSetUpdates for subset of
```release-note
Fix support for MPIJobs when using a ProvisioningRequest engine that applies updates only to worker templates.
```
> Automated cherry pick of #2265: [workload] Allow specifying PodSetUpdates for a subset of PodSets

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/util/util.go
/kind bug
If the Workload is deactivated, the workload resets the requeueState to avoid a race condition between the kueue-scheduler and the workload controller in the case of the deactivated workload.
When the workload is deactivated by exceeding the backoffLimitCount, the workload is added the `The workload is deactivated due to exceeding the maximum number of re-queuing retries`. I will introduce a dedicated reason in another PR to focus on fixing the bug.
Fixes #2174
The cherry-pick was manually created here https://github.com/kubernetes-sigs/kueue/pull/2220.
Because we have significant changes in the mechanism of re-queuing between v0.6 and the main branch.
```release-note
Fix a bug that causes the reactivated Workload to be immediately deactivated even though it doesn't exceed the …
```
> WaitForPodsReady: Reset .status.requeueState.count once the workload is deactivated

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
- test/util/util.go
/kind bug
If the Workload is deactivated, the workload resets the requeueState to avoid a race condition between the kueue-scheduler and the workload controller in the case of the deactivated workload.
When the workload is deactivated by exceeding the backoffLimitCount, the workload is added `The workload is deactivated due to exceeding the maximum number of re-queuing retries`. I will introduce a dedicated reason in another PR to focus on fixing the bug.
Fixes #2174
This PR is cherry-pick of #2219
The primary difference from #2219 is the criteria to deduce that the Workload is deactivated due to exceeding the backoffLimitCount.
In the v0.7 implementation, the deactivated workload doesn't have the `.status.requeuesState.requeueAt` since the `requeueAt` should be reset when the workload …
> [release-0.6] WaitForPodsReady: Reset .status.requeueState once the workload is deactivated

- cmd/kueuectl/app/list/helpers.go
- cmd/kueuectl/app/list/list.go
- cmd/kueuectl/app/list/list_clusterqueue.go
- cmd/kueuectl/app/list/list_localqueue_test.go
- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/list/list_workload.go
- cmd/kueuectl/app/list/list_workload_printer.go
- cmd/kueuectl/app/list/list_workload_test.go
- cmd/kueuectl/app/testing/fake.go
- cmd/kueuectl/app/util/client_getter.go
- cmd/kueuectl/app/util/helpers.go
- keps/2076-kueuectl/README.md
- pkg/controller/core/workload_controller.go
- pkg/workload/workload.go
- site/content/en/docs/reference/kubectl-kueue/commands/list.md
- test/integration/kueuectl/list_test.go
/kind feature
Added list workloads command.
Fixes #2135 
```release-note
CLI: Added list workloads command.
```
> [kueuectl] Added list workloads command.

- pkg/controller/core/workload_controller.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
/kind cleanup
Based on [this discussion](https://github.com/kubernetes-sigs/kueue/pull/2289#discussion_r1616661188), I removed the `HasRequeueState` helper function. That just verifies nil.
Fixes #
```release-note
NONE
```
> Chore: Remove HasRequeueState helper function

- test/performance/scheduler/default_rangespec.yaml
/kind flake
Because the test flaked on the main branch: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kueue-test-scheduling-perf-main/1794363845955817472
Dashboard:
Message:
```
=== Failed
=== FAIL: test/performance/scheduler/checker TestScalability/WorkloadClasses/small (0.00s)
checker_test.go:117: Average wait for admission 227486ms is more then expected 227000ms
```
Fixes #
From the comment https://github.com/kubernetes-sigs/kueue/pull/2290#discussion_r1616738204, we also observed 231068ms.
```release-note
NONE
```
> [scalability] Adjust the threshold for small workloads

- CHANGELOG/CHANGELOG-0.6.md
- Makefile
- README.md
- charts/kueue/Chart.yaml
- site/config.toml
Part of #2231
```release-note
NONE
```
> Prepare release v0.6.3

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/workload/resources.go
/kind bug
Fixes #2278
Check the containers limits for used resources in provisioning admission check controller.
```release-note
Check the containers limits for used resources in provisioning admission check controller and include them in the ProvisioningRequest as requests
```
> [provisionong-AC] Check the limits for used resources.

- .github/dependabot.yml
- .github/workflows/openvex.yaml
- .github/workflows/sbom.yaml
/kind bug
/kind cleanup
This PR fixes the SBOM generation and improves the actions setup a little bit:
* Installs the go binary into the actions runner (needed to compute dependencies for the SBOM)
* Adds the dependabot configuration to update the installed actions
* Pins the installed actions to hashes to follow recommended practices
N/A
/cc @alculquicondor 
```release-note
NONE
```
> Dependabot actions

- .github/workflows/sbom.yaml
/kind cleanup
This PR renames the SBOM output to match the latest @ossf naming conventions:
https://github.com/ossf/sbom-everywhere/blob/main/reference/sbom_naming.md
See sample release:  https://github.com/puerco/kueue/releases/tag/v0.6.3-rc.1
NONE
/cc @alculquicondor 
```release-note
NONE
```
> Fix SBOM filename to latest openssf convention

- Makefile
/kind feature
Include kueuectl binary on build artifacts.
Fixes #
```release-note
Include kubectl-kueue binary on release artifacts
```
> [kueuectl] Include kubectl-kueue binary on release artifacts

- pkg/config/validation.go
- pkg/config/validation_test.go
/kind feature
Currently, the configAPI validation doesn't have non negative check for the `queueVisibility.clusterQueues.maxCount`.
Fixes: #2084
```release-note
Added non-negative validations for the ".queueVisibility.clusterQueues.maxCount" in the Configuration.
```
> ConfigAPI: Implement the non negative validation for the queueVisibility.clusterQueues.maxCount

- apis/kueue/v1beta1/workload_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
- pkg/scheduler/flavorassigner/podset_reducer_test.go
- test/integration/controller/jobs/jobset/jobset_controller_test.go
- test/integration/scheduler/scheduler_test.go
- test/integration/webhook/workload_test.go
/kind feature
Allow for `workload.spec.podSet.[*].count` to be 0
Fixes #2227 
```release-note
Allow for `workload.spec.podSet.[*].count` to be 0
```
> Allow podSet count to be 0

- test/integration/framework/framework.go
/kind cleanup
[test-integration] Don't panic after `Framework.Init` failure allowing other test suites to run.
Fixes #
```release-note
None
```
> [test-integration] Don't panic after `Framework.Init` failure.

- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- site/content/en/docs/installation/_index.md
There was inconsistency on the amount of spaces of the commented out settings.
Now it's always just one `#` that needs to be removed.
Fixes #
```release-note
NONE
```
> Fix indentation of commented out configurations

- test/integration/controller/jobs/jobset/jobset_controller_test.go
/kind cleanup
Improve debuggability of jobset controller tests as requested [here](https://github.com/kubernetes-sigs/kueue/pull/2268#pullrequestreview-2085007373)
Fixes #2227
```release-note
```
> improve debuggability in jobset controller tests

- charts/kueue/values.yaml
- config/components/manager/controller_manager_config.yaml
- site/content/en/docs/tasks/manage/administer_cluster_quotas.md
There is a lack of documentation for the `resources.excludeResourcePrefixes`: #2267.
Also, I added the default parameter to manifests.
Part-of #2266
```release-note
NONE
```
> Add documentation for the excludeResourcePrefixes

- site/content/en/docs/tasks/manage/setup_sequential_admission.md
We don't have any documentation about https://github.com/kubernetes-sigs/kueue/pull/2264.
Part-of #2216
```release-note
NONE
```
> WaitForPodsReady: Add documentation for the backoffMaxSeconds

- cmd/kueue/main.go
- pkg/features/kube_features.go
/kind feature
To make debugging easier for users
Tested e2e manually
```release-note
Users can now see configuration of Kueue's feature gates in `kueue-controller-manager` logs
```
> Log Kueue's feature gates at the start-up

- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- pkg/util/maps/maps.go
- test/integration/multikueue/multikueue_test.go
/kind feature
Remove the multikueue remote objects synchronously when reachable based on the filters cache workload content.
Fixes #2320
```release-note
[multikueue] Remove remote objects synchronously when reachable.
```
> [multikueue] Remove remote objects synchronously when reachable.

- cmd/kueuectl/app/list/helpers.go
- cmd/kueuectl/app/list/list_clusterqueue.go
- cmd/kueuectl/app/list/list_clusterqueue_printer.go
- cmd/kueuectl/app/list/list_clusterqueue_test.go
- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/list/list_workload.go
- cmd/kueuectl/app/list/list_workload_printer.go
- cmd/kueuectl/app/list/list_workload_test.go
- test/integration/kueuectl/list_test.go
/kind feature
Support paging on kueue CLI list commands.
Fixes #2183 
```release-note
CLI: Support paging on kueue CLI list commands.
```
> [kueuectl] Support paging on kueue CLI list commands.

- site/content/en/docs/concepts/multikueue.md
- site/content/en/docs/tasks/manage/setup_multikueue.md
- site/content/en/docs/tasks/run/jobsets.md
Simplify the user-facing documentation. The support in 0.6.0 had limitations which are not worth documenting.
Let's recommend Kueue 0.7.0+ with JobSet 0.5.1+
Fixes #
The main issue is that in 0.6.x we didn't support the managedBy mechanism, and for that reason users couldn't install the Jobset controller on management, so the documentation will differ significantly for 0.6 and 0.7.
```release-note
NONE
```
> Simplify the user-facing documentation for JobSet in MultiKueue

- cmd/kueuectl/app/cmd.go
- cmd/kueuectl/app/completion/completion.go
- cmd/kueuectl/app/completion/completion_test.go
- cmd/kueuectl/app/create/create_localqueue.go
- cmd/kueuectl/app/list/list_clusterqueue_test.go
- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/list/list_localqueue_test.go
- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/list/list_workload.go
- cmd/kueuectl/app/list/list_workload_test.go
- cmd/kueuectl/app/resume/resume_clusterqueue.go
- cmd/kueuectl/app/resume/resume_workload.go
- cmd/kueuectl/app/stop/stop_clusterqueue.go
- cmd/kueuectl/app/stop/stop_workload.go
- cmd/kueuectl/app/testing/fake.go
- cmd/kueuectl/app/util/client_getter.go
- site/content/en/docs/reference/kubectl-kueue/installation.md
/kind feature
Support autocompletion on kueue CLI commands.
Fixes #2295 
```release-note
Support autocompletion on kueue CLI commands
```
> [kueuectl] Support autocompletion on kueue CLI commands

- site/hugo.toml
- site/layouts/partials/footer.html
Adds correct trademark disclaimer, as part of our ongoing effort to https://github.com/cncf/techdocs/issues/198,
Fixes  [#1647](https://github.com/kubernetes-sigs/kueue/issues/1647)
```release-note
NONE
```
> 🌱 docs: Add correct trademark disclaimer

- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
[multikueue] Ignore the `IsManaged` result during synchronous remote objects deletion, otherwise since the 
original workload owner may no longer be found  and the `IsJobManagedByKueue` method if `managedBy`
base adapters return a false negative, spiking the synchronous remote objects deletion.
Relates to #2320 
```release-note
None
```
> [multikueue] Ignore the `IsManaged` result during sync remote objects deletion.

- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/controller/admissionchecks/multikueue/multikueuecluster_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
/kind bug
/kind flake
MultiKueue skip garbage collection for disconnected clients, which otherwise can cause a panic if the GC runes between the time a `remoteClient` is connected and it's initial connection to the worker cluster.
Fixes #2365 
```release-note
[MultiKueue] Skip garbage collection for disconnected clients which could occasionally result in panic.
```
> MultiKueue skip garbage collection for disconnected clients.

- pkg/config/config.go
- pkg/config/config_test.go
/kind bug
Throws an error when the config contains unknown fields instead of silently ignoring them.
Fixes #2330 
```release-note
NONE
```
> Throw an error when config contains unknown fields

- cmd/kueuectl/app/cmd.go
- cmd/kueuectl/app/list/list.go
- cmd/kueuectl/app/list/list_clusterqueue.go
- cmd/kueuectl/app/list/list_clusterqueue_printer.go
- cmd/kueuectl/app/list/list_clusterqueue_test.go
- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/list/list_localqueue_printer.go
- cmd/kueuectl/app/list/list_localqueue_printer_test.go
- cmd/kueuectl/app/list/list_localqueue_test.go
- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/list/list_workload.go
- cmd/kueuectl/app/list/list_workload_printer.go
- cmd/kueuectl/app/list/list_workload_test.go
- test/integration/kueuectl/create_test.go
- test/integration/kueuectl/list_test.go
- test/integration/kueuectl/resume_test.go
- test/integration/kueuectl/stop_test.go
/kind cleanup
We want to use fake clocks in tests as they allow for necessary time manipulation when required.
Fixes #2287
Fixes #2353
```release-note
NONE
```
> Use the fake time instead of real in tests

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
/kind cleanup
Use clock instead time on workload controller.
Fixes #
```release-note
NONE
```
> Use clock instead time on workload controller.

- pkg/controller/admissionchecks/multikueue/controllers.go
- pkg/controller/admissionchecks/multikueue/jobset_adapter_test.go
- pkg/controller/admissionchecks/multikueue/workload.go
- pkg/controller/admissionchecks/multikueue/workload_test.go
- test/integration/multikueue/suite_test.go
/kind feature
[multikueue] Batch remote workload reconcile events.
Relates to #693 
```release-note
[multikueue] Batch remote workload reconcile events.
```
> [multikueue] Batch remote workload reconcile events.

- cmd/kueuectl/app/cmd.go
/kind bug
Remove duplication of list commands on kueuectl cli.
Fixes #
```release-note
NONE
```
> [kueuectl] Remove duplication of list commands.

- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/workload/workload.go
/kind bug
Add event for eviction on the workload.
Fixes #2012
```
Events:
Type    Reason                        Age                  From                       Message
----    ------                        ----                 ----                       -------
Normal  Pending                       3m5s (x5 over 3m5s)  kueue-admission            couldn't assign flavors to pod set main: flavor spot doesn't match node affinity, insufficient unused quota for cpu in flavor on-demand, 1 more needed. Pending the preemption of 1 workload(s)
Normal  QuotaReserved                 3m5s                 kueue-admission            Quota reserved in ClusterQueue cluster-queue, wait time since queued was 1s
Normal  EvictedDueToPodsReadyTimeout  2m5s                 kueue-workload-controller  Exceeded …
```
> Add event for eviction on the workload.

- test/integration/kueuectl/list_test.go
/kind flake
To fix "Should print workloads list with paging" test.
Fixes #2353
The order of workloads in the table is wl3, wl1, wl2, which is different that the order of workloads in the expectations. Since the creation timestamps are generated by API server they may differ, so we need to use the same order.
```release-note
NONE
```
> [kueuectl] Fix "should print workloads list with paging" test

- test/integration/multikueue/multikueue_test.go
- test/integration/multikueue/suite_test.go
Add new multikueue test without use of GC.
Allow to modify manager controller garbage collector interval to be able to disable GC.
/kind feature
We need new test to verify that synchronous object removal functionality results are not influenced by GC.
Fixes #2359
```release-note
NONE
```
> [multikueue] Add a no GC integration tests suite.

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/scheduler/scheduler.go
- pkg/util/testing/core.go
- pkg/workload/admissionchecks.go
- site/static/examples/admin/minimal-cq.yaml
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/controller/core/workload_controller_test.go
/kind feature
To unify behavior of Workloads which got an AdmissionCheck Rejected
Please wait until #2196 is merged
```release-note
A workload with a Rejected AdmissionCheck gets deactivated
```
> Deactivate Workload if any of its AdmissionCheck get Rejected

- cmd/kueuectl/app/create/create.go
- cmd/kueuectl/app/create/create_clusterqueue.go
- cmd/kueuectl/app/create/create_clusterqueue_test.go
- keps/2076-kueuectl/README.md
- site/content/en/docs/reference/kubectl-kueue/commands/create.md
- test/integration/kueuectl/create_test.go
/kind feature
Adds `kueuectl create clusterqueue` command.
Fixes #2113 
```release-note
Adds create clusterqueue command.
```
> Add create clusterqueue command

- Makefile
- cloudbuild.yaml
- hack/push-chart.sh
/kind feature
Add Helm chart repository.
Fixes #2311 
```release-note
Publish Helm charts in registry.k8s.io/kueue/charts repository
```
> Add helm chart repository

- cmd/experimental/kjobctl/README.md
- cmd/experimental/kjobctl/pkg/cmd/cmd.go
- cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
/kind feature
To use autocompletion on kjobctl.
Fixes #
```release-note
NONE
```
> [kjobctl] Added autocompletion.

- cmd/kueue/main.go
/kind bug
Initialise FairSharing option when building options for cache.
Fixes #2422 
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"kueue.x-k8s.io/v1beta1","kind":"ClusterQueue","metadata":{"annotations":{},"name":"cq-a"},"spec":{"cohort":"cohort","namespaceSelector":{},"resourceGroups":[{"coveredResources":["cpu","memory"],"flavors":[{"name":"default-flavor","resources":[{"name":"cpu","nominalQuota":9},{"name":"memory","nominalQuota":"36Gi"}]}]}]}}
creationTimestamp: "2024-06-17T11:54:20Z"
finalizers:
- kueue.x-k8s.io/resource-in-use
generation: 1
name: cq-a
resourceVersion: "1177"
uid: cd4c73e6-1ec4-4f20-9ba5-ee089272b138
spec:
cohort: cohort
flavorFungibility:
whenCanBorrow: Borrow …
```
> Initialise FairSharing option when building options for cache.

- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
/kind bug
Fixes #2391
```release-note
NONE
```
> [fix] update assignedFlavorIdx at the beginning of loop

- pkg/controller/jobs/jobset/jobset_webhook.go
- pkg/controller/jobs/jobset/jobset_webhook_test.go
- pkg/queue/manager.go
- pkg/visibility/api/rest/pending_workloads_lq.go
This is a cherry-pick of https://github.com/kubernetes-sigs/kueue/pull/2425
```release-note
Do not reject a JobSet if the corresponding cluster queue doesn't exist (when MultiKueue is enabled).
```
> [release-0.7] [MultiKueue] Do not reject JobSet when ClusterQueue does not exist

- apis/kueue/v1beta1/admissioncheck_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_admissionchecks.yaml
- config/components/crd/bases/kueue.x-k8s.io_admissionchecks.yaml
- site/content/en/docs/concepts/admission_check.md
- site/content/en/docs/reference/kueue.v1beta1.md
AdmissionCheck documentation needed an update as it was outdated. Main changes are:
- `retryDelayMinutes` field is deprecated
- AdmissionChecks can be configured per ResourceFlavor
- If AdmissionChecks gets `Rejected` a Workload is deactivated
Additionally it was lacking documentation on AdmissionCheck states (`Pending`,`Ready`, `Retry`, `Rejected`).
I've also fixed some typos.
```release-note
NONE
```
> Improve AdmissionCheck documentation

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/integration/scheduler/fairsharing/fair_sharing_test.go
/kind bug
Fix panic when there is not enough quota to assign flavors to a Workload in the cohort, when FairSharing is enabled.
Fixes #
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2439/pull-kueue-test-integration-main/1803339372448190464
```
goroutine 369 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x23ff460, 0x420acc0})
/go/pkg/mod/k8s.io/apimachinery@v0.30.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0007ba8c0?})
/go/pkg/mod/k8s.io/apimachinery@v0.30.2/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x23ff460?, 0x420acc0?})
/usr/local/go/src/runtime/panic.go:770 +0x132
sigs.k8s.io/kueue/pkg/scheduler/flavorassigner.(*Assignment).TotalRequestsFor(...) …
```
> Fix panic when not enough quota on FairSharing enabled.

- test/e2e/config/controller_manager_config.yaml
- test/e2e/singlecluster/fair_sharing_test.go
/kind feature
A simple e2e test scenario for fair sharing. We need it to gain confidence that fair sharing works as expected at the user-facing level.
Fixes #2431 
```release-note
NONE
```
> Create e2e test suite for fair sharing.

- test/integration/kueuectl/create_test.go
/kind bug
We need to clear cluster queues after each test cases on "Creating a ClusterQueue" tests to fix "Should print cluster queues list with paging" integration test and don't show this cluster queues on the list.
Fixes #2454 
```release-note
NONE
```
> [kueuectl] Clearing cluster queues after each creation on "Creating a ClusterQueue" tests.

- pkg/cache/cache.go
- pkg/controller/core/clusterqueue_controller.go
- pkg/controller/core/clusterqueue_controller_test.go
- pkg/queue/manager.go
/kind bug
Fix panic on update cluster queue status if cluster queue not found on queue manager.
Fixes #2459
```release-note
Fix panic that could occur when a ClusterQueue is deleted while Kueue was updating the ClusterQueue status.
```
> Fix panic on update cluster queue status if cluster queue not found on queue manager.

- pkg/queue/cluster_queue.go
/kind bug
Fix race condition on delete workload from queue manager.
Fixes #
I found it locally when test using `golang.org/x/tools/cmd/stress`.
```
WARNING: DATA RACE
Write at 0x00c0012ad0b0 by goroutine 1313:
runtime.mapassign_faststr()
/Users/mykhailo_bobrovskyi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/runtime/map_faststr.go:203 +0x41c
sigs.k8s.io/kueue/pkg/queue.(*ClusterQueue).Delete()
/Users/mykhailo_bobrovskyi/Projects/epam/kueue/pkg/queue/cluster_queue.go:194 +0x10c
sigs.k8s.io/kueue/pkg/queue.(*Manager).deleteWorkloadFromQueueAndClusterQueue()
/Users/mykhailo_bobrovskyi/Projects/epam/kueue/pkg/queue/manager.go:377 +0x1c4
sigs.k8s.io/kueue/pkg/queue.(*Manager).DeleteWorkload()
/Users/mykhailo_bobrovskyi/Projects/epam/kueue/pkg/queue/manager.go:365 +0xec …
```
> Fix race condition on delete workload from queue manager.

- test/e2e/multikueue/suite_test.go
- test/e2e/singlecluster/suite_test.go
- test/util/e2e.go
/kind bug
/kind flake
Wait for jobset operator ready before start e2e tests.
Fixes #2428
```release-note
NONE
```
> Wait for jobset operator on starting e2e tests.

- test/e2e/multikueue/suite_test.go
- test/e2e/singlecluster/suite_test.go
- test/util/e2e.go
Cherry pick of #2456 on release-0.7.
#2456: Wait for jobset operator on starting e2e tests.
```release-note
NONE
```
> Automated cherry pick of #2456: Wait for jobset operator on starting e2e tests.

- test/util/e2e.go
/kind cleanup
No need to wait for availability if controller manager restarts.
Fixes #
Follow up for #2456
```release-note
NONE
```
> No need to wait for availability if controller manager restarts.

- cmd/kueue/main.go
/kind feature
Use a single rate limiter across all API types.
Fixes #2423
```release-note
Use a single rate limiter for all API types clients.
ACTION REQUIRED: Consider adjusting `clientConnection.qps` and `clientConnection.burst` if you observe any performance degradation.
```
> [cmd/kueue] Use a single rate limiter across all API types.

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/controller/admissionchecks/provisioning/provisioning.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/controller/admissionchecks/provisioning/suite_test.go
/kind bug
To fix race condition when setting MaxRetries on provisioning controller.
Fixes #2470
```release-note
NONE
```
> Fix race condition when setting MaxRetries on provisioning controller.

- apis/kueue/v1beta1/workload_types.go
- pkg/controller/core/workload_controller.go
- pkg/controller/core/workload_controller_test.go
- pkg/workload/workload.go
- test/integration/controller/jobs/job/job_controller_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/scheduler/podsready/scheduler_test.go
/kind feature
Added a new Workload condition called DeactivationTarget that would signalise that a Workload which has this condition should be deactivated. This condition is temporary, so it should be removed after deactivation.
Fixes #2388 
```release-note
NONE
```
> Add a new DeactivationTarget workload condition.

- .golangci.yaml
- pkg/controller/core/workload_controller.go
/kind cleanup
This PR refactors `queueReconcileForWorkloadsOfClusterQueue` to avoid using nested contexts, as it has become unwieldy. This issue was identified by the `fatcontext` linter.
We don't need nested context in our case `ctx = ctrl.LoggerInto(ctx, log)`.
Also, nested contexts may cause performance issues. See more about fat contexts here https://gabnotes.org/fat-contexts/
```release-note
Fix performance issue in logging when processing LocalQueues.
```
> Fix lint issue reported by fatcontext

- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind bug
Fixes #2483 
There was a race condition and the AdmissionCheck didn't get `Ready` state before finishing a Workload. 
Also fixed typos and test case description.
```release-note
NONE
```
> Fix flaky integration test for ProvisioningRequest

- pkg/controller/core/workload_controller.go
/kind bug
Cherry-picking from #2485
Cherry-picking is done manually due to conflicts https://github.com/kubernetes-sigs/kueue/pull/2485#issuecomment-2195064130
I can't enable `fatcontext` because the linter requires golangci-lint v1.58.0 but `release-0.7` has v1.57.2.
```release-note
Fix performance issue in logging when processing LocalQueues.
```
> Fix nested context in loop

- cmd/experimental/podtaintstolerations/controller/pod_jobs.go
/kind bug
try to run the pod taints tolerations example but not able to build the image.
Getting following error:
```
#7 88.17 ./main.go:38:18: invalid operation: cannot take address of controller.AdmissionTaintKey (untyped string constant "kueue.x-k8s.io/kueue-admission")
```
Fixes #
```release-note
NONE
```
> fix build error in pod taints tolerations example

- pkg/podset/podset.go
- pkg/podset/podset_test.go
- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
Skip duplicate Tolerations during PodSetInfo merge.
Fixes #2427
```release-note
Skip duplicate Tolerations when an admission check introduces a toleration that the job also set.
```
> [PodSetInfo] Skip duplicate Tolerations during merge.

- .golangci.yaml
- cmd/kueue/main.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/visibility/server.go
- test/integration/controller/admissionchecks/provisioning/suite_test.go
- test/integration/controller/core/suite_test.go
- test/integration/controller/jobs/job/suite_test.go
- test/integration/controller/jobs/jobset/suite_test.go
- test/integration/controller/jobs/mpijob/suite_test.go
- test/integration/controller/jobs/mxjob/suite_test.go
- test/integration/controller/jobs/paddlejob/suite_test.go
- test/integration/controller/jobs/pod/suite_test.go
- test/integration/controller/jobs/pytorchjob/suite_test.go
- test/integration/controller/jobs/raycluster/suite_test.go
- test/integration/controller/jobs/rayjob/suite_test.go
- test/integration/controller/jobs/tfjob/suite_test.go
- test/integration/controller/jobs/xgboostjob/suite_test.go
- test/integration/framework/framework.go
- test/integration/importer/suite_test.go
- test/integration/kueuectl/suite_test.go
- test/integration/multikueue/suite_test.go
- test/integration/scheduler/fairsharing/suite_test.go
- test/integration/scheduler/podsready/suite_test.go
- test/integration/scheduler/suite_test.go
- test/integration/webhook/suite_test.go
/kind cleanup
This cosmetic PR rearranges function parameters to pass `context.Context` as their first parameter.
From the [Go CodeReviewComments](https://go.dev/wiki/CodeReviewComments#contexts):
> Most functions that use a Context should accept it as their first parameter:
>
> ```
> func F(ctx context.Context, /* other arguments */) {}
> ```
```release-note
NONE
```
> Refactor funcs to accept a Context as first parameter

- cmd/importer/pod/check.go
- cmd/importer/pod/import.go
/kind cleanup
Corrects spelling mistake in the log field `observedFirstIn`.
```release-note
Importer: corrects the field name `observedFirstIn` in logs.
```
> [importer] fix typo in log field name

- pkg/cache/snapshot.go
- pkg/scheduler/logging.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
manual cherry pick of #2504.
```release-note
Improved logging for scheduling and preemption in levels 4 and 5
```
> cherry-pick #2504 to 0.7

- cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
/kind feature
By default, plugins that use [client-go](https://godoc.org/k8s.io/client-go) cannot authenticate to Kubernetes clusters on many cloud providers. To address this need to include auth package.
Fixes #
```release-note
NONE
```
> [kjobctl] Import authentication plugins.

- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/util/testing/wrappers.go
/kind cleanup
We update the FlavorAssignerTest to use Kueue API types, rather than construct CQ/Cohort snapshot manually. This will allow us to change CQ/Cohort Snapshot logic without updating the tests each time.
Preparation for main changes in #79
```release-note
NONE
```
> Use Kueue API types in FlavorAssignerTest

- apis/kueue/v1beta1/clusterqueue_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
/kind bug
A zero value for weightedShare should be visible in the API, as it has the meaning that the CQ is not borrowing.
Fixes #
```release-note
Show weightedShared in ClusterQueue status even if the value is zero
```
> Do not omit weightedShare when zero

- apis/kueue/v1beta1/resourceflavor_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_resourceflavors.yaml
- cmd/kueuectl/app/passthrough/passthrough.go
- config/components/crd/bases/kueue.x-k8s.io_resourceflavors.yaml
- keps/2076-kueuectl/README.md
- site/content/en/docs/reference/kubectl-kueue/commands/passthrough.md
- test/integration/kueuectl/passthrough_test.go
/kind feature
Add resourceflavor to pass-through commands.
Fixes #
```release-note
CLI: Added resourceflavor to pass-through commands.
```
> [kueuectl] Add resourceflavor to pass-through commands.

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
/kind bug
The existing check that prevents borrowing when preempting didn't take in consideration that a workload could explicitly request 0 for a resource in a ClusterQueue that is at or over nominal quota.
Fixes #
```release-note
Fix check that prevents preemptions when a workload requests 0 for a resource that is at nominal or over it.
```
> Fix preemption when requesting 0 of a resource at nominal quota

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
Cherry pick of #2520 on release-0.7.
#2520: Fix preemption when requesting 0 of a resource at nominal
```release-note
Fix check that prevents preemptions when a workload requests 0 for a resource that is at nominal or over it.
```
> Automated cherry pick of #2520: Fix preemption when requesting 0 of a resource at nominal

- test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Extend the time we are waiting for an ungated pod to get a node assignment and move out of Pending phase.
Fixes #2529 
```release-note
None
```
> [e2e/pod] Extend the waiting for node assignment of an ungated pod.

- pkg/controller/admissionchecks/multikueue/multikueuecluster.go
- pkg/util/maps/maps.go
/kind bug
Fix race condition on run garbage collection in multikueuecluster reconciler.
Fixes #
Related with #2468.
This error happens  when running test-integration with --race flag.
```
WARNING: DATA RACE
Write at 0x00c000b6e570 by goroutine 526:
runtime.mapassign_faststr()
/usr/local/go/src/runtime/map_faststr.go:203 +0x0
sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue.(*clustersReconciler).setRemoteClientConfig()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/multikueuecluster.go:368 +0x32d
sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue.(*clustersReconciler).Reconcile()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/controller/admissionchecks/multikueue/multikueuecluster.go:416 +0x454 …
```
> Fix race condition on run garbage collection in multikueuecluster reconciler.

- pkg/scheduler/scheduler.go
- pkg/workload/workload.go
/kind bug
Fix race condition on requeueAndUpdate.
Fixes #
Related with #2468.
This error happens  when running test-integration with --race flag.
```
==================
WARNING: DATA RACE
Read at 0x00c0012d79f0 by goroutine 288:
sigs.k8s.io/kueue/pkg/queue.(*ClusterQueue).PushOrUpdate()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/cluster_queue.go:156 +0x428
sigs.k8s.io/kueue/pkg/queue.(*Manager).AddOrUpdateWorkloadWithoutLock()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:329 +0x26b
sigs.k8s.io/kueue/pkg/queue.(*Manager).UpdateWorkload()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/queue/manager.go:474 +0x24e
sigs.k8s.io/kueue/pkg/controller/core.(*WorkloadReconciler).Update()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/controller/core/workload_controller.go:678 +0x136b …
```
> Fix race condition on requeueAndUpdate.

- Makefile-test.mk
/kind cleanup
Runs the race detector and emits any detected race conditions as the suite runs. If any are detected the suite is marked as failed.
Fixes #
Follow up for https://github.com/kubernetes-sigs/kueue/pull/2460#issuecomment-2182995768.
```release-note
NONE
```
> Runs the race detector on integration tests.

- pkg/scheduler/scheduler_test.go
/kind cleanup
Adds test case for undertested feature of flavor fungibility when `whenCanBorrow` and `whenCanPreempt` are both set to `TryNextFlavor`.
In the test case, it's not possible to borrow or preempt in the second flavor, but it's possible to preempt in the first flavor.
Fixes #
```release-note
NONE
```
> Add test case for TryNextFlavor but flavor is full

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_snapshot.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/cohort_snapshot.go
- pkg/cache/resource.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/resources/resource.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
/kind cleanup
Preparation for #79. Create Snapshot types for CQ and Cohort, to better differentiate between Cache types. We were currently relying on fields properly being set/copied, and some fields not being set.
This change will make the code easier to understand and less error prone.
Unexporting Cohort/ClusterQueue works trivially. I will send this out in a subsequent PR.
Additionally, I didn't move methods that operate on ClusterQueueSnapshot to the new file, to keep the diff smaller. These can be moved in a subsequent PR if we wish.
Also folding https://github.com/kubernetes-sigs/kueue/pull/2489 into this change.
```release-note
NONE
```
> Define ClusterQueueSnapshot and CohortSnapshot types

- test/e2e/singlecluster/pod_test.go
The time could be increased due to the fact that is out of Kueue's control. 
As the process is controlled by the Kubernetes.
The change does not affect happy path.
/kind flake
Fixes #2429
```release-note
NONE
```
> Increase waiting time to verify workload completion.

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_multikueue_adapter.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
- pkg/util/client/client.go
/kind bug
Use `Patch` instead of `Update` on jobframework to prevent the risk of dropping fields.
Fixes #2269
```release-note
Use Patch instead of Update on jobframework to prevent the risk of dropping fields.
```
> Use Patch instead of Update on jobframework.

- CHANGELOG/CHANGELOG-0.7.md
- Makefile
- README.md
- charts/kueue/Chart.yaml
- site/hugo.toml
Part of #2542
```release-note
NONE
```
> Prepare release v0.7.1

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/resources/requests.go
- pkg/resources/resource.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/scheduler.go
- pkg/webhooks/workload_webhook.go
- pkg/workload/resources_test.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
/kind cleanup
Break the dependency of `requests` package on `workload`, so we can continue updating usages to requests.FlavorResourceQuantitiesFlat #2447
```release-note
NONE
```
> Move Requests from workload to resources package

- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/preemption/preemption.go
- pkg/workload/workload.go
- pkg/workload/workload_test.go
/kind cleanup
`FlavorResourceUsage` will be used in subsequent PR to simplify logic, e.g. [here](https://github.com/kubernetes-sigs/kueue/blob/e1e6c59bfaf71c89d0fad02ed6c130a8b9de71c0/pkg/cache/clusterqueue.go#L476-L511)
see detailed motivation in #2447
```release-note
NONE
```
> Flatten several usages of FlavorResourceQuantities

- CHANGELOG/CHANGELOG-0.7.md
- Makefile
- README.md
- SECURITY-INSIGHTS.yaml
- charts/kueue/Chart.yaml
- site/hugo.toml
Cherry pick of #2555 on website.
#2555: Update latest version to v0.7.1
```release-note
```
> Automated cherry pick of #2555: Update latest version to v0.7.1

- cmd/kueuectl/app/create/create.go
- cmd/kueuectl/app/create/create_resourceflavor.go
- cmd/kueuectl/app/create/create_resourceflavor_test.go
- keps/2076-kueuectl/README.md
- site/content/en/docs/reference/kubectl-kueue/_index.md
- site/content/en/docs/reference/kubectl-kueue/commands/create.md
- test/integration/kueuectl/create_test.go
/kind feature
Add `kueuectl create resourceflavor` command.
Fixes #
```release-note
CLI: Added create resourceflavor command.
```
> [kueuectl] Add create resourceflavor command.

- site/assets/scss/_styles_project.scss
- site/content/en/docs/concepts/cluster_queue.md
- site/content/en/docs/concepts/multikueue.md
- site/content/en/docs/concepts/preemption.md
- site/content/en/docs/installation/_index.md
- site/content/en/docs/tasks/dev/enabling_pprof_endpoints.md
- site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_in_status.md
- site/content/en/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand.md
- site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
- site/layouts/shortcodes/feature-state.html
/kind feature
Adds a feature-state component similar to what we have on the kubernetes website for marking the minimum version of kubernetes supported.
Fixes #2325
```release-note
NONE
```
> Add reusable feature-state component

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobframework/reconciler.go
- pkg/controller/jobs/job/job_controller.go
- pkg/controller/jobs/job/job_multikueue_adapter.go
- pkg/controller/jobs/jobset/jobset_controller.go
- pkg/controller/jobs/jobset/jobset_multikueue_adapter.go
- pkg/util/client/client.go
/kind bug
Reverts kubernetes-sigs/kueue#2501
Part of #2269
```release-note
NONE
```
> Revert "Use Patch instead of Update on jobframework."

- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/controller/admissionchecks/provisioning/provisioning.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind feature
Provide support for the new ProvisioningRequest's condition `BookingExpired`. When a Workload is Admitted this Condition has no effect. If Workload is still waiting for admission due to others AdmissionChecks running, then with respect to retry policy it, the Provisioning AdmissionCheck gets retried or rejected.
Fixes #2041 
```release-note
Kueue now supports ProvisioningRequest's condition `BookingExpired`
```
> Provide support for ProvisioningRequest's BookingExpired condition 

- cmd/experimental/kjobctl/pkg/cmd/cmd.go
- cmd/experimental/kjobctl/pkg/cmd/list/helpers.go
- cmd/experimental/kjobctl/pkg/cmd/list/list.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_job_printer.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_job_test.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
- cmd/experimental/kjobctl/pkg/cmd/util/helpers.go
- cmd/experimental/kjobctl/pkg/testing/wrappers/job_wrappers.go
- cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go
/kind feature
Add list job on kjobctl.
Fixes #
```release-note
NONE
```
> [kjobctl] Add list job

- pkg/scheduler/logging.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
- test/integration/scheduler/preemption_test.go
- test/util/util.go
/kind feature
Introduces an additional reason in the Preemption condition to indicate that the preemption was due to fair sharing and not regular reclamation.
Fixes #2404
```release-note
More granular Preemption condition reasons: PriorityReclamation, InCohortReclamation, InCohortFairSharing, InCohortReclaimWhileBorrowing
```
> Distinguish between Preemption due to reclamation and fair sharing

- pkg/controller/jobs/job/job_controller.go
- test/integration/controller/jobs/job/job_controller_test.go
/kind bug
To fix an issue that didn't allow to retry reset start time and restore info after error on stop job.
Fixes #2566
```release-note
Fixed issue that prevented restoring the startTime and pod template when evicting a batch/v1 Job, if any API errors happened in the process
```
> Retry to reset start time and restore info after error on stop job.

- cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
/kind cleanup
To avoid exits the test process before reporting the status we need to avoid `cobra.CheckErr`. Instead that we can use `RunE` and `cmd.SilenceUsage = true`.
Fixes #
```release-note
NONE
```
> [kjobctl] Use RunE instead Run in list job command.

- cmd/kueuectl/app/version/version.go
/kind cleanup
Removed `[flags]` suffix in use line on kueuectl version command. It's not need because we don't have flags for this command.
Fixes #
```release-note
NONE
```
> [kueuectl] Removed [flags] suffix in use line on version command.

- cmd/kueuectl/app/create/create_clusterqueue.go
- cmd/kueuectl/app/create/create_localqueue.go
- cmd/kueuectl/app/list/list_clusterqueue.go
- cmd/kueuectl/app/list/list_localqueue.go
- cmd/kueuectl/app/list/list_resourceflavor.go
- cmd/kueuectl/app/list/list_workload.go
- cmd/kueuectl/app/passthrough/passthrough.go
- cmd/kueuectl/app/resume/resume_clusterqueue.go
- cmd/kueuectl/app/resume/resume_localqueue.go
- cmd/kueuectl/app/resume/resume_workload.go
- cmd/kueuectl/app/stop/stop_clusterqueue.go
- cmd/kueuectl/app/stop/stop_localqueue.go
- cmd/kueuectl/app/stop/stop_workload.go
- cmd/kueuectl/app/version/version.go
/kind cleanup
To avoid exits the test process before reporting the status we need to avoid `cobra.CheckErr`. Instead that we can use `RunE` and `cmd.SilenceUsage = true`.
Fixes #
```release-note
NONE
```
> [kueuectl] Use RunE instead Run in commands.

- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobframework/integrationmanager_test.go
- pkg/controller/jobframework/reconciler_test.go
- pkg/controller/jobframework/setup.go
- pkg/controller/jobframework/setup_test.go
- pkg/controller/jobs/job/job_controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/job/suite_test.go
- test/integration/controller/jobs/mpijob/suite_test.go
- test/integration/controller/jobs/pod/suite_test.go
- test/integration/controller/jobs/raycluster/suite_test.go
/kind feature
Only check if the owner of a job is managed against the list of  jobs integrations currently enabled .
Fixes #2481
```release-note
Allow usage of the pod integration for pods belonging to jobs that Kueue supports, if the support for the job type is explicitly disabled
```
> [jobframework] Only check if the owner is managed for enabled integrations.

- cmd/kueuectl/app/util/client_getter.go
/kind feature
By default, plugins that use [client-go](https://godoc.org/k8s.io/client-go) cannot authenticate to Kubernetes clusters on many cloud providers. To address this need to include auth package.
Fixes #
```release-note
CLI: Fixed no Auth Provider found for name "oidc" error.
```
> [kueuectl] Import auth plugins for K8s

- cmd/kueuectl/app/util/client_getter.go
Cherry pick of #2602 on release-0.7.
#2602: Import auth plugins for K8s
```release-note
CLI: Fixed no Auth Provider found for name "oidc" error.
```
> Automated cherry pick of #2602: Import auth plugins for K8s

- test/e2e/singlecluster/visibility_test.go
/kind bug
Fix "There are pending workloads due to capacity maxed by the admitted job" e2e test.
Fixes #2581
```release-note
NONE
```
> Fixed "There are pending workloads due to capacity maxed by the admitted job" e2e test.

- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
/kind bug
Wait for removing "spot-untainted" `ResourceFlavor ` on "Job controller interacting with scheduler" test.
Fixes #2599
```release-note
NONE
```
> Wait for removing "spot-untainted" ResourceFlavor on Job controller interacting with scheduler test.

- site/content/en/docs/tasks/manage/setup_job_admission_policy.md
- site/static/examples/sample-validating-policy-binding.yaml
- site/static/examples/sample-validating-policy.yaml
Making the example policy be "opt-in" instead of "opt-out" seems more likely to be useful to users trying to adapt the example to their own use cases. 
Fixes #
```release-note
NONE
```
> Change example Job Admission Policy to use matchLabels

- apis/kueue/v1beta1/workload_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_workloads.yaml
- config/components/crd/bases/kueue.x-k8s.io_workloads.yaml
/kind feature
When retrieving information about workload resources via the kubectl get command, we are unable to determine whether the workload had completed. It would be more convenient to know if the workload had finished.
Fixes #2609 
```release-note
Add a column to workload indicating if it is finished 
```
> feat: Add a column to workload indicating if it is finished

- test/e2e/singlecluster/e2e_test.go
- test/e2e/singlecluster/jobset_test.go
/kind bug
Force remove workloads before removing ClusterQueues in AfterEach e2e tests.
Fixes #2620
Fixes #2621
We already fixed similar issue for visibility #2608.
```release-note
NONE
```
> Force remove workloads before removing ClusterQueues in AfterEach e2e tests.

- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind cleanup
Simplify cohortsUsage, by no longer taking it as a pointer receiver. We also change it to `FlavorResourceQuantitiesFlat`, so we no longer have to do allocations/null checks inside of loops.
Make more progress towards flattening `FlavorResourceQuantities` #2447
```release-note
NONE
```
> Simplify scheduler.cohortsUsage; Cleanup FlavorResourceQuantities

- test/e2e/singlecluster/e2e_test.go
- test/e2e/singlecluster/jobset_test.go
Cherry pick of #2623 on release-0.7.
#2623: Force remove workloads before removing ClusterQueues in
```release-note
NONE
```
> Automated cherry pick of #2623: Force remove workloads before removing ClusterQueues in

- test/e2e/singlecluster/visibility_test.go
Cherry pick of #2608 on release-0.7.
#2608: Fixed "There are pending workloads due to capacity maxed by
```release-note
NONE
```
> Automated cherry pick of #2608: Fixed "There are pending workloads due to capacity maxed by

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- test/integration/scheduler/preemption_test.go
/kind bug
If allowBorrowingBelowPriority is nil, then the reason should stay as InCohortReclamationReason
Fixes https://github.com/kubernetes-sigs/kueue/issues/2404
```release-note
NONE
```
> Fix detailed preemption reason bug

- .golangci.yaml
- cmd/experimental/kjobctl/.golangci.yaml
- cmd/experimental/kjobctl/apis/v1alpha1/job_template_types.go
- cmd/experimental/kjobctl/pkg/builder/builder.go
- cmd/kueuectl/app/version/version.go
- cmd/kueuectl/app/version/version_test.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
- pkg/util/priority/priority_test.go
- pkg/visibility/api/install.go
- pkg/visibility/api/rest/pending_workloads_cq_test.go
- pkg/visibility/api/rest/pending_workloads_lq_test.go
/kind cleanup
Add redundant-import-alias check on .golangci.yaml.
Fixes #
```release-note
NONE
```
> Add redundant-import-alias check on .golangci.yaml.

- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
- pkg/resources/resource.go
- pkg/resources/resource_test.go
/kind cleanup
Preparation for #2596, where we want to add usage to Cohort without needing a workload. See [WIP Commit](https://github.com/gabesaba/kueue/commit/c3277c97cadc5653505b6a86add07d0c1f1b5dc6) for example of intended usage.
Additionally, gets us closer to #2447 cleanup.
```release-note
NONE
```
> Refactor update(Flavor|Cohort)Usage to take FlavorResourceQuantitiesFlat

- pkg/visibility/server.go
/kind feature
Add logic that allow to crash server on error in CreateAndStartVisibilityServer.
Fixes #2634
```release-note
Do not start Kueue when the visibility server cannot be started, but is requested.
```
> Do not start Kueue when the visibility server cannot be started

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/scheduler/preemption/preemption.go
- test/integration/scheduler/preemption_test.go
- test/util/util.go
/kind feature
Adds a metric that tracks the number of preemptions issued by a ClusterQueue
Fixes #2491
NONE
```release-note
Add preempted_workloads_total metric that tracks the number of preemptions issued by a ClusterQueue)
```
> Add a metric that tracks the number of preemptions issued by a ClusterQueue

- test/performance/scheduler/checker/checker_test.go
- test/performance/scheduler/default_rangespec.yaml
/kind bug
/kind flake
Adjusted ClusterQueueClassesMinUsage due to experienced failures.
Fixes #2638
```release-note
NONE
```
> [performance] Relax ClusterQueueClassesMinUsage.

- cmd/kueue/main.go
/kind cleanup
Remove unnecessary wrappers for goroutines.
Fixes #
```release-note
NONE
```
> Remove unnecessary wrappers for goroutines.

- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/workload/admissionchecks_test.go
- pkg/workload/workload_test.go
/kind bug
Fixed "deleted unschedulable pods are finalized" unit test.
Fixes #2635
```release-note
NONE
```
> Fixed deleted unschedulable pods are finalized unit test.

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind bug
Reverts single line in https://github.com/kubernetes-sigs/kueue/pull/2622/files#r1684180659, which introduced a logic change. After this change, multiple preemption is allowed in the case where usage is greater than nominal. See [comment thread](https://github.com/kubernetes-sigs/kueue/pull/2641#discussion_r1684183635) for explaination.
This may not be a regression, but reverting this to preserve old behavior
```release-note
NONE
```
> Revert check in hasCommonFlavorResources

- pkg/cache/clusterqueue_snapshot.go
- pkg/features/kube_features.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- site/content/en/docs/installation/_index.md
/kind feature
When scheduling a `Preempt` workload, if conflicting workload (same cohort, overlapping resource flavors) was processed before, we would skip this preemption as our calculations [were invalidated](https://github.com/kubernetes-sigs/kueue/blob/1b8ec34eca4d07af9e91c22f163e90567226c5c7/pkg/scheduler/scheduler.go#L220-L222).
In this PR, we introduce less conservative calculations, to allow multiple preemptions within a cohort within one cycle, as long as the preemption targets do not overlap, and the workload still fits.
Additionally, we allow a `Preempt` fit workload to proceed, even if a `Fit` mode workload was previously processed, as long as the workload still fits.
Finally we improve logging in the old logic, to differentiate "No Longer Fits" from "Preemptions Invalidated" …
> Enable Multiple Preemptions within Cohort in a single Scheduling Cycle

- site/content/en/docs/concepts/cluster_queue.md
- site/content/en/docs/concepts/resource_flavor.md
- site/content/en/docs/tasks/manage/setup_wait_for_pods_ready.md
- site/content/en/docs/tasks/run/jobs.md
- site/content/en/docs/tasks/run/plain_pods.md
Using docsy instead GitHub style Note.
Fixes #1755
```release-note
NONE
```
> [website] Using docsy instead GitHub style Note.

- test/performance/scheduler/default_rangespec.yaml
/kind bug
/kind flake
Bump scalability workload classes large ms.
Fixes #2667
```release-note
NONE
```
> [performance] Bump scalability workload classes large ms.

- pkg/scheduler/scheduler.go
/kind cleanup
Get rid of vscode annoying underlying :) 
Fixes #
```release-note
NONE
```
> Cleanup typo faPreemtionTargets -> faPreemptionTargets

- .github/ISSUE_TEMPLATE/NEW_RELEASE.md
- Makefile
- Makefile-test.mk
- charts/kueue/README.md
- charts/kueue/values.yaml
- cloudbuild.yaml
- cmd/importer/README.md
- cmd/importer/run-in-cluster/kustomization.yaml
- config/components/manager/kustomization.yaml
- hack/dump_cache.sh
- hack/push-chart.sh
/kind feature
As discussed in https://github.com/kubernetes-sigs/kueue/pull/2377#issuecomment-2179242565 and https://kubernetes.slack.com/archives/CCK68P2Q2/p1718819420490889, we should start publishing Kueue images to `us-central1-docker.pkg.dev/k8s-staging-images/kueue`. 
Moreover, once https://github.com/kubernetes/k8s.io/pull/6910 is merged, we're going to have a staging repo for charts in `us-central1-docker.pkg.dev/k8s-staging-images/charts`.
Relates to #2377 
```release-note
NONE
```
> Publish images to new staging registry

- site/content/en/docs/tasks/run/jobsets.md
- site/content/en/docs/tasks/run/kubeflow/mpijobs.md
- site/content/en/docs/tasks/run/kubeflow/mxjobs.md
- site/content/en/docs/tasks/run/kubeflow/paddlejobs.md
- site/content/en/docs/tasks/run/kubeflow/pytorchjobs.md
- site/content/en/docs/tasks/run/kubeflow/tfjobs.md
- site/content/en/docs/tasks/run/kubeflow/xgboostjobs.md
- site/content/en/docs/tasks/run/rayclusters.md
- site/content/en/docs/tasks/run/rayjobs.md
To avoid users confusion when the CRDs don't work. 
This is needed until https://github.com/kubernetes-sigs/kueue/issues/2414 is fixed
Related to https://github.com/kubernetes-sigs/kueue/issues/2414
We can remove the notes once the issue is fixed, if cherry-picked. If not cherry-picked, we can update the docs to say that this is needed prior to 0.9.
```release-note
NONE
```
> Add a note about the need to restart the kueue pod

- charts/kueue/templates/manager/manager.yaml
/kind bug
Fix "unclosed action" error.
Fixes #2682
This issue reproduced with helm v3.5.2.
```release-note
Helm: Fix a bug for "unclosed action error".
```
> Fix unclosed action error.

- pkg/cache/clusterqueue_test.go
/kind cleanup
We sometimes manipulate the internal accounting of ClusterQueue and Cohort snapshots. This is brittle. Quota/Lending Limit/Borrowing Limit/Usage should be set by calling public api methods, or by defining the CQs/Cohorts via API objects, adding to cache, and creating snapshot.
#2502
This PR is part of https://github.com/kubernetes-sigs/kueue/issues/2502. Refactor for `flavorassigner_test.go` will be done in a separate PR.
```release-note
NONE
```
> fix: Refactor FitInCohort tests

- README.md
We already have gotten rid of the e2e test for the 1.25 and 1.26, and added the e2e for the 1.28, 1.29, and 1.30.
Fixes #
```release-note
NONE
```
> Doc: Update the outdated production readiness statues section

- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
/kind cleanup
Simplifies code and brings us closer to #2447
```release-note
NONE
```
> Cleanup to use FlavorResourceQuantities.Add in cache

- test/integration/controller/jobs/jobset/jobset_controller_test.go
/kind feature
Add tests for jobset preemption due to insufficient coverage.
#1463 
This PR is part of #1463.  Tests for multiple jobsets and jobsets with timeouts will be done in a separate PR.
```release-note
NONE
```
> feat: Add integration test for jobset preemption

- cmd/kueuectl/app/create/create_clusterqueue.go
- cmd/kueuectl/app/create/create_clusterqueue_test.go
/kind bug
Fix resource flavor name pattern used on `create clusterqueue` to better support [DNS Subdomain Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)
Fixes #2701
```release-note
CLI: Support `-` and `.` in the resource flavor name on `create cq`
```
> [kueuectl] Fix resource flavor name pattern on create cq

- keps/1833-metrics-for-local-queue/README.md
- keps/1833-metrics-for-local-queue/kep.yaml
/kind feature
This PR introduces an enhancement to enable collection of prometheus metrics for local queues.
Addresses issue: https://github.com/kubernetes-sigs/kueue/issues/1833
Fixes # Partially #1833
```release-note
NA
```
> [Feature] Enable prometheus metrics for local queues

- cmd/experimental/kjobctl/docs/commands/kjobctl_describe/_index.md
- cmd/experimental/kjobctl/pkg/cmd/cmd.go
- cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
- cmd/experimental/kjobctl/pkg/cmd/describe/describe_printer.go
- cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
- cmd/experimental/kjobctl/pkg/cmd/describe/helpers.go
- cmd/experimental/kjobctl/pkg/cmd/testing/fake.go
- cmd/experimental/kjobctl/pkg/cmd/util/client_getter.go
/kind feature
Add `describe` job command to kjobctl. 
Fixes #
```release-note
None
```
> [kjobctl] Add describe job

- Makefile-test.mk
- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- hack/e2e-common.sh
- hack/multikueue-e2e-test.sh
- pkg/controller/admissionchecks/multikueue/indexer_test.go
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter.go
- pkg/controller/jobs/kubeflow/jobs/tfjob/tfjob_multikueue_adapter_test.go
- pkg/util/testingjobs/tfjob/wrappers_tfjob.go
- site/content/en/docs/concepts/multikueue.md
- site/content/en/docs/tasks/manage/setup_multikueue.md
- site/static/examples/multikueue/create-multikueue-kubeconfig.sh
- test/e2e/multikueue/e2e_test.go
- test/e2e/multikueue/suite_test.go
- test/integration/controller/jobs/tfjob/tfjob_controller_test.go
- test/integration/multikueue/multikueue_test.go
- test/integration/multikueue/suite_test.go
- test/util/e2e.go
/kind feature
The PR introduces a new Multikueue adapter to handle TFJob (Kubeflow).
We want to extend Multikueue capabilities to satisfy the needs of early adopters.
Relates #2552
```release-note
NONE
```
> Support TFJob(kubeflow) in Multikueue

- pkg/controller/admissionchecks/provisioning/constants.go
- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
/kind cleanup
To be compatible with the latest version of the Cluster Autoscaler
Fixes #
```release-note
NONE
```
> Support for new ProvisioningRequest annotations

- pkg/util/testingjobs/pod/wrappers.go
- test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
To fix "Failed Pod can be replaced in group" flaky test.
Fixes #2729
Sometimes kubernetes don't have time to terminate all containers and change phase from `Pending` to `Failed`. It's not scope of kueue so we can set `LongTimeout`.
```release-note
NONE
```
> Fix "Failed Pod can be replaced in group" flaky test.

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter.go
- pkg/controller/jobs/kubeflow/jobs/paddlejob/paddlejob_multikueue_adapter_test.go
- pkg/util/testingjobs/paddlejob/wrappers.go
- site/static/examples/multikueue/create-multikueue-kubeconfig.sh
- test/e2e/multikueue/e2e_test.go
- test/e2e/multikueue/suite_test.go
- test/integration/controller/jobs/paddlejob/paddlejob_controller_test.go
- test/integration/multikueue/multikueue_test.go
- test/integration/multikueue/suite_test.go
/kind feature
The PR introduces a new MultiKueue adapter to handle PaddleJob (Kubeflow).
We want to extend MultiKueue capabilities to satisfy the needs of early adopters.
Relates #2552
```release-note
MultiKueue: Support for the Kubeflow PaddleJob
```
> Provide Kubeflow PaddleJob support for MultiKueue

- test/performance/scheduler/default_rangespec.yaml
/kind cleanup
I relaxed the CPU usage threshold for the perftest for avoiding the flaky test.
Fixes #2755
```release-note
NONE
```
> Relax the CPU threshhold for the perftest

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorch_multikueue_adapter_test.go
- pkg/controller/jobs/kubeflow/jobs/pytorchjob/pytorchjob_controller.go
- pkg/util/testingjobs/pytorchjob/wrappers_pytorchjob.go
- site/static/examples/multikueue/create-multikueue-kubeconfig.sh
- test/e2e/multikueue/e2e_test.go
- test/e2e/multikueue/suite_test.go
- test/integration/controller/jobs/pytorchjob/pytorchjob_controller_test.go
- test/integration/multikueue/multikueue_test.go
- test/integration/multikueue/suite_test.go
/kind feature
The PR introduces a new MultiKueue adapter to handle PyTorchJob (Kubeflow).
We want to extend MultiKueue capabilities to satisfy the needs of early adopters.
Relates #2552
```release-note
MultiKueue: Support for the Kubeflow PyTorchJob
```
> Provide Kubeflow PyTorchJob support for MultiKueue

- cmd/experimental/kjobctl/docs/commands/kjobctl_list/kjobctl_list_job.md
- cmd/experimental/kjobctl/pkg/cmd/list/list_job.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_job_printer.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_job_test.go
- cmd/experimental/kjobctl/pkg/cmd/list/list_test.go
- cmd/experimental/kjobctl/test/integration/kjobctl/list_test.go
/kind feature
Add a localqueue filter to the list job command on kjobctl.
Fixes #
```release-note
NONE
```
> [kjobctl] Add a localqueue filter to the list job command.

- hack/push-chart.sh
/kind cleanup
Fail push-chart.sh on first error.
Fixes #
```release-note
NONE
```
> Fail push-chart.sh on first error.

- charts/kueue/templates/rbac/role.yaml
- config/components/rbac/role.yaml
- pkg/controller/jobframework/validation.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_controller_test.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter.go
- pkg/controller/jobs/kubeflow/jobs/xgboostjob/xgboostjob_multikueue_adapter_test.go
- pkg/util/testingjobs/xgboostjob/wrappers.go
- site/static/examples/multikueue/create-multikueue-kubeconfig.sh
- test/e2e/multikueue/e2e_test.go
- test/e2e/multikueue/suite_test.go
- test/integration/controller/jobs/xgboostjob/xgboostjob_controller_test.go
- test/integration/multikueue/multikueue_test.go
- test/integration/multikueue/suite_test.go
/kind feature
The PR introduces a new MultiKueue adapter to handle XGBoostJob (Kubeflow).
We want to extend MultiKueue capabilities to satisfy the needs of early adopters.
Relates #2552
```release-note
MultiKueue: Support for the Kubeflow XGBoostJob
```
> Provide Kubeflow XGBoostJob support for MultiKueue

- site/content/en/docs/concepts/preemption.md
Update classic preemption candidates selection description.
Fixes #2681
```release-note
None
```
> [site] Update classic preemption candidates selection description.

- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobframework/integrationmanager_test.go
- pkg/controller/jobframework/setup.go
/kind feature
Adds a way to specify dependencies between job integrations.
Needed by #2717 
```release-note
Added a way to specify dependencies between job integrations.
```
> [jobframework] Add integration's framework dependencies.

- pkg/scheduler/preemption/preemption.go
/kind cleanup
Preparation for #2720
- Rename `resPerFlv` and`wlReq`
- Delete type alias for `resourcesPerFlavor`
- Update `fairPreemptions` to take `workload.Info` by value, for consistency with `GetTargets`
- Change a few function signatures to simplify data flow
- Simplify a few logical expressions
```release-note
NONE
```
> Cleanup preemption.go

- pkg/scheduler/scheduler.go
/kind bug
We don't check `RepresentativeMode` before attempting preemption in the `Partial Admission` path. This may result in a panic, if we enter the preemption path and find some targets.
In the existing unit tests, we exit [here](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/preemption/preemption.go#L110-L112), before encountering a panic [here](https://github.com/kubernetes-sigs/kueue/blob/00111d9aada59e1a6d8d90b9847cf7451bc5be76/pkg/scheduler/preemption/preemption.go#L116). See #2799 for more detail.
Related to #2799. Leaving that issue open, as related tests need to be updated
```release-note
NONE
```
> [Partial Admission] Check Mode before attempting Preemption

- hack/compare-performance.sh
/kind feature
Add a script that can be used to run `make run-performance-scheduler` on two git revisions, for **N** times and print out a summary for each iteration.
Running it like:
```bash
./hack/compare-performance.sh 27468c60 e8d2ff59 5
```
will:
- checkout 27468c60
- run `make run-performance-scheduler` 
- checkout e8d2ff59
- run `make run-performance-scheduler` 
- print a partial summary like
```bash
**********************
After iteration 1
Stats (csv):
run,rev,maxrss,sysMs,userMs,wallMs,mCPU
1,27468c60,457212,10914,63022,345534,213.9760486667014
1,e8d2ff59,452212,12751,66912,359273,221.73389038419253
Summary (csv):
run,rev,largeMsToAdm,mediumMsToAdm,smallMsToAdm,largeEvictions,mediumEvictions,smallEvictions,resUsage
1,27468c60,7450,76610,214689,0,0,0,58.885 …
```
> [hack] Add compare performance script

- apis/kueue/v1beta1/workload_types.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- test/integration/scheduler/preemption_test.go
/kind cleanup
1. for consistency - reasons for all other conditions (for example WorkloadEvicted) are in the API package
2. to enable Kueue to make decisions based on the conditions from every package. In particular, when working on https://github.com/kubernetes-sigs/kueue/pull/2807 I consider to use the reclaimWhileBorrowing reason
Fixes #
I left HumanReadablePreemptionReasons, because this is used to build messages. Kueue should not make decisions based on messages, and most messages are not part of the API packages anyway.
```release-note
NONE
```
> Move declaration of the Preempted reasons to API pkg

- test/e2e/singlecluster/visibility_test.go
/kind bug
/kind flake
Increase the timeout for waiting for pods to be running to fix "Kueue visibility server when There are pending workloads due to capacity maxed by the admitted job Should allow fetching information about pending workloads in LocalQueue" e2e test.
Fixes #2822
```release-note
NONE
```
> Increase the timeout for waiting for pods to be running.

- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_oracle.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind bug
We update `FlavorSelector` to simulate preemption, to determine if a workload can reclaim capacity from its Cohort in one Flavor, rather than preempting its workloads in another Flavor. This matches behavior in the single Flavor case, where a ClusterQueue prioritizes preempting workloads in its Cohort, before preempting its own workloads.
Fixes #2720
```release-note
Update Flavor selection logic to prefer Flavors which allow reclamation of lent nominal quota, over Flavors which require preempting workloads within the ClusterQueue. This matches the behavior in the single Flavor case.
```
> Prefer Reclamation over Priority Based Preemption

- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- test/integration/scheduler/preemption_test.go
To prevent infinite preemption loop when borrowWithinCohort is used with `PrioritySortingWithingCohort=false`
Fixes #2821
In the scenario described in #2821 when `PrioritySortingWithingCohort=false` we re-admit repeatedly workload-A (lower priority) which blocks the admission of the Workload-B2 (higher priority). 
Ideally, we would like workload-B to be scheduled, which would break the cycle. Workload-B2 would not get preempted  by Workload-A.
The code that is important for relative prioritization of the two workloads is [here](https://github.com/kubernetes-sigs/kueue/blob/21e9ac330cb6624f555668ccaca347a61c1f81ac/pkg/scheduler/scheduler.go#L625-L654):
1. [L630-634] both `Workload-A` and `Workload-B2` need to borrow to get admitted
2. [L637-639] fair sharing is not configured here, so this …
> Fix using PrioritySortingWithinCohort=false and borrowWithinCohort

- apis/kueue/v1beta1/workload_types.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler_test.go
- pkg/workload/workload.go
- test/integration/scheduler/preemption_test.go
/kind bug
/kind cleanup
Cherry-pick https://github.com/kubernetes-sigs/kueue/pull/2807 to 0.8
There are commits from two PRs:
- preparatory PR https://github.com/kubernetes-sigs/kueue/pull/2814/
- actual fix: https://github.com/kubernetes-sigs/kueue/pull/2807
```release-note
Prevent infinite preemption loop when PrioritySortingWithingCohort=false
is used together with borrowWithinCohort.
```
> Cherry-pick of #2807 to 0.8

- .github/ISSUE_TEMPLATE/NEW_RELEASE.md
- Makefile
- Makefile-test.mk
- charts/kueue/README.md
- charts/kueue/values.yaml
- cloudbuild.yaml
- cmd/importer/README.md
- cmd/importer/run-in-cluster/kustomization.yaml
- config/components/manager/kustomization.yaml
- hack/dump_cache.sh
- hack/push-chart.sh
Cherry pick of #2476 on release-0.8.
#2476: Publish images to new staging registry
```release-note
Publish images via artifact registry
```
> Automated cherry pick of #2476: Publish images to new staging registry

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_snapshot.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/hierarchy/manager.go
- pkg/hierarchy/manager_test.go
- pkg/hierarchy/wired_clusterqueue.go
- pkg/hierarchy/wired_cohort.go
- pkg/queue/cluster_queue.go
- pkg/queue/cohort.go
- pkg/queue/dumper.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
/kind feature
We define `hierarchy.Manager`, which manages `ClusterQueues`, `Cohorts`, and their edges. Currently, we duplicate logic which creates and updates edges, and creates/deletes implicit Cohorts (those without backing API objects). This change moves all of the relevant logic into a new package, `hierarchy`.
This change is important for the implementation of #79. With Hierarchical Cohorts, we have to account for both implicit and explicit Cohorts, in addition to new edges (Cohorts as parents and children of other Cohorts).
Additionally, the `hierarchy` package does not export the edges' fields, preventing unintentional manipulation outside of the `hierarchy.Manager` interface.
```release-note
NONE
```
> Define hierarchy.Manager

- Makefile
/kind cleanup
We need to make sure all generated files are added to git.
Fixes #
[Here](https://github.com/kubernetes-sigs/kueue/pull/2280#discussion_r1720126884) is discussion about that.
```release-note
NONE
```
> Verifying that new generated files are added to git.

- cmd/experimental/kjobctl/pkg/cmd/completion/completion.go
- cmd/experimental/kjobctl/pkg/cmd/completion/completion_test.go
/kind cleanup
Cover completion with tests on kjobctl.
Fixes #
```release-note
NONE
```
> [kjobctl] Cover completion with tests.

- pkg/features/kube_features.go
- site/content/en/docs/installation/_index.md
/kind feature
Graduate MultiplePreemptions feature to beta and enable it by default.
```release-note
Graduated MultiplePreemptions to Beta and enabled by default.
```
> Graduate MultiplePreemptions to Beta

- test/e2e/multikueue/e2e_test.go
/kind bug
Skips flaky test for e2e MultiKueue XGBoost, due to transitioning bug in training-operator.
Found here: https://github.com/kubeflow/training-operator/issues/1711
Part of #2838 
```release-note
NONE
```
> Skip flaky e2e MultiKueue test for XGBoost

- cmd/experimental/podtaintstolerations/test/util/pod.go
- pkg/constants/constants.go
- pkg/controller/admissionchecks/provisioning/controller.go
- pkg/controller/admissionchecks/provisioning/controller_test.go
- pkg/controller/jobs/pod/pod_controller_test.go
- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- pkg/util/testingjobs/pod/wrappers.go
- test/integration/controller/admissionchecks/provisioning/provisioning_test.go
- test/integration/controller/jobs/pod/pod_controller_test.go
- test/integration/controller/jobs/pod/pod_webhook_test.go
- test/integration/importer/importer_test.go
/kind feature
Adds the `kueue.x-k8s.io/managed` label to PodTemplates created by Kueue
Fixes #2856 
```release-note
Label `kueue.x-k8s.io/managed` is now added to PodTemplates created via ProvisioningRequest by Kueue
```
> Add the `kueue.x-k8s.io/managed` label to PodTemplates created by Kueue

- pkg/cache/cache.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_snapshot.go
- pkg/cache/clusterqueue_test.go
- pkg/hierarchy/manager.go
- pkg/hierarchy/manager_test.go
- pkg/hierarchy/wired_clusterqueue.go
- pkg/queue/manager.go
/kind cleanup
As we implement #79, we define algorithms which work recursively on both `ClusterQueues` and `Cohorts`. `Cohorts` will have a `Parent`, as `Cohort.HasCohort()` is confusing.
This rename will allow algorithms to work on both types.
```release-note
NONE
```
> Rename Cohort to Parent

- site/content/en/docs/tasks/run/jobs.md
I updated the outdated `PartialAdmission` feature state in the documentation.
The `PartialAdmission` has already been moved to the beta stage in v0.5.
Fixes #
```release-note
NONE
```
> Doc: Update outdated PartialAdmission feature state

- cmd/kueue/main.go
- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobframework/integrationmanager_test.go
- pkg/controller/jobframework/setup.go
- pkg/controller/jobframework/setup_test.go
/kind feature
Add function to wait for API availability using the RESTMapper in controller manager.
This PR checks for availability of JobFramework integrations in the Kubernetes cluster before executing the action().
The function utilises the RESTMapper from the controller-runtime manager to verify the existence of the CRD by its GroupVersionKind (GVK). If one of the CRDs become available, the respective controller and webhook will start.
The user/dev will no longer be required to restart the Kueue pod to allow for integration on new CRDs available.
No restarts on the Kueue pod is performed.
Fixes #2414 
```release-note
Detect and enable support for job CRDs installed after Kueue starts.
```
> Start JobFramework controller and webhook on new CRDs availability

- test/e2e/singlecluster/pod_test.go
/kind bug
/kind flake
Increase timeout for pod failing after pod deletion on e2e test. It is need because sometimes we have failed test on this case. It is happens because for some reason Kubelet does not have time to update status to PodFailed after deletion.
Fixes #2885
```release-note
NONE
```
> Increase timeout for pod failing after pod deletion on e2e test.

- pkg/controller/jobframework/reconciler.go
/kind bug
It is possible when two reconciliations for the same Job happen in rapid succession for the earlier call of ensureOneWorkload to not find a Workload instance while the subsequent call to handleJobWithNoWorkload fails in Create with an already exists error. This PR special cases this error condition to requeue without an ERROR level log, as it is not actually an error.
We see error being logged during the processing of 5% of all created AppWrappers in our test suite.  
As such, the error is frequently occurring  enough that we think it is worth surpassing the error-level log
message that the controller-runtime will generate if we simply return the error and let it requeue due to non-nil error.
Fixes #
```release-note
NONE
```
> Requeue without error if handleJobWithNoWorkload finds a Workload

- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
/kind bug
/kind flake
Use clock instead time for Preemptor to avoid flakiness on unit tests.
Fixes #2876
```release-note
NONE
```
> Use clock instead time for Preemptor.

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
- pkg/hierarchy/clusterqueue.go
- pkg/hierarchy/cohort.go
- pkg/hierarchy/manager.go
- pkg/hierarchy/manager_test.go
- pkg/queue/cluster_queue.go
- pkg/queue/cohort.go
- pkg/queue/manager.go
- pkg/queue/manager_test.go
/kind cleanup
Address @alculquicondor comments in #2824, and update the names to be more consistent
- Delete the name Wired from `WiredClusterQueue` and `WiredCohort`
- Define (unexported) methods for accessing state of these types inside the hierarchy package
- Consistently refer to Cohort as C in generic type parameter
- Rename Members to childCqs, as soon there will be childCohorts
- Rename Cohort to Parent
- Rename cohortFactory to newCohort
```release-note
NONE
```
> Rename/Refactor Hierarchy Package

- pkg/cache/clusterqueue.go
- pkg/cache/snapshot.go
/kind bug
/kind flake
We need to perform a deep clone of `ResourceGroups` instead of a shallow copy when taking a snapshot of `clusterQueue` to prevent race conditions.
Fixes #2901
When running `make test-integration`, sometimes happens a race condition in the `LabelKeys`  within the `ResourceGroups` structure. 
Write on clusterQueue:
```
WARNING: DATA RACE
Write at 0x00c000c6a680 by goroutine 424:
sigs.k8s.io/kueue/pkg/cache.(*clusterQueue).updateLabelKeys()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/cache/clusterqueue.go:336 +0x215
sigs.k8s.io/kueue/pkg/cache.(*clusterQueue).UpdateWithFlavors()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/cache/clusterqueue.go:312 +0x33
sigs.k8s.io/kueue/pkg/cache.(*Cache).updateClusterQueues()
/home/prow/go/src/sigs.k8s.io/kueue/pkg/cache/cache.go:205 +0x1a5 …
```
> Deep clone ResourceGroups instead shallow copy on snapshot clusterQueue.

- apis/kueue/v1beta1/clusterqueue_types.go
- charts/kueue/templates/crd/kueue.x-k8s.io_clusterqueues.yaml
- charts/kueue/templates/crd/kueue.x-k8s.io_cohorts.yaml
- config/components/crd/bases/kueue.x-k8s.io_clusterqueues.yaml
- config/components/crd/bases/kueue.x-k8s.io_cohorts.yaml
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/snapshot_test.go
- pkg/features/kube_features.go
- pkg/metrics/metrics_test.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler_test.go
- pkg/webhooks/clusterqueue_webhook_test.go
- site/content/en/docs/concepts/cluster_queue.md
- site/content/en/docs/installation/_index.md
- site/content/en/docs/reference/kueue.v1beta1.md
- test/integration/scheduler/preemption_test.go
- test/integration/scheduler/scheduler_test.go
/kind feature
Graduate LendingLimit feature to beta and enable it by default.
Feature flag is now enabled by default also in the tests. Added new test cases to verify a cases when `LendingLimit` field is set without a feature flag enabled.
```release-note
Graduated LendingLimit to Beta and enabled by default.
```
> Graduate LendingLimit to Beta

- pkg/controller/core/resourceflavor_controller.go
/kind cleanup
Function name didn't match semantics. There was no bug, as we only call this function once.
The other option is to rename this to SetUpdateWatcher (additionally AdmissionCheckController, which has a similar method but only uses it once)
```release-note
NONE
```
> Fix ResourceFlavorReconciler.AddUpdateWatcher

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/clusterqueue_snapshot.go
- pkg/cache/clusterqueue_test.go
- pkg/cache/cohort_snapshot.go
- pkg/cache/resource.go
- pkg/cache/resource_node.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/hierarchy/cohort.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_oracle.go
- pkg/scheduler/scheduler.go
/kind feature
We define `cache.ResourceNode`, which is the new way of accounting capacity
and usage that is compatible with Hierarchical Cohorts. See #79
We define `SubtreeQuota`, which is the capacity available to a certain
node in the tree, respecting `LendingLimits` of its children.
The notion of `Usage` remains the same: `Usage` past
`GuaranteedQuota` is bubbled up the parent.
We delete the field `GuaranteedQuota`, as it can be derived
from `SubtreeQuota` and `LendingLimit`.
```release-note
NONE
```
> Update ClusterQueue and Cohort Resource Accounting for Hierarchical Cohorts

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/queue/manager.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind feature
We now allow multiple preemptions within a cohort to happen in a cycle if they have non-overlapping preemption targets.
However, it was immediately obvious how to track if this was working.
Adding a metric allows to check that less preemptions get skipped than before. It can also be used to track whether a CQ is getting their preemptions continuously skipped, so it can be used in alerts.
Follow up to #2641
I also considered reporting skips that don't require preemptions, but those skips should require preemptions in the next iteration, so they will be covered. And preemption seems to be the primary pain point.
I also considered using a counter, instead of a gauge, but, because admission cycles are not capped, the number could grow too fast.
```release-note
Add gauge metric …
```
> Add gauge for skipped preemptions within a cycle

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/queue/manager.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Cherry pick of #2919 on release-0.8.
#2919: Add gauge for skipped preemptions within a cycle
```release-note
Add gauge metric admission_cycle_preemption_skips that reports the number of Workloads in a ClusterQueue
that got preemptions candidates, but had to be skipped in the last cycle.
```
> Automated cherry pick of #2919: Add gauge for skipped preemptions within a cycle

- test/integration/controller/jobs/job/job_controller_test.go
/kind flake
Wrap the job Update with Eventually to avoid flakiness.
Fixes #2902
```release-note
NONE
```
> [flaky] Wrap Update with Eventually to avoid flakiness

- cmd/experimental/kjobctl/pkg/cmd/describe/describe.go
- cmd/experimental/kjobctl/pkg/cmd/describe/describe_test.go
/kind feature
Describe only kjobctl owned objects on describe command.
Fixes #
Unfortunately, filtering by labels isn't possible when searching for resources by name. However, we can apply filters on the client side.
```release-note
NONE
```
> [kjobctl] Describe only kjobctl owned objects.

- .golangci.yaml
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/clusterqueue.go
- pkg/cache/cohort.go
- pkg/cache/resource.go
- pkg/cache/resource_node.go
- pkg/cache/snapshot_test.go
- pkg/hierarchy/cohort.go
- pkg/hierarchy/manager.go
- pkg/hierarchy/manager_test.go
- pkg/util/testing/wrappers.go
/kind feature
Update cache to support Cohorts with resources. Update hierarchy to support explicit Cohorts. Part of #79
commit 1 : move files and refactor parsing
commit 2: support Cohorts which provide resources in `cache`. support explicit Cohorts in `hierarchy`
Users cannot use this functionality until we wire up reconciler and webhook. In the interest of keeping PRs small, I will publish those in separate PRs.
```release-note
NONE
```
> Support Cohorts with Resources in cache/hierarchy packages

- pkg/controller/jobs/pod/pod_webhook.go
- pkg/controller/jobs/pod/pod_webhook_test.go
- test/integration/controller/jobs/deployment/deployment_webhook_test.go
/kind cleanup
The PodInterationOptions are optional parameters. So, we should allow an empty of the parameters.
This is not a bug since even if there is not this commit, user can specify an empty PodIntegrationOptons in the Config API:
https://github.com/kubernetes-sigs/kueue/blob/47f79fbdd5b74cc5ab1d44a26c66482af3e674ca/cmd/kueue/main.go#L277
Followup of #2813
```release-note
NONE
```
> Allow an empty PodIntegrationOptions

- Dockerfile
/kind cleanup
Resolve InvalidDefaultArgInFrom build check warnings.
Fixes #
We have warnings:
```
=> WARN: InvalidDefaultArgInFrom: Default value for ARG ${BUILDER_IMAGE} results in empty or invalid base image name (line 4)                                                0.0s
=> WARN: InvalidDefaultArgInFrom: Default value for ARG ${BASE_IMAGE} results in empty or invalid base image name (line 17)                                                  0.0s
```
on execute `make kind-image-build`.
As mentioned on docs [here](https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/) we should set default value for args that is used on the `FROM`.
```release-note
NONE
```
> Resolve InvalidDefaultArgInFrom build check warnings.

- cmd/kueuectl/app/list/list_test.go
- cmd/kueuectl/app/list/list_workload_printer.go
- cmd/kueuectl/app/list/list_workload_test.go
- test/integration/kueuectl/list_test.go
/kind feature
Add EXEC TIME column on kueuectl list workload command.
Fixes #2972
```release-note
CLI: Added EXEC TIME column on kueuectl list workload command.
```
> [kueuectl] Add EXEC TIME column on list workload command.

- pkg/cache/clusterqueue_snapshot.go
- pkg/cache/cohort_snapshot.go
- pkg/cache/snapshot.go
- pkg/cache/snapshot_test.go
- pkg/scheduler/flavorassigner/flavorassigner.go
- pkg/scheduler/flavorassigner/flavorassigner_test.go
- pkg/scheduler/preemption/preemption.go
- pkg/scheduler/preemption/preemption_test.go
- pkg/scheduler/scheduler.go
/kind cleanup
This change simplifies edge management in the Snapshot. This will allow us, in a simple manner, to snapshot and create edges between HierarchicalCohorts (#79) in a subsequent PR.
Hide ws diff when reviewing snapshot_test.go
```release-note
NONE
```
> Update Snapshoting to use hierarchy.Manager

- cmd/kueue/main.go
- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobframework/setup.go
- pkg/controller/jobframework/setup_test.go
Cherry pick of #2574 on release-0.8.
#2574: Start Controller and Webhook on new CRDs availability
```release-note
Detect and enable support for job CRDs installed after Kueue starts.
```
> Automated cherry pick of #2574: Start Controller and Webhook on new CRDs availability

- config/components/crd/kustomization.yaml
/kind bug
[config] Add cohorts CRD in the kustomization. (missed in #2693)
Fixes #2981
```release-note
None
```
> [config] Add cohorts CRD in the kustomization

- test/e2e/singlecluster/visibility_test.go
Increase the timeout for waiting for zero pending workloads after the second workload is admitted on "There are pending workloads due to capacity maxed by the admitted job" e2e test.
Fixes #2990
```release-note
NONE
```
> Increase the timeout for waiting for zero pending workloads.

- charts/kueue/templates/webhook/webhook.yaml
- cmd/kueuectl/app/list/list_pods.go
- config/components/webhook/manifests.yaml
- pkg/controller/jobframework/integrationmanager.go
- pkg/controller/jobs/deployment/deployment_controller.go
- pkg/controller/jobs/jobs.go
/kind bug
This PR fixes deployment webhook to allow for create/update of deployments after kueue is installed
Fixes #2987
Testing done:
1. enable the pod controller with following configuration option and applied the patch
```
$ cat config/components/manager/controller_manager_config.yaml
...
- "pod"
- "deployment"
podOptions:
namespaceSelector:
matchExpressions:
- key: kubernetes.io/metadata.name
operator: NotIn
values: [ kube-system, kueue-system ]
...
$  kubectl patch -n kueue-system deployment kueue-controller-manager --type='json' -p='[
{
"op": "add",
"path": "/spec/template/spec/containers/0/args/-",
"value": "--feature-gates=VisibilityOnDemand=true"
}
]'
deployment.apps/kueue-controller-manager patched
```
2. disabled the pod controller and applied the patch
```
$ cat …
```
> import deployment package in jobs.go to register the deployment webhook

- pkg/cache/cache.go
- pkg/cache/snapshot.go
- pkg/hierarchy/cohort.go
- pkg/hierarchy/manager.go
- pkg/hierarchy/manager_test.go
/kind feature
This will be used by `cache` and `queue` packages as part of HierarchicalCohorts (#79) implementation.
Sending this out as a separate PR to keep PR size small.
```release-note
NONE
```
> Support Hierarchical Cohorts in hierarchy.Manager

- CHANGELOG/CHANGELOG-0.8.md
- Makefile
- README.md
- SECURITY-INSIGHTS.yaml
- charts/kueue/Chart.yaml
- site/hugo.toml
Cherry pick of #3007 on website.
#3007: Update latest version to v0.8.1
```release-note
NONE
```
> Automated cherry pick of #3007: Update latest version to v0.8.1

- site/content/en/docs/concepts/cluster_queue.md
/kind cleanup
Use Note instead Warning on the LendingLimit is enabled by default info.
Fixes #
```release-note
NONE
```
> Use Note instead Warning on the LendingLimit is enabled by default info.

- Makefile-test.mk
- hack/performance-retry.sh
/kind flake
Retry running the performance scheduler tests on failure to avoid infra related false positive. 
Fixes #2970
```release-note
None
```
> [test][scalability] Retry performance test on failure

- test/e2e/multikueue/e2e_test.go
/kind bug
/kind flake
Fix the flake test "End To End MultiKueue Suite: kindest/node:v1.30.0: [It] MultiKueue when Creating a multikueue admission check Should run a MPIJob on worker if admitted".
Fixes #3028
```release-note
NONE
```
> Fix Should run a MPIJob on worker if admitted flaky test.
